[#atip-lifecycle]
== ライフサイクルアクション
:revdate: 2025-10-17
:revnumber: 3.4
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

このセクションでは、SUSE Telco Cloud経由でデプロイされたクラスターのライフサイクル管理について説明します。

=== 管理クラスターのアップグレード

管理クラスターのアップグレードについては、`Day 2` <<day2-mgmt-cluster,管理クラスター>>のドキュメントで説明されています。

[#atip-lifecycle-downstream]
=== ダウンストリームクラスターのアップグレード

ダウンストリームのクラスターのアップグレードには、いくつかのコンポーネントの更新が含まれます。以下のセクションでは、各コンポーネントのアップグレードプロセスについて説明します。

*オペレーティングシステムのアップグレード*

このプロセスについては、新しいオペレーティングシステムバージョンで新しいイメージをビルドするために、以下の<<eib-edge-image-connected,リファレンス>>を確認してください。
`EIB`によって生成されたこの新しいイメージを使用すると、次のプロビジョニングフェーズで提供された新しいオペレーティングバージョンが使用されます。
次のステップでは、新しいイメージを使用してノードをアップグレードします。

*RKE2クラスターのアップグレード*

自動ワークフローを使用して`RKE2`クラスターをアップグレードするために必要な変更は以下の通りです。

* 以下の<<single-node-provision,セクション>>に示す`RKE2ControlPlane`のブロック`capi-provisioning-example.yaml`を変更します。

  ** 目的の`rolloutStrategy`を指定します。
  ** `RKE2`クラスターのバージョンを、`$\{RKE2_NEW_VERSION\}`を置き換える新しいバージョンに変更します。

[,yaml]
----
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: RKE2ControlPlane
metadata:
  name: single-node-cluster
  namespace: default
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: Metal3MachineTemplate
    name: single-node-cluster-controlplane
  version: ${RKE2_NEW_VERSION}
  replicas: 1
  rolloutStrategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 0
  serverConfig:
    cni: cilium
  rolloutStrategy:
    rollingUpdate:
      maxSurge: 0
  registrationMethod: "control-plane-endpoint"
  agentConfig:
    format: ignition
    additionalUserData:
      config: |
        variant: fcos
        version: 1.4.0
        systemd:
          units:
            - name: rke2-preinstall.service
              enabled: true
              contents: |
                [Unit]
                Description=rke2-preinstall
                Wants=network-online.target
                Before=rke2-install.service
                ConditionPathExists=!/run/cluster-api/bootstrap-success.complete
                [Service]
                Type=oneshot
                User=root
                ExecStartPre=/bin/sh -c "mount -L config-2 /mnt"
                ExecStart=/bin/sh -c "sed -i \"s/BAREMETALHOST_UUID/$(jq -r .uuid /mnt/openstack/latest/meta_data.json)/\" /etc/rancher/rke2/config.yaml"
                ExecStart=/bin/sh -c "echo \"node-name: $(jq -r .name /mnt/openstack/latest/meta_data.json)\" >> /etc/rancher/rke2/config.yaml"
                ExecStartPost=/bin/sh -c "umount /mnt"
                [Install]
                WantedBy=multi-user.target
    kubelet:
      extraArgs:
        - provider-id=metal3://BAREMETALHOST_UUID
    nodeName: "localhost.localdomain"
----

* 以下の<<single-node-provision,セクション>>に示す`Metal3MachineTemplate`のブロック`capi-provisioning-example.yaml`を変更します。

  ** 前のステップで生成された新しいバージョンに合わせて、イメージ名とチェックサムを変更します。
  ** 新しいノードの作成を回避するために、ディレクティブ`nodeReuse`を`true`に追加します。
  ** ノードの自動クリーンアップを有効にするには、`automatedCleaningMode` を `metadata` に追加します。

[,yaml]
----
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: single-node-cluster-controlplane
  namespace: default
spec:
  nodeReuse: True
  template:
    spec:
      automatedCleaningMode: metadata
      dataTemplate:
        name: single-node-cluster-controlplane-template
      hostSelector:
        matchLabels:
          cluster-role: control-plane
      image:
        checksum: http://imagecache.local:8080/${NEW_IMAGE_GENERATED}.sha256
        checksumType: sha256
        format: raw
        url: http://imagecache.local:8080/${NEW_IMAGE_GENERATED}.raw
----

これらの変更を行った後、次のコマンドを使用して `capi-provisioning-example.yaml` ファイルをクラスターに適用できます。

[,shell]
----
kubectl apply -f capi-provisioning-example.yaml
----

