[#release-notes-abstract]
= 抽象データ型
:revdate: 2026-06-29
:revnumber: 3.6
:page-revdate: {revdate}
ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

{product} 3.6は、エッジにおけるインフラストラクチャおよびクラウドネイティブアプリケーションのデプロイという独自の課題に対処するための、緊密に統合され、包括的に検証されたエンドツーエンドのソリューションです。その主な目的は、初期デプロイメントのイメージ構築、ノードのプロビジョニングとオンボーディング、アプリケーションのデプロイ、監視、ライフサイクル管理にわたって、独自の設計思想を持ちながらも非常に柔軟で、拡張性が高く、安全なプラットフォームを提供することです。

このソリューションは、お客様の要件や期待が大きく異なるため、「万能な」エッジプラットフォームは存在しないという考えに基づいて設計されています。エッジデプロイメントは、大規模なスケーラビリティ、制限されたネットワーク可用性、物理的なスペースの制約、新しいセキュリティの脅威と攻撃ベクトル、ハードウェアアーキテクチャとシステムリソースの多様性、レガシーインフラストラクチャおよびアプリケーションとのデプロイとインターフェースの要件、そして寿命が長い顧客ソリューションなど、最も困難な問題のいくつかを解決し、継続的に進化させることを私たちに求めています。

{product}は、安全で安定した認定済みのSUSE Linuxプラットフォームを提供してきた30年の歴史と、Rancherポートフォリオによる拡張性が高く機能豊富なKubernetes管理を提供してきた経験の両方と一貫して、ゼロから最高クラスのオープンソースソフトウェアに基づいて構築されています。{product}は、これらの機能を基盤として、小売、医療、輸送、物流、電気通信、スマートマニュファクチャリング、産業用IoTなど、幅広い市場セグメントの要件に対処できる機能を提供します。

{product}の製品サポートライフサイクルの更新に関する詳細については、link:https://www.suse.com/lifecycle/#suse-edge-36[Product Support Lifecycle]を参照してください。

NOTE: SUSE Telco CloudはSUSE Edgeの派生製品であり、電気通信のユースケースで見られる要件にプラットフォームが対応できるようにするための追加の最適化とコンポーネントを備えています。

= バージョン情報

これらのリリースノートは、明示的に指定および説明されている場合を除き、すべてのアーキテクチャで同一であり、最新バージョンは、他のすべてのSUSE製品のリリースノートとともに、オンラインの https://www.suse.com/releasenotes[https://www.suse.com/releasenotes]で常に入手可能です。

項目は一度だけリストされますが、重要であり、複数のセクションに該当する場合は、複数の場所で参照されることがあります。リリースノートには通常、2つの連続するリリースの間に行われた変更のみが記載されます。以前の製品バージョンのリリースノートからの重要な項目が繰り返される場合があります。これらの項目を識別しやすくするために、その旨を記載した注記が含まれています。

ただし、繰り返される項目は便宜上提供されているに過ぎません。したがって、1つ以上のリリースをスキップする場合は、スキップしたリリースのリリースノートも確認してください。現在のリリースのリリースノートのみを読んでいると、システム動作に影響を与える可能性のある重要な変更を見逃す可能性があります。{product}のバージョンはx.y.zとして定義されます。ここで「x」はメジャーバージョン、「y」はマイナーバージョン、「z」はパッチバージョン（「zストリーム」とも呼ばれます）を示します。{product}の製品ライフサイクルは、特定のマイナーリリースに基づいて定義されます（例:）。「3.6」ですが、そのライフサイクルを通じて後続のパッチアップデートとともに出荷されます（例:）。"3.6.1".

NOTE: {product}のzストリームリリースは、バージョン管理されたスタックとして緊密に統合され、徹底的にテストされています。上記以外のバージョンへの個々のコンポーネントのアップグレードは、システムダウンタイムを引き起こす可能性があります。テストされていない構成でEdgeクラスターを実行することは可能ですが、推奨はされず、サポートチャネルを通じた解決に時間がかかる場合があります。

[#release-notes-3-6-1]
= リリース 3.6.1

提供開始日:2026年6月26日

フルサポート終了日:2026年11月27日

メンテナンスサポート終了日:2028年5月27日

EOL:2028年5月28日

まとめ:{product} 3.6.1は、{product} 3.6リリースストリームにおける最初のz-streamリリースです。

== 新機能

* Kubernetes 1.35.4およびRancher Prime 2.14.2に更新されました
* SUSE Security (NeuVector) 5.5.2に更新されました https://open-docs.neuvector.com/releasenotes/5x[NeuVector リリースノート]
* SUSE Storage (Longhorn) 1.11.2に更新されました https://longhorn.io/docs/1.11.1/[アップストリーム Longhorn リリースノート]
* Rancher Turtles (CAPI) 0.26.2に更新されました https://turtles.docs.rancher.com/[Rancher Turtles ドキュメント]
* Metal^3^/Ironicを0.15.0（Ironic 35.0.0.2を含む）に更新しました

== バグ修正およびセキュリティ更新

* Kubernetes 1.35.4には、いくつかのバグ修正とセキュリティ更新が含まれています https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.35.md[Kubernetes Changelog]
* Rancher Prime 2.14.2には、いくつかのバグ修正が含まれています https://github.com/rancher/rancher/releases/tag/v2.14.1[アップストリーム Rancher リリースノート]
* SUSE Storage (Longhorn) 1.11.2には、いくつかのバグ修正が含まれています https://github.com/longhorn/longhorn/releases/tag/v1.11.1[アップストリーム Longhorn バグ修正]
* NeuVector 5.5.2には、新機能といくつかのバグ修正が含まれています https://open-docs.neuvector.com/releasenotes/5x[NeuVector リリースノート]
* Metal^3^/Ironicのアップデートでは、以下を含むいくつかのバグおよびセキュリティの問題が修正されています。
** https://www.cve.org/CVERecord?id=CVE-2026-44919[CVE-2026-44919]
** https://www.cve.org/CVERecord?id=CVE-2026-46447[CVE-2026-46447]
** https://www.cve.org/CVERecord?id=CVE-2026-48681[CVE-2026-48681]
** https://www.cve.org/CVERecord?id=CVE-2026-44917[CVE-2026-44917]
** https://www.cve.org/CVERecord?id=CVE-2026-43003[CVE-2026-43003]
** https://www.cve.org/CVERecord?id=CVE-2026-50589[CVE-2026-50589]

== 既知の問題

[WARNING]
====
新しいクラスターをデプロイする場合は、<<guides-kiwi-builder-images>> に従って最初に新しいイメージをビルドしてください。 これは、イメージに最新のセキュリティ修正およびバグ修正が含まれていることを確認するために、管理クラスターおよびダウンストリームクラスターに対して推奨されます。
====

* Edge Image Builderを介してデプロイする場合、`HelmChartConfigs` マニフェストを `kubernetes/manifests` 設定ディレクトリに配置すると失敗する可能性があります。代わりに、EIBのos-filesインターフェースを使用して、`HelmChartConfigs` を `/var/lib/rancher/{rke2/k3s}/server/manifests/` に配置することを推奨します。
ifeval::["{flavor}" == "telco"]
例については、<<mgmt-cluster-directory-structure>>を参照してください。
endif::[]
これを行わないと、 https://github.com/rancher/rke2/issues/8357[#8357 RKE2 issue]で説明されているように、初期起動時にノードが `NotReady` 状態のままになる可能性があります。

* RKE2/K3s 1.34および1.35バージョンでは、CNI設定の保存に使用されるディレクトリ `/etc/cni` が、`overlayfs` に関連する特定の条件により、そこに書き込まれるファイルに関する通知を `containerd` にトリガーしない場合があります（ https://github.com/rancher/rke2/issues/8356[#8356 RKE2 issue]を参照）。その結果、RKE2/K3sのデプロイメントがCNIの起動待ちでスタックし、RKE2/K3sノードが `NotReady` 状態のままになります。これは、ノードレベルで `kubectl describe node <affected_node>` を使用して確認できます。

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

回避策として、RKE2の起動前に `/etc/cni` ディレクトリにtmpfsボリュームをマウントすることができます。これにより、containerdが通知を見逃す原因となるoverlayfsの使用を回避でき、ノードが再起動され、ポッドのinitcontainersが再度実行されるたびに設定が書き直されるはずです。EIBを使用している場合、これは`04-tmpfs-cni.sh`スクリプトが`custom/scripts`ディレクトリ内にあり（ https://github.com/suse-edge/edge-image-builder/blob/release-1.3/docs/building-images.md#custom[こちら]で説明）、次のようになります。

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* 現段階では、synce4lを介したSyncEおよびgpsdを介したGNSSを設定するための公式ドキュメントや例は提供されておらず、これらのトピックは今後のリリースで取り上げられる予定です。

* 一部のコンテナリポジトリは現在IPv4経由でのみアクセス可能なため、IPv6のみのダウンストリームクラスターには、管理クラスター上のローカルレジストリが必要です。

== コンポーネントのバージョン

以下の表は、3.6.1リリースを構成する個々のコンポーネントについて、バージョン、Helmチャートのバージョン（該当する場合）、およびバイナリ形式でリリースされたアーティファクトの取得元を説明しています。使用方法やデプロイメントの例については、関連するドキュメントに従ってください。

|======
| 名前 | バージョン | Helmチャートのバージョン | アーティファクトの場所 (URL/イメージ)
| SUSE Linux Micro | 6.2 (latest) | N/A | https://www.suse.com/download/sle-micro/[SUSE Linux Micro ダウンロードページ] +
| SUSE Linux Micro | 6.2 (latest) | N/A |チェックサムと署名は、 https://www.suse.com/download/sle-micro/[SUSE Linux Micro ダウンロードページ]からダウンロードできます。 +
SL-Micro.x86_64-6.2-Base-SelfInstall-GM.install.iso +
SL-Micro.x86_64-6.2-Base-RT-SelfInstall-GM.install.iso +
SL-Micro.x86_64-6.2-Base-GM.raw.xz +
SL-Micro.x86_64-6.2-Base-RT-GM.raw.xz +
| SUSE Multi-Linux Manager | 5.1 | N/A | https://www.suse.com/download/suse-manager/[SUSE Multi-Linux Manager ダウンロードページ]
s| K3s s| 1.35.4 s| N/A s| https://github.com/k3s-io/k3s/releases/tag/v1.35.4%2Bk3s1[アップストリーム K3s リリース]
s| RKE2 s| 1.35.4 s| N/A s| https://github.com/rancher/rke2/releases/tag/v1.35.4%2Brke2r1[Upstream RKE2 Release]
s| SUSE Rancher Prime s| 2.14.2 s| 2.14.2 s| https://charts.rancher.com/server-charts/prime/index.yaml[Rancher Prime Helm リポジトリ] +
\https://prime.ribs.rancher.io/rancher/v2.14.2/rancher-images.txt[Rancher 2.14.2 Container Images]
s| SUSE Storage (Longhorn) s| 1.11.2 s| 1.11.2 s| https://apps.rancher.io/applications/suse-storage[SUSE Storage Helm リポジトリ] +
\https://apps.rancher.io/applications/suse-storage/components[SUSE Storage Container Images]
s| SUSE Security (NeuVector) s| 5.5.2 s| 109.0.2+up2.10.2 s| https://charts.rancher.io/index.yaml[Rancher Charts Helm リポジトリ] +
registry.rancher.com/rancher/neuvector-controller:5.5.2 +
registry.rancher.com/rancher/neuvector-enforcer:5.5.2 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.12
s| Rancher Turtles プロバイダー (CAPI) s| 0.26.2 s| 306.0.7+up0.26.2 s| registry.suse.com/edge/3.6/rancher-turtles-providers-chart:306.0.7+up0.26.2 +
registry.rancher.com/rancher/cluster-api-controller:v1.12.2 +
registry.rancher.com/rancher/turtles:v0.26.2 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.24.3 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.24.3
s| Metal^3^s| 0.15.0 s| 306.0.29+up0.15.0 s| registry.suse.com/edge/3.6/metal3-chart:306.0.29+up0.15.0 +
registry.suse.com/edge/3.6/baremetal-operator:0.12.3.0 +
registry.suse.com/edge/3.6/ironic:35.0.0.2 +
registry.suse.com/edge/3.6/ironic-ipa-downloader:3.1.1 +
registry.suse.com/edge/3.6/ironic-python-agent:3.0.9
| MetalLB | 0.15.3 | 306.0.2+up0.15.3 | registry.suse.com/edge/3.6/metallb-chart:306.0.2+up0.15.3 +
registry.suse.com/edge/3.6/metallb-controller:v0.15.3 +
registry.suse.com/edge/3.6/metallb-speaker:v0.15.3
| Elemental | 1.9.0 | 1.9.0 | registry.suse.com/rancher/elemental-operator-chart:1.9.0 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.9.0 +
registry.suse.com/rancher/elemental-operator:1.9.0
| Elemental ダッシュボード拡張機能 | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/main/charts/elemental/3.0.1[Elemental 拡張機能 Helmチャート]
| Edge Image Builder | 1.3.3.1 | N/A | registry.suse.com/edge/3.6/edge-image-builder:1.3.3.1
| KubeVirt | 1.7.0 | 306.0.2+up0.7.0 | registry.suse.com/edge/3.6/kubevirt-chart:306.0.2+up0.7.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.7.0-150700.3.16.2
| KubeVirt ダッシュボード拡張機能 | 1.3.3 | 306.0.4+up1.3.3 | registry.suse.com/edge/3.6/kubevirt-dashboard-extension-chart:306.0.4+up1.3.3
| Containerized Data Importer (CDI) | 1.64.0 | 306.0.2+up0.7.0 | registry.suse.com/edge/3.6/cdi-chart:306.0.2+up0.7.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.64.0-150700.9.6.1
| Endpoint Copier Operator | 0.3.0 | 306.0.1+up0.3.0 | registry.suse.com/edge/3.6/endpoint-copier-operator-chart:306.0.1+up0.3.0 +
registry.suse.com/edge/3.6/endpoint-copier-operator:0.3.0
| SR-IOV Network Operator | 1.6.0 | 306.0.4+up1.6.0 | registry.suse.com/edge/3.6/sriov-network-operator-chart:306.0.4+up1.6.0 +
registry.suse.com/edge/3.6/sriov-crd-chart:306.0.4+up1.6.0
| System Upgrade Controller | 0.19.1 | 109.0.1 | https://charts.rancher.io/index.yaml[Rancher Charts Helm リポジトリ] +
registry.rancher.com/rancher/system-upgrade-controller:v0.19.1
s| Upgrade Controller s| 0.1.3 s| 306.0.4+up0.1.3 s| registry.suse.com/edge/3.6/upgrade-controller-chart:306.0.4+up0.1.3 +
registry.suse.com/edge/3.6/upgrade-controller:0.1.3 +
registry.rancher.com/rancher/kubectl:v1.35.2 +
registry.suse.com/edge/3.6/release-manifest:3.6.1
| SUSE Private Registry | 1.1.1 | 1.1.1 | oci://registry.suse.com/private-registry/private-registry-helm[SUSE Private Registry Helm リポジトリ] +
registry.suse.com/private-registry/harbor-core:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-jobservice:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-portal:1.1.1-1.20 +
registry.suse.com/private-registry/harbor-registry:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-registryctl:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-trivy-adapter:1.1.1-1.24
| Kiwi Builder | 10.2.29.1 | N/A | registry.suse.com/edge/3.6/kiwi-builder:10.2.29.1
| Cert-Manager | 1.20.1 | 1.20.1 | https://charts.jetstack.io[Jetstack Helmリポジトリ] +
quay.io/jetstack/cert-manager-controller:v1.20.1 +
quay.io/jetstack/cert-manager-webhook:v1.20.1 +
quay.io/jetstack/cert-manager-cainjector:v1.20.1
|======

[#release-notes-3-6-0]
= リリース 3.6.0

提供開始日:2026年5月27日

フルサポート終了日:2026年11月27日

メンテナンスサポート終了日:2028年5月27日

EOL:2028年5月28日

まとめ:{product} 3.6.0は、{product} 3.6リリースストリームにおける最初のリリースです。

== 新機能

* Kubernetes 1.35.3およびRancher Prime 2.14.1に更新されました
* SUSE Security (NeuVector) 5.5.1に更新されました https://open-docs.neuvector.com/releasenotes/5x[NeuVectorリリースノート]
* SUSE Storage (Longhorn) 1.11.1に更新されました https://longhorn.io/docs/1.11.1/[アップストリームLonghornリリースノート]
* Rancher Turtles (CAPI) 0.26.1に更新されました https://turtles.docs.rancher.com/[Rancher Turtlesドキュメント]
* MetalLB 0.15.3に更新されました https://metallb.universe.tf/release-notes/#version-0-15-3[アップストリームリリースノート]
* KubeVirt 1.7.0およびCDI (Containerized Data Importer) 1.64.0に更新されました
* Elemental 1.9.0に更新されました https://elemental.docs.rancher.com/release-notes/[Elementalリリースノート]
* Cert-Manager 1.20.1に更新されました https://cert-manager.io/docs/release-notes/[アップストリームリリースノート]
* Metal3/IronicをIronic 35.0.0を含む0.15.0に更新しました
* MetalLBのBGPモードは{product} 3.5ではテクノロジープレビューでしたが、現在は完全にサポートされています。
* ダウンストリームデプロイメントにおけるPrecision Time Protocol（PTP）は{product} 3.5ではテクノロジープレビューでしたが、SyncEおよびGNSSのサポートとともに、現在は完全にサポートされています。
* シングルスタックIPv6ダウンストリームクラスターのデプロイメントがサポートされるようになりました。ただし、これにはデュアルスタック管理クラスターが必要であることに注意してください（シングルスタック管理クラスターは引き続きテクノロジープレビューです）。

== バグおよびセキュリティ更新

* Kubernetes 1.35.3には、いくつかのバグ修正とセキュリティ更新が含まれています https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.35.md[Kubernetes変更ログ]。
* Rancher Prime 2.14.1には、いくつかのバグ修正が含まれています https://github.com/rancher/rancher/releases/tag/v2.14.1[アップストリームRancherリリースノート]。
* SUSE Storage (Longhorn) 1.11.1には、いくつかのバグ修正が含まれています https://github.com/longhorn/longhorn/releases/tag/v1.11.1[アップストリームLonghornバグ修正]
* NeuVector 5.5.1には、新機能といくつかのバグ修正が含まれています https://open-docs.neuvector.com/releasenotes/5x[NeuVectorリリースノート]

== 既知の問題

[WARNING]
====
新しいクラスターをデプロイする場合は、<<guides-kiwi-builder-images>> に従って最初に新しいイメージをビルドしてください。 これは、イメージに最新のセキュリティ修正とバグ修正が含まれていることを確認するために、管理クラスターおよびダウンストリームクラスターに対して推奨されます。
====

* Edge Image Builderを介してデプロイする場合、`HelmChartConfigs` マニフェストを`kubernetes/manifests`設定ディレクトリに配置すると失敗する可能性があります。代わりに、EIBのos-filesインターフェースを使用して、`HelmChartConfigs` を `/var/lib/rancher/{rke2/k3s}/server/manifests/` に配置することを推奨します。
ifeval::["{flavor}" == "telco"]
例については、<<mgmt-cluster-directory-structure>>を参照してください。
endif::[]
これを行わないと、 https://github.com/rancher/rke2/issues/8357[#8357 RKE2 issue]で説明されているように、初期起動時にノードが `NotReady` 状態のままになる可能性があります。

* RKE2/K3s 1.34および1.35バージョンでは、CNI設定の保存に使用されるディレクトリ `/etc/cni` が、`overlayfs` に関連する特定の条件により、そこに書き込まれるファイルに関する通知を `containerd` にトリガーしない場合があります（ https://github.com/rancher/rke2/issues/8356[#8356 RKE2 issue]を参照）。その結果、RKE2/K3sのデプロイメントがCNIの起動待ちでスタックし、RKE2/K3sノードが `NotReady` 状態のままになります。これは、ノードレベルで `kubectl describe node <affected_node>` を使用して確認できます。

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

回避策として、RKE2の起動前に`/etc/cni`ディレクトリにtmpfsボリュームをマウントすることができます。これにより、containerdが通知を見逃す原因となるoverlayfsの使用を回避でき、ノードが再起動され、ポッドのinitcontainerが再度実行されるたびに設定が書き直されるはずです。EIBを使用している場合、これは `04-tmpfs-cni.sh` ディレクトリ内の `custom/scripts` スクリプト（ https://github.com/suse-edge/edge-image-builder/blob/release-1.3/docs/building-images.md#custom[こちら]で説明）として実装でき、以下のようになります。

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* 現段階では、synce4lを介したSyncEおよびgpsdを介したGNSSを設定するための公式ドキュメントや例は提供されておらず、これらのトピックは今後のリリースで取り上げられる予定です。

* 一部のコンテナリポジトリは現在IPv4経由でのみアクセス可能なため、IPv6のみのダウンストリームクラスターには、管理クラスター上のローカルレジストリが必要です。

== コンポーネントのバージョン

次の表は、3.6.0リリースを構成する個々のコンポーネントについて、バージョン、Helmチャートバージョン（該当する場合）、およびバイナリ形式でリリースされたアーティファクトの取得元を説明しています。使用方法やデプロイの例については、関連するドキュメントに従ってください。

|======
| 名前 | バージョン | Helmチャートのバージョン | アーティファクトの場所 (URL/イメージ)
| SUSE Linux Micro | 6.2 (latest) | N/A | https://www.suse.com/download/sle-micro/[SUSE Linux Micro ダウンロードページ] +
| SUSE Linux Micro | 6.2 (latest) | N/A |チェックサムと署名は、 https://www.suse.com/download/sle-micro/[SUSE Linux Micro ダウンロードページ]からダウンロードできます。 +
SL-Micro.x86_64-6.2-Base-SelfInstall-GM.install.iso +
SL-Micro.x86_64-6.2-Base-RT-SelfInstall-GM.install.iso +
SL-Micro.x86_64-6.2-Base-GM.raw.xz +
SL-Micro.x86_64-6.2-Base-RT-GM.raw.xz +
| SUSE Multi-Linux Manager | 5.1 | N/A | https://www.suse.com/download/suse-manager/[SUSE Multi-Linux Manager ダウンロードページ]
| K3s | 1.35.3 | N/A | https://github.com/k3s-io/k3s/releases/tag/v1.35.3%2Bk3s1[アップストリーム K3s リリース]
| RKE2 | 1.35.3 | N/A | https://github.com/rancher/rke2/releases/tag/v1.35.3%2Brke2r3[Upstream RKE2 Release]
| SUSE Rancher Prime | 2.14.1 | 2.14.1 | https://charts.rancher.com/server-charts/prime/index.yaml[Rancher Prime Helm リポジトリ] +
\https://prime.ribs.rancher.io/rancher/v2.14.1/rancher-images.txt[Rancher 2.14.1 Container Images]
| SUSE Storage (Longhorn) | 1.11.1 | 1.11.1 | https://apps.rancher.io/applications/suse-storage[SUSE Storage Helm リポジトリ] +
\https://apps.rancher.io/applications/suse-storage/components[SUSE Storage Container Images]
| SUSE Security (NeuVector) | 5.5.1 | 109.0.1+up2.8.13 | https://charts.rancher.io/index.yaml[Rancher Charts Helm リポジトリ] +
registry.rancher.com/rancher/neuvector-controller:5.5.1 +
registry.rancher.com/rancher/neuvector-enforcer:5.5.1 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.12
| Rancher Turtles プロバイダー (CAPI) | 0.26.1 | 306.0.6+up0.26.1 | registry.suse.com/edge/3.6/rancher-turtles-providers-chart:306.0.6+up0.26.1 +
registry.rancher.com/rancher/cluster-api-controller:v1.12.2 +
registry.rancher.com/rancher/turtles:v0.26.1 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.24.3 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.24.3
| Metal^3^| 0.15.0 | 306.0.26+up0.15.0 | registry.suse.com/edge/3.6/metal3-chart:306.0.26+up0.15.0 +
registry.suse.com/edge/3.6/baremetal-operator:0.12.3.0 +
registry.suse.com/edge/3.6/ironic:35.0.0.1 +
registry.suse.com/edge/3.6/ironic-ipa-downloader:3.1.1 +
registry.suse.com/edge/3.6/ironic-python-agent:3.0.8
| MetalLB | 0.15.3 | 306.0.2+up0.15.3 | registry.suse.com/edge/3.6/metallb-chart:306.0.2+up0.15.3 +
registry.suse.com/edge/3.6/metallb-controller:v0.15.3 +
registry.suse.com/edge/3.6/metallb-speaker:v0.15.3
| Elemental | 1.9.0 | 1.9.0 | registry.suse.com/rancher/elemental-operator-chart:1.9.0 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.9.0 +
registry.suse.com/rancher/elemental-operator:1.9.0
| Elemental ダッシュボード拡張機能 | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/main/charts/elemental/3.0.1[Elemental 拡張機能 Helm チャート]
| Edge Image Builder | 1.3.3.1 | N/A | registry.suse.com/edge/3.6/edge-image-builder:1.3.3.1
| KubeVirt | 1.7.0 | 306.0.2+up0.7.0 | registry.suse.com/edge/3.6/kubevirt-chart:306.0.2+up0.7.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.7.0-150700.3.16.2
| KubeVirt ダッシュボード拡張機能 | 1.3.3 | 306.0.4+up1.3.3 | registry.suse.com/edge/3.6/kubevirt-dashboard-extension-chart:306.0.4+up1.3.3
| Containerized Data Importer (CDI) | 1.64.0 | 306.0.2+up0.7.0 | registry.suse.com/edge/3.6/cdi-chart:306.0.2+up0.7.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.64.0-150700.9.6.1
| Endpoint Copier Operator | 0.3.0 | 306.0.1+up0.3.0 | registry.suse.com/edge/3.6/endpoint-copier-operator-chart:306.0.1+up0.3.0 +
registry.suse.com/edge/3.6/endpoint-copier-operator:0.3.0
| SR-IOV Network Operator | 1.6.0 | 306.0.4+up1.6.0 | registry.suse.com/edge/3.6/sriov-network-operator-chart:306.0.4+up1.6.0 +
registry.suse.com/edge/3.6/sriov-crd-chart:306.0.4+up1.6.0
| System Upgrade Controller | 0.19.1 | 109.0.1 | https://charts.rancher.io/index.yaml[Rancher Charts Helm リポジトリ] +
registry.rancher.com/rancher/system-upgrade-controller:v0.19.1
| Upgrade Controller | 0.1.3 | 306.0.3+up0.1.3 | registry.suse.com/edge/3.6/upgrade-controller-chart:306.0.3+up0.1.3 +
registry.suse.com/edge/3.6/upgrade-controller:0.1.3 +
registry.rancher.com/rancher/kubectl:v1.35.2 +
registry.suse.com/edge/3.6/release-manifest:3.6.0
| SUSE Private Registry | 1.1.1 | 1.1.1 | oci://registry.suse.com/private-registry/private-registry-helm[SUSE Private Registry Helm リポジトリ] +
registry.suse.com/private-registry/harbor-core:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-jobservice:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-portal:1.1.1-1.20 +
registry.suse.com/private-registry/harbor-registry:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-registryctl:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-trivy-adapter:1.1.1-1.24
| Kiwi Builder | 10.2.29.1 | N/A | registry.suse.com/edge/3.6/kiwi-builder:10.2.29.1
| Cert-Manager | 1.20.1 | 1.20.1 | https://charts.jetstack.io[Jetstack Helm リポジトリ] +
quay.io/jetstack/cert-manager-controller:v1.20.1 +
quay.io/jetstack/cert-manager-webhook:v1.20.1 +
quay.io/jetstack/cert-manager-cainjector:v1.20.1
|======

= 削除された機能

特に記載がない限り、これらは{version-edge}.0リリースおよびそれ以降のすべてのzストリームバージョンに適用されます。

* Akriは以前のEdgeリリースにおいてテクノロジープレビューとして提供されていましたが、3.4.0以降は廃止されました。現在は製品から完全に削除されています。

[#tech-previews]
= 技術プレビュー

特に記載がない限り、これらは3.6.0リリースおよびそれ以降のすべてのzストリームバージョンに適用されます。

* シングルスタックIPv6管理クラスターのデプロイはテクノロジープレビューとして提供されており、標準的なサポート範囲の対象外です。

= コンポーネントの検証

上記のコンポーネントは、ソフトウェア部品表（SBOM）データを使用して検証できます。例えば、以下のように`cosign`を使用します。

https://www.suse.com/support/security/keys/[SUSE署名キーソース]から{product}コンテナの公開鍵をダウンロードします。

[,bash]
----
include::key.sh[]
----

例えば`crane`を使用して、コンテナイメージのハッシュを検証します。

[,bash]
----
> crane digest registry.suse.com/edge/3.6/baremetal-operator:0.12.3.0 --platform linux/amd64
sha256:example-digest-placeholder
----

NOTE: マルチアーキテクチャイメージの場合は、ダイジェストを取得する際にプラットフォームを指定する必要もあります。例: `--platform linux/amd64` または `--platform linux/arm64`。これを行わないと、次のステップ (`Error: no matching attestations`) でエラーが発生します。

次のコマンドで確認します: `cosign`

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/3.6/baremetal-operator@sha256:example-digest-placeholder > /dev/null
#
Verification for registry.suse.com/edge/3.6/baremetal-operator@sha256:example-digest-placeholder --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - The signatures were verified against the specified public key
----

https://www.suse.com/support/security/sbom/[SUSE SBOMドキュメント]に記載されている手順に従って、SBOMデータを抽出します。

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/3.6/baremetal-operator@sha256:example-digest-placeholder | jq '.payload | @base64d | fromjson | .predicate'
----

= アップグレード手順

新しいリリースへのアップグレード方法の詳細については、<<day-2-operations>>を参照してください。

= 製品サポートライフサイクル

{product}は、実績あるテクノロジーリーダーであるSUSEが提供する、受賞歴のあるサポートに支えられています。詳細については、 https://www.suse.com/lifecycle[https://www.suse.com/lifecycle]および https://www.suse.com/support/policy.html[https://www.suse.com/support/policy.html]のサポートポリシーページを参照してください。サポートケースの起票方法、SUSEによる重大度レベルの分類方法、またはサポート範囲についてご質問がある場合は、 https://www.suse.com/support/handbook/[https://www.suse.com/support/handbook/]のテクニカルサポートハンドブックを参照してください。

{product} \"3.6\" は24か月間のプロダクションサポートが提供され、最初の6か月間は「フルサポート」、その後の18か月間は「メンテナンスサポート」となります。 これらのサポートフェーズが終了すると、製品は「サービス終了」(EOL) となり、サポートは提供されなくなります。ライフサイクルフェーズの詳細については、以下の表を参照してください。

|======
| *フルサポート (6か月)*| フルサポート期間中は、緊急および選択された優先度の高いバグ修正がリリースされます。その他のすべてのパッチ (緊急ではないもの、機能強化、新機能) は、通常のリリーススケジュールに従ってリリースされます。
| *メンテナンスサポート (18か月)*| この期間中は、重大な修正のみがパッチを通じてリリースされます。その他のバグ修正はSUSEの判断でリリースされる場合がありますが、期待はしないでください。
| *サービス終了 (EOL)* | 製品リリースがサービス終了日を迎えると、お客様は製品ライセンス契約の条件の範囲内で製品を引き続き使用できます。
SUSEのサポートプランは、サービス終了日（EOL）を過ぎた製品リリースには適用されません。
|======

明記されていない限り、リストされているすべてのコンポーネントは一般提供（GA）されており、SUSEの標準的なサポート範囲に含まれます。一部のコンポーネントは「Technology Preview」としてリストされている場合があります。これは、SUSEがお客様に評価目的でGA前の機能へのアクセスを提供するものであり、標準的なサポートポリシーの対象外であり、本番環境での使用は推奨されません。SUSEは、Technology Previewコンポーネントに対する改善に関するフィードバックや提案を大いに歓迎しますが、お客様のニーズを満たさない場合や、当社が要求する成熟度に達しない場合、一般提供（GA）される前にTechnology Preview機能を廃止する権利を留保します。

SUSEは、時折、機能を廃止したり、API仕様を変更したりする場合があることにご留意ください。機能の廃止やAPI変更の理由には、機能が更新または新しい実装に置き換えられること、新しい機能セット、アップストリームテクノロジーが利用できなくなること、またはアップストリームコミュニティが互換性のない変更を導入したことなどが含まれます。これは特定のマイナーリリース（x.z）内では発生しないことを意図しており、すべてのz ストリームリリースはAPIの互換性と機能性を維持します。SUSEは、サービスの中断を最小限に抑えるため、リリースノート内で十分な通知期間をもって廃止の警告を提供し、回避策、提案、および緩和策を提供するよう努めます。

{product}チームはコミュニティからのフィードバックも歓迎しており、問題は https://www.github.com/suse-edge[https://www.github.com/suse-edge]内のそれぞれのリポジトリで提起できます。

= ソースコードの入手

本SUSE製品には、GNU一般公衆利用許諾契約書（GPL）およびその他のさまざまなオープンソースに基づいてSUSEにライセンス供与された素材が含まれています。GPLでは、SUSEはGPLライセンス対象の素材に対応するソースコードを提供することが義務付けられており、SUSEはその他すべてのオープンソースの要件を遵守しています。そのため、SUSEはすべてのソースコードを利用可能にしており、一般的に{product} GitHubリポジトリ（ https://www.github.com/suse-edge）、依存コンポーネントについてはSUSE Rancher GitHubリポジトリ（ https://www.github.com/rancher）、特にSUSE Linux Microについては、ソースコードは https://www.suse.com/download/sle-micro/[https://www.suse.com/download/sle-micro]の「Medium 2」からダウンロードできます。

= 保証と著作権

SUSEは、本書の内容または使用に関していかなる表明も保証も行わず、特に、商業性および特定目的への適合性について、明示的か黙示的かを問わず、いかなる保証も否認します。さらに、SUSEは、本書をいつでも改訂またはその内容を変更する権利を留保し、何人に対しても当該の改訂または変更について通知する義務を負わないものとします。

さらに、SUSEは、すべてのソフトウェアについて、いかなる表明または保証も行わず、特に、ソフトウェアの商業性および特定目的への適合性について、明示的か黙示的かを問わず、いかなる保証も否認します。さらに、SUSEは、SUSE製ソフトウェアの一部または全部をいつでも変更する権利を留保し、何人に対しても当該の変更について通知する義務を負わないものとします。

本契約の下で提供される製品または技術情報はすべて、米国の輸出管理規定およびその他の国の輸出関連法規の制限を受けます。お客様は、すべての輸出管理規制を遵守し、成果物の輸出、再輸出、または輸入に必要なすべての許可または等級を取得することに同意するものとします。お客様は、現在の米国の輸出除外リストに掲載されている企業、および米国の輸出管理規定で指定された輸出禁止国またはテロリスト国に本製品を輸出または再輸出しないことに同意するものとします。お客様は、成果物を、禁止されている核兵器、ミサイル、または化学兵器・生物兵器の最終用途に使用しないことに同意するものとします。SUSEソフトウェアの輸出に関する詳細は、 https://www.suse.com/company/legal/[https://www.suse.com/company/legal/]を参照してください。SUSEは、必要な輸出許可の取得をお客様が怠った場合の責任は問われないものとします。

*Copyright © 2024 SUSE LLC.*

このリリースノートドキュメントは、Creative Commons Attribution-NoDerivatives 4.0 International License (CC-BY-ND-4.0) の下でライセンスされています。このドキュメントとともにライセンスのコピーを受け取っているはずです。そうでない場合は、 https://creativecommons.org/licenses/by-nd/4.0/[https://creativecommons.org/licenses/by-nd/4.0/]を参照してください。

SUSEは、本書に記載されている製品に組み込まれている技術に関連する知的財産権を有しています。特に、これらの知的財産権には、 https://www.suse.com/company/legal/[https://www.suse.com/company/legal/]に記載されている1つまたは複数の米国特許、および米国ならびに他の国における1つまたは複数のその他の特許や出願中の特許（これらに限定されません）が含まれている場合があります。

SUSEの商標については、SUSEの商標およびサービスマークリスト (https://www.suse.com/company/legal/[https://www.suse.com/company/legal/]) を参照してください。サードパーティ各社とその製品の商標は、所有者であるそれぞれの会社に所属します。SUSEのブランド情報および使用要件については、 https://brand.suse.com/[https://brand.suse.com/]で公開されているガイドラインを参照してください。
