[#release-notes-abstract]
= 抽象データ型
:revdate: 2026-03-18
:revnumber: 3.5
:page-revdate: {revdate}
ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

SUSE Edge 3.5は、エッジにおけるインフラストラクチャおよびクラウドネイティブアプリケーションのデプロイメントという独自の課題に対処するための、緊密に統合され、包括的に検証されたエンドツーエンドのソリューションです。その主な目的は、初期デプロイメントのイメージ構築、ノードのプロビジョニングとオンボーディング、アプリケーションのデプロイ、監視、ライフサイクル管理にわたって、独自の設計思想を持ちながらも非常に柔軟で、拡張性が高く、安全なプラットフォームを提供することです。

このソリューションは、お客様の要件や期待が大きく異なるため、「万能な」エッジプラットフォームは存在しないという考えに基づいて設計されています。エッジデプロイメントは、大規模なスケーラビリティ、制限されたネットワーク可用性、物理的なスペースの制約、新しいセキュリティの脅威と攻撃ベクトル、ハードウェアアーキテクチャとシステムリソースの多様性、レガシーインフラストラクチャおよびアプリケーションとのデプロイとインターフェースの要件、そして寿命が長い顧客ソリューションなど、最も困難な問題のいくつかを解決し、継続的に進化させることを私たちに求めています。

SUSE Edgeは、安全で安定した認定済みのSUSE Linuxプラットフォームを提供してきた30年にわたる歴史と、Rancherポートフォリオによる高度にスケーラブルで機能豊富なKubernetes管理を提供してきた経験の両方に基づき、最高クラスのオープンソースソフトウェアを基盤として構築されています。SUSE Edgeは、これらの機能を基盤として構築されており、小売、医療、輸送、物流、電気通信、スマートマニュファクチャリング、産業用IoTなど、幅広い市場セグメントの要件に対応できる機能を提供します。

SUSE Edgeの製品サポートライフサイクルの更新に関する詳細については、link:https://www.suse.com/lifecycle/#suse-edge-33[Product Support Lifecycle]を参照してください。

NOTE: SUSE Telco Cloud（旧称：SUSE Edge for Telco）はSUSE Edgeの派生製品であり、電気通信のユースケースで見られる要件にプラットフォームが対応できるようにするための追加の最適化とコンポーネントを備えています。明記されていない限り、すべてのリリースノートはSUSE Edge 3.5とSUSE Telco Cloud 3.5の両方に適用されます。

= バージョン情報

これらのリリースノートは、明示的に指定および説明されている場合を除き、すべてのアーキテクチャで同一であり、最新バージョンは、他のすべてのSUSE製品のリリースノートとともに、オンラインの https://www.suse.com/releasenotes[https://www.suse.com/releasenotes]で常に入手可能です。

項目は一度だけリストされますが、重要であり、複数のセクションに該当する場合は、複数の場所で参照されることがあります。リリースノートには通常、2つの連続するリリースの間に行われた変更のみが記載されます。以前の製品バージョンのリリースノートからの重要な項目が繰り返される場合があります。これらの項目を識別しやすくするために、その旨を記載した注記が含まれています。

ただし、繰り返される項目は便宜上提供されているに過ぎません。したがって、1つ以上のリリースをスキップする場合は、スキップしたリリースのリリースノートも確認してください。現在のリリースのリリースノートのみを読んでいる場合、システム動作に影響を与える可能性のある重要な変更を見落とす可能性があります。SUSE Edgeのバージョンはx.y.zとして定義されます。ここで「x」はメジャーバージョン、「y」はマイナーバージョン、「z」はパッチバージョン（「zストリーム」とも呼ばれます）を示します。SUSE Edgeの製品ライフサイクルは、特定のマイナーリリースに基づいて定義されます（例:）。「3.5」ですが、そのライフサイクルを通じて後続のパッチ更新とともに出荷されます（例:）。"3.5.1".

NOTE: SUSE Edgeのzストリームリリースは、バージョン管理されたスタックとして緊密に統合され、徹底的にテストされています。上記以外のバージョンへの個々のコンポーネントのアップグレードは、システムダウンタイムを引き起こす可能性があります。テストされていない構成でEdgeクラスターを実行することは可能ですが、推奨はされず、サポートチャネルを通じた解決に時間がかかる場合があります。

[#release-notes-3-5-2]
= リリース 3.5.2

提供開始日:2026年7月7日

フルサポート終了日:2026年7月21日

メンテナンスサポート終了日:2027年7月21日

EOL:2027年7月22日

まとめ:SUSE Edge 3.5.2は、SUSE Edge 3.5リリースストリームにおける2回目のzストリームリリースです。

== 新機能

* Kubernetes 1.34.7およびRancher Prime 2.13.6に更新されました
* SUSE Storage (Longhorn) 1.10.2に更新されました https://longhorn.io/docs/1.10.2/[アップストリーム Longhorn リリースノート]
* SUSE Security (NeuVector) 5.5.1に更新されました https://open-docs.neuvector.com/releasenotes/5x/#551-april-2026[リリースノート]
* Metal^3^チャートを305.0.26+up0.13.2に更新し、いくつかの改善を行いました
* Upgrade Controllerチャートを305.0.3+up0.1.3に更新しました

== バグおよびセキュリティ更新

* Rancher Prime 2.13.6には、いくつかのバグ修正とセキュリティ更新が含まれています https://github.com/rancher/rancher/releases/tag/v2.13.6[アップストリーム Rancher リリースノート]
* Metal^3^/Ironicのアップデートでは、以下を含むいくつかのバグおよびセキュリティの問題が修正されています。
** CVE-2026-44916を修正しました
** CVE-2026-44917を修正しました
** CVE-2026-44919を修正しました
** Fix CVE-2026-46447
** CVE-2026-48681を修正しました
** CVE-2026-50589を修正しました
** CVE-2026-54421を修正しました

== 既知の問題

* デフォルト設定で https://documentation.suse.com/suse-edge/{version-edge}/html/edge/atip-features.html#ptp-telco-config[PTP機能] を実行するには、追加の手順が必要です。
Edge 3.5リリースで正しく動作させるには、ptp4lサービスのオーバーライドに以下を追加する必要があります。
[,bash]
----
[Service]
PrivateDevices=
DevicePolicy=closed
DeviceAllow=/dev/rtc rwm
DeviceAllow=char-ptp rwm
DeviceAllow=/dev/ptp0 rwm
----

これは、`/etc/systemd/system/ptp4l.service.d/override.conf` を編集するか、`systemctl edit ptp4l.service` を実行することで実現できます。これに対する適切な修正は、 https://bugzilla.suse.com/show_bug.cgi?id=1256059[linuxptpパッケージのバグ] が修正された時点で含まれる予定です。

[WARNING]
====
新しいクラスターをデプロイする場合は、<<guides-kiwi-builder-images>> に従って最初に新しいイメージをビルドしてください。これは、{x86-64} および {aarch64} アーキテクチャ、ならびに管理クラスターおよびダウンストリームクラスターの両方を作成するために現在必要とされる最初のステップであるためです。
====

* Edge Image Builderを介してデプロイする場合、`HelmChartConfigs` マニフェストを`kubernetes/manifests`設定ディレクトリに配置すると失敗する可能性があります。代わりに、EIBのos-filesインターフェースを使用して、`HelmChartConfigs` を `/var/lib/rancher/{rke2/k3s}/server/manifests/` に配置することを推奨します。例については <<mgmt-cluster-directory-structure>> を参照してください。 これを行わないと、 https://github.com/rancher/rke2/issues/8357[#8357 RKE2 issue]で説明されているように、初期起動時にノードが `NotReady` 状態のままになる可能性があります。

* RKE2/K3s 1.31、1.32、1.33、および1.34バージョンでは、CNI設定の保存に使用されるディレクトリ `/etc/cni` が、`overlayfs` に関連する特定の条件により、そこに書き込まれるファイルに関する通知を `containerd` にトリガーしない場合があります（ https://github.com/rancher/rke2/issues/8356[#8356 RKE2 issue]を参照）。その結果、RKE2/K3sのデプロイメントがCNIの起動待ちでスタックし、RKE2/K3sノードが `NotReady` 状態のままになります。これは、ノードレベルで `kubectl describe node <affected_node>` を使用して確認できます。

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

回避策として、RKE2の起動前に`/etc/cni`ディレクトリにtmpfsボリュームをマウントすることができます。これにより、containerdが通知を見逃す原因となるoverlayfsの使用を回避でき、ノードが再起動され、ポッドのinitcontainerが再度実行されるたびに設定が書き直されるはずです。EIBを使用している場合、これは `04-tmpfs-cni.sh` ディレクトリ内の `custom/scripts` スクリプト（こちら[https://github.com/suse-edge/edge-image-builder/blob/release-1.2/docs/building-images.md#custom]で説明されている通り）であり、以下のようになります。

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* Elementalを使用してリモートホストをオンボーディングする際、`dbus.service`と`elemental-system-agent.service`の間で競合状態が発生し、リモートホスト上の`rancher-system-agent.service`が以下のようなエラーで起動にエラーとなる可能性があります。（詳細は https://github.com/suse-edge/edge-image-builder/issues/784[#784 Edge Image Builder issue]を参照してください。）

[,bash]
----
Sep 19 19:38:07 elementalvm elemental-system-agent[3671]: time="2025-09-19T19:38:07Z" level=info msg="[6b20fe64c854da2639804884b34129bb8f718eb59578111da58d9de1509c24db_1:stderr]: Failed to restart rancher-system-agent.service: Message recipient disconnected from message bus without replying"
----

回避策として、以下のようにsystemdオーバーライドファイルを作成できます。

[,bash]
----
[Unit]
Wants=dbus.service network-online.target
After=dbus.service network-online.target time-sync.target

[Service]
ExecStartPre=/bin/bash -c 'echo "Waiting for dbus to become active..." | systemd-cat -p info -t elemental-system-agent; sleep 15; timeout 300 bash -c "while ! systemctl is-active --quiet dbus.service; do sleep 15; done"'
----

また、`30a-copy-elemental-system-agent-override.sh`という名前のカスタムスクリプトを使用して、EIBの https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/templates/31-elemental-register.sh.tpl[31-elemental-register.sh]スクリプトがcombustionフェーズ中に実行される前に、オーバーライドを`/etc/systemd/system/elemental-system-agent.service.d`に配置することができます。

[,bash]
----
#!/bin/bash

/bin/mkdir -p /etc/systemd/system/elemental-system-agent.service.d
/bin/cp -f elemental-system-agent-override.conf /etc/systemd/system/elemental-system-agent.service.d/override.conf
----

== コンポーネントのバージョン

以下の表は、3.5.2リリースを構成する個々のコンポーネントについて、バージョン、Helmチャートのバージョン（該当する場合）、およびバイナリ形式でリリースされたアーティファクトの取得元を説明しています。使用方法やデプロイの例については、関連するドキュメントに従ってください。

|======
| 名前 | バージョン | Helmチャートのバージョン | アーティファクトの場所 (URL/イメージ)
| SUSE Linux Micro | 6.2 (latest) | N/A | https://www.suse.com/download/sle-micro/[SUSE Linux Micro ダウンロードページ] +
SL-Micro.x86_64-6.2-Base-SelfInstall-GM.install.iso (sha256 76390cec4537821d90975d924bf9d7575c9912da89fa460383eff0c623fd403e) +
SL-Micro.x86_64-6.2-Base-RT-SelfInstall-GM.install.iso (sha256 8f4d03c6953966174efb4c4b176cbe6dd5cab6e2a406033fc5c2bf6884da8b5d) +
SL-Micro.x86_64-6.2-Base-GM.raw.xz (sha256 bea3ac202b54ee29fabc28568f50c86d34939cf861679f21a91dfbae9c54c92e) +
SL-Micro.x86_64-6.2-Base-RT-GM.raw.xz (sha256 b9af7763c8d63143e31e5f80eb8d06fcc9477a576de8e358ab2e9835ab39d305) +
| SUSE Multi-Linux Manager | 5.1 | N/A | https://www.suse.com/download/suse-manager/[SUSE Multi-Linux Manager ダウンロードページ]
s| K3s s| 1.34.7 s| N/A s| https://github.com/k3s-io/k3s/releases/tag/v1.34.7%2Bk3s1[アップストリーム K3s リリース]
s| RKE2 s| 1.34.7 s| N/A s| https://github.com/rancher/rke2/releases/tag/v1.34.7%2Brke2r1[Upstream RKE2 Release]
s| SUSE Rancher Prime s| 2.13.6 s| 2.13.6 s| https://charts.rancher.com/server-charts/prime/index.yaml[Rancher Prime Helm リポジトリ] +
\https://prime.ribs.rancher.io/rancher/v2.13.6/rancher-images.txt[Rancher 2.13.6 Container Images]
| SUSE Storage (Longhorn) | 1.10.2 | 1.10.2 | https://apps.rancher.io/applications/suse-storage[SUSE Storage Helm リポジトリ] +
\https://apps.rancher.io/applications/suse-storage/components[SUSE Storage Container Images]
s| SUSE Security s| 5.5.1 s| 108.0.4+up2.8.13 s| https://charts.rancher.io/index.yaml[Rancher Charts Helm リポジトリ] +
registry.suse.com/rancher/neuvector-controller:5.4.9 +
registry.suse.com/rancher/neuvector-enforcer:5.4.9 +
registry.suse.com/rancher/neuvector-manager:5.4.9 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.9 +
registry.suse.com/rancher/neuvector-registry-adapter:0.2.2 +
registry.suse.com/rancher/neuvector-scanner:6 +
registry.suse.com/rancher/neuvector-updater:0.0.7
| Rancher Turtles プロバイダー (CAPI) | 0.25.4 | 305.0.5+up0.25.4 | registry.suse.com/edge/charts/rancher-turtles-providers:305.0.5+up0.25.4 +
registry.rancher.com/rancher/cluster-api-metal3-controller:v1.10.4 +
registry.rancher.com/rancher/cluster-api-metal3-ipam-controller:v1.10.4 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.21.1 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.21.1
s| Metal^3^s| 0.13.2 s| 305.0.26+up0.13.2 s| registry.suse.com/edge/charts/metal3:305.0.26+up0.13.2 +
registry.suse.com/edge/3.5/baremetal-operator:0.11.2.0 +
registry.suse.com/edge/3.5/ironic:32.0.1.0 +
registry.suse.com/edge/3.5/ironic-ipa-downloader:3.0.11 +
registry.suse.com/edge/mariadb:10.11
| MetalLB | 0.15.2 | 305.0.1+up0.15.2 | registry.suse.com/edge/charts/metallb:305.0.1+up0.15.2 +
registry.suse.com/edge/3.5/metallb-controller:v0.15.2 +
registry.suse.com/edge/3.5/metallb-speaker:v0.15.2 +
registry.suse.com/edge/3.5/frr:10.2.1 +
registry.suse.com/edge/3.5/frr-k8s:v0.0.20 +
registry.suse.com/edge/3.5/kube-rbac-proxy:0.19.1
| Elemental | 1.8.1 | 1.8.1 | registry.suse.com/rancher/elemental-operator-chart:1.8.1 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.8.1 +
registry.suse.com/rancher/elemental-operator:1.8.1
| Elemental ダッシュボード拡張機能 | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/4.0.0/charts/elemental/3.0.1[Elemental 拡張機能 Helm チャート]
s| Edge Image Builder s| 1.3.3.1 s| N/A s| registry.suse.com/edge/3.5/edge-image-builder:1.3.3.1
| NM Configurator | 0.3.5 | N/A | https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.5[NMConfigurator アップストリームリリース]
| KubeVirt | 1.5.2 | 305.0.1+up0.6.0 | registry.suse.com/edge/charts/kubevirt:305.0.1+up0.6.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportproxy:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportserver:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.5.2
| KubeVirt ダッシュボード拡張機能 | 1.3.3 | 305.0.4+up1.3.3 | registry.suse.com/edge/charts/kubevirt-dashboard-extension:305.0.4+up1.3.3
| コンテナ化データインポーター | 1.62.0 | 305.0.1+up0.6.0 | registry.suse.com/edge/charts/cdi:305.0.1+up0.6.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-importer:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-cloner:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.62.0
| Endpoint Copier Operator | 0.3.0 | 305.0.1+up0.3.0 | registry.suse.com/edge/charts/endpoint-copier-operator:305.0.1+up0.3.0 +
registry.suse.com/edge/3.5/endpoint-copier-operator:0.3.0
| Akri（廃止） | 0.12.20 | 305.0.0+up0.12.20 | registry.suse.com/edge/charts/akri:305.0.0+up0.12.20 +
registry.suse.com/edge/charts/akri-dashboard-extension:305.0.0+up1.3.1 +
registry.suse.com/edge/3.5/akri-agent:v0.12.20 +
registry.suse.com/edge/3.5/akri-controller:v0.12.20 +
registry.suse.com/edge/3.5/akri-debug-echo-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.5/akri-onvif-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.5/akri-opcua-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.5/akri-udev-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.5/akri-webhook-configuration:v0.12.20
| SR-IOV Network Operator | 1.6.0 | 305.0.4+up1.6.0 | registry.suse.com/edge/charts/sriov-network-operator:305.0.4+up1.6.0 +
registry.suse.com/edge/charts/sriov-crd:305.0.4+up1.6.0
| System Upgrade Controller | 0.17.0 | 108.0.0 | https://charts.rancher.io/index.yaml[Rancher Charts Helm リポジトリ] +
registry.suse.com/rancher/system-upgrade-controller:v0.17.0
| Upgrade Controller | 0.1.3 | 305.0.3+up0.1.3 | registry.suse.com/edge/charts/upgrade-controller:305.0.3+up0.1.3 +
registry.suse.com/edge/3.5/upgrade-controller:0.1.3 +
registry.suse.com/edge/3.5/kubectl:1.34.2 +
registry.suse.com/edge/3.5/release-manifest:3.5.2
| Kiwi Builder | 10.2.29.1 | N/A | registry.suse.com/edge/3.5/kiwi-builder:10.2.29.1
|======

[#release-notes-3-5-1]
= リリース 3.5.1

提供開始日:2026年3月18日

フルサポート終了日:2026年7月21日

メンテナンスサポート終了日:2027年7月21日

EOL:2027年7月22日

まとめ:SUSE Edge 3.5.1は、SUSE Edge 3.5リリーストリームにおける最初のzストリームリリースです。

== 新機能

* Kubernetes 1.34.4およびRancher Prime 2.13.3に更新されました
* SUSE Storage (Longhorn) 1.10.2に更新されました https://longhorn.io/docs/1.10.2/[アップストリーム Longhorn リリースノート]
* SUSE Security (NeuVector) 5.4.9に更新されました https://open-docs.neuvector.com/releasenotes/5x/#549-february-2026[リリースノート]
* Elementalが1.8.1に更新されました
* Edge Image Builderが1.3.3に更新されました。 https://github.com/suse-edge/edge-image-builder/blob/release-1.3/RELEASE_NOTES.md[アップストリームリリースノート]を参照してください
* SUSE Multi-Linux Managerが5.1.2に更新されました。 https://www.suse.com/releasenotes/x86_64/multi-linux-manager/5.1/index.html[リリースノート]を参照してください

== バグおよびセキュリティ更新

* Rancher Prime 2.13.3には、いくつかのバグ修正が含まれています https://github.com/rancher/rancher/releases/tag/v2.13.3[アップストリーム Rancher リリースノート]
* SUSE Storage (Longhorn) 1.10.2には、いくつかのバグ修正が含まれています https://github.com/longhorn/longhorn/releases/tag/v1.10.2[アップストリーム Longhorn バグ修正]
* SUSE Security (NeuVector) 5.4.8には、いくつかのバグ修正が含まれています https://open-docs.neuvector.com/releasenotes/5x/#bugs-fixed[アップストリーム NeuVector バグ修正]
* EIB (edge-image-builder) 1.3.3には、いくつかのバグ修正が含まれています https://github.com/suse-edge/edge-image-builder/blob/release-1.3/RELEASE_NOTES.md#bug-fixes[EIB バグ修正]
* Metal3チャートがいくつかのバグ修正とともに更新されました

== 既知の問題

* デフォルト設定で https://documentation.suse.com/suse-edge/{version-edge}/html/edge/atip-features.html#ptp-telco-config[PTP機能] を実行するには、追加の手順が必要です。
Edge 3.5リリースで正しく動作させるには、ptp4lサービスのオーバーライドに以下を追加する必要があります。
[,bash]
----
[Service]
PrivateDevices=
DevicePolicy=closed
DeviceAllow=/dev/rtc rwm
DeviceAllow=char-ptp rwm
DeviceAllow=/dev/ptp0 rwm
----

これは、`/etc/systemd/system/ptp4l.service.d/override.conf` を編集するか、`systemctl edit ptp4l.service` を実行することで実現できます。これに対する適切な修正は、 https://bugzilla.suse.com/show_bug.cgi?id=1256059[linuxptpパッケージのバグ] が修正された時点で含まれる予定です。

[WARNING]
====
新しいクラスターをデプロイする場合は、<<guides-kiwi-builder-images>> に従って最初に新しいイメージをビルドしてください。これは、{x86-64} および {aarch64} アーキテクチャ、ならびに管理クラスターおよびダウンストリームクラスターの両方を作成するために現在必要とされる最初のステップであるためです。
====

* Edge Image Builderを介してデプロイする場合、`HelmChartConfigs` マニフェストを`kubernetes/manifests`設定ディレクトリに配置すると失敗する可能性があります。代わりに、EIBのos-filesインターフェースを使用して、`HelmChartConfigs` を `/var/lib/rancher/{rke2/k3s}/server/manifests/` に配置することを推奨します。例については <<mgmt-cluster-directory-structure>> を参照してください。 これを行わないと、 https://github.com/rancher/rke2/issues/8357[#8357 RKE2 issue]で説明されているように、初期起動時にノードが `NotReady` 状態のままになる可能性があります。

* RKE2/K3s 1.31、1.32、1.33、および1.34バージョンでは、CNI設定の保存に使用されるディレクトリ `/etc/cni` が、`overlayfs` に関連する特定の条件により、そこに書き込まれるファイルに関する通知を `containerd` にトリガーしない場合があります（ https://github.com/rancher/rke2/issues/8356[#8356 RKE2 issue]を参照）。その結果、RKE2/K3sのデプロイメントがCNIの起動待ちでスタックし、RKE2/K3sノードが `NotReady` 状態のままになります。これは、ノードレベルで `kubectl describe node <affected_node>` を使用して確認できます。

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

回避策として、RKE2の起動前に`/etc/cni`ディレクトリにtmpfsボリュームをマウントすることができます。これにより、containerdが通知を見逃す原因となるoverlayfsの使用を回避でき、ノードが再起動され、ポッドのinitcontainerが再度実行されるたびに設定が書き直されるはずです。EIBを使用している場合、これは `custom/scripts` ディレクトリ内の `04-tmpfs-cni.sh` スクリプト（こちら[https://github.com/suse-edge/edge-image-builder/blob/release-1.2/docs/building-images.md#custom]で説明されている通り）であり、以下のようになります。

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* Elementalを使用してリモートホストをオンボーディングする際、`dbus.service`と`elemental-system-agent.service`の間で競合状態が発生し、リモートホスト上の`rancher-system-agent.service`が以下のようなエラーで起動に失敗する可能性があります。（詳細は https://github.com/suse-edge/edge-image-builder/issues/784[#784 Edge Image Builder issue]を参照してください。）

[,bash]
----
Sep 19 19:38:07 elementalvm elemental-system-agent[3671]: time="2025-09-19T19:38:07Z" level=info msg="[6b20fe64c854da2639804884b34129bb8f718eb59578111da58d9de1509c24db_1:stderr]: Failed to restart rancher-system-agent.service: Message recipient disconnected from message bus without replying"
----

回避策として、以下のようにsystemdオーバーライドファイルを作成できます。

[,bash]
----
[Unit]
Wants=dbus.service network-online.target
After=dbus.service network-online.target time-sync.target

[Service]
ExecStartPre=/bin/bash -c 'echo "Waiting for dbus to become active..." | systemd-cat -p info -t elemental-system-agent; sleep 15; timeout 300 bash -c "while ! systemctl is-active --quiet dbus.service; do sleep 15; done"'
----

また、`30a-copy-elemental-system-agent-override.sh`という名前のカスタムスクリプトを使用して、EIBの https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/templates/31-elemental-register.sh.tpl[31-elemental-register.sh]スクリプトがcombustionフェーズ中に実行される前に、オーバーライドを`/etc/systemd/system/elemental-system-agent.service.d`に配置することができます。

[,bash]
----
#!/bin/bash

/bin/mkdir -p /etc/systemd/system/elemental-system-agent.service.d
/bin/cp -f elemental-system-agent-override.conf /etc/systemd/system/elemental-system-agent.service.d/override.conf
----

== コンポーネントのバージョン

以下の表は、3.5.1リリースを構成する個々のコンポーネントについて、バージョン、Helmチャートのバージョン（該当する場合）、およびバイナリ形式でリリースされたアーティファクトの取得元を説明しています。使用方法やデプロイの例については、関連するドキュメントに従ってください。

|======
| 名前 | バージョン | Helmチャートのバージョン | アーティファクトの場所 (URL/イメージ)
| SUSE Linux Micro | 6.2 (latest) | N/A | https://www.suse.com/download/sle-micro/[SUSE Linux Micro ダウンロードページ] +
SL-Micro.x86_64-6.2-Base-SelfInstall-GM.install.iso (sha256 76390cec4537821d90975d924bf9d7575c9912da89fa460383eff0c623fd403e) +
SL-Micro.x86_64-6.2-Base-RT-SelfInstall-GM.install.iso (sha256 8f4d03c6953966174efb4c4b176cbe6dd5cab6e2a406033fc5c2bf6884da8b5d) +
SL-Micro.x86_64-6.2-Base-GM.raw.xz (sha256 bea3ac202b54ee29fabc28568f50c86d34939cf861679f21a91dfbae9c54c92e) +
SL-Micro.x86_64-6.2-Base-RT-GM.raw.xz (sha256 b9af7763c8d63143e31e5f80eb8d06fcc9477a576de8e358ab2e9835ab39d305) +
s| SUSE Multi-Linux Manager s| 5.1.2 s| N/A s| https://www.suse.com/download/suse-manager/[SUSE Multi-Linux Manager ダウンロードページ]
s| K3s s| 1.34.4 s| N/A s| https://github.com/k3s-io/k3s/releases/tag/v1.34.4%2Bk3s1[アップストリームK3sリリース]
s| RKE2 s| 1.34.4 s| N/A s| https://github.com/rancher/rke2/releases/tag/v1.34.4%2Brke2r1[Upstream RKE2 Release]
s| SUSE Rancher Prime s| 2.13.3 s| 2.13.3 s| https://charts.rancher.com/server-charts/prime/index.yaml[Rancher Prime Helm リポジトリ] +
\https://prime.ribs.rancher.io/rancher/v2.13.3/rancher-images.txt[Rancher 2.13.3 Container Images]
s| SUSE Storage (Longhorn) s| 1.10.2 s| 1.10.2 s| https://apps.rancher.io/applications/suse-storage[SUSE Storage Helm リポジトリ] +
\https://apps.rancher.io/applications/suse-storage/components[SUSE Storage Container Images]
s| SUSE Security s| 5.4.9 s| 108.0.2+up2.8.11 s| https://charts.rancher.io/index.yaml[Rancher Charts Helm リポジトリ] +
registry.suse.com/rancher/neuvector-controller:5.4.9 +
registry.suse.com/rancher/neuvector-enforcer:5.4.9 +
registry.suse.com/rancher/neuvector-manager:5.4.9 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.9 +
registry.suse.com/rancher/neuvector-registry-adapter:0.2.2 +
registry.suse.com/rancher/neuvector-scanner:6 +
registry.suse.com/rancher/neuvector-updater:0.0.7
s| Rancher Turtles プロバイダー (CAPI) s| 0.25.4 s| 305.0.5+up0.25.4 s| registry.suse.com/edge/charts/rancher-turtles-providers:305.0.5+up0.25.4 +
registry.rancher.com/rancher/cluster-api-metal3-controller:v1.10.4 +
registry.rancher.com/rancher/cluster-api-metal3-ipam-controller:v1.10.4 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.21.1 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.21.1
s| Metal^3^s| 0.13.0 s| 305.0.23+up0.13.1 s| registry.suse.com/edge/charts/metal3:305.0.23_up0.13.1 +
registry.suse.com/edge/3.5/baremetal-operator:0.11.2.0 +
registry.suse.com/edge/3.5/ironic:32.0.0.1 +
registry.suse.com/edge/3.5/ironic-ipa-downloader:3.0.11 +
registry.suse.com/edge/mariadb:10.11
| MetalLB | 0.15.2 | 305.0.1+up0.15.2 | registry.suse.com/edge/charts/metallb:305.0.1_up0.15.2 +
registry.suse.com/edge/3.5/metallb-controller:v0.15.2 +
registry.suse.com/edge/3.5/metallb-speaker:v0.15.2 +
registry.suse.com/edge/3.5/frr:10.2.1 +
registry.suse.com/edge/3.5/frr-k8s:v0.0.20 +
registry.suse.com/edge/3.5/kube-rbac-proxy:0.19.1
s| Elemental s| 1.8.1 s| 1.8.1 s| registry.suse.com/rancher/elemental-operator-chart:1.8.1 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.8.1 +
registry.suse.com/rancher/elemental-operator:1.8.1
| Elemental ダッシュボード拡張機能 | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/4.0.0/charts/elemental/3.0.1[Elemental 拡張機能 Helm チャート]
| Edge Image Builder | 1.3.3 | N/A | registry.suse.com/edge/3.5/edge-image-builder:1.3.3
| NM Configurator | 0.3.5 | N/A | https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.5[NMConfigurator アップストリームリリース]
| KubeVirt | 1.5.2 | 305.0.1+up0.6.0 | registry.suse.com/edge/charts/kubevirt:305.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportproxy:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportserver:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.5.2
| KubeVirt ダッシュボード拡張機能 | 1.3.3 | 305.0.4+up1.3.3 | registry.suse.com/edge/charts/kubevirt-dashboard-extension:305.0.4_up1.3.3
| コンテナ化データインポーター | 1.62.0 | 305.0.1+up0.6.0 | registry.suse.com/edge/charts/cdi:305.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-importer:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-cloner:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.62.0
| Endpoint Copier Operator | 0.3.0 | 305.0.1+up0.3.0 | registry.suse.com/edge/charts/endpoint-copier-operator:305.0.1_up0.3.0 +
registry.suse.com/edge/3.5/endpoint-copier-operator:0.3.0
| Akri（廃止） | 0.12.20 | 305.0.0+up0.12.20 | registry.suse.com/edge/charts/akri:305.0.0_up0.12.20 +
registry.suse.com/edge/charts/akri-dashboard-extension:305.0.0_up1.3.1 +
registry.suse.com/edge/3.5/akri-agent:v0.12.20 +
registry.suse.com/edge/3.5/akri-controller:v0.12.20 +
registry.suse.com/edge/3.5/akri-debug-echo-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.5/akri-onvif-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.5/akri-opcua-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.5/akri-udev-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.5/akri-webhook-configuration:v0.12.20
| SR-IOV Network Operator | 1.6.0 | 305.0.4+up1.6.0 | registry.suse.com/edge/charts/sriov-network-operator:305.0.4_up1.6.0 +
registry.suse.com/edge/charts/sriov-crd:305.0.4_up1.6.0
| System Upgrade Controller | 0.17.0 | 108.0.0 | https://charts.rancher.io/index.yaml[Rancher Charts Helm リポジトリ] +
registry.suse.com/rancher/system-upgrade-controller:v0.17.0
| Upgrade Controller | 0.1.3 | 305.0.3+up0.1.3 | registry.suse.com/edge/charts/upgrade-controller:305.0.3_up0.1.3 +
registry.suse.com/edge/3.5/upgrade-controller:0.1.3 +
registry.suse.com/edge/3.5/kubectl:1.34.2 +
registry.suse.com/edge/3.5/release-manifest:3.5.1
| Kiwi Builder | 10.2.29.1 | N/A | registry.suse.com/edge/3.5/kiwi-builder:10.2.29.1
|======

[#release-notes-3-5-0]
= リリース 3.5.0

提供開始日:2026年1月21日

フルサポート終了日:2026年7月21日

メンテナンスサポート終了日:2027年7月21日

EOL:2027年7月22日

まとめ:SUSE Edge 3.5.0は、SUSE Edge 3.5リリースストリームにおける最初のリリースです。

== 新機能

* Kubernetes 1.34およびRancher Prime 2.13に更新されました
* Metal3/Ironicバージョンが更新されました
* SUSE Storage (Longhorn) 1.10.1に更新されました https://longhorn.io/docs/1.10.1/[アップストリーム Longhorn リリースノート]
* SUSE Linux Micro 6.2に更新されました https://documentation.suse.com/releasenotes/sle-micro/html/releasenotes_sle-micro_6.2/index.html[SUSE Linux Micro 6.2 リリースノート]
* Elemental 1.8.0に更新されました https://elemental.docs.rancher.com/release-notes/[Elemental リリースノート]
* SR-IOV network operatorが1.6.0に更新されました https://github.com/k8snetworkplumbingwg/sriov-network-operator/releases/tag/v1.6.0[アップストリームリリースノート]。また、関連するイメージは https://www.suse.com/products/base-container-images/[BCIベースイメージ]に基づくようになりました。
* MetalLBが0.15.2に更新されました https://metallb.universe.tf/release-notes/#version-0-15-2[アップストリームリリースノート]

== バグおよびセキュリティ更新

* Rancher Prime 2.13には、いくつかのバグ修正が含まれています https://github.com/rancher/rancher/releases/tag/v2.13.1[アップストリームRancherリリースノート]
* SUSE Storage (Longhorn) 1.10.1には、いくつかのバグ修正が含まれています https://github.com/longhorn/longhorn/releases/tag/v1.10.1[アップストリームLonghornバグ修正]
* SUSE Linux Micro 6.2には、新機能、いくつかのバグ修正、およびいくつかの変更（予測可能なネットワーク名への切り替えなど）が含まれています。 https://documentation.suse.com/releasenotes/sle-micro/html/releasenotes_sle-micro_6.2/index.html[SUSE Linux Micro 6.2リリースノート]を確認してください。
* SR-IOV network operator 1.6.0には、新機能、いくつかのバグ修正、およびいくつかの変更が含まれています。 https://github.com/k8snetworkplumbingwg/sriov-network-operator/releases/tag/v1.6.0[SRIOVアップストリームリリースノート]を確認してください。
* MetalLB 0.15.2には、新機能、いくつかのバグ修正、およびいくつかの変更が含まれています。 https://metallb.universe.tf/release-notes/#version-0-15-2[MetalLBアップストリームリリースノート]を確認してください。
* Metal3 Ironic Python Agent (IPA) は、SUSE Linux Micro 6.2と同じコードベース（カーネルを含む）に準拠しています。これにより、インスペクションデータとデプロイされたOS間でネットワークインタフェース名が一致しない一部の環境での問題が解決されます。

== 既知の問題

* SUSE Edge 3.5 (5.0.6) に含まれているSUSE Multi-Linux Managerのバージョンは、SUSE Linux Micro 6.2をまだサポートしていません。これは将来のSUSE Edge 3.5リリースで更新され、サポートされる予定です。
* デフォルト設定で https://documentation.suse.com/suse-edge/{version-edge}/html/edge/atip-features.html#ptp-telco-config[PTP機能] を実行するには、追加の手順が必要です。
Edge 3.5リリースで正しく動作させるには、ptp4lサービスのオーバーライドに以下を追加する必要があります。
[,bash]
----
[Service]
PrivateDevices=
DevicePolicy=closed
DeviceAllow=/dev/rtc rwm
DeviceAllow=char-ptp rwm
DeviceAllow=/dev/ptp0 rwm
----

これは、`/etc/systemd/system/ptp4l.service.d/override.conf` を編集するか、`systemctl edit ptp4l.service` を実行することで実現できます。これに対する適切な修正は、 https://bugzilla.suse.com/show_bug.cgi?id=1256059[linuxptpパッケージのバグ] が修正された時点で含まれる予定です。

[WARNING]
====
新しいクラスターをデプロイする場合は、<<guides-kiwi-builder-images>> に従って最初に新しいイメージをビルドしてください。これは、{x86-64} および {aarch64} アーキテクチャ、ならびに管理クラスターおよびダウンストリームクラスターの両方を作成するために現在必要とされる最初のステップであるためです。
====

* Edge Image Builderを介してデプロイする場合、`HelmChartConfigs` マニフェストを`kubernetes/manifests`設定ディレクトリに配置すると失敗する可能性があります。代わりに、EIBのos-filesインターフェースを使用して、`HelmChartConfigs` を `/var/lib/rancher/{rke2/k3s}/server/manifests/` に配置することを推奨します。例については <<mgmt-cluster-directory-structure>> を参照してください。 これを行わないと、 https://github.com/rancher/rke2/issues/8357[#8357 RKE2 issue]で説明されているように、初期起動時にノードが `NotReady` 状態のままになる可能性があります。

* RKE2/K3s 1.31、1.32、1.33、および1.34バージョンでは、CNI設定の保存に使用されるディレクトリ `/etc/cni` が、`overlayfs` に関連する特定の条件により、そこに書き込まれるファイルに関する通知を `containerd` にトリガーしない場合があります（ https://github.com/rancher/rke2/issues/8356[#8356 RKE2 issue]を参照）。その結果、RKE2/K3sのデプロイメントがCNIの起動待ちでスタックし、RKE2/K3sノードが `NotReady` 状態のままになります。これは、ノードレベルで `kubectl describe node <affected_node>` を使用して確認できます。

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

回避策として、RKE2の起動前に`/etc/cni`ディレクトリにtmpfsボリュームをマウントすることができます。これにより、containerdが通知を見逃す原因となるoverlayfsの使用を回避でき、ノードが再起動され、ポッドのinitcontainerが再度実行されるたびに設定が書き直されるはずです。EIBを使用している場合、これは`04-tmpfs-cni.sh`スクリプトが`custom/scripts`ディレクトリ内にあり（こちら[https://github.com/suse-edge/edge-image-builder/blob/release-1.2/docs/building-images.md#custom]で説明されている通り）、以下のようになります。

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* Elementalを使用してリモートホストをオンボーディングする際、`dbus.service`と`elemental-system-agent.service`の間で競合状態が発生し、リモートホスト上の`rancher-system-agent.service`が以下のようなエラーで起動に失敗する可能性があります。（詳細は https://github.com/suse-edge/edge-image-builder/issues/784[#784 Edge Image Builder issue]を参照してください。）

[,bash]
----
Sep 19 19:38:07 elementalvm elemental-system-agent[3671]: time="2025-09-19T19:38:07Z" level=info msg="[6b20fe64c854da2639804884b34129bb8f718eb59578111da58d9de1509c24db_1:stderr]: Failed to restart rancher-system-agent.service: Message recipient disconnected from message bus without replying"
----

回避策として、以下のようにsystemdオーバーライドファイルを作成できます。

[,bash]
----
[Unit]
Wants=dbus.service network-online.target
After=dbus.service network-online.target time-sync.target

[Service]
ExecStartPre=/bin/bash -c 'echo "Waiting for dbus to become active..." | systemd-cat -p info -t elemental-system-agent; sleep 15; timeout 300 bash -c "while ! systemctl is-active --quiet dbus.service; do sleep 15; done"'
----

また、`30a-copy-elemental-system-agent-override.sh`という名前のカスタムスクリプトを使用して、EIBの https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/templates/31-elemental-register.sh.tpl[31-elemental-register.sh]スクリプトがcombustionフェーズ中に実行される前に、オーバーライドを`/etc/systemd/system/elemental-system-agent.service.d`に配置することができます。

[,bash]
----
#!/bin/bash

/bin/mkdir -p /etc/systemd/system/elemental-system-agent.service.d
/bin/cp -f elemental-system-agent-override.conf /etc/systemd/system/elemental-system-agent.service.d/override.conf
----

== コンポーネントのバージョン

次の表は、3.5.0リリースを構成する個々のコンポーネントについて、バージョン、Helmチャートのバージョン（該当する場合）、およびバイナリ形式でリリースされたアーティファクトの取得元を説明しています。使用方法やデプロイの例については、関連するドキュメントに従ってください。

|======
| 名前 | バージョン | Helmチャートのバージョン | アーティファクトの場所 (URL/イメージ)
| SUSE Linux Micro | 6.2 (latest) | N/A | https://www.suse.com/download/sle-micro/[SUSE Linux Micro ダウンロードページ] +
SL-Micro.x86_64-6.2-Base-SelfInstall-GM.install.iso (sha256 76390cec4537821d90975d924bf9d7575c9912da89fa460383eff0c623fd403e) +
SL-Micro.x86_64-6.2-Base-RT-SelfInstall-GM.install.iso (sha256 8f4d03c6953966174efb4c4b176cbe6dd5cab6e2a406033fc5c2bf6884da8b5d) +
SL-Micro.x86_64-6.2-Base-GM.raw.xz (sha256 bea3ac202b54ee29fabc28568f50c86d34939cf861679f21a91dfbae9c54c92e) +
SL-Micro.x86_64-6.2-Base-RT-GM.raw.xz (sha256 b9af7763c8d63143e31e5f80eb8d06fcc9477a576de8e358ab2e9835ab39d305) +
| SUSE Multi-Linux Manager | 5.0.6 | N/A | https://www.suse.com/download/suse-manager/[SUSE Multi-Linux Manager ダウンロードページ]
| K3s | 1.34.2 | N/A | https://github.com/k3s-io/k3s/releases/tag/v1.34.2%2Bk3s1[アップストリーム K3s リリース]
| RKE2 | 1.34.2 | N/A | https://github.com/rancher/rke2/releases/tag/v1.34.2%2Brke2r1[Upstream RKE2 Release]
| SUSE Rancher Prime | 2.13.1 | 2.13.1 | https://charts.rancher.com/server-charts/prime/index.yaml[Rancher Prime Helm リポジトリ] +
\https://prime.ribs.rancher.io/rancher/v2.13.1/rancher-images.txt[Rancher 2.13.1 Container Images]
| SUSE Storage (Longhorn) | 1.10.1 | 1.10.1 | https://apps.rancher.io/applications/suse-storage[SUSE Storage Helm リポジトリ] +
\https://apps.rancher.io/applications/suse-storage/components[SUSE Storage Container Images]
| SUSE Security | 5.4.8 | 108.0.1+up2.8.10 | https://charts.rancher.io/index.yaml[Rancher Charts Helm リポジトリ] +
registry.suse.com/rancher/neuvector-controller:5.4.8 +
registry.suse.com/rancher/neuvector-enforcer:5.4.8 +
registry.suse.com/rancher/neuvector-manager:5.4.8 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.9 +
registry.suse.com/rancher/neuvector-registry-adapter:0.2.2 +
registry.suse.com/rancher/neuvector-scanner:6 +
registry.suse.com/rancher/neuvector-updater:0.0.7
| Rancher Turtles プロバイダー (CAPI) | 0.25.1 | 305.0.4+up0.25.1 | registry.suse.com/edge/charts/rancher-turtles-providers:305.0.4+up0.25.1 +
registry.rancher.com/rancher/cluster-api-metal3-controller:v1.10.4 +
registry.rancher.com/rancher/cluster-api-metal3-ipam-controller:v1.10.4 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.21.1 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.21.1
| Metal^3^| 0.13.0 | 305.0.21+up0.13.0 | registry.suse.com/edge/charts/metal3:305.0.21_up0.13.0 +
registry.suse.com/edge/3.5/baremetal-operator:0.11.2.0 +
registry.suse.com/edge/3.5/ironic:32.0.0.1 +
registry.suse.com/edge/3.5/ironic-ipa-downloader:3.0.10 +
registry.suse.com/edge/mariadb:10.11
| MetalLB | 0.15.2 | 305.0.1+up0.15.2 | registry.suse.com/edge/charts/metallb:305.0.1_up0.15.2 +
registry.suse.com/edge/3.5/metallb-controller:v0.15.2 +
registry.suse.com/edge/3.5/metallb-speaker:v0.15.2 +
registry.suse.com/edge/3.5/frr:10.2.1 +
registry.suse.com/edge/3.5/frr-k8s:v0.0.20 +
registry.suse.com/edge/3.5/kube-rbac-proxy:0.19.1
| Elemental | 1.8.0 | 1.8.0 | registry.suse.com/rancher/elemental-operator-chart:1.8.0 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.8.0 +
registry.suse.com/rancher/elemental-operator:1.8.0
| Elemental ダッシュボード拡張機能 | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/4.0.0/charts/elemental/3.0.1[Elemental 拡張機能 Helmチャート]
| Edge Image Builder | 1.3.2 | N/A | registry.suse.com/edge/3.5/edge-image-builder:1.3.2
| NM Configurator | 0.3.5 | N/A | https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.5[NMConfigurator アップストリーム リリース]
| KubeVirt | 1.5.2 | 305.0.1+up0.6.0 | registry.suse.com/edge/charts/kubevirt:305.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportproxy:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportserver:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.5.2
| KubeVirt ダッシュボード拡張機能 | 1.3.3 | 305.0.4+up1.3.3 | registry.suse.com/edge/charts/kubevirt-dashboard-extension:305.0.4_up1.3.3
| コンテナ化データインポーター | 1.62.0 | 305.0.1+up0.6.0 | registry.suse.com/edge/charts/cdi:305.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-importer:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-cloner:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.62.0
| Endpoint Copier Operator | 0.3.0 | 305.0.1+up0.3.0 | registry.suse.com/edge/charts/endpoint-copier-operator:305.0.1_up0.3.0 +
registry.suse.com/edge/3.5/endpoint-copier-operator:0.3.0
| Akri (廃止) | 0.12.20 | 305.0.0+up0.12.20 | registry.suse.com/edge/charts/akri:305.0.0_up0.12.20 +
registry.suse.com/edge/charts/akri-dashboard-extension:305.0.0_up1.3.1 +
registry.suse.com/edge/3.5/akri-agent:v0.12.20 +
registry.suse.com/edge/3.5/akri-controller:v0.12.20 +
registry.suse.com/edge/3.5/akri-debug-echo-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.5/akri-onvif-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.5/akri-opcua-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.5/akri-udev-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.5/akri-webhook-configuration:v0.12.20
| SR-IOV Network Operator | 1.6.0 | 305.0.4+up1.6.0 | registry.suse.com/edge/charts/sriov-network-operator:305.0.4_up1.6.0 +
registry.suse.com/edge/charts/sriov-crd:305.0.4_up1.6.0
| System Upgrade Controller | 0.17.0 | 108.0.0 | https://charts.rancher.io/index.yaml[Rancher Charts Helm リポジトリ] +
registry.suse.com/rancher/system-upgrade-controller:v0.17.0
| Upgrade Controller | 0.1.3 | 305.0.2+up0.1.3 | registry.suse.com/edge/charts/upgrade-controller:305.0.3_up0.1.3 +
registry.suse.com/edge/3.5/upgrade-controller:0.1.3 +
registry.suse.com/edge/3.5/kubectl:1.34.2 +
registry.suse.com/edge/3.5/release-manifest:3.5.0
| Kiwi Builder | 10.2.29.1 | N/A | registry.suse.com/edge/3.5/kiwi-builder:10.2.29.1
|======

= 廃止された機能

特に記載がない限り、これらは3.4.0リリースおよびそれ以降のすべてのzストリームバージョンに適用されます。

* Akriは以前のEdgeリリースにおいてテクノロジープレビューとして提供されていましたが、現在は廃止されています。 将来のリリースで削除される予定です。

[#tech-previews]
= 技術プレビュー

特に記載がない限り、これらは3.4.0リリースおよびそれ以降のすべてのzストリームバージョンに適用されます。

* シングルスタックIPv6のデプロイメントはテクノロジープレビューとして提供されており、標準的なサポート範囲の対象外です。
* ダウンストリームデプロイメントにおけるPrecision Time Protocol (PTP)はテクノロジープレビューとして提供されており、標準的なサポート範囲の対象外です。
* MetalLBのBGPモードはテクノロジープレビューとして提供されており、標準的なサポート範囲の対象外です。

= コンポーネントの検証

上記のコンポーネントは、ソフトウェア部品表（SBOM）データを使用して検証できます。例えば、以下のように`cosign`を使用します。

https://www.suse.com/support/security/keys/[SUSE署名キーソース]からSUSE Edgeコンテナの公開鍵をダウンロードします：

[,bash]
----
include::key.sh[]
----

例えば`crane`を使用して、コンテナイメージのハッシュを検証します。

[,bash]
----
> crane digest registry.suse.com/edge/3.4/baremetal-operator:0.10.2.1 --platform linux/amd64
sha256:310d939f8ae4b547710195b9671a4e9ff417420c0856103dd728b051788b5374
----

NOTE: マルチアーキテクチャイメージの場合は、ダイジェストを取得する際にプラットフォームを指定する必要もあります。例: `--platform linux/amd64` または `--platform linux/arm64`。これを行わないと、次のステップ (`Error: no matching attestations`) でエラーが発生します。

次のコマンドで確認します: `cosign`

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/3.4/baremetal-operator@sha256:310d939f8ae4b547710195b9671a4e9ff417420c0856103dd728b051788b5374 > /dev/null
#
Verification for registry.suse.com/edge/3.4/baremetal-operator@sha256:310d939f8ae4b547710195b9671a4e9ff417420c0856103dd728b051788b5374 --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - The signatures were verified against the specified public key
----

https://www.suse.com/support/security/sbom/[SUSE SBOMドキュメント]に記載されている手順に従って、SBOMデータを抽出します。

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/3.4/baremetal-operator@sha256:310d939f8ae4b547710195b9671a4e9ff417420c0856103dd728b051788b5374 | jq '.payload | @base64d | fromjson | .predicate'
----

= アップグレード手順

新しいリリースへのアップグレード方法の詳細については、<<day-2-operations>>を参照してください。

= 製品サポートライフサイクル

SUSE Edgeは、実績あるテクノロジーリーダーであるSUSEが提供する、受賞歴のあるサポートに支えられています。詳細については、 https://www.suse.com/lifecycle[https://www.suse.com/lifecycle]および https://www.suse.com/support/policy.html[https://www.suse.com/support/policy.html]のサポートポリシーページを参照してください。サポートケースの起票方法、SUSEによる重大度レベルの分類方法、またはサポート範囲についてご質問がある場合は、 https://www.suse.com/support/handbook/[https://www.suse.com/support/handbook/]のテクニカルサポートハンドブックを参照してください。

SUSE Edge \"3.5\" は18か月間のプロダクションサポートが提供され、最初の6か月間は「フルサポート」、その後の12か月間は「メンテナンスサポート」となります。 これらのサポートフェーズが終了すると、製品は「サービス終了」(EOL) となり、サポートは提供されなくなります。ライフサイクルフェーズの詳細については、以下の表を参照してください。

|======
| *フルサポート (6か月)*| フルサポート期間中は、緊急および選択された優先度の高いバグ修正がリリースされます。その他のすべてのパッチ (緊急ではないもの、機能強化、新機能) は、通常のリリーススケジュールに従ってリリースされます。
| *メンテナンスサポート (12か月)*| この期間中は、重大な修正のみがパッチを通じてリリースされます。その他のバグ修正はSUSEの判断でリリースされる場合がありますが、期待はしないでください。
| *サービス終了 (EOL)* | 製品リリースがサービス終了日を迎えると、お客様は製品ライセンス契約の条件の範囲内で製品を引き続き使用できます。
SUSEのサポートプランは、サービス終了日（EOL）を過ぎた製品リリースには適用されません。
|======

明記されていない限り、リストされているすべてのコンポーネントは一般提供（GA）されており、SUSEの標準的なサポート範囲に含まれます。一部のコンポーネントは「Technology Preview」としてリストされている場合があります。これは、SUSEがお客様に評価目的でGA前の機能へのアクセスを提供するものであり、標準的なサポートポリシーの対象外であり、本番環境での使用は推奨されません。SUSEは、Technology Previewコンポーネントに対する改善に関するフィードバックや提案を大いに歓迎しますが、お客様のニーズを満たさない場合や、当社が要求する成熟度に達しない場合、一般提供（GA）される前にTechnology Preview機能を廃止する権利を留保します。

SUSEは、時折、機能を廃止したり、API仕様を変更したりする場合があることにご留意ください。機能の廃止やAPI変更の理由には、機能が更新または新しい実装に置き換えられること、新しい機能セット、アップストリームテクノロジーが利用できなくなること、またはアップストリームコミュニティが互換性のない変更を導入したことなどが含まれます。これは特定のマイナーリリース（x.z）内では発生しないことを意図しており、すべてのz ストリームリリースはAPIの互換性と機能性を維持します。SUSEは、サービスの中断を最小限に抑えるため、リリースノート内で十分な通知期間をもって廃止の警告を提供し、回避策、提案、および緩和策を提供するよう努めます。

SUSE Edgeチームは、コミュニティからのフィードバックも歓迎しており、問題は https://www.github.com/suse-edge[https://www.github.com/suse-edge]内の各リポジトリで提起できます。

= ソースコードの入手

本SUSE製品には、GNU一般公衆利用許諾契約書（GPL）およびその他のさまざまなオープンソースに基づいてSUSEにライセンス供与された素材が含まれています。GPLでは、SUSEはGPLライセンス対象の素材に対応するソースコードを提供することが義務付けられており、SUSEはその他すべてのオープンソースの要件を遵守しています。そのため、SUSEはすべてのソースコードを利用可能にしており、一般的にSUSE Edge GitHubリポジトリ（ https://www.github.com/suse-edge）、依存コンポーネントについてはSUSE Rancher GitHubリポジトリ（ https://www.github.com/rancher）、特にSUSE Linux Microについては、ソースコードは https://www.suse.com/download/sle-micro/[https://www.suse.com/download/sle-micro]の「Medium 2」からダウンロードできます。

= 保証と著作権

SUSEは、本書の内容または使用に関していかなる表明も保証も行わず、特に、商業性および特定目的への適合性について、明示的か黙示的かを問わず、いかなる保証も否認します。さらに、SUSEは、本書をいつでも改訂またはその内容を変更する権利を留保し、何人に対しても当該の改訂または変更について通知する義務を負わないものとします。

さらに、SUSEは、すべてのソフトウェアについて、いかなる表明または保証も行わず、特に、ソフトウェアの商業性および特定目的への適合性について、明示的か黙示的かを問わず、いかなる保証も否認します。さらに、SUSEは、SUSE製ソフトウェアの一部または全部をいつでも変更する権利を留保し、何人に対しても当該の変更について通知する義務を負わないものとします。

本契約の下で提供される製品または技術情報はすべて、米国の輸出管理規定およびその他の国の輸出関連法規の制限を受けます。お客様は、すべての輸出管理規制を遵守し、成果物の輸出、再輸出、または輸入に必要なすべての許可または等級を取得することに同意するものとします。お客様は、現在の米国の輸出除外リストに掲載されている企業、および米国の輸出管理規定で指定された輸出禁止国またはテロリスト国に本製品を輸出または再輸出しないことに同意するものとします。お客様は、成果物を、禁止されている核兵器、ミサイル、または化学兵器・生物兵器の最終用途に使用しないことに同意するものとします。SUSEソフトウェアの輸出に関する詳細は、 https://www.suse.com/company/legal/[https://www.suse.com/company/legal/]を参照してください。SUSEは、必要な輸出許可の取得をお客様が怠った場合の責任は問われないものとします。

*Copyright © 2024 SUSE LLC.*

このリリースノートドキュメントは、Creative Commons Attribution-NoDerivatives 4.0 International License (CC-BY-ND-4.0) の下でライセンスされています。このドキュメントとともにライセンスのコピーを受け取っているはずです。そうでない場合は、 https://creativecommons.org/licenses/by-nd/4.0/[https://creativecommons.org/licenses/by-nd/4.0/]を参照してください。

SUSEは、本書に記載されている製品に組み込まれている技術に関連する知的財産権を有しています。特に、これらの知的財産権には、 https://www.suse.com/company/legal/[https://www.suse.com/company/legal/]に記載されている1つまたは複数の米国特許、および米国ならびに他の国における1つまたは複数のその他の特許や出願中の特許（これらに限定されません）が含まれている場合があります。

SUSEの商標については、SUSEの商標およびサービスマークリスト (https://www.suse.com/company/legal/[https://www.suse.com/company/legal/]) を参照してください。サードパーティ各社とその製品の商標は、所有者であるそれぞれの会社に所属します。SUSEのブランド情報および使用要件については、 https://brand.suse.com/[https://brand.suse.com/]で公開されているガイドラインを参照してください。
