[#{cluster-type}-day2-upgrade-controller]
== Upgrade Controller
:revdate: 2025-01-16
:revnumber: 3.7
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[IMPORTANT]
====
The `Upgrade Controller` currently only supports `Day 2` operations for *non air-gapped management* clusters.
====

This section covers how to perform the various `Day 2` operations related to upgrading your `management` cluster from one `{product}` platform version to another.

The `Day 2` operations are automated by the <<components-upgrade-controller, Upgrade Controller>> and include:

* <<components-slmicro, SUSE Linux Micro>> OS upgrade
ifeval::["{flavor}" == "edge"]
* <<components-rke2>> or <<components-k3s>> Kubernetes upgrade
endif::[]
ifeval::["{flavor}" == "telco"]
* <<components-rke2>> Kubernetes upgrade
endif::[]
* SUSE additional components (SUSE Rancher Prime, SUSE Security, etc.) upgrade

=== Prerequisites

Before upgrading your `management` cluster, the following prerequisites must be met:

. `SCC registered nodes` - ensure your cluster nodes' OS are registered with a subscription key that supports the OS version specified in the `{product}` <<release-notes,release>> you intend to upgrade to.

. `Upgrade Controller` - make sure that the `Upgrade Controller` has been deployed on your `management` cluster. For installation steps, refer to <<components-upgrade-controller-installation>>.

=== Upgrade

. Determine the `{product}` <<release-notes,release>> version that you wish to upgrade your `management` cluster to.

. In the `management` cluster, deploy an `UpgradePlan` that specifies the desired `release version`. The `UpgradePlan` must be deployed in the namespace of the `Upgrade Controller`.
+
[,bash]
----
kubectl apply -n <upgrade_controller_namespace> -f - <<EOF
apiVersion: lifecycle.suse.com/v1alpha1
kind: UpgradePlan
metadata:
  name: upgrade-plan-mgmt
  namespace: upgrade-controller-system  # replaces it if the upgrade controller has been deployed in a different namespace
spec:
  # Version retrieved from release notes
  releaseVersion: 3.X.Y
EOF
----
+
[NOTE]
====
There may be use-cases where you would want to make additional configurations over the `UpgradePlan`. For all possible configurations, refer to <<components-upgrade-controller-extensions-upgrade-plan>>.
====

. Deploying the `UpgradePlan` to the `Upgrade Controller's` namespace will begin the `upgrade process`.
+
[NOTE]
====
For more information on the actual `upgrade process`, refer to <<components-upgrade-controller-how>>.

For information on how to track the `upgrade process`, refer to <<components-upgrade-controller-how-track>>.
====

=== Post-Upgrade Steps
`{product}` upgrades from latest `{previous-edge-version}` z-stream to `{static-edge-version}` require a final manual steps to be performed after the `Upgrade Controller` has completed the upgrade process, related to some Helm parameters changes in the `rke2-traefik` Helm chart included in `{product}` `{static-edge-version}` release.

* apply the following changes in the `helmchartconfigs.helm.cattle.io/rke2-traefik` API object in `kube-system` namespace (or, in case that API object does not exist, apply them in the `helmcharts.helm.cattle.io/rke2-traefik` API object):
[NOTE]
====
Use the `HelmChartConfig` (or `HelmChart`) manifests to apply these changes as shown below, to assure the `Upgrade Controller` will keep them in future Management cluster upgrades.
====

[,shell]
----
# You can use `kubectl edit', `kubectl patch` or `kubectl apply` commands to apply the changes indicated below
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-traefik
  namespace: kube-system
spec:
  failurePolicy: reinstall
  valuesContent: |-
    ingressClass:
      isDefaultClass: true
    ports:
      web:
        hostPort: null
        exposedPort: 80
      websecure:
        hostPort: null
        exposedPort: 443
    service:
      enabled: true
      # type: LoadBalancer              # CHANGE_1: This Helm parameter has been REMOVED
      # ipFamilyPolicy: PreferDualStack # CHANGE_2: This Helm parameter has been REMOVED
      spec:
        type: LoadBalancer              # CHANGE_3: NEW Helm parameter replacing the old/removed one (above)
        ipFamilyPolicy: PreferDualStack # CHANGE_4: NEW Helm parameter replacing the old/removed one (above)
        externalTrafficPolicy: Local
        allocateLoadBalancerNodePorts: false
    providers:
      kubernetesIngressNGINX:           # CHANGE_5: NEW Helm parameter replacing the old/removed "KubernetesIngressNginx"
        enabled: true
        ingressClass: "rke2-ingress-nginx-migration"
        controllerClass: "rke2.​cattle.​io/ingress-nginx-migration"
EOF
----

Or, in case the `helmchartconfigs.helm.cattle.io/rke2-traefik` API object in the `kube-system` namespace does not exist:

[,shell]
----
# You can use `kubectl edit', `kubectl patch` or `kubectl apply` commands to apply the changes indicated below
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rke2-traefik
  namespace: kube-system
spec:
  chart: rke2-traefik
  version: {rke2-traefik Helm chart version}
  repo: https://rke2-charts.rancher.io
  bootstrap: false
  failurePolicy: reinstall
  backOffLimit: 20
  targetNamespace: kube-system
  set:
    global.cattle.systemDefaultRegistry: registry.rancher.com
    global.rke2DataDir: /var/lib/rancher/rke2
    global.systemDefaultRegistry: registry.rancher.com
  valuesContent: |-
    ingressClass:
      isDefaultClass: true
    ports:
      web:
        hostPort: null
        exposedPort: 80
      websecure:
        hostPort: null
        exposedPort: 443
    service:
      enabled: true
      # type: LoadBalancer              # CHANGE_1: This Helm parameter has been REMOVED
      # ipFamilyPolicy: PreferDualStack # CHANGE_2: This Helm parameter has been REMOVED
      spec:
        type: LoadBalancer              # CHANGE_3: NEW Helm parameter replacing the old/removed one (above)
        ipFamilyPolicy: PreferDualStack # CHANGE_4: NEW Helm parameter replacing the old/removed one (above)
        externalTrafficPolicy: Local
        allocateLoadBalancerNodePorts: false
    providers:
      kubernetesIngressNGINX:           # CHANGE_5: NEW Helm parameter replacing the old/removed "KubernetesIngressNginx"
        enabled: true
        ingressClass: "rke2-ingress-nginx-migration"
        controllerClass: "rke2.​cattle.​io/ingress-nginx-migration"
EOF
----

The `{rke2-traefik Helm chart version}` shown above is the one provided by the RKE2/k3s release used in the `{product}`
 `{static-edge-version}` release to upgrade to (you can get it from the corresponding https://github.com/rancher/rke2/releases/[RKE2 release page] 
 / https://github.com/k3s-io/k3s/releases/[k3s release page]).
