[#release-notes]

= Abstract
ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

SUSE Edge 3.0 is a tightly integrated and comprehensively validated end-to-end solution for addressing the unique challenges of the deployment of infrastructure and cloud-native applications at the edge. Its driving focus is to provide an opinionated, yet highly flexible, highly scalable, and secure platform that spans initial deployment image building, node provisioning and onboarding, application deployment, observability, and lifecycle management.

The solution is designed with the notion that there is no "one-size-fits-all" edge platform due to our customers’ widely varying requirements and expectations. Edge deployments push us to solve, and continually evolve, some of the most challenging problems, including massive scalability, restricted network availability, physical space constraints, new security threats and attack vectors, variations in hardware architecture and system resources, the requirement to deploy and interface with legacy infrastructure and applications, and customer solutions that have extended lifespans.

SUSE Edge is built on best-of-breed open source software from the ground up, consistent with both our 30-year history in delivering secure, stable, and certified SUSE Linux platforms and our experience in providing highly scalable and feature-rich Kubernetes management with our Rancher portfolio. SUSE Edge builds on-top of these capabilities to deliver functionality that can address a wide number of market segments, including retail, medical, transportation, logistics, telecommunications, smart manufacturing, and Industrial IoT.

NOTE: SUSE Adaptive Telco Infrastructure Platform (ATIP) is a derivative (or downstream product) of SUSE Edge, with additional optimizations and components that enable the platform to address the requirements found in telecommunications use-cases. Unless explicitly stated, all of the release notes are applicable for both SUSE Edge 3.0, and SUSE ATIP 3.0.

= About

These Release Notes are, unless explicitly specified and explained, identical across all architectures, and the most recent version, along with the release notes of all other SUSE products are always available online at https://www.suse.com/releasenotes[https://www.suse.com/releasenotes].

Entries are only listed once, but they can be referenced in several places if they are important and belong to more than one section. Release notes usually only list changes that happened between two subsequent releases. Certain important entries from the release notes of previous product versions may be repeated. To make these entries easier to identify, they contain a note to that effect.

However, repeated entries are provided as a courtesy only. Therefore, if you are skipping one or releases, check the release notes of the skipped releases also. If you are only reading the release notes of the current release, you could miss important changes that may affect system behavior. SUSE Edge versions are defined as x.y.z, where 'x' denotes the major version, 'y' denotes the minor, and 'z' denotes the patch version, also known as the "z-stream". SUSE Edge product lifecycles are defined based around a given minor release, e.g. "3.0", but ship with subsequent patch updates through its lifecycle, e.g. "3.0.1".

NOTE: SUSE Edge z-stream releases are tightly integrated and thoroughly tested as a versioned stack. Upgrade of any individual components to a different versions to those listed above is likely to result in system downtime. While it's possible to run Edge clusters in untested configurations, it is not recommended, and it may take longer to provide resolution through the support channels.

= Release 3.0.2

Availability Date: 16th August 2024

Summary: SUSE Edge 3.0.2 is the second z-stream release in the SUSE Edge 3.0 portfolio.

== New Features

* The Metal^3^ chart now supports static network configuration without any `mac-address`: https://github.com/suse-edge/charts/pull/134[SUSE Edge issue #134]
* KubeVirt is updated from `1.1.1` to `1.2.2` for details of new features refer to the: https://github.com/kubevirt/kubevirt/releases[Upstream Release Notes]

== Bug & Security Fixes

* The Metal^3^ chart fixes an issue where host reprovisioning may use stale static network configuration: https://github.com/suse-edge/charts/pull/133[SUSE Edge issue #133]
* The RKE2 Cluster API provider fixes an issue when specifying TLS configuration for a local registry: https://github.com/rancher/cluster-api-provider-rke2/pull/357[RKE2 Provider issue #357]
* The RKE2 Cluster API provider fixes an issue causing rke2-install to error after system reboot: https://github.com/rancher/cluster-api-provider-rke2/pull/346[RKE2 Provider issue #346]
* KubeVirt is updated to include several security fixes: https://www.suse.com/support/update/announcement/2024/suse-su-20242669-1[Kubevirt Update]

== Components Versions

The following table describes the individual components that make up the 3.0.2 release, including the version, the Helm chart version (if applicable), and from where the released artifact can be pulled in the binary format. Please follow the associated documentation for usage and deployment examples. Note that items in bold are highlighted changes from the previous z-stream release.

|======
| Name | Version | Helm Chart Version | Artifact Location (URL/Image)
| SLE Micro | 5.5 (latest) | N/A | https://www.suse.com/download/sle-micro/[SLE Micro Download Page] +
SLE-Micro.x86_64-5.5.0-Default-SelfInstall-GM2.install.iso (sha256 4f672a4a0f8ec421e7c25797def05598037c56b7f306283566a9f921bdce904a) +
SLE-Micro.x86_64-5.5.0-Default-RT-SelfInstall-GM2.install.iso (sha256 527a5a7cdbf11e3e6238e386533755257676ad8b4c80be3b159d0904cb637678) +
SLE-Micro.x86_64-5.5.0-Default-GM.raw.xz (sha256 13243a737ca219bad6a7aa41fa747c06e8b825fef10a756cf4d575f4493ed68b) +
SLE-Micro.x86_64-5.5.0-Default-RT-GM.raw.xz (sha256 6c2af94e7ac785c8f6a276032c8e6a4b493c294e6cd72809c75089522f01bc93)
| SUSE Manager | 4.3.11 | N/A | https://www.suse.com/download/suse-manager/[SUSE Manager Download Page]
s| K3s s| 1.28.10 | N/A | https://github.com/k3s-io/k3s/releases/tag/v1.28.10%2Bk3s1[Upstream K3s Release]
s| RKE2 s| 1.28.10 | N/A | https://github.com/rancher/rke2/releases/tag/v1.28.10%2Brke2r1[Upstream RKE2 Release]
s| Rancher Prime s| 2.8.5 s| 2.8.5 | https://github.com/rancher/rancher/releases/download/v2.8.5/rancher-images.txt[Rancher 2.8.5 Images] +
 https://charts.rancher.com/server-charts/prime[Rancher Prime Helm Repo]
| Longhorn | 1.6.1 | 103.3.0 | https://raw.githubusercontent.com/longhorn/longhorn/v1.6.1/deploy/longhorn-images.txt[Longhorn 1.6.1 Images] +
https://charts.longhorn.io[Longhorn Helm Repo]
| NM Configurator | 0.3.0 | N/A | https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.0[NMConfigurator Upstream Release]
| NeuVector| 5.3.2 | 103.0.3 | registry.suse.com/rancher/mirrored-neuvector-controller:5.3.2 +
registry.suse.com/rancher/mirrored-neuvector-enforcer:5.3.2 +
registry.suse.com/rancher/mirrored-neuvector-manager:5.3.2 +
registry.suse.com/rancher/mirrored-neuvector-prometheus-exporter:5.3.2 +
registry.suse.com/rancher mirrored-neuvector-registry-adapter:0.1.1-s1 +
registry.suse.com/rancher/mirrored-neuvector-scanner:latest +
registry.suse.com/rancher/mirrored-neuvector-updater:latest
s| Cluster API (CAPI) | 1.6.2 | N/A | registry.suse.com/edge/cluster-api-controller:1.6.2 +
registry.suse.com/edge/cluster-api-provider-metal3:1.6.0 +
*registry.suse.com/edge/cluster-api-provider-rke2-bootstrap:0.4.1* +
*registry.suse.com/edge/cluster-api-provider-rke2-controlplane:0.4.1*
s| Metal^3^ s| 1.16.0 s| 0.7.3 | registry.suse.com/edge/metal3-chart:0.7.3 +
registry.suse.com/edge/baremetal-operator:0.5.1 +
registry.suse.com/edge/ip-address-manager:1.6.0 +
registry.suse.com/edge/ironic:23.0.2.1 +
*registry.suse.com/edge/ironic-ipa-downloader:1.3.4* +
registry.suse.com/edge/kube-rbac-proxy:v0.14.2 +.1
registry.suse.com/edge/mariadb:10.6.15.1
| MetalLB | 0.14.3 | 0.14.3 | registry.suse.com/edge/metallb-chart:0.14.3 +
registry.suse.com/edge/metallb-controller:v0.14.3 +
registry.suse.com/edge/metallb-speaker:v0.14.3 +
registry.suse.com/edge/frr:8.4 +
registry.suse.com/edge/frr-k8s:v0.0.8
| Elemental | 1.4.4 | 1.4.4 | registry.suse.com/rancher/elemental-operator-chart:1.4.4 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.4.4 +
registry.suse.com/rancher/elemental-operator:1.4.4
| Edge Image Builder | 1.0.2 | N/A | registry.suse.com/edge/edge-image-builder:1.0.2
s| KubeVirt s| 1.2.2 s| 0.3.0 s| registry.suse.com/edge/kubevirt-chart:0.3.0 +
registry.suse.com/suse/sles/15.5/virt-operator:1.2.2 +
registry.suse.com/suse/sles/15.5/virt-api:1.2.2 +
registry.suse.com/suse/sles/15.5/virt-controller:1.2.2 +
registry.suse.com/suse/sles/15.5/virt-exportproxy:1.2.2 +
registry.suse.com/suse/sles/15.5/virt-exportserver:1.2.2 +
registry.suse.com/suse/sles/15.5/virt-handler:1.2.2 +
registry.suse.com/suse/sles/15.5/virt-launcher:1.2.2
| KubeVirt Dashboard Extension | 1.0.0 | 1.0.0 | registry.suse.com/edge/kubevirt-dashboard-extension-chart:1.0.0
s| Containerized Data Importer s| 1.59.0 s| 0.3.0 s| registry.suse.com/edge/cdi-chart:0.3.0 +
registry.suse.com/suse/sles/15.5/cdi-operator:1.59.0 +
registry.suse.com/suse/sles/15.5/cdi-controller:1.59.0 +
registry.suse.com/suse/sles/15.5/cdi-importer:1.59.0 +
registry.suse.com/suse/sles/15.5/cdi-cloner:1.59.0 +
registry.suse.com/suse/sles/15.5/cdi-apiserver:1.59.0 +
registry.suse.com/suse/sles/15.5/cdi-uploadserver:1.59.0 +
registry.suse.com/suse/sles/15.5/cdi-uploadproxy:1.59.0
| Endpoint Copier Operator | 0.2.0 | 0.2.0 | registry.suse.com/edge/endpoint-copier-operator:v0.2.0 +
registry.suse.com/edge/endpoint-copier-operator-chart:0.2.0
| Akri (Tech Preview) | 0.12.20 | 0.12.20 | registry.suse.com/edge/akri-chart:0.12.20 +
registry.suse.com/edge/akri-dashboard-extension-chart:1.0.0 +
registry.suse.com/edge/akri-agent:v0.12.20 +
registry.suse.com/edge/akri-controller:v0.12.20 +
registry.suse.com/edge/akri-debug-echo-discovery-handler:v0.12.20 +
registry.suse.com/edge/akri-onvif-discovery-handler:v0.12.20 +
registry.suse.com/edge/akri-opcua-discovery-handler:v0.12.20 +
registry.suse.com/edge/akri-udev-discovery-handler:v0.12.20 +
registry.suse.com/edge/akri-webhook-configuration:v0.12.20
| SR-IOV Network Operator | 1.2.2 | 1.2.2+up0.1.0 | registry.suse.com/edge/sriov-network-operator-chart:1.2.2 +
registry.suse.com/edge/sriov-crd-chart:1.2.2
|======

= Release 3.0.1

Availability Date: 14th June 2024

Summary: SUSE Edge 3.0.1 is the first z-stream release in the SUSE Edge 3.0 portfolio.

== New Features

* Elemental and EIB now support node reset for unmanaged hosts
* SR-IOV Network Operator chart is now included
* The Metal^3^ chart now supports providing additional trusted CA certificates
* NM Configurator now supports applying unified configurations without any MAC specification
* Added `version` subcommand to EIB; the version will also automatically be included in each image built by EIB

== Bug & Security Fixes

* EIB now automatically sets the execute bit on custom scripts: https://github.com/suse-edge/edge-image-builder/issues/429[SUSE Edge issue #429]
* EIB now supports disks which are >512 byte sector size: https://github.com/suse-edge/edge-image-builder/issues/447[SUSE Edge issue #447]
* Enhance EIB's ability to detect container images in Helm charts: https://github.com/suse-edge/edge-image-builder/issues/442[SUSE Edge issue #442]

== Components Versions

The following table describes the individual components that make up the 3.0.1 release, including the version, the Helm chart version (if applicable), and where the released artifact can be pulled from in binary format. Please follow the associated documentation for usage and deployment examples. Note that items in bold are highlighted changes from the previous z-stream release.

|======
| Name | Version | Helm Chart Version | Artifact Location (URL/Image)
| SLE Micro | 5.5 (latest) | N/A | https://www.suse.com/download/sle-micro/[SLE Micro Download Page] +
SLE-Micro.x86_64-5.5.0-Default-SelfInstall-GM2.install.iso (sha256 4f672a4a0f8ec421e7c25797def05598037c56b7f306283566a9f921bdce904a) +
SLE-Micro.x86_64-5.5.0-Default-RT-SelfInstall-GM2.install.iso (sha256 527a5a7cdbf11e3e6238e386533755257676ad8b4c80be3b159d0904cb637678) +
SLE-Micro.x86_64-5.5.0-Default-GM.raw.xz (sha256 13243a737ca219bad6a7aa41fa747c06e8b825fef10a756cf4d575f4493ed68b) +
SLE-Micro.x86_64-5.5.0-Default-RT-GM.raw.xz (sha256 6c2af94e7ac785c8f6a276032c8e6a4b493c294e6cd72809c75089522f01bc93)
| SUSE Manager | 4.3.11 | N/A | https://www.suse.com/download/suse-manager/[SUSE Manager Download Page]
s| K3s s| 1.28.9 | N/A | https://github.com/k3s-io/k3s/releases/tag/v1.28.9%2Bk3s1[Upstream K3s Release]
s| RKE2 s| 1.28.9 | N/A | https://github.com/rancher/rke2/releases/tag/v1.28.9%2Brke2r1[Upstream RKE2 Release]
s| Rancher Prime s| 2.8.4 s| 2.8.4 | https://github.com/rancher/rancher/releases/download/v2.8.4/rancher-images.txt[Rancher 2.8.4 Images] +
 https://charts.rancher.com/server-charts/prime[Rancher Prime Helm Repo]
| Longhorn | 1.6.1 | 103.3.0 | https://raw.githubusercontent.com/longhorn/longhorn/v1.6.1/deploy/longhorn-images.txt[Longhorn 1.6.1 Images] +
https://charts.longhorn.io[Longhorn Helm Repo]
s| NM Configurator s| 0.3.0 | N/A | https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.0[NMConfigurator Upstream Release]
| NeuVector| 5.3.2 | 103.0.3 | registry.suse.com/rancher/mirrored-neuvector-controller:5.3.2 +
registry.suse.com/rancher/mirrored-neuvector-enforcer:5.3.2 +
registry.suse.com/rancher/mirrored-neuvector-manager:5.3.2 +
registry.suse.com/rancher/mirrored-neuvector-prometheus-exporter:5.3.2 +
registry.suse.com/rancher mirrored-neuvector-registry-adapter:0.1.1-s1 +
registry.suse.com/rancher/mirrored-neuvector-scanner:latest +
registry.suse.com/rancher/mirrored-neuvector-updater:latest
| Cluster API (CAPI) | 1.6.2 | N/A | registry.suse.com/edge/cluster-api-controller:1.6.2 +
registry.suse.com/edge/cluster-api-provider-metal3:1.6.0 +
registry.suse.com/edge/cluster-api-provider-rke2-bootstrap:0.2.6 +
registry.suse.com/edge/cluster-api-provider-rke2-controlplane:0.2.6
s| Metal^3^ s| 1.16.0 s| 0.7.1 | registry.suse.com/edge/metal3-chart:0.7.1 +
registry.suse.com/edge/baremetal-operator:0.5.1 +
registry.suse.com/edge/ip-address-manager:1.6.0 +
registry.suse.com/edge/ironic:23.0.2.1 +
registry.suse.com/edge/ironic-ipa-downloader:1.3.2 +
registry.suse.com/edge/kube-rbac-proxy:v0.14.2 +.1
registry.suse.com/edge/mariadb:10.6.15.1
| MetalLB | 0.14.3 | 0.14.3 | registry.suse.com/edge/metallb-chart:0.14.3 +
registry.suse.com/edge/metallb-controller:v0.14.3 +
registry.suse.com/edge/metallb-speaker:v0.14.3 +
registry.suse.com/edge/frr:8.4 +
registry.suse.com/edge/frr-k8s:v0.0.8
s| Elemental s| 1.4.4 s| 1.4.4 | registry.suse.com/rancher/elemental-operator-chart:1.4.4 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.4.4 +
registry.suse.com/rancher/elemental-operator:1.4.4
s| Edge Image Builder s| 1.0.2 | N/A | registry.suse.com/edge/edge-image-builder:1.0.2
| KubeVirt | 1.1.1 | 0.2.4 | registry.suse.com/edge/kubevirt-chart:0.2.4 +
registry.suse.com/suse/sles/15.5/virt-operator:1.1.1 +
registry.suse.com/suse/sles/15.5/virt-api:1.1.1 +
registry.suse.com/suse/sles/15.5/virt-controller:1.1.1 +
registry.suse.com/suse/sles/15.5/virt-exportproxy:1.1.1 +
registry.suse.com/suse/sles/15.5/virt-exportserver:1.1.1 +
registry.suse.com/suse/sles/15.5/virt-handler:1.1.1 +
registry.suse.com/suse/sles/15.5/virt-launcher:1.1.1
| KubeVirt Dashboard Extension | 1.0.0 | 1.0.0 | registry.suse.com/edge/kubevirt-dashboard-extension-chart:1.0.0
| Containerized Data Importer | 1.58.0 | 0.2.3 | registry.suse.com/edge/cdi-chart:0.2.3 +
registry.suse.com/suse/sles/15.5/cdi-operator:1.58.0 +
registry.suse.com/suse/sles/15.5/cdi-controller:1.58.0 +
registry.suse.com/suse/sles/15.5/cdi-importer:1.58.0 +
registry.suse.com/suse/sles/15.5/cdi-cloner:1.58.0 +
registry.suse.com/suse/sles/15.5/cdi-apiserver:1.58.0 +
registry.suse.com/suse/sles/15.5/cdi-uploadserver:1.58.0 +
registry.suse.com/suse/sles/15.5/cdi-uploadproxy:1.58.0
| Endpoint Copier Operator | 0.2.0 | 0.2.0 | registry.suse.com/edge/endpoint-copier-operator:v0.2.0 +
registry.suse.com/edge/endpoint-copier-operator-chart:0.2.0
| Akri (Tech Preview) | 0.12.20 | 0.12.20 | registry.suse.com/edge/akri-chart:0.12.20 +
registry.suse.com/edge/akri-dashboard-extension-chart:1.0.0 +
registry.suse.com/edge/akri-agent:v0.12.20 +
registry.suse.com/edge/akri-controller:v0.12.20 +
registry.suse.com/edge/akri-debug-echo-discovery-handler:v0.12.20 +
registry.suse.com/edge/akri-onvif-discovery-handler:v0.12.20 +
registry.suse.com/edge/akri-opcua-discovery-handler:v0.12.20 +
registry.suse.com/edge/akri-udev-discovery-handler:v0.12.20 +
registry.suse.com/edge/akri-webhook-configuration:v0.12.20
s| SR-IOV Network Operator s| 1.2.2 s| 1.2.2+up0.1.0 | registry.suse.com/edge/sriov-network-operator-chart:1.2.2 +
registry.suse.com/edge/sriov-crd-chart:1.2.2
|======

= Release 3.0.0

Availability Date: 26th April 2024

Summary: SUSE Edge 3.0.0 is the first release in the SUSE Edge 3.0 portfolio.

== New Features

* Not Applicable - this is the first release shipped in 3.0.z.

== Bug & Security Fixes

* Not Applicable - this is the first release shipped in 3.0.z.

== Components Versions

The following table describes the individual components that make up the 3.0.0 release, including the version, the Helm chart version (if applicable), and where the released artifact can be pulled from in binary format. Please follow the associated documentation for usage and deployment examples.

|======
| Name | Version | Helm Chart Version | Artifact Location (URL/Image)
| SLE Micro | 5.5 (latest) | N/A | https://www.suse.com/download/sle-micro/[SLE Micro Download Page] +
SLE-Micro.x86_64-5.5.0-Default-SelfInstall-GM2.install.iso (sha256 4f672a4a0f8ec421e7c25797def05598037c56b7f306283566a9f921bdce904a) +
SLE-Micro.x86_64-5.5.0-Default-RT-SelfInstall-GM2.install.iso (sha256 527a5a7cdbf11e3e6238e386533755257676ad8b4c80be3b159d0904cb637678) +
SLE-Micro.x86_64-5.5.0-Default-GM.raw.xz (sha256 13243a737ca219bad6a7aa41fa747c06e8b825fef10a756cf4d575f4493ed68b) +
SLE-Micro.x86_64-5.5.0-Default-RT-GM.raw.xz (sha256 6c2af94e7ac785c8f6a276032c8e6a4b493c294e6cd72809c75089522f01bc93)
| SUSE Manager | 4.3.11 | N/A | https://www.suse.com/download/suse-manager/[SUSE Manager Download Page]
| K3s | 1.28.8 | N/A | https://github.com/k3s-io/k3s/releases/tag/v1.28.8%2Bk3s1[Upstream K3s Release]
| RKE2 | 1.28.8 | N/A | https://github.com/rancher/rke2/releases/tag/v1.28.8%2Brke2r1[Upstream RKE2 Release]
| Rancher Prime | 2.8.3 | 2.8.3 | https://github.com/rancher/rancher/releases/download/v2.8.3/rancher-images.txt[Rancher 2.8.3 Images] +
 https://charts.rancher.com/server-charts/prime[Rancher Prime Helm Repo]
| Longhorn | 1.6.1 | 103.3.0 | https://raw.githubusercontent.com/longhorn/longhorn/v1.6.1/deploy/longhorn-images.txt[Longhorn 1.6.1 Images] +
https://charts.longhorn.io[Longhorn Helm Repo]
| NM Configurator | 0.2.3 | N/A | https://github.com/suse-edge/nm-configurator/releases/tag/v0.2.3[NMConfigurator Upstream Release]
| NeuVector| 5.3.2 | 103.0.3 | registry.suse.com/rancher/mirrored-neuvector-controller:5.3.2 +
registry.suse.com/rancher/mirrored-neuvector-enforcer:5.3.2 +
registry.suse.com/rancher/mirrored-neuvector-manager:5.3.2 +
registry.suse.com/rancher/mirrored-neuvector-prometheus-exporter:5.3.2 +
registry.suse.com/rancher mirrored-neuvector-registry-adapter:0.1.1-s1 +
registry.suse.com/rancher/mirrored-neuvector-scanner:latest +
registry.suse.com/rancher/mirrored-neuvector-updater:latest
| Cluster API (CAPI) | 1.6.2 | N/A | registry.suse.com/edge/cluster-api-controller:1.6.2 +
registry.suse.com/edge/cluster-api-provider-metal3:1.6.0 +
registry.suse.com/edge/cluster-api-provider-rke2-bootstrap:0.2.6 +
registry.suse.com/edge/cluster-api-provider-rke2-controlplane:0.2.6
| Metal^3^ | 1.16.0 | 0.6.5 | registry.suse.com/edge/metal3-chart:0.6.5 +
registry.suse.com/edge/baremetal-operator:0.5.1 +
registry.suse.com/edge/ip-address-manager:1.6.0 +
registry.suse.com/edge/ironic:23.0.1.2 +
registry.suse.com/edge/ironic-ipa-downloader:1.3.1 +
registry.suse.com/edge/kube-rbac-proxy:v0.14.2 +
registry.suse.com/edge/mariadb:10.6.15.1
| MetalLB | 0.14.3 | 0.14.3 | registry.suse.com/edge/metallb-chart:0.14.3 +
registry.suse.com/edge/metallb-controller:v0.14.3 +
registry.suse.com/edge/metallb-speaker:v0.14.3 +
registry.suse.com/edge/frr:8.4 +
registry.suse.com/edge/frr-k8s:v0.0.8
| Elemental | 1.4.3 | 1.4.3 | registry.suse.com/rancher/elemental-operator-chart:1.4.3 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.4.3 +
registry.suse.com/rancher/elemental-operator:1.4.3
| Edge Image Builder | 1.0.1 | N/A | registry.suse.com/edge/edge-image-builder:1.0.1
| KubeVirt | 1.1.1 | 0.2.4 | registry.suse.com/edge/kubevirt-chart:0.2.4 +
registry.suse.com/suse/sles/15.5/virt-operator:1.1.1 +
registry.suse.com/suse/sles/15.5/virt-api:1.1.1 +
registry.suse.com/suse/sles/15.5/virt-controller:1.1.1 +
registry.suse.com/suse/sles/15.5/virt-exportproxy:1.1.1 +
registry.suse.com/suse/sles/15.5/virt-exportserver:1.1.1 +
registry.suse.com/suse/sles/15.5/virt-handler:1.1.1 +
registry.suse.com/suse/sles/15.5/virt-launcher:1.1.1
| KubeVirt Dashboard Extension | 1.0.0 | 1.0.0 | registry.suse.com/edge/kubevirt-dashboard-extension-chart:1.0.0
| Containerized Data Importer | 1.58.0 | 0.2.3 | registry.suse.com/edge/cdi-chart:0.2.3 +
registry.suse.com/suse/sles/15.5/cdi-operator:1.58.0 +
registry.suse.com/suse/sles/15.5/cdi-controller:1.58.0 +
registry.suse.com/suse/sles/15.5/cdi-importer:1.58.0 +
registry.suse.com/suse/sles/15.5/cdi-cloner:1.58.0 +
registry.suse.com/suse/sles/15.5/cdi-apiserver:1.58.0 +
registry.suse.com/suse/sles/15.5/cdi-uploadserver:1.58.0 +
registry.suse.com/suse/sles/15.5/cdi-uploadproxy:1.58.0
| Endpoint Copier Operator | 0.2.0 | 0.2.0 | registry.suse.com/edge/endpoint-copier-operator:v0.2.0 +
registry.suse.com/edge/endpoint-copier-operator-chart:0.2.0
| Akri (Tech Preview) | 0.12.20 | 0.12.20 | registry.suse.com/edge/akri-chart:0.12.20 +
registry.suse.com/edge/akri-dashboard-extension-chart:1.0.0 +
registry.suse.com/edge/akri-agent:v0.12.20 +
registry.suse.com/edge/akri-controller:v0.12.20 +
registry.suse.com/edge/akri-debug-echo-discovery-handler:v0.12.20 +
registry.suse.com/edge/akri-onvif-discovery-handler:v0.12.20 +
registry.suse.com/edge/akri-opcua-discovery-handler:v0.12.20 +
registry.suse.com/edge/akri-udev-discovery-handler:v0.12.20 +
registry.suse.com/edge/akri-webhook-configuration:v0.12.20
|======

= Components Verification

The components mentioned above may be verified using the Software Bill Of Materials (SBOM) data - for example using `cosign` as outlined below:

Download the SUSE Edge Container public key from the https://www.suse.com/support/security/keys/[SUSE Signing Keys source]:

[,bash]
----
include::key.sh[]
----

Verify the container image hash, for example using `crane`:

[,bash]
----
> crane digest registry.suse.com/edge/baremetal-operator:0.5.1
sha256:13e8b2c59aeb503f8adaac095495007071559c9d6d8ef5a7cb1ce6fd1430c782
----

Verify with `cosign`:

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/baremetal-operator@sha256:13e8b2c59aeb503f8adaac095495007071559c9d6d8ef5a7cb1ce6fd1430c782 > /dev/null
#
Verification for registry.suse.com/edge/baremetal-operator@sha256:13e8b2c59aeb503f8adaac095495007071559c9d6d8ef5a7cb1ce6fd1430c782 --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - The claims were present in the transparency log
  - The signatures were integrated into the transparency log when the certificate was valid
  - The signatures were verified against the specified public key
----

Extract SBOM data as described at the https://www.suse.com/support/security/sbom/[upstream documentation]:

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/baremetal-operator@sha256:13e8b2c59aeb503f8adaac095495007071559c9d6d8ef5a7cb1ce6fd1430c782 | jq '.payload | @base64d | fromjson | .predicate'
----

= Upgrade Steps

Refer to the Day 2 Documentation for details around how to upgrade to a new z-stream release.

= Known Limitations

Unless otherwise stated these apply to the 3.0.0 release and all subsequent z-stream versions.

* Akri is released for the first time as a Technology Preview offering, and is not subject to the standard scope of support.
* Rancher UI Extensions used in SUSE Edge cannot currently be deployed via the Rancher Marketplace and must be deployed manually. https://github.com/rancher/rancher/issues/29105[Rancher issue #29105]
* If you're using NVIDIA GPU's, SELinux cannot be enabled at the containerd layer due to a missing SELinux policy. https://bugzilla.suse.com/show_bug.cgi?id=1222725[Bugzilla #1222725]
* If deploying with Metal^3^ and Cluster API (CAPI), clusters aren't automatically imported into Rancher post-installation. It will be addressed in future releases.
* Due to certain limitations, Elemental and Metal^3^ components cannot be deployed on the same management cluster. It will be addressed in future releases.

= Product Support Lifecycle

SUSE Edge is backed by award-winning support from SUSE, an established technology leader with a proven history of delivering enterprise-quality support services. For more information, see https://www.suse.com/lifecycle[https://www.suse.com/lifecycle] and the Support Policy page at https://www.suse.com/support/policy.html[https://www.suse.com/support/policy.html]. If you have any questions about raising a support case, how SUSE classifies severity levels, or the scope of support, please see the Technical Support Handbook at https://www.suse.com/support/handbook/[https://www.suse.com/support/handbook/].

At the time of publication, each minor version of SUSE Edge, e.g. "3.0" is supported for 12-months of production support, with an initial 6-months of "full support", followed by 6-months of "maintenance support". In the "full support" coverage period, SUSE may introduce new features (that do not break existing functionality), introduce bug fixes, and deliver security patches. During the "maintenance support" window, only critical security and bug fixes will be introduced, with other fixes delivered at our discretion.

Unless explicitly stated, all components listed are considered Generally Available (GA), and are covered by SUSE's standard scope of support. Some components may be listed as "Technology Preview", where SUSE is providing customers with access to early pre-GA features and functionality for evaluation, but are not subject to the standard support policies and are not recommended for production use-cases. SUSE very much welcomes feedback and suggestions on the improvements that can be made to Technology Preview components, but SUSE reserves the right to deprecate a Technology Preview feature before it becomes Generally Available if it doesn't meet the needs of our customers or doesn't reach a state of maturity that we require.

Please note that SUSE must occasionally deprecate features or change API specifications. Reasons for feature deprecation or API change could include a feature being updated or replaced by a new implementation, a new feature set, upstream technology is no longer available, or the upstream community has introduced incompatible changes. It is not intended that this will ever happen within a given minor release (x.z), and so all z-stream releases will maintain API compatibility and feature functionality. SUSE will endeavor to provide deprecation warnings with plenty of notice within the release notes, along with workarounds, suggestions, and mitigations to minimize service disruption.

The SUSE Edge team also welcomes community feedback, where issues can be raised within the respective code repository within https://www.github.com/suse-edge[https://www.github.com/suse-edge].

= Obtaining source code

This SUSE product includes materials licensed to SUSE under the GNU General Public License (GPL) and various other open source licenses. The GPL requires SUSE to provide the source code that corresponds to the GPL-licensed material, and SUSE conforms to all other open-source license requirements. As such, SUSE makes all source code available, and can generally be found in the SUSE Edge GitHub repository (https://www.github.com/suse-edge[https://www.github.com/suse-edge]), the SUSE Rancher GitHub repository (https://www.github.com/rancher[https://www.github.com/rancher]) for dependent components, and specifically for SLE Micro, the source code is available for download at https://www.suse.com/download/sle-micro/[https://www.suse.com/download/sle-micro] on "Medium 2".

= Legal notices

SUSE makes no representations or warranties with regard to the contents or use of this documentation, and specifically disclaims any express or implied warranties of merchantability or fitness for any particular purpose. Further, SUSE reserves the right to revise this publication and to make changes to its content, at any time, without the obligation to notify any person or entity of such revisions or changes.

Further, SUSE makes no representations or warranties with regard to any software, and specifically disclaims any express or implied warranties of merchantability or fitness for any particular purpose. Further, SUSE reserves the right to make changes to any and all parts of SUSE software, at any time, without any obligation to notify any person or entity of such changes.

Any products or technical information provided under this Agreement may be subject to U.S. export controls and the trade laws of other countries. You agree to comply with all export control regulations and to obtain any required licenses or classifications to export, re-export, or import deliverables. You agree not to export or re-export to entities on the current U.S. export exclusion lists or to any embargoed or terrorist countries as specified in U.S. export laws. You agree to not use deliverables for prohibited nuclear, missile, or chemical/biological weaponry end uses. Refer to https://www.suse.com/company/legal/[https://www.suse.com/company/legal/] for more information on exporting SUSE software. SUSE assumes no responsibility for your failure to obtain any necessary export approvals.

*Copyright © 2024 SUSE LLC.*

This release notes document is licensed under a Creative Commons Attribution-NoDerivatives 4.0 International License (CC-BY-ND-4.0). You should have received a copy of the license along with this document. If not, see https://creativecommons.org/licenses/by-nd/4.0/[https://creativecommons.org/licenses/by-nd/4.0/].

SUSE has intellectual property rights relating to technology embodied in the product that is described in this document. In particular, and without limitation, these intellectual property rights may include one or more of the U.S. patents listed at https://www.suse.com/company/legal/[https://www.suse.com/company/legal/] and one or more additional patents or pending patent applications in the U.S. and other countries.

For SUSE trademarks, see the SUSE Trademark and Service Mark list (https://www.suse.com/company/legal/[https://www.suse.com/company/legal/]). All third-party trademarks are the property of their respective owners. For SUSE brand information and usage requirements, please see the guidelines published at https://brand.suse.com/[https://brand.suse.com/].
