[#release-notes]

= Abstract
:revdate: 2026-01-20
:page-revdate: {revdate}
ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

{product} 3.6 is a tightly integrated and comprehensively validated end-to-end solution for addressing the unique challenges of the deployment of infrastructure and cloud-native applications at the edge. Its driving focus is to provide an opinionated, yet highly flexible, highly scalable, and secure platform that spans initial deployment image building, node provisioning and onboarding, application deployment, observability, and lifecycle management.

The solution is designed with the notion that there is no "one-size-fits-all" edge platform due to our customers’ widely varying requirements and expectations. Edge deployments push us to solve, and continually evolve, some of the most challenging problems, including massive scalability, restricted network availability, physical space constraints, new security threats and attack vectors, variations in hardware architecture and system resources, the requirement to deploy and interface with legacy infrastructure and applications, and customer solutions that have extended lifespans.

{product} is built on best-of-breed open source software from the ground up, consistent with both our 30-year history in delivering secure, stable, and certified SUSE Linux platforms and our experience in providing highly scalable and feature-rich Kubernetes management with our Rancher portfolio. {product} builds on-top of these capabilities to deliver functionality that can address a wide number of market segments, including retail, medical, transportation, logistics, telecommunications, smart manufacturing, and Industrial IoT.

For more information on product support lifecycle updates for {product}, see link:https://www.suse.com/lifecycle/#suse-edge-36[Product Support Lifecycle].

NOTE: SUSE Telco Cloud is a derivative of SUSE Edge, with additional optimizations and components that enable the platform to address the requirements found in telecommunications use-cases.

= About

These Release Notes are, unless explicitly specified and explained, identical across all architectures, and the most recent version, along with the release notes of all other SUSE products are always available online at https://www.suse.com/releasenotes[https://www.suse.com/releasenotes].

Entries are only listed once, but they can be referenced in several places if they are important and belong to more than one section. Release notes usually only list changes that happened between two subsequent releases. Certain important entries from the release notes of previous product versions may be repeated. To make these entries easier to identify, they contain a note to that effect.

However, repeated entries are provided as a courtesy only. Therefore, if you are skipping one or more releases, check the release notes of the skipped releases also. If you are only reading the release notes of the current release, you could miss important changes that may affect system behavior. {product} versions are defined as x.y.z, where 'x' denotes the major version, 'y' denotes the minor, and 'z' denotes the patch version, also known as the "z-stream". {product} product lifecycles are defined based around a given minor release, e.g. "3.6", but ship with subsequent patch updates through its lifecycle, e.g. "3.6.1".

NOTE: {product} z-stream releases are tightly integrated and thoroughly tested as a versioned stack. Upgrade of any individual components to a different versions to those listed above is likely to result in system downtime. While it's possible to run Edge clusters in untested configurations, it is not recommended, and it may take longer to provide resolution through the support channels.

[#release-notes-3-6-0]
= Release 3.6.0

Availability Date: 27th May 2026

Full Support End Date: 27th November 2026

Maintenance Support End Date: 27th May 2028

EOL: 28th May 2028

Summary: {product} 3.6.0 is the first release in the {product} 3.6 release stream.

== New Features

* Updated to Kubernetes 1.35.3 and Rancher Prime 2.14.1
* Updated to SUSE Security (NeuVector) 5.5.1 https://open-docs.neuvector.com/releasenotes/5x[NeuVector Release Notes]
* Updated to SUSE Storage (Longhorn) 1.11.1 https://longhorn.io/docs/1.11.1/[Upstream Longhorn Release Notes]
* Updated to Rancher Turtles (CAPI) 0.26.1 https://turtles.docs.rancher.com/[Rancher Turtles Documentation]
* Updated to MetalLB 0.15.3 https://metallb.universe.tf/release-notes/#version-0-15-3[Upstream Release Notes]
* Updated to KubeVirt 1.7.0 and CDI (Containerized Data Importer) 1.64.0
* Updated to Elemental 1.9.0 https://elemental.docs.rancher.com/release-notes/[Elemental Release Notes]
* Updated to Cert-Manager 1.20.1 https://cert-manager.io/docs/release-notes/[Upstream Release Notes]
* Updated Metal3/Ironic to 0.15.0 with Ironic 35.0.0
* BGP mode for MetalLB was a Technology Preview in {product} 3.5 and is now fully supported
* Precision Time Protocol (PTP) on downstream deployments was a Technology Preview in {product} 3.5 and is now fully supported
* Single-stack IPv6 downstream cluster deployments are now supported, however note this requires a dual-stack management cluster (single stack management clusters remain a Technology Preview)

== Bug & Security Fixes

* Kubernetes 1.35.3 contains several bugfixes and security updates https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.35.md[Kubernetes Changelog]
* Rancher Prime 2.14.1 contains several bugfixes https://github.com/rancher/rancher/releases/tag/v2.14.1[Upstream Rancher Release Notes]
* SUSE Storage (Longhorn) 1.11.1 contains several bugfixes https://github.com/longhorn/longhorn/releases/tag/v1.11.1[Upstream Longhorn Bug Fixes]
* NeuVector 5.5.1 contains new features and several bugfixes https://open-docs.neuvector.com/releasenotes/5x[NeuVector Release Notes]

== Known Issues

[WARNING]
====
If deploying new clusters, please follow <<guides-kiwi-builder-images>> to build fresh images first.  This is suggested for management and downstream clusters to ensure the images contain the latest security and bug fixes.
====

* When deploying via Edge Image Builder, `HelmChartConfigs` manifests may fail if they are put in the `kubernetes/manifests` configuration directory. Instead it is recommended to place any `HelmChartConfigs` in `/var/lib/rancher/{rke2/k3s}/server/manifests/` using the EIB os-files interface.
ifeval::["{flavor}" == "telco"]
See <<mgmt-cluster-directory-structure>> for an example.
endif::[]
Failure to do this may cause nodes to stay in `NotReady` state on initial startup, as discussed in https://github.com/rancher/rke2/issues/8357[#8357 RKE2 issue].

* On RKE2/K3s 1.34 and 1.35 versions, the directory `/etc/cni` being used to store CNI configurations may not trigger a notification of the files being written there to `containerd` due to certain conditions related to `overlayfs` (see the https://github.com/rancher/rke2/issues/8356[#8356 RKE2 issue]). This in turn results in the deployment of RKE2/K3s to get stuck waiting for the CNI to start, and the RKE2/K3s nodes to stay in `NotReady` state. This can be seen at node level with `kubectl describe node <affected_node>`:

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

As a workaround, a tmpfs volume can be mounted at the `/etc/cni` directory before RKE2 starts. It avoids the usage of overlayfs which results in containerd missing notifications and the configs should get rewritten every time the node is restarted and the pods initcontainers run again. If using EIB, this can be a `04-tmpfs-cni.sh` script in the `custom/scripts` directory (as explained here[https://github.com/suse-edge/edge-image-builder/blob/release-1.3/docs/building-images.md#custom]) that looks like:

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

== Component Versions

The following table describes the individual components that make up the 3.6.0 release, including the version, the Helm chart version (if applicable), and from where the released artifact can be pulled in the binary format. Please follow the associated documentation for usage and deployment examples.

|======
| Name | Version | Helm Chart Version | Artifact Location (URL/Image)
| SUSE Linux Micro | 6.2 (latest) | N/A | https://www.suse.com/download/sle-micro/[SUSE Linux Micro Download Page] +
| SUSE Linux Micro | 6.2 (latest) | N/A |Checksums and signatures are available for download at https://www.suse.com/download/sle-micro/[SUSE Linux Micro Download Page] +
SL-Micro.x86_64-6.2-Base-SelfInstall-GM.install.iso +
SL-Micro.x86_64-6.2-Base-RT-SelfInstall-GM.install.iso +
SL-Micro.x86_64-6.2-Base-GM.raw.xz +
SL-Micro.x86_64-6.2-Base-RT-GM.raw.xz +
| SUSE Multi-Linux Manager | 5.0.6 | N/A | https://www.suse.com/download/suse-manager/[SUSE Multi-Linux Manager Download Page]
| K3s | 1.35.3 | N/A | https://github.com/k3s-io/k3s/releases/tag/v1.35.3%2Bk3s1[Upstream K3s Release]
| RKE2 | 1.35.3 | N/A | https://github.com/rancher/rke2/releases/tag/v1.35.3%2Brke2r3[Upstream RKE2 Release]
| SUSE Rancher Prime | 2.14.1 | 2.14.1 | https://charts.rancher.com/server-charts/prime/index.yaml[Rancher Prime Helm Repository] +
https://prime.ribs.rancher.io/rancher/v2.14.1/rancher-images.txt[Rancher 2.14.1 Container Images]
| SUSE Storage (Longhorn) | 1.11.1 | 1.11.1 | https://apps.rancher.io/applications/suse-storage[SUSE Storage Helm Repository] +
https://apps.rancher.io/applications/suse-storage/components[SUSE Storage Container Images]
| SUSE Security (NeuVector) | 5.5.1 | 109.0.1+up2.8.13 | https://charts.rancher.io/index.yaml[Rancher Charts Helm Repository] +
registry.rancher.com/rancher/neuvector-controller:5.5.1 +
registry.rancher.com/rancher/neuvector-enforcer:5.5.1 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.12
| Rancher Turtles Providers (CAPI) | 0.26.1 | 306.0.6+up0.26.1 | registry.suse.com/edge/3.6/rancher-turtles-providers-chart:306.0.6+up0.26.1 +
registry.rancher.com/rancher/cluster-api-controller:v1.12.2 +
registry.rancher.com/rancher/turtles:v0.26.1 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.24.3 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.24.3
| Metal^3^ | 0.15.0 | 306.0.26+up0.15.0 | registry.suse.com/edge/3.6/metal3-chart:306.0.26+up0.15.0 +
registry.suse.com/edge/3.6/baremetal-operator:0.12.3.0 +
registry.suse.com/edge/3.6/ironic:35.0.0.1 +
registry.suse.com/edge/3.6/ironic-ipa-downloader:3.1.1 +
registry.suse.com/edge/3.6/ironic-python-agent:3.0.8
| MetalLB | 0.15.3 | 306.0.2+up0.15.3 | registry.suse.com/edge/3.6/metallb-chart:306.0.2+up0.15.3 +
registry.suse.com/edge/3.6/metallb-controller:v0.15.3 +
registry.suse.com/edge/3.6/metallb-speaker:v0.15.3
| Elemental | 1.9.0 | 1.9.0 | registry.suse.com/rancher/elemental-operator-chart:1.9.0 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.9.0 +
registry.suse.com/rancher/elemental-operator:1.9.0
| Elemental Dashboard Extension | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/main/charts/elemental/3.0.1[Elemental Extension Helm Chart]
| Edge Image Builder | 1.3.3.1 | N/A | registry.suse.com/edge/3.6/edge-image-builder:1.3.3.1
| KubeVirt | 1.7.0 | 306.0.2+up0.7.0 | registry.suse.com/edge/3.6/kubevirt-chart:306.0.2+up0.7.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.7.0-150700.3.16.2
| KubeVirt Dashboard Extension | 1.3.3 | 306.0.4+up1.3.3 | registry.suse.com/edge/3.6/kubevirt-dashboard-extension-chart:306.0.4+up1.3.3
| Containerized Data Importer (CDI) | 1.64.0 | 306.0.2+up0.7.0 | registry.suse.com/edge/3.6/cdi-chart:306.0.2+up0.7.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.64.0-150700.9.6.1
| Endpoint Copier Operator | 0.3.0 | 306.0.1+up0.3.0 | registry.suse.com/edge/3.6/endpoint-copier-operator-chart:306.0.1+up0.3.0 +
registry.suse.com/edge/3.6/endpoint-copier-operator:0.3.0
| SR-IOV Network Operator | 1.6.0 | 306.0.4+up1.6.0 | registry.suse.com/edge/3.6/sriov-network-operator-chart:306.0.4+up1.6.0 +
registry.suse.com/edge/3.6/sriov-crd-chart:306.0.4+up1.6.0
| System Upgrade Controller | 0.19.1 | 109.0.1 | https://charts.rancher.io/index.yaml[Rancher Charts Helm Repository] +
registry.rancher.com/rancher/system-upgrade-controller:v0.19.1
| Upgrade Controller | 0.1.3 | 306.0.3+up0.1.3 | registry.suse.com/edge/3.6/upgrade-controller-chart:306.0.3+up0.1.3 +
registry.suse.com/edge/3.6/upgrade-controller:0.1.3 +
registry.rancher.com/rancher/kubectl:v1.35.2 +
registry.suse.com/edge/3.6/release-manifest:3.6.0
| SUSE Private Registry | 1.1.1 | 1.1.1 | oci://registry.suse.com/private-registry/private-registry-helm[SUSE Private Registry Helm Repository] +
registry.suse.com/private-registry/harbor-core:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-jobservice:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-portal:1.1.1-1.20 +
registry.suse.com/private-registry/harbor-registry:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-registryctl:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-trivy-adapter:1.1.1-1.24
| Kiwi Builder | 10.2.29.1 | N/A | registry.suse.com/edge/3.6/kiwi-builder:10.2.29.1
| Cert-Manager | 1.20.1 | 1.20.1 | https://charts.jetstack.io[Jetstack Helm Repository] +
quay.io/jetstack/cert-manager-controller:v1.20.1 +
quay.io/jetstack/cert-manager-webhook:v1.20.1 +
quay.io/jetstack/cert-manager-cainjector:v1.20.1
|======

= Removed features

Unless otherwise stated, these apply to the {version-edge}.0 release and all subsequent z-stream versions.

* Akri was a Technology Preview offering in previous Edge releases and deprecated from 3.4.0 onwards. It is now completely removed from the offering.

[#tech-previews]
= Technology Previews

Unless otherwise stated, these apply to the 3.6.0 release and all subsequent z-stream versions.

* Single-stack IPv6 management cluster deployments are a Technology Preview offering and are not subject to the standard scope of support.

= Component Verification

The components mentioned above may be verified using the Software Bill Of Materials (SBOM) data - for example, using `cosign` as outlined below:

Download the {product} Container public key from the https://www.suse.com/support/security/keys/[SUSE Signing Keys source]:

[,bash]
----
include::key.sh[]
----

Verify the container image hash, for example using `crane`:

[,bash]
----
> crane digest registry.suse.com/edge/3.6/baremetal-operator:0.12.3.0 --platform linux/amd64
sha256:example-digest-placeholder
----

NOTE: For multi-arch images it is also necessary to specify a platform when obtaining the digest, e.g `--platform linux/amd64` or `--platform linux/arm64`. Failure to do this will result in an error in the following step (`Error: no matching attestations`).

Verify with `cosign`:

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/3.6/baremetal-operator@sha256:example-digest-placeholder > /dev/null
#
Verification for registry.suse.com/edge/3.6/baremetal-operator@sha256:example-digest-placeholder --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - The signatures were verified against the specified public key
----

Extract SBOM data as described at the https://www.suse.com/support/security/sbom/[SUSE SBOM documentation]:

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/3.6/baremetal-operator@sha256:example-digest-placeholder | jq '.payload | @base64d | fromjson | .predicate'
----

= Upgrade Steps

Refer to the <<day-2-operations>> for details around how to upgrade to a new release.

= Product Support Lifecycle

{product} is backed by award-winning support from SUSE, an established technology leader with a proven history of delivering enterprise-quality support services. For more information, see https://www.suse.com/lifecycle[https://www.suse.com/lifecycle] and the Support Policy page at https://www.suse.com/support/policy.html[https://www.suse.com/support/policy.html]. If you have any questions about raising a support case, how SUSE classifies severity levels, or the scope of support, please see the Technical Support Handbook at https://www.suse.com/support/handbook/[https://www.suse.com/support/handbook/].

{product} "3.6" is supported for 24-months of production support, with an initial 6-months of "full support", followed by 18-months of "maintenance support".  After these support phases the product reaches "end of life" (EOL) and is no longer supported. More info about the lifecycle phases can be found in the table below:

|======
| *Full Support (6 months)* | Urgent and selected high-priority bug fixes will be released during the full support window, and all other patches (non-urgent, enhancements, new capabilities) will be released via the regular release schedule.
| *Maintenance Support (18 months)* | During this period, only critical fixes will be released via patches. Other bug fixes may be released at SUSE's discretion but should not be expected.
| *End of Life (EOL)*  | Once a product release reaches its End of Life date, the customer may continue to use the product within the terms of product licensing agreement.
Support Plans from SUSE do not apply to product releases past their EOL date.
|======

Unless explicitly stated, all components listed are considered Generally Available (GA), and are covered by SUSE's standard scope of support. Some components may be listed as "Technology Preview", where SUSE is providing customers with access to early pre-GA features and functionality for evaluation, but are not subject to the standard support policies and are not recommended for production use-cases. SUSE very much welcomes feedback and suggestions on the improvements that can be made to Technology Preview components, but SUSE reserves the right to deprecate a Technology Preview feature before it becomes Generally Available if it doesn't meet the needs of our customers or doesn't reach a state of maturity that we require.

Please note that SUSE must occasionally deprecate features or change API specifications. Reasons for feature deprecation or API change could include a feature being updated or replaced by a new implementation, a new feature set, upstream technology is no longer available, or the upstream community has introduced incompatible changes. It is not intended that this will ever happen within a given minor release (x.z), and so all z-stream releases will maintain API compatibility and feature functionality. SUSE will endeavor to provide deprecation warnings with plenty of notice within the release notes, along with workarounds, suggestions, and mitigations to minimize service disruption.

The {product} team also welcomes community feedback, where issues can be raised within the respective code repository within https://www.github.com/suse-edge[https://www.github.com/suse-edge].

= Obtaining source code

This SUSE product includes materials licensed to SUSE under the GNU General Public License (GPL) and various other open source licenses. The GPL requires SUSE to provide the source code that corresponds to the GPL-licensed material, and SUSE conforms to all other open-source license requirements. As such, SUSE makes all source code available, and can generally be found in the {product} GitHub repository (https://www.github.com/suse-edge[https://www.github.com/suse-edge]), the SUSE Rancher GitHub repository (https://www.github.com/rancher[https://www.github.com/rancher]) for dependent components, and specifically for SUSE Linux Micro, the source code is available for download at https://www.suse.com/download/sle-micro/[https://www.suse.com/download/sle-micro] on "Medium 2".

= Legal notices

SUSE makes no representations or warranties with regard to the contents or use of this documentation, and specifically disclaims any express or implied warranties of merchantability or fitness for any particular purpose. Further, SUSE reserves the right to revise this publication and to make changes to its content, at any time, without the obligation to notify any person or entity of such revisions or changes.

Further, SUSE makes no representations or warranties with regard to any software, and specifically disclaims any express or implied warranties of merchantability or fitness for any particular purpose. Further, SUSE reserves the right to make changes to any and all parts of SUSE software, at any time, without any obligation to notify any person or entity of such changes.

Any products or technical information provided under this Agreement may be subject to U.S. export controls and the trade laws of other countries. You agree to comply with all export control regulations and to obtain any required licenses or classifications to export, re-export, or import deliverables. You agree not to export or re-export to entities on the current U.S. export exclusion lists or to any embargoed or terrorist countries as specified in U.S. export laws. You agree to not use deliverables for prohibited nuclear, missile, or chemical/biological weaponry end uses. Refer to https://www.suse.com/company/legal/[https://www.suse.com/company/legal/] for more information on exporting SUSE software. SUSE assumes no responsibility for your failure to obtain any necessary export approvals.

*Copyright © 2024 SUSE LLC.*

This release notes document is licensed under a Creative Commons Attribution-NoDerivatives 4.0 International License (CC-BY-ND-4.0). You should have received a copy of the license along with this document. If not, see https://creativecommons.org/licenses/by-nd/4.0/[https://creativecommons.org/licenses/by-nd/4.0/].

SUSE has intellectual property rights relating to technology embodied in the product that is described in this document. In particular, and without limitation, these intellectual property rights may include one or more of the U.S. patents listed at https://www.suse.com/company/legal/[https://www.suse.com/company/legal/] and one or more additional patents or pending patent applications in the U.S. and other countries.

For SUSE trademarks, see the SUSE Trademark and Service Mark list (https://www.suse.com/company/legal/[https://www.suse.com/company/legal/]). All third-party trademarks are the property of their respective owners. For SUSE brand information and usage requirements, please see the guidelines published at https://brand.suse.com/[https://brand.suse.com/].
