[#release-notes]

= Abstract
ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

SUSE Edge 3.2 is a tightly integrated and comprehensively validated end-to-end solution for addressing the unique challenges of the deployment of infrastructure and cloud-native applications at the edge. Its driving focus is to provide an opinionated, yet highly flexible, highly scalable, and secure platform that spans initial deployment image building, node provisioning and onboarding, application deployment, observability, and lifecycle management.

The solution is designed with the notion that there is no "one-size-fits-all" edge platform due to our customers’ widely varying requirements and expectations. Edge deployments push us to solve, and continually evolve, some of the most challenging problems, including massive scalability, restricted network availability, physical space constraints, new security threats and attack vectors, variations in hardware architecture and system resources, the requirement to deploy and interface with legacy infrastructure and applications, and customer solutions that have extended lifespans.

SUSE Edge is built on best-of-breed open source software from the ground up, consistent with both our 30-year history in delivering secure, stable, and certified SUSE Linux platforms and our experience in providing highly scalable and feature-rich Kubernetes management with our Rancher portfolio. SUSE Edge builds on-top of these capabilities to deliver functionality that can address a wide number of market segments, including retail, medical, transportation, logistics, telecommunications, smart manufacturing, and Industrial IoT.

NOTE: SUSE Edge for Telco (formerly known as Adaptive Telco Infrastructure Platform/ATIP) is a derivative (or downstream product) of SUSE Edge, with additional optimizations and components that enable the platform to address the requirements found in telecommunications use-cases. Unless explicitly stated, all the release notes are applicable for both SUSE Edge 3.2, and SUSE Edge for Telco 3.2.

= About

These Release Notes are, unless explicitly specified and explained, identical across all architectures, and the most recent version, along with the release notes of all other SUSE products are always available online at https://www.suse.com/releasenotes[https://www.suse.com/releasenotes].

Entries are only listed once, but they can be referenced in several places if they are important and belong to more than one section. Release notes usually only list changes that happened between two subsequent releases. Certain important entries from the release notes of previous product versions may be repeated. To make these entries easier to identify, they contain a note to that effect.

However, repeated entries are provided as a courtesy only. Therefore, if you are skipping one or more releases, check the release notes of the skipped releases also. If you are only reading the release notes of the current release, you could miss important changes that may affect system behavior. SUSE Edge versions are defined as x.y.z, where 'x' denotes the major version, 'y' denotes the minor, and 'z' denotes the patch version, also known as the "z-stream". SUSE Edge product lifecycles are defined based around a given minor release, e.g. "3.2", but ship with subsequent patch updates through its lifecycle, e.g. "3.2.1".

NOTE: SUSE Edge z-stream releases are tightly integrated and thoroughly tested as a versioned stack. Upgrade of any individual components to a different versions to those listed above is likely to result in system downtime. While it's possible to run Edge clusters in untested configurations, it is not recommended, and it may take longer to provide resolution through the support channels.

[#release-notes-3-2-0]
= Release 3.2.0

Availability Date: 20th January 2025

Summary: SUSE Edge 3.2.0 is the first release in the SUSE Edge 3.2 release stream.

== New Features

* Updated to Kubernetes 1.31, and Rancher Prime 2.10
* Updated Rancher Turtles, Cluster API and Metal3/Ironic versions
* A container image is now provided which enables building updated SUSE Linux Micro images. See <<guides-kiwi-builder-images>> for more details.
* Deployment of dual-stack downstream clusters is now possible via the directed network provisioning flow as a technology preview.
* Configuration of Precision Time Protocol (PTP) is now possible as a technology preview. See <<tech-previews>> for more details.

== Bug & Security Fixes

* With the included RKE2 CAPI provider version, it is now possible to define dual-stack CAPI clusters. Previously, only single-stack deployments were possible due to a https://github.com/rancher/cluster-api-provider-rke2/pull/452[bug that filtered additional CIDRs] for both Pods and Services. For examples on configuring IPv4, IPv6 and dual-stack downstream clusters (currently limited to single-host deployments), refer to https://github.com/suse-edge/atip[https://github.com/suse-edge/atip].

== Known issues

* When deploying via the directed network provisioning flow, a bug affects clusters with static IPs in networks with DHCP servers and/or RAs: static network configurations only apply to the provisioned host and will not be in effect during the host discovery and enrollment. Please refer to the https://github.com/suse-edge/atip/tree/main/telco-examples/edge-clusters/dhcp-less/dual-stack/single-node#readme[SUSE Edge for Telco examples repository] for more details and updates.
* When using `toolbox` in SUSE Linux Micro 6.0, the default container image does not contain some tools which were included in the previous 5.5 version.  The workaround is to configure toolbox to use the previous `suse/sle-micro/5.5/toolbox` container image, see `toolbox --help` for options to configure the image.

== Components Versions

The following table describes the individual components that make up the 3.2 release, including the version, the Helm chart version (if applicable), and from where the released artifact can be pulled in the binary format. Please follow the associated documentation for usage and deployment examples.

|======
| Name | Version | Helm Chart Version | Artifact Location (URL/Image)
| SUSE Linux Micro | 6.0 (latest) | N/A | https://www.suse.com/download/sle-micro/[SUSE Linux Micro Download Page] +
SL-Micro.x86_64-6.0-Base-SelfInstall-GM2.install.iso (sha256 bc7c3210c8a9b688d2713ad87f17e2c90cb99fd6dee1db528a5ff7f239cbcf79) +
SL-Micro.x86_64-6.0-Base-RT-SelfInstall-GM2.install.iso (sha256 8242895e21745aec15ef526a95272887fa95dd832782b2cea4a95f41493f6648) +
SL-Micro.x86_64-6.0-Base-GM2.raw.xz (sha256 7ae13d080e66c8b35624b6566b5eaff0875c8c141d0def9fbaee5876781ed81b) +
SL-Micro.x86_64-6.0-Base-RT-GM2.raw.xz (sha256 9a19078c062ab52c62c0254e11f5a5a9fac938fd094abff5aa5eac2ec00b2d4e) +
| SUSE Multi-Linux Manager | 5.0.2 | N/A | https://www.suse.com/download/suse-manager/[SUSE Multi-Linux Manager Download Page]
| K3s | 1.31.3 | N/A | https://github.com/k3s-io/k3s/releases/tag/v1.31.3%2Bk3s1[Upstream K3s Release]
| RKE2 | 1.31.3 | N/A | https://github.com/rancher/rke2/releases/tag/v1.31.3%2Brke2r1[Upstream RKE2 Release]
| SUSE Rancher Prime | 2.10.1 | 2.10.1 | https://charts.rancher.com/server-charts/prime/index.yaml[Rancher Prime Helm Repository] +
https://github.com/rancher/rancher/releases/download/v2.10.1/rancher-images.txt[Rancher 2.10.1 Container Images]
| SUSE Storage | 1.7.2 | 105.1.0+up1.7.2 | https://charts.rancher.io/index.yaml[Rancher Charts Helm Repository] +
registry.suse.com/rancher/mirrored-longhornio-csi-attacher:v4.7.0 +
registry.suse.com/rancher/mirrored-longhornio-csi-provisioner:v4.0.1-20241007 +
registry.suse.com/rancher/mirrored-longhornio-csi-resizer:v1.12.0 +
registry.suse.com/rancher/mirrored-longhornio-csi-snapshotter:v7.0.2-20241007 +
registry.suse.com/rancher/mirrored-longhornio-csi-node-driver-registrar:v2.12.0 +
registry.suse.com/rancher/mirrored-longhornio-livenessprobe:v2.14.0 +
registry.suse.com/rancher/mirrored-longhornio-backing-image-manager:v1.7.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-engine:v1.7.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-instance-manager:v1.7.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-manager:v1.7.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-share-manager:v1.7.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-ui:v1.7.2 +
registry.suse.com/rancher/mirrored-longhornio-support-bundle-kit:v0.0.45 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-cli:v1.7.2 +
| SUSE Security| 5.4.1 | 105.0.0+up2.8.3 | https://charts.rancher.io/index.yaml[Rancher Charts Helm Repository] +
registry.suse.com/rancher/mirrored-neuvector-controller:5.4.1 +
registry.suse.com/rancher/mirrored-neuvector-enforcer:5.4.1 +
registry.suse.com/rancher/mirrored-neuvector-manager:5.4.1 +
registry.suse.com/rancher/mirrored-neuvector-prometheus-exporter:5.3.2 +
registry.suse.com/rancher mirrored-neuvector-registry-adapter:0.1.3 +
registry.suse.com/rancher/mirrored-neuvector-scanner:latest +
registry.suse.com/rancher/mirrored-neuvector-updater:latest
| Rancher Turtles (CAPI) | 0.14.1 | 302.0.0+up0.14.1 | registry.suse.com/edge/3.2/rancher-turtles-chart:302.0.0_up0.14.1 +
registry.rancher.com/rancher/rancher/turtles:v0.14.1 +
registry.rancher.com/rancher/cluster-api-operator:v0.14.0 +
registry.rancher.com/rancher/cluster-api-metal3-controller:v1.8.2 +
registry.rancher.com/rancher/cluster-api-metal3-ipam-controller:v1.8.1 +
registry.suse.com/rancher/cluster-api-controller:v1.8.4 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.9.0 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.9.0
| Metal^3^ | 0.9.0 | 302.0.0+up0.9.0 | registry.suse.com/edge/3.2/metal3-chart:302.0.0_up0.9.0 +
registry.suse.com/edge/3.2/baremetal-operator:0.8.0 +
registry.suse.com/edge/3.2/ironic:26.1.2.0 +
registry.suse.com/edge/3.2/ironic-ipa-downloader:3.0.0 +
registry.suse.com/edge/3.2/kube-rbac-proxy:0.18.1 +
registry.suse.com/edge/mariadb:10.6.15.1
| MetalLB | 0.14.9 | 302.0.0+up0.14.9 | registry.suse.com/edge/3.2/metallb-chart:302.0.0_up0.14.9 +
registry.suse.com/edge/3.2/metallb-controller:v0.14.8 +
registry.suse.com/edge/3.2/metallb-speaker:v0.14.8 +
registry.suse.com/edge/3.2/frr:8.4 +
registry.suse.com/edge/3.2/frr-k8s:v0.0.14
| Elemental | 1.6.5 | 1.6.5 | registry.suse.com/rancher/elemental-operator-chart:1.6.5 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.6.5 +
registry.suse.com/rancher/elemental-operator:1.6.5
| Elemental Dashboard Extension | 3.0.0 | 3.0.0 | link:https://github.com/rancher/ui-plugin-charts/tree/3.2.0/charts/elemental/3.0.0[Elemental Extension Helm Chart]
| Edge Image Builder | 1.1.0 | N/A | registry.suse.com/edge/3.2/edge-image-builder:1.1.0
| NM Configurator | 0.3.1 | N/A | https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.1[NMConfigurator Upstream Release]
| KubeVirt | 1.3.1 | 302.0.0+up0.4.0 | registry.suse.com/edge/3.2/kubevirt-chart:302.0.0_up0.4.0 +
registry.suse.com/suse/sles/15.6/virt-operator:1.3.1 +
registry.suse.com/suse/sles/15.6/virt-api:1.3.1 +
registry.suse.com/suse/sles/15.6/virt-controller:1.3.1 +
registry.suse.com/suse/sles/15.6/virt-exportproxy:1.3.1 +
registry.suse.com/suse/sles/15.6/virt-exportserver:1.3.1 +
registry.suse.com/suse/sles/15.6/virt-handler:1.3.1 +
registry.suse.com/suse/sles/15.6/virt-launcher:1.3.1
| KubeVirt Dashboard Extension | 1.2.1 | 302.0.0+up1.2.1 | registry.suse.com/edge/3.2/kubevirt-dashboard-extension-chart:302.0.0_up1.2.1
| Containerized Data Importer | 1.60.1 | 302.0.0+up0.4.0 | registry.suse.com/edge/3.2/cdi-chart:302.0.0_up0.4.0 +
registry.suse.com/suse/sles/15.6/cdi-operator:1.60.1 +
registry.suse.com/suse/sles/15.6/cdi-controller:1.60.1 +
registry.suse.com/suse/sles/15.6/cdi-importer:1.60.1 +
registry.suse.com/suse/sles/15.6/cdi-cloner:1.60.1 +
registry.suse.com/suse/sles/15.6/cdi-apiserver:1.60.1 +
registry.suse.com/suse/sles/15.6/cdi-uploadserver:1.60.1 +
registry.suse.com/suse/sles/15.6/cdi-uploadproxy:1.60.1
| Endpoint Copier Operator | 0.2.0 | 302.0.0+up0.2.1 | registry.suse.com/edge/3.2/endpoint-copier-operator-chart:302.0.0_up0.2.1 +
registry.suse.com/edge/3.2/endpoint-copier-operator:0.2.0
| Akri (Tech Preview) | 0.12.20 | 302.0.0+up0.12.20 | registry.suse.com/edge/3.2/akri-chart:302.0.0_up0.12.20 +
registry.suse.com/edge/3.2/akri-dashboard-extension-chart:302.0.0_up1.2.1 +
registry.suse.com/edge/3.2/akri-agent:v0.12.20 +
registry.suse.com/edge/3.2/akri-controller:v0.12.20 +
registry.suse.com/edge/3.2/akri-debug-echo-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.2/akri-onvif-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.2/akri-opcua-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.2/akri-udev-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.2/akri-webhook-configuration:v0.12.20
| SR-IOV Network Operator | 1.4.0 | 302.0.0+up1.4.0 | registry.suse.com/edge/3.2/sriov-network-operator-chart:302.0.0_up1.4.0 +
registry.suse.com/edge/3.2/sriov-crd-chart:302.0.0_up1.4.0
| System Upgrade Controller | 0.14.2 | 105.0.1 | https://charts.rancher.io/index.yaml[Rancher Charts Helm Repository] +
registry.suse.com/rancher/system-upgrade-controller:v0.14.2
| Upgrade Controller | 0.1.1 | 302.0.0+up0.1.1 | registry.suse.com/edge/3.2/upgrade-controller-chart:302.0.0_up0.1.1 +
registry.suse.com/edge/3.2/upgrade-controller:0.1.1 +
registry.suse.com/edge/3.2/kubectl:1.30.3 +
registry.suse.com/edge/3.2/release-manifest:3.2.0
| Kiwi Builder | 10.1.16.0 | N/A | registry.suse.com/edge/3.2/kiwi-builder:10.1.16.0
|======

[#tech-previews]
= Technology previews

Unless otherwise stated, these apply to the 3.2.0 release and all subsequent z-stream versions.

* Akri is a Technology Preview offering and is not subject to the standard scope of support.
* Edge Image Builder on aarch64 is a Technology Preview offering and is not subject to the standard scope of support.
* IPv6 and dual-stack downstream deployments are a Technology Preview offering and are not subject to the standard scope of support.
* Precision Time Protocol (PTP) on downstream deployments is a Technology Preview offering and is not subject to standard scope of support.

= Components Verification

The components mentioned above may be verified using the Software Bill Of Materials (SBOM) data - for example, using `cosign` as outlined below:

Download the SUSE Edge Container public key from the https://www.suse.com/support/security/keys/[SUSE Signing Keys source]:

[,bash]
----
include::key.sh[]
----

Verify the container image hash, for example using `crane`:

[,bash]
----
> crane digest registry.suse.com/edge/3.2/baremetal-operator:0.8.0
sha256:d85c1bcd286dec81a3806a8fb8b66c0e0741797f23174f5f6f41281b1e27c52f
----

Verify with `cosign`:

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/3.2/baremetal-operator@sha256:d85c1bcd286dec81a3806a8fb8b66c0e0741797f23174f5f6f41281b1e27c52f > /dev/null
#
Verification for registry.suse.com/edge/3.2/baremetal-operator@sha256:d85c1bcd286dec81a3806a8fb8b66c0e0741797f23174f5f6f41281b1e27c52f --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - The claims were present in the transparency log
  - The signatures were integrated into the transparency log when the certificate was valid
  - The signatures were verified against the specified public key
----

Extract SBOM data as described at the https://www.suse.com/support/security/sbom/[SUSE SBOM documentation]:

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/3.2/baremetal-operator@sha256:d85c1bcd286dec81a3806a8fb8b66c0e0741797f23174f5f6f41281b1e27c52f | jq '.payload | @base64d | fromjson | .predicate'
----

= Upgrade Steps

Refer to the <<day-2-operations>> for details around how to upgrade to a new release.

Below are some technical considerations to be aware of when upgrading from Edge 3.1:

== SSH root login on SUSE Linux Micro 6.0

In SUSE Linux Micro 5.5 it was possible to SSH as root using password-based authentication, but SUSE Linux Micro 6.0 only key-based authentication is allowed by default.

Systems upgraded to 6.0 from 5.x carry over the old behavior. New installations will enforce the new behavior.

It is recommended to create a non-root user or use key based authentication, but if necessary installing the package `openssh-server-config-rootlogin` restores the old behavior and allows password-based login for the root user.

== Metal^3^ chart changes

In Edge 3.2 the Metal^3^ chart changes some default behavior, chart configuration changes may be required if you require the previous default behavior:

* The Ironic deployment has been rebased to more closely align with the upstream image, which includes several fixes and security improvements:
** Removal of the deprecated `idrac-wsman` driver
** Removal of the `ironic-inspector` API (inspection is now handled via the Ironic API)
** More restrictive access rules for the Ironic HTTP server
* MariaDB is now optional and disabled by default; on upgrade the MariaDB deployment will be replaced by SQLite unless the new `enable_mariadb` chart variable is specified.
* Persistent storage for the Ironic shared volume is now optional and disabled by default - on upgrade it will be necessary to ensure the `size` and `storageClass` persistence values are specified if you wish to retain a PVC in the deployment

= Product Support Lifecycle

SUSE Edge is backed by award-winning support from SUSE, an established technology leader with a proven history of delivering enterprise-quality support services. For more information, see https://www.suse.com/lifecycle[https://www.suse.com/lifecycle] and the Support Policy page at https://www.suse.com/support/policy.html[https://www.suse.com/support/policy.html]. If you have any questions about raising a support case, how SUSE classifies severity levels, or the scope of support, please see the Technical Support Handbook at https://www.suse.com/support/handbook/[https://www.suse.com/support/handbook/].

SUSE Edge "3.2" is supported for 18-months of production support, with an initial 6-months of "full support", followed by 12-months of "maintenance support".  After these support phases the product reaches "end of life" (EOL) and is no longer supported. More info about the lifecycle phases can be found in the table below:

|======
| *Full Support (6 months)* | Urgent and selected high-priority bug fixes will be released during the full support window, and all other patches (non-urgent, enhancements, new capabilities) will be released via the regular release schedule.
| *Maintenance Support (12 months)* | During this period, only critical fixes will be released via patches. Other bug fixes may be released at SUSE's discretion but should not be expected.
| *End of Life (EOL)*  | Once a product release reaches its End of Life date, the customer may continue to use the product within the terms of product licensing agreement.
Support Plans from SUSE do not apply to product releases past their EOL date.
|======

Unless explicitly stated, all components listed are considered Generally Available (GA), and are covered by SUSE's standard scope of support. Some components may be listed as "Technology Preview", where SUSE is providing customers with access to early pre-GA features and functionality for evaluation, but are not subject to the standard support policies and are not recommended for production use-cases. SUSE very much welcomes feedback and suggestions on the improvements that can be made to Technology Preview components, but SUSE reserves the right to deprecate a Technology Preview feature before it becomes Generally Available if it doesn't meet the needs of our customers or doesn't reach a state of maturity that we require.

Please note that SUSE must occasionally deprecate features or change API specifications. Reasons for feature deprecation or API change could include a feature being updated or replaced by a new implementation, a new feature set, upstream technology is no longer available, or the upstream community has introduced incompatible changes. It is not intended that this will ever happen within a given minor release (x.z), and so all z-stream releases will maintain API compatibility and feature functionality. SUSE will endeavor to provide deprecation warnings with plenty of notice within the release notes, along with workarounds, suggestions, and mitigations to minimize service disruption.

The SUSE Edge team also welcomes community feedback, where issues can be raised within the respective code repository within https://www.github.com/suse-edge[https://www.github.com/suse-edge].

= Obtaining source code

This SUSE product includes materials licensed to SUSE under the GNU General Public License (GPL) and various other open source licenses. The GPL requires SUSE to provide the source code that corresponds to the GPL-licensed material, and SUSE conforms to all other open-source license requirements. As such, SUSE makes all source code available, and can generally be found in the SUSE Edge GitHub repository (https://www.github.com/suse-edge[https://www.github.com/suse-edge]), the SUSE Rancher GitHub repository (https://www.github.com/rancher[https://www.github.com/rancher]) for dependent components, and specifically for SUSE Linux Micro, the source code is available for download at https://www.suse.com/download/sle-micro/[https://www.suse.com/download/sle-micro] on "Medium 2".

= Legal notices

SUSE makes no representations or warranties with regard to the contents or use of this documentation, and specifically disclaims any express or implied warranties of merchantability or fitness for any particular purpose. Further, SUSE reserves the right to revise this publication and to make changes to its content, at any time, without the obligation to notify any person or entity of such revisions or changes.

Further, SUSE makes no representations or warranties with regard to any software, and specifically disclaims any express or implied warranties of merchantability or fitness for any particular purpose. Further, SUSE reserves the right to make changes to any and all parts of SUSE software, at any time, without any obligation to notify any person or entity of such changes.

Any products or technical information provided under this Agreement may be subject to U.S. export controls and the trade laws of other countries. You agree to comply with all export control regulations and to obtain any required licenses or classifications to export, re-export, or import deliverables. You agree not to export or re-export to entities on the current U.S. export exclusion lists or to any embargoed or terrorist countries as specified in U.S. export laws. You agree to not use deliverables for prohibited nuclear, missile, or chemical/biological weaponry end uses. Refer to https://www.suse.com/company/legal/[https://www.suse.com/company/legal/] for more information on exporting SUSE software. SUSE assumes no responsibility for your failure to obtain any necessary export approvals.

*Copyright © 2024 SUSE LLC.*

This release notes document is licensed under a Creative Commons Attribution-NoDerivatives 4.0 International License (CC-BY-ND-4.0). You should have received a copy of the license along with this document. If not, see https://creativecommons.org/licenses/by-nd/4.0/[https://creativecommons.org/licenses/by-nd/4.0/].

SUSE has intellectual property rights relating to technology embodied in the product that is described in this document. In particular, and without limitation, these intellectual property rights may include one or more of the U.S. patents listed at https://www.suse.com/company/legal/[https://www.suse.com/company/legal/] and one or more additional patents or pending patent applications in the U.S. and other countries.

For SUSE trademarks, see the SUSE Trademark and Service Mark list (https://www.suse.com/company/legal/[https://www.suse.com/company/legal/]). All third-party trademarks are the property of their respective owners. For SUSE brand information and usage requirements, please see the guidelines published at https://brand.suse.com/[https://brand.suse.com/].
