[#release-notes]

= Abstract
:revdate: 2025-09-25
:page-revdate: {revdate}
ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

SUSE Edge 3.4 is a tightly integrated and comprehensively validated end-to-end solution for addressing the unique challenges of the deployment of infrastructure and cloud-native applications at the edge. Its driving focus is to provide an opinionated, yet highly flexible, highly scalable, and secure platform that spans initial deployment image building, node provisioning and onboarding, application deployment, observability, and lifecycle management.

The solution is designed with the notion that there is no "one-size-fits-all" edge platform due to our customers’ widely varying requirements and expectations. Edge deployments push us to solve, and continually evolve, some of the most challenging problems, including massive scalability, restricted network availability, physical space constraints, new security threats and attack vectors, variations in hardware architecture and system resources, the requirement to deploy and interface with legacy infrastructure and applications, and customer solutions that have extended lifespans.

SUSE Edge is built on best-of-breed open source software from the ground up, consistent with both our 30-year history in delivering secure, stable, and certified SUSE Linux platforms and our experience in providing highly scalable and feature-rich Kubernetes management with our Rancher portfolio. SUSE Edge builds on-top of these capabilities to deliver functionality that can address a wide number of market segments, including retail, medical, transportation, logistics, telecommunications, smart manufacturing, and Industrial IoT.

For more information on product support lifecycle updates for SUSE Edge, see link:https://www.suse.com/lifecycle/#suse-edge-33[Product Support Lifecycle]. 

NOTE: SUSE Telco Cloud (formerly known as SUSE Edge for Telco) is a derivative of SUSE Edge, with additional optimizations and components that enable the platform to address the requirements found in telecommunications use-cases. Unless explicitly stated, all the release notes are applicable for both SUSE Edge 3.4, and SUSE Telco Cloud 3.4.

= About

These Release Notes are, unless explicitly specified and explained, identical across all architectures, and the most recent version, along with the release notes of all other SUSE products are always available online at https://www.suse.com/releasenotes[https://www.suse.com/releasenotes].

Entries are only listed once, but they can be referenced in several places if they are important and belong to more than one section. Release notes usually only list changes that happened between two subsequent releases. Certain important entries from the release notes of previous product versions may be repeated. To make these entries easier to identify, they contain a note to that effect.

However, repeated entries are provided as a courtesy only. Therefore, if you are skipping one or more releases, check the release notes of the skipped releases also. If you are only reading the release notes of the current release, you could miss important changes that may affect system behavior. SUSE Edge versions are defined as x.y.z, where 'x' denotes the major version, 'y' denotes the minor, and 'z' denotes the patch version, also known as the "z-stream". SUSE Edge product lifecycles are defined based around a given minor release, e.g. "3.4", but ship with subsequent patch updates through its lifecycle, e.g. "3.4.1".

NOTE: SUSE Edge z-stream releases are tightly integrated and thoroughly tested as a versioned stack. Upgrade of any individual components to a different versions to those listed above is likely to result in system downtime. While it's possible to run Edge clusters in untested configurations, it is not recommended, and it may take longer to provide resolution through the support channels.

[#release-notes-3-4-1]
= Release 3.4.1
Availability date: 22th October 2025

Full Support End Date: 20th March 2026

Maintenance Support End Date: 20th September 2027

EOL: 21st September 2027

Summary: SUSE Edge 3.4.1 is the first z-stream release in SUSE Edge 3.4 release stream

== New Features

* Updated to Kubernetes 1.33.5 and Rancher Prime 2.12.3 https://github.com/rancher/rancher/releases/tag/v2.11.6[Release Notes]
* Updated to SUSE Security (Neuvector) 5.4.6 https://open-docs.neuvector.com/releasenotes/5x/#546-august-2025[Release Notes]
* Updated to SUSE Storage (Longhorn) 1.9.1 https://longhorn.io/docs/1.9.1/important-notes/[Release Notes]

== Bug & Security Fixes

* SUSE Security (Neuvector) 5.4.6 contains several bugfixes https://open-docs.neuvector.com/releasenotes/5x/#bugs-fixed[Upstream Neuvector Bug Fixes]
* https://github.com/rancher/rke2/releases/tag/v1.33.5%2Brke2r1[RKE2 1.33.5] contains several updates and fixes, including resolution of an issue in certain deployments related to CPU affinity https://github.com/opencontainers/runc/pull/4858[Upstream runc issue]


== Known Issues

[WARNING]
====
If deploying new clusters, please follow <<guides-kiwi-builder-images>> to build fresh images first as this is now the first step required to create clusters for both {x86-64} and {aarch64} architectures as well as management and downstream clusters.
====

* When deploying via Edge Image Builder, `HelmChartConfigs` manifests may fail if they are put in the `kubernetes/manifests` configuration directory. Instead it is reccomended to place any `HelmChartConfigs` in `/var/lib/rancher/{rke2/k3s}/server/manifests/` using the EIB os-files interface, see <<mgmt-cluster-directory-structure>> for example.  Failure to do this may cause nodes to stay in `NotReady` state on initial startup, as discussed in https://github.com/rancher/rke2/issues/8357[#8357 RKE2 issue]

* On RKE2/K3s 1.31, 1.32 and 1.33 versions, the directory `/etc/cni` being used to store CNI configurations may not trigger a notification of the files being written there to `containerd` due to certain conditions related to `overlayfs` (see the https://github.com/rancher/rke2/issues/8356[#8356 RKE2 issue]). This in turn results in the deployment of RKE2/K3s to get stuck waiting for the CNI to start, and the RKE2/K3s nodes to stay in `NotReady` state. This can be seen at node level with `kubectl describe node <affected_node>`:

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

As a workaround, a tmpfs volume can be mounted at the `/etc/cni` directory before RKE2 starts. It avoids the usage of overlayfs which results in containerd missing notifications and the configs should get rewritten every time the node is restarted and the pods initcontainers run again. If using EIB, this can be a `04-tmpfs-cni.sh` script in the `custom/scripts` directory (as explained here[https://github.com/suse-edge/edge-image-builder/blob/release-1.2/docs/building-images.md#custom]) that looks like:

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* When onboarding remote hosts using Elemental, a race condition between `dbus.service` and `elemental-system-agent.service` might occur, resulting in `rancher-system-agent.service` on remote host to fail starting with errors similar to the one below. (see the https://github.com/suse-edge/edge-image-builder/issues/784[#784 Edge Image Builder issue] for details.)

[,bash]
----
Sep 19 19:38:07 elementalvm elemental-system-agent[3671]: time="2025-09-19T19:38:07Z" level=info msg="[6b20fe64c854da2639804884b34129bb8f718eb59578111da58d9de1509c24db_1:stderr]: Failed to restart rancher-system-agent.service: Message recipient disconnected from message bus without replying"
----

As a workaround, a systemd override file can be created as below

[,bash]
----
[Unit]
Wants=dbus.service network-online.target
After=dbus.service network-online.target time-sync.target

[Service]
ExecStartPre=/bin/bash -c 'echo "Waiting for dbus to become active..." | systemd-cat -p info -t elemental-system-agent; sleep 15; timeout 300 bash -c "while ! systemctl is-active --quiet dbus.service; do sleep 15; done"'
----

and a custom script named `30a-copy-elemental-system-agent-override.sh` can be used to place the override to `/etc/systemd/system/elemental-system-agent.service.d` prior to EIB's https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/templates/31-elemental-register.sh.tpl[31-elemental-register.sh] script runs during the combustion phase.

[,bash]
----
#!/bin/bash

/bin/mkdir -p /etc/systemd/system/elemental-system-agent.service.d
/bin/cp -f elemental-system-agent-override.conf /etc/systemd/system/elemental-system-agent.service.d/override.conf
----

== Component Versions

The following table describes the individual components that make up the 3.4.1 release, including the version, the Helm chart version (if applicable), and from where the released artifact can be pulled in the binary format. Please follow the associated documentation for usage and deployment examples.

|======
| Name | Version | Helm Chart Version | Artifact Location (URL/Image)
| SUSE Linux Micro | 6.1 (latest) | N/A | https://www.suse.com/download/sle-micro/[SUSE Linux Micro Download Page] +
SL-Micro.x86_64-6.1-Base-SelfInstall-GM.install.iso (sha256 70b9be28f2d92bc3b228412e4fc2b1d5026e691874b728e530b8063522158854) +
SL-Micro.x86_64-6.1-Base-RT-SelfInstall-GM.install.iso (sha256 9ce83e4545d4b36c7c6a44f7841dc3d9c6926fe32dbff694832e0fbd7c496e9d) +
SL-Micro.x86_64-6.1-Base-GM.raw.xz (sha256 36e3efa55822113840dd76fdf6914e933a7b7e88a1dce5cb20c424ccf2fb4430) +
SL-Micro.x86_64-6.1-Base-RT-GM.raw.xz (sha256 2ee66735da3e1da107b4878e73ae68f5fb7309f5ec02b5dfdb94e254fda8415e) +
| SUSE Multi-Linux Manager | 5.0.5 | N/A | https://www.suse.com/download/suse-manager/[SUSE Multi-Linux Manager Download Page]
| K3s | 1.33.5 | N/A | https://github.com/k3s-io/k3s/releases/tag/v1.33.5%2Bk3s1[Upstream K3s Release]
| RKE2 | 1.33.5 | N/A | https://github.com/rancher/rke2/releases/tag/v1.33.5%2Brke2r1[Upstream RKE2 Release]
| SUSE Rancher Prime | 2.12.3 | 2.12.3 | https://charts.rancher.com/server-charts/prime/index.yaml[Rancher Prime Helm Repository] +
https://github.com/rancher/rancher/releases/download/v2.12.3/rancher-images.txt[Rancher 2.12.1 Container Images]
| SUSE Storage (Longhorn) | 1.9.1 | 107.1.0+up1.9.1 | https://charts.rancher.io/index.yaml[Rancher Charts Helm Repository] +
registry.suse.com/rancher/mirrored-longhornio-csi-attacher:v4.9.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-provisioner:v5.3.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-resizer:v1.14.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-snapshotter:v8.3.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-node-driver-registrar:v2.14.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-livenessprobe:v2.16.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-backing-image-manager:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-engine:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-instance-manager:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-manager:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-share-manager:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-ui:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-support-bundle-kit:v0.0.61 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-cli:v1.9.1 +
| SUSE Security | 5.4.6 | 107.0.1+up2.8.8 | https://charts.rancher.io/index.yaml[Rancher Charts Helm Repository] +
registry.suse.com/rancher/neuvector-controller:5.4.6 +
registry.suse.com/rancher/neuvector-enforcer:5.4.6 +
registry.suse.com/rancher/neuvector-manager:5.4.6 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.6 +
registry.suse.com/rancher/neuvector-registry-adapter:0.1.8 +
registry.suse.com/rancher/neuvector-scanner:6 +
registry.suse.com/rancher/neuvector-updater:0.0.4
| Rancher Turtles (CAPI) | 0.24.0 | 304.0.6+up0.24.0 | registry.suse.com/edge/charts/rancher-turtles:304.0.6_up0.24.0 +
registry.rancher.com/rancher/rancher/turtles:v0.24.0 +
registry.rancher.com/rancher/cluster-api-metal3-controller:v1.10.2 +
registry.rancher.com/rancher/cluster-api-metal3-ipam-controller:v1.10.2 +
registry.suse.com/rancher/cluster-api-controller:v1.10.5 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.20.1 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.20.1
| Rancher Turtles Airgap Resources | 0.24.0 | 304.0.6+up0.24.0 | registry.suse.com/edge/charts/rancher-turtles-airgap-resources:304.0.6_up0.24.0
| Metal^3^ | 0.11.5 | 304.0.16+up0.12.6 | registry.suse.com/edge/charts/metal3:304.0.16_up0.12.6 +
registry.suse.com/edge/3.4/baremetal-operator:0.10.2.1 +
registry.suse.com/edge/3.4/ironic:29.0.4.3 +
registry.suse.com/edge/3.4/ironic-ipa-downloader:3.0.9 +
registry.suse.com/edge/mariadb:10.6.15.1
| MetalLB | 0.14.9 | 304.0.0+up0.14.9 | registry.suse.com/edge/charts/metallb:304.0.0_up0.14.9 +
registry.suse.com/edge/3.4/metallb-controller:v0.14.8 +
registry.suse.com/edge/3.4/metallb-speaker:v0.14.8 +
registry.suse.com/edge/3.4/frr:8.4 +
registry.suse.com/edge/3.4/frr-k8s:v0.0.14
| Elemental | 1.7.3 | 1.7.3 | registry.suse.com/rancher/elemental-operator-chart:1.7.3 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.7.3 +
registry.suse.com/rancher/elemental-operator:1.7.3
| Elemental Dashboard Extension | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/4.0.0/charts/elemental/3.0.1[Elemental Extension Helm Chart]
| Edge Image Builder | 1.3.0 | N/A | registry.suse.com/edge/3.4/edge-image-builder:1.3.0
| NM Configurator | 0.3.3 | N/A | https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.3[NMConfigurator Upstream Release]
| KubeVirt | 1.5.2 | 304.0.1+up0.6.0 | registry.suse.com/edge/charts/kubevirt:304.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportproxy:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportserver:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.5.2
| KubeVirt Dashboard Extension | 1.3.2 | 304.0.3+up1.3.2 | registry.suse.com/edge/charts/kubevirt-dashboard-extension:304.0.3_up1.3.2
| Containerized Data Importer | 1.62.0 | 304.0.1+up0.6.0 | registry.suse.com/edge/charts/cdi:304.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-importer:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-cloner:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.62.0
| Endpoint Copier Operator | 0.3.0 | 304.0.1+up0.3.0 | registry.suse.com/edge/charts/endpoint-copier-operator:304.0.1_up0.3.0 +
registry.suse.com/edge/3.4/endpoint-copier-operator:0.3.0
| SR-IOV Network Operator | 1.5.0 | 304.0.2+up1.5.0 | registry.suse.com/edge/charts/sriov-network-operator:304.0.2_up1.5.0 +
registry.suse.com/edge/charts/sriov-crd:304.0.2_up1.5.0
| System Upgrade Controller | 0.16.0 | 107.0.0 | https://charts.rancher.io/index.yaml[Rancher Charts Helm Repository] +
registry.suse.com/rancher/system-upgrade-controller:v0.16.0
| Upgrade Controller | 0.1.1 | 304.0.1+up0.1.1 | registry.suse.com/edge/charts/upgrade-controller:304.0.1_up0.1.1 +
registry.suse.com/edge/3.4/upgrade-controller:0.1.1 +
registry.suse.com/edge/3.4/kubectl:1.33.4 +
registry.suse.com/edge/3.4/release-manifest:3.4.1
| Kiwi Builder | 10.2.12.0 | N/A | registry.suse.com/edge/3.4/kiwi-builder:10.2.12.0
|======



[#release-notes-3-4-0]
= Release 3.4.0

Availability Date: 24th September 2025

Full Support End Date: 20th March 2026

Maintenance Support End Date: 20th September 2027

EOL: 21st September 2027

Summary: SUSE Edge 3.4.0 is the first release in the SUSE Edge 3.4 release stream.

== New Features

* Updated to Kubernetes 1.33 and Rancher Prime 2.12
* Updated Rancher Turtles, Cluster API and Metal3/Ironic versions
* Updated to SUSE Storage (Longhorn) 1.9.1 https://longhorn.io/docs/1.9.1/[Release Notes]
* More flexible deployment of {aarch64} downstream clusters is now possible via the directed network provisioning flow. See <<atip-automated-provisioning>> for more details.
* Deployment of dual-stack clusters is now fully supported (single-stack ipv6 remains in <<tech-previews>>)
* BGP mode for MetalLB is now available as a tech preview see <<tech-previews>> and <<guides-metallb-k3s-l3>> for more details.
* Edge Image Builder has been updated to 1.3.0, see https://github.com/suse-edge/edge-image-builder/blob/release-1.3/RELEASE_NOTES.md[Upstream Release Notes]

== Bug & Security Fixes

* Rancher Prime 2.12 contains several bugfixes https://github.com/rancher/rancher/releases/tag/v2.12.1[Upstream Rancher Release Notes]
* Rancher Prime 2.12 contains a fix for issues related to AppVersion when determining extension upgrade availability, which impacted operation with Edge charts https://github.com/rancher/dashboard/issues/14204[Upstream Issue]
* SUSE Storage (Longhorn) 1.9.1 contains several bugfixes https://github.com/longhorn/longhorn/releases/tag/v1.9.1[Upstream Longhorn Bug Fixes]
* The updated Metal^3^ chart fixes an issue where the wrong MAC may be collected for bonded interfaces during inspection https://bugs.launchpad.net/ironic-python-agent/+bug/2103450[Upstream IPA issue]
* The updated Metal^3^ chart fixes an issue where the deployment may not be correctly restarted on ConfigMap updates https://github.com/suse-edge/charts/issues/219[Upstream Issue]
* The Rancher Turtles update includes a fix which resolves an issue where MachineTemplate ownerReferences were not applied by the RKE2 CAPI provider https://github.com/rancher/cluster-api-provider-rke2/issues/500[Upstream Issue]

== Known Issues

[WARNING]
====
If deploying new clusters, please follow <<guides-kiwi-builder-images>> to build fresh images first as this is now the first step required to create clusters for both {x86-64} and {aarch64} architectures as well as management and downstream clusters.
====

* When deploying via Edge Image Builder, `HelmChartConfigs` manifests may fail if they are put in the `kubernetes/manifests` configuration directory. Instead it is reccomended to place any `HelmChartConfigs` in `/var/lib/rancher/{rke2/k3s}/server/manifests/` using the EIB os-files interface, see <<mgmt-cluster-directory-structure>> for example.  Failure to do this may cause nodes to stay in `NotReady` state on initial startup, as discussed in https://github.com/rancher/rke2/issues/8357[#8357 RKE2 issue]

* On RKE2/K3s 1.31, 1.32 and 1.33 versions, the directory `/etc/cni` being used to store CNI configurations may not trigger a notification of the files being written there to `containerd` due to certain conditions related to `overlayfs` (see the https://github.com/rancher/rke2/issues/8356[#8356 RKE2 issue]). This in turn results in the deployment of RKE2/K3s to get stuck waiting for the CNI to start, and the RKE2/K3s nodes to stay in `NotReady` state. This can be seen at node level with `kubectl describe node <affected_node>`:

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

As a workaround, a tmpfs volume can be mounted at the `/etc/cni` directory before RKE2 starts. It avoids the usage of overlayfs which results in containerd missing notifications and the configs should get rewritten every time the node is restarted and the pods initcontainers run again. If using EIB, this can be a `04-tmpfs-cni.sh` script in the `custom/scripts` directory (as explained here[https://github.com/suse-edge/edge-image-builder/blob/release-1.2/docs/building-images.md#custom]) that looks like:

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* When onboarding remote hosts using Elemental, a race condition between `dbus.service` and `elemental-system-agent.service` might occur, resulting in `rancher-system-agent.service` on remote host to fail starting with errors similar to the one below. (see the https://github.com/suse-edge/edge-image-builder/issues/784[#784 Edge Image Builder issue] for details.)

[,bash]
----
Sep 19 19:38:07 elementalvm elemental-system-agent[3671]: time="2025-09-19T19:38:07Z" level=info msg="[6b20fe64c854da2639804884b34129bb8f718eb59578111da58d9de1509c24db_1:stderr]: Failed to restart rancher-system-agent.service: Message recipient disconnected from message bus without replying"
----

As a workaround, a systemd override file can be created as below

[,bash]
----
[Unit]
Wants=dbus.service network-online.target
After=dbus.service network-online.target time-sync.target

[Service]
ExecStartPre=/bin/bash -c 'echo "Waiting for dbus to become active..." | systemd-cat -p info -t elemental-system-agent; sleep 15; timeout 300 bash -c "while ! systemctl is-active --quiet dbus.service; do sleep 15; done"'
----

and a custom script named `30a-copy-elemental-system-agent-override.sh` can be used to place the override to `/etc/systemd/system/elemental-system-agent.service.d` prior to EIB's https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/templates/31-elemental-register.sh.tpl[31-elemental-register.sh] script runs during the combustion phase.

[,bash]
----
#!/bin/bash

/bin/mkdir -p /etc/systemd/system/elemental-system-agent.service.d
/bin/cp -f elemental-system-agent-override.conf /etc/systemd/system/elemental-system-agent.service.d/override.conf
----

== Component Versions

The following table describes the individual components that make up the 3.4.0 release, including the version, the Helm chart version (if applicable), and from where the released artifact can be pulled in the binary format. Please follow the associated documentation for usage and deployment examples.

|======
| Name | Version | Helm Chart Version | Artifact Location (URL/Image)
| SUSE Linux Micro | 6.1 (latest) | N/A | https://www.suse.com/download/sle-micro/[SUSE Linux Micro Download Page] +
SL-Micro.x86_64-6.1-Base-SelfInstall-GM.install.iso (sha256 70b9be28f2d92bc3b228412e4fc2b1d5026e691874b728e530b8063522158854) +
SL-Micro.x86_64-6.1-Base-RT-SelfInstall-GM.install.iso (sha256 9ce83e4545d4b36c7c6a44f7841dc3d9c6926fe32dbff694832e0fbd7c496e9d) +
SL-Micro.x86_64-6.1-Base-GM.raw.xz (sha256 36e3efa55822113840dd76fdf6914e933a7b7e88a1dce5cb20c424ccf2fb4430) +
SL-Micro.x86_64-6.1-Base-RT-GM.raw.xz (sha256 2ee66735da3e1da107b4878e73ae68f5fb7309f5ec02b5dfdb94e254fda8415e) +
| SUSE Multi-Linux Manager | 5.0.5 | N/A | https://www.suse.com/download/suse-manager/[SUSE Multi-Linux Manager Download Page]
| K3s | 1.33.3 | N/A | https://github.com/k3s-io/k3s/releases/tag/v1.33.3%2Bk3s1[Upstream K3s Release]
| RKE2 | 1.33.3 | N/A | https://github.com/rancher/rke2/releases/tag/v1.33.3%2Brke2r1[Upstream RKE2 Release]
| SUSE Rancher Prime | 2.12.1 | 2.12.1 | https://charts.rancher.com/server-charts/prime/index.yaml[Rancher Prime Helm Repository] +
https://github.com/rancher/rancher/releases/download/v2.12.1/rancher-images.txt[Rancher 2.12.1 Container Images]
| SUSE Storage (Longhorn) | 1.9.1 | 107.0.0+up1.9.1 | https://charts.rancher.io/index.yaml[Rancher Charts Helm Repository] +
registry.suse.com/rancher/mirrored-longhornio-csi-attacher:v4.9.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-provisioner:v5.3.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-resizer:v1.14.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-snapshotter:v8.3.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-node-driver-registrar:v2.14.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-livenessprobe:v2.16.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-backing-image-manager:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-engine:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-instance-manager:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-manager:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-share-manager:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-ui:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-support-bundle-kit:v0.0.61 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-cli:v1.9.1 +
| SUSE Security | 5.4.5 | 107.0.0+up2.8.7 | https://charts.rancher.io/index.yaml[Rancher Charts Helm Repository] +
registry.suse.com/rancher/neuvector-controller:5.4.5 +
registry.suse.com/rancher/neuvector-enforcer:5.4.5 +
registry.suse.com/rancher/neuvector-manager:5.4.5 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.6 +
registry.suse.com/rancher/neuvector-registry-adapter:0.1.8 +
registry.suse.com/rancher/neuvector-scanner:6 +
registry.suse.com/rancher/neuvector-updater:0.0.4
| Rancher Turtles (CAPI) | 0.24.0 | 304.0.6+up0.24.0 | registry.suse.com/edge/charts/rancher-turtles:304.0.6_up0.24.0 +
registry.rancher.com/rancher/rancher/turtles:v0.24.0 +
registry.rancher.com/rancher/cluster-api-metal3-controller:v1.10.2 +
registry.rancher.com/rancher/cluster-api-metal3-ipam-controller:v1.10.2 +
registry.suse.com/rancher/cluster-api-controller:v1.10.5 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.20.1 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.20.1
| Rancher Turtles Airgap Resources | 0.24.0 | 304.0.6+up0.24.0 | registry.suse.com/edge/charts/rancher-turtles-airgap-resources:304.0.6_up0.24.0
| Metal^3^ | 0.11.5 | 304.0.16+up0.12.6 | registry.suse.com/edge/charts/metal3:304.0.16_up0.12.6 +
registry.suse.com/edge/3.4/baremetal-operator:0.10.2.1 +
registry.suse.com/edge/3.4/ironic:29.0.4.3 +
registry.suse.com/edge/3.4/ironic-ipa-downloader:3.0.9 +
registry.suse.com/edge/mariadb:10.6.15.1
| MetalLB | 0.14.9 | 304.0.0+up0.14.9 | registry.suse.com/edge/charts/metallb:304.0.0_up0.14.9 +
registry.suse.com/edge/3.4/metallb-controller:v0.14.8 +
registry.suse.com/edge/3.4/metallb-speaker:v0.14.8 +
registry.suse.com/edge/3.4/frr:8.4 +
registry.suse.com/edge/3.4/frr-k8s:v0.0.14
| Elemental | 1.7.3 | 1.7.3 | registry.suse.com/rancher/elemental-operator-chart:1.7.3 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.7.3 +
registry.suse.com/rancher/elemental-operator:1.7.3
| Elemental Dashboard Extension | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/4.0.0/charts/elemental/3.0.1[Elemental Extension Helm Chart]
| Edge Image Builder | 1.3.0 | N/A | registry.suse.com/edge/3.4/edge-image-builder:1.3.0
| NM Configurator | 0.3.3 | N/A | https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.3[NMConfigurator Upstream Release]
| KubeVirt | 1.5.2 | 304.0.1+up0.6.0 | registry.suse.com/edge/charts/kubevirt:304.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportproxy:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportserver:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.5.2
| KubeVirt Dashboard Extension | 1.3.2 | 304.0.3+up1.3.2 | registry.suse.com/edge/charts/kubevirt-dashboard-extension:304.0.3_up1.3.2
| Containerized Data Importer | 1.62.0 | 304.0.1+up0.6.0 | registry.suse.com/edge/charts/cdi:304.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-importer:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-cloner:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.62.0
| Endpoint Copier Operator | 0.3.0 | 304.0.1+up0.3.0 | registry.suse.com/edge/charts/endpoint-copier-operator:304.0.1_up0.3.0 +
registry.suse.com/edge/3.4/endpoint-copier-operator:0.3.0
| Akri (Deprecated) | 0.12.20 | 304.0.0+up0.12.20 | registry.suse.com/edge/charts/akri:304.0.0_up0.12.20 +
registry.suse.com/edge/charts/akri-dashboard-extension:304.0.0_up1.3.1 +
registry.suse.com/edge/3.4/akri-agent:v0.12.20 +
registry.suse.com/edge/3.4/akri-controller:v0.12.20 +
registry.suse.com/edge/3.4/akri-debug-echo-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.4/akri-onvif-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.4/akri-opcua-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.4/akri-udev-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.4/akri-webhook-configuration:v0.12.20
| SR-IOV Network Operator | 1.5.0 | 304.0.2+up1.5.0 | registry.suse.com/edge/charts/sriov-network-operator:304.0.2_up1.5.0 +
registry.suse.com/edge/charts/sriov-crd:304.0.2_up1.5.0
| System Upgrade Controller | 0.16.0 | 107.0.0 | https://charts.rancher.io/index.yaml[Rancher Charts Helm Repository] +
registry.suse.com/rancher/system-upgrade-controller:v0.16.0
| Upgrade Controller | 0.1.1 | 304.0.1+up0.1.1 | registry.suse.com/edge/charts/upgrade-controller:304.0.1_up0.1.1 +
registry.suse.com/edge/3.4/upgrade-controller:0.1.1 +
registry.suse.com/edge/3.4/kubectl:1.33.4 +
registry.suse.com/edge/3.4/release-manifest:3.4.0
| Kiwi Builder | 10.2.12.0 | N/A | registry.suse.com/edge/3.4/kiwi-builder:10.2.12.0
|======

= Deprecated features

Unless otherwise stated, these apply to the 3.4.0 release and all subsequent z-stream versions.

* Akri was a Technology Preview offering in previous Edge releases and is now deprecated.  Removal is planned for a future release.

[#tech-previews]
= Technology Previews

Unless otherwise stated, these apply to the 3.4.0 release and all subsequent z-stream versions.

* Single-stack IPv6 deployments are a Technology Preview offering and are not subject to the standard scope of support.
* Precision Time Protocol (PTP) on downstream deployments is a Technology Preview offering and is not subject to standard scope of support.
* BGP mode for MetalLB is a Technology Preview offering and is not subject to standard scope of support.

= Component Verification

The components mentioned above may be verified using the Software Bill Of Materials (SBOM) data - for example, using `cosign` as outlined below:

Download the SUSE Edge Container public key from the https://www.suse.com/support/security/keys/[SUSE Signing Keys source]:

[,bash]
----
include::key.sh[]
----

Verify the container image hash, for example using `crane`:

[,bash]
----
> crane digest registry.suse.com/edge/3.4/baremetal-operator:0.10.2.1 --platform linux/amd64
sha256:310d939f8ae4b547710195b9671a4e9ff417420c0856103dd728b051788b5374
----

NOTE: For multi-arch images it is also necessary to specify a platform when obtaining the digest, e.g `--platform linux/amd64` or `--platform linux/arm64`. Failure to do this will result in an error in the following step (`Error: no matching attestations`).

Verify with `cosign`:

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/3.4/baremetal-operator@sha256:310d939f8ae4b547710195b9671a4e9ff417420c0856103dd728b051788b5374 > /dev/null
#
Verification for registry.suse.com/edge/3.4/baremetal-operator@sha256:310d939f8ae4b547710195b9671a4e9ff417420c0856103dd728b051788b5374 --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - The signatures were verified against the specified public key
----

Extract SBOM data as described at the https://www.suse.com/support/security/sbom/[SUSE SBOM documentation]:

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/3.4/baremetal-operator@sha256:310d939f8ae4b547710195b9671a4e9ff417420c0856103dd728b051788b5374 | jq '.payload | @base64d | fromjson | .predicate'
----

= Upgrade Steps

Refer to the <<day-2-operations>> for details around how to upgrade to a new release.

= Product Support Lifecycle

SUSE Edge is backed by award-winning support from SUSE, an established technology leader with a proven history of delivering enterprise-quality support services. For more information, see https://www.suse.com/lifecycle[https://www.suse.com/lifecycle] and the Support Policy page at https://www.suse.com/support/policy.html[https://www.suse.com/support/policy.html]. If you have any questions about raising a support case, how SUSE classifies severity levels, or the scope of support, please see the Technical Support Handbook at https://www.suse.com/support/handbook/[https://www.suse.com/support/handbook/].

SUSE Edge "3.4" is supported for 24-months of production support, with an initial 6-months of "full support", followed by 18-months of "maintenance support".  After these support phases the product reaches "end of life" (EOL) and is no longer supported. More info about the lifecycle phases can be found in the table below:

|======
| *Full Support (6 months)* | Urgent and selected high-priority bug fixes will be released during the full support window, and all other patches (non-urgent, enhancements, new capabilities) will be released via the regular release schedule.
| *Maintenance Support (18 months)* | During this period, only critical fixes will be released via patches. Other bug fixes may be released at SUSE's discretion but should not be expected.
| *End of Life (EOL)*  | Once a product release reaches its End of Life date, the customer may continue to use the product within the terms of product licensing agreement.
Support Plans from SUSE do not apply to product releases past their EOL date.
|======

Unless explicitly stated, all components listed are considered Generally Available (GA), and are covered by SUSE's standard scope of support. Some components may be listed as "Technology Preview", where SUSE is providing customers with access to early pre-GA features and functionality for evaluation, but are not subject to the standard support policies and are not recommended for production use-cases. SUSE very much welcomes feedback and suggestions on the improvements that can be made to Technology Preview components, but SUSE reserves the right to deprecate a Technology Preview feature before it becomes Generally Available if it doesn't meet the needs of our customers or doesn't reach a state of maturity that we require.

Please note that SUSE must occasionally deprecate features or change API specifications. Reasons for feature deprecation or API change could include a feature being updated or replaced by a new implementation, a new feature set, upstream technology is no longer available, or the upstream community has introduced incompatible changes. It is not intended that this will ever happen within a given minor release (x.z), and so all z-stream releases will maintain API compatibility and feature functionality. SUSE will endeavor to provide deprecation warnings with plenty of notice within the release notes, along with workarounds, suggestions, and mitigations to minimize service disruption.

The SUSE Edge team also welcomes community feedback, where issues can be raised within the respective code repository within https://www.github.com/suse-edge[https://www.github.com/suse-edge].

= Obtaining source code

This SUSE product includes materials licensed to SUSE under the GNU General Public License (GPL) and various other open source licenses. The GPL requires SUSE to provide the source code that corresponds to the GPL-licensed material, and SUSE conforms to all other open-source license requirements. As such, SUSE makes all source code available, and can generally be found in the SUSE Edge GitHub repository (https://www.github.com/suse-edge[https://www.github.com/suse-edge]), the SUSE Rancher GitHub repository (https://www.github.com/rancher[https://www.github.com/rancher]) for dependent components, and specifically for SUSE Linux Micro, the source code is available for download at https://www.suse.com/download/sle-micro/[https://www.suse.com/download/sle-micro] on "Medium 2".

= Legal notices

SUSE makes no representations or warranties with regard to the contents or use of this documentation, and specifically disclaims any express or implied warranties of merchantability or fitness for any particular purpose. Further, SUSE reserves the right to revise this publication and to make changes to its content, at any time, without the obligation to notify any person or entity of such revisions or changes.

Further, SUSE makes no representations or warranties with regard to any software, and specifically disclaims any express or implied warranties of merchantability or fitness for any particular purpose. Further, SUSE reserves the right to make changes to any and all parts of SUSE software, at any time, without any obligation to notify any person or entity of such changes.

Any products or technical information provided under this Agreement may be subject to U.S. export controls and the trade laws of other countries. You agree to comply with all export control regulations and to obtain any required licenses or classifications to export, re-export, or import deliverables. You agree not to export or re-export to entities on the current U.S. export exclusion lists or to any embargoed or terrorist countries as specified in U.S. export laws. You agree to not use deliverables for prohibited nuclear, missile, or chemical/biological weaponry end uses. Refer to https://www.suse.com/company/legal/[https://www.suse.com/company/legal/] for more information on exporting SUSE software. SUSE assumes no responsibility for your failure to obtain any necessary export approvals.

*Copyright © 2024 SUSE LLC.*

This release notes document is licensed under a Creative Commons Attribution-NoDerivatives 4.0 International License (CC-BY-ND-4.0). You should have received a copy of the license along with this document. If not, see https://creativecommons.org/licenses/by-nd/4.0/[https://creativecommons.org/licenses/by-nd/4.0/].

SUSE has intellectual property rights relating to technology embodied in the product that is described in this document. In particular, and without limitation, these intellectual property rights may include one or more of the U.S. patents listed at https://www.suse.com/company/legal/[https://www.suse.com/company/legal/] and one or more additional patents or pending patent applications in the U.S. and other countries.

For SUSE trademarks, see the SUSE Trademark and Service Mark list (https://www.suse.com/company/legal/[https://www.suse.com/company/legal/]). All third-party trademarks are the property of their respective owners. For SUSE brand information and usage requirements, please see the guidelines published at https://brand.suse.com/[https://brand.suse.com/].
