[#release-notes]

= Abstract
:revdate: 2025-07-17
:page-revdate: {revdate}
ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

SUSE Edge 3.3 is a tightly integrated and comprehensively validated end-to-end solution for addressing the unique challenges of the deployment of infrastructure and cloud-native applications at the edge. Its driving focus is to provide an opinionated, yet highly flexible, highly scalable, and secure platform that spans initial deployment image building, node provisioning and onboarding, application deployment, observability, and lifecycle management.

The solution is designed with the notion that there is no "one-size-fits-all" edge platform due to our customers’ widely varying requirements and expectations. Edge deployments push us to solve, and continually evolve, some of the most challenging problems, including massive scalability, restricted network availability, physical space constraints, new security threats and attack vectors, variations in hardware architecture and system resources, the requirement to deploy and interface with legacy infrastructure and applications, and customer solutions that have extended lifespans.

SUSE Edge is built on best-of-breed open source software from the ground up, consistent with both our 30-year history in delivering secure, stable, and certified SUSE Linux platforms and our experience in providing highly scalable and feature-rich Kubernetes management with our Rancher portfolio. SUSE Edge builds on-top of these capabilities to deliver functionality that can address a wide number of market segments, including retail, medical, transportation, logistics, telecommunications, smart manufacturing, and Industrial IoT.

NOTE: SUSE Telco Cloud (formerly known as SUSE Edge for Telco) is a derivative of SUSE Edge, with additional optimizations and components that enable the platform to address the requirements found in telecommunications use-cases. Unless explicitly stated, all the release notes are applicable for both SUSE Edge 3.3, and SUSE Telco Cloud 3.3.

= About

These Release Notes are, unless explicitly specified and explained, identical across all architectures, and the most recent version, along with the release notes of all other SUSE products are always available online at https://www.suse.com/releasenotes[https://www.suse.com/releasenotes].

Entries are only listed once, but they can be referenced in several places if they are important and belong to more than one section. Release notes usually only list changes that happened between two subsequent releases. Certain important entries from the release notes of previous product versions may be repeated. To make these entries easier to identify, they contain a note to that effect.

However, repeated entries are provided as a courtesy only. Therefore, if you are skipping one or more releases, check the release notes of the skipped releases also. If you are only reading the release notes of the current release, you could miss important changes that may affect system behavior. SUSE Edge versions are defined as x.y.z, where 'x' denotes the major version, 'y' denotes the minor, and 'z' denotes the patch version, also known as the "z-stream". SUSE Edge product lifecycles are defined based around a given minor release, e.g. "3.3", but ship with subsequent patch updates through its lifecycle, e.g. "3.3.1".

NOTE: SUSE Edge z-stream releases are tightly integrated and thoroughly tested as a versioned stack. Upgrade of any individual components to a different versions to those listed above is likely to result in system downtime. While it's possible to run Edge clusters in untested configurations, it is not recommended, and it may take longer to provide resolution through the support channels.

[#release-notes-3-3-2]
= Release 3.3.2

Availability Date: 20th August 2025

Summary: SUSE Edge 3.3.2 is the second z-stream release in the SUSE Edge 3.3 release stream.

== New Features

* Updated to Kubernetes 1.32.5 and Rancher Prime 2.11.3 https://github.com/rancher/rancher/releases/tag/v2.11.3[Release Notes]
* Updated to SUSE Storage (Longhorn) 1.8.2 https://longhorn.io/docs/1.8.2/[Release Notes]
* Updated to SUSE Security (Neuvector) 5.4.5 https://open-docs.neuvector.com/releasenotes/5x/#545-july-2025[Release Notes]
* Updated to Rancher Turtles 0.21.0 https://turtles.docs.rancher.com/turtles/stable/en/changelogs/changelogs/v0.21.0.html[Release Notes]

== Bug & Security Fixes

* SUSE Storage (Longhorn) 1.8.2 contains several bugfixes https://github.com/longhorn/longhorn/releases/tag/v1.8.2[Upstream Longhorn Bug Fixes]
* SUSE Security (Neuvector) 5.4.5 contains several bugfixes https://open-docs.neuvector.com/releasenotes/5x/#bug-fixes[Upstream Neuvector Bug Fixes]
* The RKE2 CAPI provider has been updated to resolve an issue where rolling upgrades can result in Machines stuck in Deleting state https://github.com/rancher/cluster-api-provider-rke2/issues/655[Upstream RKE2 provider issue 655]

== Known Issues

[WARNING]
====
If deploying new clusters, please follow <<guides-kiwi-builder-images>> to build fresh images first as this is now the first step required to create clusters for both {x86-64} and {aarch64} architectures as well as management and downstream clusters.
====

* When deploying via Edge Image Builder, `HelmChartConfigs` manifests may fail if they are put in the `kubernetes/manifests` configuration directory. Instead it is reccomended to place any `HelmChartConfigs` in `/var/lib/rancher/{rke2/k3s}/server/manifests/` using the EIB os-files interface, see <<mgmt-cluster-directory-structure>> for example.  Failure to do this may cause nodes to stay in `NotReady` state on initial startup, as discussed in https://github.com/rancher/rke2/issues/8357[#8357 RKE2 issue]

* On RKE2/K3s 1.31 and 1.32 versions, the directory `/etc/cni` being used to store CNI configurations may not trigger a notification of the files being written there to `containerd` due to certain conditions related to `overlayfs` (see the https://github.com/rancher/rke2/issues/8356[#8356 RKE2 issue]). This in turn results in the deployment of RKE2/K3s to get stuck waiting for the CNI to start, and the RKE2/K3s nodes to stay in `NotReady` state. This can be seen at node level with `kubectl describe node <affected_node>`:

[,bash]
----
<200b><200b>Conditions:
  Type         »Status  LastHeartbeatTime             »·LastTransitionTime            »·Reason                   »··Message
  ----         »------  -----------------             »·------------------            »·------                   »··-------
  Ready        »False   Thu, 05 Jun 2025 17:41:28 +0000   Thu, 05 Jun 2025 14:38:16 +0000   KubeletNotReady          »··container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

As a workaround, a tmpfs volume can be mounted at the `/etc/cni` directory before RKE2 starts. It avoids the usage of overlayfs which results in containerd missing notifications and the configs should get rewritten every time the node is restarted and the pods initcontainers run again. If using EIB, this can be a `04-tmpfs-cni.sh` script in the `custom/scripts` directory (as explained here[https://github.com/suse-edge/edge-image-builder/blob/release-1.2/docs/building-images.md#custom]) that looks like:

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

== Component Versions

The following table describes the individual components that make up the 3.3.2 release, including the version, the Helm chart version (if applicable), and from where the released artifact can be pulled in the binary format. Please follow the associated documentation for usage and deployment examples.

|======
| Name | Version | Helm Chart Version | Artifact Location (URL/Image)
| SUSE Linux Micro | 6.1 (latest) | N/A | https://www.suse.com/download/sle-micro/[SUSE Linux Micro Download Page] +
SL-Micro.x86_64-6.1-Base-SelfInstall-GM.install.iso (sha256 70b9be28f2d92bc3b228412e4fc2b1d5026e691874b728e530b8063522158854) +
SL-Micro.x86_64-6.1-Base-RT-SelfInstall-GM.install.iso (sha256 9ce83e4545d4b36c7c6a44f7841dc3d9c6926fe32dbff694832e0fbd7c496e9d) +
SL-Micro.x86_64-6.1-Base-GM.raw.xz (sha256 36e3efa55822113840dd76fdf6914e933a7b7e88a1dce5cb20c424ccf2fb4430) +
SL-Micro.x86_64-6.1-Base-RT-GM.raw.xz (sha256 2ee66735da3e1da107b4878e73ae68f5fb7309f5ec02b5dfdb94e254fda8415e) +
| SUSE Multi-Linux Manager | 5.0.3 | N/A | https://www.suse.com/download/suse-manager/[SUSE Multi-Linux Manager Download Page]
s| K3s s| 1.32.5 | N/A | https://github.com/k3s-io/k3s/releases/tag/v1.32.5%2Bk3s1[Upstream K3s Release]
s| RKE2 s| 1.32.5 | N/A | https://github.com/rancher/rke2/releases/tag/v1.32.5%2Brke2r1[Upstream RKE2 Release]
s| SUSE Rancher Prime s| 2.11.3 | 2.11.3 | https://charts.rancher.com/server-charts/prime/index.yaml[Rancher Prime Helm Repository] +
https://github.com/rancher/rancher/releases/download/v2.11.3/rancher-images.txt[Rancher 2.11.3 Container Images]
s| SUSE Storage s| 1.8.2 s| 106.2.1+up1.8.2 | https://charts.rancher.io/index.yaml[Rancher Charts Helm Repository] +
*registry.suse.com/rancher/mirrored-longhornio-csi-attacher:v4.9.0* +
*registry.suse.com/rancher/mirrored-longhornio-csi-provisioner:v5.3.0* +
registry.suse.com/rancher/mirrored-longhornio-csi-resizer:v1.13.2 +
registry.suse.com/rancher/mirrored-longhornio-csi-snapshotter:v8.2.0 +
*registry.suse.com/rancher/mirrored-longhornio-csi-node-driver-registrar:v2.14.0* +
*registry.suse.com/rancher/mirrored-longhornio-livenessprobe:v2.16.0* +
*registry.suse.com/rancher/mirrored-longhornio-backing-image-manager:v1.8.2* +
*registry.suse.com/rancher/mirrored-longhornio-longhorn-engine:v1.8.2* +
*registry.suse.com/rancher/mirrored-longhornio-longhorn-instance-manager:v1.8.2* +
*registry.suse.com/rancher/mirrored-longhornio-longhorn-manager:v1.8.2* +
*registry.suse.com/rancher/mirrored-longhornio-longhorn-share-manager:v1.8.2* +
*registry.suse.com/rancher/mirrored-longhornio-longhorn-ui:v1.8.2* +
registry.suse.com/rancher/mirrored-longhornio-support-bundle-kit:v0.0.52 +
*registry.suse.com/rancher/mirrored-longhornio-longhorn-cli:v1.8.2* +
s| SUSE Security s| 5.4.5 s| 106.0.2+up2.8.7 | https://charts.rancher.io/index.yaml[Rancher Charts Helm Repository] +
*registry.suse.com/rancher/neuvector-controller:5.4.5* +
*registry.suse.com/rancher/neuvector-enforcer:5.4.5* +
*registry.suse.com/rancher/neuvector-manager:5.4.5* +
*registry.suse.com/rancher/neuvector-compliance-config:1.0.6* +
registry.suse.com/rancher/neuvector-registry-adapter:0.1.6 +
registry.suse.com/rancher/neuvector-scanner:6 +
registry.suse.com/rancher/neuvector-updater:0.0.3
s| Rancher Turtles (CAPI) s| 0.21.0 s| 303.0.5+up0.21.0 | *registry.suse.com/edge/charts/rancher-turtles:303.0.5_up0.21.0* +
*registry.rancher.com/rancher/rancher/turtles:v0.21.0* +
*registry.rancher.com/rancher/cluster-api-operator:v0.18.1* +
*registry.rancher.com/rancher/cluster-api-metal3-controller:v1.9.4* +
registry.rancher.com/rancher/cluster-api-metal3-ipam-controller:v1.9.4 +
registry.suse.com/rancher/cluster-api-controller:v1.9.5 +
*registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.18.0* +
*registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.18.0*
s| Rancher Turtles Airgap Resources s| 0.21.0 s| 303.0.5+up0.21.0 s| registry.suse.com/edge/charts/rancher-turtles-airgap-resources:303.0.5_up0.21.0
| Metal^3^ | 0.11.5 | 303.0.7+up0.11.5 | registry.suse.com/edge/charts/metal3:303.0.7_up0.11.5 +
registry.suse.com/edge/3.3/baremetal-operator:0.9.1.1 +
registry.suse.com/edge/3.3/ironic:26.1.2.4 +
registry.suse.com/edge/3.3/ironic-ipa-downloader:3.0.7 +
registry.suse.com/edge/mariadb:10.6.15.1
| MetalLB | 0.14.9 | 303.0.0+up0.14.9 | registry.suse.com/edge/charts/metallb:303.0.0_up0.14.9 +
registry.suse.com/edge/3.3/metallb-controller:v0.14.8 +
registry.suse.com/edge/3.3/metallb-speaker:v0.14.8 +
registry.suse.com/edge/3.3/frr:8.4 +
registry.suse.com/edge/3.3/frr-k8s:v0.0.14
| Elemental | 1.6.8 | 1.6.8 | registry.suse.com/rancher/elemental-operator-chart:1.6.8 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.6.8 +
registry.suse.com/rancher/elemental-operator:1.6.8
| Elemental Dashboard Extension | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/4.0.0/charts/elemental/3.0.1[Elemental Extension Helm Chart]
| Edge Image Builder | 1.2.1 | N/A | registry.suse.com/edge/3.3/edge-image-builder:1.2.1
| NM Configurator | 0.3.3 | N/A | https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.3[NMConfigurator Upstream Release]
| KubeVirt | 1.4.0 | 303.0.0+up0.5.0 | registry.suse.com/edge/charts/kubevirt:303.0.0_up0.5.0 +
registry.suse.com/suse/sles/15.6/virt-operator:1.4.0 +
registry.suse.com/suse/sles/15.6/virt-api:1.4.0 +
registry.suse.com/suse/sles/15.6/virt-controller:1.4.0 +
registry.suse.com/suse/sles/15.6/virt-exportproxy:1.4.0 +
registry.suse.com/suse/sles/15.6/virt-exportserver:1.4.0 +
registry.suse.com/suse/sles/15.6/virt-handler:1.4.0 +
registry.suse.com/suse/sles/15.6/virt-launcher:1.4.0
| KubeVirt Dashboard Extension | 1.3.2 | 303.0.2+up1.3.2 | registry.suse.com/edge/charts/kubevirt-dashboard-extension:303.0.2_up1.3.2
| Containerized Data Importer | 1.61.0 | 303.0.0+up0.5.0 | registry.suse.com/edge/charts/cdi:303.0.0_up0.5.0 +
registry.suse.com/suse/sles/15.6/cdi-operator:1.61.0 +
registry.suse.com/suse/sles/15.6/cdi-controller:1.61.0 +
registry.suse.com/suse/sles/15.6/cdi-importer:1.61.0 +
registry.suse.com/suse/sles/15.6/cdi-cloner:1.61.0 +
registry.suse.com/suse/sles/15.6/cdi-apiserver:1.61.0 +
registry.suse.com/suse/sles/15.6/cdi-uploadserver:1.61.0 +
registry.suse.com/suse/sles/15.6/cdi-uploadproxy:1.61.0
| Endpoint Copier Operator | 0.2.0 | 303.0.0+up0.2.1 | registry.suse.com/edge/charts/endpoint-copier-operator:303.0.0_up0.2.1 +
registry.suse.com/edge/3.3/endpoint-copier-operator:0.2.0
| Akri (Tech Preview) | 0.12.20 | 303.0.0+up0.12.20 | registry.suse.com/edge/charts/akri:303.0.0_up0.12.20 +
registry.suse.com/edge/charts/akri-dashboard-extension:303.0.0_up1.3.1 +
registry.suse.com/edge/3.3/akri-agent:v0.12.20 +
registry.suse.com/edge/3.3/akri-controller:v0.12.20 +
registry.suse.com/edge/3.3/akri-debug-echo-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.3/akri-onvif-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.3/akri-opcua-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.3/akri-udev-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.3/akri-webhook-configuration:v0.12.20
| SR-IOV Network Operator | 1.5.0 | 303.0.2+up1.5.0 | registry.suse.com/edge/charts/sriov-network-operator:303.0.2_up1.5.0 +
registry.suse.com/edge/charts/sriov-crd:303.0.2_up1.5.0
| System Upgrade Controller | 0.15.2 | 106.0.0 | https://charts.rancher.io/index.yaml[Rancher Charts Helm Repository] +
registry.suse.com/rancher/system-upgrade-controller:v0.15.2
| Upgrade Controller | 0.1.1 | 303.0.1+up0.1.1 | registry.suse.com/edge/charts/upgrade-controller:303.0.1_up0.1.1 +
registry.suse.com/edge/3.3/upgrade-controller:0.1.1 +
registry.suse.com/edge/3.3/kubectl:1.32.4 +
*registry.suse.com/edge/3.3/release-manifest:3.3.2*
| Kiwi Builder | 10.2.12.0 | N/A | registry.suse.com/edge/3.3/kiwi-builder:10.2.12.0
|======

[#release-notes-3-3-1]
= Release 3.3.1

Availability Date: 13th June 2025

Summary: SUSE Edge 3.3.1 is first z-stream release in the SUSE Edge 3.3 release stream.

== New Features

* Updated to Kubernetes 1.32.4 and Rancher Prime 2.11.2 https://github.com/rancher/rancher/releases/tag/v2.11.2[Release Notes]
* Updated to SUSE Security (Neuvector) 5.4.4 https://open-docs.neuvector.com/releasenotes/5x#544-may-2025[Release Notes]
* Updated to Rancher Turtles 0.20.0 https://turtles.docs.rancher.com/turtles/stable/en/changelogs/changelogs/v0.20.0.html[Release Notes]

== Bug & Security Fixes

* In some cases when using a management cluster that has been upgraded from Edge 3.2 to 3.3.0, downstream rolling upgrades via CAPI could result in Machines stuck in Deleting state, this has been resolved via an update to the RKE2 CAPI provider https://github.com/rancher/cluster-api-provider-rke2/issues/661[Upstream RKE2 provider issue 661]
* When configuring networking via nm-configurator, certain configurations which identify interfaces by MAC in 3.3.0 did not work, this has been resolved by updating NMC to 0.3.3 with corresponding updates to the EIB and Metal^3^ IPA downloader container images  https://github.com/suse-edge/nm-configurator/issues/163[Upstream NM Configurator Issue]
* For long running Metal^3^ management clusters in 3.3.0, it was possible for certificate expiry to cause the baremetal-operator connection to ironic to fail, requiring a workaround of a manual pod restart, this has been resolved via updates to the Metal^3^ chart https://github.com/suse-edge/charts/issues/178[SUSE Edge charts issue]
* Previously Rancher UI was not not able to list SUSE Edge charts from OCI registry in the Application catalog. This has been resolved with the update to Rancher 2.11.2 https://github.com/rancher/rancher/issues/48746[Rancher Issue]

== Known Issues

[WARNING]
====
If deploying new clusters, please follow <<guides-kiwi-builder-images>> to build fresh images first as this is now the first step required to create clusters for both {x86-64} and {aarch64} architectures as well as management and downstream clusters.
====

* When using `toolbox` in SUSE Linux Micro 6.1, the default container image does not contain some tools which were included in the previous 5.5 version.  The workaround is to configure toolbox to use the previous `suse/sle-micro/5.5/toolbox` container image, see `toolbox --help` for options to configure the image.
* In some cases rolling upgrades via CAPI can result in Machines stuck in Deleting state, this will be resolved via a future update https://github.com/rancher/cluster-api-provider-rke2/issues/655[Upstream RKE2 provider issue 655]
* Due to fixes related to https://nvd.nist.gov/vuln/detail/CVE-2025-1974[CVE-2025-1974] as mentioned in 3.3.0, SUSE Linux Micro 6.1 *must* be updated to include kernel `>=6.4.0-26-default` or `>=6.4.0-30-rt` (real-time kernel) due to required SELinux kernel patches. If not applied, the ingress-nginx pod will remain in a `CrashLoopBackOff` state. To apply the kernel update run `transactional-update` on the host itself (to update all packages), or `transactional-update pkg update kernel-default` (or kernel-rt) to update just the kernel, then reboot the host. If deploying new clusters, please follow <<guides-kiwi-builder-images>> to build fresh images containing the latest kernel.

* On RKE2/K3s 1.31 and 1.32 versions, the directory `/etc/cni` being used to store CNI configurations may not trigger a notification of the files being written there to `containerd` due to certain conditions related to `overlayfs` (see the https://github.com/rancher/rke2/issues/8356[#8356 RKE2 issue]). This in turn results in the deployment of RKE2/K3s to get stuck waiting for the CNI to start, and the RKE2/K3s nodes to stay in `NotReady` state. This can be seen at node level with `kubectl describe node <affected_node>`:

[,bash]
----
<200b><200b>Conditions:
  Type         »Status  LastHeartbeatTime             »·LastTransitionTime            »·Reason                   »··Message
  ----         »------  -----------------             »·------------------            »·------                   »··-------
  Ready        »False   Thu, 05 Jun 2025 17:41:28 +0000   Thu, 05 Jun 2025 14:38:16 +0000   KubeletNotReady          »··container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

As a workaround, a tmpfs volume can be mounted at the `/etc/cni` directory before RKE2 starts. It avoids the usage of overlayfs which results in containerd missing notifications and the configs should get rewritten every time the node is restarted and the pods initcontainers run again. If using EIB, this can be a `04-tmpfs-cni.sh` script in the `custom/scripts` directory (as explained here[https://github.com/suse-edge/edge-image-builder/blob/release-1.2/docs/building-images.md#custom]) that looks like:

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

== Component Versions

The following table describes the individual components that make up the 3.3.1 release, including the version, the Helm chart version (if applicable), and from where the released artifact can be pulled in the binary format. Please follow the associated documentation for usage and deployment examples.

|======
| Name | Version | Helm Chart Version | Artifact Location (URL/Image)
| SUSE Linux Micro | 6.1 (latest) | N/A | https://www.suse.com/download/sle-micro/[SUSE Linux Micro Download Page] +
SL-Micro.x86_64-6.1-Base-SelfInstall-GM.install.iso (sha256 70b9be28f2d92bc3b228412e4fc2b1d5026e691874b728e530b8063522158854) +
SL-Micro.x86_64-6.1-Base-RT-SelfInstall-GM.install.iso (sha256 9ce83e4545d4b36c7c6a44f7841dc3d9c6926fe32dbff694832e0fbd7c496e9d) +
SL-Micro.x86_64-6.1-Base-GM.raw.xz (sha256 36e3efa55822113840dd76fdf6914e933a7b7e88a1dce5cb20c424ccf2fb4430) +
SL-Micro.x86_64-6.1-Base-RT-GM.raw.xz (sha256 2ee66735da3e1da107b4878e73ae68f5fb7309f5ec02b5dfdb94e254fda8415e) +
| SUSE Multi-Linux Manager | 5.0.3 | N/A | https://www.suse.com/download/suse-manager/[SUSE Multi-Linux Manager Download Page]
s| K3s s| 1.32.4 | N/A | https://github.com/k3s-io/k3s/releases/tag/v1.32.4%2Bk3s1[Upstream K3s Release]
s| RKE2 s| 1.32.4 | N/A | https://github.com/rancher/rke2/releases/tag/v1.32.4%2Brke2r1[Upstream RKE2 Release]
s| SUSE Rancher Prime s| 2.11.2 | 2.11.2 | https://charts.rancher.com/server-charts/prime/index.yaml[Rancher Prime Helm Repository] +
https://github.com/rancher/rancher/releases/download/v2.11.1/rancher-images.txt[Rancher 2.11.1 Container Images]
| SUSE Storage | 1.8.1 | 106.2.0+up1.8.1 | https://charts.rancher.io/index.yaml[Rancher Charts Helm Repository] +
registry.suse.com/rancher/mirrored-longhornio-csi-attacher:v4.8.1 +
registry.suse.com/rancher/mirrored-longhornio-csi-provisioner:v5.2.0 +
registry.suse.com/rancher/mirrored-longhornio-csi-resizer:v1.13.2 +
registry.suse.com/rancher/mirrored-longhornio-csi-snapshotter:v8.2.0 +
registry.suse.com/rancher/mirrored-longhornio-csi-node-driver-registrar:v2.13.0 +
registry.suse.com/rancher/mirrored-longhornio-livenessprobe:v2.15.0 +
registry.suse.com/rancher/mirrored-longhornio-backing-image-manager:v1.8.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-engine:v1.8.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-instance-manager:v1.8.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-manager:v1.8.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-share-manager:v1.8.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-ui:v1.8.1 +
registry.suse.com/rancher/mirrored-longhornio-support-bundle-kit:v0.0.52 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-cli:v1.8.1 +
s| SUSE Security s| 5.4.4 s| 106.0.1+up2.8.6 | https://charts.rancher.io/index.yaml[Rancher Charts Helm Repository] +
*registry.suse.com/rancher/neuvector-controller:5.4.4* +
*registry.suse.com/rancher/neuvector-enforcer:5.4.4* +
*registry.suse.com/rancher/neuvector-manager:5.4.4* +
*registry.suse.com/rancher/neuvector-compliance-config:1.0.5* +
registry.suse.com/rancher/neuvector-registry-adapter:0.1.6 +
registry.suse.com/rancher/neuvector-scanner:6 +
*registry.suse.com/rancher/neuvector-updater:0.0.3*
s| Rancher Turtles (CAPI) | 0.20.0 | 303.0.4+up0.20.0 | *registry.suse.com/edge/charts/rancher-turtles:303.0.3_up0.20.0* +
*registry.rancher.com/rancher/rancher/turtles:v0.20.0* +
registry.rancher.com/rancher/cluster-api-operator:v0.17.0 +
registry.rancher.com/rancher/cluster-api-metal3-controller:v1.9.3 +
registry.rancher.com/rancher/cluster-api-metal3-ipam-controller:v1.9.4 +
registry.suse.com/rancher/cluster-api-controller:v1.9.5 +
*registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.16.1* +
*registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.16.1*
s| Rancher Turtles Airgap Resources s| 0.20.0 s| 303.0.4+up0.20.0 s| registry.suse.com/edge/charts/rancher-turtles-airgap-resources:303.0.3_up0.20.0
s| Metal^3^ s| 0.11.5 s| 303.0.7+up0.11.5 | *registry.suse.com/edge/charts/metal3:303.0.7_up0.11.5* +
*registry.suse.com/edge/3.3/baremetal-operator:0.9.1.1* +
registry.suse.com/edge/3.3/ironic:26.1.2.4 +
*registry.suse.com/edge/3.3/ironic-ipa-downloader:3.0.7* +
registry.suse.com/edge/mariadb:10.6.15.1
| MetalLB | 0.14.9 | 303.0.0+up0.14.9 | registry.suse.com/edge/charts/metallb:303.0.0_up0.14.9 +
registry.suse.com/edge/3.3/metallb-controller:v0.14.8 +
registry.suse.com/edge/3.3/metallb-speaker:v0.14.8 +
registry.suse.com/edge/3.3/frr:8.4 +
registry.suse.com/edge/3.3/frr-k8s:v0.0.14
| Elemental | 1.6.8 | 1.6.8 | registry.suse.com/rancher/elemental-operator-chart:1.6.8 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.6.8 +
registry.suse.com/rancher/elemental-operator:1.6.8
| Elemental Dashboard Extension | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/4.0.0/charts/elemental/3.0.1[Elemental Extension Helm Chart]
s| Edge Image Builder s| 1.2.1 | N/A | *registry.suse.com/edge/3.3/edge-image-builder:1.2.1*
s| NM Configurator s| 0.3.3 | N/A | https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.3[NMConfigurator Upstream Release]
| KubeVirt | 1.4.0 | 303.0.0+up0.5.0 | registry.suse.com/edge/charts/kubevirt:303.0.0_up0.5.0 +
registry.suse.com/suse/sles/15.6/virt-operator:1.4.0 +
registry.suse.com/suse/sles/15.6/virt-api:1.4.0 +
registry.suse.com/suse/sles/15.6/virt-controller:1.4.0 +
registry.suse.com/suse/sles/15.6/virt-exportproxy:1.4.0 +
registry.suse.com/suse/sles/15.6/virt-exportserver:1.4.0 +
registry.suse.com/suse/sles/15.6/virt-handler:1.4.0 +
registry.suse.com/suse/sles/15.6/virt-launcher:1.4.0
| KubeVirt Dashboard Extension | 1.3.2 | 303.0.2+up1.3.2 | registry.suse.com/edge/charts/kubevirt-dashboard-extension:303.0.2_up1.3.2
| Containerized Data Importer | 1.61.0 | 303.0.0+up0.5.0 | registry.suse.com/edge/charts/cdi:303.0.0_up0.5.0 +
registry.suse.com/suse/sles/15.6/cdi-operator:1.61.0 +
registry.suse.com/suse/sles/15.6/cdi-controller:1.61.0 +
registry.suse.com/suse/sles/15.6/cdi-importer:1.61.0 +
registry.suse.com/suse/sles/15.6/cdi-cloner:1.61.0 +
registry.suse.com/suse/sles/15.6/cdi-apiserver:1.61.0 +
registry.suse.com/suse/sles/15.6/cdi-uploadserver:1.61.0 +
registry.suse.com/suse/sles/15.6/cdi-uploadproxy:1.61.0
| Endpoint Copier Operator | 0.2.0 | 303.0.0+up0.2.1 | registry.suse.com/edge/charts/endpoint-copier-operator:303.0.0_up0.2.1 +
registry.suse.com/edge/3.3/endpoint-copier-operator:0.2.0
| Akri (Tech Preview) | 0.12.20 | 303.0.0+up0.12.20 | registry.suse.com/edge/charts/akri:303.0.0_up0.12.20 +
registry.suse.com/edge/charts/akri-dashboard-extension:303.0.0_up1.3.1 +
registry.suse.com/edge/3.3/akri-agent:v0.12.20 +
registry.suse.com/edge/3.3/akri-controller:v0.12.20 +
registry.suse.com/edge/3.3/akri-debug-echo-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.3/akri-onvif-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.3/akri-opcua-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.3/akri-udev-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.3/akri-webhook-configuration:v0.12.20
| SR-IOV Network Operator | 1.5.0 | 303.0.2+up1.5.0 | registry.suse.com/edge/charts/sriov-network-operator:303.0.2_up1.5.0 +
registry.suse.com/edge/charts/sriov-crd:303.0.2_up1.5.0
| System Upgrade Controller | 0.15.2 | 106.0.0 | https://charts.rancher.io/index.yaml[Rancher Charts Helm Repository] +
registry.suse.com/rancher/system-upgrade-controller:v0.15.2
s| Upgrade Controller s| 0.1.1 s| 303.0.1+up0.1.1 | *registry.suse.com/edge/charts/upgrade-controller:303.0.1_up0.1.1* +
registry.suse.com/edge/3.3/upgrade-controller:0.1.1 +
*registry.suse.com/edge/3.3/kubectl:1.32.4* +
*registry.suse.com/edge/3.3/release-manifest:3.3.1*
| Kiwi Builder | 10.2.12.0 | N/A | registry.suse.com/edge/3.3/kiwi-builder:10.2.12.0
|======

[#release-notes-3-3-0]
= Release 3.3.0

Availability Date: 20th May 2025

Summary: SUSE Edge 3.3.0 is the first release in the SUSE Edge 3.3 release stream.

== New Features

* Updated to Kubernetes 1.32, and Rancher Prime 2.11
* Updated Operating System to https://documentation.suse.com/sle-micro/6.1[SUSE Linux Micro 6.1]
* Updated Rancher Turtles, Cluster API and Metal3/Ironic versions
* A container image is now provided which enables building updated SUSE Linux Micro images. See <<guides-kiwi-builder-images>> for more details.
* Deployment of {aarch64} downstream clusters is now possible via the directed network provisioning flow. See <<atip-automated-provisioning>> for more details.
* Deployment of dual-stack downstream clusters is now possible via the directed network provisioning flow as a technology preview.
* Configuration of Precision Time Protocol (PTP) is now possible as a technology preview. See <<tech-previews>> for more details.

== Bug & Security Fixes

* Addresses https://nvd.nist.gov/vuln/detail/CVE-2025-1974[CVE-2025-1974] with patches for ingress-nginx in RKE2. More information available https://kubernetes.io/blog/2025/03/24/ingress-nginx-cve-2025-1974/[here].
* SUSE Storage (Longhorn) 1.8.1 contains several bugfixes, including
** Fix volume FailedMount issue which can cause volume attachment to fail https://github.com/longhorn/longhorn/issues/9939[Upstream Longhorn Issue]
** Fix engine stuck in stopped state issue which can prevent volume attachment https://github.com/longhorn/longhorn/issues/9938[Upstream Longhorn Issue]
* The Metal^3^ chart update contains several bugfixes, including
** A bug when deploying clusters with static IPs in networks with DHCP servers has been resolved https://github.com/suse-edge/charts/pull/196[Upstream Issue]
* The MetalLB chart contains a fix to ensure downstream images are used when frr-k8s is enabled
* The Kiwi Builder has been updated to 10.2.12 to match recent security changes in Kiwi, shifting from https://github.com/OSInside/kiwi/commit/d4d39e481aaff8be28337a9c76c3913a8a482628[md5 to sha256 checksum methods] for image verification.
* The Edge Image Builder image has been rebuilt to include the updated MetalLB release and address the Kiwi changes, both mentioned above.

== Known Issues

[WARNING]
====
If deploying new clusters, please follow <<guides-kiwi-builder-images>> to build fresh images first as this is now the first step required to create clusters for both {x86-64} and {aarch64} architectures as well as management and downstream clusters.
====

* When using `toolbox` in SUSE Linux Micro 6.1, the default container image does not contain some tools which were included in the previous 5.5 version.  The workaround is to configure toolbox to use the previous `suse/sle-micro/5.5/toolbox` container image, see `toolbox --help` for options to configure the image.
* In some cases rolling upgrades via CAPI can result in Machines stuck in Deleting state, this will be resolved via a future update https://github.com/rancher/cluster-api-provider-rke2/issues/655[Upstream RKE2 provider issue 655]
* In some cases when using a management cluster that has been upgraded from Edge 3.2, downstream rolling upgrades via CAPI can result in Machines stuck in Deleting state, this will be resolved via a future update https://github.com/rancher/cluster-api-provider-rke2/issues/661[Upstream RKE2 provider issue 661]
* When using RKE2 1.32.3, which resolves https://nvd.nist.gov/vuln/detail/CVE-2025-1974[CVE-2025-1974], SUSE Linux Micro 6.1 *must* be updated to include kernel `>=6.4.0-26-default` or `>=6.4.0-30-rt` (real-time kernel) due to required SELinux kernel patches. If not applied, the ingress-nginx pod will remain in a `CrashLoopBackOff` state. To apply the kernel update run `transactional-update` on the host itself (to update all packages), or `transactional-update pkg update kernel-default` (or kernel-rt) to update just the kernel, then reboot the host. If deploying new clusters, please follow <<guides-kiwi-builder-images>> to build fresh images containing the latest kernel.
* When configuring networking via nm-congfigurator, certain configurations which identify interfaces by MAC currently do not work, this will be resolved in a future update https://github.com/suse-edge/nm-configurator/issues/163[Upstream NM Configurator Issue]
* For long running Metal^3^ management clusters, it is possible for certificate expiry to cause the baremetal-operator connection to ironic to fail, requiring a workaround of a manual pod restart https://github.com/suse-edge/charts/issues/178[SUSE Edge charts issue]

* On RKE2/K3s 1.31 and 1.32 versions, the directory `/etc/cni` being used to store CNI configurations may not trigger a notification of the files being written there to `containerd` due to certain conditions related to `overlayfs` (see the https://github.com/rancher/rke2/issues/8356[#8356 RKE2 issue]). This in turn results in the deployment of RKE2/K3s to get stuck waiting for the CNI to start, and the RKE2/K3s nodes to stay in `NotReady` state. This can be seen at node level with `kubectl describe node <affected_node>`:

[,bash]
----
​​Conditions:
  Type         	Status  LastHeartbeatTime             	LastTransitionTime            	Reason                   	Message
  ----         	------  -----------------             	------------------            	------                   	-------
  Ready        	False   Thu, 05 Jun 2025 17:41:28 +0000   Thu, 05 Jun 2025 14:38:16 +0000   KubeletNotReady          	container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

As a workaround, a tmpfs volume can be mounted at the `/etc/cni` directory before RKE2 starts. It avoids the usage of overlayfs which results in containerd missing notifications and the configs should get rewritten every time the node is restarted and the pods initcontainers run again. If using EIB, this can be a `04-tmpfs-cni.sh` script in the `custom/scripts` directory (as explained here[https://github.com/suse-edge/edge-image-builder/blob/release-1.2/docs/building-images.md#custom]) that looks like:

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

== Component Versions

The following table describes the individual components that make up the 3.3.0 release, including the version, the Helm chart version (if applicable), and from where the released artifact can be pulled in the binary format. Please follow the associated documentation for usage and deployment examples.

|======
| Name | Version | Helm Chart Version | Artifact Location (URL/Image)
| SUSE Linux Micro | 6.1 (latest) | N/A | https://www.suse.com/download/sle-micro/[SUSE Linux Micro Download Page] +
SL-Micro.x86_64-6.1-Base-SelfInstall-GM.install.iso (sha256 70b9be28f2d92bc3b228412e4fc2b1d5026e691874b728e530b8063522158854) +
SL-Micro.x86_64-6.1-Base-RT-SelfInstall-GM.install.iso (sha256 9ce83e4545d4b36c7c6a44f7841dc3d9c6926fe32dbff694832e0fbd7c496e9d) +
SL-Micro.x86_64-6.1-Base-GM.raw.xz (sha256 36e3efa55822113840dd76fdf6914e933a7b7e88a1dce5cb20c424ccf2fb4430) +
SL-Micro.x86_64-6.1-Base-RT-GM.raw.xz (sha256 2ee66735da3e1da107b4878e73ae68f5fb7309f5ec02b5dfdb94e254fda8415e) +
| SUSE Multi-Linux Manager | 5.0.3 | N/A | https://www.suse.com/download/suse-manager/[SUSE Multi-Linux Manager Download Page]
| K3s | 1.32.3 | N/A | https://github.com/k3s-io/k3s/releases/tag/v1.32.3%2Bk3s1[Upstream K3s Release]
| RKE2 | 1.32.3 | N/A | https://github.com/rancher/rke2/releases/tag/v1.32.3%2Brke2r1[Upstream RKE2 Release]
| SUSE Rancher Prime | 2.11.1 | 2.11.1 | https://charts.rancher.com/server-charts/prime/index.yaml[Rancher Prime Helm Repository] +
https://github.com/rancher/rancher/releases/download/v2.11.1/rancher-images.txt[Rancher 2.11.1 Container Images]
| SUSE Storage | 1.8.1 | 106.2.0+up1.8.1 | https://charts.rancher.io/index.yaml[Rancher Charts Helm Repository] +
registry.suse.com/rancher/mirrored-longhornio-csi-attacher:v4.7.0 +
registry.suse.com/rancher/mirrored-longhornio-csi-provisioner:v4.0.1-20241007 +
registry.suse.com/rancher/mirrored-longhornio-csi-resizer:v1.12.0 +
registry.suse.com/rancher/mirrored-longhornio-csi-snapshotter:v7.0.2-20241007 +
registry.suse.com/rancher/mirrored-longhornio-csi-node-driver-registrar:v2.12.0 +
registry.suse.com/rancher/mirrored-longhornio-livenessprobe:v2.14.0 +
registry.suse.com/rancher/mirrored-longhornio-backing-image-manager:v1.7.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-engine:v1.7.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-instance-manager:v1.7.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-manager:v1.7.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-share-manager:v1.7.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-ui:v1.7.2 +
registry.suse.com/rancher/mirrored-longhornio-support-bundle-kit:v0.0.45 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-cli:v1.7.2 +
| SUSE Security| 5.4.3 | 106.0.0+up2.8.5 | https://charts.rancher.io/index.yaml[Rancher Charts Helm Repository] +
registry.suse.com/rancher/neuvector-controller:5.4.3 +
registry.suse.com/rancher/neuvector-enforcer:5.4.3 +
registry.suse.com/rancher/neuvector-manager:5.4.3 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.4 +
registry.suse.com/rancher/neuvector-registry-adapter:0.1.6 +
registry.suse.com/rancher/neuvector-scanner:6 +
registry.suse.com/rancher/neuvector-updater:0.0.2
| Rancher Turtles (CAPI) | 0.19.0 | 303.0.2+up0.19.0 | registry.suse.com/edge/charts/rancher-turtles:303.0.2_up0.19.0 +
registry.rancher.com/rancher/rancher/turtles:v0.19.0 +
registry.rancher.com/rancher/cluster-api-operator:v0.17.0 +
registry.rancher.com/rancher/cluster-api-metal3-controller:v1.9.3 +
registry.rancher.com/rancher/cluster-api-metal3-ipam-controller:v1.9.4 +
registry.suse.com/rancher/cluster-api-controller:v1.9.5 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.15.1 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.15.1
| Rancher Turtles Airgap Resources | 0.19.0 | 303.0.2+up0.19.0 | registry.suse.com/edge/charts/rancher-turtles-airgap-resources:303.0.2_up0.19.0
| Metal^3^ | 0.11.3 | 303.0.5+up0.11.3 | registry.suse.com/edge/charts/metal3:303.0.5_up0.11.3 +
registry.suse.com/edge/3.3/baremetal-operator:0.9.1 +
registry.suse.com/edge/3.3/ironic:26.1.2.4 +
registry.suse.com/edge/3.3/ironic-ipa-downloader:3.0.6 +
registry.suse.com/edge/mariadb:10.6.15.1
| MetalLB | 0.14.9 | 303.0.0+up0.14.9 | registry.suse.com/edge/charts/metallb:303.0.0_up0.14.9 +
registry.suse.com/edge/3.3/metallb-controller:v0.14.8 +
registry.suse.com/edge/3.3/metallb-speaker:v0.14.8 +
registry.suse.com/edge/3.3/frr:8.4 +
registry.suse.com/edge/3.3/frr-k8s:v0.0.14
| Elemental | 1.6.8 | 1.6.8 | registry.suse.com/rancher/elemental-operator-chart:1.6.8 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.6.8 +
registry.suse.com/rancher/elemental-operator:1.6.8
| Elemental Dashboard Extension | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/4.0.0/charts/elemental/3.0.1[Elemental Extension Helm Chart]
| Edge Image Builder | 1.2.0 | N/A | registry.suse.com/edge/3.3/edge-image-builder:1.2.0
| NM Configurator | 0.3.2 | N/A | https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.2[NMConfigurator Upstream Release]
| KubeVirt | 1.4.0 | 303.0.0+up0.5.0 | registry.suse.com/edge/charts/kubevirt:303.0.0_up0.5.0 +
registry.suse.com/suse/sles/15.6/virt-operator:1.4.0 +
registry.suse.com/suse/sles/15.6/virt-api:1.4.0 +
registry.suse.com/suse/sles/15.6/virt-controller:1.4.0 +
registry.suse.com/suse/sles/15.6/virt-exportproxy:1.4.0 +
registry.suse.com/suse/sles/15.6/virt-exportserver:1.4.0 +
registry.suse.com/suse/sles/15.6/virt-handler:1.4.0 +
registry.suse.com/suse/sles/15.6/virt-launcher:1.4.0
| KubeVirt Dashboard Extension | 1.3.2 | 303.0.2+up1.3.2 | registry.suse.com/edge/charts/kubevirt-dashboard-extension:303.0.2_up1.3.2
| Containerized Data Importer | 1.61.0 | 303.0.0+up0.5.0 | registry.suse.com/edge/charts/cdi:303.0.0_up0.5.0 +
registry.suse.com/suse/sles/15.6/cdi-operator:1.61.0 +
registry.suse.com/suse/sles/15.6/cdi-controller:1.61.0 +
registry.suse.com/suse/sles/15.6/cdi-importer:1.61.0 +
registry.suse.com/suse/sles/15.6/cdi-cloner:1.61.0 +
registry.suse.com/suse/sles/15.6/cdi-apiserver:1.61.0 +
registry.suse.com/suse/sles/15.6/cdi-uploadserver:1.61.0 +
registry.suse.com/suse/sles/15.6/cdi-uploadproxy:1.61.0
| Endpoint Copier Operator | 0.2.0 | 303.0.0+up0.2.1 | registry.suse.com/edge/charts/endpoint-copier-operator:303.0.0_up0.2.1 +
registry.suse.com/edge/3.3/endpoint-copier-operator:0.2.0
| Akri (Tech Preview) | 0.12.20 | 303.0.0+up0.12.20 | registry.suse.com/edge/charts/akri:303.0.0_up0.12.20 +
registry.suse.com/edge/charts/akri-dashboard-extension:303.0.0_up1.3.1 +
registry.suse.com/edge/3.3/akri-agent:v0.12.20 +
registry.suse.com/edge/3.3/akri-controller:v0.12.20 +
registry.suse.com/edge/3.3/akri-debug-echo-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.3/akri-onvif-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.3/akri-opcua-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.3/akri-udev-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.3/akri-webhook-configuration:v0.12.20
| SR-IOV Network Operator | 1.5.0 | 303.0.2+up1.5.0 | registry.suse.com/edge/charts/sriov-network-operator:303.0.2_up1.5.0 +
registry.suse.com/edge/charts/sriov-crd:303.0.2_up1.5.0
| System Upgrade Controller | 0.15.2 | 106.0.0 | https://charts.rancher.io/index.yaml[Rancher Charts Helm Repository] +
registry.suse.com/rancher/system-upgrade-controller:v0.15.2
| Upgrade Controller | 0.1.1 | 303.0.0+up0.1.1 | registry.suse.com/edge/charts/upgrade-controller:303.0.0_up0.1.1 +
registry.suse.com/edge/3.3/upgrade-controller:0.1.1 +
registry.suse.com/edge/3.3/kubectl:1.30.3 +
registry.suse.com/edge/3.3/release-manifest:3.3.0
| Kiwi Builder | 10.2.12.0 | N/A | registry.suse.com/edge/3.3/kiwi-builder:10.2.12.0
|======

[#tech-previews]
= Technology Previews

Unless otherwise stated, these apply to the 3.3.0 release and all subsequent z-stream versions.

* Akri is a Technology Preview offering and is not subject to the standard scope of support.
* IPv6 and dual-stack downstream deployments are a Technology Preview offering and are not subject to the standard scope of support.
* Precision Time Protocol (PTP) on downstream deployments is a Technology Preview offering and is not subject to standard scope of support.

= Component Verification

The components mentioned above may be verified using the Software Bill Of Materials (SBOM) data - for example, using `cosign` as outlined below:

Download the SUSE Edge Container public key from the https://www.suse.com/support/security/keys/[SUSE Signing Keys source]:

[,bash]
----
include::key.sh[]
----

Verify the container image hash, for example using `crane`:

[,bash]
----
> crane digest registry.suse.com/edge/3.3/baremetal-operator:0.9.1 --platform linux/amd64
sha256:02c5590cd51b1a1ea02f9908f2184ef4fbc856eb0197e804a7d57566d9278ddd
----

NOTE: For multi-arch images it is also necessary to specify a platform when obtaining the digest, e.g `--platform linux/amd64` or `--platform linux/arm64`. Failure to do this will result in an error in the following step (`Error: no matching attestations`).

Verify with `cosign`:

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/3.3/baremetal-operator@sha256:02c5590cd51b1a1ea02f9908f2184ef4fbc856eb0197e804a7d57566d9278ddd > /dev/null
#
Verification for registry.suse.com/edge/3.3/baremetal-operator@sha256:02c5590cd51b1a1ea02f9908f2184ef4fbc856eb0197e804a7d57566d9278ddd --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - The claims were present in the transparency log
  - The signatures were integrated into the transparency log when the certificate was valid
  - The signatures were verified against the specified public key
----

Extract SBOM data as described at the https://www.suse.com/support/security/sbom/[SUSE SBOM documentation]:

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/3.2/baremetal-operator@sha256:d85c1bcd286dec81a3806a8fb8b66c0e0741797f23174f5f6f41281b1e27c52f | jq '.payload | @base64d | fromjson | .predicate'
----

= Upgrade Steps

Refer to the <<day-2-operations>> for details around how to upgrade to a new release.

= Product Support Lifecycle

SUSE Edge is backed by award-winning support from SUSE, an established technology leader with a proven history of delivering enterprise-quality support services. For more information, see https://www.suse.com/lifecycle[https://www.suse.com/lifecycle] and the Support Policy page at https://www.suse.com/support/policy.html[https://www.suse.com/support/policy.html]. If you have any questions about raising a support case, how SUSE classifies severity levels, or the scope of support, please see the Technical Support Handbook at https://www.suse.com/support/handbook/[https://www.suse.com/support/handbook/].

SUSE Edge "3.3" is supported for 18-months of production support, with an initial 6-months of "full support", followed by 12-months of "maintenance support".  After these support phases the product reaches "end of life" (EOL) and is no longer supported. More info about the lifecycle phases can be found in the table below:

|======
| *Full Support (6 months)* | Urgent and selected high-priority bug fixes will be released during the full support window, and all other patches (non-urgent, enhancements, new capabilities) will be released via the regular release schedule.
| *Maintenance Support (12 months)* | During this period, only critical fixes will be released via patches. Other bug fixes may be released at SUSE's discretion but should not be expected.
| *End of Life (EOL)*  | Once a product release reaches its End of Life date, the customer may continue to use the product within the terms of product licensing agreement.
Support Plans from SUSE do not apply to product releases past their EOL date.
|======

Unless explicitly stated, all components listed are considered Generally Available (GA), and are covered by SUSE's standard scope of support. Some components may be listed as "Technology Preview", where SUSE is providing customers with access to early pre-GA features and functionality for evaluation, but are not subject to the standard support policies and are not recommended for production use-cases. SUSE very much welcomes feedback and suggestions on the improvements that can be made to Technology Preview components, but SUSE reserves the right to deprecate a Technology Preview feature before it becomes Generally Available if it doesn't meet the needs of our customers or doesn't reach a state of maturity that we require.

Please note that SUSE must occasionally deprecate features or change API specifications. Reasons for feature deprecation or API change could include a feature being updated or replaced by a new implementation, a new feature set, upstream technology is no longer available, or the upstream community has introduced incompatible changes. It is not intended that this will ever happen within a given minor release (x.z), and so all z-stream releases will maintain API compatibility and feature functionality. SUSE will endeavor to provide deprecation warnings with plenty of notice within the release notes, along with workarounds, suggestions, and mitigations to minimize service disruption.

The SUSE Edge team also welcomes community feedback, where issues can be raised within the respective code repository within https://www.github.com/suse-edge[https://www.github.com/suse-edge].

= Obtaining source code

This SUSE product includes materials licensed to SUSE under the GNU General Public License (GPL) and various other open source licenses. The GPL requires SUSE to provide the source code that corresponds to the GPL-licensed material, and SUSE conforms to all other open-source license requirements. As such, SUSE makes all source code available, and can generally be found in the SUSE Edge GitHub repository (https://www.github.com/suse-edge[https://www.github.com/suse-edge]), the SUSE Rancher GitHub repository (https://www.github.com/rancher[https://www.github.com/rancher]) for dependent components, and specifically for SUSE Linux Micro, the source code is available for download at https://www.suse.com/download/sle-micro/[https://www.suse.com/download/sle-micro] on "Medium 2".

= Legal notices

SUSE makes no representations or warranties with regard to the contents or use of this documentation, and specifically disclaims any express or implied warranties of merchantability or fitness for any particular purpose. Further, SUSE reserves the right to revise this publication and to make changes to its content, at any time, without the obligation to notify any person or entity of such revisions or changes.

Further, SUSE makes no representations or warranties with regard to any software, and specifically disclaims any express or implied warranties of merchantability or fitness for any particular purpose. Further, SUSE reserves the right to make changes to any and all parts of SUSE software, at any time, without any obligation to notify any person or entity of such changes.

Any products or technical information provided under this Agreement may be subject to U.S. export controls and the trade laws of other countries. You agree to comply with all export control regulations and to obtain any required licenses or classifications to export, re-export, or import deliverables. You agree not to export or re-export to entities on the current U.S. export exclusion lists or to any embargoed or terrorist countries as specified in U.S. export laws. You agree to not use deliverables for prohibited nuclear, missile, or chemical/biological weaponry end uses. Refer to https://www.suse.com/company/legal/[https://www.suse.com/company/legal/] for more information on exporting SUSE software. SUSE assumes no responsibility for your failure to obtain any necessary export approvals.

*Copyright © 2024 SUSE LLC.*

This release notes document is licensed under a Creative Commons Attribution-NoDerivatives 4.0 International License (CC-BY-ND-4.0). You should have received a copy of the license along with this document. If not, see https://creativecommons.org/licenses/by-nd/4.0/[https://creativecommons.org/licenses/by-nd/4.0/].

SUSE has intellectual property rights relating to technology embodied in the product that is described in this document. In particular, and without limitation, these intellectual property rights may include one or more of the U.S. patents listed at https://www.suse.com/company/legal/[https://www.suse.com/company/legal/] and one or more additional patents or pending patent applications in the U.S. and other countries.

For SUSE trademarks, see the SUSE Trademark and Service Mark list (https://www.suse.com/company/legal/[https://www.suse.com/company/legal/]). All third-party trademarks are the property of their respective owners. For SUSE brand information and usage requirements, please see the guidelines published at https://brand.suse.com/[https://brand.suse.com/].
