= SUSE Edge Documentation

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Welcome to the SUSE Edge documentation! In this set of documentation, you will find quick start guides, validated designs, guidance on using components, third-party integrations, and best practices for managing your edge computing workloads.

== What is SUSE Edge?

The SUSE Edge is a purpose-built cloud native edge computing platform for managing the full lifecycle of edge devices at scale. It is built by putting together open source components into a set of validated designs that we know work together to solve the different constraints we find when designing for and operating edge environments.

== Which Quick Start should you use?

Because there is a varied set of operating environments that each come with their own set of constraints, we support a few different ways to provision your devices.

=== Direct network provisioning

When you know the hardware being used and have direct access to the out-of-band management interface, we provide a solution based on Cluster API and Metal^3^. 

This solution is the most robust since you are directly interacting with the hardware's management interface and have fewer constraints on communication.

The quick start for this solution can be found in <<quickstart-metal3>>.

=== "Phone home" network provisioning

Sometimes you are operating in an environment where the central management cluster cannot manage the hardware directly (for example, your remote network is behind a firewall or there is no out-of-band management interface). In this scenario, we provide tooling to remotely provision clusters and their workloads with no need to know where hardware is being shipped when it is bootstrapped.


The quick start for this solution can be found in <<quickstart-elemental>>.

=== Image-based provisioning

 Lastly, for air-gapped environments or ones with unreliable networks, we provide tooling to easily and repeatably build installation media that includes all the needed artifacts when installing. This includes your workload.

The quick start for this solution can be found in <<quickstart-eib>>.


== Design philosophy

SUSE Edge is designed and built based on the constraints commonly found in edge environments. Since these are different from data centers, this meant rethinking many more common assumptions.

For example, we find value in minimalism, modularity, and ease of operations. 

Minimalism is important for edge environments since the more complex a system is, the more likely it is to break. When looking at hundreds of locations, up to hundreds of thousands, complex systems will break in complex ways. 

Modularity in our solution allows for more user choice while removing unneeded complexity in the deployed platform. 

We also need to balance these with the ease of operations. Humans may make mistakes when repeating a process thousands of times, so the platform should make sure any potential mistakes are recoverable, eliminating the need for on-site technician visits.

== Components used 

SUSE Maintained Components:

* <<components-rancher,Rancher>>
* <<components-fleet,Fleet>>
* <<components-slmicro,SLE Micro>>
* <<components-metal3,Metal^3^>>
* <<components-eib,Edge Image Builder>>
* <<components-elemental,Elemental>>
* <<components-k3s,K3s>>
* <<components-rke2,RKE2>>
* <<components-longhorn,Longhorn>>
* <<components-neuvector,NeuVector>>
* <<components-metallb,MetalLB>>
* <<components-kubevirt,KubeVirt>>
