= SUSE Edge Documentation

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Welcome to the SUSE Edge documentation! In this set of documentation you will find quick starts, our validated designs, how we use components, our 3rd-party integrations, and best practices for managing your edge computing workloads.

== What is SUSE Edge?

The SUSE Edge is a purpose-built cloud native edge computing platform for managing the full lifecycle of edge devices at scale. It is built by putting together open source components into a set of validated designs that we know work together to solve the different constraints we find when designing for and operating edge environments.

== Which Quick Start should you use?

Because there is a varied set of operating environments that each come with their own set of constraints, we support a few different ways to provision your devices.

=== Direct Network Provisioning

When you know the hardware being used and have direct access to the out of band management interface, we provide a solution based on Cluster API and Metal^3^. 

This solution is the most robust since you are directly interacting with the hardware's management interface and have less constraints on communication.

The quick start for this solution can be found here 

TODO add link!

=== "Phone Home" Network Provisioning

Sometimes you are operating in an environment where the central management cluster can't manage the hardware directly (e.g. your remote network is behind a firewall or there is no out of band management interface). In this scenario, we provide tooling to remotely provision clusters and their workloads without needing to know where hardware is being shipped when it's bootstrapped.


The quick start for this solution can be found here 

TODO add link!

=== Image Based Provisioning

Lastly, for airgapped environments or ones with unreliable networks we provide tooling to easily and repeatably build installation media that includes all of the needed artifacts when installing. This includes your workload.

The quick start for this solution can be found here

TODO add link!


== Design Philosophy

TODO write or delete

== Components Used 

SUSE Maintained Components:

* link:../components/rancher.adoc[Rancher]
* link:../components/fleet.adoc[Fleet]
* link:../components/sle-micro.adoc[SLE Micro]
* link:../components/metal3.adoc[Metal^3]
* link:../components/edge-image-builder.adoc[Edge Image Builder]
* link:../components/elemental.adoc[Elemental]
* link:../components/k3s.adoc[K3s]
* link:../components/rke2.adoc[RKE2]
* link:../components/longhorn.adoc[Longhorn]
* link:../components/neuvector.adoc[NeuVector]
* link:../components/metallb.adoc[MetalLB]

Partner Maintained Components:

* link:../integrations/nats.adoc[NATS]
* link:../components/edge-image-builder.adoc[Linkerd]