[#components-eib]
= Edge Image Builder
:revdate: 2025-08-07
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:


ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Consulte el https://github.com/suse-edge/edge-image-builder[Repositorio oficial].
 

Edge Image Builder (EIB) es una herramienta que agiliza la generación de imágenes de disco personalizadas y listas para arrancar (CRB) para iniciar máquinas. Estas imágenes permiten la implementación integral de toda la pila de software de SUSE con una sola imagen.

Aunque EIB puede crear imágenes CRB para todos los escenarios de aprovisionamiento, EIB demuestra un valor tremendo en implementaciones en entornos aislados con redes limitadas o completamente aisladas.


== ¿Cómo utiliza {product} Edge Image Builder?

{product} utiliza EIB para la configuración simplificada y rápida de imágenes personalizadas de SUSE Linux Micro para una variedad de escenarios. Estos escenarios incluyen el inicio de máquinas virtuales y de equipos sin sistema operativo con:

* Implementaciones totalmente aisladas (air-gapped) de Kubernetes K3s/RKE2 (nodo único y multinodo)
* Implementaciones totalmente aisladas (air-gapped) de gráficos Helm y manifiestos de Kubernetes
* Registro en Rancher a través de la API de Elemental
* Metal^3^
* Redes personalizadas (por ejemplo, IP estática, nombre de host, VLAN, bonding, etc.)
* Configuraciones personalizadas del sistema operativo (por ejemplo, usuarios, grupos, contraseñas, claves SSH, proxies, NTP, certificados SSL personalizados, etc.)
* Instalación en entorno aislado de paquetes RPM a nivel de host y cargados lateralmente (incluida la resolución de dependencias)
* Registro en SUSE Multi-Linux Manager para la gestión del SO
* Imágenes de contenedor integradas
* Argumentos de la línea de comandos del núcleo de Linux
* Unidades de systemd que se deben habilitar/deshabilitar en el momento del arranque
* Guiones y archivos personalizados para cualquier tarea manual

== Introducción

Puede encontrar documentación completa sobre el uso y las pruebas de Edge Image Builder {link-eib-docs}[aquí].

Además, consulte <<quickstart-eib>> que cubre un escenario de ampliación básico.

Una vez que esté familiarizado con esta herramienta, encontrará información más útil en nuestra página <<tips-and-tricks,Sección de Consejos y Trucos de EIB>>.

== Problemas conocidos

* EIB aísla los gráficos de Helm mediante la creación de plantillas de los gráficos de Helm y el análisis de todas las imágenes dentro de la plantilla. Si un gráfico de Helm no mantiene todas sus imágenes dentro de la plantilla y, en su lugar, carga las imágenes de forma lateral, EIB no podrá aislar esas imágenes automáticamente. La solución para esto es añadir manualmente cualquier imagen no detectada a la sección `embeddedArtifactRegistry` del archivo de definición.
