[#components-elemental]
= Elemental
:revdate: 16/01/2025
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Elemental es una pila de software que permite la gestión centralizada y completa del sistema operativo nativo de nube con Kubernetes. La pila Elemental consta de una serie de componentes que residen en el propio Rancher o en los nodos edge. Los componentes principales son:

* *elemental-operator* - El operador principal que reside en Rancher y gestiona las solicitudes de registro de los clientes.
* *elemental-register* - El cliente que se ejecuta en los nodos edge permitiendo el registro a través de `elemental-operator`.
* *elemental-system-agent* - Un agente que reside en los nodos edge; su configuración se alimenta desde `elemental-register` y recibe un `plan` para configurar el `rancher-system-agent`
* *rancher-system-agent* - Una vez que el nodo edge se ha registrado completamente, este toma el relevo de `elemental-system-agent` y espera más `plans` de Rancher Manager (por ejemplo, para la instalación de Kubernetes).

Consulte https://elemental.docs.rancher.com/[la documentación en sentido ascendente de Elemental] para obtener información completa sobre Elemental y su relación con Rancher.

== ¿Cómo utiliza {product} Elemental?

Utilizamos partes de Elemental para gestionar dispositivos remotos donde Metal^3^ no es una opción (por ejemplo, no hay BMC, o el dispositivo está detrás de un gateway NAT). Esta herramienta permite a un operador iniciar sus dispositivos en un laboratorio antes de saber cuándo o dónde se enviarán. Concretamente, aprovechamos los componentes `elemental-register` y `elemental-system-agent` para permitir la incorporación de hosts de SUSE Linux Micro a Rancher para casos de uso de aprovisionamiento de red "phone home". Al utilizar Edge Image Builder (EIB) para crear imágenes de despliegue, el registro automático a través de Rancher mediante Elemental puede lograrse especificando la configuración de registro en el directorio de configuración de EIB.

NOTE: En {product} {version-edge} *no* aprovechamos los aspectos de gestión del sistema operativo de Elemental y, por tanto, no es posible gestionar la aplicación de parches de su sistema operativo a través de Rancher. En lugar de utilizar las herramientas de Elemental para crear imágenes de despliegue, {product} utiliza las herramientas de Edge Image Builder, que consumen la configuración de registro.

== Prácticas recomendadas

=== Medios de instalación

La forma recomendada {product} de crear imágenes de despliegue que puedan aprovechar Elemental para el registro en Rancher en el modelo de despliegue de «aprovisionamiento de red phone home» es seguir las instrucciones detalladas en la guía de inicio rápido de <<quickstart-elemental,incorporación de hosts remotos con Elemental>>.

=== Etiquetas

Elemental realiza un seguimiento de su inventario con el CRD `MachineInventory` y proporciona una forma de seleccionar el inventario, por ejemplo, para seleccionar máquinas en las que desplegar clústeres de Kubernetes, basándose en etiquetas. Esto proporciona una forma para que los usuarios predefinan la mayoría (si no todas) de sus necesidades de infraestructura antes incluso de comprar el hardware. Además, dado que los nodos pueden añadir/eliminar etiquetas en sus respectivos objetos de inventario (volviendo a ejecutar `elemental-register` con el indicador adicional `--label "FOO=BAR"`), podemos escribir guiones que descubran y comuniquen a Rancher dónde se ha arrancado un nodo.

== Problemas conocidos

* La interfaz de usuario de Elemental no sabe actualmente cómo crear medios de instalación ni actualizar sistemas operativos que no sean «Elemental Teal». Esto debería solucionarse en futuras versiones.
