[#components-eco]
= Operador de Endpoint Copier
:revdate: 2025-02-28
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:


ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://github.com/suse-edge/endpoint-copier-operator[Endpoint Copier Operator] es un operador de Kubernetes cuyo propósito es crear una copia de un Servicio y un Endpoint de Kubernetes y mantenerlos sincronizados.

== ¿Cómo utiliza {product} el Operador de Endpoint Copier?

En {product}, el Operador de Endpoint Copier desempeña un papel crucial para lograr una configuración de alta disponibilidad (HA) para clústeres K3s/RKE2. Esto se logra creando un servicio `kubernetes-vip` de tipo `LoadBalancer`, asegurando que su Endpoint permanezca en sincronización constante con el Endpoint de Kubernetes. Se aprovecha <<components-metallb,MetalLB>> para gestionar el servicio `kubernetes-vip`, ya que la dirección IP expuesta se utiliza desde otros nodos para unirse al clúster.

== Mejores prácticas

La documentación completa para utilizar el Operador de Endpoint Copier se puede encontrar https://github.com/suse-edge/endpoint-copier-operator/blob/main/README.md[aquí].

Además, consulte <<guides-metallb-k3s,nuestra guía>> sobre cómo lograr una configuración de alta disponibilidad (HA) de K3s/RKE2 utilizando el Operador de Endpoint Copier y MetalLB.

== Problemas conocidos
Actualmente, el Operador de Endpoint Copier está limitado a trabajar con un solo Servicio/Endpoint. Se planean mejoras para admitir múltiples Servicios/Endpoints en el futuro.
