[#components-k3s]
= K3s
:revdate: 16/01/2025
:revnumber: 3,6
:page-revdate: {revdate}
:experimental:


ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://k3s.io/[K3s] es una distribución de Kubernetes certificada y de alta disponibilidad diseñada para cargas de trabajo de producción en ubicaciones remotas, desatendidas y con recursos limitados, o dentro de dispositivos IoT.

Se empaqueta como un binario único y pequeño, por lo que las instalaciones y actualizaciones son rápidas y sencillas.

== ¿Cómo utiliza {product} K3s?

K3s se puede utilizar como la distribución de Kubernetes que respalda la pila {product}.
Está pensado para instalarse en un sistema operativo SUSE Linux Micro.

El uso de K3s como distribución de Kubernetes de la pila {product} solo se recomienda cuando etcd como backend no se ajusta a sus limitaciones. Si etcd como backend es posible, es mejor utilizar <<components-rke2,RKE2>>.

== Prácticas recomendadas

=== Instalación
La forma recomendada de instalar K3s como parte de la pila {product} es mediante Edge Image Builder (EIB). Consulte <<components-eib,su documentación>> para obtener más detalles sobre cómo configurarlo para desplegar K3s.

Admite automáticamente la configuración de alta disponibilidad (HA), así como la configuración de Elemental.

=== Fleet para el flujo de trabajo de GitOps
La pila {product} utiliza Fleet como su herramienta de GitOps preferida.
Para obtener más información sobre su instalación y uso, consulte <<components-fleet,la sección de Fleet>> en esta documentación.

=== Gestión del almacenamiento

K3s viene con almacenamiento de ruta local preconfigurado, que es adecuado para clústeres de un solo nodo.
Para clústeres que abarcan varios nodos, recomendamos utilizar <<components-suse-storage,SUSE Storage>>.

=== Balance de la carga y alta disponibilidad

Si ha instalado K3s utilizando EIB, esta parte ya está cubierta por la documentación de EIB en la sección de alta disponibilidad.

De lo contrario, debe instalar y configurar MetalLB según nuestra <<guides-metallb-k3s,documentación de MetalLB>>.
