[#components-slmicro]
= SUSE Linux Micro
:revdate: 16/01/2025
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


Consultad la {link-micro-official-docs}[documentación oficial de SUSE Linux Micro]

[quote]
____
SUSE Linux Micro es un sistema operativo ligero y seguro para el edge. Fusiona los componentes empresariales reforzados de SUSE Linux Enterprise con las funciones que los desarrolladores desean en un sistema operativo moderno e inmutable. Como resultado, se obtiene una plataforma de infraestructura fiable con la mejor conformidad normativa y fácil de usar.
____

== ¿Cómo utiliza {product} SUSE Linux Micro?

Utilizamos SUSE Linux Micro como sistema operativo base para nuestra pila de plataforma. Esto nos proporciona una base segura, estable y mínima sobre la que construir.

SUSE Linux Micro es único en su uso de instantáneas del sistema de archivos (Btrfs) para permitir reversiones sencillas en caso de que algo salga mal con una actualización. Esto permite realizar actualizaciones remotas seguras de toda la plataforma incluso sin acceso físico en caso de problemas.

== Prácticas recomendadas

=== Medios de instalación

{product} utiliza el <<components-eib,Edge Image Builder>> para preconfigurar la imagen de instalación auto-instalable de SUSE Linux Micro.

=== Administración local

SUSE Linux Micro viene con Cockpit para permitir la gestión local del host a través de una aplicación web.

Este servicio está desactivado por defecto, pero puede iniciarse habilitando el servicio systemd `cockpit.socket`.
Como Cockpit prohíbe el inicio de sesión como root por defecto, se recomienda la creación de un usuario con privilegios administrativos; consultad la {link-micro-official-docs}[documentación oficial de SUSE Linux Micro] para obtener más información.



== Problemas conocidos

* Actualmente no hay ningún entorno de escritorio disponible en SUSE Linux Micro, pero se está desarrollando una solución en contenedores.
