[#components-metal3]
= Metal^3^
:revdate: 2024-11-20
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://metal3.io/[Metal^3^] es un proyecto de la CNCF que proporciona capacidades de gestión de infraestructura de equipo sin sistema operativo para Kubernetes.

Metal^3^ proporciona recursos nativos de Kubernetes para gestionar el ciclo de vida de servidores de equipo sin sistema operativo que admiten la gestión mediante protocolos fuera de banda como https://www.dmtf.org/standards/redfish[Redfish].

También cuenta con un soporte maduro para https://cluster-api.sigs.k8s.io/[Cluster API (CAPI)]. 
Esto permite la gestión de recursos de hardware a través de múltiples proveedores de infraestructura mediante API neutrales respecto al proveedor y ampliamente adoptadas. 
Cluster API utiliza Metal^3^ como backend de infraestructura para objetos Machine.

== ¿Cómo utiliza {product} Metal^3^?

{product} utiliza Metal^3^ para gestionar el ciclo de vida del hardware físico, como los servidores. El hardware debe admitir un protocolo de gestión fuera de banda compatible con Metal^3^ (p. ej., Redfish). Cuando un clúster de gestión {product} aprovisiona o desaprovisiona clústeres de sentido descendente, Metal^3^ interactuará con la BMC de un servidor a través de Redfish. Las siguientes acciones suelen formar parte de esta interacción: +

* Montar y desmontar soportes virtuales (Virtual Media).
* Encender, apagar y reiniciar servidores.

Este enfoque es útil para escenarios en los que el hardware de destino admite la gestión fuera de banda y se desea un flujo de gestión de infraestructura totalmente automatizado.

Metal^3^ y CAPI proporcionan API declarativas que permiten la gestión del inventario y del estado de servidores de equipo sin sistema operativo, incluyendo la inspección, limpieza y aprovisionamiento/desaprovisionamiento automatizados.

== Problemas conocidos

* El controlador https://github.com/metal3-io/ip-address-manager[IP Address Management] de sentido ascendente no es compatible actualmente, ya que todavía no es compatible con nuestra elección de herramientas de configuración de red. Sin embargo, el pod `ipam-controller-manager` alojado en el espacio de nombres `metal3-ipam-system` es necesario, ya que CAPM3 requiere que existan los CRD `ipam`.
* Relacionado con esto, los recursos IPAM y los campos networkData de Metal3DataTemplate no son compatibles.
* Actualmente solo se admite la ampliación mediante redfish-virtualmedia.
