[#components-metal3]
= Metal^3^
:revdate: 2024-11-20
:revnumber: 3,4
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://metal3.io/[Metal^3^] es un proyecto de la CNCF que proporciona capacidades de gestión de infraestructura de equipo sin sistema operativo para Kubernetes.

Metal^3^ proporciona recursos nativos de Kubernetes para gestionar el ciclo de vida de los servidores de equipo sin sistema operativo que admiten la gestión mediante protocolos fuera de banda como https://www.dmtf.org/standards/redfish[Redfish].

También cuenta con un soporte maduro para https://cluster-api.sigs.k8s.io/[Cluster API (CAPI)], que permite la gestión de recursos de infraestructura a través de múltiples proveedores mediante APIs neutrales al proveedor y ampliamente adoptadas.

== ¿Cómo utiliza SUSE Edge Metal^3^?

Este método es útil para escenarios en los que el hardware de destino admite la gestión fuera de banda y se desea un flujo de gestión de infraestructura totalmente automatizado.

Este método proporciona APIs declarativas que permiten la gestión del inventario y del estado de equipos sin sistema operativo, incluyendo la inspección, limpieza y aprovisionamiento/desaprovisionamiento automatizados.

[#known-issues-metal3]
== Problemas conocidos

* El controlador https://github.com/metal3-io/ip-address-manager[IP Address Management] de sentido ascendente no es compatible actualmente, ya que todavía no es compatible con nuestra elección de herramientas de configuración de red. Sin embargo, el pod `ipam-controller-manager` alojado en el espacio de nombres `metal3-ipam-system` es necesario, ya que CAPM3 requiere que existan los CRD `ipam`.
* Relacionado con esto, los recursos IPAM y los campos networkData de Metal3DataTemplate no son compatibles.
* Solo se admite actualmente el despliegue mediante redfish-virtualmedia.
* Es posible observar una falta de coincidencia en el nombre del dispositivo de red entre el agente de Python de ironic (IPA) y el sistema operativo de destino (SL Micro 6.0/6.1), especialmente al intentar configurar nombres predecibles para los dispositivos.

Esto sucede porque el núcleo de Linux del agente de Python de ironic (IPA) no está actualmente alineado con el núcleo de Linux del sistema operativo de destino (SL Micro 6.0/6.1), por lo tanto, hay una falta de coincidencia en los controladores de red que permite al IPA descubrir dispositivos de red con un patrón de nomenclatura diferente al que espera SL Micro.

Existen dos enfoques diferentes que se pueden utilizar como solución provisional mientras tanto: +
* Crear dos secretos diferentes con la configuración de red, uno para ser utilizado con el IPA usando los nombres de dispositivo tal como el IPA los descubrirá y usará como `preprovisioningNetworkDataName` en la definición `BareMetalHost` y otro secreto con los nombres de dispositivo tal como SL Micro los descubrirá y usará como `networkData.name` en la definición `BareMetalHost`. +
* Utilizar los UUID para hacer referencia a otras interfaces en los archivos nmconnection generados en su lugar.
Más detalles en la sección xref:edge.adoc#tips-and-tricks[Tips and tricks].
