[#components-rancher-turtles]
= Rancher Turtles
:revdate: 2025-12-15
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


Consulte la documentación de Rancher Turtles en https://documentation.suse.com/cloudnative/cluster-api/

[quote]
____
Rancher Turtles es un operador de Kubernetes que proporciona integración entre Rancher Manager y Cluster API (CAPI) con el objetivo de brindar soporte de CAPI completo a Rancher
____


== Características clave de Rancher Turtles

* Importación automática de clústeres CAPI en Rancher mediante la instalación del agente de clúster de Rancher en clústeres aprovisionados por CAPI.
* Instale y configure las dependencias del controlador CAPI a través del https://cluster-api-operator.sigs.k8s.io/[Operador CAPI].
* Gestione las dependencias instaladas del proveedor CAPI a través de `CAPIProvider` la API

== Uso de Rancher Turtles en {product}

La pila {product} proporciona un chart de Helm `rancher-turtles-providers` que habilita ciertos proveedores CAPI a través de la API `CAPIProvider`:

* Proveedor del plano de control e iniciar de RKE2
* Proveedor de infraestructura <<components-metal3,Metal3>>
* Proveedor de IPAM <<components-metal3,Metal3>> (actualmente no es compatible)
* Proveedor de complementos de Fleet

Solo se admiten los proveedores predeterminados instalados a través del wrapper chart; los proveedores alternativos de plano de control, iniciar e infraestructura no se admiten actualmente como parte de la pila {product}.

== Instalación de Rancher Turtles

Desde Rancher 2.13, Rancher Turtles está habilitado de forma predeterminada al instalar Rancher.

Los proveedores de Rancher Turtles pueden instalarse siguiendo la guía <<quickstart-metal3,Metal3 Quickstart>> o la documentación del <<atip-management-cluster,clúster de gestión>>.

== Recursos adicionales

* https://rancher.com/docs/[Documentación de Rancher]
* https://cluster-api.sigs.k8s.io/[Libro de Cluster API]
