= SUSE Edge 工程 GitHub 工作流程：最佳实践
:revdate: 2025-07-29
:revnumber: 3.6
:page-revdate: {revdate}

使用 Git 和 GitHub 工作流程的方法有很多种，例如如何创建 PR/MR、将提交拣选到特定分支等。

本文档介绍了 SUSE Edge 工程团队的做法。

== 配置您的用户和电子邮件

[,shell]
----
$ git config --global user.name "FIRST_NAME LAST_NAME"
$ git config --global user.email "MY_NAME@example.com"
----

这可以在每个储存库中单独完成，无需 `--global` 标志。

== Fork 储存库

理想情况下，您不应将更改推送到 suse-edge/ 仓库的分支，而应在 GitHub UI 上 fork 该仓库并在那里 _进行您的操作_。

[NOTE]
====
如果您不想使用与 fork 相同的名称，则不必这样做。
====

== 正确设置 origin/upstream

完成储存库 fork 后，现在将其克隆到您的工作站并配置 origin/upstream 远程储存库：

* 克隆储存库

[,shell]
----
$ git clone git@github.com:e-minguez/suse-edge-charts.git
----

这将创建“origin”远程储存库：

[,shell]
----
$ git remote -v
origin  git@github.com:e-minguez/suse-edge-charts.git (fetch)
origin  git@github.com:e-minguez/suse-edge-charts.git (push)
----

* 添加 upstream 储存库

[,shell]
----
$ git remote add upstream git@github.com:suse-edge/charts.git
----

（可选）禁用推送 URL，以免向其推送：

[,shell]
----
$ git remote set-url --push upstream ""
----

它应显示为：

[,shell]
----
$ git remote -v
origin  git@github.com:e-minguez/suse-edge-charts.git (fetch)
origin  git@github.com:e-minguez/suse-edge-charts.git (push)
upstream        git@github.com:suse-edge/charts.git (fetch)
upstream         (push)
----

== 签署提交

某些储存库要求签署提交，以确认您已阅读并同意该储存库/项目的规则和许可。

提交更改时，只需在提交命令中附加 `-s` 或 `--signoff` 标志，如下所示：

[,shell]
----
$ git commit --signoff --message 'This is my commit message'
----

如果您编写的提交缺少 signed-off-by 行，您可以修改您的提交：

[,shell]
----
git commit --amend --signoff
----

如果您已经将更改推送到 GitHub，则在此之后需要使用 `git push -f` 强制推送您的分支。

== 提交签名验证

您可以对提交进行签名，让其他人确信您所做更改的来源。如果提交或标签具有可加密验证的 GPG、SSH 或 S/MIME 签名，GitHub 会将该提交或标签标记为“已验证”或“部分验证”。

该过程涉及生成 GPG 密钥、使用 SSH 密钥或 X.509 密钥。有关如何配置它的更多信息，请参阅 https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification[GitHub] 文档。

== 保持您的主分支同步

如果您一直在特定分支上工作，并且想要从上游储存库的主分支获取最新更新：

[,shell]
----
$ git switch main
$ git pull --rebase upstream/main
----

== 创建一个分支以处理功能/修复/其他内容

[,shell]
----
$ git switch main
$ git pull --rebase upstream/main
$ git checkout -b myawesomebranch
----

这将创建一个包含主分支内容的新本地分支。

== 将更改从本地分支推送到 GitHub

[,shell]
----
$ git add <files>
$ git commit -av
# Review the changes, add a meaningful commit message and save it
$ git push origin/myawesomebranch
----

== 创建 PR

在上述 git push 消息之后，将显示一个 GitHub URL。访问该 URL 并创建 PR。仔细检查内容、分支、源/目标储存库以及更改列表。

== 变基您的分支

上游储存库主分支中的内容可能会发生变化。您需要更新您的主分支，并对您正在开发的分支进行变基。

[,shell]
----
$ git pull --rebase upstream/main
$ git push --force-with-lease
----

____
可能会出现与 `--force-with-lease` 相关的问题。
____

== 拣选提交

当内容已合并到例如主分支中，而您想将它们拣选到另一个分支（例如 release-3.3）时，流程应为：

* 获取所有分支：

----
$ git fetch --all
----

* 获取您想要拣选（cherry-pick）的提交 ID（来自主分支）：

----
$ git log main --oneline
----

或

----
$ git log main --graph --oneline --all
----

* 创建一个用于存放拣选过程的分支：

----
$ git checkout -b cherry-pick-of-fix-293 upstream/release-3.3
----

* 拣选（cherry-pick）提交：

----
$ git cherry-pick -x <commit-id(s)>
----

观察输出并查看是否存在冲突。如果有，祝您好运，修复它们！:)

* 以防万一，请查看 git 日志：

----
$ git log
----

* 推送更改

----
$ git push origin cherry-pick-of-fix-293
----

* 创建 PR

在上述 git push 消息之后，将显示一个 GitHub URL。访问该 URL 并创建 PR。仔细检查内容、分支、源/目标存储库以及更改列表。

== 采纳来自 PR 的反馈

大多数情况下，拉取请求都需要进行一些更改。要采纳这些反馈，有几种方法，但通常建议在本地修改提交，并将反馈一并推送。

* 验证您是否仍在 PR 分支上：

----
$ git branch
$ git status
----

* 将更改添加到所需文件，并将文件添加到暂存区：

----
$ git add path/to/my/file
----

如果您只想在不更改消息的情况下将更改添加到上一个提交：

----
$ git commit --amend --no-edit
----

然后强制推送该分支（见下文）

如果您想将多个解决反馈的小提交合并为一个干净的提交，或者将它们与 PR 中的先前提交合并：

* 计算您要压缩/重写的提交数量（例如，N）。

----
$ git log --oneliner
----

然后：

----
$ git rebase -i HEAD~N
----

这将打开一个编辑器，您可以在其中压缩、修复、重写等提交

* 保存并关闭编辑器

* 强制推送分支。这需要 _强制推送_，因为远程分支现在与本地分支不同：

----
$ git push --force-with-lease origin myawesomebranch
----

[NOTE]
====
请参阅 https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History[官方 Git 文档以获取更多信息]

如果您正在尝试修复 Github 问题，请记得通过在提交信息中添加“Closes #XXX”或“Fixes #XXX”将 PR 链接到问题。有关此功能的更多信息，请参阅 https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword[使用关键字将拉取请求链接到问题]。
====
