= SUSE Edge 文档
:revdate: 2024-03-06
:revnumber: 3.6
:page-revdate: {revdate}

ifdef::env-github[]
:imagesdir: images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

欢迎访问 SUSE Edge 文档储存库。

== Asciidoctor 与 Markdown 对比

* https://docs.asciidoctor.org/asciidoc/latest/asciidoc-vs-markdown/#comparison-by-example[示例对比]

== Asciidoctor 资源

官方文档::
* https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/[快速参考]
* https://github.com/uyuni-project/uyuni-docs/wiki/asciidoc-getting-started[入门]
* https://github.com/powerman/asciidoc-cheatsheet[速查表]
* https://docs.asciidoctor.org/asciidoc/latest/[Asciidoc 语言文档]

示例（请参阅 `raw` 版本以获取代码）::
* https://github.com/openSUSE/daps/blob/main/test/documents/adoc/part_inlines.adoc[内联元素]
* https://github.com/openSUSE/daps/blob/main/test/documents/adoc/part_block.adoc[块元素]


== 编辑与预览

该文档使用 Asciidoc(tor) 编写。从一个非常基础的 link:template.adoc[模板] 开始。

* 源文件可以直接在 GitHub 中进行编辑和预览。
* 如果您在本地编辑文档
** https://docs.asciidoctor.org/asciidoctor/latest/tooling/#web-browser-add-ons-preview-only[Web 浏览器预览插件]
** https://docs.asciidoctor.org/asciidoctor/latest/tooling/#ides-and-text-editors[IDE 和文本编辑器]
** Emacs 和 vi 也有 asciidoc 模式 ;-)


== 最佳实践

=== 每行一个句子

* 使直接在 GitHub 中进行编辑变得容易得多，并使源文件更具可读性
* 在编辑器中使用软换行


=== 标题必须按顺序排列

* 始终以 0 级标题开始文档
  ** 仅使用单个 0 级标题
* 不允许在后续标题中跳过级别

[,asciidoc]
----
= Level 0

== Level 1

=== Level 2

// ===== Level 4: Not allowed

==== Level 3

== Level 1
----


=== 不要使用自动 ID

Asciidoctor 会自动生成您可以链接到的 ID/锚点：

[,asciidoc]
.不要使用
----
== Usage
...

Refer to <<usage>> for more information. 
----

不建议使用此功能，因为每次更改相应的标题时，您也需要更改引用。
请改用显式 ID/锚点：

[,asciidoc]
.请使用
----
[#usage]
== Usage
...

Refer to <<usage>> for more information. 
----

=== 始终使用块分隔符

某些块元素可以以简短和长格式编写。
始终使用长格式以避免混淆并提高源文件的可读性。

[,asciidoc]
.不要使用
----
NOTE: This is a note

 This is a literal block
----

[,asciidoc]
.请使用
----
[NOTE]
====
This is a note
====

....
This is a literal block
....
----

==== 嵌套结构

嵌套结构（例如列表项内的注释）必须通过加号 (`+`) 字符连接。

[,asciidoc]
----
* normal listitem
* lisitem with annotation
+
[NOTE]
====
note
====
+
* lisitem with two paragraphs
+
second paragraph
+
* normal listitem
----

=== 按键、菜单、按钮

Asciidoctor 附带了三个用于显示按键、菜单选择和按钮点击的宏：

[,asciidoc]
----
Press kbd:[C] to continue or kbd:[Crtl+C] to cancel, kbd:[F1] opens the help menu.

To save the file, select menu:File[Save].
Select menu:View[Zoom > Reset] to reset the zoom level to the default setting.

Press the btn:[OK] button when you are finished.
----

[IMPORTANT]
====
此功能仅在标题中设置了属性 `:experimental:` 时才会激活。
====

=== 标签页视图

使用以 `[.tabs]` 开头的分隔/标记列表：

[,asciidoc]
----
[.tabs]
TAB 1::
+
Content tab 1
+
TAB 2::
+
Content tab 2
----

=== 包含语句必须用空行分隔

请务必确保包含语句的前后都有空行。


== 不支持的 Asciidoc 标签

创建 SUSE 品牌版本时不支持以下内容。
不要使用：

* 高亮、下划线、删除线
+
[,asciidoc]
----
#highlight#
##high##light
[.underline]#underline#
[.line-through]#strike-through#
----
+
* 清单
+
[,asciidoc]
----
* [*] checked
* [x] also checked
* [ ] not checked
----
+
* 音频和视频
+
[,asciidoc]
----
audio::audio.wav[]
video:: video.mp4[]
----
+
* 侧边栏
+
[,asciidoc]
----
****
Sidebar text
****
----
+
* 脚注
+
[,asciidoc]
----
footnote:[Footnote]
----

== 构建文档 

=== 构建通用版本

构建非 SUSE 品牌版本的书籍比构建 SUSE 品牌版本更简单、更快捷。

浏览器扩展（最简单的方法）::
+
* 安装 https://docs.asciidoctor.org/asciidoctor/latest/tooling/#web-browser-add-ons-preview-only[浏览器扩展] 并在浏览器中预览 edge-book/edge.adoc。
* 预览会在保存更改时自动更新
+
本地 HTML 构建::
+
* 在您的系统上安装 asciidoctor。
* 在 GitHub 检出目录中运行以下命令。
+
[,bash]
----
asciidoctor -d book --attribute="toc=left" edge-book/edge.adoc
----
+
* 结果：`edge-book/edge.html`


=== 在本地构建 SUSE 品牌版本

要以发布格式在本地构建文档，请使用 https://github.com/openSUSE/daps2docker[daps2docker]。请注意，检查您的贡献不需要进行这些构建。
只要您的文档在预览中呈现正常，就可以了。


.要求
* 确保您的工作站正在运行 docker 或 podman
* 确保您的用户可以启动容器
* 从 https://download.opensuse.org/repositories/Documentation:/Tools/ 安装 daps2docker
* 导航至此存储库的本地检出目录中的文档目录

构建 HTML::
`daps2docker DC-edge html`
构建单页 HTML::
`daps2docker DC-edge single-html`
构建 PDF::
`daps2docker DC-edge pdf`

[TIP]
.使用 Podman
====
默认情况下，daps2docker 使用 docker 作为其容器引擎。
要使用 Podman，请导出环境变量 CONTAINER_ENGINE=podman：`export CONTAINER_ENGINE=podman`
====

[TIP]
.构建错误
====
daps2docker 从 DocBook XML 源构建文档。
Asciidoctor 带有内置的 DocBook 转换器。

在验证方面，Asciidoc(tor) 比 DocBook 宽容得多。
在某些情况下，有效的 asciidoc 源代码在转换为 DocBook 时无法通过验证。
在这种情况下，使用 daps2docker 进行构建将会失败。
如果发生这种情况，请联系我 (@fsundermeyer)，我会提供帮助。
====

=== 更多信息

...请参阅 https://github.com/openSUSE/daps2docker[daps2docker 储存库]。
您还将找到有关如何在其他发行版上安装它以及如何设置自定义配置的说明。

