[#atip]
= SUSE Telco Cloud
:revdate: 2025-08-25
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc: preamble

== Visão geral

O SUSE Telco Cloud (anteriormente conhecido como {product} para Telco) é uma plataforma de computação otimizada para telecomunicações que permite que operadoras de telecomunicações e fornecedores de redes de telecomunicações inovem e acelerem a modernização de suas redes.

O SUSE Telco Cloud é uma pilha nativa de nuvem completa habilitada para Telco para hospedar CNFs, cobrindo todos os domínios de telecomunicações: Packet Core, RAN, OSS e BSS.

- Automatiza a implementação zero-touch e o gerenciamento do ciclo de vida de configurações complexas de pilha de borda em escala de Telco.
- Garante continuamente a qualidade em hardware de nível Telco, usando configurações e cargas de trabalho específicas para Telco.
- Consiste em componentes criados especificamente para a borda e, portanto, possuem menor pegada e maior desempenho por Watt.
- Mantém uma estratégia de plataforma flexível com APIs neutras em relação ao fornecedor e 100% de código aberto.
