[#{cluster-type}-day2-fleet]
== Fleet
:revdate: 14/01/2025
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Esta sección ofrece información sobre cómo realizar operaciones de «Día 2» utilizando el componente <<components-fleet, Fleet>>.

Los siguientes temas se tratan como parte de esta sección:

. <<{cluster-type}-day2-fleet-components>> - componentes predeterminados utilizados para todas las operaciones de «Día 2».
. <<{cluster-type}-day2-fleet-determine-use-case>> - proporciona una visión general de los recursos personalizados de Fleet que se utilizarán y su idoneidad para diferentes casos de uso de operaciones de «Día 2».
. <<{cluster-type}-day2-upgrade-workflow>> - proporciona una guía de flujo de trabajo para ejecutar operaciones de «Día 2» con Fleet.
. <<{cluster-type}-day2-fleet-os-upgrade>> - describe cómo realizar actualizaciones del SO utilizando Fleet.
. <<{cluster-type}-day2-fleet-k8s-upgrade>> - describe cómo realizar actualizaciones de la versión de Kubernetes utilizando Fleet.
. <<{cluster-type}-day2-fleet-helm-upgrade>> - describe cómo realizar actualizaciones de Helm charts utilizando Fleet.

[#{cluster-type}-day2-fleet-components]
=== Componentes

A continuación, podéis encontrar una descripción de los componentes predeterminados que deben configurarse en vuestro clúster `{cluster-type}` para que podáis realizar con éxito operaciones de «Día 2» utilizando Fleet.

ifeval::["{cluster-type}" == "management"]
==== Rancher

*Opcional*; responsable de gestionar `downstream clusters` y desplegar `System Upgrade Controller` en vuestro `management cluster`.

Para obtener más información, consulte el <<components-rancher>>.
endif::[]

==== System Upgrade Controller (SUC)

ifeval::["{cluster-type}" == "downstream"]
[NOTE]
====
*Debe* desplegarse en cada clúster descendente.
====
endif::[]

*System Upgrade Controller* es responsable de ejecutar tareas en nodos especificados basándose en los datos de configuración proporcionados a través de un recurso personalizado, llamado `Plan`.

*SUC* se utiliza activamente para actualizar el sistema operativo y la distribución de Kubernetes.

Para obtener más información sobre el componente *SUC* y cómo encaja en la pila Edge, consultad <<components-system-upgrade-controller>>.

ifeval::["{cluster-type}" == "downstream"]
Para obtener información sobre cómo desplegar *SUC*, primero <<{cluster-type}-day2-fleet-determine-use-case,determinad vuestro caso de uso>> y, a continuación, consultad <<components-system-upgrade-controller-fleet-gitrepo,Instalación del controlador de actualización del sistema - GitRepo>> o <<components-system-upgrade-controller-fleet-bundle,Instalación del controlador de actualización del sistema - Bundle>>.
endif::[]

[#{cluster-type}-day2-fleet-determine-use-case]
=== Determinad vuestro caso de uso

Fleet utiliza dos tipos de link:https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[recursos personalizados] para permitir la gestión de recursos de Kubernetes y Helm.

A continuación, podéis encontrar información sobre el propósito de estos recursos y los casos de uso para los que son más adecuados en el contexto de las operaciones de «Día 2».

==== GitRepo

Un `GitRepo` es un recurso de <<components-fleet,Fleet>> que representa un repositorio Git desde el cual `Fleet` puede crear `Bundles`. Cada `Bundle` se crea en función de las rutas de configuración definidas dentro del recurso `GitRepo`. Para obtener más información, consultad la https://fleet.rancher.io/gitrepo-add[documentación de GitRepo].

En el contexto de las operaciones de «Día 2», los recursos `GitRepo` se utilizan normalmente para desplegar `SUC` o `SUC Plans` en *entornos no aislados* que utilizan un enfoque de _Fleet GitOps_.

Alternativamente, los recursos `GitRepo` también pueden utilizarse para desplegar `SUC` o `SUC Plans` en *entornos aislados*, *siempre que reflejéis la configuración de vuestro repositorio a través de un servidor git local*.

==== Bundle

`Bundles` contienen recursos de Kubernetes *sin procesar* que se implementarán en el clúster de destino. Normalmente se crean a partir de un recurso `GitRepo`, pero existen casos de uso en los que se pueden desplegar manualmente. Para obtener más información, consultad la https://fleet.rancher.io/bundle-add[documentación de Bundle].

En el contexto de las operaciones de "Día 2", los recursos `Bundle` se utilizan normalmente para desplegar `SUC` o `SUC Plans` en *entornos aislados* que no utilizan ningún tipo de procedimiento de _GitOps local_ (por ejemplo, un *servidor git local*).

Alternativamente, si vuestro caso de uso no permite un flujo de trabajo _GitOps_ (por ejemplo, mediante un repositorio Git), los recursos `Bundle` también podrían utilizarse para desplegar `SUC` o `SUC Plans` en entornos *no aislados*.

[#{cluster-type}-day2-upgrade-workflow]
=== Flujo de trabajo de Día 2

A continuación se muestra un flujo de trabajo de «Día 2» que debe seguirse al actualizar la versión de un clúster {cluster-type} a una versión específica de Edge.

. <<{cluster-type}-day2-fleet-os-upgrade,Actualización de versión del SO>>

. <<{cluster-type}-day2-fleet-k8s-upgrade,Actualización de versión de Kubernetes>>

. <<{cluster-type}-day2-fleet-helm-upgrade,Actualización de versión de Helm charts>>

:leveloffset: +1

include::fleet-os-upgrade.adoc[]

include::fleet-k8s-upgrade.adoc[]

include::fleet-helm-upgrade.adoc[]

:leveloffset: -1
