[#general-troubleshooting-principles]
== 一般的なトラブルシューティングの原則
:revdate: 2025-06-17
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

コンポーネント固有の問題に取り組む前に、以下の一般的な原則を考慮してください。

* *ログを確認する*:ログは情報の主要なソースです。多くの場合、エラーは自己説明的であり、何が失敗したかについてのヒントが含まれています。
* *クロックを確認する*:システム間でクロックに差異があると、あらゆる種類の異なるエラーにつながる可能性があります。クロックが同期されていることを確認してください。EIBは起動時にクロック同期を強制するように指示できます。<<quickstart-eib,OS時刻の設定>>を参照してください。
* *起動の問題*:システムが起動中に停止した場合は、最後に表示されたメッセージを記録してください。コンソール（物理的またはBMC経由）にアクセスして、起動メッセージを確認してください。
* *ネットワークの問題*:ネットワークインタフェースの設定（`ip a`）、ルーティングテーブル（`ip route`）を確認し、他のノードや外部サービスとの接続性をテストしてください（`ping`、`nc`）。ファイアウォールのルールが必要なポートをブロックしていないことを確認してください。
* *コンポーネントの状態を確認する*:Kubernetesリソースには`kubectl get`および`kubectl describe`を使用してください。特定のKubernetesネームスペースのイベントを確認するには、`kubectl get events --sort-by='.lastTimestamp' -n <namespace>`を使用してください。
* *サービスの状態を確認する*:systemdサービスには`systemctl status <service>`を使用してください。
* *構文の確認*:ソフトウェアは、設定ファイルに対して特定の構造と構文を想定しています。例えばyamlファイルの場合、`yamllint`や同様のツールを使用して、適切な構文であることを確認してください。
* *問題の切り分け*:問題を特定のコンポーネントまたは階層（ネットワーク、ストレージ、OS、Kubernetes、Metal^3^、Ironicなど...）に絞り込むようにしてください。
* *ドキュメント*:詳細については、常に公式の https://documentation.suse.com/suse-edge/[{product}ドキュメント]およびアップストリームドキュメントを参照してください。
* *バージョン*: {product}は、さまざまなSUSEコンポーネントを対象に、独自の設計思想に基づいて徹底的にテストされたバージョンです。各{product}リリースの各コンポーネントのバージョンは、 https://documentation.suse.com/suse-edge/support-matrix/html/support-matrix/index.html[{product}サポートマトリックス]で確認できます。
* *既知の問題*:各{product}リリースには、リリースノートに「既知の問題」セクションがあり、将来のリリースで修正される予定ですが、現在のリリースに影響を与える可能性のある問題に関する情報が記載されています。
