[#troubleshooting-kiwi]
== Kiwiのトラブルシューティング
:revdate: 2025-06-17
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Kiwiは、Edge Image Builderで使用する更新されたSUSE Linux Microイメージを生成するために使用されます。

.よくある問題

* *SL Microのバージョン不一致*:ビルドホストのオペレーティングシステムバージョンは、ビルド対象のオペレーティングシステムバージョンと一致している必要があります（SL Micro 6.0ホスト -> SL Micro 6.0イメージ）。
* *SELinuxがEnforcing状態*:特定の制限により、現在Kiwiでイメージをビルドするには、一時的にSELinuxを無効にする必要があります。`getenforce`でSELinuxの状態を確認し、`setenforce 0`でビルドプロセスを実行する前に無効にしてください。
* *ビルドホストが登録されていません*:ビルドプロセスでは、SUSE SCCからパッケージを取得するためにビルドホストのサブスクリプションを使用します。ホストが登録されていないと失敗します。
* *ループデバイスのテスト失敗*:Kiwiビルドプロセスを初めて実行すると、開始直後に「ERROR:」で失敗します。「Early loop device test failed, please retry the container run.」というエラーは、基盤となるホストシステム上で作成されたループデバイスが、コンテナイメージ内で即座に認識されないことに起因する現象です。Kiwiビルドプロセスを再度実行すれば、問題なく進行するはずです。
* *権限の不足*:ビルドプロセスは、ルートユーザ（またはsudo経由）として実行されることを想定しています。
* *権限が正しくありません*:ビルドプロセスでは、コンテナの実行時に `--privileged` フラグが必要です。それが存在することを再確認してください。

.ログ

* *ビルドコンテナログ*:ビルドコンテナのログを確認してください。ログは、アーティファクトの保存に使用されたディレクトリに生成されます。必要な情報については、docker logsまたはpodman logsも確認してください。
* *一時ビルドディレクトリ*:Kiwiはビルドプロセス中に一時ディレクトリを作成します。メインの出力で不十分な場合は、これらの中間ログやアーティファクトを確認してください。

.問題の対策の手順

. * `build-image` 出力の確認*:コンソール出力のエラーメッセージは、通常、非常に示唆に富んでいます。
. *ビルド環境の確認*:Kiwi自体に必要なすべての前提条件（例：docker/podman、SELinux、十分なディスク容量）が、Kiwiを実行しているマシンで満たされていることを確認してください。
. *ビルドコンテナのログを確認*:失敗したコンテナのログを確認して、より詳細なエラーがないか調べてください（上記を参照）。
. *定義ファイルの検証*:カスタムKiwiイメージ定義ファイルを使用している場合は、ファイルに誤字や構文エラーがないか再確認してください。

[NOTE]
====
https://documentation.suse.com/appliance/kiwi-9/html/kiwi/troubleshooting.html[Kiwiトラブルシューティングガイド]を確認してください。
====
