[#troubleshooting-phone-home-scenarios]
== Phone-Homeシナリオのトラブルシューティング
:revdate: 2025-06-17
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Phone-homeシナリオでは、Elementalを使用して管理クラスターに接続し、EIBを使ってelemental-registrationビットを含むOSイメージを作成します。ホストの初回起動時、EIBビルドプロセス中、または管理クラスターへの登録を試行する際に問題が発生する可能性があります。

.よくある問題

* *システムの登録に失敗*:ノードがUIに登録されません。ホストが正常に起動しており、Rancherと通信でき、時計が同期されており、Elementalサービスが正常であることを確認してください。
* *システムのプロビジョニングに失敗*:ノードは登録されていますが、プロビジョニングに失敗します。ホストがRancherと通信でき、時計が同期されており、Elementalサービスが正常であることを確認してください。


.ログ

* *システムログ*: `journalctl`
* *Elemental-system-agentログ*: `journalctl -u elemental-system-agent`
* *K3s/RKE2ログ*: `journalctl -u k3s or journalctl -u rke2-server` (または `rke2-agent`)
* *Elemental operatorポッド*: `kubectl logs -n cattle-elemental-system -l app=elemental-operator`

.問題の対策の手順

. *ログの確認*:Elemental operatorポッドのログを確認して、問題がないか調べます。ノードが起動している場合は、ホストのログを確認します。

. *MachineRegistrationとTPMの確認*:デフォルトでは、 https://elemental.docs.rancher.com/authentication/[認証]にTPMが使用されますが、TPMがないホスト向けの代替手段もあります。

