[#troubleshooting-edge-image-builder]
== Edge Image Builder (EIB) のトラブルシューティング
:revdate: 2025-06-17
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

EIBは、カスタム{product}イメージの作成に使用されます。

.よくある問題

* *SCCコードが間違っています*:EIB定義ファイルで使用されているSCCコードが、SL Microのバージョンおよびアーキテクチャと一致していることを確認してください。
* *依存関係が不足しています*:ビルド環境内に不足しているパッケージやツールがないことを確認してください。
* *イメージサイズが正しくありません*:rawイメージの場合、`diskSize`パラメーターが必要であり、これはイメージに含まれるイメージ、RPM、およびその他のアーティファクトに大きく依存します。
* *権限*:カスタム/ファイルディレクトリにスクリプトを保存する場合は、それらのファイルはcombustion時に利用可能になるだけでEIBによって変更は行われないため、実行権限があることを確認してください。
* *オペレーティングシステムのグループ依存関係*:カスタムユーザーおよびグループでイメージを作成する場合、"`primaryGroup`"として設定されるグループは明示的に作成する必要があります。
* *オペレーティングシステムのユーザーのSSHキーにはホームフォルダーが必要です*:SSHキーを持つユーザーでイメージを作成する場合、`createHomeDir=true`を使用してホームフォルダーも作成する必要があります。
* *Combustionの問題*:EIBは、OSのカスタマイズおよびその他すべての{product}コンポーネントのデプロイメントをcombustionに依存しています。これには、custom/scriptsフォルダーに配置されるカスタムスクリプトも含まれます。combustion処理は`initrd`時に実行されるため、スクリプトが実行される時点ではシステムは完全に起動していないことに注意してください。
* *Podmanマシンのサイズ*:<<tips-and-tricks,EIBのヒントとコツのセクション>>で説明されているように、Linux以外のオペレーティングシステムでEIBコンテナを実行するために、podmanマシンに十分なCPU/メモリがあることを確認してください。
* *不適切なイメージ*:使用しているベースイメージが、 https://www.suse.com/support/security/download-verification/[`checksum`を検証]することで適切にダウンロードされていることを確認してください。<<guides-kiwi-builder-images,kiwi-builder>>を使用してイメージをビルドしている場合は、プロセスによって生成されたsumファイルも確認してください。

.ログ

* *EIB出力*:`eib build`コマンドのコンソール出力は非常に重要です。
* *ビルドコンテナログ*:ビルドコンテナのログを確認してください。ログは、アーティファクトの保存に使用されたディレクトリに生成されます。必要な情報については、`docker logs`または`podman logs`も確認してください。
+
[NOTE]
====
詳細については、 https://github.com/suse-edge/edge-image-builder/blob/main/docs/debugging.md[デバッグ]を参照してください。
====

* *一時ビルドディレクトリ*:EIBは、ビルドプロセス中に一時ディレクトリを作成します。メインの出力で不十分な場合は、これらの中間ログやアーティファクトを確認してください。
* *Combustionログ*:EIBでビルドされたイメージが何らかの理由で起動しない場合は、ルートシェルが利用可能です。ホストコンソール（物理的、BMC経由など）に接続し、`journalctl -u combustion`でCombustionログを確認してください。また、エラーの根本原因を特定するために、`journalctl`を使用してオペレーティングシステムのログ全般を確認してください。


.問題の対策の手順

. *出力`eib-build`の確認*:コンソール出力のエラーメッセージは、通常、非常に重要な情報を示しています。
. *ビルド環境の確認*:EIB自体に必要なすべての前提条件（例：docker/podman、十分なディスク容量など）が、EIBを実行しているマシンで満たされていることを確認してください。
. *ビルドコンテナのログを調査する*:失敗したコンテナのログを確認し、より詳細なエラーがないか調べてください（上記を参照）。
. *の設定`eib`を検証する*: `eib`の設定ファイルに誤字がないか、またはソースファイルやビルドスクリプトへのパスが正しく指定されているかを再確認してください。
* *コンポーネントを個別にテストする*:EIBビルドにカスタムスクリプトやステージが含まれている場合は、それらを個別に実行してエラー箇所を特定してください。

[NOTE]
====
https://github.com/suse-edge/edge-image-builder/blob/main/docs/debugging.md[Edge Image Builderのデバッグ]を確認してください。
====
