[#day2-helm-upgrade]
== Helm chart upgrade
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc: auto

[NOTE]
====
The below sections focus on using `Fleet` functionalities to achieve a Helm chart update.

Users adopting a third-party GitOps workflow, should take the configurations for their desired helm chart from its `fleet.yaml` located at `fleets/day2/chart-templates/<chart-name>`. *Make sure you are retrieving the chart data from a valid "Day 2" Edge link:https://github.com/ipetrov117/fleet-examples/releases[release].*
====

=== Components

* <<components-rancher,Rancher>> - Located on the `management cluster`; responsible for the downstream cluster management.

* <<components-fleet,Fleet>> - Service offered by the `Rancher` component; responsible for muti-cluster resource deployment. It is assumed that existing charts are deployed with Fleet.

=== Preparation for air-gapped environments

==== Ensure that you have access to your Helm chart's upgrade `fleet.yaml` file

Host the needed resources on a local git server that is accessible by your `management cluster`.

==== Find the required assets for your Edge release version

. Go to our Day 2 link:https://github.com/ipetrov117/fleet-examples/releases[release] page and find the Edge 3.X.Y release that you want to upgrade your chart to and click *Assets*.

. From the release's *Assets* section, download the following files, which are required for an air-gapped upgrade of a SUSE supported helm chart:
+
[cols="1,1"]
|======
|*Release File* 
|*Description*

|_edge-save-images.sh_
|This script pulls the images in the `edge-release-images.txt` file and saves them to a '.tar.gz' archive that can then be used in your air-gapped environment.

|_edge-save-oci-artefacts.sh_
|This script pulls the SUSE OCI chart artefacts in the `edge-release-helm-oci-artefacts.txt` file and creates a '.tar.gz' archive of a directory containing all other chart OCI archives.

|_edge-load-images.sh_
|This script loads the images in the '.tar.gz' archive generated by `edge-save-images.sh`, retags them and pushes them to your private registry.

|_edge-load-oci-artefacts.sh_
|This script takes a directory containing '.tgz' SUSE OCI charts and loads all OCI charts to your private registry. The directory is retrieved from the '.tar.gz' archive that the `edge-save-oci-artefacts.sh` script has generated.

|_edge-release-helm-oci-artefacts.txt_
|This file contains a list of OCI artefacts for the SUSE Edge release Helm charts.

|_edge-release-images.txt_
|This file contains a list of images needed by the Edge release Helm charts.
|======

==== Create the SUSE Edge release images archive

_On a machine with internet access:_

. Make `edge-save-images.sh` executable:
+
[,bash]
----
chmod +x edge-save-images.sh
----

. Use `edge-save-images.sh` script to create a _Docker_ importable '.tar.gz' archive:
+
[,bash]
----
./edge-save-images.sh --source-registry registry.suse.com
----

. This will create a ready to load `edge-images.tar.gz` (unless you have specified the `-i|--images` option) archive with the needed images.

. Copy this archive to your *air-gapped* machine
+
[,bash]
----
scp edge-images.tar.gz <user>@<machine_ip>:/path
----

==== Create a SUSE Edge Helm chart OCI images archive

_On a machine with internet access:_

. Make `edge-save-oci-artefacts.sh` executable:
+
[,bash]
----
chmod +x edge-save-oci-artefacts.sh
----

. Use `edge-save-oci-artefacts.sh` script to create a '.tar.gz' archive of all SUSE Edge Helm chart OCI images:
+
[,bash]
----
./edge-save-oci-artefacts.sh --source-registry registry.suse.com
----

. This will create a `oci-artefacts.tar.gz` archive containing all SUSE Edge Helm chart OCI images

. Copy this archive to your *air-gapped* machine
+
[,bash]
----
scp oci-artefacts.tar.gz <user>@<machine_ip>:/path
----

==== Load SUSE Edge release images to your air-gapped machine

_On your air-gapped machine:_

. Log into your private registry (if required):
+
[,bash]
----
podman login <REGISTRY.YOURDOMAIN.COM:PORT>
----

. Make `edge-load-images.sh` executable:
+
[,bash]
----
chmod +x edge-load-images.sh
----

. Use `edge-load-images.sh` to load the images from the *copied* `edge-images.tar.gz` archive, retag them and push them to your private registry:
+
[,bash]
----
./edge-load-images.sh --source-registry registry.suse.com --registry <REGISTRY.YOURDOMAIN.COM:PORT> --images edge-images.tar.gz
----

==== Load SUSE Edge Helm chart OCI images to your air-gapped machine

_On your air-gapped machine:_

. Log into your private registry (if required):
+
[,bash]
----
podman login <REGISTRY.YOURDOMAIN.COM:PORT>
----

. Make `edge-load-oci-artefacts.sh` executable:
+
[,bash]
----
chmod +x edge-load-oci-artefacts.sh
----

. Untar the copied `oci-artefacts.tar.gz` archive:
+
[,bash]
----
tar -xvf oci-artefacts.tar.gz
----

. This will produce a directory with the naming template `edge-release-oci-tgz-<date>`

. Pass this directory to the `edge-load-oci-artefacts.sh` script to load the SUSE Edge helm chart OCI images to your private registry:
+
[NOTE]
====
This script assumes the `helm` CLI has been pre-installed on your environment. For Helm installation instructions, see link:https://helm.sh/docs/intro/install/[Installing Helm].
====
+
[,bash]
----
./edge-load-oci-artefacts.sh --archive-directory edge-release-oci-tgz-<date> --registry <REGISTRY.YOURDOMAIN.COM:PORT> --source-registry registry.suse.com
----

==== Create registry mirrors pointing to your private registry for your Kubernetes distribution

For RKE2, see link:https://docs.rke2.io/install/containerd_registry_configuration[Containerd Registry Configuration]

For K3s, see link:https://docs.k3s.io/installation/registry-mirror[Embedded Registry Mirror]

=== Upgrade procedure

[NOTE]
====
The below upgrade procedure utilises Rancher's <<components-fleet,Fleet>> funtionality. Users using a third-party GitOps workflow should retrieve the chart versions supported by each Edge release from the <<release_notes>> and populate these versions to their third-party GitOps workflow.
====

This section focuses on the following Helm upgrade procedure use-cases:

. _I have a new cluster and would like to deploy and manage a SUSE Helm chart_

. _I would like to upgrade a Fleet managed Helm chart_

. _I would like to upgrade a manually deployed Helm chart_

[IMPORTANT]
====
Manually deployed Helm charts cannot be reliably upgraded. We suggest to redeploy the helm chart using the <<day2-helm-upgrade-new-cluster>> method.
====

==== I have a new cluster and would like to deploy and manage a SUSE Helm chart

For users that want to manage their Helm chart lifecycle through Fleet.

===== Prepare your Fleet resources

. Acquire the Chart's Fleet resources from the Edge link:https://github.com/ipetrov117/fleet-examples/releases[release] tag that you wish to use

.. From the selected Edge release tag revision, navigate to the Helm chart fleet - `fleets/day2/chart-templates/<chart>`

.. Copy the chart Fleet directory to the Git repository that you will be using for your GitOps workflow

.. *Optionally*, if the Helm chart requires configurations to its *values*, edit the `.helm.values` configuration inside the `fleet.yaml` file of the copied directory

.. *Optionally*, there may be use-cases where you need to add additional resources to your chart's fleet so that it can better fit your environment. For information on how to enhance your Fleet directory, see link:https://fleet.rancher.io/gitrepo-content[Git Repository Contents]

An *example* for the `metal3` helm chart would look like:

* User Git repository strucutre:
+
[,bash]
----
<user_repository_root>
└── metal3
    └── fleet.yaml
----

* `fleet.yaml` content populated with user `metal3` data:
+
[,yaml]
----
defaultNamespace: metal3-system

helm:
  releaseName: metal3
  chart: "oci://registry.suse.com/edge/metal3-chart"
  version: "0.6.5"
  # custom chart value overrides
  values: 
    global:
      ironicIP: "192.168.122.76"
      enable_tls: false
      enable_vmedia_tls: false
      enable_basicAuth: false
      provisioningInterface: "eth0"
    metal3-ironic:
      persistence:
        ironic:
          storageClass: "longhorn"
    metal3-mariadb:
      persistence:
        storageClass: "longhorn"
----
+
[NOTE]
====
These are just example values that are used to illustrate custom configurations on the `metal3` chart. They should *NOT* be treated as deployment guidelines for the `metal3` chart.
====

===== Create the GitRepo

After populating your repository with the chart's Fleet resources, you must create a link:https://fleet.rancher.io/ref-gitrepo[GitRepo] resource. This resource will hold information on how to access your chart's Fleet resources and to which clusters it needs to apply those resources.

The `GitRepo` resource can be created through the Rancher UI, or by manually deploying the resource to the `management cluster`.

For information on how to create and deploy the GitRepo resource *manually*, see link:https://fleet.rancher.io/tut-deployment[Creating a Deployment].

To create a `GitRepo` resource through the *Rancher UI*, see link:https://ranchermanager.docs.rancher.com/v2.8/integrations-in-rancher/fleet/overview#accessing-fleet-in-the-rancher-ui[Accessing Fleet in the Rancher UI].

_Example *metal3* `GitRepo` resource for *manual* deployment:_

[,yaml]
----
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: metal3-git-repo
  namespace: fleet-default
spec:
  # If using a tag
  # revision: <user_repository_tag>
  # 
  # If using a branch
  # branch: <user_repository_branch>
  paths:
  # As seen in the 'Prepare your Fleet resources' example
  - metal3
  repo: <user_repository_url>
  targets:
  # Match all clusters
  - clusterSelector: {}
----

===== Managing the deployed Helm chart

Once deployed with Fleet, for Helm chart upgrades, see <<upgrade_fleet_managed_chart>>.

[#upgrade_fleet_managed_chart]
==== I would like to upgrade a Fleet managed Helm chart

. Determine the version to which you need to upgrade your chart so that it is compatible with an Edge 3.X.Y release. Helm chart version per Edge release can be viewed from the <<release_notes>>.

. In your Fleet monitored Git repository, edit the Helm chart's `fleet.yaml` file with the correct chart *version* and *repository* from the <<release_notes>>.

. After commiting and pushing the changes to your repository, this will trigger an upgrade of the desired Helm chart