== Introduction
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc: preamble

This section is meant to be a *starting point* for the `Day 2` operations documentation. You can find the following information. 

. The default <<day2-downstream-components, components>> used to achieve `Day 2` operations over multiple downstream clusters.

. Determining which `Day 2` resources should you use for your specific <<day2-determine-use-case, use-case>>. 

. The suggested workflow <<day2-upgrade-workflow,sequence>> for `Day 2` operations.


[#day2-downstream-components]
=== Components

Below you can find a description of the default components that should be setup on either your `management cluster` or your `downstream clusters` so that you can successfully perform `Day 2` operations.

==== Rancher

[NOTE]
====
For use-cases where you want to utilise <<components-fleet,Fleet>> without Rancher, you can skip the Rancher component all together.
====

Responsible for the management of your `downstream clusters`. Should be deployed on your `management cluster`.

For more information, see <<components-rancher>>.

==== Fleet

Responsible for multi-cluster resource deployment. 

Typically offered by the `Rancher` component. For use-cases where `Rancher` is not used, can be deployed as a standalone component.

For more information on installing Fleet as a standalone component, see Fleet's link:https://fleet.rancher.io/installation[Installation Details].

For more information regarding the Fleet component, see <<components-fleet>>.

[IMPORTANT]
====
This documentation heavily relies on `Fleet` and more specifically on the `GitRepo` and `Bundle` resources (more on this in <<day2-determine-use-case>>) for establishing a GitOps way of automating the deployment of resources related to `Day 2` operations. 

For use-cases, where a third party GitOps tool usage is desired, see:

. For `OS package updates` - <<os-pkg-suc-plan-deployment-third-party>>

. For `Kubernetes distribution upgrades` - <<k8s-upgrade-suc-plan-deployment-third-party>>

. For `Helm chart upgrades` - retrieve the chart version supported by the desired Edge release from the <<release-notes>> page and populate the chart version and URL in your third party GitOps tool
====

==== System-upgrade-controller (SUC)

The *system-upgrade-controller (SUC)* is responsible for executing tasks on specified nodes based on configuration data provided through a custom resource, called a `Plan`. Should be located on each `downstream cluster` that requires some sort of a `Day 2` operation.

For more information regarding *SUC*, see the upstream link:https://github.com/rancher/system-upgrade-controller[repository].

For information on how to deploy *SUC* on your downstream clusters, first <<day2-determine-use-case, determine your use-case>> and then refer to either <<day2-suc-dep-gitrepo>>, or <<day2-suc-dep-bundle>> for SUC deployment information.

[#day2-determine-use-case]
=== Determine your use-case

As mentioned previously, resources related to `Day 2` operations are propagated to downstream clusters using Fleet's `GitRepo` and `Bundle` resources. 

Below you can find more information regarding what these resources do and for which use-cases should they be used for `Day 2` operations.

==== GitRepo

A `GitRepo` is a <<components-fleet, Fleet>> resource that represents a Git repository from which `Fleet` can create `Bundles`. Each `Bundle` is created based on configuration paths defined inside of the `GitRepo` resource. For more information, see the https://fleet.rancher.io/gitrepo-add[GitRepo] documentation.

In terms of `Day 2` operations `GitRepo` resources are normally used to deploy `SUC` or `SUC Plans` on *non air-gapped* environments that utilise a _Fleet GitOps_ approach.

Alternatively, `GitRepo` resources can also be used to deploy `SUC` or `SUC Plans` on *air-gapped* environments, *if you mirror your repository setup through a local git server*.

==== Bundle

`Bundles` hold *raw* Kubernetes resources that will be deployed on the targeted cluster. Usually they are created from a `GitRepo` resource, but there are use-cases where they can be deployed manually. For more information refer to the https://fleet.rancher.io/bundle-add[Bundle] documentation.

In terms of `Day 2` operations `Bundle` resources are normally used to deploy `SUC` or `SUC Plans` on *air-gapped* environments that do not use some form of _local GitOps_ procedure (e.g. a *local git server*).

Alternatively, if your use-case does not allow for a _GitOps_ workflow (e.g. using a Git repository), *Bundle* resources could also be used to deploy `SUC` or `SUC Plans` on *non air-gapped* environments. 

[#day2-upgrade-workflow]
=== Day 2 workflow

The following is a `Day 2` workflow that should be followed when upgrading a downstream cluster to a specific Edge release.

. <<day2-os-package-update, OS package update>>
. <<day2-k8s-upgrade, Kubernetes version upgrade>>
. <<day2-helm-upgrade, Helm chart upgrade>>
