[#{cluster-type}-day2-fleet]
== Fleet
:revdate: 2025-01-14
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

This section offers information on how to perform "Day 2" operations using the <<components-fleet, Fleet>> component.

The following topics are covered as part of this section:

. <<{cluster-type}-day2-fleet-components>> - default components used for all "Day 2" operations.
. <<{cluster-type}-day2-fleet-determine-use-case>> - provides an overview of the Fleet custom resources that will be used and their suitability for different "Day 2" operations use-cases.
. <<{cluster-type}-day2-upgrade-workflow>> - provides a workflow guide for executing "Day 2" operations with Fleet.
. <<{cluster-type}-day2-fleet-os-upgrade>> - describes how to do OS upgrades using Fleet.
. <<{cluster-type}-day2-fleet-k8s-upgrade>> - describes how to do Kubernetes version upgrades using Fleet.
. <<{cluster-type}-day2-fleet-helm-upgrade>> - describes how to do Helm chart upgrades using Fleet.

[#{cluster-type}-day2-fleet-components]
=== Components

Below you can find a description of the default components that should be set up on your `{cluster-type}` cluster so that you can successfully perform "Day 2" operations using Fleet.

ifeval::["{cluster-type}" == "management"]
==== Rancher

*Optional*; Responsible for managing `downstream clusters` and deploying the `System Upgrade Controller` on your `management cluster`.

For more information, see <<components-rancher>>.
endif::[]

==== System Upgrade Controller (SUC)

ifeval::["{cluster-type}" == "downstream"]
[NOTE]
====
*Must* be deployed on each downstream cluster.
====
endif::[]

*System Upgrade Controller* is responsible for executing tasks on specified nodes based on configuration data provided through a custom resource, called a `Plan`.  

*SUC* is actively utilized to upgrade the operating system and Kubernetes distribution.

For more information about the *SUC* component and how it fits in the Edge stack, see <<components-system-upgrade-controller>>.

ifeval::["{cluster-type}" == "downstream"]
For information on how to deploy *SUC*, first <<{cluster-type}-day2-fleet-determine-use-case, determine your use-case>> and then refer to <<components-system-upgrade-controller-fleet-gitrepo, System Upgrade Controller installation - GitRepo>>, or <<components-system-upgrade-controller-fleet-bundle, System Upgrade Controller installation - Bundle>>.
endif::[]

[#{cluster-type}-day2-fleet-determine-use-case]
=== Determine your use-case

Fleet uses two types of link:https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[custom resources] to enable the management of Kubernetes and Helm resources.

Below you can find information about the purpose of these resources and the use-cases they are best suited for in the context of "Day 2" operations.

==== GitRepo

A `GitRepo` is a <<components-fleet, Fleet>> resource that represents a Git repository from which `Fleet` can create `Bundles`. Each `Bundle` is created based on configuration paths defined inside of the `GitRepo` resource. For more information, see the https://fleet.rancher.io/gitrepo-add[GitRepo] documentation.

In the context of "Day 2" operations, `GitRepo` resources are normally used to deploy `SUC` or `SUC Plans` in *non air-gapped* environments that utilize a _Fleet GitOps_ approach.

Alternatively, `GitRepo` resources can also be used to deploy `SUC` or `SUC Plans` on *air-gapped* environments, *provided you mirror your repository setup through a local git server*.

==== Bundle

`Bundles` hold *raw* Kubernetes resources that will be deployed on the targeted cluster. Usually they are created from a `GitRepo` resource, but there are use-cases where they can be deployed manually. For more information refer to the https://fleet.rancher.io/bundle-add[Bundle] documentation.

In the context of "Day 2" operations, `Bundle` resources are normally used to deploy `SUC` or `SUC Plans` in *air-gapped* environments that do not use some form of _local GitOps_ procedure (e.g. a *local git server*).

Alternatively, if your use-case does not allow for a _GitOps_ workflow (e.g. using a Git repository), `Bundle` resources could also be used to deploy `SUC` or `SUC Plans` in *non air-gapped* environments.

[#{cluster-type}-day2-upgrade-workflow]
=== Day 2 workflow

The following is a "Day 2" workflow that should be followed when upgrading a {cluster-type} cluster to a specific Edge release.

. <<{cluster-type}-day2-fleet-os-upgrade, OS upgrade>>

. <<{cluster-type}-day2-fleet-k8s-upgrade, Kubernetes version upgrade>>

. <<{cluster-type}-day2-fleet-helm-upgrade, Helm chart upgrade>>

:leveloffset: +1

include::fleet-os-upgrade.adoc[]

include::fleet-k8s-upgrade.adoc[]

include::fleet-helm-upgrade.adoc[]

:leveloffset: -1
