[#mgmt_lifecycle]
== Lifecycle Actions
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

This section covers the lifecycle management actions of the deployed `Rancher Management Cluster`.

=== RKE2 upgrade

[NOTE]
====
To ensure *disaster recovery*, we advise to do a backup of the RKE2 cluster data. For information on how to do this, check link:https://docs.rke2.io/backup_restore[here]. The default location for the `rke2` binary is `/opt/rke2/bin`.
====

You can upgrade the RKE2 version using the RKE2 installation script as follows:

[source,bash]
----
curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=vX.Y.Z+rke2rN sh -
----

Remember to restart the `rke2` process after installing:

[source,bash]
----
# For server nodes:
systemctl restart rke2-server

# For agent nodes:
systemctl restart rke2-agent
----

[IMPORTANT]
====
To avoid any unforseen upgrade problems, use the following node upgrade order:

. _Server nodes_ - should be upgraded *one* node at a time.
. _Agent nodes_  - should be upgraded after *all* server node upgrades have finished. Can be upgraded in parallel.
====

_For further information, see the link:https://docs.rke2.io/upgrade/manual_upgrade#upgrade-rke2-using-the-installation-script[RKE2 upgrade documentation]._

=== OS upgrade

NOTE: This section assumes that you have registered your system to https://scc.suse.com.

SUSE regularly releases new `SLE Micro` package updates. To retrieve the updated package versions SLE Micro uses `transactional-upgrade`.

`transactional-upgrade` provides an application and library to update a Linux operating system in a transactional way, i.e. the update will be performed in the background while the system continues running as it is. Only after you *reboot* the system will the update take effect. For further information, see the `transactional-update` https://github.com/openSUSE/transactional-update[GitHub] GitHub page.

.To update all packages in the system, execute:
[source,bash]
----
transactional-update
----

Since *rebooting* the node will result in it being unavailable for some time, if you are running a multi-node cluster, you can https://kubernetes.io/docs/reference/kubectl/generated/kubectl_cordon/[cordon] and https://kubernetes.io/docs/reference/kubectl/generated/kubectl_drain/[drain] the node before the *reboot*.

.To cordon a node, execute:
[source,bash]
----
kubectl cordon <node>
----

This will result in the node being taken out of the default scheduling mechanism, ensuring that no pods will be assinged to it by mistake.

.To drain a node, execute:
[source, bash]
----
kubectl drain <node>
----

This will ensure that all workloads on the node will be transferred to other available nodes.

[NOTE]
====
Depending on what workloads you are running on the node, you might also need to provide additional flags (e.g. `--delete-emptydir-data`, `--ignore-daemonsets`) to the command.
====

.Reboot node:
[source,bash]
----
sudo reboot
----

After a successful reboot, the packages on your node will be updated. The only thing left is to bring the node back to the default scheduling mechanism with the https://kubernetes.io/docs/reference/kubectl/generated/kubectl_uncordon/[uncordon] command.

.Uncordon node:
[source,bash]
----
kubectl uncordon <node>
----

[NOTE]
====
In case you want to revert the update, use the above steps with the following `transactional-update` command:

[source,bash]
----
transactional-update rollback last
----
====

=== Rancher upgrade

[NOTE]
====
To ensure disaster recovery, we advise to do a Rancher backup. For information on how to do this, check link:https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/back-up-rancher[here].
====

[NOTE]
====
This section assumes you have installed `helm` on your system. For `helm` installation instructions, check link:https://helm.sh/docs/intro/install[here].
====

.Update your local helm cache:
[source,bash]
----
helm repo update
----

.Get `Rancher Prime` helm repo:
[source,bash]
----
helm repo add rancher-prime https://charts.rancher.com/server-charts/prime
----

.Fetch the latest `Rancher Prime` helm chart version:
[source,bash]
----
helm fetch rancher-prime/rancher

# Alternatively if you want to fetch a specific verison
helm fetch rancher-prime/rancher --version=X.Y.Z
----

This should produce a `rancher-<version>.tgz` file in your current working directory.

.Get the values for the current Rancher release and print them to a `rancher-values.yaml` file
[source,bash]
----
helm get values rancher -n cattle-system -o yaml > rancher-values.yaml
----

.Update the helm chart
[source,bash]
----
helm upgrade rancher rancher-prime/rancher \
  --namespace cattle-system \
  -f rancher-values.yaml \
  --version=2.X.Y
----

_For additional information on the Rancher helm chart upgrade, check link:https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/upgrades[here]._