[#day2-mgmt-cluster]
= Management Cluster
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc: preamble

This section covers how to do various `Day 2` operations on a `management cluster`.

== RKE2 upgrade

[NOTE]
====
To ensure *disaster recovery*, we advise to do a backup of the RKE2 cluster data. For information on how to do this, check link:https://docs.rke2.io/backup_restore[here]. The default location for the `rke2` binary is `/opt/rke2/bin`.
====

You can upgrade the RKE2 version using the RKE2 installation script as follows:

[source,bash]
----
curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=vX.Y.Z+rke2rN sh -
----

Remember to restart the `rke2` process after installing:

[source,bash]
----
# For server nodes:
systemctl restart rke2-server

# For agent nodes:
systemctl restart rke2-agent
----

[IMPORTANT]
====
To avoid any unforseen upgrade problems, use the following node upgrade order:

. _Server nodes_ - should be upgraded *one* node at a time.
. _Agent nodes_  - should be upgraded after *all* server node upgrades have finished. Can be upgraded in parallel.
====

_For further information, see the link:https://docs.rke2.io/upgrade/manual_upgrade#upgrade-rke2-using-the-installation-script[RKE2 upgrade documentation]._

== OS upgrade

NOTE: This section assumes that you have registered your system to https://scc.suse.com.

SUSE regularly releases new `SLE Micro` package updates. To retrieve the updated package versions SLE Micro uses `transactional-upgrade`.

`transactional-upgrade` provides an application and library to update a Linux operating system in a transactional way, i.e. the update will be performed in the background while the system continues running as it is. Only after you *reboot* the system will the update take effect. For further information, see the `transactional-update` https://github.com/openSUSE/transactional-update[GitHub] GitHub page.

.To update all packages in the system, execute:
[source,bash]
----
transactional-update
----

Since *rebooting* the node will result in it being unavailable for some time, if you are running a multi-node cluster, you can https://kubernetes.io/docs/reference/kubectl/generated/kubectl_cordon/[cordon] and https://kubernetes.io/docs/reference/kubectl/generated/kubectl_drain/[drain] the node before the *reboot*.

.To cordon a node, execute:
[source,bash]
----
kubectl cordon <node>
----

This will result in the node being taken out of the default scheduling mechanism, ensuring that no pods will be assigned to it by mistake.

.To drain a node, execute:
[source, bash]
----
kubectl drain <node>
----

This will ensure that all workloads on the node will be transferred to other available nodes.

[NOTE]
====
Depending on what workloads you are running on the node, you might also need to provide additional flags (e.g. `--delete-emptydir-data`, `--ignore-daemonsets`) to the command.
====

.Reboot node:
[source,bash]
----
sudo reboot
----

After a successful reboot, the packages on your node will be updated. The only thing left is to bring the node back to the default scheduling mechanism with the https://kubernetes.io/docs/reference/kubectl/generated/kubectl_uncordon/[uncordon] command.

.Uncordon node:
[source,bash]
----
kubectl uncordon <node>
----

[NOTE]
====
In case you want to revert the update, use the above steps with the following `transactional-update` command:

[source,bash]
----
transactional-update rollback last
----
====

== Helm upgrade

[NOTE]
====
This section assumes you have installed `helm` on your system. For `helm` installation instructions, check link:https://helm.sh/docs/intro/install[here].
====

This section covers how to upgrade both an <<day2-mgmt-cluster-eib-helm-chart-upgrade,EIB>> and <<day2-mgmt-cluster-helm-chart-upgrade,non-EIB>> deployed helm chart.

[#day2-mgmt-cluster-eib-helm-chart-upgrade]
=== EIB deployed helm chart

EIB deploys helm charts defined in it's <<quickstart-eib-definition-file, image definition file>> by using RKE2's manifest https://docs.rke2.io/advanced#auto-deploying-manifests[auto-deploy] functionality. 

In order to upgrade a chart that is deployed in such a manner, you need to upgrade the chart manifest file that EIB will create under the `/var/lib/rancher/rke2/server/manifests` directory on your `initializer` node.

[NOTE]
====
To ensure disaster recovery, we advise that you always backup your chart manifest file as well as follow any documentation related to disaster recovery that your chart offers.
====

To upgrade the chart manifest file, follow these steps:

. Locate the `initializer` node

** For `multi-node clusters` - in your EIB image definition file, you should have specified the `initializer: true` property for one of your nodes. If you have not specified this property, the initializer node will be the first *server* node in your node list.

** For `single-node clusters` - the initializer is the currently running node.

. SSH to the `initializer` node:
+
[source,bash]
----
ssh root@<node_ip>
----

. link:https://helm.sh/docs/helm/helm_pull/[Pull] the helm chart: 

** For helm charts hosted in a helm chart repository:
+
[source,bash]
----
helm repo add <chart_repo_name> <chart_repo_urls>
helm pull <chart_repo_name>/<chart_name>

# Alternatively if you want to pull a specific verison
helm pull <chart_repo_name>/<chart_name> --version=X.Y.Z
----

** For OCI-based helm charts:
+
[source,bash]
----
helm pull oci://<chart_oci_url>

# Alternatively if you want to pull a specific verison
helm pull oci://<chart_oci_url> --version=X.Y.Z
----

. Encode the pulled `.tgz` archive so that it can be passed to a `HelmChart` CR config:
+
[source,bash]
----
base64 -w 0 <chart_name>-X.Y.Z.tgz  > <chart_name>-X.Y.Z.txt
----

. Make a copy of the chart manifest file that we will edit:
+
[source, bash]
----
cp /var/lib/rancher/rke2/server/manifests/<chart_name>.yaml ./<chart_name>.yaml
----

. Change the `chartContent` and `version` configurations of the `bar.yaml` file:
+
[source,bash]
----
sed -i -e "s|chartContent:.*|chartContent: $(<chart-name-X.Y.Z.txt)|" -e "s|version:.*|version: X.Y.Z|" <chart_name>.yaml
----
+
[NOTE]
====
If you need to do any additional upgrade changes to the chart (e.g. adding *new* custom chart values), you need to manually edit the chart manifest file.
====

. Replace the original chart manifest file:
+
[source,bash]
----
cp <chart_name>.yaml /var/lib/rancher/rke2/server/manifests/
----

The above commands will trigger an upgrade of the helm chart. The upgrade will be handled by the https://github.com/k3s-io/helm-controller#helm-controller[helm-controller].

To track the helm chart upgrade you need to view the logs of the pod that the `helm-controller` creates for the chart upgrade. Refer to the <<day2-mgmt-cluster-eib-helm-chart-upgrade-examples, Examples>> section for more information.

[#day2-mgmt-cluster-eib-helm-chart-upgrade-examples]
==== Examples

[NOTE]
====
The examples in this section assume that you have already located and connected to your `initializer` node.
====

This section offer examples on how to upgrade a:

* <<day2-mgmt-cluster-eib-helm-chart-upgrade-examples-rancher, Rancher>> helm chart

* <<day2-mgmt-cluster-eib-helm-chart-upgrade-examples-metal3, Metal^3^>> helm chart

[#day2-mgmt-cluster-eib-helm-chart-upgrade-examples-rancher]
===== Rancher upgrade

[NOTE]
====
To ensure disaster recovery, we advise to do a Rancher backup. For information on how to do this, check link:https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/back-up-rancher[here].
====

This example shows how to upgrade Rancher to the `2.8.5` version.

. Add the `Rancher Prime` Helm repository:
+
[source,bash]
----
helm repo add rancher-prime https://charts.rancher.com/server-charts/prime
----

. Pull the latest `Rancher Prime` helm chart version:
+
[source,bash]
----
helm pull rancher-prime/rancher --version=2.8.5
----

. Encode `.tgz` archive so that it can be passed to a `HelmChart` CR config:
+
[source,bash]
----
base64 -w 0 rancher-2.8.5.tgz  > rancher-2.8.5-encoded.txt
----

. Make a copy of the `rancher.yaml` file that we will edit:
+
[source, bash]
----
cp /var/lib/rancher/rke2/server/manifests/rancher.yaml ./rancher.yaml
----

. Change the `chartContent` and `version` configurations of the `rancher.yaml` file:
+
[source,bash]
----
sed -i -e "s|chartContent:.*|chartContent: $(<rancher-2.8.5-encoded.txt)|" -e "s|version:.*|version: 2.8.5|" rancher.yaml
----
+
[NOTE]
====
If you need to do any additional upgrade changes to the chart (e.g. adding *new* custom chart values), you need to manually edit the `rancher.yaml` file.
====

. Replace the original `rancher.yaml` file:
+
[source,bash]
----
cp rancher.yaml /var/lib/rancher/rke2/server/manifests/
----

To verify the update:

. List pods in `default` namespace: 
+
[source,bash]
----
kubectl get pods -n default

# Example output
NAME                              READY   STATUS      RESTARTS   AGE
helm-install-cert-manager-7v7nm   0/1     Completed   0          88m
helm-install-rancher-p99k5        0/1     Completed   0          3m21s
----

. Look at the logs of the `helm-install-rancher-*` pod:
+
[source,bash]
----
kubectl logs <helm_install_rancher_pod> -n default

# Example
kubectl logs helm-install-rancher-p99k5 -n default
----

. Verify `Rancher` pods are running:
+
[source,bash]
----
kubectl get pods -n cattle-system

# Example output
NAME                               READY   STATUS      RESTARTS   AGE
helm-operation-mccvd               0/2     Completed   0          3m52s
helm-operation-np8kn               0/2     Completed   0          106s
helm-operation-q8lf7               0/2     Completed   0          2m53s
rancher-648d4fbc6c-qxfpj           1/1     Running     0          5m27s
rancher-648d4fbc6c-trdnf           1/1     Running     0          9m57s
rancher-648d4fbc6c-wvhbf           1/1     Running     0          9m57s
rancher-webhook-649dcc48b4-zqjs7   1/1     Running     0          100s
----

. Verify `Rancher` version upgrade:
+
[source,bash]
----
kubectl get settings.management.cattle.io server-version

# Example output
NAME             VALUE
server-version   v2.8.5
----

[#day2-mgmt-cluster-eib-helm-chart-upgrade-examples-metal3]
===== Metal^3^ upgrade

This example shows how to upgrade Metal^3^ to the `0.7.3` version.

. Pull the latest `Metal^3^` helm chart version:
+
[source,bash]
----
helm pull oci://registry.suse.com/edge/metal3-chart --version 0.7.3
----

. Encode `.tgz` archive so that it can be passed to a `HelmChart` CR config:
+
[source,bash]
----
base64 -w 0 metal3-chart-0.7.3.tgz  > metal3-chart-0.7.3-encoded.txt
----

. Make a copy of the `Metal^3^` manifest file that we will edit:
+
[source, bash]
----
cp /var/lib/rancher/rke2/server/manifests/metal3.yaml ./metal3.yaml
----

. Change the `chartContent` and `version` configurations of the `Metal^3^` manifest file:
+
[source,bash]
----
sed -i -e "s|chartContent:.*|chartContent: $(<metal3-chart-0.7.3-encoded.txt)|" -e "s|version:.*|version: 0.7.3|" metal3.yaml
----
+
[NOTE]
====
If you need to do any additional upgrade changes to the chart (e.g. adding *new* custom chart values), you need to manually edit the `metal3.yaml` file.
====

. Replace the original `Metal^3^` manifest file:
+
[source,bash]
----
cp metal3.yaml /var/lib/rancher/rke2/server/manifests/
----

To verify the update:

. List pods in `default` namespace: 
+
[source,bash]
----
kubectl get pods -n default

# Example output
NAME                              READY   STATUS      RESTARTS   AGE
helm-install-metal3-7p7bl         0/1     Completed   0          27s
----

. Look at the logs of the `helm-install-rancher-*` pod:
+
[source,bash]
----
kubectl logs <helm_install_rancher_pod> -n default

# Example
kubectl logs helm-install-metal3-7p7bl -n default
----

. Verify `Metal^3^` pods are running:
+
[source,bash]
----
kubectl get pods -n metal3-system

# Example output
NAME                                                     READY   STATUS    RESTARTS      AGE
baremetal-operator-controller-manager-785f99c884-9z87p   2/2     Running   2 (25m ago)   36m
metal3-metal3-ironic-96fb66cdd-lkss2                     4/4     Running   0             3m54s
metal3-metal3-mariadb-55fd44b648-q6zhk                   1/1     Running   0             36m
----

. Verify the `HelmChart` resource version is upgraded:
+
[source,bash]
----
kubectl get helmchart metal3 -n default

# Example output
NAME     JOB                   CHART   TARGETNAMESPACE   VERSION   REPO   HELMVERSION   BOOTSTRAP
metal3   helm-install-metal3           metal3-system     0.7.3
----

[#day2-mgmt-cluster-helm-chart-upgrade]
=== Non-EIB deployed helm chart

. Get the values for the currently running helm chart `.yaml` file and make any changes to them *if necessary*:
+
[source,bash]
----
helm get values <chart_name> -n <chart_namespace> -o yaml > <chart_name>-values.yaml
----

. Update the helm chart:
+
[source,bash]
----
# For charts using a chart repository
helm upgrade <chart_name> <chart_repo_name>/<chart_name> \
  --namespace <chart_namespace> \
  -f <chart_name>-values.yaml \
  --version=X.Y.Z

# For OCI based charts
helm upgrade <chart_name> oci://<oci_registry_url>/<chart_name> \
  --namespace <chart_namespace> \
  -f <chart_name>-values.yaml \
  --version=X.Y.Z
----

. Verify the chart upgrade. Depending on the chart you may need to verify different resources. For examples of chart upgrades, see the <<day2-mgmt-cluster-helm-chart-upgrade-examples, Examples>> section.

[#day2-mgmt-cluster-helm-chart-upgrade-examples]
==== Examples

This section offer examples on how to upgrade a:

* <<day2-mgmt-cluster-helm-chart-upgrade-examples-rancher, Rancher>> helm chart

* <<day2-mgmt-cluster-helm-chart-upgrade-examples-metal3, Metal^3^>> helm chart

[#day2-mgmt-cluster-helm-chart-upgrade-examples-rancher]
===== Rancher

[NOTE]
====
To ensure disaster recovery, we advise to do a Rancher backup. For information on how to do this, check link:https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/back-up-rancher[here].
====

This example shows how to upgrade Rancher to the `2.8.5` version.

. Get the values for the current Rancher release and print them to a `rancher-values.yaml` file:
+
[source,bash]
----
helm get values rancher -n cattle-system -o yaml > rancher-values.yaml
----

. Update the helm chart:
+
[source,bash]
----
helm upgrade rancher rancher-prime/rancher \
  --namespace cattle-system \
  -f rancher-values.yaml \
  --version=2.8.5
----

. Verify `Rancher` version upgrade:
+
[source,bash]
----
kubectl get settings.management.cattle.io server-version

# Example output
NAME             VALUE
server-version   v2.8.5
----

_For additional information on the Rancher helm chart upgrade, check link:https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/upgrades[here]._


[#day2-mgmt-cluster-helm-chart-upgrade-examples-metal3]
===== Metal^3^

This example shows how to upgrade Metal^3^ to the `0.7.3` version.

. Get the values for the current Rancher release and print them to a `rancher-values.yaml` file:
+
[source,bash]
----
helm get values metal3 -n metal3-system -o yaml > metal3-values.yaml
----

. Update the helm chart:
+
[source,bash]
----
helm upgrade metal3 oci://registry.suse.com/edge/metal3-chart \
  --namespace metal3-system \
  -f metal3-values.yaml \
  --version=0.7.3
----

. Verify `Metal^3^` pods are running:
+
[source,bash]
----
kubectl get pods -n metal3-system

# Example output
NAME                                                     READY   STATUS    RESTARTS   AGE
baremetal-operator-controller-manager-785f99c884-fvsx4   2/2     Running   0          12m
metal3-metal3-ironic-96fb66cdd-j9mgf                     4/4     Running   0          2m41s
metal3-metal3-mariadb-55fd44b648-7fmvk                   1/1     Running   0          12m
----

. Verify `Metal^3^` helm release version change:
+
[source,bash]
----
helm ls -n metal3-system

# Expected output
NAME    NAMESPACE      REVISION  UPDATED                                  STATUS    CHART         APP VERSION
metal3  metal3-system  2         2024-06-17 12:43:06.774802846 +0000 UTC  deployed  metal3-0.7.3  1.16.0
----

== Cluster API upgrade

The Cluster API (CAPI) controllers on a Metal^3^ management cluster are not currently managed via Helm, this section describes the upgrade process.

[NOTE]
====
This section assumes you have installed `clusterctl` and configured on your system as described in the <<quickstart-metal3, Metal^3^ quickstart>>
====

When upgrading to Edge 3.0.2 from any previous version it will be necessary to upgrade the RKE2 providers:

[,bash]
----
clusterctl upgrade apply --bootstrap "rke2:v0.4.1" --control-plane "rke2:v0.4.1"
----

WARNING: Please ensure the versions selected align with those described in the <<id-release-notes, Release Notes>>, usage of other upstream releases is not supported.
