[#day2-mgmt-cluster]
= Management Cluster
:revdate: 2025-01-14
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc: preamble

This section covers how to perform the various `Day 2` operations related to upgrading your `management` cluster from one Edge platform version to another.

The `Day 2` operations are automated by the <<components-upgrade-controller, Upgrade Controller>> and include:

* <<components-slmicro, SL Micro>> OS upgrade

* <<components-rke2, RKE2>>/<<components-k3s, K3s>> upgrade

* SUSE additional components (Rancher, Neuvector, etc.) upgrade

== Prerequisites

Before upgrading your `management` cluster, the following prerequisites must be met:

. `SCC registered nodes` - ensure your cluster nodes' OS are registered with a subscription key that supports the OS version specified in the Edge <<release-notes,release>> you intend to upgrade to.

. `Upgrade Controller` - make sure that the `Upgrade Controller` has been deployed on your `management` cluster. For installation steps, refer to <<components-upgrade-controller-installation, Installing the Upgrade Controller>>.

== Upgrade

. Determine the Edge <<release-notes,release>> version that you wish to upgrade your `management` cluster to.

. In the `management` cluster, deploy an `UpgradePlan` that specifies the desired `release version`. The `UpgradePlan` must be deployed in the namespace of the `Upgrade Controller`.
+
[,bash]
----
kubectl apply -n <upgrade_controller_namespace> -f - <<EOF
apiVersion: lifecycle.suse.com/v1alpha1
kind: UpgradePlan
metadata:
  name: upgrade-plan-mgmt-3-1-X
spec:
  # Version retrieved from release notes
  releaseVersion: 3.1.X
EOF
----
+
[NOTE]
====
There may be use-cases where you would want to make additional configurations over the `UpgradePlan`. For all possible configurations, refer to the <<components-upgrade-controller-extensions-upgrade-plan, UpgradePlan>> section.
====

. Deploying the `UpgradePlan` to the `Upgrade Controller's` namespace will begin the `upgrade process`.
+
[NOTE]
====
For more information on the actual `upgrade process`, refer to <<components-upgrade-controller-how, How does the Upgrade Controller work?>>.

For information on how to track the `upgrade process`, refer to <<components-upgrade-controller-how-track, Tracking the upgrade process>>.
====
