[#mgmt_lifecycle]
== Lifecycle Actions
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

This section covers the lifecycle management actions of the deployed `Rancher Management Cluster`.

=== RKE2 upgrade

[NOTE]
====
To ensure *disaster recovery*, we advise to do a backup of the RKE2 cluster data. For information on how to do this, check link:https://docs.rke2.io/backup_restore[here]. The default location for the `rke2` binary is `/opt/rke2/bin`.
====

As stated in the link:https://docs.rke2.io/upgrade/manual_upgrade#upgrade-rke2-using-the-installation-script[RKE2 documentation], you can upgrade the RKE2 version using the RKE2 installation script as follows:

[source,bash]
----
curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=vX.Y.Z+rke2rN sh -
----

Remember to restart the `rke2` process after installing:

[source,bash]
----
systemctl restart rke2-server
----

=== OS upgrade

NOTE: This section assumes that you have registered your system to https://scc.suse.com.

SUSE regularly releases new `SLE Micro` package updates. To retrieve the updated package versions SLE Micro uses transactional upgrade.

.Package update command:
[source,bash]
----
transactional-update
----

In case you want to revert the update, you can use:

[source,bash]
----
transactional-update rollback last
----

=== Rancher upgrade

[NOTE]
====
To ensure disaster recovery, we advise to do a Rancher backup. For information on how to do this, check link:https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/back-up-rancher[here].
====

[NOTE]
====
This section assumes you have installed `helm` on your system. For `helm` installation instructions, check link:https://helm.sh/docs/intro/install[here].
====

.Update your local helm cache:
[source,bash]
----
helm repo update
----

.Get `Rancher Prime` helm repo:
[source,bash]
----
helm repo add rancher-prime https://charts.rancher.com/server-charts/prime
----

.Fetch the latest `Rancher Prime` helm chart version:
[source,bash]
----
helm fetch rancher-prime/rancher

# Alternatively if you want to fetch a specific verison
helm fetch rancher-prime/rancher --version=X.Y.Z
----

This should produce a `rancher-<version>.tgz` file in your current working directory.

.Get the values for the current Rancher release and print them to a `rancher-values.yaml` file
[source,bash]
----
helm get values rancher -n cattle-system -o yaml > rancher-values.yaml
----

.Update the helm chart
[source,bash]
----
helm upgrade rancher rancher-prime/rancher \
  --namespace cattle-system \
  -f rancher-values.yaml \
  --version=2.X.Y
----

_For additional information on the Rancher helm chart upgrade, check link:https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/upgrades[here]._