[#{cluster-type}-day2-upgrade-controller]
== Upgrade Controller
:revdate: 2025-01-16
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[IMPORTANT]
====
The `Upgrade Controller` currently only supports `Day 2` operations for *non air-gapped management* clusters.
====

This section covers how to perform the various `Day 2` operations related to upgrading your `management` cluster from one Edge platform version to another.

The `Day 2` operations are automated by the <<components-upgrade-controller, Upgrade Controller>> and include:

* <<components-slmicro, SUSE Linux Micro>> OS upgrade

* <<components-rke2>> or <<components-k3s>> Kubernetes upgrade

* SUSE additional components (SUSE Rancher Prime, SUSE Security, etc.) upgrade

=== Prerequisites

Before upgrading your `management` cluster, the following prerequisites must be met:

. `SCC registered nodes` - ensure your cluster nodes' OS are registered with a subscription key that supports the OS version specified in the Edge <<release-notes,release>> you intend to upgrade to.

. `Upgrade Controller` - make sure that the `Upgrade Controller` has been deployed on your `management` cluster. For installation steps, refer to <<components-upgrade-controller-installation>>.

=== Upgrade

. Determine the Edge <<release-notes,release>> version that you wish to upgrade your `management` cluster to.

. In the `management` cluster, deploy an `UpgradePlan` that specifies the desired `release version`. The `UpgradePlan` must be deployed in the namespace of the `Upgrade Controller`.
+
[,bash]
----
kubectl apply -n <upgrade_controller_namespace> -f - <<EOF
apiVersion: lifecycle.suse.com/v1alpha1
kind: UpgradePlan
metadata:
  name: upgrade-plan-mgmt
spec:
  # Version retrieved from release notes
  releaseVersion: 3.X.Y
EOF
----
+
[NOTE]
====
There may be use-cases where you would want to make additional configurations over the `UpgradePlan`. For all possible configurations, refer to <<components-upgrade-controller-extensions-upgrade-plan>>.
====

. Deploying the `UpgradePlan` to the `Upgrade Controller's` namespace will begin the `upgrade process`.
+
[NOTE]
====
For more information on the actual `upgrade process`, refer to <<components-upgrade-controller-how>>.

For information on how to track the `upgrade process`, refer to <<components-upgrade-controller-how-track>>.
====
