[#components-eib]
= Edge Image Builder
:revdate: 2025-08-07
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:


ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Consulte o https://github.com/suse-edge/edge-image-builder[Repositório Oficial].
 

O Edge Image Builder (EIB) é uma ferramenta que simplifica a geração de imagens de disco personalizadas e prontas para inicialização (CRB) para máquinas de bootstrapping. Essas imagens permitem a implantação de ponta a ponta de toda a pilha de software SUSE com uma única imagem.

Embora o EIB possa criar imagens CRB para todos os cenários de provisionamento, o EIB demonstra um valor tremendo em implantações air-gapped com redes limitadas ou completamente isoladas.


== Como o {product} usa o Edge Image Builder?

{product} usa o EIB para a configuração simplificada e rápida de imagens personalizadas do SUSE Linux Micro para uma variedade de cenários. Esses cenários incluem o bootstrapping de máquinas virtuais e bare metal:

* Implantações totalmente air-gapped de K3s/RKE2 Kubernetes (nó único e multi-nó)
* Implantações totalmente air-gapped de Helm charts e manifestos do Kubernetes
* Registro no Rancher via API Elemental
* Metal^3^
* Rede personalizada (por exemplo, IP estático, nome de host, VLANs, bonding, etc.)
* Configurações personalizadas do sistema operacional (por exemplo, usuários, grupos, senhas, chaves SSH, proxies, NTP, certificados SSL personalizados, etc.)
* Instalação air-gapped de pacotes RPM em nível de host e carregados lateralmente (incluindo resolução de dependências)
* Registro no SUSE Multi-Linux Manager para gerenciamento do sistema operacional
* Imagens de contêiner incorporadas
* Argumentos da linha de comando do kernel
* Unidades do systemd a serem habilitadas/desabilitadas no momento da inicialização
* Scripts e arquivos personalizados para quaisquer tarefas manuais

== Operações iniciais

Documentação abrangente para o uso e teste do Edge Image Builder pode ser encontrada {link-eib-docs}[aqui].

Adicionalmente, veja <<quickstart-eib>> cobrindo um cenário básico de implantação.

Assim que estiver familiarizado com esta ferramenta, encontre mais informações úteis em nossa página <<tips-and-tricks,seção de Dicas e Truques do EIB>>.

== Problemas conhecidos

* O EIB aplica air-gap aos Helm charts por meio da criação de templates para os Helm charts e da análise de todas as imagens presentes no template. Se um Helm chart não mantiver todas as suas imagens dentro do template e, em vez disso, carregá-las lateralmente, o EIB não será capaz de air-gap essas imagens automaticamente. A solução para isso é adicionar manualmente quaisquer imagens não detectadas à seção `embeddedArtifactRegistry` do arquivo de definição.
