[#components-elemental]
= Elemental
:revdate: 2025-01-16
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

O Elemental é uma pilha de software que permite o gerenciamento centralizado e completo de sistemas operacionais nativos de nuvem com o Kubernetes. A pilha Elemental consiste em vários componentes que residem no próprio Rancher ou nos nós de borda. Os componentes principais são:

* *elemental-operator* - O operador principal que reside no Rancher e lida com solicitações de registro de clientes.
* *elemental-register* - O cliente que é executado nos nós de borda permitindo o registro via `elemental-operator`.
* *elemental-system-agent* - Um agente que reside nos nós de borda; sua configuração é alimentada pelo `elemental-register` e ele recebe um `plan` para configurar o `rancher-system-agent`
* *rancher-system-agent* - Uma vez que o nó de borda tenha sido totalmente registrado, este assume o lugar do `elemental-system-agent` e aguarda por mais `plans` do Rancher Manager (por exemplo, para a instalação do Kubernetes).

Consulte a https://elemental.docs.rancher.com/[documentação upstream do Elemental] para obter informações completas sobre o Elemental e seu relacionamento com o Rancher.

== Como o {product} usa o Elemental?

Usamos partes do Elemental para gerenciar dispositivos remotos onde o Metal^3^ não é uma opção (por exemplo, não há BMC, ou o dispositivo está atrás de um gateway NAT). Essa ferramenta permite que um operador inicialize seus dispositivos em um laboratório antes de saber quando ou para onde eles serão enviados. Ou seja, aproveitamos os componentes `elemental-register` e `elemental-system-agent` para permitir a integração de hosts SUSE Linux Micro ao Rancher para casos de uso de provisionamento de rede "phone home". Ao usar o Edge Image Builder (EIB) para criar imagens de implantação, o registro automático através do Rancher via Elemental pode ser alcançado especificando a configuração de registro no diretório de configuração do EIB.

NOTE: No {product} {version-edge} nós *não* utilizamos os aspectos de gerenciamento do sistema operacional do Elemental e, portanto, não é possível gerenciar a aplicação de patches no seu sistema operacional via Rancher. Em vez de usar as ferramentas do Elemental para criar imagens de implantação, o {product} usa a ferramenta Edge Image Builder, que consome a configuração de registro.

== Melhores práticas

=== Mídia de instalação

A {product} maneira recomendada de criar imagens de implantação que possam aproveitar o Elemental para registro no Rancher no cenário de implantação de "provisionamento de rede phone home" é seguir as instruções detalhadas no guia de início rápido <<quickstart-elemental,remote host onboarding with Elemental>>.

=== Rótulos

O Elemental rastreia seu inventário com o `MachineInventory` CRD e fornece uma maneira de selecionar o inventário, por exemplo, para selecionar máquinas para implantar clusters do Kubernetes, com base em rótulos. Isso fornece uma maneira para os usuários predefinirem a maioria (se não todas) de suas necessidades de infraestrutura antes mesmo de o hardware ser comprado. Além disso, como os nós podem adicionar/remover rótulos em seus respectivos objetos de inventário (executando novamente o `elemental-register` com a flag adicional `--label "FOO=BAR"`), podemos escrever scripts que descobrirão e informarão ao Rancher onde um nó foi inicializado.

== Problemas conhecidos

* A interface do usuário do Elemental atualmente não sabe como criar mídia de instalação ou atualizar sistemas operacionais que não sejam "Elemental Teal". Isso deve ser abordado em versões futuras.
