[#components-eco]
= Operador Endpoint Copier
:revdate: 2025-02-28
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:


ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://github.com/suse-edge/endpoint-copier-operator[O Operador Endpoint Copier] é um operador do Kubernetes cujo objetivo é criar uma cópia de um Serviço e Endpoint do Kubernetes e mantê-los sincronizados.

== Como o {product} usa o Operador Endpoint Copier?

Na {product}, o Operador Endpoint Copier desempenha um papel crucial na obtenção de uma configuração de Alta Disponibilidade (HA) para clusters K3s/RKE2. Isso é realizado criando um serviço `kubernetes-vip` do tipo `LoadBalancer`, garantindo que seu Endpoint permaneça em sincronização constante com o Endpoint do Kubernetes. <<components-metallb,MetalLB>> é utilizado para gerenciar o serviço `kubernetes-vip`, já que o endereço IP exposto é usado por outros nós para ingressar no cluster.

== Melhores práticas

A documentação abrangente para usar o Operador Endpoint Copier pode ser encontrada https://github.com/suse-edge/endpoint-copier-operator/blob/main/README.md[aqui].

Além disso, consulte <<guides-metallb-k3s,nosso guia>> sobre como obter uma configuração de HA para K3s/RKE2 usando o Operador Endpoint Copier e MetalLB.

== Problemas conhecidos
Atualmente, o Operador Endpoint Copier está limitado a trabalhar com apenas um Serviço/Endpoint. Melhorias para oferecer suporte a múltiplos Serviços/Endpoints estão planejadas para o futuro.
