[#components-k3s]
= K3s
:revdate: 2025-01-16
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:


ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://k3s.io/[K3s] é uma distribuição Kubernetes certificada e de alta disponibilidade, projetada para cargas de trabalho de produção em locais remotos, autônomos e com restrição de recursos, ou dentro de dispositivos IoT.

Ele é empacotado como um binário único e pequeno, portanto, as instalações e atualizações são rápidas e fáceis.

== Como o {product} usa o K3s?

O K3s pode ser usado como a distribuição Kubernetes que sustenta a pilha {product}.
Ele foi projetado para ser instalado em um sistema operacional SUSE Linux Micro.

O uso do K3s como a distribuição Kubernetes da pilha {product} só é recomendado quando o etcd como backend não atende às suas restrições. Se o etcd como backend for possível, é melhor usar o <<components-rke2,RKE2>>.

== Melhores práticas

=== Instalação
A maneira recomendada de instalar o K3s como parte da pilha {product} é usando o Edge Image Builder (EIB). Consulte <<components-eib,sua documentação>> para obter mais detalhes sobre como configurá-lo para implantar o K3s.

Ele oferece suporte automático à configuração de alta disponibilidade (HA), bem como à configuração do Elemental.

=== Fleet para fluxo de trabalho GitOps
A pilha {product} usa o Fleet como sua ferramenta GitOps preferencial.
Para obter mais informações sobre sua instalação e uso, consulte <<components-fleet,a seção do Fleet>> nesta documentação.

=== Gerenciamento de armazenamento

O K3s vem com armazenamento local-path pré-configurado, o que é adequado para clusters de nó único.
Para clusters que abrangem vários nós, recomendamos o uso do <<components-suse-storage,SUSE Storage>>.

=== Balanceamento de carga e HA

Se você instalou o K3s usando o EIB, esta parte já está coberta pela documentação do EIB na seção de HA.

Caso contrário, você precisa instalar e configurar o MetalLB conforme nossa <<guides-metallb-k3s,documentação do MetalLB>>.
