[#components-slmicro]
= SUSE Linux Micro
:revdate: 2025-01-16
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


Consulte a {link-micro-official-docs}[documentação oficial do SUSE Linux Micro]

[quote]
____
O SUSE Linux Micro é um sistema operacional leve e seguro para a borda. Ele funde os componentes corporativos robustos do SUSE Linux Enterprise com os recursos que os desenvolvedores desejam em um sistema operacional moderno e estável. Como resultado, você obtém uma plataforma de infraestrutura confiável, simples de usar e com a mais alta conformidade da categoria.
____

== Como o {product} usa o SUSE Linux Micro?

Usamos o SUSE Linux Micro como o sistema operacional base para nossa pilha de plataforma. Isso nos fornece uma base segura, estável e mínima para construir.

O SUSE Linux Micro é único em seu uso de instantâneos do sistema de arquivos (Btrfs) para permitir rollbacks fáceis caso algo dê errado durante o fazer upgrade. Isso permite fazer upgrade remoto para toda a plataforma, mesmo sem acesso físico em caso de problemas.

== Melhores práticas

=== Mídia de instalação

O {product} usa o <<components-eib,Edge Image Builder>> para pré-configurar a imagem de instalação para auto-instalação do SUSE Linux Micro.

=== Administração local

O SUSE Linux Micro vem com o Cockpit para permitir o gerenciamento local do host por meio de um aplicativo Web.

Este serviço está desativado por padrão, mas pode ser iniciado ativando o serviço systemd `cockpit.socket`.
Como o Cockpit proíbe o login root por padrão, a criação de um usuário com privilégios administrativos é recomendada; consulte a {link-micro-official-docs}[documentação oficial do SUSE Linux Micro] para obter mais informações.



== Problemas conhecidos

* Não há ambiente de desktop disponível no SUSE Linux Micro no momento, mas uma solução conteinerizada está em desenvolvimento.
