[#components-suse-storage]
= https://www.suse.com/products/rancher/storage/[SUSE Storage]
:revdate: 2025-05-20
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

O SUSE Storage é um sistema de armazenamento em blocos distribuído, leve, confiável e fácil de usar, projetado para o Kubernetes. É um produto baseado no Longhorn, um projeto de código aberto inicialmente desenvolvido pela Rancher Labs e atualmente incubado na CNCF.


== Pré-requisitos

Se você está seguindo este guia, ele pressupõe que você já tenha o seguinte disponível:

* Pelo menos um host com o SUSE Linux Micro {version-operatingsystem} instalado; isso pode ser físico ou virtual
* Um cluster Kubernetes instalado; seja K3s ou RKE2
* Helm

== Instalação manual do SUSE Storage

=== Instalando o Open-iSCSI

Um requisito fundamental para implantar e usar o SUSE Storage é a instalação do pacote `open-iscsi` e o daemon `iscsid` em execução em todos os nós do Kubernetes.
Isso é necessário, já que o Longhorn depende do `iscsiadm` no host para fornecer volumes persistentes ao Kubernetes.

Vamos instalá-lo:

[,shell]
----
transactional-update pkg install open-iscsi
----

É importante observar que, uma vez concluída a operação, o pacote é instalado apenas em um novo snapshot, já que o SUSE Linux Micro é um sistema operacional imutável.
Para carregá-lo e para que o daemon `iscsid` comece a ser executado, devemos reiniciar no novo snapshot que acabamos de criar.
Emita o comando reboot quando estiver pronto:

[,shell]
----
reboot
----

[TIP]
====
Para obter ajuda adicional na instalação do open-iscsi, consulte a {link-longhorn-iscsi}[documentação oficial do Longhorn].
====

=== Instalando o SUSE Storage

Existem várias maneiras de instalar o SUSE Storage em seus clusters Kubernetes.
Este guia seguirá a instalação via Helm; no entanto, sinta-se à vontade para seguir a {link-longhorn-installation}[documentação oficial] caso deseje outra abordagem.

. Faça login na Coleção de Aplicativos do Rancher:
+
[,shell]
----
helm registry login dp.apps.rancher.io --username $APPS.RANCHER.IO_USERNAME --password $APPS.RANCHER.IO_ACCESS_TOKEN
----
+
. Instale o SUSE Storage no namespace `longhorn-system` e adicione suas credenciais de registro de contêiner:
+
[,shell,subs="attributes"]
----
helm install longhorn oci://dp.apps.rancher.io/charts/suse-storage \
  --version {version-longhorn-chart} \
  --namespace longhorn-system \
  --create-namespace \
  --set privateRegistry.createSecret=true \
  --set privateRegistry.registryUrl=dp.apps.rancher.io \
  --set privateRegistry.registryUser=$APPS.RANCHER.IO_USERNAME \
  --set privateRegistry.registryPasswd=$APPS.RANCHER.IO_ACCESS_TOKEN \
  --set privateRegistry.registrySecret=application-collection
----
+
. Confirme se a implantação foi bem-sucedida:
+
[,shell]
----
kubectl -n longhorn-system get pods
----
+
[,console]
----
localhost:~ # kubectl -n longhorn-system get pods
NAME                                                READY   STATUS    RESTARTS        AGE
csi-attacher-7656559cf4-pkhh6                       1/1     Running   0               103s
csi-attacher-7656559cf4-pnzw5                       1/1     Running   0               103s
csi-attacher-7656559cf4-z94mm                       1/1     Running   0               103s
csi-provisioner-6d9cf6456d-kcwtq                    1/1     Running   0               103s
csi-provisioner-6d9cf6456d-mvvml                    1/1     Running   0               103s
csi-provisioner-6d9cf6456d-q4f88                    1/1     Running   0               103s
csi-resizer-f587cd467-clr2n                         1/1     Running   0               103s
csi-resizer-f587cd467-z28v4                         1/1     Running   0               103s
csi-resizer-f587cd467-zxmtx                         1/1     Running   0               103s
csi-snapshotter-6dcdf78684-757mg                    1/1     Running   0               103s
csi-snapshotter-6dcdf78684-8ktgc                    1/1     Running   0               103s
csi-snapshotter-6dcdf78684-ffsqr                    1/1     Running   0               103s
engine-image-ei-099f845a-lvdtr                      1/1     Running   0               2m21s
instance-manager-4adffddaffe02374cd5635b8a6113de7   1/1     Running   0               111s
longhorn-csi-plugin-w7pwr                           3/3     Running   0               103s
longhorn-driver-deployer-6886fb84bc-wm9h6           1/1     Running   2 (2m32s ago)   2m45s
longhorn-manager-zblbl                              2/2     Running   0               2m45s
longhorn-ui-6bcc65d4bd-mcn6r                        1/1     Running   0               2m45s
longhorn-ui-6bcc65d4bd-rwf97                        1/1     Running   0               2m45s
----

== Criando volumes do SUSE Storage

O SUSE Storage utiliza recursos do Kubernetes chamados `StorageClass` para provisionar automaticamente objetos `PersistentVolume` para pods.
Pense em `StorageClass` como uma maneira de os administradores descreverem as _classes_ ou _perfis_ de armazenamento que oferecem.

Vamos criar um `StorageClass` com algumas opções padrão:

[,shell]
----
kubectl apply -f - <<EOF
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-example
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"
EOF
----

Agora que temos nosso `StorageClass` disponível, precisamos de um `PersistentVolumeClaim` referenciando-o.
Uma `PersistentVolumeClaim` (PVC) é uma solicitação de armazenamento feita por um usuário. PVCs consomem recursos de `PersistentVolume`.
As solicitações podem pedir tamanhos e modos de acesso específicos (por exemplo, podem ser montadas uma vez como leitura/gravação ou várias vezes como somente leitura).

Vamos criar um `PersistentVolumeClaim`:

[,shell]
----
kubectl apply -f - <<EOF
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
  namespace: longhorn-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-example
  resources:
    requests:
      storage: 2Gi
EOF
----

É isso! Assim que tivermos o `PersistentVolumeClaim` criado, podemos prosseguir com a anexação dele a um `Pod`.
Quando o `Pod` é implantado, o Kubernetes cria o volume Longhorn e o vincula ao `Pod` se houver armazenamento disponível.

[,shell]
----
kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: longhorn-system
spec:
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: longhorn-volv-pvc
EOF
----

[TIP]
====
O conceito de armazenamento no Kubernetes é um tópico complexo, mas importante. Mencionamos brevemente alguns dos recursos mais comuns do Kubernetes, no entanto, sugerimos que você se familiarize com a {link-longhorn-terminology}[documentação de terminologia] que o Longhorn oferece.
====

Neste exemplo, o resultado deve ser semelhante a isto:

[,console]
----
localhost:~ # kubectl get storageclass
NAME                 PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
longhorn (default)   driver.longhorn.io   Delete          Immediate           true                   12m
longhorn-example     driver.longhorn.io   Delete          Immediate           true                   24s

localhost:~ # kubectl get pvc -n longhorn-system
NAME                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS       AGE
longhorn-volv-pvc   Bound    pvc-f663a92e-ac32-49ae-b8e5-8a6cc29a7d1e   2Gi        RWO            longhorn-example   54s

localhost:~ # kubectl get pods -n longhorn-system
NAME                                                READY   STATUS    RESTARTS      AGE
csi-attacher-5c4bfdcf59-qmjtz                       1/1     Running   0             14m
csi-attacher-5c4bfdcf59-s7n65                       1/1     Running   0             14m
csi-attacher-5c4bfdcf59-w9xgs                       1/1     Running   0             14m
csi-provisioner-667796df57-fmz2d                    1/1     Running   0             14m
csi-provisioner-667796df57-p7rjr                    1/1     Running   0             14m
csi-provisioner-667796df57-w9fdq                    1/1     Running   0             14m
csi-resizer-694f8f5f64-2rb8v                        1/1     Running   0             14m
csi-resizer-694f8f5f64-z9v9x                        1/1     Running   0             14m
csi-resizer-694f8f5f64-zlncz                        1/1     Running   0             14m
csi-snapshotter-959b69d4b-5dpvj                     1/1     Running   0             14m
csi-snapshotter-959b69d4b-lwwkv                     1/1     Running   0             14m
csi-snapshotter-959b69d4b-tzhwc                     1/1     Running   0             14m
engine-image-ei-5cefaf2b-hvdv5                      1/1     Running   0             14m
instance-manager-0ee452a2e9583753e35ad00602250c5b   1/1     Running   0             14m
longhorn-csi-plugin-gd2jx                           3/3     Running   0             14m
longhorn-driver-deployer-9f4fc86-j6h2b              1/1     Running   0             15m
longhorn-manager-z4lnl                              1/1     Running   0             15m
longhorn-ui-5f4b7bbf69-bln7h                        1/1     Running   3 (14m ago)   15m
longhorn-ui-5f4b7bbf69-lh97n                        1/1     Running   3 (14m ago)   15m
volume-test                                         1/1     Running   0             26s
----

== Acessando a interface do usuário

Se você instalou o SUSE Storage com kubectl ou Helm, precisará configurar um controlador Ingress para permitir tráfego externo no cluster. A autenticação não está habilitada por padrão. Se o aplicativo de catálogo do Rancher foi usado, o Rancher criou automaticamente um controlador Ingress com controle de acesso (o rancher-proxy).

. Obtenha o endereço IP do serviço externo do Longhorn:
+
[,console]
----
kubectl -n longhorn-system get svc
----
+
. Depois de recuperar o endereço IP `longhorn-frontend`, você pode começar a usar a interface do usuário navegando até ele em seu navegador.

== Instalando com o Edge Image Builder

O {product} está usando o <<components-eib>> para personalizar imagens base do SUSE Linux Micro OS.
Vamos demonstrar como fazer isso para provisionar um cluster RKE2 com o SUSE Storage sobre ele.

Vamos criar o arquivo de definição:

[,shell,subs="attributes,specialchars"]
----
export CONFIG_DIR=$HOME/eib
mkdir -p $CONFIG_DIR

cat << EOF > $CONFIG_DIR/iso-definition.yaml
apiVersion: {version-eib-api-latest}
image:
  imageType: iso
  baseImage: {micro-base-image-iso}
  arch: x86_64
  outputImageName: eib-image.iso
kubernetes:
  version: {version-kubernetes-rke2}
  helm:
    charts:
      - name: suse-storage
        releaseName: longhorn
        version: {version-longhorn-chart}
        repositoryName: rancher-application-collection
        targetNamespace: longhorn-system
        createNamespace: true
        installationNamespace: kube-system
    repositories:
      - name: rancher-application-collection
        url: oci://dp.apps.rancher.io/charts
        authentication:
          username: $APPS.RANCHER.IO_USERNAME
          password: $APPS.RANCHER.IO_ACCESS_TOKEN
embeddedArtifactRegistry:
  registries:
    - uri: dp.apps.rancher.io
      authentication:
        username: $APPS.RANCHER.IO_USERNAME
        password: $APPS.RANCHER.IO_ACCESS_TOKEN
  images:
    - name: dp.apps.rancher.io/containers/kubernetes-csi-external-attacher:4.11.0-13.2
    - name: dp.apps.rancher.io/containers/kubernetes-csi-external-provisioner:5.3.0-14.1
    - name: dp.apps.rancher.io/containers/kubernetes-csi-external-resizer:2.1.0-6.2
    - name: dp.apps.rancher.io/containers/kubernetes-csi-external-snapshotter:8.5.0-13.2
    - name: dp.apps.rancher.io/containers/kubernetes-csi-livenessprobe:2.18.0-13.2
    - name: dp.apps.rancher.io/containers/kubernetes-csi-node-driver-registrar:2.16.0-13.2
    - name: dp.apps.rancher.io/containers/longhorn-backing-image-manager:1.11.2-4.1
    - name: dp.apps.rancher.io/containers/longhorn-engine:1.11.2-4.2
    - name: dp.apps.rancher.io/containers/longhorn-instance-manager:1.11.2-4.3
    - name: dp.apps.rancher.io/containers/longhorn-manager:1.11.2-4.2
    - name: dp.apps.rancher.io/containers/longhorn-share-manager:1.11.2-4.1
    - name: dp.apps.rancher.io/containers/longhorn-ui:1.11.2-4.1
    - name: dp.apps.rancher.io/containers/rancher-support-bundle-kit:0.0.84-9.4
operatingSystem:
  packages:
    sccRegistrationCode: <reg-code>
    packageList:
      - open-iscsi
  users:
  - username: root
    encryptedPassword: \$6\$jHugJNNd3HElGsUZ\$eodjVe4te5ps44SVcWshdfWizrP.xAyd71CVEXazBJ/.v799/WRCBXxfYmunlBO2yp1hm/zb4r8EmnrrNCF.P/
EOF
----

[NOTE]
====
A personalização de qualquer um dos valores do gráfico Helm é possível por meio de um arquivo separado fornecido em `helm.charts[].valuesFile`.
Consulte a {link-eib-building-images-k8s}[documentação upstream] para obter detalhes.
====

Vamos criar a imagem:

[,shell,subs="attributes"]
----
podman run --rm --privileged -it -v $CONFIG_DIR:/eib registry.suse.com/edge/{version-edge-registry}/edge-image-builder:{version-eib} build --definition-file $CONFIG_DIR/iso-definition.yaml
----

Após a criação da imagem, você pode usá-la para instalar seu SO em um host físico ou virtual.
Assim que o provisionamento for concluído, você poderá fazer login no sistema usando o par de credenciais `root:eib`.

Certifique-se de que o SUSE Storage tenha sido implantado com sucesso:

[,console]
----
localhost:~ # /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml -n longhorn-system get pods
NAME                                                READY   STATUS    RESTARTS        AGE
csi-attacher-5c4bfdcf59-qmjtz                       1/1     Running   0               103s
csi-attacher-5c4bfdcf59-s7n65                       1/1     Running   0               103s
csi-attacher-5c4bfdcf59-w9xgs                       1/1     Running   0               103s
csi-provisioner-667796df57-fmz2d                    1/1     Running   0               103s
csi-provisioner-667796df57-p7rjr                    1/1     Running   0               103s
csi-provisioner-667796df57-w9fdq                    1/1     Running   0               103s
csi-resizer-694f8f5f64-2rb8v                        1/1     Running   0               103s
csi-resizer-694f8f5f64-z9v9x                        1/1     Running   0               103s
csi-resizer-694f8f5f64-zlncz                        1/1     Running   0               103s
csi-snapshotter-959b69d4b-5dpvj                     1/1     Running   0               103s
csi-snapshotter-959b69d4b-lwwkv                     1/1     Running   0               103s
csi-snapshotter-959b69d4b-tzhwc                     1/1     Running   0               103s
engine-image-ei-5cefaf2b-hvdv5                      1/1     Running   0               109s
instance-manager-0ee452a2e9583753e35ad00602250c5b   1/1     Running   0               109s
longhorn-csi-plugin-gd2jx                           3/3     Running   0               103s
longhorn-driver-deployer-9f4fc86-j6h2b              1/1     Running   0               2m28s
longhorn-manager-z4lnl                              1/1     Running   0               2m28s
longhorn-ui-5f4b7bbf69-bln7h                        1/1     Running   3 (2m7s ago)    2m28s
longhorn-ui-5f4b7bbf69-lh97n                        1/1     Running   3 (2m10s ago)   2m28s
----

[NOTE]
====
Esta instalação não funcionará para ambientes totalmente air-gapped.
Nesses casos, consulte <<suse-storage-install>>.
====
