[#components-metal3]
= Metal^3^
:revdate: 2024-11-20
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://metal3.io/[Metal^3^] é um projeto da CNCF que fornece recursos de gerenciamento de infraestrutura bare-metal para o Kubernetes.

O Metal^3^ fornece recursos nativos do Kubernetes para gerenciar o ciclo de vida de servidores bare-metal que oferecem suporte a gerenciamento via protocolos fora de banda, como https://www.dmtf.org/standards/redfish[Redfish].

Ele também possui suporte maduro para https://cluster-api.sigs.k8s.io/[Cluster API (CAPI)]. 
Isso permite o gerenciamento de recursos de hardware em vários provedores de infraestrutura por meio de APIs neutras de fornecedores amplamente adotadas. 
O Cluster API usa o Metal^3^ como um backend de infraestrutura para objetos Machine.

== Como o {product} usa o Metal^3^?

O {product} usa o Metal^3^ para gerenciar o ciclo de vida de hardware físico, como servidores. O hardware precisa oferecer suporte a um protocolo de gerenciamento fora de banda que seja suportado pelo Metal^3^ (por exemplo, Redfish). Quando um cluster de gerenciamento {product} provisiona ou desprovisiona clusters downstream, o Metal^3^ interagirá com o BMC de um servidor via Redfish. As seguintes ações geralmente fazem parte dessa interação: +

* Montar e desmontar Mídia Virtual.
* Ligar, desligar e reiniciar servidores.

Essa abordagem é útil para cenários onde o hardware de destino oferece suporte a gerenciamento fora de banda e um fluxo de gerenciamento de infraestrutura totalmente automatizado é desejado.

O Metal^3^ e o CAPI fornecem APIs declarativas que permitem o gerenciamento de inventário e estado de servidores bare-metal, incluindo inspeção, limpeza e provisionamento/desprovisionamento automatizados.

== Problemas conhecidos

* O https://github.com/metal3-io/ip-address-manager[controlador de Gerenciamento de Endereço IP] upstream não é suportado atualmente, pois ainda não é compatível com nossa escolha de ferramentas de configuração de rede. No entanto, o pod `ipam-controller-manager` hospedado no namespace `metal3-ipam-system` é necessário, pois o CAPM3 requer que os CRDs `ipam` existam.
* Relacionado a isso, os recursos de IPAM e os campos networkData do Metal3DataTemplate não são suportados.
* Apenas a implantação via redfish-virtualmedia é suportada atualmente.
