[#components-metal3]
= Metal^3^
:revdate: 2024-11-20
:revnumber: 3.4
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://metal3.io/[Metal^3^] é um projeto da CNCF que fornece recursos de gerenciamento de infraestrutura bare-metal para o Kubernetes.

O Metal^3^ fornece recursos nativos do Kubernetes para gerenciar o ciclo de vida de servidores bare-metal que suportam gerenciamento via protocolos fora de banda, como https://www.dmtf.org/standards/redfish[Redfish].

Ele também possui suporte maduro para https://cluster-api.sigs.k8s.io/[Cluster API (CAPI)], que permite o gerenciamento de recursos de infraestrutura em vários provedores de infraestrutura por meio de APIs neutras de fornecedores amplamente adotadas.

== Como o SUSE Edge usa o Metal^3^?

Este método é útil para cenários em que o hardware de destino suporta gerenciamento fora de banda e deseja-se um fluxo de gerenciamento de infraestrutura totalmente automatizado.

Este método fornece APIs declarativas que permitem o gerenciamento de inventário e estado de servidores bare metal, incluindo inspeção, limpeza e provisionamento/desprovisionamento automatizados.

[#known-issues-metal3]
== Problemas conhecidos

* O https://github.com/metal3-io/ip-address-manager[controlador de Gerenciamento de Endereço IP] upstream não é suportado atualmente, pois ainda não é compatível com nossa escolha de ferramentas de configuração de rede. No entanto, o pod `ipam-controller-manager` hospedado no namespace `metal3-ipam-system` é necessário, pois o CAPM3 requer que os CRDs `ipam` existam.
* Relacionado a isso, os recursos de IPAM e os campos networkData do Metal3DataTemplate não são suportados.
* Apenas a implantação via redfish-virtualmedia é suportada atualmente.
* É possível observar um desalinhamento no nome do dispositivo de rede entre o ironic python agent (IPA) e o sistema operacional de destino (SL Micro 6.0/6.1), especialmente ao tentar configurar nomes previsíveis para os dispositivos.

Isso acontece porque o kernel do ironic python agent (IPA) não está atualmente alinhado com o kernel do sistema operacional de destino (SL Micro 6.0/6.1), portanto, há um desalinhamento nos drivers de rede que permite que o IPA descubra dispositivos de rede em um padrão de nomenclatura diferente do que o SL Micro espera.

Existem duas abordagens diferentes a serem usadas como solução alternativa nesse meio tempo: +
* Crie dois segredos diferentes com a configuração de rede, um para ser usado com o IPA usando os nomes de dispositivo conforme o IPA os descobrirá e o usará como `preprovisioningNetworkDataName` na definição `BareMetalHost` e outro segredo com os nomes de dispositivo conforme o SL Micro os descobrirá e o usará como `networkData.name` na definição `BareMetalHost`. +
* Use os UUIDs para referenciar outras interfaces nos arquivos nmconnection gerados.
Mais detalhes na seção xref:edge.adoc#tips-and-tricks[Dicas e truques].
