[#components-suse-security]
= https://www.suse.com/products/rancher/security/[SUSE Security]
:revdate: 2025-01-16
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]



O SUSE Security é uma solução de segurança para Kubernetes que fornece segurança de rede L7, segurança de tempo de execução, segurança da cadeia de suprimento e verificações de conformidade em um pacote coeso.

O SUSE Security é um produto que é implantado como uma plataforma de múltiplos contêineres, cada um comunicando-se por várias portas e interfaces. Internamente, ele usa o NeuVector como seu componente de segurança de contêiner subjacente. Os seguintes contêineres compõem a plataforma SUSE Security:

* Gerente. Um contêiner sem estado que apresenta o console baseado na Web. Normalmente, apenas um é necessário e ele pode ser executado em qualquer lugar. A falha do Gerente não afeta nenhuma das operações do controller ou enforcer. No entanto, certas notificações (eventos) e dados de conexão recentes são armazenados em cache na memória pelo Gerente, portanto, a visualização deles seria afetada.
* Controller. O ‘plano de controle’ para o SUSE Security deve ser implantado em uma configuração de HA, para que a configuração não seja perdida em uma falha de nó. Eles podem ser executados em qualquer lugar, embora os clientes frequentemente escolham colocá-los em nós de ‘gerenciamento’, master ou infra devido à sua criticidade.
* Enforcer. Este contêiner é implantado como um DaemonSet, portanto, um Enforcer está em cada nó a ser protegido. Normalmente é implantado em cada nó de trabalho, mas o agendamento pode ser habilitado para nós master e infra para implantar lá também. Nota: Se o Enforcer não estiver em um nó de cluster e as conexões vierem de um pod nesse nó, o SUSE Security os rotula como cargas de trabalho 'não gerenciadas'.
* Scanner. Realiza a verificação de vulnerabilidade usando o banco de dados CVE incorporado, conforme direcionado pelo Controller. Vários scanners podem ser implantados para aumentar a capacidade de verificação. Os scanners podem ser executados em qualquer lugar, mas geralmente são executados nos nós onde os controllers são executados. Veja abaixo as considerações de dimensionamento dos nós do scanner. Um scanner também pode ser invocado independentemente quando usado para verificação na fase de compilação, por exemplo, dentro de um pipeline que aciona uma verificação, recupera os resultados e interrompe o scanner. O scanner contém o banco de dados CVE mais recente, portanto, deve ser atualizado diariamente.
* Updater. O atualizador aciona uma atualização do scanner por meio de um cron job do Kubernetes quando uma atualização do banco de dados CVE é desejada. Certifique-se de configurar isso para o seu ambiente.


Uma documentação mais detalhada sobre a integração e as melhores práticas do SUSE Security pode ser encontrada https://open-docs.neuvector.com/[aqui].

== Como o {product} usa o SUSE Security?

O {product} fornece uma configuração mais enxuta do SUSE Security como ponto de partida para implantações de borda.

== Notas importantes

* O contêiner `Scanner` deve ter memória suficiente para carregar a imagem a ser escaneada na memória e expandi-la. Para verificar imagens que excedam 1 GB, aumente a memória do scanner para um valor ligeiramente superior ao tamanho da maior imagem esperada.

* Alto número de conexões de rede esperado no modo Protect. O `Enforcer` requer CPU e memória quando está no modo Protect (bloqueio de firewall em linha) para manter e inspecionar conexões e possíveis cargas úteis (DLP). Aumentar a memória e dedicar um núcleo de CPU ao `Enforcer` pode garantir uma capacidade adequada de filtragem de pacotes.

== Instalando com o Edge Image Builder

{product} está usando <<components-eib>> para personalizar imagens base do SUSE Linux Micro OS.
Siga <<suse-security-install>> para uma instalação air-gapped do SUSE Security sobre clusters Kubernetes provisionados pelo EIB.
