[#components-rancher-turtles]
= Rancher Turtles
:revdate: 2025-12-15
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


Consulte a documentação do Rancher Turtles em https://documentation.suse.com/cloudnative/cluster-api/

[quote]
____
O Rancher Turtles é um operador do Kubernetes que faz a integração entre o Rancher Manager e a Cluster API (CAPI) com o objetivo de levar suporte completo à CAPI para o Rancher
____


== Principais recursos do Rancher Turtles

* Importe automaticamente clusters CAPI para o Rancher, instalando o Rancher Cluster Agent em clusters provisionados pelo CAPI.
* Instale e configure as dependências do controlador CAPI por meio do https://cluster-api-operator.sigs.k8s.io/[CAPI Operator].
* Gerencie as dependências do provedor CAPI instaladas por meio da `CAPIProvider` API

== Uso do Rancher Turtles no {product}

A pilha {product} fornece um gráfico helm `rancher-turtles-providers` que habilita determinados provedores CAPI por meio da `CAPIProvider` API:

* Provedor de plano de controle e de inicializar do RKE2
* Provedor de infraestrutura <<components-metal3,Metal3>>
* Provedor de IPAM <<components-metal3,Metal3>> (atualmente não suportado)
* Provedor de addon Fleet

Apenas os provedores padrão instalados por meio do agrupador são suportados – provedores alternativos de plano de controle, de inicializar e de infraestrutura não são suportados atualmente como parte da pilha {product}.

== Instalando o Rancher Turtles

Desde o Rancher 2.13, o Rancher Turtles é habilitado por padrão ao instalar o Rancher.

Os Provedores do Rancher Turtles podem ser instalados seguindo o guia <<quickstart-metal3,Metal3 Quickstart>> ou a documentação do <<atip-management-cluster,Management Cluster>>.

== Recursos adicionais

* https://rancher.com/docs/[Documentação do Rancher]
* https://cluster-api.sigs.k8s.io/[Livro da Cluster API]
