[#components-rancher-turtles]
= Rancher Turtles
:revdate: 2025-04-25
:revnumber: 3.4
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


Consulte a documentação do Rancher Turtles em https://documentation.suse.com/cloudnative/cluster-api/

[quote]
____
O Rancher Turtles é um operador do Kubernetes que faz a integração entre o Rancher Manager e a Cluster API (CAPI) com o objetivo de levar suporte completo à CAPI para o Rancher
____


== Principais recursos do Rancher Turtles

* Importe automaticamente clusters CAPI para o Rancher, instalando o Rancher Cluster Agent em clusters provisionados pelo CAPI.
* Instale e configure as dependências do controlador CAPI por meio do https://cluster-api-operator.sigs.k8s.io/[CAPI Operator].

== Uso dos Rancher Turtles no SUSE Edge

O stack SUSE Edge fornece um chart agrupador de helm que instala o Rancher Turtles com uma configuração específica que habilita:

* Componentes do kernel do controlador CAPI
* Componentes do plano de controle do RKE2 e do provedor de inicializar.
* Componentes do provedor de infraestrutura <<components-metal3,Metal3>>

Apenas os provedores padrão instalados por meio do gráfico agrupador são suportados – provedores alternativos de Plano de Controle, de inicialização e de infraestrutura não são suportados atualmente como parte da pilha SUSE Edge.

== Instalando o Rancher Turtles

O Rancher Turtles pode ser instalado seguindo o guia <<quickstart-metal3,Metal3 Quickstart>> ou a documentação do <<atip-management-cluster,Management Cluster>>.

== Recursos adicionais

* https://rancher.com/docs/[Documentação do Rancher]
* https://cluster-api.sigs.k8s.io/[Livro da Cluster API]
