[#components-eib]
= Edge Image Builder
:revdate: 2025-08-07
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:


ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

请参阅 https://github.com/suse-edge/edge-image-builder[官方储存库]。
 

Edge Image Builder (EIB) 是一款用于简化生成定制化、即启即用 (CRB) 磁盘镜像以引导机器的工具。这些镜像支持通过单个镜像实现整个 SUSE 软件栈的端到端部署。

虽然 EIB 可以为所有配置场景创建 CRB 镜像，但 EIB 在网络受限或完全隔离的部署中展现出了巨大的价值。


== {product} 如何使用 Edge Image Builder？

{product}使用 EIB 来简化和快速配置用于各种场景的定制化 SUSE Linux Micro 镜像。这些场景包括对虚拟机和裸机的引导，具体如下：

* 完全隔离环境下的 K3s/RKE2 Kubernetes 部署（单节点和多节点）
* 完全隔离环境下的 Helm chart 和 Kubernetes 清单部署
* 通过 Elemental API 注册到 Rancher
* Metal^3^
* 定制化网络（例如，静态 IP、主机名、VLAN、绑定等）
* 定制化操作系统配置（例如，用户、组、密码、SSH 密钥、代理、NTP、自定义 SSL 证书等）
* 主机级和侧载 RPM 包的隔离安装（包括依赖项解析）
* 注册到 SUSE Multi-Linux Manager 进行操作系统管理
* 嵌入式容器镜像
* 内核命令行参数
* 在引导时启用/禁用的 Systemd 单元
* 用于任何手动任务的自定义脚本和文件

== 入门

有关 Edge Image Builder 使用和测试的综合文档可以在 {link-eib-docs}[此处] 找到。

此外，请参阅涵盖基本部署场景的 <<quickstart-eib>>。

一旦您熟悉了此工具，请在我们的 <<tips-and-tricks,EIB 提示与技巧部分>> 页面上查找更多有用的信息。

== 已知问题

* EIB 通过对 Helm chart 进行模板化并解析模板内的所有镜像来实现 Helm chart 的隔离。如果 Helm chart 没有将其所有镜像保留在模板内，而是侧载了这些镜像，则 EIB 将无法自动对这些镜像进行隔离。解决此问题的办法是手动将任何未检测到的镜像添加到定义文件的 `embeddedArtifactRegistry` 部分。
