[#components-slmicro]
= SUSE Linux Micro
:revdate: 2025-01-16
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


请参阅 {link-micro-official-docs}[SUSE Linux Micro 官方文档]

[quote]
____
SUSE Linux Micro 是一款适用于边缘计算的轻量级且安全的操作系统。它将 SUSE Linux Enterprise 的企业强化组件与开发人员需要的各种功能融入一套现代的不可变操作系统。从而形成一个可靠的基础设施平台，不仅具有最佳的合规性，而且易于使用。
____

== {product} 如何使用 SUSE Linux Micro？

我们将 SUSE Linux Micro 用作我们平台堆栈的基础操作系统。这为我们提供了一个安全、稳定且精简的基础，以便在其上进一步构建。

SUSE Linux Micro 的独特之处在于它使用文件系统 (Btrfs) 快照，以便在升级出现问题时轻松回滚。即使在出现问题且无法进行物理访问的情况下，这也允许对整个平台进行安全的远程升级。

== 最佳实践

=== 安装媒体

{product} 使用 <<components-eib,Edge Image Builder>> 来预配置 SUSE Linux Micro 自安装安装镜像。

=== 本地管理

SUSE Linux Micro 附带 Cockpit，允许通过 Web 应用程序对主机进行本地管理。

此服务默认处于禁用状态，但可以通过启用 systemd 服务 `cockpit.socket` 来启动。
由于 Cockpit 默认禁止 root 登录，建议创建具有管理权限的用户。有关更多信息，请参阅 {link-micro-official-docs}[SUSE Linux Micro 官方文档]。



== 已知问题

* 目前 SUSE Linux Micro 中没有可用的桌面环境，但正在开发容器化解决方案。
