[#components-metal3]
= Metal^3^
:revdate: 2024-11-20
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://metal3.io/[Metal^3^] 是一个 CNCF 项目，为 Kubernetes 提供裸机基础设施管理功能。

Metal^3^ 提供 Kubernetes 原生资源来管理裸机服务器的生命周期，这些服务器支持通过带外协议（例如 https://www.dmtf.org/standards/redfish[Redfish]）进行管理。

它还对 https://cluster-api.sigs.k8s.io/[Cluster API (CAPI)] 拥有成熟的支持。
这使得能够通过广泛采用的供应商中立 API 管理跨多个基础设施提供商的硬件资源。
Cluster API 使用 Metal^3^ 作为 Machine 对象的基础设施后端。

== {product} 如何使用 Metal^3^？

{product} 使用 Metal^3^ 来管理物理硬件（例如服务器）的生命周期。硬件需要支持 Metal^3^ 支持的带外管理协议（例如 Redfish）。当 {product} 管理集群配置或取消配置下游集群时，Metal^3^ 将通过 Redfish 与服务器的 BMC 进行交互。以下操作通常是此交互的一部分： +

* 挂载和卸载虚拟媒体。
* 服务器开机、关机和重置。

这种方法适用于目标硬件支持带外管理且需要完全自动化的基础设施管理流程的场景。

Metal^3^ 和 CAPI 提供了声明式 API，支持裸机服务器的库存和状态管理，包括自动检查、清理以及配置/取消配置。

== 已知问题

* 目前不支持上游 https://github.com/metal3-io/ip-address-manager[IP 地址管理控制器]，因为它尚不兼容我们选择的网络配置工具。但是，`ipam-controller-manager` 托管在 `metal3-ipam-system` 名称空间上的 Pod 是必需的，因为 CAPM3 要求存在 `ipam` CRD。
* 相关地，不支持 IPAM 资源和 Metal3DataTemplate networkData 字段。
* 目前仅支持通过 redfish-virtualmedia 进行部署。
