[#components-metal3]
= Metal^3^
:revdate: 2024-11-20
:revnumber: 3.4
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://metal3.io/[Metal^3^] 是一个 CNCF 项目，为 Kubernetes 提供裸机基础设施管理功能。

Metal^3^ 提供 Kubernetes 原生资源来管理裸机服务器的生命周期，这些服务器支持通过带外协议（例如 https://www.dmtf.org/standards/redfish[Redfish]）进行管理。

它还对 https://cluster-api.sigs.k8s.io/[Cluster API (CAPI)] 提供了成熟的支持，该支持通过广泛采用的供应商中立 API 实现跨多个基础设施提供商的基础设施资源管理。

== SUSE Edge 如何使用 Metal^3^?

这种方法适用于目标硬件支持带外管理且需要完全自动化的基础设施管理流程的场景。

此方法提供了声明式 API，支持裸机服务器的库存和状态管理，包括自动检查、清理以及配置/取消配置。

[#known-issues-metal3]
== 已知问题

* 目前不支持上游 https://github.com/metal3-io/ip-address-manager[IP 地址管理控制器]，因为它尚不兼容我们选择的网络配置工具。但是，`ipam-controller-manager` 托管在 `metal3-ipam-system` 名称空间上的 Pod 是必需的，因为 CAPM3 要求存在 `ipam` CRD。
* 相关地，不支持 IPAM 资源和 Metal3DataTemplate networkData 字段。
* 目前仅支持通过 redfish-virtualmedia 进行部署。
* 在 ironic python agent (IPA) 和目标操作系统 (SL Micro 6.0/6.1) 之间可能会观察到网络设备名称不匹配的情况，尤其是在尝试为设备配置可预测名称时。

出现这种情况是因为 ironic python agent (IPA) 的内核目前与目标操作系统 (SL Micro 6.0/6.1) 的内核不一致，因此网络驱动程序存在不匹配，导致 IPA 发现网络设备时所使用的命名模式与 SL Micro 预期的不同。

在此期间，有两种不同的解决方法可供使用： +
* 创建两个包含网络配置的不同密钥，一个用于 IPA，使用 IPA 发现的设备名称，并将其作为 `preprovisioningNetworkDataName` 用于 `BareMetalHost` 定义；另一个密钥使用 SL Micro 发现的设备名称，并将其作为 `networkData.name` 用于 `BareMetalHost` 定义。 +
* 改为使用 UUID 来引用生成的 nmconnection 文件中的其他接口。
更多详细信息，请参阅 xref:edge.adoc#tips-and-tricks[Tips and tricks] 部分。
