[#components-nmc]
= 边缘网络
:revdate: 2025-03-26
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:


ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

本节介绍了 {product} 解决方案中的网络配置方法。
我们将展示如何在 SUSE Linux Micro 上以声明方式配置 NetworkManager，并解释相关工具是如何集成的。

== NetworkManager 概述

NetworkManager 是用于管理主网络连接和其他连接接口的工具。

NetworkManager 将网络配置存储为包含期望状态的连接文件。
这些连接以文件的形式存储在 `/etc/NetworkManager/system-connections/` 目录中。

有关 NetworkManager 的详细信息，请参阅 {link-micro-networkmanager}[SUSE Linux Micro 文档]。

== nmstate 概述

nmstate 是一个被广泛采用的库（附带一个 CLI 工具），它通过预定义的模式为网络配置提供声明式 API。

有关 nmstate 的详细信息，请参阅 https://nmstate.io/[上游文档]。

== Enter:NetworkManager 配置器 (nmc)

{product} 中提供的网络自定义选项是通过一个名为 NetworkManager 配置器（简称 _nmc_）的 CLI 工具实现的。
它利用了 nmstate 库提供的功能，因此完全能够配置静态 IP 地址、DNS 服务器、VLAN、网络绑定、网桥等。
该工具允许我们根据预定义的期望状态生成网络配置，并以自动化的方式在许多不同的节点上应用这些配置。

有关 NetworkManager 配置器 (nmc) 的详细信息，请参阅 https://github.com/suse-edge/nm-configurator[上游储存库]。

== {product} 如何使用 NetworkManager 配置器？

{product} 在各种不同的配置模型中利用 _nmc_ 进行网络自定义：
ifeval::["{flavor}" == "telco"]
* 定向网络配置场景中的自定义网络配置 (<<quickstart-metal3>>)
endif::[]
* 基于镜像的置备场景中的声明式静态配置 (<<quickstart-eib>>)

== 使用 Edge Image Builder 进行配置

Edge Image Builder (EIB) 是一款能够使用单个操作系统映像配置多个主机的工具。
在本节中，我们将展示如何使用声明式方法来描述所需的网络状态，这些状态如何转换为相应的 NetworkManager 连接，然后在置备过程中应用。

=== 先决条件

如果您正在阅读本指南，则假定您已具备以下条件：

* 一台运行 SLES 15 SP6 或 openSUSE Leap 15.6 的 {x86-64} 物理主机（或虚拟机）
* 一个可用的容器运行时（例如 Podman）
* 一份 SUSE Linux Micro {version-operatingsystem} RAW 映像副本，可在 https://www.suse.com/download/sle-micro/[此处] 找到

=== 获取 Edge Image Builder 容器映像

EIB 容器映像是公开可用的，可以通过运行以下命令从 {product} 注册表中下载：

[,shell,subs="attributes"]
----
podman pull registry.suse.com/edge/{version-edge-registry}/edge-image-builder:{version-eib}
----

=== 创建映像配置目录 [[image-config-dir-creation]]

让我们从创建配置目录开始：

[,shell]
----
export CONFIG_DIR=$HOME/eib
mkdir -p $CONFIG_DIR/base-images
----

现在，我们将确保已下载的基础映像副本被移动到配置目录中：

[,shell,subs="attributes"]
----
mv /path/to/downloads/{micro-base-image-raw} $CONFIG_DIR/base-images/
----

> NOTE: EIB 绝不会修改基础映像输入。它将创建一个包含其修改内容的新映像。

此时，配置目录应如下所示：

[,console,subs="attributes"]
----
└── base-images/
    └── {micro-base-image-raw}
----

=== 创建映像定义文件

定义文件描述了 Edge Image Builder 支持的大多数可配置选项。

让我们从一个非常基础的操作系统映像定义文件开始：

[,shell,subs="attributes,specialchars"]
----
cat << EOF > $CONFIG_DIR/definition.yaml
apiVersion: {version-eib-api-latest}
image:
  arch: x86_64
  imageType: raw
  baseImage: {micro-base-image-raw}
  outputImageName: modified-image.raw
operatingSystem:
  users:
    - username: root
      encryptedPassword: $6$jHugJNNd3HElGsUZ$eodjVe4te5ps44SVcWshdfWizrP.xAyd71CVEXazBJ/.v799/WRCBXxfYmunlBO2yp1hm/zb4r8EmnrrNCF.P/
EOF
----

`image` 部分是必需的，它指定了输入映像、其架构和类型，以及输出映像的名称。
`operatingSystem` 部分是可选的，包含用于启用使用 `root/eib` 用户名/密码登录到置备系统的配置。

> NOTE: 请随意使用您自己的加密密码，方法是运行 `openssl passwd -6 <password>`。

此时，配置目录应如下所示：

[,console,subs="attributes"]
----
├── definition.yaml
└── base-images/
    └── {micro-base-image-raw}
----

=== 定义网络配置 [[default-network-definition]]

所需的网络配置不属于我们刚刚创建的镜像定义文件。
我们现在将把它们填充到特殊的 `network/` 目录下。让我们创建它：

[,shell]
----
mkdir -p $CONFIG_DIR/network
----

如前所述，NetworkManager 配置器 (_nmc_) 工具期望以预定义模式的形式输入。
您可以在 https://nmstate.io/examples.html[上游 NMState 示例文档] 中找到如何设置各种不同的网络选项。

本指南将解释如何配置三个不同节点上的网络：

* 使用两个以太网接口的节点
* 使用网络绑定的节点
* 使用网络网桥的节点

[WARNING]
====
在生产构建中不建议使用完全不同的网络设置，尤其是在配置 Kubernetes 集群时。
网络配置通常应在节点之间保持同构，或者至少在给定集群内的角色之间保持同构。
本指南包含各种不同的选项，仅供参考。
====

> NOTE: 以下内容假设使用具有 IP 地址范围 `192.168.122.1/24` 的默认 `libvirt` 网络。
如果您的环境有所不同，请相应地进行调整。

让我们为第一个节点创建所需的状态，我们将其称为 `node1.suse.com`：

[,shell]
----
cat << EOF > $CONFIG_DIR/network/node1.suse.com.yaml
routes:
  config:
    - destination: 0.0.0.0/0
      metric: 100
      next-hop-address: 192.168.122.1
      next-hop-interface: eth0
      table-id: 254
    - destination: 192.168.122.0/24
      metric: 100
      next-hop-address: 192.168.122.1
      next-hop-interface: eth0
      table-id: 254
dns-resolver:
  config:
    server:
      - 192.168.122.1
      - 8.8.8.8
interfaces:
  - name: eth0
    type: ethernet
    state: up
    mac-address: 34:8A:B1:4B:16:E1
    ipv4:
      address:
        - ip: 192.168.122.50
          prefix-length: 24
      dhcp: false
      enabled: true
    ipv6:
      enabled: false
  - name: eth3
    type: ethernet
    state: down
    mac-address: 34:8A:B1:4B:16:E2
    ipv4:
      address:
        - ip: 192.168.122.55
          prefix-length: 24
      dhcp: false
      enabled: true
    ipv6:
      enabled: false
EOF
----

在此示例中，我们定义了两个以太网接口（eth0 和 eth3）的所需状态、它们请求的 IP 地址、路由和 DNS 解析。

[WARNING]
====
您必须确保列出所有以太网接口的 MAC 地址。
这些地址在置备过程中用作节点的标识符，并用于确定应应用哪些配置。
这就是我们能够使用单个 ISO 或 RAW 镜像配置多个节点的方法。
====

接下来是第二个节点，我们将称之为 `node2.suse.com`，它将使用网络绑定：

[,shell]
----
cat << EOF > $CONFIG_DIR/network/node2.suse.com.yaml
routes:
  config:
    - destination: 0.0.0.0/0
      metric: 100
      next-hop-address: 192.168.122.1
      next-hop-interface: bond99
      table-id: 254
    - destination: 192.168.122.0/24
      metric: 100
      next-hop-address: 192.168.122.1
      next-hop-interface: bond99
      table-id: 254
dns-resolver:
  config:
    server:
      - 192.168.122.1
      - 8.8.8.8
interfaces:
  - name: bond99
    type: bond
    state: up
    ipv4:
      address:
        - ip: 192.168.122.60
          prefix-length: 24
      enabled: true
    link-aggregation:
      mode: balance-rr
      options:
        miimon: '140'
      port:
        - eth0
        - eth1
  - name: eth0
    type: ethernet
    state: up
    mac-address: 34:8A:B1:4B:16:E3
    ipv4:
      enabled: false
    ipv6:
      enabled: false
  - name: eth1
    type: ethernet
    state: up
    mac-address: 34:8A:B1:4B:16:E4
    ipv4:
      enabled: false
    ipv6:
      enabled: false
EOF
----

在此示例中，我们定义了两个以太网接口（eth0 和 eth1）的所需状态，它们未启用 IP 寻址，以及一个具有轮询策略的网络绑定及其将用于转发网络流量的相应地址。

最后，我们将创建第三个也是最后一个所需状态文件，它将利用网络网桥，我们将称之为 `node3.suse.com`：

[,shell]
----
cat << EOF > $CONFIG_DIR/network/node3.suse.com.yaml
routes:
  config:
    - destination: 0.0.0.0/0
      metric: 100
      next-hop-address: 192.168.122.1
      next-hop-interface: linux-br0
      table-id: 254
    - destination: 192.168.122.0/24
      metric: 100
      next-hop-address: 192.168.122.1
      next-hop-interface: linux-br0
      table-id: 254
dns-resolver:
  config:
    server:
      - 192.168.122.1
      - 8.8.8.8
interfaces:
  - name: eth0
    type: ethernet
    state: up
    mac-address: 34:8A:B1:4B:16:E5
    ipv4:
      enabled: false
    ipv6:
      enabled: false
  - name: linux-br0
    type: linux-bridge
    state: up
    ipv4:
      address:
        - ip: 192.168.122.70
          prefix-length: 24
      dhcp: false
      enabled: true
    bridge:
      options:
        group-forward-mask: 0
        mac-ageing-time: 300
        multicast-snooping: true
        stp:
          enabled: true
          forward-delay: 15
          hello-time: 2
          max-age: 20
          priority: 32768
      port:
        - name: eth0
          stp-hairpin-mode: false
          stp-path-cost: 100
          stp-priority: 32
EOF
----

此时，配置目录应如下所示：

[,console,subs="attributes"]
----
├── definition.yaml
├── network/
│   │── node1.suse.com.yaml
│   │── node2.suse.com.yaml
│   └── node3.suse.com.yaml
└── base-images/
    └── {micro-base-image-raw}
----

> NOTE: `network/` 目录下的文件名是刻意这样命名的。
它们对应于将在置备过程中设置的主机名。

=== 构建操作系统镜像

现在所有必要的配置都已就绪，我们可以通过简单地运行以下命令来构建镜像：

[,shell,subs="attributes"]
----
podman run --rm -it -v $CONFIG_DIR:/eib registry.suse.com/edge/{version-edge-registry}/edge-image-builder:{version-eib} build --definition-file definition.yaml
----

输出应如下所示：

[,shell]
----
Generating image customization components...
Identifier ................... [SUCCESS]
Custom Files ................. [SKIPPED]
Time ......................... [SKIPPED]
Network ...................... [SUCCESS]
Groups ....................... [SKIPPED]
Users ........................ [SUCCESS]
Proxy ........................ [SKIPPED]
Rpm .......................... [SKIPPED]
Systemd ...................... [SKIPPED]
Elemental .................... [SKIPPED]
Suma ......................... [SKIPPED]
Embedded Artifact Registry ... [SKIPPED]
Keymap ....................... [SUCCESS]
Kubernetes ................... [SKIPPED]
Certificates ................. [SKIPPED]
Building RAW image...
Kernel Params ................ [SKIPPED]
Image build complete!
----

上面的代码片段告诉我们 `Network` 组件已成功配置，我们可以继续配置边缘节点。

> NOTE: 可以在生成的 `_build` 目录下的时间戳目录中检查日志文件 (`network-config.log`) 和相应的 NetworkManager 连接文件。

=== 配置边缘节点

让我们复制生成的 RAW 镜像：

[,shell]
----
mkdir edge-nodes && cd edge-nodes
for i in {1..4}; do cp $CONFIG_DIR/modified-image.raw node$i.raw; done
----

您会注意到我们复制了四次构建的镜像，但只指定了三个节点的网络配置。
这是因为我们还想展示如果我们配置一个与任何所需配置都不匹配的节点会发生什么。

> NOTE: 本指南将使用虚拟化进行节点配置示例。确保在 BIOS 中启用了必要的扩展（有关详细信息，请参阅 https://documentation.suse.com/sles/15-SP6/html/SLES-all/cha-virt-support.html#sec-kvm-requires-hardware[此处]）。

我们将使用 `virt-install` 来使用复制的原始磁盘创建虚拟机。
每个虚拟机将使用 10 GB 的 RAM 和 6 个 vCPU。

==== 配置第一个节点

让我们创建虚拟机：

[,shell]
----
virt-install --name node1 --ram 10000 --vcpus 6 --disk path=node1.raw,format=raw --osinfo detect=on,name=sle-unknown --graphics none --console pty,target_type=serial --network default,mac=34:8A:B1:4B:16:E1 --network default,mac=34:8A:B1:4B:16:E2 --virt-type kvm --import
----

> NOTE: 重要的是，我们要使用与上述预期状态中相同的 MAC 地址来创建网络接口。

操作完成后，我们将看到类似以下的内容：

[,console]
----
Starting install...
Creating domain...

Running text console command: virsh --connect qemu:///system console node1
Connected to domain 'node1'
Escape character is ^] (Ctrl + ])


Welcome to SUSE Linux Micro 6.0 (x86_64) - Kernel 6.4.0-18-default (tty1).

SSH host key: SHA256:XN/R5Tw43reG+QsOw480LxCnhkc/1uqMdwlI6KUBY70 (RSA)
SSH host key: SHA256:/96yGrPGKlhn04f1rb9cXv/2WJt4TtrIN5yEcN66r3s (DSA)
SSH host key: SHA256:Dy/YjBQ7LwjZGaaVcMhTWZNSOstxXBsPsvgJTJq5t00 (ECDSA)
SSH host key: SHA256:TNGqY1LRddpxD/jn/8dkT/9YmVl9hiwulqmayP+wOWQ (ED25519)
eth0: 192.168.122.50
eth1:


Configured with the Edge Image Builder
Activate the web console with: systemctl enable --now cockpit.socket

node1 login:
----

我们现在可以使用 `root:eib` 凭据对登录。
如果我们更喜欢使用 SSH 登录主机，而不是此处显示的 `virsh console`，我们也可以这样做。

登录后，让我们确认所有设置均已就绪。

验证主机名是否设置正确：

[,shell]
----
node1:~ # hostnamectl
 Static hostname: node1.suse.com
 ...
----

验证路由配置是否正确：

[,shell]
----
node1:~ # ip r
default via 192.168.122.1 dev eth0 proto static metric 100
192.168.122.0/24 dev eth0 proto static scope link metric 100
192.168.122.0/24 dev eth0 proto kernel scope link src 192.168.122.50 metric 100
----

验证互联网连接是否可用：

[,shell]
----
node1:~ # ping google.com
PING google.com (142.250.72.78) 56(84) bytes of data.
64 bytes from den16s09-in-f14.1e100.net (142.250.72.78): icmp_seq=1 ttl=56 time=13.2 ms
64 bytes from den16s09-in-f14.1e100.net (142.250.72.78): icmp_seq=2 ttl=56 time=13.4 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 13.248/13.304/13.361/0.056 ms
----

验证是否配置了恰好两个以太网接口，且其中只有一个处于活动状态：

[,shell]
----
node1:~ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 34:8a:b1:4b:16:e1 brd ff:ff:ff:ff:ff:ff
    altname enp0s2
    altname ens2
    inet 192.168.122.50/24 brd 192.168.122.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 34:8a:b1:4b:16:e2 brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    altname ens3

node1:~ # nmcli -f NAME,UUID,TYPE,DEVICE,FILENAME con show
NAME  UUID                                  TYPE      DEVICE  FILENAME
eth0  dfd202f5-562f-5f07-8f2a-a7717756fb70  ethernet  eth0    /etc/NetworkManager/system-connections/eth0.nmconnection
eth1  7e211aea-3d14-59cf-a4fa-be91dac5dbba  ethernet  --      /etc/NetworkManager/system-connections/eth1.nmconnection
----

您会注意到第二个接口是 `eth1`，而不是我们预期的网络状态中预定义的 `eth3`。
这是因为 NetworkManager 配置器 (_nmc_) 能够检测到操作系统为 MAC 地址为 `34:8a:b1:4b:16:e2` 的 NIC 分配了不同的名称，并相应地调整了其设置。

通过检查置备的 Combustion 阶段来验证这一点是否确实发生：

[,shell]
----
node1:~ # journalctl -u combustion | grep nmc
Apr 23 09:20:19 localhost.localdomain combustion[1360]: [2024-04-23T09:20:19Z INFO  nmc::apply_conf] Identified host: node1.suse.com
Apr 23 09:20:19 localhost.localdomain combustion[1360]: [2024-04-23T09:20:19Z INFO  nmc::apply_conf] Set hostname: node1.suse.com
Apr 23 09:20:19 localhost.localdomain combustion[1360]: [2024-04-23T09:20:19Z INFO  nmc::apply_conf] Processing interface 'eth0'...
Apr 23 09:20:19 localhost.localdomain combustion[1360]: [2024-04-23T09:20:19Z INFO  nmc::apply_conf] Processing interface 'eth3'...
Apr 23 09:20:19 localhost.localdomain combustion[1360]: [2024-04-23T09:20:19Z INFO  nmc::apply_conf] Using interface name 'eth1' instead of the preconfigured 'eth3'
Apr 23 09:20:19 localhost.localdomain combustion[1360]: [2024-04-23T09:20:19Z INFO  nmc] Successfully applied config
----

我们现在将置备其余节点，但仅展示最终配置中的差异。
您可以随意对即将置备的所有节点应用上述全部或部分检查。

==== 置备第二个节点

让我们创建虚拟机：

[,shell]
----
virt-install --name node2 --ram 10000 --vcpus 6 --disk path=node2.raw,format=raw --osinfo detect=on,name=sle-unknown --graphics none --console pty,target_type=serial --network default,mac=34:8A:B1:4B:16:E3 --network default,mac=34:8A:B1:4B:16:E4 --virt-type kvm --import
----

一旦虚拟机启动并运行，我们就可以确认该节点正在使用网络绑定。

[,shell]
----
node2:~ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master bond99 state UP group default qlen 1000
    link/ether 34:8a:b1:4b:16:e3 brd ff:ff:ff:ff:ff:ff
    altname enp0s2
    altname ens2
3: eth1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master bond99 state UP group default qlen 1000
    link/ether 34:8a:b1:4b:16:e3 brd ff:ff:ff:ff:ff:ff permaddr 34:8a:b1:4b:16:e4
    altname enp0s3
    altname ens3
4: bond99: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 34:8a:b1:4b:16:e3 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.60/24 brd 192.168.122.255 scope global noprefixroute bond99
       valid_lft forever preferred_lft forever
----

确认路由正在使用该网络绑定：

[,shell]
----
node2:~ # ip r
default via 192.168.122.1 dev bond99 proto static metric 100
192.168.122.0/24 dev bond99 proto static scope link metric 100
192.168.122.0/24 dev bond99 proto kernel scope link src 192.168.122.60 metric 300
----

确保正确使用了静态连接文件：

[,shell]
----
node2:~ # nmcli -f NAME,UUID,TYPE,DEVICE,FILENAME con show
NAME    UUID                                  TYPE      DEVICE  FILENAME
bond99  4a920503-4862-5505-80fd-4738d07f44c6  bond      bond99  /etc/NetworkManager/system-connections/bond99.nmconnection
eth0    dfd202f5-562f-5f07-8f2a-a7717756fb70  ethernet  eth0    /etc/NetworkManager/system-connections/eth0.nmconnection
eth1    0523c0a1-5f5e-5603-bcf2-68155d5d322e  ethernet  eth1    /etc/NetworkManager/system-connections/eth1.nmconnection
----

==== 配置第三个节点

让我们创建虚拟机：

[,shell]
----
virt-install --name node3 --ram 10000 --vcpus 6 --disk path=node3.raw,format=raw --osinfo detect=on,name=sle-unknown --graphics none --console pty,target_type=serial --network default,mac=34:8A:B1:4B:16:E5 --virt-type kvm --import
----

一旦虚拟机启动并运行，我们就可以确认该节点正在使用网络桥接：

[,shell]
----
node3:~ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master linux-br0 state UP group default qlen 1000
    link/ether 34:8a:b1:4b:16:e5 brd ff:ff:ff:ff:ff:ff
    altname enp0s2
    altname ens2
3: linux-br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 34:8a:b1:4b:16:e5 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.70/24 brd 192.168.122.255 scope global noprefixroute linux-br0
       valid_lft forever preferred_lft forever
----

确认路由正在使用该网桥：

[,shell]
----
node3:~ # ip r
default via 192.168.122.1 dev linux-br0 proto static metric 100
192.168.122.0/24 dev linux-br0 proto static scope link metric 100
192.168.122.0/24 dev linux-br0 proto kernel scope link src 192.168.122.70 metric 425
----

确保正确使用了静态连接文件：

[,shell]
----
node3:~ # nmcli -f NAME,UUID,TYPE,DEVICE,FILENAME con show
NAME       UUID                                  TYPE      DEVICE     FILENAME
linux-br0  1f8f1469-ed20-5f2c-bacb-a6767bee9bc0  bridge    linux-br0  /etc/NetworkManager/system-connections/linux-br0.nmconnection
eth0       dfd202f5-562f-5f07-8f2a-a7717756fb70  ethernet  eth0       /etc/NetworkManager/system-connections/eth0.nmconnection
----

==== 配置第四个节点

最后，我们将配置一个节点，该节点的 MAC 地址与任何预定义的配置均不匹配。
在这些情况下，我们将默认使用 DHCP 来配置网络接口。

让我们创建虚拟机：

[,shell]
----
virt-install --name node4 --ram 10000 --vcpus 6 --disk path=node4.raw,format=raw --osinfo detect=on,name=sle-unknown --graphics none --console pty,target_type=serial --network default --virt-type kvm --import
----

一旦虚拟机启动并运行，我们就可以确认该节点正在为其网络接口使用随机 IP 地址：

[,shell]
----
localhost:~ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:56:63:71 brd ff:ff:ff:ff:ff:ff
    altname enp0s2
    altname ens2
    inet 192.168.122.86/24 brd 192.168.122.255 scope global dynamic noprefixroute eth0
       valid_lft 3542sec preferred_lft 3542sec
    inet6 fe80::5054:ff:fe56:6371/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
----

验证 nmc 是否未能为此节点应用静态配置：

[,shell]
----
localhost:~ # journalctl -u combustion | grep nmc
Apr 23 12:15:45 localhost.localdomain combustion[1357]: [2024-04-23T12:15:45Z ERROR nmc] Applying config failed: None of the preconfigured hosts match local NICs
----

验证以太网接口是否已通过 DHCP 配置：

[,shell]
----
localhost:~ # journalctl | grep eth0
Apr 23 12:15:29 localhost.localdomain NetworkManager[704]: <info>  [1713874529.7801] manager: (eth0): new Ethernet device (/org/freedesktop/NetworkManager/Devices/2)
Apr 23 12:15:29 localhost.localdomain NetworkManager[704]: <info>  [1713874529.7802] device (eth0): state change: unmanaged -> unavailable (reason 'managed', sys-iface-state: 'external')
Apr 23 12:15:29 localhost.localdomain NetworkManager[704]: <info>  [1713874529.7929] device (eth0): carrier: link connected
Apr 23 12:15:29 localhost.localdomain NetworkManager[704]: <info>  [1713874529.7931] device (eth0): state change: unavailable -> disconnected (reason 'carrier-changed', sys-iface-state: 'managed')
Apr 23 12:15:29 localhost.localdomain NetworkManager[704]: <info>  [1713874529.7944] device (eth0): Activation: starting connection 'Wired Connection' (300ed658-08d4-4281-9f8c-d1b8882d29b9)
Apr 23 12:15:29 localhost.localdomain NetworkManager[704]: <info>  [1713874529.7945] device (eth0): state change: disconnected -> prepare (reason 'none', sys-iface-state: 'managed')
Apr 23 12:15:29 localhost.localdomain NetworkManager[704]: <info>  [1713874529.7947] device (eth0): state change: prepare -> config (reason 'none', sys-iface-state: 'managed')
Apr 23 12:15:29 localhost.localdomain NetworkManager[704]: <info>  [1713874529.7953] device (eth0): state change: config -> ip-config (reason 'none', sys-iface-state: 'managed')
Apr 23 12:15:29 localhost.localdomain NetworkManager[704]: <info>  [1713874529.7964] dhcp4 (eth0): activation: beginning transaction (timeout in 90 seconds)
Apr 23 12:15:33 localhost.localdomain NetworkManager[704]: <info>  [1713874533.1272] dhcp4 (eth0): state changed new lease, address=192.168.122.86

localhost:~ # nmcli -f NAME,UUID,TYPE,DEVICE,FILENAME con show
NAME              UUID                                  TYPE      DEVICE  FILENAME
Wired Connection  300ed658-08d4-4281-9f8c-d1b8882d29b9  ethernet  eth0    /var/run/NetworkManager/system-connections/default_connection.nmconnection
----

[#networking-unified]
=== 统一节点配置

在某些情况下，无法依赖已知的 MAC 地址。在这些情况下，我们可以选择所谓的 _统一配置_，它允许我们在 `_all.yaml` 文件中指定设置，然后将其应用于所有已配置的节点。

我们将使用不同的配置结构构建并配置边缘节点。按照从 <<image-config-dir-creation>> 到 <<default-network-definition>> 的所有步骤操作。

在此示例中，我们定义了两个以太网接口（eth0 和 eth1）的期望状态——一个使用 DHCP，另一个分配了静态 IP 地址。

[,shell]
----
mkdir -p $CONFIG_DIR/network

cat <<- EOF > $CONFIG_DIR/network/_all.yaml
interfaces:
- name: eth0
  type: ethernet
  state: up
  ipv4:
    dhcp: true
    enabled: true
  ipv6:
    enabled: false
- name: eth1
  type: ethernet
  state: up
  ipv4:
    address:
    - ip: 10.0.0.1
      prefix-length: 24
    enabled: true
    dhcp: false
  ipv6:
    enabled: false
EOF
----

让我们构建镜像：

[,shell,subs="attributes"]
----
podman run --rm -it -v $CONFIG_DIR:/eib registry.suse.com/edge/{version-edge-registry}/edge-image-builder:{version-eib} build --definition-file definition.yaml
----

镜像构建成功后，让我们使用它创建一个虚拟机：

[,shell]
----
virt-install --name node1 --ram 10000 --vcpus 6 --disk path=$CONFIG_DIR/modified-image.raw,format=raw --osinfo detect=on,name=sle-unknown --graphics none --console pty,target_type=serial --network default --network default --virt-type kvm --import
----

配置过程可能需要几分钟。完成后，使用提供的凭据登录系统。

验证路由配置是否正确：

[,shell]
----
localhost:~ # ip r
default via 192.168.122.1 dev eth0 proto dhcp src 192.168.122.100 metric 100
10.0.0.0/24 dev eth1 proto kernel scope link src 10.0.0.1 metric 101
192.168.122.0/24 dev eth0 proto kernel scope link src 192.168.122.100 metric 100
----

验证互联网连接是否可用：

[,shell]
----
localhost:~ # ping google.com
PING google.com (142.250.72.46) 56(84) bytes of data.
64 bytes from den16s08-in-f14.1e100.net (142.250.72.46): icmp_seq=1 ttl=56 time=14.3 ms
64 bytes from den16s08-in-f14.1e100.net (142.250.72.46): icmp_seq=2 ttl=56 time=14.2 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 14.196/14.260/14.324/0.064 ms
----

验证以太网接口是否已配置并处于活动状态：

[,shell]
----
localhost:~ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:26:44:7a brd ff:ff:ff:ff:ff:ff
    altname enp1s0
    inet 192.168.122.100/24 brd 192.168.122.255 scope global dynamic noprefixroute eth0
       valid_lft 3505sec preferred_lft 3505sec
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:ec:57:9e brd ff:ff:ff:ff:ff:ff
    altname enp7s0
    inet 10.0.0.1/24 brd 10.0.0.255 scope global noprefixroute eth1
       valid_lft forever preferred_lft forever

localhost:~ # nmcli -f NAME,UUID,TYPE,DEVICE,FILENAME con show
NAME  UUID                                  TYPE      DEVICE  FILENAME
eth0  dfd202f5-562f-5f07-8f2a-a7717756fb70  ethernet  eth0    /etc/NetworkManager/system-connections/eth0.nmconnection
eth1  0523c0a1-5f5e-5603-bcf2-68155d5d322e  ethernet  eth1    /etc/NetworkManager/system-connections/eth1.nmconnection

localhost:~ # cat /etc/NetworkManager/system-connections/eth0.nmconnection
[connection]
autoconnect=true
autoconnect-slaves=-1
id=eth0
interface-name=eth0
type=802-3-ethernet
uuid=dfd202f5-562f-5f07-8f2a-a7717756fb70

[ipv4]
dhcp-client-id=mac
dhcp-send-hostname=true
dhcp-timeout=2147483647
ignore-auto-dns=false
ignore-auto-routes=false
method=auto
never-default=false

[ipv6]
addr-gen-mode=0
dhcp-timeout=2147483647
method=disabled

localhost:~ # cat /etc/NetworkManager/system-connections/eth1.nmconnection
[connection]
autoconnect=true
autoconnect-slaves=-1
id=eth1
interface-name=eth1
type=802-3-ethernet
uuid=0523c0a1-5f5e-5603-bcf2-68155d5d322e

[ipv4]
address0=10.0.0.1/24
dhcp-timeout=2147483647
method=manual

[ipv6]
addr-gen-mode=0
dhcp-timeout=2147483647
method=disabled
----

=== 自定义网络配置

我们已经介绍了 Edge Image Builder 的默认网络配置，它依赖于 NetworkManager Configurator。
不过，也可以选择通过自定义脚本进行修改。虽然此选项非常灵活且不依赖于 MAC 地址，但其局限性在于，当使用单个镜像引导多个节点时，使用它会很不方便。

> NOTE: 建议通过 `/network` 目录下描述所需网络状态的文件来使用默认网络配置。
仅当该行为不适用于您的用例时，才选择自定义脚本。

我们将使用不同的配置结构构建并配置边缘节点。按照从 <<image-config-dir-creation>> 到 <<default-network-definition>> 的所有步骤操作。

在此示例中，我们将创建一个自定义脚本，为所有已配置节点上的 `eth0` 接口应用静态配置，并删除和禁用 NetworkManager 自动创建的有线连接。这在您希望确保集群中的每个节点都具有相同网络配置的情况下非常有用，因此您无需在创建镜像之前关注每个节点的 MAC 地址。

让我们首先将连接文件存储在 `/custom/files` 目录中：

[,shell]
----
mkdir -p $CONFIG_DIR/custom/files

cat << EOF > $CONFIG_DIR/custom/files/eth0.nmconnection
[connection]
autoconnect=true
autoconnect-slaves=-1
autoconnect-retries=1
id=eth0
interface-name=eth0
type=802-3-ethernet
uuid=dfd202f5-562f-5f07-8f2a-a7717756fb70
wait-device-timeout=60000

[ipv4]
dhcp-timeout=2147483647
method=auto

[ipv6]
addr-gen-mode=eui64
dhcp-timeout=2147483647
method=disabled
EOF
----

现在静态配置已创建，我们还将创建自定义网络脚本：

[,shell]
----
mkdir -p $CONFIG_DIR/network

cat << EOF > $CONFIG_DIR/network/configure-network.sh
#!/bin/bash
set -eux

# Remove and disable wired connections
mkdir -p /etc/NetworkManager/conf.d/
printf "[main]\nno-auto-default=*\n" > /etc/NetworkManager/conf.d/no-auto-default.conf
rm -f /var/run/NetworkManager/system-connections/* || true

# Copy pre-configured network configuration files into NetworkManager
mkdir -p /etc/NetworkManager/system-connections/
cp eth0.nmconnection /etc/NetworkManager/system-connections/
chmod 600 /etc/NetworkManager/system-connections/*.nmconnection
EOF

chmod a+x $CONFIG_DIR/network/configure-network.sh
----

> NOTE: nmc 二进制文件仍将默认包含，因此如有必要，它也可以在 `configure-network.sh` 脚本中使用。

[WARNING]
====
自定义脚本必须始终放置在配置目录下的 `/network/configure-network.sh` 中。如果存在，所有其他文件都将被忽略。
无法同时使用 YAML 格式的静态配置和自定义脚本来配置网络。
====

此时，配置目录应如下所示：

[,console,subs="attributes"]
----
├── definition.yaml
├── custom/
│   └── files/
│       └── eth0.nmconnection
├── network/
│   └── configure-network.sh
└── base-images/
    └── {micro-base-image-raw}
----

让我们构建镜像：

[,shell,subs="attributes"]
----
podman run --rm -it -v $CONFIG_DIR:/eib registry.suse.com/edge/{version-edge-registry}/edge-image-builder:{version-eib} build --definition-file definition.yaml
----

镜像构建成功后，让我们使用它创建一个虚拟机：

[,shell]
----
virt-install --name node1 --ram 10000 --vcpus 6 --disk path=$CONFIG_DIR/modified-image.raw,format=raw --osinfo detect=on,name=sle-unknown --graphics none --console pty,target_type=serial --network default --virt-type kvm --import
----

配置过程可能需要几分钟。完成后，使用提供的凭据登录系统。

验证路由配置是否正确：

[,shell]
----
localhost:~ # ip r
default via 192.168.122.1 dev eth0 proto dhcp src 192.168.122.185 metric 100
192.168.122.0/24 dev eth0 proto kernel scope link src 192.168.122.185 metric 100
----

验证互联网连接是否可用：

[,shell]
----
localhost:~ # ping google.com
PING google.com (142.250.72.78) 56(84) bytes of data.
64 bytes from den16s09-in-f14.1e100.net (142.250.72.78): icmp_seq=1 ttl=56 time=13.6 ms
64 bytes from den16s09-in-f14.1e100.net (142.250.72.78): icmp_seq=2 ttl=56 time=13.6 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 13.592/13.599/13.606/0.007 ms
----

验证以太网接口是否使用我们的连接文件进行了静态配置且处于活动状态：

[,shell]
----
localhost:~ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:31:d0:1b brd ff:ff:ff:ff:ff:ff
    altname enp0s2
    altname ens2
    inet 192.168.122.185/24 brd 192.168.122.255 scope global dynamic noprefixroute eth0

localhost:~ # nmcli -f NAME,UUID,TYPE,DEVICE,FILENAME con show
NAME  UUID                                  TYPE      DEVICE  FILENAME
eth0  dfd202f5-562f-5f07-8f2a-a7717756fb70  ethernet  eth0    /etc/NetworkManager/system-connections/eth0.nmconnection

localhost:~ # cat  /etc/NetworkManager/system-connections/eth0.nmconnection
[connection]
autoconnect=true
autoconnect-slaves=-1
autoconnect-retries=1
id=eth0
interface-name=eth0
type=802-3-ethernet
uuid=dfd202f5-562f-5f07-8f2a-a7717756fb70
wait-device-timeout=60000

[ipv4]
dhcp-timeout=2147483647
method=auto

[ipv6]
addr-gen-mode=eui64
dhcp-timeout=2147483647
method=disabled
----
