[#components-rancher]
= Rancher
:revdate: 2025-06-10
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


请参阅 https://ranchermanager.docs.rancher.com/{rancher-docs-version}. 处的 Rancher 文档

[quote]
____
Rancher 是一个功能强大的开源 Kubernetes 管理平台，可简化跨多个环境的 Kubernetes 集群的部署、操作和监控。无论您是在本地、云端还是边缘管理集群，Rancher 都能为您所有的 Kubernetes 需求提供一个统一且集中的平台。
____


== Rancher 的主要功能

* **多集群管理：**Rancher 直观的界面让您可以从任何地方（公有云、私有数据中心和边缘位置）管理 Kubernetes 集群。
* **安全和合规性：**Rancher 在您的 Kubernetes 环境中强制执行安全策略、基于角色的访问控制 (RBAC) 和合规性标准。
* **简化的集群操作：**Rancher 自动执行集群配置、升级和故障排除，从而简化了各种规模团队的 Kubernetes 操作。
* **集中式应用程序目录：**Rancher 应用程序目录提供了多种 Helm Chart 和 Kubernetes Operator，使部署和管理容器化应用程序变得简单。
* **持续交付：**Rancher 支持 GitOps 和 CI/CD 流水线，实现自动化和简化的应用程序交付流程。

== Rancher 在 {product} 中的使用

Rancher 为 {product} 堆栈提供了多项核心功能：

=== 集中式 Kubernetes 管理

在具有大量分布式集群的典型边缘部署中，Rancher 充当管理这些 Kubernetes 集群的中央控制平面。它提供了一个用于配置、升级、监控和故障排除的统一界面，从而简化操作并确保一致性。

=== 简化的集群部署

Rancher 简化了轻量级 SUSE Linux Micro 操作系统上的 Kubernetes 集群创建，通过强大的 Kubernetes 功能轻松实现边缘基础设施的部署。

=== 应用程序部署和管理

集成的 Rancher 应用程序目录可以简化跨 {product} 集群部署和管理容器化应用程序的过程，从而实现无缝的边缘工作负载部署。

=== 安全与策略执行

Rancher 提供基于策略的治理工具、基于角色的访问控制 (RBAC) 以及与外部身份验证提供程序的集成。这有助于 {product} 部署保持安全性和合规性，这在分布式环境中至关重要。

== 最佳实践

=== GitOps

Rancher 将 Fleet 作为内置组件包含在内，允许使用存储在 git 中的代码来管理集群配置和应用程序部署。

=== 可观测性

Rancher 包含内置的监控和日志记录工具（如 Prometheus 和 Grafana），可全面了解集群的健康状况和性能。

== 使用 Edge Image Builder 进行安装

{product} 正在使用 <<components-eib>> 来定制基础 SUSE Linux Micro 操作系统镜像。
请遵循 <<rancher-install>> 以在 EIB 配置的 Kubernetes 集群之上进行 Rancher 的隔离的安装。

== 其他资源

* https://rancher.com/docs/[Rancher 文档]
* https://www.rancher.academy/[Rancher 学院]
* https://rancher.com/community/[Rancher 社区]
* https://helm.sh/[Helm Charts]
* https://operatorhub.io/[Kubernetes Operators]
