[#tips-edge-image-builder]
= Edge Image Builder
:revdate: 26/03/2025
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


== Común

- Si se encuentra en un entorno que no es Linux y sigue estas instrucciones para crear una imagen, es probable que esté ejecutando `Podman` a través de una máquina virtual. Por defecto, esta máquina virtual estará configurada para tener una pequeña cantidad de recursos del sistema asignados y puede causar inestabilidad en `Edge Image Builder` durante operaciones que consumen muchos recursos, como el proceso de resolución de RPM. Tendrá que ajustar los recursos de la máquina Podman, ya sea utilizando Podman Desktop (rueda dentada de ajustes -> icono de edición de máquina Podman) o directamente a través del `podman-machine-set` https://docs.podman.io/en/stable/markdown/podman-machine-set.1.html[comando].
- En este momento, `Edge Image Builder` no es capaz de crear imágenes en una configuración de arquitectura cruzada, es decir, tiene que ejecutarlo en:
  * {aarch64}sistemas (como Apple Silicon) para crear imágenes de SL Micro `aarch64`
  * {x86-64}sistemas para crear imágenes de SL Micro `x86_64`.

== SUSE Linux Micro

- La carga de módulos del kernel durante el arranque puede realizarse utilizando el archivo `/etc/modprobe.d/module.conf` correspondiente. Cree la carpeta `os-files` correspondiente utilizando Edge Image Builder:

[,console]
----
.
├── definition.yaml
└── os-files
    └── etc
        └── modprobe.d
            └── module.conf
----

Para obtener más información, consulte la https://documentation.suse.com/sles/15-SP7/html/SLES-all/cha-mod.html#sec-mod-modprobe-d[sección «Managing kernel modules» de la documentación de SUSE Linux Enterprise Server]

== Kubernetes

- La creación de clústeres de Kubernetes de varios nodos requiere ajustar `kubernetes` la sección en el archivo de definición a:
  * listar todos los nodos de servidor y agente bajo `kubernetes.nodes` 
  * establecer una dirección IP virtual que se utilizaría para que todos los nodos que no sean inicializadores se unan al clúster bajo `kubernetes.network.apiVIP`
  * opcionalmente, establecer un host de API para especificar una dirección de dominio para acceder al clúster bajo `kubernetes.network.apiHost`
Para obtener más información sobre esta configuración, consulte la https://github.com/suse-edge/edge-image-builder/blob/main/docs/building-images.md#kubernetes[documentación de la sección de Kubernetes].


- `Edge Image Builder` depende de los nombres de host de los diferentes nodos para determinar su tipo de Kubernetes (`server` o `agent`). Aunque esta configuración se gestiona en el archivo de definición, para la configuración de red general de las máquinas podemos utilizar la configuración DHCP tal y como se describe en <<components-nmc>>.
