[#collecting-diagnostics-for-support]
== Collecting Diagnostics for Support
:revdate: 2025-06-17
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

include::../edge-book/versions.adoc[]

When contacting SUSE Support, providing comprehensive diagnostic information is crucial.

.Essential Information to Collect

* *Detailed problem description*: What happened, when did it happen, what were you doing, what is the expected behavior, and what is the actual behavior?
* *Steps to reproduce*: Can you reliably reproduce the issue? If so, list the exact steps.
* *Component versions*: SUSE Edge version, components versions (RKE2/K3, EIB, Metal^3^, Elemental,..).
* *Relevant logs*: 
** `journalctl` output (filtered by service if possible, or full boot logs).
** Kubernetes pod logs (kubectl logs).
** Metal³/Elemental component logs.
** EIB build logs and other logs
* *System information*:
** `uname -a`
** `df -h`
** `ip a`
** `/etc/os-release`
* *Configuration files*: Relevant configuration files for Elemental, Metal^3^, EIB such as helm chart values, configmaps, etc.
* *Kubernetes information*: Nodes, Services, Deployments, etc.
* *Kubernetes objects affected*: BMH, MachineRegistration, etc.

.How to collect

* *For logs*: Redirect command output to files (for example, `journalctl -u k3s > k3s_logs.txt`).
* *For Kubernetes resources*: Use `kubectl get <resource> -o yaml > <resource_name>.yaml` to get detailed YAML definitions.
* *For system information*: Collect output of the commands listed above.
* *For SL Micro*: Check the https://documentation.suse.com/sle-micro/5.5/html/SLE-Micro-all/cha-adm-support-slemicro.html[SUSE Linux Micro Troubleshooting Guide] documentation on how to gather system information for support with `supportconfig`.
* *For RKE2/Rancher*: Check the https://www.suse.com/support/kb/doc/?id=000020191[The Rancher v2.x Linux log collector script] article to run The Rancher v2.x Linux log collector script.

* *For Edge (Nessie)*: Nessie {version-nessie} is a powerful diagnostic tool designed to collect logs and configuration data from SUSE Edge environments. It gathers comprehensive information from both the host system and Kubernetes clusters, making it invaluable for troubleshooting and support. 
** Nessie has two "modes" a kubernetes mode and a system mode.
*** To collect logs from a SUSE Edge cluster, run (provided that you have access to the kubeconfig file locally):
+
[,bash,subs="attributes"]
----
podman run --rm --privileged \
  -v /etc/rancher/k3s/k3s.yaml:/etc/rancher/k3s/k3s.yaml:ro \
  -v /var/log/journal:/var/log/journal:ro \
  -v /run/systemd:/run/systemd:ro \
  -v /etc/machine-id:/etc/machine-id:ro \
  -v /tmp:/tmp \
  -e NESSIE_LOG_DIR="/tmp" \
  -e NESSIE_ZIP_DIR="/tmp" \
  registry.suse.com/edge/{version-edge}/nessie:{version-nessie}
----
+
[NOTE]
====
Adjust the paths of the `k3s.yaml/rke2.yaml` file if needed. See https://github.com/suse-edge/support-tools/blob/main/nessie/README.md[Nessie] for more information.
You should be able to run this container in non-privileged mode if you have proper permissions (typically `k3s.yaml` / `rke2-server.yaml` files are owned by root).
====
*** To collect logs in the system mode from the actual operating system, run:
+
[,bash,subs="attributes"]
----
podman run --rm --privileged \
  -v /var/log/journal:/var/log/journal:ro \
  -v /run/systemd:/run/systemd:ro \
  -v /etc/machine-id:/etc/machine-id:ro \
  -v /tmp:/tmp \
  -e NESSIE_LOG_DIR="/tmp" \
  -e NESSIE_ZIP_DIR="/tmp" \
  -e NESSIE_VERBOSE="1" \
  -e NESSIE_SKIP_POD_LOGS="true" \
  -e NESSIE_SKIP_K8S_CONFIGS="true" \
  -e NESSIE_SKIP_METRICS="true" \
  registry.suse.com/edge/{version-edge}/nessie:{version-nessie}
----
+
[NOTE]
====
Please make sure to check https://github.com/suse-edge/support-tools/blob/main/nessie/README.md[Nessie] for more details and information on how to run Nessie in your environment.
Likewise, you should be able to run this container in non-privileged mode provided you have proper permissions.
====


.Contact Support
Please check the article available at https://www.suse.com/support/kb/doc/?id=000019452[How-to effectively work with SUSE Technical Support] and the support handbook located at https://www.suse.com/support/handbook/[SUSE Technical Support Handbook] for more details on how to contact SUSE support.
