[#troubleshooting-kiwi]
== Troubleshooting Kiwi
:revdate: 2025-06-17
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Kiwi is used to generate updated SUSE Linux Micro images to be used with Edge Image Builder.

.Common Issues

* *SL Micro Version Mismatch*: The build host operating system version must match the operating system version being built (SL Micro 6.0 host -> SL Micro 6.0 image).
* *SELinux in Enforcing State*: Due to certain limitations, it is currently required to disable SELinux temporarily to be able to build images with Kiwi. Check the SElinux status with `getenforce` and disable it before running the build process with `setenforce 0`.
* *Build host not registered*: The build process uses the build host subscriptions to be able to pull packages from SUSE SCC. If the host is not registered it fails.
* *Loop Device Test Failure*: The first time that the Kiwi build process is executed, it will fail shortly after starting with "ERROR: Early loop device test failed, please retry the container run.", this is a symptom of loop devices being created on the underlying host system that are not immediately visible inside of the container image. Re-run the Kiwi build process again and it should proceed without issue.
* *Missing Permissions*: The build process expects to be run as root user (or via sudo).
* *Wrong Privileges*: The build process expects the `--privileged` flag when running the container. Double-check that it is present.

.Logs

* *Build container logs*: Check the logs of the build container. The logs are generated in the directory that was used to store the artifacts. Check docker logs or podman logs for the necessary information as well.
* *Temporary build directories*: Kiwi creates temporary directories during the build process. Check these for intermediate logs or artifacts if the main output is insufficient.

.Troubleshooting steps

. *Review `build-image` output*: The error message in the console output is usually very indicative.
. *Check build environment*: Ensure all prerequisites for Kiwi itself (for example, docker/podman, SElinux, sufficient disk space) are met on the machine running Kiwi.
. *Inspect build container logs*: Review the logs of the failed container for more detailed errors (see above).
. *Verify definition file*: If you are using  a custom Kiwi image definition file, double-check the file for any typos or syntax.

[NOTE]
====
Check the https://documentation.suse.com/appliance/kiwi-9/html/kiwi/troubleshooting.html[Kiwi Troubleshooting Guide].
====
