[#troubleshooting-phone-home-scenarios]
== Troubleshooting Phone-Home scenarios
:revdate: 2025-06-17
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Phone-home scenarios involve using Elemental to connect back to the Management cluster and EIB to create an OS image including the elemental-registration bits. Issues can happen when the host is being booted for the first time, during the EIB build process or trying to register to the Management cluster.

.Common Issues

* *System fails to register*: Node not being registered in the UI. Ensure the host is booted properly and, is able to communicate back to Rancher, clock is in sync and the Elemental services are ok.
* *System fails to be provisioned*: Node is registered but it fails to be provisioned. Ensure the host is able to communicate back to Rancher, clock is in sync and the Elemental services are ok.


.Logs

* *System logs*: `journalctl`
* *Elemental-system-agent  logs*: `journalctl -u elemental-system-agent`
* *K3s/RKE2 logs*: `journalctl -u k3s or journalctl -u rke2-server` (or `rke2-agent`)
* *Elemental operator pod*: `kubectl logs -n cattle-elemental-system -l app=elemental-operator` 

.Troubleshooting steps

. *Review logs*: Check Elemental operator pod logs to see if there are any issues. Check the host logs if the node is booted.

. *Check MachineRegistration and TPM*: By default, TPM is used for https://elemental.docs.rancher.com/authentication/[authentication] but there are alternatives for hosts without TPM.

