[#atip]
= SUSE Telco Cloud
:revdate: 2025-08-25
:revnumber: 3,6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc: preamble

== Descripción general

SUSE Telco Cloud (anteriormente conocido como {product} for Telco) es una plataforma informática optimizada para telecomunicaciones que permite a los operadores de telecomunicaciones y a los proveedores de redes de telecomunicaciones innovar y acelerar la modernización de sus redes.

SUSE Telco Cloud es una pila nativa de nube completa habilitada para telecomunicaciones para alojar CNFs, que cubre todos los dominios de telecomunicaciones: Packet Core, RAN, OSS y BSS.

- Automatiza el despliegue zero-touch y la gestión del ciclo de vida de configuraciones complejas de pila edge a escala de telecomunicaciones.
- Garantiza continuamente la calidad en hardware de grado de telecomunicaciones, utilizando configuraciones y cargas de trabajo específicas para telecomunicaciones.
- Consta de componentes diseñados específicamente para el edge y, por tanto, tienen una menor huella y un mayor rendimiento por vatio.
- Mantiene una estrategia de plataforma flexible con API independientes del proveedor y 100% de código abierto.
