= SUSE Edgeドキュメント
:revdate: 2024-03-06
:revnumber: 3.6
:page-revdate: {revdate}

ifdef::env-github[]
:imagesdir: images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

SUSE Edge ドキュメントリポジトリへようこそ。

== Asciidoctor と Markdown の比較

* https://docs.asciidoctor.org/asciidoc/latest/asciidoc-vs-markdown/#comparison-by-example[例による比較]

== Asciidoctor リソース

公式ドキュメント::
* https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/[クイックリファレンス]
* https://github.com/uyuni-project/uyuni-docs/wiki/asciidoc-getting-started[はじめに]
* https://github.com/powerman/asciidoc-cheatsheet[チートシート]
* https://docs.asciidoctor.org/asciidoc/latest/[Asciidoc言語ドキュメント]

例（コードについては`raw`バージョンを参照）::
* https://github.com/openSUSE/daps/blob/main/test/documents/adoc/part_inlines.adoc[インライン要素]
* https://github.com/openSUSE/daps/blob/main/test/documents/adoc/part_block.adoc[ブロック要素]


== 編集とプレビュー

ドキュメントはAsciidoc(tor)で記述されています。非常に基本的なlink:template.adoc[テンプレート]から始めます。

* ソースはGitHubで直接編集およびプレビューできます。
* ドキュメントをローカルで編集する場合
** https://docs.asciidoctor.org/asciidoctor/latest/tooling/#web-browser-add-ons-preview-only[Webブラウザ用プレビューアドオン]
** https://docs.asciidoctor.org/asciidoctor/latest/tooling/#ides-and-text-editors[IDEおよびテキストエディタ]
** emacsおよびvi用のasciidocモードもあります ;-)


== ベストプラクティス

=== 1行につき1文にします

* GitHubでの直接編集が大幅に容易になり、ソースが読みやすくなります
* エディターでソフトラップを使用してください


=== 見出しは順序通りにする必要があります

* ドキュメントは常にレベル0の見出しで開始してください
  ** レベル0の見出しは1つだけ使用してください
* 後続の見出しでレベルを飛ばすことは許可されていません

[,asciidoc]
----
= Level 0

== Level 1

=== Level 2

// ===== Level 4: Not allowed

==== Level 3

== Level 1
----


=== 自動IDは使用しないでください

Asciidoctorは、リンク先となるID/アンカーを自動的に生成します。

[,asciidoc]
.使用しない
----
== Usage
...

Refer to <<usage>> for more information. 
----

この機能の使用は推奨されません。見出しを変更するたびに、参照先も変更する必要があるためです。
代わりに明示的なID/アンカーを使用してください。

[,asciidoc]
.使用する
----
[#usage]
== Usage
...

Refer to <<usage>> for more information. 
----

=== 常にブロック区切り文字を使用してください

一部のブロック要素には、短い形式と長い形式があります。
混乱を避け、ソースの可読性を高めるために、常に長い形式を使用してください。

[,asciidoc]
.使用しない
----
NOTE: This is a note

 This is a literal block
----

[,asciidoc]
.使用する
----
[NOTE]
====
This is a note
====

....
This is a literal block
....
----

==== ネストされた構造

リスト項目内の注釈など、ネストされた構造は、プラス (`+`) 文字で連結する必要があります。

[,asciidoc]
----
* normal listitem
* lisitem with annotation
+
[NOTE]
====
note
====
+
* lisitem with two paragraphs
+
second paragraph
+
* normal listitem
----

=== キー入力、メニュー、ボタン

Asciidoctorには、キー入力、メニュー選択、ボタンクリックを表示するための3つのマクロが用意されています。

[,asciidoc]
----
Press kbd:[C] to continue or kbd:[Crtl+C] to cancel, kbd:[F1] opens the help menu.

To save the file, select menu:File[Save].
Select menu:View[Zoom > Reset] to reset the zoom level to the default setting.

Press the btn:[OK] button when you are finished.
----

[IMPORTANT]
====
この機能は、ヘッダーで属性 `:experimental:` が設定されている場合にのみ有効になります。
====

=== タブ表示

`[.tabs]`の前に区切り文字/ラベル付きリストを使用します：

[,asciidoc]
----
[.tabs]
TAB 1::
+
Content tab 1
+
TAB 2::
+
Content tab 2
----

=== インクルードステートメントは空行で区切る必要があります

インクルードステートメントの前後に必ず空行を挿入してください。


== サポートされていないAsciidocタグ

SUSEブランドのバージョンを作成する場合、以下はサポートされていません。
以下は使用しないでください：

* ハイライト、下線、取り消し線
+
[,asciidoc]
----
#highlight#
##high##light
[.underline]#underline#
[.line-through]#strike-through#
----
+
* チェックリスト
+
[,asciidoc]
----
* [*] checked
* [x] also checked
* [ ] not checked
----
+
* オーディオおよびビデオ
+
[,asciidoc]
----
audio::audio.wav[]
video:: video.mp4[]
----
+
* sidebars
+
[,asciidoc]
----
****
Sidebar text
****
----
+
* 脚注
+
[,asciidoc]
----
footnote:[Footnote]
----

== ドキュメントの構築 

=== 汎用バージョンの構築

SUSEブランドではないバージョンで書籍を構築する方が、SUSEブランドのバージョンを構築するよりも簡単で迅速です。

ブラウザー拡張機能（最も簡単な方法）::
+
* https://docs.asciidoctor.org/asciidoctor/latest/tooling/#web-browser-add-ons-preview-only[ブラウザー拡張機能]をインストールし、ブラウザーで edge-book/edge.adoc をプレビューします。
* プレビューは、変更が保存されると自動的に更新されます。
+
ローカルHTMLビルド::
+
* システムにasciidoctorをインストールします。
* GitHubチェックアウトで次のコマンドを実行します。
+
[,bash]
----
asciidoctor -d book --attribute="toc=left" edge-book/edge.adoc
----
+
* 結果: `edge-book/edge.html`


=== SUSEブランドバージョンのローカルビルド

公開される形式でドキュメントをローカルでビルドするには、 https://github.com/openSUSE/daps2docker[daps2docker]を使用します。なお、コントリビューションを確認するためにこれらのビルドを行う必要はありません。
プレビューでドキュメントが正常にレンダリングされる限り、問題ありません。


.要件
* ワークステーションでdockerまたはpodmanが実行されていることを確認してください。
* ユーザーがコンテナを起動できることを確認してください。
* install daps2docker from https://download.opensuse.org/repositories/Documentation:/Tools/
* このリポジトリのローカルチェックアウトのドキュメントディレクトリに移動します。

HTMLのビルド::
`daps2docker DC-edge html`
シングルHTMLのビルド::
`daps2docker DC-edge single-html`
PDFのビルド::
`daps2docker DC-edge pdf`

[TIP]
.Podmanの使用
====
デフォルトでは、daps2dockerはコンテナエンジンとしてdockerを使用します。
Podmanを使用するには、環境変数CONTAINER_ENGINE=podmanをエクスポートします: `export CONTAINER_ENGINE=podman`
====

[TIP]
.ビルドエラー
====
daps2dockerは、DocBook XMLソースからドキュメントをビルドします。
Asciidoctorには、DocBookへのビルトインコンバーターが付属しています。

Asciidoc(tor)は、検証に関してはDocBookよりもはるかに寛容です。
場合によっては、有効なAsciiDocソースコードであっても、DocBookに変換する際に検証エラーが発生することがあります。
そのような場合、daps2dockerを使用したビルドは失敗します。
その場合は、私（@fsundermeyer）までご連絡いただければ、サポートいたします。
====

=== 詳細情報

... https://github.com/openSUSE/daps2docker[daps2dockerリポジトリ]を参照してください。
また、他のディストリビューションへのインストール方法や、カスタム設定の方法に関する手順も記載されています。

