[#components-eib]
= Edge Image Builder
:revdate: 2025-08-07
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:


ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://github.com/suse-edge/edge-image-builder[公式リポジトリ]を参照してください。
 

Edge Image Builder (EIB) は、マシンの起動用に、カスタマイズされた起動可能（CRB）ディスクイメージの生成を効率化するツールです。これらのイメージにより、単一のイメージでSUSEソフトウェアスタック全体の包括的なデプロイメントが可能になります。

EIBはすべてのプロビジョニングシナリオに対応するCRBイメージを作成できますが、ネットワークが制限されている、または完全に隔離されたエアギャップ(された)環境でのデプロイメントにおいて、EIBは非常に大きな価値を発揮します。


== {product}はどのようにEdge Image Builderを使用しますか？

{product}は、さまざまなシナリオに対応するカスタマイズされたSUSE Linux Microイメージを簡素かつ迅速に構成するためにEIBを使用します。これらのシナリオには、以下のような仮想マシンおよびベアメタルマシンのブートストラップが含まれます。

* K3s/RKE2 Kubernetesの完全なエアギャップ(された)環境でのデプロイメント（シングルおよびマルチノード）
* HelmチャートおよびKubernetesマニフェストの完全なエアギャップ(された)環境でのデプロイメント
* Elemental API経由でのRancherへの登録
* Metal^3^
* カスタマイズされたネットワーク（例：静的IP、ホスト名、VLAN、ボンディングなど）
* カスタマイズされたオペレーティングシステムの構成（例：ユーザー、グループ、パスワード、SSHキー、プロキシ、NTP、カスタムSSL証明書など）
* ホストレベルおよびサイドロードされたRPMパッケージのエアギャップ(された)環境でのインストール（依存関係の解決を含む）
* OS管理のためのSUSE Multi-Linux Managerへの登録
* 組み込みコンテナイメージ
* カーネルのコマンドライン引数
* 起動時に有効/無効にするSystemdユニット
* 手動タスク用のカスタムスクリプトおよびファイル

== はじめに

Edge Image Builderの使用方法とテストに関する包括的なドキュメントは、{link-eib-docs}[こちら]にあります。

さらに、基本的なデプロイメントシナリオを網羅した<<quickstart-eib>>も参照してください。

このツールに慣れましたら、<<tips-and-tricks,EIBのヒントとコツのセクション>>ページで、さらに役立つ情報をご覧ください。

== 当バージョンの注意事項

* EIBは、Helmチャートをテンプレート化し、テンプレート内のすべてのイメージを解析することで、Helmチャートに対してエアギャップ処理を施します。Helmチャートがすべてのイメージをテンプレート内に保持せず、代わりにイメージをサイドロードする場合、EIBはそれらのイメージを自動的にエアギャップすることはできません。この解決策として、検出されなかったイメージを定義ファイルの`embeddedArtifactRegistry`セクションに手動で追加してください。
