[#components-elemental]
= Elemental
:revdate: 2025-01-16
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Elementalは、Kubernetesによる完全なクラウドネイティブOSの一元管理を可能にするソフトウェアスタックです。Elementalスタックは、Rancher自体またはエッジノードのいずれかに存在する多数のコンポーネントで構成されています。主要コンポーネントは以下の通りです。

* *elemental-operator* - Rancher上に存在し、クライアントからの登録要求を処理するコアオペレーターです。
* *elemental-register* - エッジノード上で実行され、`elemental-operator`を介した登録を可能にするクライアントです。
* *elemental-system-agent* - エッジノード上に存在するエージェントです。その設定は`elemental-register`から供給され、`rancher-system-agent`を設定するための`plan`を受け取ります。
* *rancher-system-agent* - エッジノードが完全に登録されると、これが`elemental-system-agent`から引き継ぎ、Rancher Managerからのさらなる`plans`（Kubernetesインストールなど）を待機します。

ElementalとRancherとの関係に関する詳細については、 https://elemental.docs.rancher.com/[Elementalアップストリームドキュメント]を参照してください。

== {product}はどのようにElementalを使用しますか？

私たちは、Metal^3^が選択肢にない場合（例えば、BMCがない、またはデバイスがNATゲートウェイの背後にある場合など）に、リモートデバイスを管理するためにElementalの一部を使用しています。このツールにより、オペレーターは、デバイスの出荷先や出荷時期が不明な段階でも、ラボでデバイスを起動できます。具体的には、`elemental-register`および`elemental-system-agent`コンポーネントを活用して、「phone home」ネットワークプロビジョニングのユースケース向けに、SUSE Linux MicroホストをRancherにオンボーディングできるようにしています。Edge Image Builder (EIB) を使用してデプロイメントイメージを作成する場合、EIBの設定ディレクトリに登録構成を指定することで、Elementalを介したRancherによる自動登録を実現できます。

NOTE: {product} {version-edge}では、Elementalのオペレーティングシステム管理の側面は活用して*いない*ため、Rancherを介してオペレーティングシステムのパッチ適用を管理することはできません。デプロイメントイメージの構築にElementalツールを使用する代わりに、{product}はEdge Image Builderツールを使用し、登録設定を取り込みます。

== ベストプラクティス

=== インストールメディア

「phone homeネットワークプロビジョニング」デプロイメントフットプリントにおいて、Rancherへの登録にElementalを活用できるデプロイメントイメージを構築する{product}推奨の方法は、<<quickstart-elemental,Elementalを使用したリモートホストのオンボーディング>>クイックスタートで詳述されている手順に従うことです。

=== ラベル

Elementalは`MachineInventory` CRDでインベントリを追跡し、ラベルに基づいてKubernetesクラスターをデプロイするマシンを選択するなど、インベントリを選択する方法を提供します。これにより、ユーザーはハードウェアを購入する前であっても、インフラストラクチャのニーズのほとんど（すべてではないにしても）を事前に定義できるようになります。また、ノードはそれぞれのインベントリオブジェクトでラベルを追加/削除できるため（追加のフラグ`--label "FOO=BAR"`を指定して`elemental-register`を再実行することで）、ノードがどこで起動されたかを検出し、Rancherに通知するスクリプトを作成できます。

== 当バージョンの注意事項

* Elemental UIは現在、インストールメディアの構築や、「Elemental Teal」以外のオペレーティングシステムを更新する方法を認識していません。これについては、将来のリリースで対処される予定です。
