[#components-eco]
= Endpoint Copier Operator
:revdate: 2025-02-28
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:


ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://github.com/suse-edge/endpoint-copier-operator[Endpoint Copier Operator]は、KubernetesのServiceとEndpointのコピーを作成し、それらをsyncし続けることを目的としたKubernetesオペレーターです。

== {product}はどのようにEndpoint Copier Operatorを使用しますか？

{product}において、Endpoint Copier OperatorはK3s/RKE2クラスターの高可用性（HA）セットアップを実現する上で重要な役割を果たします。これは、タイプ`kubernetes-vip`の`LoadBalancer`サービスを作成し、そのEndpointがKubernetesのEndpointと常に同期されるようにすることで実現されます。<<components-metallb,MetalLB>>は`kubernetes-vip`サービスの管理に活用されており、公開されたIPアドレスは他のノードからクラスターに参加するために使用されます。

== ベストプラクティス

Endpoint Copier Operatorの使用に関する包括的なドキュメントは、 https://github.com/suse-edge/endpoint-copier-operator/blob/main/README.md[こちら]にあります。

さらに、Endpoint Copier OperatorとMetalLBを使用したK3s/RKE2 HAセットアップの実現に関する<<guides-metallb-k3s,ガイド>>も参照してください。

== 当バージョンの注意事項
現在、Endpoint Copier Operatorは1つのService/Endpointのみを扱うように制限されています。複数のService/Endpointをサポートするための機能強化が将来的に計画されています。
