[#components-k3s]
= K3s
:revdate: 2025-01-16
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:


ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://k3s.io/[K3s]は、無人環境、リソースが制限された環境、遠隔地、またはIoTアプライアンス内の本番ワークロード向けに設計された、高可用性を備えた認定Kubernetesディストリビューションです。

単一の小さなバイナリとしてパッケージ化されているため、インストールと更新が迅速かつ簡単です。

== {product}はどのようにK3sを使用しますか

K3sは、{product}スタックを支えるKubernetesディストリビューションとして使用できます。
これは、SUSE Linux Microオペレーティングシステムにインストールすることを前提としています。

{product}スタックのKubernetesディストリビューションとしてK3sを使用することは、etcdをバックエンドとして使用することが制約に合わない場合にのみ推奨されます。etcdをバックエンドとして使用できる場合は、<<components-rke2,RKE2>>を使用することをお勧めします。

== ベストプラクティス

=== インストール
{product}スタックの一部としてK3sをインストールする推奨方法は、Edge Image Builder (EIB) を使用することです。K3sをデプロイするように設定する方法の詳細については、<<components-eib,そのドキュメント>>を参照してください。

HAセットアップおよびElementalセットアップを自動的にサポートします。

=== GitOpsワークフローのためのFleet
{product}スタックは、推奨されるGitOpsツールとしてFleetを使用します。
そのインストールと使用に関する詳細については、本ドキュメントの<<components-fleet,Fleetセクション>>を参照してください。

=== ストレージ管理

K3sにはlocal-pathストレージが事前設定されており、シングルノードクラスターに適しています。
複数のノードにまたがるクラスターには、<<components-suse-storage,SUSE Storage>>の使用を推奨します。

=== 負荷分散とHA

EIBを使用してK3sをインストールした場合、この部分はすでにEIBドキュメントのHAセクションで説明されています。

それ以外の場合は、<<guides-metallb-k3s,MetalLBドキュメント>>に従ってMetalLBをインストールおよび設定する必要があります。
