[#components-metal3]
= Metal^3^
:revdate: 2024-11-20
:revnumber: 3.4
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://metal3.io/[Metal^3^]は、Kubernetes向けのベアメタルインフラストラクチャ管理機能を提供するCNCFプロジェクトです。

Metal^3^は、 https://www.dmtf.org/standards/redfish[Redfish]などの帯域外プロトコルを介した管理をサポートするベアメタルサーバーのライフサイクルを管理するための、Kubernetesネイティブなリソースを提供します。

また、広く採用されているベンダー中立のAPIを介して複数のインフラストラクチャプロバイダー間でインフラストラクチャリソースの管理を可能にする https://cluster-api.sigs.k8s.io/[Cluster API (CAPI)]の成熟したサポートも備えています。

== SUSE Edgeはどのようにベアメタル^3^を使用しますか？

この方法は、ターゲットハードウェアが帯域外管理をサポートしており、完全に自動化されたインフラストラクチャ管理フローが望まれるシナリオで役立ちます。

このメソッドは、自動化された検査、クリーニング、プロビジョニング/デプロビジョニングを含む、ベアメタルサーバーのインベントリおよび状態管理を可能にする宣言型APIを提供します。

[#known-issues-metal3]
== 当バージョンの注意事項

* アップストリームの https://github.com/metal3-io/ip-address-manager[IP Address Management controller]は、現在、当社のネットワーク構成ツールの選択と互換性がないため、サポートされていません。ただし、`ipam-controller-manager`ポッドが`metal3-ipam-system`ネームスペースでホストされている必要があります。CAPM3は`ipam` CRDの存在を要求するためです。
* 関連して、IPAMリソースおよびMetal3DataTemplateのnetworkDataフィールドはサポートされていません。
* 現在、redfish-virtualmedia経由のデプロイメントのみがサポートされています。
* ironic python agent (IPA) とターゲットオペレーティングシステム (SL Micro 6.0/6.1) の間で、特にデバイスの予測可能な名前を構成しようとする際に、ネットワークデバイス名の不一致が観察される可能性があります。

これは、ironic python agent (IPA) のカーネルが現在ターゲットオペレーティングシステム (SL Micro 6.0/6.1) のカーネルと一致していないために発生します。そのため、ネットワークドライバーに不一致が生じ、IPAがSL Microの想定とは異なる命名パターンでネットワークデバイスを検出してしまいます。

当面の回避策として、以下の2つの異なるアプローチがあります。 +
* ネットワーク構成を含む2つの異なるシークレットを作成します。1つは、IPAが検出するデバイス名を使用して、`preprovisioningNetworkDataName`を`BareMetalHost`定義として利用するシークレット、もう1つは、SL Microが検出するデバイス名を使用して、`networkData.name`を`BareMetalHost`定義として利用するシークレットです。 +
* 代わりに、UUIDを使用して、生成されたnmconnectionファイル上の他のインターフェースを参照します。
詳細は、xref:edge.adoc#tips-and-tricks[Tips and tricks]セクションを参照してください。
