[#components-metal3]
= Metal^3^
:revdate: 2024-11-20
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://metal3.io/[Metal^3^]は、Kubernetes向けのベアメタルインフラストラクチャ管理機能を提供するCNCFプロジェクトです。

Metal^3^は、 https://www.dmtf.org/standards/redfish[Redfish]などの帯域外プロトコルによる管理をサポートするベアメタルサーバーのライフサイクルを管理するための、Kubernetesネイティブなリソースを提供します。

また、 https://cluster-api.sigs.k8s.io/[Cluster API (CAPI)]に対する成熟したサポートも備えています。
これにより、広く採用されているベンダー中立のAPIを介して、複数のインフラストラクチャプロバイダー全体でハードウェアリソースを管理できるようになります。
Cluster APIは、MachineオブジェクトのインフラストラクチャバックエンドとしてMetal^3^を使用します。

== {product}はどのようにMetal^3^を使用しますか？

{product}はMetal^3^を使用して、サーバーなどの物理ハードウェアのライフサイクルを管理します。ハードウェアは、Metal^3^がサポートする帯域外管理プロトコル（Redfishなど）をサポートしている必要があります。{product}管理クラスターがダウンストリームクラスターのプロビジョニングまたはデプロビジョニングを行う際、Metal^3^はRedfishを介してサーバーのBMCと対話します。以下の操作は、通常、この対話の一部となります。 +

* 仮想メディアのマウントおよびアンマウント。
* サーバーの電源オン、電源オフ、およびリセット。

このアプローチは、ターゲットハードウェアが帯域外管理をサポートしており、完全に自動化されたインフラストラクチャ管理フローが求められるシナリオで役立ちます。

Metal^3^とCAPIは、自動化された検査、クリーニング、プロビジョニング/デプロビジョニングを含む、ベアメタルサーバーのインベントリおよび状態管理を可能にする宣言型APIを提供します。

== 当バージョンの注意事項

* アップストリームの https://github.com/metal3-io/ip-address-manager[IP Address Management controller]は、現在、当社のネットワーク構成ツールの選択と互換性がないため、サポートされていません。ただし、`ipam-controller-manager`ポッドが`metal3-ipam-system`ネームスペースでホストされている必要があります。CAPM3は`ipam` CRDの存在を要求するためです。
* 関連して、IPAMリソースおよびMetal3DataTemplateのnetworkDataフィールドはサポートされていません。
* 現在、redfish-virtualmedia経由のデプロイのみがサポートされています。
