[#components-metallb]
= MetalLB
:revdate: 2025-02-28
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://metallb.universe.tf/[MetalLB公式ドキュメント]を参照してください。

[quote]
____
MetalLBは、標準的なルーティングプロトコルを使用する、ベアメタルKubernetesクラスター向けのロードバランサー実装です。

ベアメタル環境では、ネットワークロードバランサーのセットアップはクラウド環境よりも著しく複雑です。クラウドセットアップにおける単純なAPI呼び出しとは異なり、ベアメタルでは、高可用性（HA）を管理したり、単一ノードのロードバランサーに固有の潜在的な単一障害点（SPOF）に対処したりするために、専用のネットワークアプライアンス、またはロードバランサーと仮想IP（VIP）構成の組み合わせが必要になります。これらの構成は容易に自動化できず、コンポーネントが動的にスケールアップおよびスケールダウンするKubernetesデプロイメントにおいて課題となります。

MetalLBは、Kubernetesモデルを活用して、ベアメタルセットアップであってもクラウド環境で動作しているかのように、ロードバランサー型のサービスを作成することで、これらの課題に対処します。

https://metallb.universe.tf/concepts/layer2/[L2モード]（ARP _トリック_を使用）または https://metallb.universe.tf/concepts/bgp/[BGP]を介した、2つの異なるアプローチがあります。主にL2は特別なネットワーク機器を必要としませんが、一般的にはBGPの方が優れています。ユースケースによります。
____

== {product}はどのようにMetalLBを使用しますか？

{product}はMetalLBを3つの主要な方法で使用します。

* ロードバランサーソリューションとして：MetalLBは、ベアメタルマシンのロードバランサーソリューションとして機能します。
* HA K3s/RKE2セットアップの場合：MetalLBは、仮想IPアドレスを使用してKubernetes APIの負荷分散を可能にします。
* L3 BGPソリューションとして、MetalLBはサービスIPへのルートを近隣のルーターにアドバタイズします。

[NOTE]
====
APIを公開できるようにするため、<<components-eco, Endpoint Copier Operator>>を使用し、`kubernetes`サービスから`kubernetes-vip`ロードバランサーサービスへのK8s APIエンドポイントをsyncし続けます。
====

== ベストプラクティス
L2モードでのMetalLBのインストールについては<<guides-metallb-k3s>>で、L3モードについては<<guides-metallb-k3s-l3>>で説明されています。

高可用性トポロジーを実現するために`kube-api-server`の前にMetalLBをインストールするガイドは、<<guides-metallb-kubernetes>>にあります。


== 当バージョンの注意事項

* K3sには、`Klipper`と呼ばれるロードバランサーソリューションが付属しています。MetalLBを使用するには、`Klipper`を無効にする必要があります。これは、 https://docs.k3s.io/networking[K3sドキュメント]で説明されているように、`--disable servicelb`オプションを指定してK3sサーバーを起動することで実行できます。
