[#components-rancher]
= Rancher
:revdate: 2025-06-10
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


https://ranchermanager.docs.rancher.com/{rancher-docs-version}.のRancherドキュメントを参照してください

[quote]
____
Rancherは、複数の環境にわたるKubernetesクラスタのデプロイ、運用、監視を効率化する、強力なオープンソースのKubernetes管理プラットフォームです。オンプレミス、クラウド、エッジのいずれでクラスタを管理する場合でも、RancherはすべてのKubernetesニーズに対応する統合された一元管理プラットフォームを提供します。
____


== Rancherの主な機能

* **マルチクラスタ管理:**Rancherの直感的なインターフェースにより、パブリッククラウド、プライベートデータセンター、エッジロケーションなど、どこからでもKubernetesクラスタを管理できます。
* **セキュリティとコンプライアンス:**Rancherは、Kubernetes環境全体でセキュリティポリシー、ロールベースのアクセス制御（RBAC）、およびコンプライアンス基準を適用します。
* **クラスタ運用の簡素化:**Rancherはクラスタのプロビジョニング、アップグレード、トラブルシューティングを自動化し、あらゆる規模のチームのKubernetes運用を簡素化します。
* **一元化されたアプリケーションカタログ:**Rancherのアプリケーションカタログは、多様なHelmチャートとKubernetes Operatorを提供し、コンテナ化されたアプリケーションのデプロイと管理を容易にします。
* **継続的デリバリ:**RancherはGitOpsとCI/CDパイプラインをサポートしており、自動化された効率的なアプリケーションデリバリープロセスを実現します。

== {product}におけるRancherの利用

Rancherは{product}スタックにいくつかのコア機能を提供します。

=== 一元化されたKubernetes管理

多数の分散クラスタを伴う一般的なエッジデプロイメントにおいて、RancherはこれらのKubernetesクラスタを管理するための中心的なコントロールプレーンとして機能します。プロビジョニング、アップグレード、監視、トラブルシューティングのための統合インターフェースを提供し、運用を簡素化して一貫性を確保します。

=== クラスタ展開の簡素化

Rancherは、軽量なSUSE Linux Microオペレーティングシステム上でのKubernetesクラスタ作成を効率化し、堅牢なKubernetes機能によるエッジインフラストラクチャの展開を容易にします。

=== アプリケーションの展開と管理

統合されたRancherアプリケーションカタログにより、{product}クラスタ全体でのコンテナ化されたアプリケーションの展開と管理が簡素化され、エッジワークロードのシームレスな展開が可能になります。

=== セキュリティとポリシーの適用

Rancherは、ポリシーに基づくガバナンストール、ロールベースのアクセス制御（RBAC）、および外部認証プロバイダーとの統合を提供します。これは、分散環境において不可欠な{product}デプロイメントのセキュリティとコンプライアンスを維持するのに役立ちます。

== ベストプラクティス

=== GitOps

RancherにはFleetがビルトインコンポーネントとして含まれており、Gitに保存されたコードを使用してクラスタ設定とアプリケーションのデプロイメントを管理できます。

=== 監視

Rancherには、PrometheusやGrafanaなどの監視およびログ記録ツールが組み込まれており、クラスタの健全性とパフォーマンスを包括的に把握できます。

== Edge Image Builderを使用したインストール

{product}は、SUSE Linux Micro OSのベースイメージをカスタマイズするために<<components-eib>>を使用しています。
EIBによってプロビジョニングされたKubernetesクラスタ上にRancherをエアギャップ(された)インストールするには、<<rancher-install>>に従ってください。

== その他の資料

* https://rancher.com/docs/[Rancherドキュメント]
* https://www.rancher.academy/[Rancher Academy]
* https://rancher.com/community/[Rancherコミュニティ]
* https://helm.sh/[Helmチャート]
* https://operatorhub.io/[Kubernetesオペレーター]
