[#components-rke2]
= RKE2
:revdate: 2025-05-01
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://docs.rke2.io/[RKE2公式ドキュメント]を参照してください。

RKE2は、以下によってセキュリティとコンプライアンスに重点を置いた、完全に準拠したKubernetesディストリビューションです。

* クラスタが最小限のオペレータの介入でCIS Kubernetesベンチマークv1.6またはv1.23に合格できるようにするデフォルトと設定オプションを提供すること
* FIPS 140-2コンプライアンスを有効にすること
* RKE2ビルドパイプラインで https://trivy.dev[trivy]を使用して、コンポーネントのCVEを定期的にスキャンすること

RKE2は、コントロールプレーンのコンポーネントをkubeletによって管理される静的ポッドとして起動します。組み込みのコンテナランタイムはcontainerdです。

注意:RKE2は、現在ターゲットとしている別のユースケースとセクターを伝えるために、RKE Governmentとしても知られています。

== RKE2とK3sの比較

K3sは、エッジ、IoT、ARMに焦点を当てた、完全に準拠した軽量なKubernetesディストリビューションであり、使いやすさとリソースが制限された環境向けに最適化されています。

RKE2は、RKEの1.xバージョン（以下、RKE1と呼びます）とK3sの両方の長所を兼ね備えています。

K3sからは、そのユーザビリティ、運用の容易さ、デプロイモデルを継承しています。

RKE1からは、アップストリームのKubernetesとの密接な整合性を継承しています。K3sは、エッジデプロイメント向けに最適化するため、アップストリーム Kubernetes から一部乖離していますが、RKE1 と RKE2 はアップストリームと密接に整合性を保つことができます。

== {product}はどのようにRKE2を使用していますか？

RKE2は{product}スタックの基本的な構成要素です。これは<<components-slmicro,SUSE Linux Micro>>の上で動作し、エッジワークロードのデプロイに必要な標準的なKubernetesインターフェースを提供します。

== ベストプラクティス

=== インストール

{product}スタックの一部としてRKE2をインストールする推奨方法は、Edge Image Builder（EIB）を使用することです。RKE2をデプロイするための設定方法の詳細については、<<components-eib,EIBドキュメント>>を参照してください。

EIBは、RKE2のバージョン指定、 https://docs.rke2.io/reference/server_config[サーバー]や https://docs.rke2.io/reference/linux_agent_config[エージェント]の設定など、RKE2が必要とするあらゆるパラメータをサポートする柔軟性を備えており、すべてのエッジユースケースをカバーします。

ifeval::["{flavor}" == "telco"]
Metal^3^に関連するその他のユースケースにおいても、RKE2が使用およびインストールされています。それらの特定のケースでは、 https://github.com/rancher-sandbox/cluster-api-provider-rke2[Cluster API Provider RKE2]が、Edge Stackを使用してMetal^3^でプロビジョニングされるクラスター上にRKE2を自動的にデプロイします。

それらのケースでは、関連するさまざまなCRDにRKE2設定を適用する必要があります。`RKE2ControlPlane` CRDを使用して異なるCNIを提供する方法の例を以下に示します。

[,yaml]
----
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: RKE2ControlPlane
metadata:
  name: single-node-cluster
  namespace: default
spec:
  serverConfig:
    cni: calico
    cniMultusEnable: true
...
----

Metal^3^のユースケースの詳細については、<<components-metal3>>を参照してください。
endif::[]

=== 高可用性

HAデプロイメントの場合、EIBは<<components-metallb,MetalLB>>と<<components-eco,Endpoint Copier Operator>>を自動的にデプロイおよび構成し、RKE2 APIエンドポイントを外部に公開します。

=== ネットワーキング

{product}スタックは、 https://docs.cilium.io/en/stable/[Cilium]と https://docs.tigera.io/calico/latest/about/[Calico]をサポートしており、デフォルトの CNI は Cilium です。また、Pod が複数のネットワークインタフェースを必要とする場合は、 https://github.com/k8snetworkplumbingwg/multus-cni[Multus]メタプラグインも使用できます。RKE2スタンドアロンは、 https://docs.rke2.io/install/network_options[より広範なCNIオプション]をサポートしています。

=== ストレージ

RKE2は、いかなる種類の永続ストレージクラスやオペレーターも提供しません。複数のノードにまたがるクラスターには、<<components-suse-storage,SUSE Storage>>の使用が推奨されます。

