[#components-rancher-turtles]
= Rancher Turtles
:revdate: 2025-04-25
:revnumber: 3.4
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


Rancher Turtlesマニュアルは https://documentation.suse.com/cloudnative/cluster-api/を参照してください

[quote]
____
Rancher Turtlesは、Rancher ManagerとCluster API (CAPI)の統合を提供するKubernetes Operatorで、RancherにCAPIのフルサポートをもたらすことを目的としています。
____


== Rancher Turtlesの主な機能

* CAPIでプロビジョニングされたクラスタにRancher Cluster Agentをインストールすることで、CAPIクラスタをRancherに自動的にインポートします。
* https://cluster-api-operator.sigs.k8s.io/[CAPI Operator]を介して、CAPIコントローラの依存関係をインストールおよび構成します。

== SUSE EdgeにおけるRancher Turtlesの使用

SUSE Edgeスタックは、Rancher Turtlesを特定の設定でインストールするHelmラッパーチャートを提供し、以下を有効にします。

* コアCAPIコントローラコンポーネント
* RKE2コントロールプレーンおよび起動用プロバイダコンポーネント
* <<components-metal3,Metal3>>インフラストラクチャプロバイダコンポーネント

ラッパーチャートを介してインストールされたデフォルトのプロバイダのみがサポートされています。代替のコントロールプレーンプロバイダ、起動するプロバイダ、およびインフラストラクチャプロバイダは、現在SUSE Edgeスタックの一部としてサポートされていません。

== Rancher Turtlesのインストール

Rancher Turtlesは、<<quickstart-metal3,Metal3クイックスタート>>ガイド、または<<atip-management-cluster,管理クラスタ>>のドキュメントに従ってインストールできます。

== その他の資料

* https://rancher.com/docs/[Rancherのマニュアル]
* https://cluster-api.sigs.k8s.io/[Cluster APIブック]
