[#components-rancher-turtles]
= Rancher Turtles
:revdate: 2025-12-15
:revnumber: 3.5
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


Rancher Turtlesマニュアルは https://documentation.suse.com/cloudnative/cluster-api/を参照してください

[quote]
____
Rancher Turtlesは、Rancher ManagerとCluster API (CAPI)の統合を提供するKubernetes Operatorで、RancherにCAPIのフルサポートをもたらすことを目的としています。
____


== Rancher Turtlesの主な機能

* CAPIでプロビジョニングされたクラスタにRancher Cluster Agentをインストールすることで、CAPIクラスタをRancherに自動的にインポートします。
* https://cluster-api-operator.sigs.k8s.io/[CAPI Operator]を介して、CAPIコントローラの依存関係をインストールおよび構成します。
* `CAPIProvider` APIを介して、インストール済みのCAPIプロバイダの依存関係を管理します。

== SUSE EdgeにおけるRancher Turtlesの使用

SUSE Edgeスタックは、`rancher-turtles-providers` Helmチャートを提供し、`CAPIProvider` APIを介して特定のCAPIプロバイダを有効にします。

* RKE2コントロールプレーンおよびブートストラッププロバイダ
* <<components-metal3,Metal3>>インフラストラクチャプロバイダ
* <<components-metal3,Metal3>> IPAMプロバイダ（現在サポートされていません）
* Fleetアドオンプロバイダ

ラッパーチャートを介してインストールされたデフォルトのプロバイダのみがサポートされています。代替のコントロールプレーンプロバイダ、起動するプロバイダ、およびインフラストラクチャプロバイダは、現在SUSE Edgeスタックの一部としてサポートされていません。

== Rancher Turtlesのインストール

Rancher 2.13以降、RancherをインストールするとRancher Turtlesがデフォルトで有効になります。

Rancher Turtlesプロバイダは、<<quickstart-metal3,Metal3クイックスタート>>ガイド、または<<atip-management-cluster,管理クラスタ>>のマニュアルに従ってインストールできます。

== その他の資料

* https://rancher.com/docs/[Rancherのマニュアル]
* https://cluster-api.sigs.k8s.io/[Cluster APIブック]
