= Documentación de SUSE Edge
:revdate: 2024-03-06
:revnumber: 3.6
:page-revdate: {revdate}

ifdef::env-github[]
:imagesdir: images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Bienvenido al repositorio de documentación de SUSE Edge.

== Asciidoctor vs Markdown

* https://docs.asciidoctor.org/asciidoc/latest/asciidoc-vs-markdown/#comparison-by-example[Comparación mediante ejemplos]

== Recursos de Asciidoctor

Documentación oficial::
* https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/[Referencia rápida]
* https://github.com/uyuni-project/uyuni-docs/wiki/asciidoc-getting-started[Introducción]
* https://github.com/powerman/asciidoc-cheatsheet[Hoja de referencia]
* https://docs.asciidoctor.org/asciidoc/latest/[Documentación del lenguaje Asciidoc]

Ejemplos (consulte la versión `raw` para ver el código)::
* https://github.com/openSUSE/daps/blob/main/test/documents/adoc/part_inlines.adoc[Elementos en línea]
* https://github.com/openSUSE/daps/blob/main/test/documents/adoc/part_block.adoc[Elementos de bloque]


== Edición y previsualización

La documentación está escrita en Asciidoc(tor). Empiece con una link:template.adoc[plantilla] muy básica.

* Las fuentes se pueden editar y previsualizar directamente en GitHub.
* Si editáis vuestros documentos localmente
** https://docs.asciidoctor.org/asciidoctor/latest/tooling/#web-browser-add-ons-preview-only[Complementos de previsualización para navegadores web]
** https://docs.asciidoctor.org/asciidoctor/latest/tooling/#ides-and-text-editors[IDEs y editores de texto]
** También existen modos de asciidoc para emacs y vi ;-)


== Prácticas recomendadas

=== Una frase por línea

* hacen que editar directamente en GitHub sea mucho más fácil y que las fuentes sean más legibles
* utilizad el ajuste de línea en vuestro editor


=== Los encabezados deben estar en orden

* empezad siempre un documento con un encabezado de nivel 0
  ** utilizad solo un único encabezado de nivel cero
* no está permitido saltarse un nivel con los encabezados subsiguientes

[,asciidoc]
----
= Level 0

== Level 1

=== Level 2

// ===== Level 4: Not allowed

==== Level 3

== Level 1
----


=== No utilicéis identificadores automáticos

Asciidoctor genera automáticamente identificadores/anclas a los que podéis enlazar:

[,asciidoc]
.No utilicéis
----
== Usage
...

Refer to <<usage>> for more information. 
----

No se recomienda utilizar esta funcionalidad, porque cada vez que cambiéis el encabezado correspondiente, tendríais que cambiar también la(s) referencia(s).
Utilizad mejor identificadores/anclas explícitos:

[,asciidoc]
.Utilizad
----
[#usage]
== Usage
...

Refer to <<usage>> for more information. 
----

=== Utilizad siempre delimitadores de bloque

Algunos elementos de bloque pueden escribirse de forma corta y larga.
Utilizad siempre la forma larga para evitar confusiones y aumentar la legibilidad de las fuentes.

[,asciidoc]
.No utilicéis
----
NOTE: This is a note

 This is a literal block
----

[,asciidoc]
.Utilizad
----
[NOTE]
====
This is a note
====

....
This is a literal block
....
----

==== Estructuras anidadas

Las estructuras anidadas, p. ej. una anotación dentro de un elemento de lista, deben concatenarse mediante un carácter más (`+`).

[,asciidoc]
----
* normal listitem
* lisitem with annotation
+
[NOTE]
====
note
====
+
* lisitem with two paragraphs
+
second paragraph
+
* normal listitem
----

=== Pulsaciones de teclas, menús, botones

Asciidoctor incluye tres macros para mostrar pulsaciones de teclas, selección de menús y clics de botones:

[,asciidoc]
----
Press kbd:[C] to continue or kbd:[Crtl+C] to cancel, kbd:[F1] opens the help menu.

To save the file, select menu:File[Save].
Select menu:View[Zoom > Reset] to reset the zoom level to the default setting.

Press the btn:[OK] button when you are finished.
----

[IMPORTANT]
====
Esta función solo se activa cuando el atributo `:experimental:` está establecido en la cabecera.
====

=== Vista de pestañas

Usad listas delimitadas/etiquetadas precedidas por `[.tabs]`:

[,asciidoc]
----
[.tabs]
TAB 1::
+
Content tab 1
+
TAB 2::
+
Content tab 2
----

=== Las sentencias include deben estar separadas por líneas vacías

Aseguraos siempre de que una sentencia include esté precedida y seguida por una línea vacía.


== Etiquetas Asciidoc no compatibles

Lo siguiente no es compatible al crear una versión con la marca SUSE.
No utilicéis:

* resaltado, subrayado, tachado
+
[,asciidoc]
----
#highlight#
##high##light
[.underline]#underline#
[.line-through]#strike-through#
----
+
* listas de verificación
+
[,asciidoc]
----
* [*] checked
* [x] also checked
* [ ] not checked
----
+
* audio y vídeo
+
[,asciidoc]
----
audio::audio.wav[]
video:: video.mp4[]
----
+
* barras laterales
+
[,asciidoc]
----
****
Sidebar text
****
----
+
* notas al pie
+
[,asciidoc]
----
footnote:[Footnote]
----

== Generación de la documentación 

=== Generación de una versión genérica

Generar el libro en una versión sin la marca SUSE es más fácil y rápido que generar la versión con la marca SUSE.

Extensión del navegador (la forma más sencilla)::
+
* Instalad https://docs.asciidoctor.org/asciidoctor/latest/tooling/#web-browser-add-ons-preview-only[una extensión del navegador] y previsualizad edge-book/edge.adoc en vuestro navegador.
* La vista previa se actualiza automáticamente tras guardar los cambios.
+
Una compilación HTML local::
+
* Instala asciidoctor en tu sistema.
* Ejecuta el siguiente comando en la copia de GitHub.
+
[,bash]
----
asciidoctor -d book --attribute="toc=left" edge-book/edge.adoc
----
+
* Resultado: `edge-book/edge.html`


=== Compilación local de la versión con marca SUSE

Para generar la documentación localmente en el formato en el que se publicará, utiliza https://github.com/openSUSE/daps2docker[daps2docker]
Ten en cuenta que no es necesario realizar estas compilaciones para comprobar tus contribuciones.
Mientras el documento se visualice correctamente en las vistas previas, todo estará bien.


.Requisitos
* asegúrate de que tu estación de trabajo esté ejecutando docker o podman
* asegúrate de que tu usuario pueda iniciar contenedores
* instala daps2docker desde https://download.opensuse.org/repositories/Documentation:/Tools/
* navega hasta la copia local de este repositorio en el directorio de documentación

Generación de HTML::
`daps2docker DC-edge html`
Generación de HTML único::
`daps2docker DC-edge single-html`
Generación de PDF::
`daps2docker DC-edge pdf`

[TIP]
.Uso de Podman
====
De forma predeterminada, daps2docker utiliza docker como su motor de contenedores.
Para utilizar Podman, exporta la variable de entorno CONTAINER_ENGINE=podman: `export CONTAINER_ENGINE=podman`
====

[TIP]
.Errores de compilación
====
daps2docker genera documentación a partir de fuentes DocBook XML.
Asciidoctor incluye un convertidor integrado a DocBook.

Asciidoc(tor) es mucho más permisivo que DocBook en lo que respecta a la validación.
En algunos casos, el código fuente asciidoc válido no se valida al convertirlo a DocBook.
En tal caso, la compilación con daps2docker fallará.
Si eso sucede, contactad conmigo (@fsundermeyer) y os ayudaré.
====

=== Información adicional

...véase el https://github.com/openSUSE/daps2docker[repositorio de daps2docker].
También encontraréis instrucciones sobre cómo instalarlo en otras distribuciones y cómo establecer una configuración personalizada.

