= Redacción técnica: Mejores prácticas
:revdate: 2024-03-06
:revnumber: 3.6
:page-revdate: {revdate}

Cinco reglas básicas sobre cómo escribir mejor documentación técnica

== #1 Cambiad de perspectiva

____
¡No me digáis cómo funciona...decidme cómo usarlo!
____

* Poneos siempre en el lugar de vuestro lector
** ¿Qué nivel de conocimientos requiero que tengan los lectores?
** ¿Qué quiere conseguir el lector?
** ¿Qué preguntas puede tener el lector?
** ¿Qué puede salir mal?
* Tened en cuenta que vuestros lectores
** solo disponen de tiempo limitado
** están frustrados
** están bajo presión
** trabajan en un entorno ruidoso
** no son hablantes nativos


[IMPORTANT]
====
Más del 80% de nuestros lectores llegan a través de la búsqueda (de Google) y probablemente aterricen en algún capítulo aleatorio del libro.
Aseguraos de proporcionar siempre todo el contexto y los requisitos necesarios al principio de un capítulo.
====




== #2 Mantenedlo simple y breve (KISS)

Las instrucciones breves y sencillas son más fáciles de entender y menos propensas a errores.
Esto no solo es relevante para los lectores, sino también para la localización.

Lenguaje sencillo y claro::
+
* utiliza -> *usa*
* indica -> *muestra*, *di*, *di*
* requisito previo -> *requisito*
+
Sin palabras de relleno::
+
* para -> *para*
* ya existente -> *existente*
* completamente nuevo -> *nuevo*
* simplemente haz -> *haz*
* por favor, haz -> *haz*
+
Usa el tiempo presente::
+
* Ejecuta xxx. Aparecerá el diálogo yyy. -> *Ejecuta xxx. El diálogo yyy aparece.*
+
Una idea, una frase::
+
Usa YaST, que viene en dos versiones (interfaz de usuario de X Window, ncurses) para configurar y gestionar el sistema y para instalar nuevo software o actualizaciones de seguridad y parches.
+
->
+
*Usa YaST para configurar y gestionar el sistema.*
*Úsalo también para instalar nuevo software y para mantener tu sistema actualizado.*
*YaST incluye una interfaz de usuario para utilizarse en X Window.*
*Para su uso en un terminal, hay disponible una interfaz ncurses.*
+
Limitad la descripción de alternativas::
+
Normalmente hay más de una forma de hacer las cosas.
Limitad la documentación a la _única_ forma recomendada y soportada de hacer las cosas.
Documentad alternativas solo cuando sea absolutamente necesario, por ejemplo, interfaz de usuario y línea de comandos.

== #3 Estructurad la información

* Pensad en vuestro documento como en un embudo: empezad con información general y sed más específicos a medida que avancéis
* colocad la información donde sea importante
** el objetivo y el contexto van primero
** los requisitos van en segundo lugar
** el procedimiento va al final
** las advertencias y notas deben colocarse donde sean relevantes
** Lo anterior también se aplica a todas las secciones del documento
* Utilizad siempre listas ordenadas para describir un conjunto de pasos (procedimiento)
** no más de 10 pasos por procedimiento (7+/- 2 es lo ideal); dividid en tareas diferentes para acortar
** objetivo, pasos, resultado
* No coloquéis ninguna información en los listados de programas
** ...porque no se traducirán
* no utilicéis titulares de nivel inferior a 3 (`==== Level 3 headline`)
* Dividid los comandos que tengan más de 80 caracteres en varias líneas

== #4 Sed coherentes

Las repeticiones _no_ son malas::
+
. Ejecutad el comando XXX -> *Ejecutad el comando XXX*
. Ejecutad el comando YYY -> *Ejecutad el comando YYY*
. Ejecutad el comando ZZZ -> *Ejecutad el comando ZZZ*
+
Utilizad una terminología coherente::
+
* enlace simbólico, enlace, enlace blando, symlink -> *enlace simbólico*
* actualizar vs actualizar versión
* complemento, complemento, complemento -> *complemento*

== #5 Evitad interrupciones

Una línea de pensamiento::
+
Sin embargo, no están marcados como instalados. -> *Sin embargo, no están marcados como instalados.*
+
No separeis los verbos::
+
Apagad el servidor. -> *Apagad el servidor.*
