= SUSE Edge Engineering GitHub workflow: Best Practices

There are multiple ways to use Git and GitHub workflows, how to create PR/MR, cherry pick commits to a specific branch, etc.

This document explains how the SUSE Edge engineering team does it.

== Configure your user and email

[,shell]
----
$ git config --global user.name "FIRST_NAME LAST_NAME"
$ git config --global user.email "MY_NAME@example.com"
----

This can be done individually per repository without the `--global` flag.

== Fork the repository

Ideally, you won't push changes to branches on the suse-edge/ repositories but instead you'll fork the repository on the GitHub UI and _do your thing_ there.

[NOTE]
====
You don't need to use the same name for your fork if you don't want to.
====

== Setup the origin/upstream properly

Once you have your repo forked, it is time to clone it to your workstation and configure the origin/upstream remotes:

* Clone the repo

[,shell]
----
$ git clone git@github.com:e-minguez/suse-edge-charts.git
----

This will create the "origin" remote:

[,shell]
----
$ git remote -v
origin  git@github.com:e-minguez/suse-edge-charts.git (fetch)
origin  git@github.com:e-minguez/suse-edge-charts.git (push)
----

* Add the upstream repository

[,shell]
----
$ git remote add upstream git@github.com:suse-edge/charts.git
----

Optionally, disable the push url so you don't push it against it:

[,shell]
----
$ git remote set-url --push upstream ""
----

It should look like this:

[,shell]
----
$ git remote -v
origin  git@github.com:e-minguez/suse-edge-charts.git (fetch)
origin  git@github.com:e-minguez/suse-edge-charts.git (push)
upstream        git@github.com:suse-edge/charts.git (fetch)
upstream         (push)
----

== Sign off commits

Some repositories require to sign-off the commits to acknoledge that you have read and agreed with the rules and licensing of the repository/project.

When commiting the changes, just append the `-s` or `--signoff` flag to the commit command as:

[,shell]
----
$ git commit --signoff --message 'This is my commit message'
----

If you have authored a commit that is missing the signed-off-by line, you can amend your commits:

[,shell]
----
git commit --amend --signoff
----

If you've pushed your changes to GitHub already you'll need to force push your branch after this with `git push -f`.

== Commit signature verification

You can sign commits to give other people confidence about the origin of a change you have made. If a commit or tag has a GPG, SSH, or S/MIME signature that is cryptographically verifiable, GitHub marks the commit or tag "Verified" or "Partially verified."

The process involves generating a GPG key, use an SSH key or an X.509 key. Please see the https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification[GitHub] documentation for more information on how to configure it.

== Keep your main branch in sync

If you have been working on a specific branch and you would like to get the latest updates from the main branch of the upstream repository:

[,shell]
----
$ git switch main
$ git pull --rebase upstream/main
----

== Create a branch to work on a feature/fix/something

[,shell]
----
$ git switch main
$ git pull --rebase upstream/main
$ git checkout -b myawesomebranch
----

This will create a new branch locally with the content of the main one.

== Push changes from your local branch to GitHub

[,shell]
----
$ git add <files>
$ git commit -av
# Review the changes, add a meaningful commit message and save it
$ git push origin/myawesomebranch
----

== Create a PR

After the git push message from above, a GitHub URL will be shown. Follow it and create the PR. Double check the content, the branches, the repositories from/to and the list of changes.

== Rebase your branch

It can happen that the content in the main branch of the upstream repository changed. You will need to refresh your main branch and rebase the branch you've been working.

[,shell]
----
$ git pull --rebase upstream/main
$ git push --force-with-lease
----

____
Potential issues with `--force-with-lease` can happen.
____

== Cherry pick commits

When things have been merged on for example the main branch and you want to cherry-pick them in another branch (for example release-3.3), the process should be:

* Get all the branches:

----
$ git fetch --all
----

* Get the commit id(s) you want to cherry-pick (from the main branch):

----
$ git log main --oneliner
----

* Create a branch where the cherry-pick process is landing:

----
$ git checkout -b cherry-pick-of-fix-293 upstream/release-3.3
----

* Cherry-pick the commit(s):

----
$ git cherry-pick -x <commit-id(s)>
----

Observe the output and see if there are conflicts. If there are, good luck fix them! :)

* Review the git log just in case:

----
$ git log
----

* Push the changes

----
$ git push origin cherry-pick-of-fix-293
----

* Create the PR

After the git push message from above, a GitHub URL will be shown. Follow it and create the PR. Double check the content, the branches, the repositories from/to and the list of changes.
