= SUSE Edge docmentation

ifdef::env-github[]
:imagesdir: images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Welcome to the SUSE Edge documentation repository.

== Asciidoctor resources

Official documentation::
+
* https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/[Quick reference]
* https://github.com/uyuni-project/uyuni-docs/wiki/asciidoc-getting-started[Getting
  Started]
* https://github.com/powerman/asciidoc-cheatsheet[Cheat sheet]
* https://docs.asciidoctor.org/asciidoc/latest/[Asciidoc language documentation]
+
Examples (refer to `raw` version for code)::
+
* https://github.com/openSUSE/daps/blob/main/test/documents/adoc/part_inlines.adoc[Inline
  elements]
* https://github.com/openSUSE/daps/blob/main/test/documents/adoc/part_inlines.adoc[Block elements]


== Editing & Previewing

The documenation is written in Asciidoc(tor). Start with a very basic link:teamplate.adoc[Template].

* Sources can be directly edited and previewed in GitHub.
* If you edit your docs locally
** https://docs.asciidoctor.org/asciidoctor/latest/tooling/#web-browser-add-ons-preview-only[Preview add-ons for Web browsers]
** https://docs.asciidoctor.org/asciidoctor/latest/tooling/#ides-and-text-editors[IDEs and text editors]
** There also is asciidoc modes for emacs and vi ;-)


== Building the SUSE branded version locally

To build the documentation locally in the format it will get published, use https://github.com/openSUSE/daps2docker[daps2docker]
Note that doing these builds is not needed to check your contributions.
As long as your document renders fine in previews you are good.


.Requirements
* make sure your workstation is running docker or podman
* make sure your user can start containers
* install daps2docker from https://download.opensuse.org/repositories/Documentation:/Tools/
* navigate to the local checkout of this repository into the documentatio directory  

Building HTML::
`daps2docker DC-edge html`
Building Single HTML::
`daps2docker DC-edge single-html`
Building PDF::
`daps2docker DC-edge pdf`

[TIP]
.Using Podman
====
By default, daps2docker uses docker as its container engine.
To use podman, export the environment variable CONTAINER_ENGINE=podman: `export CONTAINER_ENGINE=podman`
====

[TIP]
.Build errors
====
daps2docker builds documentation from DocBook XML sources.
Asciidoctor comes with a built-in converter to DocBook.

Asciidoc(tor) is way more forgiving than DocBook when it comes to validation.
In some cases, valid asciidoc source code does not validate when converting it
to DocBook.
In such a case building with daps2docker will fail.
If that happens, contact me (@fsundermeyer) and I will help.
====

=== For more information

...see the https://github.com/openSUSE/daps2docker[daps2docker repository].
You will also find instructions on how to install it on other distributions and how to set a custom configuration.

