[#{cluster-type}-day2-fleet]
== Fleet
:revdate: 2025-01-14
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Esta seção oferece informações sobre como realizar operações de "Dia 2" usando o componente <<components-fleet, Fleet>>.

Os tópicos a seguir são abordados como parte desta seção:

. <<{cluster-type}-day2-fleet-components>> - componentes padrão usados para todas as operações de "Dia 2".
. <<{cluster-type}-day2-fleet-determine-use-case>> - fornece uma visão geral dos recursos personalizados do Fleet que serão usados e sua adequação para diferentes casos de uso de operações de "Dia 2".
. <<{cluster-type}-day2-upgrade-workflow>> - fornece um guia de fluxo de trabalho para a execução de operações de "Dia 2" com o Fleet.
. <<{cluster-type}-day2-fleet-os-upgrade>> - descreve como fazer upgrade do SO usando o Fleet.
. <<{cluster-type}-day2-fleet-k8s-upgrade>> - descreve como fazer upgrade da versão do Kubernetes usando o Fleet.
. <<{cluster-type}-day2-fleet-helm-upgrade>> - descreve como fazer upgrade do Helm chart usando o Fleet.

[#{cluster-type}-day2-fleet-components]
=== Componentes

Abaixo, você pode encontrar uma descrição dos componentes padrão que devem ser configurados em seu cluster `{cluster-type}` para que você possa realizar com sucesso as operações de "Dia 2" usando o Fleet.

ifeval::["{cluster-type}" == "management"]
==== Rancher

*Opcional*; Responsável por gerenciar o `downstream clusters` e implantar o `System Upgrade Controller` em seu `management cluster`.

Para obter mais informações, consulte <<components-rancher>>. 
endif::[]

==== System Upgrade Controller (SUC)

ifeval::["{cluster-type}" == "downstream"]
[NOTE]
====
*Deve* ser implantado em cada cluster downstream.
====
endif::[]

O *System Upgrade Controller* é responsável por executar tarefas em nós especificados com base em dados de configuração fornecidos por meio de um recurso personalizado, chamado de `Plan`.

O *SUC* é utilizado ativamente para fazer upgrade do sistema operacional e da distribuição do Kubernetes.

Para obter mais informações sobre o componente *SUC* e como ele se encaixa na pilha Edge, consulte <<components-system-upgrade-controller>>.

ifeval::["{cluster-type}" == "downstream"]
Para obter informações sobre como implantar o *SUC*, primeiro <<{cluster-type}-day2-fleet-determine-use-case, determine seu caso de uso>> e, em seguida, consulte <<components-system-upgrade-controller-fleet-gitrepo, Instalação do System Upgrade Controller - GitRepo>> ou <<components-system-upgrade-controller-fleet-bundle, Instalação do System Upgrade Controller - Bundle>>.
endif::[]

[#{cluster-type}-day2-fleet-determine-use-case]
=== Determine seu caso de uso

O Fleet usa dois tipos de link:https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[recursos personalizados] para permitir o gerenciamento de recursos do Kubernetes e do Helm.

Abaixo, você pode encontrar informações sobre o propósito desses recursos e os casos de uso para os quais eles são mais adequados no contexto de operações de "Dia 2".

==== GitRepo

Um `GitRepo` é um recurso <<components-fleet, Fleet>> que representa um repositório Git a partir do qual o `Fleet` pode criar `Bundles`. Cada `Bundle` é criado com base em caminhos de configuração definidos dentro do recurso `GitRepo`. Para obter mais informações, consulte a documentação do https://fleet.rancher.io/gitrepo-add[GitRepo].

No contexto de operações de "Dia 2", os recursos `GitRepo` são normalmente usados para implantar `SUC` ou `SUC Plans` em ambientes *não air-gapped* que utilizam uma abordagem de _Fleet GitOps_.

Alternativamente, os recursos `GitRepo` também podem ser usados para implantar `SUC` ou `SUC Plans` em ambientes *air-gapped*, *desde que você espelhe a configuração do seu repositório por meio de um servidor git local*.

==== Pacote

`Bundles` contêm recursos *raw* do Kubernetes que serão implantados no cluster de destino. Geralmente, eles são criados a partir de um recurso `GitRepo`, mas existem casos de uso em que podem ser implantados manualmente. Para obter mais informações, consulte a documentação do https://fleet.rancher.io/bundle-add[Bundle].

No contexto de operações de "Dia 2", os recursos `Bundle` são normalmente usados para implantar `SUC` ou `SUC Plans` em ambientes *air-gapped* que não utilizam alguma forma de procedimento de _GitOps local_ (por exemplo, um *servidor git local*).

Alternativamente, se o seu caso de uso não permitir um fluxo de trabalho _GitOps_ (por exemplo, usando um repositório Git), os recursos `Bundle` também podem ser usados para implantar `SUC` ou `SUC Plans` em ambientes *não air-gapped*.

[#{cluster-type}-day2-upgrade-workflow]
=== Fluxo de trabalho de Dia 2

O que se segue é um fluxo de trabalho de "Dia 2" que deve ser seguido ao fazer upgrade de um cluster {cluster-type} para uma versão específica do Edge.

. <<{cluster-type}-day2-fleet-os-upgrade,Fazer upgrade do SO>>

. <<{cluster-type}-day2-fleet-k8s-upgrade, Kubernetes version upgrade>>

. <<{cluster-type}-day2-fleet-helm-upgrade,Fazer upgrade do Helm chart>>

:leveloffset: +1

include::fleet-os-upgrade.adoc[]

include::fleet-k8s-upgrade.adoc[]

include::fleet-helm-upgrade.adoc[]

:leveloffset: -1
