[#{cluster-type}-day2-upgrade-controller]
== Upgrade Controller
:revdate: 2025-01-16
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[IMPORTANT]
====
O `Upgrade Controller` atualmente suporta apenas operações `Day 2` para clusters *não air-gapped*.
====

Esta seção aborda como realizar as várias operações `Day 2` relacionadas a fazer upgrade do seu cluster `management` de uma versão de plataforma `{product}` para outra.

As operações `Day 2` são automatizadas pelo <<components-upgrade-controller, Upgrade Controller>> e incluem:

* Fazer upgrade do SO <<components-slmicro, SUSE Linux Micro>>
ifeval::["{flavor}" == "edge"]
* <<components-rke2>>Fazer upgrade do Kubernetes ou <<components-k3s>>
endif::[]
ifeval::["{flavor}" == "telco"]
* <<components-rke2>>Fazer upgrade do Kubernetes
endif::[]
* Fazer upgrade de componentes adicionais do SUSE (SUSE Rancher Prime, SUSE Security, etc.)

=== Pré-requisitos

Antes de fazer upgrade do seu cluster `management`, os seguintes pré-requisitos devem ser atendidos:

. `SCC registered nodes` - certifique-se de que o SO dos nós do seu cluster esteja registrado com uma chave de assinatura que suporte a versão do SO especificada na `{product}` <<release-notes,release>> para a qual você pretende fazer upgrade.

. `Upgrade Controller` - certifique-se de que o `Upgrade Controller` tenha sido implantado em seu cluster `management`. Para as etapas de instalação, consulte <<components-upgrade-controller-installation>>.

=== Upgrade

. Determine a versão de `{product}` <<release-notes,release>> para a qual você deseja fazer upgrade do seu cluster `management`.

. No cluster `management`, implante um `UpgradePlan` que especifique o `release version` desejado. O `UpgradePlan` deve ser implantado no namespace do `Upgrade Controller`.
+
[,bash]
----
kubectl apply -n <upgrade_controller_namespace> -f - <<EOF
apiVersion: lifecycle.suse.com/v1alpha1
kind: UpgradePlan
metadata:
  name: upgrade-plan-mgmt
spec:
  # Version retrieved from release notes
  releaseVersion: 3.X.Y
EOF
----
+
[NOTE]
====
Podem existir casos de uso em que você deseje fazer configurações adicionais sobre o `UpgradePlan`. Para todas as configurações possíveis, consulte <<components-upgrade-controller-extensions-upgrade-plan>>.
====

. A implantação do `UpgradePlan` no namespace do `Upgrade Controller's` iniciará o `upgrade process`.
+
[NOTE]
====
Para obter mais informações sobre o `upgrade process` real, consulte <<components-upgrade-controller-how>>.

Para obter informações sobre como rastrear o `upgrade process`, consulte <<components-upgrade-controller-how-track>>.
====

=== Tarefas pós-upgrade
Fazer upgrade do `{product}` do z-stream `{previous-edge-version}` mais recente para `{static-edge-version}` pode exigir algumas etapas manuais finais a serem executadas após o `Upgrade Controller` ter concluído o processo de fazer upgrade. Essas estão relacionadas à substituição do Ingress-NGINX pelo Traefik como o único controlador de ingresso suportado no `{product}` a partir da versão `{version}`.

[NOTE]
====
O provedor de ingresso `Traefik` integrado ao RKE2/K3s é o único controlador de ingresso suportado na versão `{product} {version}`, sendo ainda possível executar temporariamente o `Ingress-NGINX` junto com o `Traefik` para oferecer suporte a cenários complexos de migração de ingresso, mas apenas após os clusters de Gerenciamento e/ou Downstream `{product}` terem feito upgrade para a versão `{version}` e pelo tempo necessário para realizar essa migração.

O guia https://docs.rke2.io/reference/ingress_migration[Migração de Ingress NGINX para Traefik] fornece detalhes sobre os caminhos de migração de ingresso disponíveis assim que o controlador de ingresso `Traefik` substituir o `Ingress-NGINX` descontinuado.
====

Caso o cluster de Gerenciamento recém-fez upgrade não estivesse executando o controlador de ingresso `Traefik` (mas o padrão Ingress-NGINX) antes de iniciar o upgrade, agora é necessário implantar manualmente o `Traefik`.

Primeiro, vamos garantir que a instância do ingress-NGINX implantada esteja configurada corretamente (por exemplo, para evitar colisões desnecessárias de hostPort entre os pods dos dois controladores de ingresso):

[,shell]
----
kubectl apply -f - <<- EOF
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      hostPort:
        enabled: false  # not needed when exposing through a type:LoadBalancer service
      config:
        use-forwarded-headers: "true"
        enable-real-ip: "true"
      publishService:
        enabled: true
      service:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Local
EOF
----

Agora podemos prosseguir com a implantação do `Traefik`, por meio da instalação dos gráficos Helm `rke2-traefik-crd` e `rke2-traefik`.
[NOTE]
====
Implante esses gráficos Helm por meio de manifestos `HelmChart`, conforme mostrado abaixo, para garantir que o `Upgrade Controller` também cuide de fazer upgrade desses gráficos Helm em futuros processos de fazer upgrade do cluster de Gerenciamento.
====

[,shell]
----
kubectl apply -f - <<- EOF
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rke2-traefik-crd
  namespace: kube-system
spec:
  chart: rke2-traefik-crd
  version: {rke2-traefik-crd Helm chart version}
  repo: https://rke2-charts.rancher.io
  bootstrap: false
  failurePolicy: reinstall
  backOffLimit: 20
  targetNamespace: kube-system
  set:
    global.cattle.systemDefaultRegistry: registry.rancher.com
    global.rke2DataDir: /var/lib/rancher/rke2
    global.systemDefaultRegistry: registry.rancher.com
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rke2-traefik
  namespace: kube-system
spec:
  chart: rke2-traefik
  version: {rke2-traefik Helm chart version}
  repo: https://rke2-charts.rancher.io
  bootstrap: false
  failurePolicy: reinstall
  backOffLimit: 20
  targetNamespace: kube-system
  set:
    global.cattle.systemDefaultRegistry: registry.rancher.com
    global.rke2DataDir: /var/lib/rancher/rke2
    global.systemDefaultRegistry: registry.rancher.com
  valuesContent: |-
    ingressClass:
      isDefaultClass: false  # if traefik deployed alongside ingress-nginx
    ports:
      web:
        hostPort: null    # disallow hostPort
        exposedPort: 80
      websecure:
        hostPort: null    # disallow hostPort
        exposedPort: 443
    service:
      enabled: true
      type: LoadBalancer
      spec:
        externalTrafficPolicy: Local
        allocateLoadBalancerNodePorts: false  # k8s GA from 1.24; supported by MetalLB
    providers:
      kubernetesIngressNginx:  # this provider allows traefik to "understand" most of the ingress-nginx annotations
        enabled: true
        ingressClass: "rke2-ingress-nginx-migration"
        controllerClass: "rke2.​cattle.​io/ingress-nginx-migration"
EOF
----

O `{rke2-traefik-crd Helm chart version}` e o `{rke2-traefik-crd Helm chart version}` são aqueles ditados pela versão do RKE2/k3s para a qual fizemos upgrade.

Na última etapa, finalmente criamos os objetos necessários do MetalLB para expor o serviço `Traefik` por meio de um serviço do tipo LoadBalancer:

[,shell]
----
kubectl apply -f - <<- EOF
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ingress-ippool-traefik
  namespace: metallb-system
spec:
  addresses:
  - {EXTERNAL_IP_FOR_TRAEFIK_SERVICE}/32
  serviceAllocation:
    priority: 100
    serviceSelectors:
    - matchExpressions:
      - {key: app.kubernetes.io/name, operator: In, values: [rke2-traefik]}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ingress-l2-adv-traefik
  namespace: metallb-system
spec:
  ipAddressPools:
  - ingress-ippool-traefik
EOF
----

Agora, tanto o `Traefik` quanto o `Ingress-NGINX` estão sendo executados lado a lado, permitindo que você execute com segurança a migração necessária de seus ingresses de um para o outro.

[IMPORTANT]
====
Assim que todos os ingresses tiverem sido migrados e você não precisar mais do `Ingress-NGINX`, certifique-se de desinstalá-lo e limpar todos os recursos relacionados para evitar qualquer consumo desnecessário de recursos em seu cluster.
====