[#{cluster-type}-day2-upgrade-controller]
== Upgrade Controller
:revdate: 2025-01-16
:revnumber: 3.5
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[IMPORTANT]
====
O `Upgrade Controller` atualmente suporta apenas operações `Day 2` para clusters *não air-gapped*.
====

Esta seção aborda como realizar as várias operações `Day 2` relacionadas a fazer upgrade do seu cluster `management` de uma versão de plataforma Edge para outra.

As operações `Day 2` são automatizadas pelo <<components-upgrade-controller, Upgrade Controller>> e incluem:

* Fazer upgrade do SO <<components-slmicro, SUSE Linux Micro>>

* <<components-rke2>>Fazer upgrade do Kubernetes ou <<components-k3s>>

* Fazer upgrade de componentes adicionais do SUSE (SUSE Rancher Prime, SUSE Security, etc.)

=== Pré-requisitos

Antes de fazer upgrade do seu cluster `management`, os seguintes pré-requisitos devem ser atendidos:

. `SCC registered nodes` - certifique-se de que o SO dos nós do seu cluster esteja registrado com uma chave de assinatura que suporte a versão do SO especificada na <<release-notes,release>> Edge para a qual você pretende fazer upgrade.

. `Upgrade Controller` - certifique-se de que o `Upgrade Controller` tenha sido implantado em seu cluster `management`. Para as etapas de instalação, consulte <<components-upgrade-controller-installation>>.

=== Upgrade

. Determine a versão do <<release-notes,release>> Edge para a qual você deseja fazer upgrade do seu cluster `management`.

. No cluster `management`, implante um `UpgradePlan` que especifique o `release version` desejado. O `UpgradePlan` deve ser implantado no namespace do `Upgrade Controller`.
+
[,bash]
----
kubectl apply -n <upgrade_controller_namespace> -f - <<EOF
apiVersion: lifecycle.suse.com/v1alpha1
kind: UpgradePlan
metadata:
  name: upgrade-plan-mgmt
spec:
  # Version retrieved from release notes
  releaseVersion: 3.X.Y
EOF
----
+
[NOTE]
====
Podem existir casos de uso em que você deseje fazer configurações adicionais sobre o `UpgradePlan`. Para todas as configurações possíveis, consulte <<components-upgrade-controller-extensions-upgrade-plan>>.
====

. A implantação do `UpgradePlan` no namespace do `Upgrade Controller's` iniciará o `upgrade process`.
+
[NOTE]
====
Para obter mais informações sobre o `upgrade process` real, consulte <<components-upgrade-controller-how>>.

Para obter informações sobre como rastrear o `upgrade process`, consulte <<components-upgrade-controller-how-track>>.
====
