[#{cluster-type}-day2-fleet]
== Fleet
:revdate: 2025-01-14
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

本セクションでは、<<components-fleet, Fleet>>コンポーネントを使用して「Day 2」オペレーションを実行する方法について説明します。

本セクションでは、以下のトピックを扱います。

. <<{cluster-type}-day2-fleet-components>> - すべての「Day 2」オペレーションで使用されるデフォルトコンポーネント。
. <<{cluster-type}-day2-fleet-determine-use-case>> - 使用されるFleetカスタムリソースの概要と、さまざまな「Day 2」オペレーションのユースケースへの適合性について説明します。
. <<{cluster-type}-day2-upgrade-workflow>> - Fleetを使用して「Day 2」オペレーションを実行するためのワークフローガイドを提供します。
. <<{cluster-type}-day2-fleet-os-upgrade>> - Fleetを使用してOSアップグレードを実行する方法について説明します。
. <<{cluster-type}-day2-fleet-k8s-upgrade>> - Fleetを使用してKubernetesバージョンのアップグレードを実行する方法について説明します。
. <<{cluster-type}-day2-fleet-helm-upgrade>> - Fleetを使用してHelmチャートのアップグレードを実行する方法について説明します。

[#{cluster-type}-day2-fleet-components]
=== コンポーネント

以下に、Fleetを使用して「Day 2」オペレーションを正常に実行するために、`{cluster-type}`クラスター上にセットアップする必要があるデフォルトコンポーネントの説明を記載します。

ifeval::["{cluster-type}" == "management"]
==== Rancher

*オプション*。`downstream clusters`の管理および`System Upgrade Controller`への`management cluster`のデプロイを担当します。

詳細については、<<components-rancher>>を参照してください。
endif::[]

==== System Upgrade Controller (SUC)

ifeval::["{cluster-type}" == "downstream"]
[NOTE]
====
*Must*は、各ダウンストリームクラスターに必ずデプロイする必要があります。
====
endif::[]

*System Upgrade Controller*は、`Plan`と呼ばれるカスタムリソースを通じて提供される設定データに基づき、指定されたノードでタスクを実行する役割を担います。

*SUC*は、オペレーティングシステムおよびKubernetesディストリビューションのアップグレードに積極的に活用されています。

*SUC*コンポーネントの詳細およびEdgeスタックにおける位置付けについては、<<components-system-upgrade-controller>>を参照してください。

ifeval::["{cluster-type}" == "downstream"]
*SUC*のデプロイ方法については、まず<<{cluster-type}-day2-fleet-determine-use-case,ユースケースを特定>>してから、<<components-system-upgrade-controller-fleet-gitrepo, System Upgrade Controllerのインストール - GitRepo>>または<<components-system-upgrade-controller-fleet-bundle, System Upgrade Controllerのインストール - Bundle>>を参照してください。
endif::[]

[#{cluster-type}-day2-fleet-determine-use-case]
=== ユースケースの特定

Fleetは、KubernetesおよびHelmリソースの管理を可能にするために、2種類のlink:https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[カスタムリソース]を使用します。

以下に、これらのリソースの目的と、「Day 2」オペレーションの文脈において最適なユースケースに関する情報を記載します。

==== GitRepo

`GitRepo`は、`Fleet`が`Bundles`を作成するためのGitリポジトリを表す<<components-fleet, Fleet>>リソースです。各 `Bundle` は、`GitRepo` リソース内で定義された設定パスに基づいて作成されます。詳細については、 https://fleet.rancher.io/gitrepo-add[GitRepo]マニュアルを参照してください。

「Day 2」運用のコンテキストでは、`GitRepo` リソースは通常、_Fleet GitOps_ アプローチを利用する *非エアギャップ(された)* 環境で `SUC` または `SUC Plans` をデプロイするために使用されます。

あるいは、*ローカル git サーバーを介してリポジトリ設定をミラーリングすることを条件に*、*エアギャップ(された)* 環境で `SUC` または `SUC Plans` をデプロイするために `GitRepo` リソースを使用することもできます。

==== バンドル

`Bundles` は、ターゲットクラスターにデプロイされる *raw* Kubernetes リソースを保持します。通常、これらは `GitRepo` リソースから作成されますが、手動でデプロイできるユースケースもあります。詳細については、 https://fleet.rancher.io/bundle-add[Bundle]マニュアルを参照してください。

「Day 2」運用のコンテキストでは、`Bundle` リソースは通常、_ローカル GitOps_ 手順（例：*ローカル git サーバー*）を使用しない *エアギャップ(された)* 環境で `SUC` または `SUC Plans` をデプロイするために使用されます。

あるいは、ユースケースで _GitOps_ ワークフロー（Git リポジトリの使用など）が許可されない場合は、*非エアギャップ(された)* 環境で `SUC` または `SUC Plans` をデプロイするために `Bundle` リソースを使用することもできます。

[#{cluster-type}-day2-upgrade-workflow]
=== Day 2 ワークフロー

以下は、{cluster-type} クラスターを特定の Edge リリースにアップグレードする際に従うべき「Day 2」ワークフローです。

. <<{cluster-type}-day2-fleet-os-upgrade, OS upgrade>>

. <<{cluster-type}-day2-fleet-k8s-upgrade, Kubernetes version upgrade>>

. <<{cluster-type}-day2-fleet-helm-upgrade, Helm チャートアップグレード>>

:leveloffset: +1

include::fleet-os-upgrade.adoc[]

include::fleet-k8s-upgrade.adoc[]

include::fleet-helm-upgrade.adoc[]

:leveloffset: -1
