[#{cluster-type}-day2-upgrade-controller]
== Upgrade Controller
:revdate: 2025-01-16
:revnumber: 3.4
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[IMPORTANT]
====
`Upgrade Controller`は現在、*非エアギャップ管理*クラスターに対する`Day 2`操作のみをサポートしています。
====

このセクションでは、あるEdgeプラットフォームバージョンから別のバージョンへの `management`クラスターアップグレードに関連する各種`Day 2`操作の実行方法について説明します。

`Day 2`操作は<<components-upgrade-controller,Upgrade Controller>>によって自動化されており、以下が含まれます。

* <<components-slmicro, SUSE Linux Micro>> OSアップグレード

* <<components-rke2>>または<<components-k3s>> Kubernetesアップグレード

* SUSE追加コンポーネント（SUSE Rancher Prime、SUSE Securityなど）のアップグレード

=== 前提条件

`management`クラスターをアップグレードする前に、以下の前提条件を満たす必要があります。

. `SCC registered nodes` - クラスターノードのOSが、アップグレード先のEdge<<release-notes,リリース>>で指定されているOSバージョンをサポートするサブスクリプションキーで登録されていることを確認してください。

. `Upgrade Controller` - `Upgrade Controller`が`management`クラスターにデプロイされていることを確認してください。インストール手順については、<<components-upgrade-controller-installation>>を参照してください。

=== アップグレード

. アップグレードする`management`クラスターのEdge<<release-notes,リリース>>バージョンを決定します。

. `management`クラスターに、目的の`UpgradePlan`を指定する`release version`をデプロイします。`UpgradePlan`は、`Upgrade Controller`のネームスペースにデプロイする必要があります。
+
[,bash]
----
kubectl apply -n <upgrade_controller_namespace> -f - <<EOF
apiVersion: lifecycle.suse.com/v1alpha1
kind: UpgradePlan
metadata:
  name: upgrade-plan-mgmt
spec:
  # Version retrieved from release notes
  releaseVersion: 3.X.Y
EOF
----
+
[NOTE]
====
`UpgradePlan`に対して追加の設定を行いたいユースケースがあるかもしれません。可能なすべての設定については、<<components-upgrade-controller-extensions-upgrade-plan>>を参照してください。
====

. `UpgradePlan`を`Upgrade Controller's`ネームスペースにデプロイすると、`upgrade process`が開始されます。
+
[NOTE]
====
実際の`upgrade process`の詳細については、<<components-upgrade-controller-how>>を参照してください。

`upgrade process`の追跡方法については、<<components-upgrade-controller-how-track>>を参照してください。
====
