[#{cluster-type}-day2-upgrade-controller]
== Upgrade Controller
:revdate: 2025-01-16
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[IMPORTANT]
====
`Upgrade Controller`は現在、*非エアギャップ管理*クラスターに対する`Day 2`操作のみをサポートしています。
====

このセクションでは、`Day 2`クラスターをある`management`プラットフォームバージョンから別のバージョンへアップグレードする際に関連する、さまざまな`{product}`操作の実行方法について説明します。

`Day 2`操作は<<components-upgrade-controller,Upgrade Controller>>によって自動化されており、以下が含まれます。

* <<components-slmicro, SUSE Linux Micro>> OSアップグレード
ifeval::["{flavor}" == "edge"]
* <<components-rke2>>または<<components-k3s>> Kubernetesアップグレード
endif::[]
ifeval::["{flavor}" == "telco"]
* <<components-rke2>> Kubernetesアップグレード
endif::[]
* SUSE追加コンポーネント（SUSE Rancher Prime、SUSE Securityなど）のアップグレード

=== 前提条件

`management`クラスターをアップグレードする前に、以下の前提条件を満たす必要があります。

. `SCC registered nodes` - クラスターノードのOSが、アップグレード先の`{product}`<<release-notes,リリース>>で指定されているOSバージョンをサポートするサブスクリプションキーで登録されていることを確認してください。

. `Upgrade Controller` - `Upgrade Controller`が`management`クラスターにデプロイされていることを確認してください。インストール手順については、<<components-upgrade-controller-installation>>を参照してください。

=== アップグレード

. `{product}`クラスターのアップグレード先となる<<release-notes,リリース>>バージョンを決定します。`management`

. `management`クラスターに、目的の`UpgradePlan`を指定する`release version`をデプロイします。`UpgradePlan`は、`Upgrade Controller`のネームスペースにデプロイする必要があります。
+
[,bash]
----
kubectl apply -n <upgrade_controller_namespace> -f - <<EOF
apiVersion: lifecycle.suse.com/v1alpha1
kind: UpgradePlan
metadata:
  name: upgrade-plan-mgmt
spec:
  # Version retrieved from release notes
  releaseVersion: 3.X.Y
EOF
----
+
[NOTE]
====
`UpgradePlan`に対して追加の設定を行いたいユースケースがあるかもしれません。可能なすべての設定については、<<components-upgrade-controller-extensions-upgrade-plan>>を参照してください。
====

. `UpgradePlan`を`Upgrade Controller's`ネームスペースにデプロイすると、`upgrade process`が開始されます。
+
[NOTE]
====
実際の`upgrade process`の詳細については、<<components-upgrade-controller-how>>を参照してください。

`upgrade process`の追跡方法については、<<components-upgrade-controller-how-track>>を参照してください。
====

=== アップグレード後の手順
最新の`{product}` z-streamから`{previous-edge-version}`への`{static-edge-version}`のアップグレードでは、`Upgrade Controller`がアップグレードプロセスを完了した後に、最終的な手動手順を実行する必要がある場合があります。これらは、`{product}`リリース以降、`{version}`で唯一サポートされるイングレスコントローラーとしてIngress-NGINXをTraefikに置き換えることに関連しています。

[NOTE]
====
RKE2/K3sに統合された`Traefik`イングレスプロバイダーは、`{product} {version}`リリースでサポートされる唯一のイングレスコントローラーです。複雑なイングレス移行シナリオをサポートするために`Ingress-NGINX`と`Traefik`を一時的に並行して実行することは可能ですが、それは`{product}`管理クラスターやダウンストリームクラスターがバージョン`{version}`にアップグレードされた後、かつ移行に必要な期間に限られます。

RKE2 https://docs.rke2.io/reference/ingress_migration[Ingress NGINXからTraefikへの移行] ガイドでは、`Traefik`イングレスコントローラーが廃止された`Ingress-NGINX`に置き換わった後に利用可能なイングレス移行パスの詳細を提供しています。
====

もし、アップグレード開始前の管理クラスターでデフォルトのIngress-NGINXを使用しており、`Traefik`イングレスコントローラーを利用していなかった場合は、アップグレード後に`Traefik`を手動でデプロイする必要があります。

まず、デプロイ済みのIngress-NGINXインスタンスが適切に設定されていることを確認します（例：２つのイングレスコントローラー間でPodの不要なhostPort競合を回避するために）：

[,shell]
----
kubectl apply -f - <<- EOF
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      hostPort:
        enabled: false  # not needed when exposing through a type:LoadBalancer service
      config:
        use-forwarded-headers: "true"
        enable-real-ip: "true"
      publishService:
        enabled: true
      service:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Local
EOF
----

次に、`Traefik`と`rke2-traefik-crd`の両方のHelmチャートをインストールすることで、`rke2-traefik`のデプロイを進めることができます。
[NOTE]
====
以下に示すように`HelmChart`マニフェストを使ってこれらのHelmチャートをデプロイすることで、`Upgrade Controller`が将来の管理クラスターアップグレード時にもこれらのHelmチャートのアップグレードを担うことを保証します。
====

[,shell]
----
kubectl apply -f - <<- EOF
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rke2-traefik-crd
  namespace: kube-system
spec:
  chart: rke2-traefik-crd
  version: {rke2-traefik-crd Helm chart version}
  repo: https://rke2-charts.rancher.io
  bootstrap: false
  failurePolicy: reinstall
  backOffLimit: 20
  targetNamespace: kube-system
  set:
    global.cattle.systemDefaultRegistry: registry.rancher.com
    global.rke2DataDir: /var/lib/rancher/rke2
    global.systemDefaultRegistry: registry.rancher.com
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rke2-traefik
  namespace: kube-system
spec:
  chart: rke2-traefik
  version: {rke2-traefik Helm chart version}
  repo: https://rke2-charts.rancher.io
  bootstrap: false
  failurePolicy: reinstall
  backOffLimit: 20
  targetNamespace: kube-system
  set:
    global.cattle.systemDefaultRegistry: registry.rancher.com
    global.rke2DataDir: /var/lib/rancher/rke2
    global.systemDefaultRegistry: registry.rancher.com
  valuesContent: |-
    ingressClass:
      isDefaultClass: false  # if traefik deployed alongside ingress-nginx
    ports:
      web:
        hostPort: null    # disallow hostPort
        exposedPort: 80
      websecure:
        hostPort: null    # disallow hostPort
        exposedPort: 443
    service:
      enabled: true
      type: LoadBalancer
      spec:
        externalTrafficPolicy: Local
        allocateLoadBalancerNodePorts: false  # k8s GA from 1.24; supported by MetalLB
    providers:
      kubernetesIngressNginx:  # this provider allows traefik to "understand" most of the ingress-nginx annotations
        enabled: true
        ingressClass: "rke2-ingress-nginx-migration"
        controllerClass: "rke2.​cattle.​io/ingress-nginx-migration"
EOF
----

`{rke2-traefik-crd Helm chart version}`と`{rke2-traefik-crd Helm chart version}`は、アップグレードしたRKE2/K3sのバージョンにより定められたものです。

最後のステップでは、LoadBalancerタイプのサービスを通じて`Traefik`サービスを公開するために、MetalLBが必要とするオブジェクトを作成します：

[,shell]
----
kubectl apply -f - <<- EOF
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ingress-ippool-traefik
  namespace: metallb-system
spec:
  addresses:
  - {EXTERNAL_IP_FOR_TRAEFIK_SERVICE}/32
  serviceAllocation:
    priority: 100
    serviceSelectors:
    - matchExpressions:
      - {key: app.kubernetes.io/name, operator: In, values: [rke2-traefik]}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ingress-l2-adv-traefik
  namespace: metallb-system
spec:
  ipAddressPools:
  - ingress-ippool-traefik
EOF
----

これで、`Traefik`と`Ingress-NGINX`が並行して稼働し、一方からもう一方へ安全に必要なイングレスの移行を実施できるようになります。

[IMPORTANT]
====
すべてのイングレスが移行され、`Ingress-NGINX`が不要になったら、不必要なリソース消費を防ぐために、必ずこれをアンインストールし、関連する全てのリソースをクリーンアップしてください。
====