= Documentação do SUSE Edge
:revdate: 2024-03-06
:revnumber: 3.6
:page-revdate: {revdate}

ifdef::env-github[]
:imagesdir: images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Bem-vindo ao repositório de documentação do SUSE Edge.

== Asciidoctor vs Markdown

* https://docs.asciidoctor.org/asciidoc/latest/asciidoc-vs-markdown/#comparison-by-example[Comparação pelo exemplo]

== Recursos do Asciidoctor

Documentação oficial::
* https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/[Referência rápida]
* https://github.com/uyuni-project/uyuni-docs/wiki/asciidoc-getting-started[Introdução]
* https://github.com/powerman/asciidoc-cheatsheet[Folha de dicas]
* https://docs.asciidoctor.org/asciidoc/latest/[Documentação da linguagem Asciidoc]

Exemplos (consulte a versão `raw` para obter o código)::
* https://github.com/openSUSE/daps/blob/main/test/documents/adoc/part_inlines.adoc[Elementos
  em linha]
* https://github.com/openSUSE/daps/blob/main/test/documents/adoc/part_block.adoc[Elementos de bloco]


== Edição e visualização

A documentação é escrita em Asciidoc(tor). Comece com um link:template.adoc[Modelo] muito básico.

* As fontes podem ser editadas e visualizadas diretamente no GitHub.
* Se você editar seus documentos localmente
** https://docs.asciidoctor.org/asciidoctor/latest/tooling/#web-browser-add-ons-preview-only[Complementos de visualização para navegadores Web]
** https://docs.asciidoctor.org/asciidoctor/latest/tooling/#ides-and-text-editors[IDEs e editores de texto]
** Também existem modos asciidoc para emacs e vi ;-)


== Melhores práticas

=== Uma frase por linha

* tornam a edição diretamente no GitHub muito mais fácil e tornam as fontes mais legíveis
* use quebra de linha automática no seu editor


=== Os títulos devem estar em ordem

* sempre inicie um documento com um título de nível 0
  ** use apenas um único título de nível zero
* não é permitido pular um nível com títulos subsequentes

[,asciidoc]
----
= Level 0

== Level 1

=== Level 2

// ===== Level 4: Not allowed

==== Level 3

== Level 1
----


=== Não use IDs automáticos

O Asciidoctor gera automaticamente IDs/âncoras aos quais você pode vincular:

[,asciidoc]
.Não use
----
== Usage
...

Refer to <<usage>> for more information. 
----

Não é recomendado usar este recurso, porque toda vez que você alterar o respectivo título, você precisaria alterar a(s) referência(s) também.
Em vez disso, use IDs/âncoras explícitos:

[,asciidoc]
.Use
----
[#usage]
== Usage
...

Refer to <<usage>> for more information. 
----

=== Sempre use delimitadores de bloco

Alguns elementos de bloco podem ser escritos em uma forma curta e uma longa.
Sempre use a forma longa para evitar confusão e para aumentar a legibilidade das fontes.

[,asciidoc]
.Não use
----
NOTE: This is a note

 This is a literal block
----

[,asciidoc]
.Use
----
[NOTE]
====
This is a note
====

....
This is a literal block
....
----

==== Estruturas aninhadas

Estruturas aninhadas, por exemplo, uma anotação dentro de um item de lista, devem ser concatenadas por um caractere de mais (`+`).

[,asciidoc]
----
* normal listitem
* lisitem with annotation
+
[NOTE]
====
note
====
+
* lisitem with two paragraphs
+
second paragraph
+
* normal listitem
----

=== Teclas, Menus, Botões

O Asciidoctor vem com três macros para exibir teclas, seleção de menu e cliques de botão:

[,asciidoc]
----
Press kbd:[C] to continue or kbd:[Crtl+C] to cancel, kbd:[F1] opens the help menu.

To save the file, select menu:File[Save].
Select menu:View[Zoom > Reset] to reset the zoom level to the default setting.

Press the btn:[OK] button when you are finished.
----

[IMPORTANT]
====
Este recurso só é ativado quando o atributo `:experimental:` é definido no cabeçalho.
====

=== Visualização em abas

Use listas delimitadas/rotuladas precedidas por `[.tabs]`:

[,asciidoc]
----
[.tabs]
TAB 1::
+
Content tab 1
+
TAB 2::
+
Content tab 2
----

=== Instruções de inclusão devem ser separadas por linhas vazias

Sempre certifique-se de que uma instrução de inclusão seja precedida e seguida por uma linha vazia.


== Tags Asciidoc não suportadas

O seguinte não é suportado ao criar uma versão com a marca SUSE.
Não use:

* realce, sublinhado, tachado
+
[,asciidoc]
----
#highlight#
##high##light
[.underline]#underline#
[.line-through]#strike-through#
----
+
* listas de verificação
+
[,asciidoc]
----
* [*] checked
* [x] also checked
* [ ] not checked
----
+
* áudio e vídeo
+
[,asciidoc]
----
audio::audio.wav[]
video:: video.mp4[]
----
+
* barras laterais
+
[,asciidoc]
----
****
Sidebar text
****
----
+
* notas de rodapé
+
[,asciidoc]
----
footnote:[Footnote]
----

== Compilando a documentação 

=== Compilando uma versão genérica

Compilar o livro em uma versão sem a marca SUSE é mais fácil e rápido do que compilar a versão com a marca SUSE.

Extensão para navegador (a maneira mais fácil)::
+
* Instale https://docs.asciidoctor.org/asciidoctor/latest/tooling/#web-browser-add-ons-preview-only[uma extensão de navegador] e visualize edge-book/edge.adoc no seu navegador.
* A pré-visualização é atualizada automaticamente quando as alterações são salvas.
+
Uma compilação HTML local::
+
* Instale o Asciidoctor no seu sistema.
* Execute o seguinte comando no checkout do GitHub.
+
[,bash]
----
asciidoctor -d book --attribute="toc=left" edge-book/edge.adoc
----
+
* Resultado: `edge-book/edge.html`


=== Construindo a versão com a marca SUSE localmente

Para construir a documentação localmente no formato em que será publicada, use https://github.com/openSUSE/daps2docker[daps2docker]
Observe que realizar essas compilações não é necessário para verificar suas contribuições.
Desde que seu documento seja renderizado corretamente nas visualizações, você está pronto.


.Requisitos
* Certifique-se de que sua estação de trabalho esteja executando Docker ou Podman
* certifique-se de que seu usuário possa iniciar contêineres
* instale o daps2docker a partir de https://download.opensuse.org/repositories/Documentation:/Tools/
* navegue até o checkout local deste repositório no diretório de documentação

Building HTML::
`daps2docker DC-edge html`
Building Single HTML::
`daps2docker DC-edge single-html`
Building PDF::
`daps2docker DC-edge pdf`

[TIP]
.Usando Podman
====
Por padrão, o daps2docker usa o Docker como seu mecanismo de contêiner.
Para usar o Podman, exporte a variável de ambiente CONTAINER_ENGINE=podman: `export CONTAINER_ENGINE=podman`
====

[TIP]
.Erros de construção
====
O daps2docker constrói a documentação a partir de fontes DocBook XML.
O Asciidoctor vem com um conversor incorporado para DocBook.

O Asciidoc(tor) é muito mais tolerante que o DocBook quando se trata de validação.
Em alguns casos, o código-fonte asciidoc válido não é validado ao convertê-lo para DocBook.
Nesse caso, a compilação com daps2docker falhará.
Se isso acontecer, entre em contato comigo (@fsundermeyer) e eu ajudarei.
====

=== Para obter mais informações

...veja o https://github.com/openSUSE/daps2docker[repositório daps2docker].
Você também encontrará instruções sobre como instalá-lo em outras distribuições e como definir uma configuração personalizada.

