= Redação Técnica: Melhores práticas
:revdate: 2024-03-06
:revnumber: 3.6
:page-revdate: {revdate}

Cinco regras básicas sobre como escrever uma melhor documentação técnica

== #1 Mude a perspectiva

____
Não me diga como funciona...diga-me como usá-lo!
____

* Sempre se coloque no lugar do seu leitor
** Qual nível de conhecimento exijo que os leitores tenham?
** O que o leitor deseja alcançar?
** Que perguntas o leitor pode ter?
** O que pode dar errado?
* Considere que seus leitores
** têm apenas tempo limitado
** estão frustrados
** estão sob pressão
** trabalham em um ambiente barulhento
** não são falantes nativos


[IMPORTANT]
====
Mais de 80% dos nossos leitores chegam via pesquisa (Google) e provavelmente caem em algum capítulo aleatório do livro.
Certifique-se de sempre fornecer todo o contexto e requisitos necessários no início de um capítulo.
====




== #2 Mantenha Simples e Curto (KISS)

Instruções curtas e simples são mais fáceis de entender e menos propensas a erros.
Isso não é relevante apenas para os leitores, mas também para a localização.

Linguagem simples e clara::
+
* utilize -> *use*
* indique -> *mostre*, *diga*, *fale*
* pré-requisito -> *requisito*
+
Sem palavras de preenchimento::
+
* para -> *para*
* já existente -> *existente*
* completamente novo -> *novo*
* simplesmente faça -> *faça*
* por favor, faça -> *faça*
+
Use o tempo presente::
+
* Execute xxx. A caixa de diálogo yyy aparecerá. -> *Execute xxx. A caixa de diálogo yyy aparece.*
+
Uma ideia, uma frase::
+
Use o YaST, que vem em duas versões (interface X Window e ncurses), para configurar e gerenciar o sistema e para instalar novo software ou atualizações de segurança e patches.
+
->
+
*Use o YaST para configurar e gerenciar o sistema.*
*Use-o também para instalar novo software e para manter seu sistema atualizado.*
*O YaST vem com uma interface de usuário para ser usada no X Window.*
*Para o uso em um terminal, uma interface ncurses está disponível.*
+
Limite a descrição de alternativas::
+
Geralmente, há mais de uma maneira de fazer as coisas.
Limite a documentação à _única_ maneira recomendada e suportada de fazer as coisas.
Documente alternativas apenas quando absolutamente necessário, por exemplo, interface de usuário e linha de comando.

== #3 Estruture a Informação

* Pense no seu documento como um funil: comece com informações gerais e torne-se mais específico à medida que avança
* coloque a informação onde ela importa
** o objetivo e o contexto vêm primeiro
** os requisitos vêm em segundo lugar
** o procedimento vem por último
** avisos e notas precisam ser colocados onde forem relevantes
** O que foi dito acima também se aplica a todas as seções do documento
* Sempre use listas ordenadas para descrever um conjunto de etapas (procedimento)
** não mais que 10 etapas por procedimento (7+/- 2 é o ideal); divida em tarefas diferentes para encurtar
** objetivo, etapas, resultado
* Não coloque nenhuma informação em listagens de programas
** ...porque elas não serão traduzidas
* não use títulos menores que o nível 3 (`==== Level 3 headline`)
* quebre comandos com mais de 80 caracteres em várias linhas

== #4 Seja consistente

Repetições _não_ são ruins::
+
. Execute o comando XXX -> *Execute o comando XXX*
. Execute o comando YYY -> *Execute o comando YYY*
. Execute o comando ZZZ -> *Execute o comando ZZZ*
+
Use terminologia consistente::
+
* link simbólico, link, soft link, symlink -> *link simbólico*
* atualizar vs fazer upgrade
* complemento, addon, add on -> *complemento*

== #5 Evite interrupções

Uma linha de raciocínio::
+
Eles, no entanto, não estão marcados como instalados. -> *No entanto, eles não estão marcados como instalados.*
+
Não separe verbos::
+
Desligue o servidor. -> *Desligue o servidor.*
