[#collecting-diagnostics-for-support]
== Recopilación de diagnósticos para el soporte
:revdate: 17-06-2025
:revnumber: 3,6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

include::../edge-book/versions.adoc[]

Al ponerse en contacto con el soporte de SUSE, es fundamental proporcionar información de diagnóstico completa.

.Información esencial a recopilar

* *Descripción detallada del problema*: ¿Qué ha ocurrido?, ¿cuándo ha ocurrido?, ¿qué estaba haciendo?, ¿cuál es el comportamiento esperado y cuál es el comportamiento real?
* *Pasos para reproducir*: ¿Puede reproducir el problema de forma fiable? En caso afirmativo, enumere los pasos exactos.
* *Versiones de los componentes*: versión de {product}, versiones de los componentes (RKE2/K3, EIB, Metal^3^, Elemental, etc.).
* *Registros relevantes*: 
** Salida de `journalctl` (filtrada por servicio si es posible, o registros de arranque completos).
** Registros de pods de Kubernetes (kubectl logs).
** Registros de los componentes de Metal³/Elemental.
** Registros de compilación de EIB y otros registros
* *Información del sistema*:
** `uname -a`
** `df -h`
** `ip a`
** `/etc/os-release`
* *Archivos de configuración*: Archivos de configuración relevantes para Elemental, Metal^3^, EIB, tales como valores de gráficos helm, configmaps, etc.
* *Información de Kubernetes*: Nodos, servicios, despliegues, etc.
* *Objetos de Kubernetes afectados*: BMH, MachineRegistration, etc.

.Cómo recopilar

* *Para registros*: Redirija la salida del comando a archivos (por ejemplo, `journalctl -u k3s > k3s_logs.txt`).
* *Para recursos de Kubernetes*: Utilice `kubectl get <resource> -o yaml > <resource_name>.yaml` para obtener definiciones YAML detalladas.
* *Para información del sistema*: Recopile la salida de los comandos enumerados anteriormente.
* *For SL Micro*: Consulte la documentación https://documentation.suse.com/sle-micro/5.5/html/SLE-Micro-all/cha-adm-support-slemicro.html[Guía de resolución de problemas de SUSE Linux Micro] sobre cómo recopilar información del sistema para obtener asistencia con `supportconfig`.
* *Para RKE2/Rancher*: Consulte el artículo https://www.suse.com/support/kb/doc/?id=000020191[El script recopilador de registros de Linux de Rancher v2.x] para ejecutar dicho script.

* *Para Edge (Nessie)*: Nessie {version-nessie} es una potente herramienta de diagnóstico diseñada para recopilar registros y datos de configuración de entornos {product}. Recopila información exhaustiva tanto del sistema anfitrión como de los clústeres de Kubernetes, lo que la hace inestimable para la resolución de problemas y la asistencia. 
** Nessie tiene dos «modos»: un modo Kubernetes y un modo de sistema.
*** Para recopilar registros de un clúster {product}, ejecute (siempre que tenga acceso al archivo kubeconfig localmente):
+
[,bash,subs="attributes"]
----
podman run --rm --privileged \
  -v /etc/rancher/k3s/k3s.yaml:/etc/rancher/k3s/k3s.yaml:ro \
  -v /var/log/journal:/var/log/journal:ro \
  -v /run/systemd:/run/systemd:ro \
  -v /etc/machine-id:/etc/machine-id:ro \
  -v /tmp:/tmp \
  -e NESSIE_LOG_DIR="/tmp" \
  -e NESSIE_ZIP_DIR="/tmp" \
  registry.suse.com/edge/{version-edge}/nessie:{version-nessie}
----
+
[NOTE]
====
Ajuste las rutas del archivo `k3s.yaml/rke2.yaml` si es necesario. Consulte https://github.com/suse-edge/support-tools/blob/main/nessie/README.md[Nessie] para obtener más información.
Debería poder ejecutar este contenedor en modo sin privilegios si tiene los permisos adecuados (normalmente los archivos `k3s.yaml` / `rke2-server.yaml` son propiedad de root).
====
*** Para recopilar registros en el modo de sistema desde el sistema operativo real, ejecute:
+
[,bash,subs="attributes"]
----
podman run --rm --privileged \
  -v /var/log/journal:/var/log/journal:ro \
  -v /run/systemd:/run/systemd:ro \
  -v /etc/machine-id:/etc/machine-id:ro \
  -v /tmp:/tmp \
  -e NESSIE_LOG_DIR="/tmp" \
  -e NESSIE_ZIP_DIR="/tmp" \
  -e NESSIE_VERBOSE="1" \
  -e NESSIE_SKIP_POD_LOGS="true" \
  -e NESSIE_SKIP_K8S_CONFIGS="true" \
  -e NESSIE_SKIP_METRICS="true" \
  registry.suse.com/edge/{version-edge}/nessie:{version-nessie}
----
+
[NOTE]
====
Asegúrese de consultar https://github.com/suse-edge/support-tools/blob/main/nessie/README.md[Nessie] para obtener más detalles e información sobre cómo ejecutar Nessie en su entorno.
Asimismo, debería poder ejecutar este contenedor en modo sin privilegios siempre que tenga los permisos adecuados.
====


.Contactar con el soporte
Consulte el artículo disponible en https://www.suse.com/support/kb/doc/?id=000019452[Instrucciones para trabajar eficazmente con el soporte técnico de SUSE] y el manual de soporte ubicado en https://www.suse.com/support/handbook/[Manual de soporte técnico de SUSE] para obtener más detalles sobre cómo ponerse en contacto con el soporte de SUSE.
