[#general-troubleshooting-principles]
== Principios generales de resolución de problemas
:revdate: 17/06/2025
:revnumber: 3,6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Antes de profundizar en problemas específicos de los componentes, considera estos principios generales:

* *Comprobar registros*: Los registros son la fuente principal de información. La mayoría de las veces, los errores se explican por sí mismos y contienen pistas sobre lo que falló.
* *Comprobar relojes*: Tener diferencias de reloj entre sistemas puede provocar todo tipo de errores diferentes. Aseguraos de que los relojes estén sincronizados. Se puede indicar a EIB que fuerce la sincronización del reloj en el momento del arranque, véase <<quickstart-eib,Configuración de la hora del SO>>.
* *Problemas de arranque*: Si el sistema se queda bloqueado durante el arranque, anotad los últimos mensajes mostrados. Acceded a la consola (física o a través de BMC) para observar los mensajes de arranque.
* *Problemas de red*: Verificad la configuración de la interfaz de red (`ip a`), la tabla de enrutamiento (`ip route`), probad la conectividad desde/hacia otros nodos y servicios externos (`ping`, `nc`). Aseguraos de que las reglas del firewall no estén bloqueando los puertos necesarios.
* *Verificar el estado del componente*: Utilizad `kubectl get` y `kubectl describe` para los recursos de Kubernetes. Utilizad `kubectl get events --sort-by='.lastTimestamp' -n <namespace>` para ver los eventos en un espacio de nombres de Kubernetes concreto.
* *Verificar el estado de los servicios*: Utilizad `systemctl status <service>` para los servicios de systemd.
* *Comprobar la sintaxis*: El software espera una estructura y una sintaxis determinadas en los archivos de configuración. Para los archivos yaml, por ejemplo, utilizad `yamllint` o herramientas similares para verificar la sintaxis correcta.
* *Aislar el problema*: Intentad acotar el problema a un componente o capa específicos (por ejemplo, red, almacenamiento, SO, Kubernetes, Metal^3^, Ironic,...).
* *Documentación*: Consultad siempre la https://documentation.suse.com/suse-edge/[{product} documentación] oficial y también la documentación del sentido ascendente para obtener información detallada.
* *Versiones*: {product} es una versión preconfigurada y probada exhaustivamente de diferentes componentes de SUSE. Las versiones de cada componente por cada versión de {product} pueden consultarse en la https://documentation.suse.com/suse-edge/support-matrix/html/support-matrix/index.html[{product} matriz de compatibilidad].
* *Problemas conocidos*: Para cada versión de {product} existe una sección de «Problemas conocidos» en las notas de la versión que contiene información sobre problemas que se corregirán en futuras versiones, pero que pueden afectar a la actual.
