[#troubleshooting-kiwi]
== Solución de problemas de Kiwi
:revdate: 17/06/2025
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Kiwi se utiliza para generar imágenes actualizadas de SUSE Linux Micro que se usarán con Edge Image Builder.

.Problemas comunes

* *SL Micro Version Mismatch*: La versión del sistema operativo del host de compilación debe coincidir con la versión del sistema operativo que se está compilando (host SL Micro 6.0 -> imagen SL Micro 6.0).
* *SELinux en modo exigente*: Debido a ciertas limitaciones, actualmente es necesario desactivar SELinux temporalmente para poder crear imágenes con Kiwi. Comprobad el estado de SELinux con `getenforce` y desactivadlo antes de ejecutar el proceso de compilación con `setenforce 0`.
* *Host de compilación no registrado*: El proceso de compilación utiliza las suscripciones del host de compilación para poder extraer paquetes de SUSE SCC. Si el host no está registrado, fallará.
* *Error en la prueba del dispositivo de bucle*: La primera vez que se ejecuta el proceso de compilación de Kiwi, fallará poco después de iniciarse con \"ERROR: La prueba inicial del dispositivo de bucle falló, por favor, reintentad la ejecución del contenedor. Esto es un síntoma de que se están creando dispositivos de bucle en el sistema host subyacente que no son inmediatamente visibles dentro de la imagen del contenedor. Volved a ejecutar el proceso de compilación de Kiwi y debería continuar sin problemas.
* *Permisos faltantes*: El proceso de compilación requiere ejecutarse como usuario raíz (o mediante sudo).
* *Privilegios incorrectos*: El proceso de compilación requiere el indicador `--privileged` al ejecutar el contenedor. Comprobad dos veces que esté presente.

.Registros

* *Registros del contenedor de compilación*: Comprobad los registros del contenedor de compilación. Los registros se generan en el directorio que se utilizó para almacenar los artefactos. Consultad también los registros de docker o podman para obtener la información necesaria.
* *Directorios de compilación temporales*: Kiwi crea directorios temporales durante el proceso de compilación. Comprobadlos para ver si hay registros o artefactos intermedios si la salida principal es insuficiente.

.Pasos para la solución de problemas

. *Revisad la salida de `build-image`*: El mensaje de error en la salida de la consola suele ser muy indicativo.
. *Comprobad el entorno de compilación*: Aseguraos de que se cumplen todos los requisitos previos para el propio Kiwi (por ejemplo, docker/podman, SELinux, espacio en disco suficiente) en la máquina que ejecuta Kiwi.
. *Inspeccionad los registros del contenedor de compilación*: Revisad los registros del contenedor fallido para obtener errores más detallados (véase más arriba).
. *Verificad el archivo de definición*: Si utilizáis un archivo de definición de imagen de Kiwi personalizado, comprobad de nuevo el archivo por si hubiera errores tipográficos o de sintaxis.

[NOTE]
====
Comprobad la https://documentation.suse.com/appliance/kiwi-9/html/kiwi/troubleshooting.html[Guía de resolución de problemas de Kiwi].
====
