[#troubleshooting-phone-home-scenarios]
== Solución de problemas de escenarios de Phone-Home
:revdate: 2025-06-17
:revnumber: 3,6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Los escenarios de Phone-home implican el uso de Elemental para volver a conectar con el clúster de gestión y EIB para crear una imagen de SO que incluya los bits de registro de Elemental. Pueden producirse problemas cuando el host se inicia por primera vez, durante el proceso de compilación de EIB o al intentar registrarse en el clúster de gestión.

.Problemas comunes

* *El sistema no se registra*: El nodo no se registra en la interfaz de usuario. Aseguraos de que el host se inicie correctamente, de que pueda comunicarse con Rancher, de que el reloj esté sincronizado y de que los servicios de Elemental funcionen correctamente.
* *El sistema no se aprovisiona*: El nodo está registrado pero no se aprovisiona. Aseguraos de que el host pueda comunicarse con Rancher, de que el reloj esté sincronizado y de que los servicios de Elemental funcionen correctamente.


.Registros

* *Registros del sistema*: `journalctl`
* *Registros del agente del sistema Elemental*: `journalctl -u elemental-system-agent`
* *Registros de K3s/RKE2*: `journalctl -u k3s or journalctl -u rke2-server` (o `rke2-agent`)
* *Pod del Operador de Elemental*: `kubectl logs -n cattle-elemental-system -l app=elemental-operator` 

.Pasos para la solución de problemas

. *Revisar registros*: Comprobad los registros del pod del operador de Elemental para ver si hay algún problema. Comprobad los registros del host si el nodo ha arrancado.

. *Comprobad MachineRegistration y TPM*: Por defecto, se utiliza TPM para https://elemental.docs.rancher.com/authentication/[autenticación], pero existen alternativas para hosts sin TPM.

