[#troubleshooting-edge-image-builder]
== Solución de problemas de Edge Image Builder (EIB)
:revdate: 2025-06-17
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

EIB se utiliza para crear imágenes {product} personalizadas.

.Problemas comunes

* *Código SCC incorrecto*: Asegúrese de que el código SCC utilizado en el archivo de definición de EIB coincida con la versión y la arquitectura de SL Micro.
* *Dependencias faltantes*: Asegúrese de que no falten paquetes ni herramientas en el entorno de compilación.
* *Tamaño de imagen incorrecto*: Para imágenes raw, el parámetro `diskSize` es obligatorio y depende en gran medida de las imágenes, los RPM y otros artefactos que se incluyan en la imagen.
* *Permisos*: Si almacena un script en el directorio custom/files, asegúrese de que tenga permisos de ejecución, ya que esos archivos solo están disponibles en el momento de la combustión, pero EIB no realiza cambios. 
* *Dependencias de grupos del sistema operativo*: Al crear una imagen con usuarios y grupos personalizados, los grupos que se establezcan como "`primaryGroup`" deben crearse explícitamente.
* *Las claves ssh de usuario del sistema operativo requieren una carpeta de inicio*: Al crear una imagen con usuarios con claves ssh, la carpeta de inicio también debe crearse con `createHomeDir=true`.
* *Problemas de combustión*: EIB depende de la combustión para la personalización del SO y el despliegue de todos los demás componentes {product}. Esto también incluye los scripts personalizados que se colocan en la carpeta custom/scripts. Tenga en cuenta que el proceso de combustión se ejecuta en el momento `initrd`, por lo que el sistema no está completamente arrancado cuando se ejecutan los scripts.
* *Tamaño de la máquina Podman*: Como se explica en la <<tips-and-tricks,sección de consejos y trucos de EIB>>, verifique que la máquina podman tenga suficiente CPU/memoria para ejecutar el contenedor EIB en sistemas operativos que no sean Linux.
* *Imagen incorrecta*: Asegúrese de que la imagen base que se utiliza se descargue correctamente https://www.suse.com/support/security/download-verification/[verificando el `checksum`]. Si está compilando la imagen con <<guides-kiwi-builder-images,kiwi-builder>>, compruebe también el archivo de suma generado por el proceso.

.Registros

* *Salida de EIB*: La salida de consola del comando `eib build` es crucial.
* *Registros del contenedor de compilación*: Compruebe los registros del contenedor de compilación. Los registros se generan en el directorio que se utilizó para almacenar los artefactos. Consulte también `docker logs` o `podman logs` para obtener la información necesaria.
+
[NOTE]
====
Para obtener más información, consulte https://github.com/suse-edge/edge-image-builder/blob/main/docs/debugging.md[Depuración].
====

* *Directorios de compilación temporales*: EIB crea directorios temporales durante el proceso de compilación. Compruebe estos directorios en busca de registros intermedios o artefactos si la salida principal es insuficiente.
* *Registros de combustión*: Si la imagen que se está creando con EIB no arranca por cualquier motivo, hay disponible una shell de root. Conéctese a la consola del host (ya sea físicamente, a través de BMC, etc.) y compruebe los registros de combustión con `journalctl -u combustion` y, en general, todos los registros del sistema operativo con `journalctl` para encontrar la causa raíz del fallo.


.Pasos para la solución de problemas

. *Revise la salida de `eib-build`*: El mensaje de error en la salida de la consola suele ser muy indicativo.
. *Compruebe el entorno de compilación*: Asegúrese de que se cumplen todos los requisitos previos para el propio EIB (por ejemplo, docker/podman, espacio en disco suficiente) en la máquina que ejecuta EIB.
. *Inspeccione los registros del contenedor de compilación*: Revise los registros del contenedor fallido para obtener errores más detallados (véase más arriba).
. *Verifique la configuración de `eib`*: Compruebe dos veces el archivo de configuración `eib` en busca de errores tipográficos o rutas incorrectas a los archivos de origen o scripts de compilación.
* *Pruebe los componentes individualmente*: Si su compilación de EIB implica scripts o etapas personalizados, ejecútelos de forma independiente para aislar los fallos.

[NOTE]
====
Consulte https://github.com/suse-edge/edge-image-builder/blob/main/docs/debugging.md[Depuración de Edge Image Builder].
====
