= Edge Image Builder

== Common

- If you are in a non-Linux environment and following these instructions to build an image, then you are likely running `Podman` via a virtual machine. By default, this virtual machine will be configured to have a small amount of system resources allocated to it and can cause instability for `Edge Image Builder` during resource intensive operations, such as the RPM resolution process. You will need to adjust the resources of the podman machine, either by using Podman Desktop (settings cogwheel -> podman machine edit icon) or directly  via the `podman-machine-set` https://docs.podman.io/en/stable/markdown/podman-machine-set.1.html[command]
- At this point in time, the `Edge Image Builder` is not able to build images in a cross architecture setup, i.e. you have to run it on:
  * {aarch64} systems (such as Apple Silicon) to build SL Micro `aarch64` images
  * {x86-64} systems to build SL Micro `x86_64` images.


== Kubernetes

- Creating multi node Kubernetes clusters requires adjusting the `kubernetes` section in the definition file to:
  * list all server and agent nodes under `kubernetes.nodes` 
  * set a virtual IP address that would be used for all non-initializer nodes to join the cluster under `kubernetes.network.apiVIP`
  * optionally, set an API host to specify a domain address for accessing the cluster under `kubernetes.network.apiHost`
To learn more about this configuration, please refer to the https://github.com/suse-edge/edge-image-builder/blob/main/docs/building-images.md#kubernetes[Kubernetes section docs].


- `Edge Image Builder` relies on the hostnames of the different nodes to determine their Kubernetes type (`server` or `agent`). While this configuration is managed in the definition file, for the general networking setup of the machines we can utilize either DHCP configuration as described in <<components-nmc>>.
