= *Metal^3^*

.Ironic:
Due to a link:../components/metal3.adoci#L31[known issue], if you are trying to configure predictable names for the target OS netwrok devices and you end up in errors, seeing that the discovered device names have different naming pattern, then you have a couple of options:

1. Go with the discovered device naming pattern (change your configuration for predictable names to the pattern the hardware supports)
2. Use UUIDs as identifiers.

How to get the UUIDs you need:

- In your OpenSUSE or SLES machine install nmc:
`zyper in nm-configurator`

- and then run directly:
`nmc generate --config-dir /path/to/your/config --output-dir /where/you/want/it`
now in the output files you should have the UUIDs that you can use in your configuration.

Alternatively, if you don't use OpenSUSE or SLES, you can use the nmc through the Edge Image Builder container image:
`podman run -it --rm -v $(pwd):/path/to/your/config:Z --entrypoint=/usr/bin/nmc registry.suse.com/edge/3.3/edge-image-builder:1.2.1 generate --config-dir /path/to/your/config --output-dir /where/you/want/it`
