= Edge Image Builder

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://github.com/suse-edge/edge-image-builder[Official Repository]

Edge Image Builder (EIB) is a tool that streamlines the process of generating pre-configured, ready-to-deploy (RTD) disk images for bootstrapping machines, allowing for the end to end deployment of the entire SUSE software stack through a single image.

Additionally, while EIB can create RTD images for all provisioning scenarios, EIB demonstrates tremendous value in air-gapped deployments with limited, or completely isolated networks.


== How does SUSE Edge use Edge Image Builder?

SUSE Edge uses EIB for the simplified and quick configuration of customized SLE Micro images for a variety of scenarios. These scenarios include the bootstrapping of virtual and bare-metal machines with:

* Fully air-gapped deployments of K3s/RKE2 Kubernetes (single & multi-node)
* Fully air-gapped Helm chart and Kubernetes manifest deployments
* Registration to Rancher via Elemental API
* Metal^3^
* Customized Networking (e.g. static IP, hostname, VLAN's, bonding, etc.)
* Customized operating system configurations (e.g. users, groups, passwords, ssh-keys, proxies, NTP, custom SSL certificates, etc.)
* Air-gapped installation of host-level packages (including dependency resolution)
* Registration with SUSE Customer Center (SCC)
* Registration to SUSE Manager for OS management
* Side-loaded RPMs
* Embedded container images
* Kernel command line arguments
* Systemd units to be enabled/disabled at boot-time
* Custom scripts and files for any manual tasks

== Best Practices

=== Getting started

Comprehensive documentation for the usage and testing of Edge Image Builder can be found link:https://github.com/suse-edge/edge-image-builder/blob/main/docs[here].

Additionally, here is a link:../quickstart/eib.adoc[quick-start guide] for Edge Image Builder covering a basic deployment scenario.

== Known issues

* EIB air-gaps Helm charts through templating the Helm charts and parsing all of the images within the template. If a Helm chart does not keep all of its images within the template and instead side-loads the images, EIB will not be able to air-gap those images automatically. The solution to this is to manually add any undetected images to the `embeddedArtifactRegistry` section of the definition file.

* EIB loads all of the necessary artifacts for an air-gapped deployment into the `combustion` directory. The `combustion` directory is loaded into memory at `/dev/shm` at boot time. `/dev/shm` uses half of the memory allocated to the machine. In the scenario where the contents of the `combustion` directory are larger than half of the RAM of the machine, the combustion process will fail with a `no space left on device` error. This issue is currently being worked on, however, in the case of virtual machines, the quickest solution is to allocate more RAM.