[#components-elemental]
= Elemental
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

From the https://elemental.docs.rancher.com/[upstream documentation]

[quote]
____
Elemental is a software stack enabling centralized, full cloud-native OS management with Kubernetes.

The Elemental Stack consists of a handful of packages on top of SLE Micro for Rancher:

* elemental-operator - Connects to Rancher Manager and handles MachineRegistration and MachineInventory CRDs.
* elemental-register - Registers machines via machineRegistrations and installs them via elemental-cli.
* rancher-system-agent - Runs on the installed system and gets instructions ("Plans") from Rancher Manager what to install and run on the system.
____

== How does SUSE Edge use Elemental?

We use portions of Elemental for managing remote devices where Metal^3^ is not an option (e.g. there is no BMC or the device is behind a NAT gateway). This tooling allows for an operator to bootstrap their devices in a lab before knowing when or where they will be shipped to.

We also use it for remote management of a node's OS in a declarative way when Metal^3^ is not an option.

== Best Practices

=== Installation Media

Currently the best way to build a supported Elemental installation disk for SUSE Edge is described in <<quickstart-elemental,the Elemental quickstart>>.

=== Labels

Elemental tracks its inventory with the MachineInventory CRD and provides a way to select inventory based on labels. This provides a way for users to predefine most (if not all) of their infrastructure needs prior to hardware even being purchased.

Also, since nodes can add/remove labels on their respective inventory object (by re-running `elemental-register` with the additional flag `--label "FOO=BAR"`), we can write scripts that will discover and let Elemental/Rancher know where a node is booted.


== Known issues

* The Elemental UI doesn't currently know how to build installation media or update non-"Elemental Teal" operating systems. This should be addressed in future releases.
