[#components-eco]
= Endpoint Copier Operator
:revdate: 2025-02-28
:page-revdate: {revdate}
:experimental:


ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://github.com/suse-edge/endpoint-copier-operator[Endpoint Copier Operator] is a Kubernetes operator whose purpose is to create a copy of a Kubernetes Service and Endpoint and to keep them synced.

== How does SUSE Edge use Endpoint Copier Operator?

At SUSE Edge, the Endpoint Copier Operator plays a crucial role in achieving High Availability (HA) setup for K3s/RKE2 clusters. This is accomplished by creating a `kubernetes-vip` service of type `LoadBalancer`, ensuring its Endpoint remains in constant synchronization with the kubernetes Endpoint. <<components-metallb,MetalLB>> is leveraged to manage the `kubernetes-vip` service, as the exposed IP address is used from other nodes to join the cluster.

== Best Practices

Comprehensive documentation for using the Endpoint Copier Operator can be found https://github.com/suse-edge/endpoint-copier-operator/blob/main/README.md[here].

Additionally, refer to <<guides-metallb-k3s,our guide>>  on achieving a K3s/RKE2 HA setup using the Endpoint Copier Operator and MetalLB.

== Known issues
Presently, the Endpoint Copier Operator is limited to working with only one Service/Endpoint. Enhancements to support multiple Services/Endpoints are planned for the future.
