= K3s

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://k3s.io/[K3s] is a highly available, certified Kubernetes distribution designed for production workloads in unattended, resource-constrained, remote locations or inside IoT appliances.

It is packaged as a single and small binary so installations and updates are fast and easy.

== How does SUSE Edge use K3s

K3s can be used as the Kubernetes distribution backing the SUSE Edge stack.
It is meant to be installed on a SLE Micro operating system.

The use of K3s as the SUSE Edge stack Kubernetes distribution is only recommended when etcd as a backend is not a possibility. If you can use etcd as a backend, use link:./rke2.adoc[RKE2].

== Best practices

=== Installation
The recommended way of installing K3s as part of the SUSE Edge stack is by using Edge Image Builder (EIB), see link:./edge-image-builder.adoc[its documentation] for more details on how to configure it to deploy K3s.

It automatically supports HA setup, as well as Elemental setup.

=== Fleet for GitOps workflow
The SUSE Edge stack uses fleet as its preferred GitOps tool.
For more information around its installation and use, refer to link:./fleet.adoc[the fleet section] in this documentation.

=== Storage management

K3s comes with local-path storage pre-configured, this is suitable for single-node clusters.
For clusters spanning over multiple nodes, it is recommended to use link:./longhorn.adoc[Longhorn]

=== Load Balancing and HA

If you installed K3s using EIB this part is already covered by the EIB documentation in the HA section.

Otherwise, you need to install and configure MetalLB as per our link:../guides/metallb-k3s.adoc[MetalLB documentation].

== Known issues
