[#guides-kiosk]
= Building Kiosks with SUSE Edge
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]



TODO: write intro

In this guide, we will demonstrate how to manage these workloads in a secure, scalable, and maintainable way. 

== Architecture

TODO

== Prerequisites

To run this, you will need a system with:
- SLE Micro 5.5+ 
- Either K3s or RKE2
- Helm installed (if not using EIB or Fleet)
- A display attached (when running in a VM, make sure to use a virtual display instead of just the console)

== Deployment

The preferred way to deploy on Kubernetes is through the helm chart. TODO add link to chart once published. 

We need to install helm first with:
[,bash]
----
curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
----

Once helm is installed, install the chart by running:

[,bash] 
----
helm upgrade --install kiosk --namespace kiosk --create-namespace oci://link-to-chart --version=0.1.0
----

To change the URL that's loaded:

[,bash] 
----
helm upgrade --install kiosk --namespace kiosk --create-namespace oci://link-to-chart --version=0.1.0 --set workload.url=http://<svcname>.svc.<namespace>.cluster.local
----

=== Deployment with Fleet



== Custom Workloads

By default, we run Firefox in kiosk mode and use the "URL"

== Integrations

=== Integration with EIB

With airgapped/disconnected devices, it might be best to use the Edge Image Builder to create an image that installs k3s along with your GUI workload

=== Integration with Akri

If you have more than one node in your cluster, you may want to only run this workload on nodes that have a display attached.

TODO: once I have a flag to use Akri instead of DaemonSet