[#components-slmicro]
= SUSE Linux Micro
:revdate: 2025-01-16
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


See {link-micro-official-docs}[SUSE Linux Micro official documentation]

[quote]
____
SUSE Linux Micro is a lightweight and secure operating system for the edge. It merges the enterprise-hardened components of SUSE Linux Enterprise with the features that developers want in a modern, immutable operating system. As a result, you get a reliable infrastructure platform with best-in-class compliance that is also simple to use.
____

== How does SUSE Edge use SUSE Linux Micro?

We use SUSE Linux Micro as the base operating system for our platform stack. This provides us with a secure, stable and minimal base for building upon.

SUSE Linux Micro is unique in its use of file system (Btrfs) snapshots to allow for easy rollbacks in case something goes wrong with an upgrade. This allows for secure remote upgrades for the entire platform even without physical access in case of issues.

== Best practices

=== Installation media

SUSE Edge uses the <<components-eib,Edge Image Builder>> to preconfigure the SUSE Linux Micro self-install installation image.

=== Local administration

SUSE Linux Micro comes with Cockpit to allow the local management of the host through a Web application.

This service is disabled by default but can be started by enabling the systemd service `cockpit.socket`.
As cockpit forbids root login by default, the creation of a user with administrative privileges is recommended, refer to the {link-micro-official-docs}[SUSE Linux Micro official documentation] for more information.



== Known issues

* There is no desktop environment available in SUSE Linux Micro at the moment but a containerized solution is in development.
