= Longhorn
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Longhorn is a lightweight, reliable, and user-friendly distributed block storage system designed for Kubernetes.
As an open-source project, Longhorn was initially developed by Rancher Labs and is currently incubated under the CNCF.

== Prerequisites

* K3s installed. You can find a guide on how to install it on SLE Micro https://documentation.suse.com/trd/kubernetes/single-html/kubernetes_ri_k3s-slemicro/index.html#id-k3s[here]
* Open-iSCSI
** You can install it on SLE Micro by running `sudo transactional-update pkg install open-iscsi` and rebooting the host.
* Helm

== Install Longhorn

To deploy `Longhorn`, the https://longhorn.io/docs/1.6.0/deploy/install/install-with-helm/#installing-longhorn[Longhorn install] guide can be used.

In this example Helm was used to install longhorn.

* Add the Longhorn Helm repository:

** `helm repo add longhorn https://charts.longhorn.io`

* Fetch the latest charts from the repository:

** `helm repo update`

* Install Longhorn in the longhorn-system namespace.

** `helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace --version 1.6.0`

* To confirm that the deployment succeeded, run:

** `kubectl -n longhorn-system get pod`

[,console]
----
localhost:~ # kubectl -n longhorn-system get pod
NAMESPACE         NAME                                                READY   STATUS      RESTARTS        AGE
longhorn-system   longhorn-ui-5fc9fb76db-z5dc9                        1/1     Running     0               90s
longhorn-system   longhorn-ui-5fc9fb76db-dcb65                        1/1     Running     0               90s
longhorn-system   longhorn-manager-wts2v                              1/1     Running     1 (77s ago)     90s
longhorn-system   longhorn-driver-deployer-5d4f79ddd-fxgcs            1/1     Running     0               90s
longhorn-system   instance-manager-a9bf65a7808a1acd6616bcd4c03d925b   1/1     Running     0               70s
longhorn-system   engine-image-ei-acb7590c-htqmp                      1/1     Running     0               70s
longhorn-system   csi-attacher-5c4bfdcf59-j8xww                       1/1     Running     0               50s
longhorn-system   csi-provisioner-667796df57-l69vh                    1/1     Running     0               50s
longhorn-system   csi-attacher-5c4bfdcf59-xgd5z                       1/1     Running     0               50s
longhorn-system   csi-provisioner-667796df57-dqkfr                    1/1     Running     0               50s
longhorn-system   csi-attacher-5c4bfdcf59-wckt8                       1/1     Running     0               50s
longhorn-system   csi-resizer-694f8f5f64-7n2kq                        1/1     Running     0               50s
longhorn-system   csi-snapshotter-959b69d4b-rp4gk                     1/1     Running     0               50s
longhorn-system   csi-resizer-694f8f5f64-r6ljc                        1/1     Running     0               50s
longhorn-system   csi-resizer-694f8f5f64-k7429                        1/1     Running     0               50s
longhorn-system   csi-snapshotter-959b69d4b-5k8pg                     1/1     Running     0               50s
longhorn-system   csi-provisioner-667796df57-n5w9s                    1/1     Running     0               50s
longhorn-system   csi-snapshotter-959b69d4b-x7b7t                     1/1     Running     0               50s
longhorn-system   longhorn-csi-plugin-bsc8c                           3/3     Running     0               50s
----

== Create Longhorn Volumes

* Longhorn StorageClass Creation

** First, create a Longhorn StorageClass containing parameters for provisioning PVs.
PersistentVolumeClaim (PVC) Creation

*** `kubectl create -f <name_of_file.yaml>`

*** Example values

[,yaml]
----
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"
----

* Create a PVC referencing the StorageClass.

** The Kubernetes master checks the PVC to ensure the resource request can be fulfilled.

*** `kubectl create -f <name_of_file.yaml>`

*** Example values

[,yaml]
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
  namespace: longhorn-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
----

* Pod Deployment

** When the Pod is deployed, the Kubernetes master creates the Longhorn volume and binds it to the Pod if storage is available.

*** `kubectl create -f <name_of_file.yaml>`

*** Example values

[,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: longhorn-system
spec:
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: longhorn-volv-pvc
----

In this example the end result should look something like this:

[,console]
----
localhost:~ # kubectl get storageclass
NAME                   PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-path (default)   rancher.io/local-path   Delete          WaitForFirstConsumer   false                  25h
longhorn (default)     driver.longhorn.io      Delete          Immediate              true                   24h

localhost:~ # kubectl get pvc
NAME                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
longhorn-volv-pvc     Bound    pvc-ad598c98-4cb7-4216-aff6-a52f7e4ea6ac   2Gi        RWO            longhorn       22h

localhost:~ # kubectl get pods -A
NAMESPACE         NAME                                                READY   STATUS      RESTARTS        AGE
longhorn-system   longhorn-ui-5fc9fb76db-z5dc9                        1/1     Running     0               24h
longhorn-system   longhorn-ui-5fc9fb76db-dcb65                        1/1     Running     0               24h
longhorn-system   longhorn-manager-wts2v                              1/1     Running     1 (24h ago)     24h
longhorn-system   longhorn-driver-deployer-5d4f79ddd-fxgcs            1/1     Running     0               24h
longhorn-system   instance-manager-a9bf65a7808a1acd6616bcd4c03d925b   1/1     Running     0               24h
longhorn-system   engine-image-ei-acb7590c-htqmp                      1/1     Running     0               24h
longhorn-system   csi-attacher-5c4bfdcf59-j8xww                       1/1     Running     0               24h
longhorn-system   csi-provisioner-667796df57-l69vh                    1/1     Running     0               24h
longhorn-system   csi-attacher-5c4bfdcf59-xgd5z                       1/1     Running     0               24h
longhorn-system   csi-resizer-694f8f5f64-7n2kq                        1/1     Running     0               24h
longhorn-system   csi-snapshotter-959b69d4b-rp4gk                     1/1     Running     0               24h
longhorn-system   csi-resizer-694f8f5f64-r6ljc                        1/1     Running     0               24h
longhorn-system   csi-resizer-694f8f5f64-k7429                        1/1     Running     0               24h
longhorn-system   csi-snapshotter-959b69d4b-5k8pg                     1/1     Running     0               24h
longhorn-system   csi-provisioner-667796df57-n5w9s                    1/1     Running     0               24h
longhorn-system   csi-snapshotter-959b69d4b-x7b7t                     1/1     Running     0               24h
longhorn-system   longhorn-csi-plugin-bsc8c                           3/3     Running     0               24h
longhorn-system   csi-provisioner-667796df57-dqkfr                    1/1     Running     2 (8m45s ago)   24h
longhorn-system   csi-attacher-5c4bfdcf59-wckt8                       1/1     Running     2 (3m59s ago)   24h
longhorn-system   volume-test                                         1/1     Running     0               22h
----


