[#components-metal3]
= Metal^3^
:revdate: 2024-11-20
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://metal3.io/[Metal^3^] is a CNCF project which provides bare-metal infrastructure
management capabilities for Kubernetes.

Metal^3^ provides Kubernetes-native resources to manage the lifecycle of bare-metal servers
which support management via out-of-band protocols such as https://www.dmtf.org/standards/redfish[Redfish].

It also has mature support for https://cluster-api.sigs.k8s.io/[Cluster API (CAPI)]. 
This enables management of hardware resources across multiple
infrastructure providers via broadly adopted vendor-neutral APIs. 
Cluster API uses Metal^3^ as an infrastructure backend for Machine objects.  

== How does SUSE Edge use Metal^3^?

SUSE Edge uses Metal^3^ to manage the lifecycle of physical hardware, such as
servers. The hardware needs to support an out-of-band management protocol that
is supported by Metal^3^ (e.g. Redfish). When a SUSE Edge management cluster
provisions or deprovisions downstream clusters, Metal^3^ will interact with a
server's BMC via Redfish. The following actions are typically part of this
interaction: +

* Mount and umount Virtual Media.
* Power on, power off, and reset servers.

This approach is useful for scenarios where the target hardware supports out-of-band management, and a fully automated infrastructure management flow is desired.

Metal^3^ and CAPI provide declarative APIs that enable inventory and state
management of bare-metal servers, including automated inspection, cleaning, and
provisioning/deprovisioning.

== Known issues

* The upstream https://github.com/metal3-io/ip-address-manager[IP Address Management controller] is currently not supported, because it is not yet compatible with our choice of network configuration tooling. However the `ipam-controller-manager` pod hosted on the `metal3-ipam-system` namespace is needed as CAPM3 requires the `ipam` CRDs to exist.
* Relatedly, the IPAM resources and Metal3DataTemplate networkData fields are not supported.
* Only deployment via redfish-virtualmedia is currently supported.
