= Metal³
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://metal3.io/[Metal^3^] is a CNCF project which provides baremetal infrastructure
management capabilities for Kubernetes.

Metal^3^ provides Kubernetes-native resources to manage the lifecycle of baremetal servers
which support management via out-of-band protocols such as https://www.dmtf.org/standards/redfish[Redfish].

It also has mature support for https://cluster-api.sigs.k8s.io/[Cluster API (CAPI)] which enables management
of infrastructure resources across multiple infrastructure providers via a broadly adopted vendor-neutral APIs.

== How does SUSE Edge use Metal3?

This method is useful for scenarios where the target hardware supports out-of-band management, and a fully-automated
infrastructure management flow is desired.

This method provides declarative APIs that enable inventory and state management of baremetal servers, including
automated inspection, cleaning and provisioning/deprovisioning.

== Known Issues

* The upstream [IP Address Management controller](https://github.com/metal3-io/ip-address-manager) is currently not supported, because it's not yet compatible with our choice of network configuration tooling.
* Relatedly, the IPAM resources and Metal3DataTemplate networkData fields are not supported
* Only deployment via redfish-virtualmedia is currently supported
