[#components-metallb]
= MetalLB
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

See https://metallb.universe.tf/[MetalLB official documentation].

[quote]
____
MetalLB is a load-balancer implementation for bare-metal Kubernetes clusters, using standard routing protocols.

In bare-metal environments, setting up network load balancers is notably more complex than in cloud environments. Unlike the straightforward API calls in cloud setups, bare-metal requires either dedicated network appliances or a combination of load balancers and Virtual IP (VIP) configurations to manage High Availability (HA) or address the potential Single Point of Failure (SPOF) inherent in a single node load balancer. These configurations are not easily automated, posing challenges in Kubernetes deployments where components dynamically scale up and down.

MetalLB addresses these challenges by harnessing the Kubernetes model to create LoadBalancer type services as if they were operating in a cloud environment, even on bare-metal setups.

There are two different approaches, via https://metallb.universe.tf/concepts/layer2/[L2 mode] (using ARP _tricks_) or via https://metallb.universe.tf/concepts/bgp/[BGP]. Mainly L2 does not need any special network gear but BGP is in general better. It depends on the use cases.
____

== How does SUSE Edge use MetalLB?

SUSE Edge uses MetalLB in two key ways:

* As a Load Balancer Solution: MetalLB serves as the Load Balancer solution for bare-metal machines.
* For an HA K3s/RKE2 Setup: MetalLB allows for load balancing the Kubernetes API using a Virtual IP address.

[NOTE]
====
In order to be able to expose the API, the `endpoint-copier-operator` is used to keep in sync the K8s API endpoints from the 'kubernetes' service to a 'kubernetes-vip' LoadBalancer service. 
====

== Best practices
Installation of MetalLB in L2 mode is detailed in <<guides-metallb-k3s,the MetalLB guide>>.

A guide on installing MetalLB in front of the kube-api-server to achieve HA setups can be found in the <<guides-metallb-kubernetes,MetalLB in front of the Kubernetes API server>> tutorial.


== Known issues

* K3S LoadBalancer Solution: K3S comes with its Load Balancer solution, `Klipper`. To use MetalLB, Klipper must be disabled. This can be done by starting the K3s server with the `--disable servicelb` option, as described in the https://docs.k3s.io/networking[K3s documentation].
