[#components-metal3]
= Metal^3^
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://metal3.io/[Metal^3^] is a CNCF project which provides bare-metal infrastructure
management capabilities for Kubernetes.

Metal^3^ provides Kubernetes-native resources to manage the lifecycle of bare-metal servers
which support management via out-of-band protocols such as https://www.dmtf.org/standards/redfish[Redfish].

It also has mature support for https://cluster-api.sigs.k8s.io/[Cluster API (CAPI)] which enables management
of infrastructure resources across multiple infrastructure providers via broadly adopted vendor-neutral APIs.

== How does SUSE Edge use Metal^3^?

This method is useful for scenarios where the target hardware supports out-of-band management, and a fully automated
infrastructure management flow is desired.

This method provides declarative APIs that enable inventory and state management of bare-metal servers, including
automated inspection, cleaning and provisioning/deprovisioning.

== Known issues

* The upstream https://github.com/metal3-io/ip-address-manager[IP Address Management controller] is currently not supported, because it is not yet compatible with our choice of network configuration tooling.
* Relatedly, the IPAM resources and Metal3DataTemplate networkData fields are not supported.
* Only deployment via redfish-virtualmedia is currently supported.
* It is possible to observe a network device name misalignment between the ironic python agent (IPA) and the target operating system (SL Micro 6.0/6.1), especially when trying to configure predictable names for the devices.

This happens because the kernel of the ironic python agent (IPA) is not currently aligned with the kernel of the target operating system (SL Micro 6.0/6.1), therefore there's a misalignment in the network drivers that allows the IPA to discover network devices in a different naming pattern than SL Micro expects.

It is recommended to create two different secrets with the network configuration, one to be used with the IPA using the device names as IPA will discover and use it as `preprovisioningNetworkDataName` on the `BareMetalHost` definition and another secret with the device names as SL Micro will discover and use it as `networkData.name` on the `BareMetalHost` definition.

You can see an example in the link:..tips/metal3.adoc[tips and tricks] section.
