[#components-suse-security]
= https://www.suse.com/products/rancher/security/[SUSE Security]
:revdate: 2025-01-16
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]



SUSE Security is a security solution for Kubernetes that provides L7 network security, runtime security, supply chain security, and compliance checks in a cohesive package.

SUSE Security is a product that is deployed as a platform of multiple containers, each communicating over various ports and interfaces. Under the hood, it uses NeuVector as its underlying container security component. The following containers make up the SUSE Security platform:

* Manager. A stateless container which presents the Web-based console. Typically, only
one is needed and this can run anywhere. Failure of the Manager does not affect any of
the operations of the controller or enforcer. However, certain notifications (events) and
recent connection data are cached in memory by the Manager so viewing of these would
be affected.
* Controller. The ‘control plane’ for SUSE Security must be deployed in an HA
configuration, so configuration is not lost in a node failure. These can run anywhere,
although customers often choose to place these on ‘management’, master or
infra nodes because of their criticality.
* Enforcer. This container is deployed as a DaemonSet so one Enforcer is on every node to
be protected. Typically deploys to every worker node but scheduling can be enabled for
master and infra nodes to deploy there as well. Note: If the Enforcer is not on a cluster node
and connections come from a pod on that node, SUSE Security labels them as ‘unmanaged’ workloads.
* Scanner. Performs the vulnerability scanning using the built-in CVE database, as
directed by the Controller. Multiple scanners can be deployed to increase scanning
capacity. Scanners can run anywhere but are often run on the nodes where the controllers
run. See below for sizing considerations of scanner nodes. A scanner can also be invoked
independently when used for build-phase scanning, for example, within a pipeline that triggers a scan, retrieves the results, and stops the scanner. The scanner contains the latest CVE database so
should be updated daily.
* Updater. The updater triggers an update of the scanner through a Kubernetes cron job
when an update of the CVE database is desired. Please be sure to configure this for your
environment.


A more in-depth SUSE Security onboarding and best practices documentation can be found https://open-docs.neuvector.com/[here].

== How does SUSE Edge use SUSE Security?

SUSE Edge provides a leaner configuration of SUSE Security as a starting point for edge deployments.

== Important notes

* The `Scanner` container must have enough memory to pull the
image to be scanned into memory and expand it. To scan images exceeding 1 GB, increase the scanner's memory to slightly above the largest expected image size.

* High network connections expected in Protect mode. The `Enforcer` requires CPU and
memory when in Protect (inline firewall blocking) mode to hold and inspect connections
and possible payload (DLP). Increasing memory and dedicating a CPU core to the
`Enforcer` can ensure adequate packet filtering capacity.

== Installing with Edge Image Builder

SUSE Edge is using <<components-eib>> in order to customize base SUSE Linux Micro OS images.
Follow <<suse-security-install>> for an air-gapped installation of SUSE Security on top of Kubernetes clusters provisioned by EIB.
