[#components-neuvector]
= NeuVector
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]



NeuVector is a security solution for Kubernetes that provides L7 network security, runtime security, supply chain security, and compliance checking all in a cohesive package. 

NeuVector is deployed as a platform of several containers, all of which communicate to each on various ports and interfaces. The following are the different containers deployed:

* Manager. A stateless container which presents the web-based console. Typically, only
one is needed and this can run anywhere. Failure of the Manager does not affect any of
the operations of the controller or enforcer. However, some notifications (events) and
recent connection data are cached in memory by the manager so viewing of these would
be affected.
* Controller. The ‘control plane’ for NeuVector, should be deployed in an HA
configuration so configuration is not lost in a node failure. These can run anywhere,
although in many cases customers choose to place these on ‘management’, master or
infra nodes because of their criticality.
* Enforcer. This container is deployed as a daemonset so one Enforcer is on every node to
be protected. Typically deploys to every worker node but scheduling can be enabled for
master and infra nodes to deploy there as well. Note: If the Enforcer is not on a node in
the cluster and connections come from a pod on that node, these are displayed as
‘unmanaged’ workloads in NeuVector.
* Scanner. Performs the vulnerability scanning using the built-in CVE database, as
directed by the Controller. Multiple scanners can be deployed to increase scanning
capacity. Scanners can run anywhere but are often run on the nodes where the controllers
run. See below for sizing considerations of scanner nodes. A scanner can also be invoked
independently when used for build-phase scanning such in a pipeline that triggers a scan,
retrieves results, and stops the scanner. The scanner contains the latest CVE database so
should be updated daily.
* Updater. The updater triggers an update of the scanner through a Kubernetes cron job
when an update of the CVE database is desired. Please be sure to configure this for your
environment.


A more in depth NeuVector oboarding and best practices doc can be found https://open-docs.neuvector.com/deploying/production/NV_Onboarding_5.0.pdf[here].

== How does SUSE Edge use NeuVector?

SUSE Edge provides a leaner configuration of NeuVector as a starting point for edge deployments. 

These changes to the NeuVector configuration can be found https://github.com/suse-edge/charts/blob/main/packages/neuvector-core/generated-changes/patch/values.yaml.patch[here].

== Important Notes

* The Scanner container must have enough memory to pull the
image to be scanned into memory and expand it. If images larger than 1GB are to be
scanned, increase memory to the scanner to slightly higher than the largest expected
image size.

* High network connections expected in Protect mode. The Enforcer requires CPU and
memory when in Protect (inline firewall blocking) mode to hold and inspect connections
and possible payload (DLP). Increasing memory and dedicating a CPU core to the
Enforcer can ensure adequate packet filtering capacity.

