= NeuVector
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


NeuVector is a security solution for Kubernetes that provides L7 network security, runtime security, supply chain security, and compliance checking all in a cohesive package. 

NeuVector is deployed as a platform of several containers, all of which communicate to each on various ports and interfaces.

== How does SUSE Edge use NeuVector?

SUSE Edge uses a customized NeuVector Helm chart for securing Kubernetes in various deployments. 

The SUSE Edge NeuVector Helm charts can be found https://github.com/suse-edge/charts[here].

== Best Practices

When installing NeuVector into an edge environment with constrained resources, we recommend turning off a few of the components. 

These components are defaulted to off in the SUSE Edge version of the chart.

These specified configurations can be found https://github.com/suse-edge/charts/blob/main/charts/neuvector-core/2.6.6/values.yaml[here].

== Important Notes

* The Scanner container must have enough memory to pull the
image to be scanned into memory and expand it. If images larger than 1GB are to be
scanned, increase memory to the scanner to slightly higher than the largest expected
image size.

* High network connections expected in Protect mode. The Enforcer requires CPU and
memory when in Protect (inline firewall blocking) mode to hold and inspect connections
and possible payload (DLP). Increasing memory and dedicating a CPU core to the
Enforcer can ensure adequate packet filtering capacity.

