[#components-nmc]
= Edge Networking

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

In this section we’re going to describe the approach SUSE Edge undertakes to customize the various different networking options on your edge nodes.
Modern Linux distributions (incl. SLE Micro) are leveraging NetworkManager to suit their configuration needs.

At the time of this writing, SUSE Edge Networking is not a standalone product. This guide will, however, dive deep into
what it consists of, how it is integrated into the SUSE Edge solution and how it can be used outside of it.

== NetworkManager overview

NetworkManager is a program that manages the primary network connection and other connection interfaces.
It is handled by systemd and is shipped with all necessary service unit files.

NetworkManager stores all network configurations as connections, which are a collection of data that describes how to create or connect to a network.
These connections are stored as files in the `/etc/NetworkManager/system-connections/` directory.

Details about NetworkManager can be found in the https://documentation.suse.com/sle-micro/5.5/html/SLE-Micro-all/cha-nm-configuration.html[upstream SLE Micro documentation].

== nmstate overview

There are different solutions attempting to automate and manage host networking and one of the most popular ones is nmstate.
It is a library (with an accompanying CLI tool) which offers a declarative API for network configurations via a predefined schema.

Details about nmstate can be found in the https://nmstate.io/[upstream documentation].

== Enter: NetworkManager Configurator (nmc)

Edge Networking is achieved via a CLI tool called NetworkManager Configurator or _nmc_ in short.
It is leveraging the functionality provided by the nmstate library and as such it is fully capable of
configuring static IP addresses, DNS servers, VLANs, bonding, bridges, etc.
This tool allows us to generate network configurations from predefined desired states and to apply those across many different nodes in an automated fashion.

Details about the NetworkManager Configurator (nmc) can be found in the https://github.com/suse-edge/nm-configurator[upstream repository].

== How does SUSE Edge use NetworkManager Configurator?

SUSE Edge utilizes _nmc_ for the network customizations in the various different provisioning models:

* Custom network configurations in the Direct Network Provisioning scenarios (<<quickstart-metal3>>)
* Declarative static configurations in the Image Based Provisioning scenarios (<<quickstart-eib>>)
