[#components-rke2]
= RKE2

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

See https://docs.rke2.io/[RKE2 official documentation].

RKE2 is a fully conformant Kubernetes distribution that focuses on security and compliance by:

* Providing defaults and configuration options that allow clusters to pass the CIS Kubernetes Benchmark v1.6 or v1.23 with minimal operator intervention
* Enabling FIPS 140-2 compliance
* Regularly scanning components for CVEs using https://trivy.dev[trivy] in the RKE2 build pipeline

RKE2 launches control plane components as static pods, managed by kubelet. The embedded container runtime is containerd.

Note: RKE2 is also known as RKE Government in order to convey another use case and sector it currently targets.

== RKE2 vs K3s

K3s is a fully compliant and lightweight Kubernetes distribution focused on Edge, IoT, ARM - optimized for ease of use and resource constrained environments.

RKE2 combines the best of both worlds from the 1.x version of RKE (hereafter referred to as RKE1) and K3s.

From K3s, it inherits the usability, ease of operation and deployment model.

From RKE1, it inherits close alignment with upstream Kubernetes. In places, K3s has diverged from upstream Kubernetes in order to optimize for edge deployments, but RKE1 and RKE2 can stay closely aligned with upstream.

== How does SUSE Edge use RKE2?

RKE2 is a fundamental piece of the SUSE Edge stack. It sits on top of
<<components-slmicro,SUSE Linux Micro>>, providing a standard Kubernetes interface required to deploy Edge workloads.

== Best practices

=== Installation

The recommended way of installing RKE2 as part of the SUSE Edge stack is by using Edge Image Builder (EIB). See the <<components-eib,EIB documentation>> for more details on how to configure it to deploy RKE2.

EIB is flexible enough to support any parameter required by RKE2, such as specifying the RKE2 version, the https://docs.rke2.io/reference/server_config[servers] or the https://docs.rke2.io/reference/linux_agent_config[agents] configuration, covering all the Edge use cases.

For other use cases involving Metal^3^, RKE2 is also being used and installed. In those particular cases, the https://github.com/rancher-sandbox/cluster-api-provider-rke2[Cluster API Provider RKE2] automatically deploys RKE2 on clusters being provisioned with Metal^3^ using the Edge Stack.

In those cases, the RKE2 configuration must be applied on the different CRDs involved. An example of how to provide a different CNI using the `RKE2ControlPlane` CRD looks like:

[,yaml]
----
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: RKE2ControlPlane
metadata:
  name: single-node-cluster
  namespace: default
spec:
  serverConfig:
    cni: calico
    cniMultusEnable: true
...
----

For more information about the Metal^3^ use cases, see <<components-metal3>>.

=== High availability

For HA deployments, EIB automatically deploys and configures
<<components-metallb,MetalLB>> and the link:https://github.com/suse-edge/endpoint-copier-operator[Endpoint Copier Operator] to expose the RKE2 API endpoint externally.

=== Networking

The supported CNI for the Edge Stack is https://docs.cilium.io/en/stable/[Cilium] with optionally adding the meta-plugin https://github.com/k8snetworkplumbingwg/multus-cni[Multus], but RKE2 supports https://docs.rke2.io/install/network_options[a few others] as well.

=== Storage

RKE2 does not provide any kind of persistent storage class or operators. For clusters spanning over multiple nodes, it is recommended to use <<components-longhorn,Longhorn>>.

