= SLE Micro
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


Via the https://documentation.suse.com/sle-micro/5.5/[Official docs]

[quote]
____
SUSE Linux Enterprise Micro is a lightweight and secure operating system for the edge. It merges the enterprise-hardened components of SUSE Linux Enterprise with the features that developers want in a modern, immutable operating system. As a result, you get a reliable infrastructure platform with best-in-class compliance that is also simple to use.
____

== How does SUSE Edge use SLE Micro?

We use SLE Micro as the base Operating System for our platform stack. This provides us with a secure, stable, and minimal starting point to start building on.

SLE Micro is unique in it's use of filesystem (btrfs) snapshots to allow for easy rollbacks in the case of something going wrong with an upgrade. This allows for more confidence in remotely upgrading the entire platform even when there is no ability to physically access the system in the case of a problem. 

== Best Practices

TODO

== Known Issues

TODO