[#components-rancher-turtles]
= Rancher Turtles
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


See Rancher Turtles documentation at https://documentation.suse.com/cloudnative/cluster-api/

[quote]
____
Rancher Turtles is a Kubernetes Operator that provides integration between Rancher Manager and Cluster API (CAPI) with the aim of bringing full CAPI support to Rancher
____


== Key Features of Rancher Turtles

* Automatically import CAPI clusters into Rancher, by installing the Rancher Cluster Agent in CAPI provisioned clusters.
* Install and configure CAPI controller dependencies via the https://cluster-api-operator.sigs.k8s.io/[CAPI Operator].

== Rancher Turtles use in SUSE Edge

The SUSE Edge stack provides a helm wrapper chart which installs Rancher Turtles with a specific configuration that enables:

* Core CAPI controller components
* RKE2 Control Plane and Bootstrap provider components
* <<components-metal3,Metal3>> infrastructure provider components

Only the default providers installed via the wrapper chart are supported - alternative Control Plane, Bootstrap and Infrastructure providers are not currently supported as part of the SUSE Edge stack.

== Installing Rancher Turtles

Rancher Turtles may be installed by following the <<quickstart-metal3,Metal3 Quickstart>> guide, or the <<atip-management-cluster,Management Cluster>> documentation.

== Additional Resources

* https://rancher.com/docs/[Rancher Documentation]
* https://cluster-api.sigs.k8s.io/[Cluster API Book]
