[#components-rancher-turtles]
= Rancher Turtles
:revdate: 2025-12-15
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


See Rancher Turtles documentation at https://documentation.suse.com/cloudnative/cluster-api/

[quote]
____
Rancher Turtles is a Kubernetes Operator that provides integration between Rancher Manager and Cluster API (CAPI) with the aim of bringing full CAPI support to Rancher
____


== Key Features of Rancher Turtles

* Automatically import CAPI clusters into Rancher, by installing the Rancher Cluster Agent in CAPI provisioned clusters.
* Install and configure CAPI controller dependencies via the https://cluster-api-operator.sigs.k8s.io/[CAPI Operator].
* Manage installed CAPI provider dependencies via the `CAPIProvider` API

== Rancher Turtles use in SUSE Edge

The SUSE Edge stack provides a `rancher-turtles-providers` helm chart that enables certain CAPI providers via the `CAPIProvider` API:

* RKE2 Control Plane and Bootstrap provider
* <<components-metal3,Metal3>> infrastructure provider
* <<components-metal3,Metal3>> IPAM provider (currently not supported)
* Fleet addon provider

Only the default providers installed via the wrapper chart are supported - alternative Control Plane, Bootstrap and Infrastructure providers are not currently supported as part of the SUSE Edge stack.

== Installing Rancher Turtles

Since Rancher 2.13, Rancher Turtles is enabled by default when installing Rancher.

Rancher Turtles Providers may be installed by following the <<quickstart-metal3,Metal3 Quickstart>> guide, or the <<atip-management-cluster,Management Cluster>> documentation.

== Additional Resources

* https://rancher.com/docs/[Rancher Documentation]
* https://cluster-api.sigs.k8s.io/[Cluster API Book]
