[#components-upgrade-controller]
= Upgrade Controller
:revdate: 2025-05-20
:page-revdate: {revdate}

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

A Kubernetes controller capable of performing upgrades over the following SUSE Edge platform components:

* Operating System (SUSE Linux Micro)
* Kubernetes (K3s & RKE2)
* Additional components (Rancher, Elemental, SUSE Security, etc.)

The link:https://github.com/suse-edge/upgrade-controller[Upgrade Controller] streamlines the upgrade process for the components mentioned above by encapsulating their complexities within a single `user-facing` resource that serves as a *trigger* for the upgrade. Users only need to configure this resource and the `Upgrade Controller` takes care of the rest.

[NOTE]
====
The `Upgrade Controller` currently supports SUSE Edge platform upgrades only for *non air-gapped management* clusters. Refer to the <<components-upgrade-controller-known-issues>> section for more information.
====

== How does SUSE Edge use Upgrade Controller?

The *Upgrade Controller* is essential in automating the (formerly manual) "Day 2" operations required to upgrade management clusters from one SUSE Edge release version to the next.

To achieve this automation, the Upgrade Controller utilizes tools such as the <<components-system-upgrade-controller, System Upgrade Controller>> and the link:https://github.com/k3s-io/helm-controller/[Helm Controller]. 

For further details on how the Upgrade Controller works, see <<components-upgrade-controller-how>>.

For known limitations that the Upgrade Controller has, see <<components-upgrade-controller-known-issues>>.

For information on the difference between the Upgrade Controller and the System Upgrade Controller, see <<components-upgrade-controller-uc-vs-suc>>.

[#components-upgrade-controller-uc-vs-suc]
== Upgrade Controller vs System Upgrade Controller

The <<components-system-upgrade-controller, System Upgrade Controller (SUC)>> is a general-purpose tool that propagates upgrade instructions to specific Kubernetes nodes.

While it supports some "Day 2" operations for the SUSE Edge platform, it *does not* cover all of them. Moreover, even for supported operations, users have to manually configure, maintain, and deploy multiple `SUC Plans` — an error-prone process that can lead to unexpected issues.

This led to the need for a tool that **automates** and **abstracts** the complexity of managing various "Day 2" operations for the SUSE Edge platform. Thus, the `Upgrade Controller` was developed. It simplifies the upgrade process by introducing a single `user-facing resource` that drives the upgrade. Users only need to manage this resource, while the `Upgrade Controller` takes care of the rest.

[#components-upgrade-controller-installation]
== Installing the Upgrade Controller

=== Prerequisites

* link:https://helm.sh/docs/intro/install/[Helm]

* link:{link-cert-manager-installation}[cert-manager]

* <<components-system-upgrade-controller-install, System Upgrade Controller>>

* A Kubernetes cluster; either K3s or RKE2

=== Steps

. Install the Upgrade Controller Helm chart on your management cluster:
+
[,bash,subs="attributes"]
----
helm install upgrade-controller oci://registry.suse.com/edge/charts/upgrade-controller --version {version-upgrade-controller-chart} --create-namespace --namespace upgrade-controller-system
----

. Validate the Upgrade Controller deployment:
+
[,bash]
----
kubectl get deployment -n upgrade-controller-system
----

. Validate the Upgrade Controller pod:
+
[,bash]
----
kubectl get pods -n upgrade-controller-system
----

. Validate the Upgrade Controller pod logs:
+
[,bash]
----
kubectl logs <pod_name> -n upgrade-controller-system
----

[#components-upgrade-controller-installation-eib]
== Installing the Upgrade Controller via Edge Image Builder

As an alternative to the manual installation described above, it is possible to install the upgrade controller as part of the inital deployment orchestrated by <<components-eib, Edge Image Builder>>.

In this case it is necessary to add the following helm chart configuration to the EIB configuration file:

[,yaml]
----
kubernetes:
  helm:
    charts:
      - name: cert-manager
        repositoryName: jetstack
        version: {version-cert-manager}
        targetNamespace: cert-manager
        valuesFile: certmanager-values.yaml
        createNamespace: true
        installationNamespace: kube-system
      - name: upgrade-controller
        version: {version-upgrade-controller-chart}
        repositoryName: suse-edge-charts
        targetNamespace: upgrade-controller-system
        createNamespace: true
        installationNamespace: kube-system
----

[#components-upgrade-controller-how]
== How does the Upgrade Controller work?

In order to perform an Edge release upgrade, the Upgrade Controller introduces two new Kubernetes link:https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[custom resources]:

* <<components-upgrade-controller-extensions-upgrade-plan, UpgradePlan>> - created by the user; holds configurations regarding an Edge release upgrade.

* <<components-upgrade-controller-extensions-release-manifest, ReleaseManifest>> - created by the Upgrade Controller; holds component versions specific to a particular Edge release version. *This file must not be edited by users.*

The Upgrade Controller proceeds to create a `ReleaseManifest` resource that holds the component data for the Edge release version specified by the user under the `releaseVersion` property in the `UpgradePlan` resource.

Using the component data from the `ReleaseManifest`, the Upgrade Controller proceeds to upgrade the Edge release components in the following order:

. <<components-upgrade-controller-how-os, Operating System (OS)>>.

. <<components-upgrade-controller-how-k8s, Kubernetes>>.

. <<components-upgrade-controller-how-additional, Additional components>>.

[NOTE]
====
During the upgrade process, the Upgrade Controller continually outputs upgrade information to the created `UpgradePlan`. For more information on how to track the upgrade process, see <<components-upgrade-controller-how-track, Tracking the upgrade process>>.
====

[#components-upgrade-controller-how-os]
=== Operating System upgrade

To upgrade the operating system, the Upgrade Controller creates <<components-system-upgrade-controller, SUC>> Plans that have the following naming template:

* For SUC Plans related to control plane node OS upgrades - `control-plane-<os-name>-<os-version>-<suffix>`.

* For SUC Plans related to worker node OS upgrades - `workers-<os-name>-<os-version>-<suffix>`.

Based on these plans, SUC proceeds to create workloads on each node of the cluster that perform the actual OS upgrade.

Depending on the `ReleaseManifest`, the OS upgrade may include:

* Package only updates - for use-cases where the OS version does not change between Edge releases.

* Full OS migration - for use-cases where the OS version changes between Edge releases.

The upgrade is executed *one* node at a time starting with the control plane nodes first. Only if the control-plane node upgrade finishes will the worker nodes begin to be upgraded.

[NOTE]
====
The Upgrade Controller configures the OS SUC Plans to do perform a link:https://kubernetes.io/docs/reference/kubectl/generated/kubectl_drain/[drain] of the cluster nodes if the cluster has more than *one* node of the specified type.

For clusters where the control plane nodes are *greater than* one and there is *only one* worker node, a drain will be performed only for the control plane nodes and vice versa.

For information on how to disable node drains altogether, see the <<components-upgrade-controller-extensions-upgrade-plan, UpgradePlan>> section.
====

[#components-upgrade-controller-how-k8s]
=== Kubernetes upgrade

To upgrade the Kubernetes distribution of a cluster, the Upgrade Controller creates <<components-system-upgrade-controller, SUC>> Plans that have the following naming template:

* For SUC Plans related to control plane node Kubernetes upgrades - `control-plane-<k8s-version>-<suffix>`.

* For SUC Plans related to worker node Kubernetes upgrades - `workers-<k8s-version>-<suffix>`.

Based on these plans, SUC proceeds to create workloads on each node of the cluster that perform the actual Kubernetes upgrade.

The Kubernetes upgrade will happen *one* node at a time starting with the control plane nodes first. Only if the control plane node upgrade finishes will the worker nodes begin to be upgraded.

[NOTE]
====
The Upgrade Controller configures the Kubernetes SUC Plans to perform a link:https://kubernetes.io/docs/reference/kubectl/generated/kubectl_drain/[drain] of the cluster nodes if the cluster has more than *one* node of the specified type.

For clusters where the control plane nodes are *greater than* one and there is *only one* worker node, a drain will be performed only for the control plane nodes and vice versa.

For information on how to disable node drains altogether, see <<components-upgrade-controller-extensions-upgrade-plan>>.
====

[#components-upgrade-controller-how-additional]
=== Additional components upgrades

Currently, all additional components are installed via Helm charts. For a full list of the components for a specific release, refer to the <<release-notes, Release Notes>>.

For Helm charts deployed through <<components-eib, EIB>>, the Upgrade Controller updates the existing link:https://docs.rke2.io/helm#using-the-helm-crd[HelmChart CR] of each component.

For Helm charts deployed outside of EIB, the Upgrade Controller creates a `HelmChart` resource for each component.

After the creation/update of the `HelmChart` resource, the Upgrade Controller relies on the link:https://github.com/k3s-io/helm-controller/[helm-controller] to pick up this change and proceed with the actual component upgrade.

Charts will be upgraded sequentially based on their order in the `ReleaseManifest`. Additional values can also be passed through the `UpgradePlan`. If a chart's version remains unchanged in the new SUSE Edge release, it will not be upgraded. For more information about this, refer to <<components-upgrade-controller-extensions-upgrade-plan>>.

[#components-upgrade-controller-extensions]
== Kubernetes API extensions

Extensions to the Kubernetes API introduced by the Upgrade Controller.

[#components-upgrade-controller-extensions-upgrade-plan]
=== UpgradePlan

The Upgrade Controller introduces a new Kubernetes link:https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[custom resource] called an `UpgradePlan`.

The `UpgradePlan` serves as an instruction mechanism for the Upgrade Controller and it supports the following configurations:

* `releaseVersion` - Edge release version to which the cluster should be upgraded to. The release version must follow link:https://semver.org[semantic] versioning and should be retrieved from the <<release-notes, Release Notes>>.

* `disableDrain` - *Optional*; instructs the Upgrade Controller on whether to disable node link:https://kubernetes.io/docs/reference/kubectl/generated/kubectl_drain/[drains]. Useful for when you have workloads with link:https://kubernetes.io/docs/tasks/run-application/configure-pdb/[Disruption Budgets].

** Example for control plane node drain disablement:
+
[,yaml]
----
spec:
  disableDrain:
    controlPlane: true
----

** Example for control plane and worker node drain disablement:
+
[,yaml]
----
spec:
  disableDrain:
    controlPlane: true
    worker: true
----

* `helm` - *Optional*; specifies additional values for components installed via Helm.
+
[WARNING]
====
It is only advised to use this field for values that are critical for upgrades. Standard chart value updates should be performed after the respective charts have been upgraded to the next version.
====

** Example:
+
[,yaml]
----
spec:
  helm:
  - chart: foo
    values:
      bar: baz
----

[#components-upgrade-controller-extensions-release-manifest]
=== ReleaseManifest

The Upgrade Controller introduces a new Kubernetes link:https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[custom resource] called a `ReleaseManifest`.

The `ReleaseManifest` resource is created by the Upgrade Controller and holds component data for *one* specific Edge release version. This means that each Edge release version upgrade will be represented by a different `ReleaseManifest` resource.

[WARNING]
====
The Release Manifest should always be created by the Upgrade Controller. 

It is not advisable to manually create or edit the `ReleaseManifest` resources. Users that decide to do so should do this *at their own risk*.
====

Component data that the Release Manifest ships include, but is not limited to:

* Operating System data - version, supported architectures, additional upgrade data, etc.

* Kubernetes distribution data - link:https://docs.rke2.io[RKE2]/link:https://k3s.io[K3s] supported versions

* Additional components data - SUSE Helm chart data (location, version, name, etc.)

For an example of how a Release Manifest can look, refer to the {link-lifecycle-example}[upstream] documentation. _Please note that this is just an example and it is not intended to be created as a valid `ReleaseManifest` resource._

[#components-upgrade-controller-how-track]
== Tracking the upgrade process

This section serves as means to track and debug the upgrade process that the Upgrade Controller initiates once the user creates an `UpgradePlan` resource.

[#components-upgrade-controller-how-track-general]
=== General

General information about the state of the upgrade process can be viewed in the Upgrade Plan's status conditions.

The Upgrade Plan resource's status can be viewed in the following way:
[,bash]
----
kubectl get upgradeplan <upgradeplan_name> -n upgrade-controller-system -o yaml
----

.Running Upgrade Plan example:
[,yaml,subs="attributes"]
----
apiVersion: lifecycle.suse.com/v1alpha1
kind: UpgradePlan
metadata:
  name: upgrade-plan-mgmt
  namespace: upgrade-controller-system
spec:
  releaseVersion: {version-edge}
status:
  conditions:
  - lastTransitionTime: "2024-10-01T06:26:27Z"
    message: Control plane nodes are being upgraded
    reason: InProgress
    status: "False"
    type: OSUpgraded
  - lastTransitionTime: "2024-10-01T06:26:27Z"
    message: Kubernetes upgrade is not yet started
    reason: Pending
    status: Unknown
    type: KubernetesUpgraded
  - lastTransitionTime: "2024-10-01T06:26:27Z"
    message: Rancher upgrade is not yet started
    reason: Pending
    status: Unknown
    type: RancherUpgraded
  - lastTransitionTime: "2024-10-01T06:26:27Z"
    message: Longhorn upgrade is not yet started
    reason: Pending
    status: Unknown
    type: LonghornUpgraded
  - lastTransitionTime: "2024-10-01T06:26:27Z"
    message: MetalLB upgrade is not yet started
    reason: Pending
    status: Unknown
    type: MetalLBUpgraded
  - lastTransitionTime: "2024-10-01T06:26:27Z"
    message: CDI upgrade is not yet started
    reason: Pending
    status: Unknown
    type: CDIUpgraded
  - lastTransitionTime: "2024-10-01T06:26:27Z"
    message: KubeVirt upgrade is not yet started
    reason: Pending
    status: Unknown
    type: KubeVirtUpgraded
  - lastTransitionTime: "2024-10-01T06:26:27Z"
    message: NeuVector upgrade is not yet started
    reason: Pending
    status: Unknown
    type: NeuVectorUpgraded
  - lastTransitionTime: "2024-10-01T06:26:27Z"
    message: EndpointCopierOperator upgrade is not yet started
    reason: Pending
    status: Unknown
    type: EndpointCopierOperatorUpgraded
  - lastTransitionTime: "2024-10-01T06:26:27Z"
    message: Elemental upgrade is not yet started
    reason: Pending
    status: Unknown
    type: ElementalUpgraded
  - lastTransitionTime: "2024-10-01T06:26:27Z"
    message: SRIOV upgrade is not yet started
    reason: Pending
    status: Unknown
    type: SRIOVUpgraded
  - lastTransitionTime: "2024-10-01T06:26:27Z"
    message: Metal3 upgrade is not yet started
    reason: Pending
    status: Unknown
    type: Metal3Upgraded
  - lastTransitionTime: "2024-10-01T06:26:27Z"
    message: RancherTurtles upgrade is not yet started
    reason: Pending
    status: Unknown
    type: RancherTurtlesUpgraded
  observedGeneration: 1
  sucNameSuffix: 90315a2b6d
----

Here you can view every component that the Upgrade Controller will try to schedule an upgrade for. Each condition follows the below template:

* `lastTransitionTime` - the last time that this component condition has transitioned from one status to another.

* `message` - message that indicates the current upgrade state of the specific component condition.

* `reason` - the current upgrade state of the specific component condition. Possible `reasons` include:

** `Succeeded` - upgrade of the specific component is successful.

** `Failed` - upgrade of the specific component has failed.

** `InProgress` - upgrade of the specific component is currently in progress.

** `Pending` - upgrade of the specific component is not yet scheduled.

** `Skipped` - specific component is not found on the cluster, so its upgrade will be skipped.

** `Error` - specific component has encountered a transient error.
 
* `status` - status of the current condition `type`, one of `True`, `False`, `Unknown`.

* `type` - indicator for the currently upgraded component.

The Upgrade Controller creates SUC Plans for component conditions of type `OSUpgraded` and `KubernetesUpgraded`. To further track the SUC Plans created for these components, refer to <<components-system-upgrade-controller-monitor-plans>>.

All other component condition types can be further tracked by viewing the resources created for them by the link:https://github.com/k3s-io/helm-controller/[helm-controller]. For more information, see
<<components-upgrade-controller-how-track-helm>>.

An Upgrade Plan scheduled by the Upgrade Controller can be marked as `successful` once:

. There are no `Pending` or `InProgress` component conditions.

. The `lastSuccessfulReleaseVersion` property points to the `releaseVersion` that is specified in the Upgrade Plan's configuration. _This property is added to the Upgrade Plan's status by the Upgrade Controller once the upgrade process is successful._

.Successful `UpgradePlan` example:
[,yaml,subs="attributes"]
----
apiVersion: lifecycle.suse.com/v1alpha1
kind: UpgradePlan
metadata:
  name: upgrade-plan-mgmt
  namespace: upgrade-controller-system
spec:
  releaseVersion: {version-edge}
status:
  conditions:
  - lastTransitionTime: "2024-10-01T06:26:48Z"
    message: All cluster nodes are upgraded
    reason: Succeeded
    status: "True"
    type: OSUpgraded
  - lastTransitionTime: "2024-10-01T06:26:59Z"
    message: All cluster nodes are upgraded
    reason: Succeeded
    status: "True"
    type: KubernetesUpgraded
  - lastTransitionTime: "2024-10-01T06:27:13Z"
    message: Chart rancher upgrade succeeded
    reason: Succeeded
    status: "True"
    type: RancherUpgraded
  - lastTransitionTime: "2024-10-01T06:27:13Z"
    message: Chart longhorn is not installed
    reason: Skipped
    status: "False"
    type: LonghornUpgraded
  - lastTransitionTime: "2024-10-01T06:27:13Z"
    message: Specified version of chart metallb is already installed
    reason: Skipped
    status: "False"
    type: MetalLBUpgraded
  - lastTransitionTime: "2024-10-01T06:27:13Z"
    message: Chart cdi is not installed
    reason: Skipped
    status: "False"
    type: CDIUpgraded
  - lastTransitionTime: "2024-10-01T06:27:13Z"
    message: Chart kubevirt is not installed
    reason: Skipped
    status: "False"
    type: KubeVirtUpgraded
  - lastTransitionTime: "2024-10-01T06:27:13Z"
    message: Chart neuvector-crd is not installed
    reason: Skipped
    status: "False"
    type: NeuVectorUpgraded
  - lastTransitionTime: "2024-10-01T06:27:14Z"
    message: Specified version of chart endpoint-copier-operator is already installed
    reason: Skipped
    status: "False"
    type: EndpointCopierOperatorUpgraded
  - lastTransitionTime: "2024-10-01T06:27:14Z"
    message: Chart elemental-operator upgrade succeeded
    reason: Succeeded
    status: "True"
    type: ElementalUpgraded
  - lastTransitionTime: "2024-10-01T06:27:15Z"
    message: Chart sriov-crd is not installed
    reason: Skipped
    status: "False"
    type: SRIOVUpgraded
  - lastTransitionTime: "2024-10-01T06:27:19Z"
    message: Chart metal3 is not installed
    reason: Skipped
    status: "False"
    type: Metal3Upgraded
  - lastTransitionTime: "2024-10-01T06:27:27Z"
    message: Chart rancher-turtles is not installed
    reason: Skipped
    status: "False"
    type: RancherTurtlesUpgraded
  lastSuccessfulReleaseVersion: {version-edge}
  observedGeneration: 1
  sucNameSuffix: 90315a2b6d
----

[#components-upgrade-controller-how-track-helm]
=== Helm Controller

This section covers how to track resources created by the link:https://github.com/k3s-io/helm-controller/[helm-controller].

[NOTE]
====
The below steps assume that `kubectl` has been configured to connect to the cluster where the Upgrade Controller has been deployed to.
====

. Locate the `HelmChart` resource for the specific component:
+
[,bash]
----
kubectl get helmcharts -n kube-system
----

. Using the name of the `HelmChart` resource, locate the upgrade Pod that was created by the `helm-controller`:
+
[,bash]
----
kubectl get pods -l helmcharts.helm.cattle.io/chart=<helmchart_name> -n kube-system

# Example for Rancher
kubectl get pods -l helmcharts.helm.cattle.io/chart=rancher -n kube-system
NAME                         READY   STATUS      RESTARTS   AGE
helm-install-rancher-tv9wn   0/1     Completed   0          16m
----

. View the logs of the component specific pod:
+
[,bash]
----
kubectl logs <pod_name> -n kube-system
----

[#components-upgrade-controller-known-issues]
== Known Limitations

* Downstream cluster upgrades are not yet managed by the Upgrade Controller. For information on how to upgrade downstream clusters, refer to <<day2-downstream-clusters>>.

* The Upgrade Controller expects any additional SUSE Edge Helm charts that are deployed through <<components-eib,EIB>> to have their link:https://docs.rke2.io/helm#using-the-helm-crd[HelmChart CR] deployed in the `kube-system` namespace. To do this, configure the `installationNamespace` property in your EIB definition file. For more information, see the link:https://github.com/suse-edge/edge-image-builder/blob/main/docs/building-images.md#kubernetes[upstream] documentation.

* Currently the Upgrade Controller has no way to determine the current running Edge release version on the management cluster. Ensure to provide an Edge release version that is greater than the currently running Edge release version on the cluster.

* Currently the Upgrade Controller supports *non air-gapped* environment upgrades only. *Air-gapped* upgrades are not yet possible.
