[#tips-edge-image-builder]
= Edge Image Builder
:revdate: 2025-03-26
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


== Comum

- Se você estiver em um ambiente que não seja Linux e estiver seguindo estas instruções para criar uma imagem, provavelmente está executando o `Podman` por meio de uma máquina virtual. Por padrão, esta máquina virtual será configurada para ter uma pequena quantidade de recursos do sistema alocados a ela, o que pode causar instabilidade para o `Edge Image Builder` durante operações que exigem muitos recursos, como o processo de resolução de RPM. Você precisará ajustar os recursos da máquina podman, usando o Podman Desktop (ícone de engrenagem de configurações -> ícone de edição da máquina podman) ou diretamente via `podman-machine-set` https://docs.podman.io/en/stable/markdown/podman-machine-set.1.html[comando]
- Neste momento, o `Edge Image Builder` não é capaz de criar imagens em uma configuração de arquitetura cruzada, ou seja, você precisa executá-lo em:
  * {aarch64}sistemas (como Apple Silicon) para criar imagens do SL Micro `aarch64`
  * {x86-64}sistemas para criar imagens do SL Micro `x86_64`.

== SUSE Linux Micro

- O carregamento de módulos do kernel na inicialização pode ser feito usando o `/etc/modprobe.d/module.conf`arquivo correspondente. Crie a `os-files`pasta correspondente usando o Edge Image Builder:

[,console]
----
.
├── definition.yaml
└── os-files
    └── etc
        └── modprobe.d
            └── module.conf
----

Para mais informações, consulte a https://documentation.suse.com/sles/15-SP7/html/SLES-all/cha-mod.html#sec-mod-modprobe-d[seção "Managing kernel modules" da documentação do SUSE Linux Enterprise Server]

== Kubernetes

- A criação de clusters Kubernetes com vários nós requer o ajuste da `kubernetes`seção no arquivo de definição para:
  * listar todos os nós de servidor e agente em `kubernetes.nodes` 
  * definir um endereço IP virtual que será utilizado para que todos os nós que não são inicializadores se juntem ao cluster em `kubernetes.network.apiVIP`
  * Opcionalmente, defina um host de API para especificar um endereço de domínio para acessar o cluster em `kubernetes.network.apiHost`
Para saber mais sobre essa configuração, consulte a https://github.com/suse-edge/edge-image-builder/blob/main/docs/building-images.md#kubernetes[documentação da seção Kubernetes].


- O `Edge Image Builder` depende dos nomes de host dos diferentes nós para determinar seu tipo de Kubernetes (`server` ou `agent`). Embora essa configuração seja gerenciada no arquivo de definição, para a configuração de rede das máquinas, podemos utilizar o DHCP conforme descrito em <<components-nmc>>.
