[#collecting-diagnostics-for-support]
== Coleta de diagnósticos para suporte
:revdate: 2025-06-17
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

include::../edge-book/versions.adoc[]

Ao entrar em contato com o Suporte da SUSE, fornecer informações de diagnóstico abrangentes é crucial.

.Informações essenciais a serem coletadas

* *Descrição detalhada do problema*: O que aconteceu, quando aconteceu, o que você estava fazendo, qual é o comportamento esperado e qual é o comportamento real?
* *Passos para reproduzir*: Você consegue reproduzir o problema de forma confiável? Se sim, liste os passos exatos.
* *Versões dos componentes*: {product} versão, versões dos componentes (RKE2/K3, EIB, Metal^3^, Elemental,..).
* *Logs relevantes*: 
** `journalctl` saída (filtrada por serviço, se possível, ou logs de inicialização completos).
** Logs de pod do Kubernetes (kubectl logs).
** Logs de componentes Metal³/Elemental.
** Logs de compilação do EIB e outros logs
* *Informações sobre o sistema*:
** `uname -a`
** `df -h`
** `ip a`
** `/etc/os-release`
* *Arquivos de configuração*: Arquivos de configuração relevantes para Elemental, Metal^3^, EIB, como valores de helm chart, configmaps, etc.
* *Informações do Kubernetes*: Nós, Serviços, Implantações, etc.
* *Objetos do Kubernetes afetados*: BMH, MachineRegistration, etc.

.Como coletar

* *Para logs*: Redirecione a saída do comando para arquivos (por exemplo, `journalctl -u k3s > k3s_logs.txt`).
* *Para recursos do Kubernetes*: Use `kubectl get <resource> -o yaml > <resource_name>.yaml` para obter definições YAML detalhadas.
* *Para informações do sistema*: Colete a saída dos comandos listados acima.
* *Para SL Micro*: Consulte a documentação https://documentation.suse.com/sle-micro/5.5/html/SLE-Micro-all/cha-adm-support-slemicro.html[SUSE Linux Micro Troubleshooting Guide] sobre como coletar informações do sistema para suporte com `supportconfig`.
* *Para RKE2/Rancher*: Consulte o artigo https://www.suse.com/support/kb/doc/?id=000020191[The Rancher v2.x Linux log collector script] para executar o script de coleta de logs do Rancher v2.x Linux.

* *Para Edge (Nessie)*: O Nessie {version-nessie} é uma ferramenta de diagnóstico poderosa projetada para coletar logs e dados de configuração de ambientes {product}. Ele reúne informações abrangentes tanto do sistema host quanto dos clusters Kubernetes, tornando-o inestimável para solução de problemas e suporte. 
** O Nessie possui dois "modos": um modo kubernetes e um modo de sistema.
*** Para coletar logs de um cluster {product}, execute (desde que você tenha acesso ao arquivo kubeconfig localmente):
+
[,bash,subs="attributes"]
----
podman run --rm --privileged \
  -v /etc/rancher/k3s/k3s.yaml:/etc/rancher/k3s/k3s.yaml:ro \
  -v /var/log/journal:/var/log/journal:ro \
  -v /run/systemd:/run/systemd:ro \
  -v /etc/machine-id:/etc/machine-id:ro \
  -v /tmp:/tmp \
  -e NESSIE_LOG_DIR="/tmp" \
  -e NESSIE_ZIP_DIR="/tmp" \
  registry.suse.com/edge/{version-edge}/nessie:{version-nessie}
----
+
[NOTE]
====
Ajuste os caminhos do arquivo `k3s.yaml/rke2.yaml`, se necessário. Consulte https://github.com/suse-edge/support-tools/blob/main/nessie/README.md[Nessie] para obter mais informações.
Você deve conseguir executar este contêiner em modo não privilegiado se tiver as permissões adequadas (normalmente os arquivos `k3s.yaml` / `rke2-server.yaml` pertencem ao [root]).
====
*** Para coletar logs no modo de sistema a partir do sistema operacional real, execute:
+
[,bash,subs="attributes"]
----
podman run --rm --privileged \
  -v /var/log/journal:/var/log/journal:ro \
  -v /run/systemd:/run/systemd:ro \
  -v /etc/machine-id:/etc/machine-id:ro \
  -v /tmp:/tmp \
  -e NESSIE_LOG_DIR="/tmp" \
  -e NESSIE_ZIP_DIR="/tmp" \
  -e NESSIE_VERBOSE="1" \
  -e NESSIE_SKIP_POD_LOGS="true" \
  -e NESSIE_SKIP_K8S_CONFIGS="true" \
  -e NESSIE_SKIP_METRICS="true" \
  registry.suse.com/edge/{version-edge}/nessie:{version-nessie}
----
+
[NOTE]
====
Certifique-se de verificar https://github.com/suse-edge/support-tools/blob/main/nessie/README.md[Nessie] para obter mais detalhes e informações sobre como executar o Nessie em seu ambiente.
Da mesma forma, você deve conseguir executar este contêiner em modo não privilegiado, desde que tenha as permissões adequadas.
====


.Contatar Suporte
Verifique o artigo disponível em https://www.suse.com/support/kb/doc/?id=000019452[Procedimentos para trabalhar efetivamente com o Suporte Técnico da SUSE] e o manual de suporte localizado em https://www.suse.com/support/handbook/[SUSE Technical Support Handbook] para obter mais detalhes sobre como entrar em contato com o suporte da SUSE.
