[#general-troubleshooting-principles]
== Princípios Gerais de Solução de Problemas
:revdate: 2025-06-17
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Antes de mergulhar em problemas específicos de componentes, considere estes princípios gerais:

* *Verificar logs*: Os logs são a principal fonte de informação. Na maioria das vezes, os erros são autoexplicativos e contêm dicas sobre o que falhou.
* *Verificar relógios*: Ter diferenças de relógio entre sistemas pode levar a todos os tipos de erros diferentes. Certifique-se de que os relógios estejam sincronizados. O EIB pode ser instruído a forçar a sincronização do relógio no momento da inicialização, veja <<quickstart-eib,Configurando a Hora do SO>>.
* *Problemas de Inicialização*: Se o sistema travar durante a inicialização, anote as últimas mensagens exibidas. Acesse o console (físico ou via BMC) para observar as mensagens de inicialização.
* *Problemas de Rede*: Verifique a configuração da interface de rede (`ip a`), a tabela de roteamento (`ip route`), teste a conectividade de/para outros nós e serviços externos (`ping`, `nc`). Certifique-se de que as regras do gateway de segurança não estejam bloqueando portas necessárias.
* *Verificar status do componente*: Use `kubectl get` e `kubectl describe` para recursos do Kubernetes. Use `kubectl get events --sort-by='.lastTimestamp' -n <namespace>` para ver os eventos em um namespace específico do Kubernetes.
* *Verificar status dos serviços*: Use `systemctl status <service>` para serviços do systemd.
* *Verifique a sintaxe*: O software espera uma determinada estrutura e sintaxe nos arquivos de configuração. Para arquivos yaml, por exemplo, use `yamllint` ou ferramentas similares para verificar a sintaxe correta.
* *Isole o problema*: Tente restringir o problema a um componente ou camada específica (por exemplo, rede, armazenamento, SO, Kubernetes, Metal^3^, Ironic,...).
* *Documentação*: Consulte sempre a https://documentation.suse.com/suse-edge/[{product} documentação] oficial e também a documentação upstream para obter informações detalhadas.
* *Versões*: {product} é uma versão opinativa e minuciosamente testada de diferentes componentes SUSE. As versões de cada componente por versão do {product} podem ser observadas na https://documentation.suse.com/suse-edge/support-matrix/html/support-matrix/index.html[{product} matriz de suporte].
* *Problemas conhecidos*: Para cada versão do {product}, há uma seção “Problemas conhecidos” nas notas de versão que contém informações sobre problemas que serão corrigidos em versões futuras, mas que podem afetar a atual.
