[#troubleshooting-kiwi]
== Solucionando problemas do Kiwi
:revdate: 2025-06-17
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

O Kiwi é usado para gerar imagens atualizadas do SUSE Linux Micro para serem usadas com o Edge Image Builder.

.Problemas comuns

* *Incompatibilidade de versão do SL Micro*: A versão do sistema operacional do host de build deve corresponder à versão do sistema operacional que está sendo compilada (host SL Micro 6.0 -> imagem SL Micro 6.0).
* *SELinux em modo enforcing*: Devido a certas limitações, atualmente é necessário desativar o SELinux temporariamente para conseguir gerar imagens com o Kiwi. Verifique o status do SELinux com `getenforce` e desative-o antes de executar o processo de build com `setenforce 0`.
* *Host de build não registrado*: O processo de build usa as assinaturas do host de build para conseguir extrair pacotes do SUSE SCC. Se o host não estiver registrado, ele falhará.
* *Falha no teste do dispositivo de loop*: Na primeira vez que o processo de build do Kiwi for executado, ele falhará logo após o início com \"ERROR: Falha no teste inicial do dispositivo de loop, por favor, tente novamente executar o contêiner.", este é um sintoma de dispositivos de loop sendo criados no sistema host subjacente que não são imediatamente visíveis dentro da imagem do contêiner. Execute o processo de build do Kiwi novamente e ele deverá prosseguir sem problemas.
* *Permissões ausentes*: O processo de build espera ser executado como usuário root (ou via sudo).
* *Privilégios incorretos*: O processo de build espera a flag `--privileged` ao executar o contêiner. Verifique novamente se ela está presente.

.Registros

* *Logs do contêiner de build*: Verifique os logs do contêiner de build. Os logs são gerados no diretório que foi usado para armazenar os artefatos. Verifique também os logs do docker ou os logs do podman para obter as informações necessárias.
* *Diretórios de build temporários*: O Kiwi cria diretórios temporários durante o processo de build. Verifique-os em busca de logs ou artefatos intermediários se a saída principal for insuficiente.

.Etapas de solução de problemas

. *Revisar saída do `build-image`*: A mensagem de erro na saída do console geralmente é muito indicativa.
. *Verificar ambiente de build*: Certifique-se de que todos os pré-requisitos para o próprio Kiwi (por exemplo, docker/podman, SELinux, espaço em disco suficiente) sejam atendidos na máquina que executa o Kiwi.
. *Inspecionar logs do contêiner de build*: Revise os logs do contêiner que falhou para obter erros mais detalhados (veja acima).
. *Verificar arquivo de definição*: Se você estiver usando um arquivo de definição de imagem Kiwi personalizado, verifique novamente o arquivo em busca de erros de digitação ou sintaxe.

[NOTE]
====
Verifique o https://documentation.suse.com/appliance/kiwi-9/html/kiwi/troubleshooting.html[Guia de solução de problemas do Kiwi].
====
