[#troubleshooting-edge-image-builder]
== Solução de problemas do Edge Image Builder (EIB)
:revdate: 2025-06-17
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

O EIB é usado para criar {product} imagens personalizadas.

.Problemas comuns

* *Código SCC incorreto*: Certifique-se de que o código SCC usado no arquivo de definição do EIB corresponda à versão e arquitetura do SL Micro.
* *Dependências ausentes*: Certifique-se de que não haja pacotes ou ferramentas ausentes no ambiente de compilação.
* *Tamanho de imagem incorreto*: Para imagens raw, o parâmetro `diskSize` é obrigatório e depende muito das imagens, RPMs e outros artefatos incluídos na imagem.
* *Permissões*: Se armazenar um script no diretório custom/files, certifique-se de que ele tenha permissões de execução, pois esses arquivos ficam disponíveis apenas no momento da combustão, mas nenhuma alteração é realizada pelo EIB. 
* *Dependências de grupo do sistema operacional*: Ao criar uma imagem com usuários e grupos personalizados, os grupos definidos como "`primaryGroup`" devem ser criados explicitamente.
* *As chaves SSH do usuário do sistema operacional exigem uma pasta home*: Ao criar uma imagem com usuários com chaves SSH, a pasta home também precisa ser criada com `createHomeDir=true`.
* *Problemas de combustão*: O EIB depende da combustão para a personalização do SO e a implantação de todos os outros componentes {product}. Isso também inclui scripts personalizados sendo colocados na pasta custom/scripts. Observe que o processo de combustão está sendo executado no momento `initrd`, portanto, o sistema não está completamente inicializado quando os scripts são executados.
* *Tamanho da máquina Podman*: Conforme explicado na <<tips-and-tricks,seção de Dicas e Truques do EIB>>, verifique se a máquina podman tem CPU/memória suficiente para executar o contêiner EIB em sistemas operacionais que não sejam Linux.
* *Imagem incorreta*: Certifique-se de que a imagem base sendo usada esteja corretamente baixada https://www.suse.com/support/security/download-verification/[verificando o `checksum`]. Se você estiver criando a imagem com <<guides-kiwi-builder-images,kiwi-builder>>, verifique também o arquivo de soma gerado pelo processo.

.Registros

* *Saída do EIB*: A saída do console do comando `eib build` é crucial.
* *Logs do contêiner de compilação*: Verifique os logs do contêiner de compilação. Os logs são gerados no diretório que foi usado para armazenar os artefatos. Verifique `docker logs` ou `podman logs` para obter as informações necessárias também.
+
[NOTE]
====
Para obter mais informações, consulte https://github.com/suse-edge/edge-image-builder/blob/main/docs/debugging.md[Depuração].
====

* *Diretórios temporários de compilação*: O EIB cria diretórios temporários durante o processo de compilação. Verifique-os em busca de logs intermediários ou artefatos se a saída principal for insuficiente.
* *Logs de combustão*: Se a imagem sendo criada com o EIB não inicializar por qualquer motivo, um shell root estará disponível. Conecte-se ao console do host (seja fisicamente, via BMC, etc.) e verifique os logs de combustão com `journalctl -u combustion` e, em geral, todos os logs do sistema operacional com `journalctl` para encontrar a causa raiz da falha.


.Etapas de solução de problemas

. *Analise a saída de `eib-build`*: A mensagem de erro na saída do console geralmente é muito indicativa.
. *Verificar ambiente de compilação*: Certifique-se de que todos os pré-requisitos para o próprio EIB (por exemplo, docker/podman, espaço em disco suficiente) sejam atendidos na máquina que executa o EIB.
. *Inspecionar logs do contêiner de compilação*: Analise os logs do contêiner com falha para obter erros mais detalhados (veja acima).
. *Verificar configuração de `eib`*: Verifique novamente o arquivo de configuração `eib` em busca de erros de digitação ou caminhos incorretos para arquivos de origem ou scripts de compilação.
* *Testar componentes individualmente*: Se a compilação do EIB envolver scripts ou estágios personalizados, execute-os de forma independente para isolar falhas.

[NOTE]
====
Verifique https://github.com/suse-edge/edge-image-builder/blob/main/docs/debugging.md[Depuração do Edge Image Builder].
====
