[#troubleshooting-phone-home-scenarios]
== Resolução de problemas em cenários de Phone-Home
:revdate: 2025-06-17
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Cenários de Phone-Home envolvem o uso do Elemental para conectar de volta ao cluster de Gerenciamento e o uso do EIB para criar uma imagem de SO, incluindo os bits de elemental-registration. Problemas podem ocorrer quando o host está sendo inicializado pela primeira vez, durante o processo de criação do EIB ou ao tentar registrar no cluster de Gerenciamento.

.Problemas comuns

* *O sistema falha ao se registrar*: O nó não está sendo registrado na interface do usuário. Certifique-se de que o host esteja inicializado corretamente e seja capaz de se comunicar de volta com o Rancher, que o relógio esteja sincronizado e que os serviços do Elemental estejam ok.
* *O sistema falha ao ser provisionado*: O nó está registrado, mas falha ao ser provisionado. Certifique-se de que o host seja capaz de se comunicar de volta com o Rancher, que o relógio esteja sincronizado e que os serviços do Elemental estejam ok.


.Registros

* *Logs do sistema*: `journalctl`
* *Logs do Elemental-system-agent*: `journalctl -u elemental-system-agent`
* *Logs do K3s/RKE2*: `journalctl -u k3s or journalctl -u rke2-server` (ou `rke2-agent`)
* *Pod do operador Elemental*: `kubectl logs -n cattle-elemental-system -l app=elemental-operator` 

.Etapas de solução de problemas

. *Revisar logs*: Verifique os logs do pod do Operador Elemental para ver se há algum problema. Verifique os logs do host se o nó estiver inicializado.

. *Verificar MachineRegistration e TPM*: Por padrão, o TPM é usado para https://elemental.docs.rancher.com/authentication/[autenticação], mas existem alternativas para hosts sem TPM.

