= *Edge Image Builder*


.Common 
- If you are in a non-Linux OS, then you are running podman via a podman machine. This machine is low on resources on it's default settings and can cause Edge Image Builder to hung for resource intense operations, such as downloading RPMs.
  You will need to adjust the resources of the podman machine, either by using Podman Desktop (settings cogwheel -> podman machine edit icon) or directly  via the `podman-machine-set` https://docs.podman.io/en/stable/markdown/podman-machine-set.1.html[command]
- To avoid any complications, the image architecture being built must match the one on the system running the Edge Image Builder container, for example if you are using an Apple Silicon MacBook, then you should be building only `aarch64` images:

----
image:
  arch: aarch64
  imageType: iso
  baseImage: slemicro.iso
  outputImageName: single-node-k3s.iso
----

.Kubernetes
- You can't create an image for a multi node kubernetes cluster without setting up a networking section in your definition file, more information https://github.com/suse-edge/edge-image-builder/blob/main/docs/building-images.md#kubernetes[here]
- You can't create an image for a multi node kubernetes cluster without setting up an `kubernetes.network.apiVIP` parameter (even better add an `kubernetes.network.apiHost` parameter to the setup as well) in the network section of your definition file, more information https://github.com/suse-edge/edge-image-builder/blob/main/docs/building-images.md#kubernetes[here]

----
kubernetes:
  version: v1.31.1+k3s1
  network:
    apiVIP: 192.168.64.11
    apiHost: 192.168.64.11
----

- When creating an image for a multi node kubernetes cluster you need to have a way to declare which machine gets which hostname and if it's a server or agent. While the server/agent configuration is managed in the definition file, for the general networking and setting up proper hostnames for the machines you should add the network configuration files in a networking directory. The easiest approach is to use the https://github.com/suse-edge/nm-configurator[nm-configurator] approach 

----
Example:
Definition file excerpt:

---
kubernetes:
  version: v1.30.4+k3s1
  network:
    apiVIP: 192.168.64.11
  nodes:
    - hostname: node1.suse.com
      type: server
      initializer: true
    - hostname: node2.suse.com
      type: agent
---

- Network files location:
├── definition.yaml
└── network
    ├── node1.suse.com.yaml
    └── node2.suse.com.yaml

node1.suse.com.yaml contents:
---
routes:
  config:
  - destination: 0.0.0.0/0
    metric: 100
    next-hop-address: 192.168.64.1
    next-hop-interface: eth0
    table-id: 254
dns-resolver:
  config:
    server:
    - 192.168.64.1
    - 8.8.8.8
interfaces:
- name: eth0
  type: ethernet
  state: up
  mac-address: 34:8A:B1:4B:16:E1
  ipv4:
    address:
    - ip: 192.168.64.21
      prefix-length: 24
    dhcp: false
    enabled: true
  ipv6:
    enabled: false
---

node2.suse.com.yaml contents:
---
routes:
  config:
  - destination: 0.0.0.0/0
    metric: 100
    next-hop-address: 192.168.64.1
    next-hop-interface: eth0
    table-id: 254
dns-resolver:
  config:
    server:
    - 192.168.64.1
    - 8.8.8.8
interfaces:
- name: eth0
  type: ethernet
  state: up
  mac-address: 34:8A:B1:4B:16:E2
  ipv4:
    address:
    - ip: 192.168.64.22
      prefix-length: 24
    dhcp: false
    enabled: true
  ipv6:
    enabled: false
---

----
