[#release-notes-abstract]
= 摘要
:revdate: 2026-07-17
:revnumber: 3.4
:page-revdate: {revdate}
ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

SUSE Edge 3.4 是一款紧密集成且经过全面验证的端到端解决方案，旨在解决边缘基础设施和云原生应用部署所面临的独特挑战。其主要目标是提供一个具有明确主张、同时高度灵活、可伸缩且安全的平台，涵盖初始部署镜像构建、节点配置和上线、应用部署、可观测性及生命周期管理。

该解决方案的设计理念是，由于客户的需求和期望各不相同，因此不存在“一刀切”的边缘平台。边缘部署促使我们不断解决并优化一些极具挑战性的问题，包括大规模可伸缩性、受限的网络可用性、物理空间限制、新的安全威胁和攻击向量、硬件架构及系统资源的差异、部署和对接旧有基础设施与应用的需求，以及生命周期更长的客户解决方案。

SUSE Edge 从底层构建于最优秀的开源软件之上，这与我们 30 年来提供安全、稳定且经过认证的 SUSE Linux 平台的历史，以及我们通过 Rancher 产品组合提供高度可扩展且功能丰富的 Kubernetes 管理经验相一致。SUSE Edge 在这些功能的基础上进一步扩展，以提供能够满足众多市场细分领域需求的功能，包括零售、医疗、交通、物流、电信、智能制造和工业物联网。

有关 SUSE Edge 产品支持生命周期更新的更多信息，请参阅 link:https://www.suse.com/lifecycle/#suse-edge-33[产品支持生命周期]。

NOTE: SUSE Telco Cloud（前身为 SUSE Edge for Telco）是 SUSE Edge 的衍生产品，具有额外的优化和组件，使该平台能够满足电信用例中的需求。除非另有明确说明，否则所有发行说明均适用于 SUSE Edge 3.4 和 SUSE Telco Cloud 3.4。

= 关于

除非另有明确说明和解释，否则这些发行说明在所有架构上都是相同的，并且最新版本以及所有其他 SUSE 产品的发行说明始终可在 https://www.suse.com/releasenotes[https://www.suse.com/releasenotes] 在线获取。

条目仅列出一次，但如果它们很重要且属于多个部分，则可以在多个地方引用它们。发行说明通常仅列出两个后续版本之间发生的更改。以前产品版本的发行说明中的某些重要条目可能会重复。为了更容易识别这些条目，它们包含相关的说明。

但是，重复的条目仅作为一种便利提供。因此，如果您跳过一个或多个版本，请同时查看所跳过版本的发行说明。如果您只阅读当前版本的发行说明，可能会错过影响系统行为的重要变更。SUSE Edge 版本定义为 x.y.z，其中“x”表示主版本，“y”表示次版本，“z”表示补丁版本，也称为“z-stream”。SUSE Edge 产品生命周期是基于给定的次版本发布来定义的，例如。“3.4”，但在其生命周期内会随附后续补丁更新，例如。"3.4.1".

NOTE: SUSE Edge z-stream 版本作为版本化堆栈进行了紧密集成和全面测试。将任何单个组件升级到不同于上述版本的版本可能会导致系统停机时间。虽然可以在未经测试的配置中运行 Edge 集群，但不建议这样做，并且通过支持渠道提供解决方案可能需要更长时间。

[#release-notes-3-4-4]
= Release 3.4.4

可用性日期：2026 年 7 月 22 日

全面支持结束日期：2026 年 3 月 20 日

维护支持结束日期：2027 年 9 月 20 日

EOL：2027 年 9 月 21 日

摘要：SUSE Edge 3.4.4 是 SUSE Edge 3.4 发布流中的第四个 z-stream 版本

* Rancher Prime 2.11.15 包含多项漏洞修复和安全更新 https://github.com/rancher/rancher/releases/tag/v2.11.15[上游 Rancher 发行说明]
* Metal^3^/Ironic 更新修复了若干 Bug 和安全问题，包括以下内容：
** 修复 CVE-2026-44916
** 修复 CVE-2026-44917
** 修复 CVE-2026-44919
** 修复 CVE-2026-46447
** 修复 CVE-2026-48681
** 修复 CVE-2026-54421


== 新功能

* 更新至 Kubernetes 1.33.11 https://github.com/k3s-io/k3s/releases/tag/v1.33.11%2Bk3s1[K3s 发行说明] / https://github.com/rancher/rke2/releases/tag/v1.33.11%2Brke2r1[RKE2 发行说明]
* 更新至 Rancher Prime 2.12.10 https://github.com/rancher/rancher/releases/tag/v2.12.10[发行说明]
* 更新至 SUSE Security (NeuVector) 5.5.2 https://open-docs.neuvector.com/5.5/releasenotes/5x[发行说明]
* 将 Metal^3^ chart 更新至 304.0.22+up0.12.9，包含多项改进

== Bug 修复与安全更新

* Rancher Prime 2.12.10 包含多项漏洞修复和安全更新 https://github.com/rancher/rancher/releases/tag/v2.12.10[上游 Rancher 发行说明]
* Edge Image Builder 已更新至 1.3.1.1
* Metal^3^/Ironic 更新修复了若干 Bug 和安全问题，包括以下内容：
** 修复 CVE-2026-44916
** 修复 CVE-2026-44917
** 修复 CVE-2026-44919
** 修复 CVE-2026-46447
** 修复 CVE-2026-48681
** 修复 CVE-2026-54421

== 已知问题

* Rancher 2.12.* 版本中存在一个已知 Bug，可能会破坏系统升级控制器 (SUC) 的升级工作流程。Rancher Prime 2.12.x 捆绑了一个过时的 `plans.upgrade.cattle.io` CRD，并在每次 Rancher 重启时重新应用它，从而覆盖了 SUC v0.16.3 所拥有的模式。这会将 `spec.drain.timeout` 字段从 `IntOrString` 还原为仅限整数，因此任何使用字符串超时值（例如 `timeout: "5m"`）的 SUC `Plan` 在 Rancher 重启后都会无法通过模式验证。由于 Rancher 重启会在日常操作和升级期间发生，这种情况会在正常运行中反复出现，并可能阻塞 SUC 管理的操作系统和 Kubernetes 升级工作流程。
+
作为临时解决方法，请重启系统升级控制器部署以重新确认正确的模式。每次 Rancher 重启后都必须重复此操作：
+
[,bash]
----
kubectl -n cattle-system rollout restart deployment/system-upgrade-controller
----
[WARNING]
====
如果正在部署新集群，请先按照 <<guides-kiwi-builder-images>> 构建全新的镜像，因为这是目前为 {x86-64} 和 {aarch64} 架构以及管理集群和下游集群创建集群所需的第一步。
====

* 当通过 Edge Image Builder 部署时，如果将 `HelmChartConfigs` 清单放入 `kubernetes/manifests` 配置目录，它们可能会失败。建议改为使用 EIB os-files 接口将任何 `HelmChartConfigs` 放置在 `/var/lib/rancher/{rke2/k3s}/server/manifests/` 中，例如请参阅 <<mgmt-cluster-directory-structure>>。 如果不这样做，可能会导致节点在初始启动时保持在 `NotReady` 状态，如 https://github.com/rancher/rke2/issues/8357[#8357 RKE2 问题] 中所述。

* 在 RKE2/K3s 1.31、1.32 和 1.33 版本中，用于存储 CNI 配置的目录 `/etc/cni` 可能不会因与 `overlayfs` 相关的某些条件而触发向 `containerd` 发送文件写入通知（请参阅 https://github.com/rancher/rke2/issues/8356[#8356 RKE2 问题]）。这反过来会导致 RKE2/K3s 的部署卡在等待 CNI 启动的状态，并使 RKE2/K3s 节点保持在 `NotReady` 状态。这可以在节点级别通过 `kubectl describe node <affected_node>` 查看：

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

作为一种变通方法，可以在 RKE2 启动之前将 tmpfs 卷挂载到 `/etc/cni` 目录。它避免了使用 overlayfs，因为后者会导致 containerd 丢失通知，并且配置应在每次节点重启和容器的 init 容器再次运行时被重写。如果使用 EIB，这可以是一个位于 `custom/scripts` 目录中的 `04-tmpfs-cni.sh` 脚本（如[此处](https://github.com/suse-edge/edge-image-builder/blob/release-1.2/docs/building-images.md#custom)所述），其内容如下：

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* 当使用 Elemental 接入远程主机时，`dbus.service` 与 `elemental-system-agent.service` 之间可能会出现竞态条件，导致远程主机上的 `rancher-system-agent.service` 启动失败，并出现类似下方的错误。（详情请参阅 https://github.com/suse-edge/edge-image-builder/issues/784[#784 Edge Image Builder 问题]。）

[,bash]
----
Sep 19 19:38:07 elementalvm elemental-system-agent[3671]: time="2025-09-19T19:38:07Z" level=info msg="[6b20fe64c854da2639804884b34129bb8f718eb59578111da58d9de1509c24db_1:stderr]: Failed to restart rancher-system-agent.service: Message recipient disconnected from message bus without replying"
----

作为一种变通方法，可以按如下方式创建 systemd 覆盖文件

[,bash]
----
[Unit]
Wants=dbus.service network-online.target
After=dbus.service network-online.target time-sync.target

[Service]
ExecStartPre=/bin/bash -c 'echo "Waiting for dbus to become active..." | systemd-cat -p info -t elemental-system-agent; sleep 15; timeout 300 bash -c "while ! systemctl is-active --quiet dbus.service; do sleep 15; done"'
----

并且可以使用名为 `30a-copy-elemental-system-agent-override.sh` 的自定义脚本，在 EIB 的 https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/templates/31-elemental-register.sh.tpl[31-elemental-register.sh] 脚本于 combustion 阶段运行之前，将该覆盖文件放置到 `/etc/systemd/system/elemental-system-agent.service.d`。

[,bash]
----
#!/bin/bash

/bin/mkdir -p /etc/systemd/system/elemental-system-agent.service.d
/bin/cp -f elemental-system-agent-override.conf /etc/systemd/system/elemental-system-agent.service.d/override.conf
----

== 组件版本

下表描述了构成 3.4.4 版本的各个组件，包括版本、Helm Chart 版本（如果适用），以及可以从何处以二进制格式拉取已发布的制品。请遵循相关文档以获取使用和部署示例。

|======
| 名称 | 版本 | Helm Chart 版本 | 制品位置 (URL/镜像)
| SUSE Linux Micro | 6.1 (最新) | 不适用 | https://www.suse.com/download/sle-micro/[SUSE Linux Micro 下载页面] +
SL-Micro.x86_64-6.1-Base-SelfInstall-GM.install.iso (sha256 70b9be28f2d92bc3b228412e4fc2b1d5026e691874b728e530b8063522158854) +
SL-Micro.x86_64-6.1-Base-RT-SelfInstall-GM.install.iso (sha256 9ce83e4545d4b36c7c6a44f7841dc3d9c6926fe32dbff694832e0fbd7c496e9d) +
SL-Micro.x86_64-6.1-Base-GM.raw.xz (sha256 36e3efa55822113840dd76fdf6914e933a7b7e88a1dce5cb20c424ccf2fb4430) +
SL-Micro.x86_64-6.1-Base-RT-GM.raw.xz (sha256 2ee66735da3e1da107b4878e73ae68f5fb7309f5ec02b5dfdb94e254fda8415e) +
| SUSE Multi-Linux Manager | 5.0.6 | 不适用 | https://www.suse.com/download/suse-manager/[SUSE® Multi-Linux Manager 下载页面]
s| K3s s| 1.33.11 | 不适用 | https://github.com/k3s-io/k3s/releases/tag/v1.33.11%2Bk3s1[上游 K3s 版本]
s| RKE2 s| 1.33.11 | 不适用 | https://github.com/rancher/rke2/releases/tag/v1.33.11%2Brke2r1[上游 RKE2 版本]
s| SUSE Rancher Prime s| 2.12.10 s| 2.12.10 | https://charts.rancher.com/server-charts/prime/index.yaml[Rancher Prime Helm 存储库] +
\https://prime.ribs.rancher.io/rancher/v2.12.10/rancher-images.txt[Rancher 2.12.10 Container Images]
| SUSE Storage (Longhorn) | 1.9.2 | 107.1.1+up1.9.2 | https://charts.rancher.io/index.yaml[Rancher Charts Helm 存储库] +
registry.suse.com/rancher/mirrored-longhornio-csi-attacher:v4.9.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-provisioner:v5.3.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-resizer:v1.14.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-snapshotter:v8.3.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-node-driver-registrar:v2.14.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-livenessprobe:v2.16.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-backing-image-manager:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-engine:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-instance-manager:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-manager:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-share-manager:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-ui:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-support-bundle-kit:v0.0.61 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-cli:v1.9.2 +
s| SUSE Security s| 5.5.2 s| 107.0.7+up2.10.2 | https://charts.rancher.io/index.yaml[Rancher Charts Helm 存储库] +
registry.suse.com/rancher/neuvector-controller:5.5.2 +
registry.suse.com/rancher/neuvector-enforcer:5.5.2 +
registry.suse.com/rancher/neuvector-manager:5.5.2 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.13 +
registry.suse.com/rancher/neuvector-registry-adapter:0.1.8 +
registry.suse.com/rancher/neuvector-scanner:6 +
registry.suse.com/rancher/neuvector-updater:0.0.4
| Rancher Turtles (CAPI) | 0.24.3 | 304.0.8+up0.24.3 | registry.suse.com/edge/charts/rancher-turtles:304.0.8_up0.24.3 +
registry.rancher.com/rancher/rancher/turtles:v0.24.3 +
registry.rancher.com/rancher/cluster-api-metal3-controller:v1.10.2 +
registry.rancher.com/rancher/cluster-api-metal3-ipam-controller:v1.10.2 +
registry.suse.com/rancher/cluster-api-controller:v1.10.5 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.20.1 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.20.1
| Rancher Turtles Airgap 资源 | 0.24.3 | 304.0.8+up0.24.3 | registry.suse.com/edge/charts/rancher-turtles-airgap-resources:304.0.8_up0.24.3
s| Metal^3^| 0.12.9 s| 304.0.22+up0.12.9 | registry.suse.com/edge/charts/metal3:304.0.22_up0.12.9 +
registry.suse.com/edge/3.4/baremetal-operator:0.10.4 +
registry.suse.com/edge/3.4/ironic:29.0.4.4 +
registry.suse.com/edge/3.4/ironic-ipa-downloader:3.0.10 +
| MetalLB | 0.14.9 | 304.0.0+up0.14.9 | registry.suse.com/edge/charts/metallb:304.0.0_up0.14.9 +
registry.suse.com/edge/3.4/metallb-controller:v0.14.9 +
registry.suse.com/edge/3.4/metallb-speaker:v0.14.9 +
registry.suse.com/edge/3.4/frr:8.5.6 +
registry.suse.com/edge/3.4/frr-k8s:v0.0.16 +
registry.suse.com/edge/3.4/kube-rbac-proxy:0.18.1
| Elemental | 1.7.3 | 1.7.3 | registry.suse.com/rancher/elemental-operator-chart:1.7.3 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.7.3 +
registry.suse.com/rancher/elemental-operator:1.7.3
| Elemental 仪表板扩展 | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/4.0.0/charts/elemental/3.0.1[Elemental 扩展 Helm Chart]
s| Edge Image Builder s| 1.3.1.1 | 不适用 s| registry.suse.com/edge/3.4/edge-image-builder:1.3.1.1
| NM 配置器 | 0.3.5 | 不适用 | https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.5[上游 NMConfigurator 版本]
| KubeVirt | 1.5.2 | 304.0.1+up0.6.0 | registry.suse.com/edge/charts/kubevirt:304.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportproxy:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportserver:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.5.2
| KubeVirt 仪表板扩展 | 1.3.2 | 304.0.3+up1.3.2 | registry.suse.com/edge/charts/kubevirt-dashboard-extension:304.0.3_up1.3.2
| 容器化数据导入器 | 1.62.0 | 304.0.1+up0.6.0 | registry.suse.com/edge/charts/cdi:304.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-importer:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-cloner:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.62.0
| 端点复制器操作员 | 0.3.0 | 304.0.1+up0.3.0 | registry.suse.com/edge/charts/endpoint-copier-operator:304.0.1_up0.3.0 +
registry.suse.com/edge/3.4/endpoint-copier-operator:0.3.0
| SR-IOV Network Operator | 1.5.0 | 304.0.2+up1.5.0 | registry.suse.com/edge/charts/sriov-network-operator:304.0.2_up1.5.0 +
registry.suse.com/edge/charts/sriov-crd:304.0.2_up1.5.0
| 系统升级控制器 | 0.16.3 | 107.0.0 | https://charts.rancher.io/index.yaml[Rancher Charts Helm 存储库] +
registry.suse.com/rancher/system-upgrade-controller:v0.16.3
s| 升级控制器 s| 0.1.3 s| 304.0.3+up0.1.3 | registry.suse.com/edge/charts/upgrade-controller:304.0.3_up0.1.3 +
registry.suse.com/edge/3.4/upgrade-controller:0.1.3 +
registry.suse.com/edge/3.4/kubectl:1.33.11 +
*registry.suse.com/edge/3.4/release-manifest:3.4.4*
| Kiwi 构建器 | 10.2.12.1 | 不适用 | registry.suse.com/edge/3.4/kiwi-builder:10.2.12.1
|======

[#release-notes-3-4-3]
= Release 3.4.3

可用性日期：2026 年 1 月 12 日

全面支持结束日期：2026 年 3 月 20 日

维护支持结束日期：2027 年 9 月 20 日

EOL：2027 年 9 月 21 日

摘要：SUSE Edge 3.4.3 是 SUSE Edge 3.4 发布流中的第三个 z-stream 版本

== 新功能

* 更新至 Kubernetes 1.33.6 和 Rancher Prime 2.12.5 https://github.com/rancher/rancher/releases/tag/v2.12.5[发行说明]
* 更新至 SUSE Multi-Linux Manager 5.0.6 https://documentation.suse.com/releasenotes/suma/5.0/#_version_5_0_6[发行说明)

== Bug 修复与安全更新

* Edge Rancher Turtles chart 已更新，以确保在卸载时正确去除资源（这是升级到 3.5 迁移过程的一部分，因此是必需的）
* RKE2 1.33.6 包含多项版本更新和修复 https://github.com/rancher/rke2/releases/tag/v1.33.6%2Brke2r1[发行说明]
* SUSE Multi-Linux Manager 5.0.6 包含多项与安全相关的修复 https://documentation.suse.com/releasenotes/suma/5.0/#_version_5_0_6[发行说明)

== 已知问题

[WARNING]
====
如果正在部署新集群，请先按照 <<guides-kiwi-builder-images>> 构建全新的镜像，因为这是目前为 {x86-64} 和 {aarch64} 架构以及管理集群和下游集群创建集群所需的第一步。
====

* 当通过 Edge Image Builder 部署时，如果将 `HelmChartConfigs` 清单放入 `kubernetes/manifests` 配置目录，它们可能会失败。建议改为使用 EIB os-files 接口将任何 `HelmChartConfigs` 放置在 `/var/lib/rancher/{rke2/k3s}/server/manifests/` 中，例如请参阅 <<mgmt-cluster-directory-structure>>。 如果不这样做，可能会导致节点在初始启动时保持在 `NotReady` 状态，如 https://github.com/rancher/rke2/issues/8357[#8357 RKE2 问题] 中所述。

* 在 RKE2/K3s 1.31、1.32 和 1.33 版本中，用于存储 CNI 配置的目录 `/etc/cni` 可能不会因与 `overlayfs` 相关的某些条件而触发向 `containerd` 发送文件写入通知（请参阅 https://github.com/rancher/rke2/issues/8356[#8356 RKE2 问题]）。这反过来会导致 RKE2/K3s 的部署卡在等待 CNI 启动的状态，并使 RKE2/K3s 节点保持在 `NotReady` 状态。这可以在节点级别通过 `kubectl describe node <affected_node>` 查看：

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

作为一种变通方法，可以在 RKE2 启动之前将 tmpfs 卷挂载到 `/etc/cni` 目录。它避免了使用 overlayfs，因为后者会导致 containerd 丢失通知，并且配置应在每次节点重启和容器的 init 容器再次运行时被重写。如果使用 EIB，这可以是一个位于 `custom/scripts` 目录中的 `04-tmpfs-cni.sh` 脚本（如[此处](https://github.com/suse-edge/edge-image-builder/blob/release-1.2/docs/building-images.md#custom)所述），其内容如下：

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* 当使用 Elemental 接入远程主机时，`dbus.service` 和 `elemental-system-agent.service` 之间可能会出现竞态条件，导致远程主机上的 `rancher-system-agent.service` 在启动时失败，并出现类似于下方的错误。（详情请参阅 https://github.com/suse-edge/edge-image-builder/issues/784[#784 Edge Image Builder 问题]。）

[,bash]
----
Sep 19 19:38:07 elementalvm elemental-system-agent[3671]: time="2025-09-19T19:38:07Z" level=info msg="[6b20fe64c854da2639804884b34129bb8f718eb59578111da58d9de1509c24db_1:stderr]: Failed to restart rancher-system-agent.service: Message recipient disconnected from message bus without replying"
----

作为一种变通方法，可以按如下方式创建 systemd 覆盖文件

[,bash]
----
[Unit]
Wants=dbus.service network-online.target
After=dbus.service network-online.target time-sync.target

[Service]
ExecStartPre=/bin/bash -c 'echo "Waiting for dbus to become active..." | systemd-cat -p info -t elemental-system-agent; sleep 15; timeout 300 bash -c "while ! systemctl is-active --quiet dbus.service; do sleep 15; done"'
----

并且可以使用名为 `30a-copy-elemental-system-agent-override.sh` 的自定义脚本，在 EIB 的 https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/templates/31-elemental-register.sh.tpl[31-elemental-register.sh] 脚本于 combustion 阶段运行之前，将该覆盖文件放置到 `/etc/systemd/system/elemental-system-agent.service.d`。

[,bash]
----
#!/bin/bash

/bin/mkdir -p /etc/systemd/system/elemental-system-agent.service.d
/bin/cp -f elemental-system-agent-override.conf /etc/systemd/system/elemental-system-agent.service.d/override.conf
----

== 组件版本

下表描述了构成 3.4.3 版本的各个组件，包括版本、Helm chart 版本（如果适用），以及可以从何处以二进制格式拉取已发布的制品。请遵循相关文档以获取使用和部署示例。

|======
| 名称 | 版本 | Helm Chart 版本 | 制品位置 (URL/镜像)
| SUSE Linux Micro | 6.1 (最新) | 不适用 | https://www.suse.com/download/sle-micro/[SUSE Linux Micro 下载页面] +
SL-Micro.x86_64-6.1-Base-SelfInstall-GM.install.iso 映像 (sha256 70b9be28f2d92bc3b228412e4fc2b1d5026e691874b728e530b8063522158854) +
SL-Micro.x86_64-6.1-Base-RT-SelfInstall-GM.install.iso 映像 (sha256 9ce83e4545d4b36c7c6a44f7841dc3d9c6926fe32dbff694832e0fbd7c496e9d) +
SL-Micro.x86_64-6.1-Base-GM.raw.xz (sha256 36e3efa55822113840dd76fdf6914e933a7b7e88a1dce5cb20c424ccf2fb4430) +
SL-Micro.x86_64-6.1-Base-RT-GM.raw.xz (sha256 2ee66735da3e1da107b4878e73ae68f5fb7309f5ec02b5dfdb94e254fda8415e) +
s| SUSE Multi-Linux Manager s| 5.0.6 | 不适用 | https://www.suse.com/download/suse-manager/[SUSE® Multi-Linux Manager 下载页面]
s| K3s s| 1.33.6 | 不适用 | https://github.com/k3s-io/k3s/releases/tag/v1.33.6%2Bk3s1[上游 K3s 版本]
s| RKE2 s| 1.33.6 | 不适用 | https://github.com/rancher/rke2/releases/tag/v1.33.6%2Brke2r1[上游 RKE2 版本]
s| SUSE Rancher Prime s| 2.12.5 s| 2.12.5 | https://charts.rancher.com/server-charts/prime/index.yaml[Rancher Prime Helm 存储库] +
\https://prime.ribs.rancher.io/rancher/v2.12.4/rancher-images.txt[Rancher 2.12.4 Container Images]
| SUSE Storage (Longhorn) | 1.9.2 | 107.1.1+up1.9.2 | https://charts.rancher.io/index.yaml[Rancher Charts Helm 存储库] +
registry.suse.com/rancher/mirrored-longhornio-csi-attacher:v4.9.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-provisioner:v5.3.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-resizer:v1.14.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-snapshotter:v8.3.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-node-driver-registrar:v2.14.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-livenessprobe:v2.16.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-backing-image-manager:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-engine:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-instance-manager:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-manager:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-share-manager:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-ui:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-support-bundle-kit:v0.0.61 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-cli:v1.9.2 +
| SUSE Security | 5.4.8 | 107.0.3+up2.8.10 | https://charts.rancher.io/index.yaml[Rancher Charts Helm 存储库] +
registry.suse.com/rancher/neuvector-controller:5.4.8 +
registry.suse.com/rancher/neuvector-enforcer:5.4.8 +
registry.suse.com/rancher/neuvector-manager:5.4.8 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.9 +
registry.suse.com/rancher/neuvector-registry-adapter:0.1.8 +
registry.suse.com/rancher/neuvector-scanner:6 +
registry.suse.com/rancher/neuvector-updater:0.0.4
s| Rancher Turtles (CAPI) s| 0.24.3 s| 304.0.8+up0.24.3 | registry.suse.com/edge/charts/rancher-turtles:304.0.8_up0.24.3 +
registry.rancher.com/rancher/rancher/turtles:v0.24.3 +
registry.rancher.com/rancher/cluster-api-metal3-controller:v1.10.2 +
registry.rancher.com/rancher/cluster-api-metal3-ipam-controller:v1.10.2 +
registry.suse.com/rancher/cluster-api-controller:v1.10.5 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.20.1 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.20.1
s| Rancher Turtles Airgap 资源 s| 0.24.3 | 304.0.8+up0.24.3 | registry.suse.com/edge/charts/rancher-turtles-airgap-resources:304.0.8_up0.24.3
| Metal^3^| 0.12.9 | 304.0.19+up0.12.9 | registry.suse.com/edge/charts/metal3:304.0.19_up0.12.9 +
registry.suse.com/edge/3.4/baremetal-operator:0.10.4 +
registry.suse.com/edge/3.4/ironic:29.0.4.4 +
registry.suse.com/edge/3.4/ironic-ipa-downloader:3.0.10 +
| MetalLB | 0.14.9 | 304.0.0+up0.14.9 | registry.suse.com/edge/charts/metallb:304.0.0_up0.14.9 +
registry.suse.com/edge/3.4/metallb-controller:v0.14.9 +
registry.suse.com/edge/3.4/metallb-speaker:v0.14.9 +
registry.suse.com/edge/3.4/frr:8.5.6 +
registry.suse.com/edge/3.4/frr-k8s:v0.0.16 +
registry.suse.com/edge/3.4/kube-rbac-proxy:0.18.1
| Elemental | 1.7.3 | 1.7.3 | registry.suse.com/rancher/elemental-operator-chart:1.7.3 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.7.3 +
registry.suse.com/rancher/elemental-operator:1.7.3
| Elemental 仪表板扩展 | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/4.0.0/charts/elemental/3.0.1[Elemental 扩展 Helm Chart]
| Edge Image Builder | 1.3.1 | 不适用 s| registry.suse.com/edge/3.4/edge-image-builder:1.3.1
| NM 配置器 | 0.3.5 | 不适用 s| https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.5[上游 NMConfigurator 版本]
| KubeVirt | 1.5.2 | 304.0.1+up0.6.0 | registry.suse.com/edge/charts/kubevirt:304.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportproxy:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportserver:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.5.2
| KubeVirt 仪表板扩展 | 1.3.2 | 304.0.3+up1.3.2 | registry.suse.com/edge/charts/kubevirt-dashboard-extension:304.0.3_up1.3.2
| 容器化数据导入器 | 1.62.0 | 304.0.1+up0.6.0 | registry.suse.com/edge/charts/cdi:304.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-importer:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-cloner:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.62.0
| 端点复制器操作员 | 0.3.0 | 304.0.1+up0.3.0 | registry.suse.com/edge/charts/endpoint-copier-operator:304.0.1_up0.3.0 +
registry.suse.com/edge/3.4/endpoint-copier-operator:0.3.0
| SR-IOV Network Operator | 1.5.0 | 304.0.2+up1.5.0 | registry.suse.com/edge/charts/sriov-network-operator:304.0.2_up1.5.0 +
registry.suse.com/edge/charts/sriov-crd:304.0.2_up1.5.0
| 系统升级控制器 | 0.16.0 | 107.0.0 | https://charts.rancher.io/index.yaml[Rancher Charts Helm 存储库] +
registry.suse.com/rancher/system-upgrade-controller:v0.16.0
| 升级控制器 | 0.1.1 | 304.0.1+up0.1.1 | registry.suse.com/edge/charts/upgrade-controller:304.0.1_up0.1.1 +
registry.suse.com/edge/3.4/upgrade-controller:0.1.1 +
registry.suse.com/edge/3.4/kubectl:1.33.4 +
*registry.suse.com/edge/3.4/release-manifest:3.4.3*
| Kiwi 构建器 s| 10.2.12.1 | 不适用 s| registry.suse.com/edge/3.4/kiwi-builder:10.2.12.1
|======

[#release-notes-3-4-2]
= 3.4.2 版本

可用性日期：2025 年 12 月 17 日

全面支持结束日期：2026 年 3 月 20 日

维护支持结束日期：2027 年 9 月 20 日

EOL：2027 年 9 月 21 日

摘要：SUSE Edge 3.4.2 是 SUSE Edge 3.4 发布流中的第二个 z-stream 版本

== 新功能

* 更新至 Rancher Prime 2.12.4 https://github.com/rancher/rancher/releases/tag/v2.12.4[发行说明]
* 更新至 SUSE Security (Neuvector) 5.4.8 https://open-docs.neuvector.com/releasenotes/5x#548-december-2025[发行说明]
* 更新至 SUSE Storage (Longhorn) 1.9.2 https://longhorn.io/docs/1.9.2/important-notes/[发行说明]
* Edge Image Builder 已更新至 1.3.1，请参阅 https://github.com/suse-edge/edge-image-builder/blob/release-1.3/RELEASE_NOTES.md[上游发行说明]
* 更新了 Rancher Turtles、Kiwi Builder、NM Configurator、Metal3/IPA/Ironic 版本

== Bug 修复与安全更新

* SUSE Security (Neuvector) 5.4.8 包含多项 Bug 修复 https://open-docs.neuvector.com/releasenotes/5x/#548-december-2025[上游 Neuvector Bug 修复]
* SUSE Storage (Longhorn) 1.9.2 包含多项 Bug 修复 https://github.com/longhorn/longhorn/releases/tag/v1.9.2[上游 Longhorn Bug 修复]
* EIB (edge-image-builder) 1.3.1 包含针对 Elemental 集群删除的修复 https://github.com/suse-edge/edge-image-builder/issues/808[EIB Bug 修复]
* Metal3 0.12.9 包含针对某些 Intel NIC 的 LACP 问题的多项 Bug 修复，并添加了一些用于调整 TLS 密码套件以克服 BMC 问题的环境变量。
* NMC (nm-configurator) 0.3.5 包含多项 Bug 修复 https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.5[NMC Bug 修复]
* Kiwi Builder 10.2.12.1 添加了 iptables，因为部署 RKE2 时需要此组件

== 已知问题

[WARNING]
====
如果正在部署新集群，请先按照 <<guides-kiwi-builder-images>> 构建全新的镜像，因为这是目前为 {x86-64} 和 {aarch64} 架构以及管理集群和下游集群创建集群所需的第一步。
====

* 当通过 Edge Image Builder 部署时，如果将 `HelmChartConfigs` 清单放入 `kubernetes/manifests` 配置目录，它们可能会失败。建议使用 EIB os-files 接口将任何 `HelmChartConfigs` 放置在 `/var/lib/rancher/{rke2/k3s}/server/manifests/` 中，例如，参见 <<mgmt-cluster-directory-structure>>。 如果不这样做，可能会导致节点在初始启动时保持在 `NotReady` 状态，详见 https://github.com/rancher/rke2/issues/8357[#8357 RKE2 issue]。

* 在 RKE2/K3s 1.31、1.32 和 1.33 版本中，用于存储 CNI 配置的目录 `/etc/cni` 可能由于与 `overlayfs` 相关的某些条件，不会向 `containerd` 发送文件写入的通知（详见 https://github.com/rancher/rke2/issues/8356[#8356 RKE2 issue]）。这反过来会导致 RKE2/K3s 的部署卡在等待 CNI 启动的状态，并使 RKE2/K3s 节点保持在 `NotReady` 状态。这可以在节点级别通过 `kubectl describe node <affected_node>` 查看：

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

作为一种变通方法，可以在 RKE2 启动之前将 tmpfs 卷挂载到 `/etc/cni` 目录。它避免了使用 overlayfs，因为后者会导致 containerd 丢失通知，并且配置应在每次节点重启和容器的 init 容器再次运行时被重写。如果使用 EIB，这可以是一个位于 `custom/scripts` 目录中的 `04-tmpfs-cni.sh` 脚本（具体说明见[此处](https://github.com/suse-edge/edge-image-builder/blob/release-1.2/docs/building-images.md#custom)），其内容如下：

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* 当使用 Elemental 将远程主机接入时，`dbus.service` 和 `elemental-system-agent.service` 之间可能会出现竞态条件，导致远程主机上的 `rancher-system-agent.service` 启动失败，并出现类似下方的错误。（详情请参阅 https://github.com/suse-edge/edge-image-builder/issues/784[#784 Edge Image Builder issue]。）

[,bash]
----
Sep 19 19:38:07 elementalvm elemental-system-agent[3671]: time="2025-09-19T19:38:07Z" level=info msg="[6b20fe64c854da2639804884b34129bb8f718eb59578111da58d9de1509c24db_1:stderr]: Failed to restart rancher-system-agent.service: Message recipient disconnected from message bus without replying"
----

作为一种变通方法，可以按如下方式创建 systemd 覆盖文件。

[,bash]
----
[Unit]
Wants=dbus.service network-online.target
After=dbus.service network-online.target time-sync.target

[Service]
ExecStartPre=/bin/bash -c 'echo "Waiting for dbus to become active..." | systemd-cat -p info -t elemental-system-agent; sleep 15; timeout 300 bash -c "while ! systemctl is-active --quiet dbus.service; do sleep 15; done"'
----

并且可以使用名为 `30a-copy-elemental-system-agent-override.sh` 的自定义脚本，在 combustion 阶段 EIB 的 https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/templates/31-elemental-register.sh.tpl[31-elemental-register.sh] 脚本运行之前，将该覆盖文件放置到 `/etc/systemd/system/elemental-system-agent.service.d`。

[,bash]
----
#!/bin/bash

/bin/mkdir -p /etc/systemd/system/elemental-system-agent.service.d
/bin/cp -f elemental-system-agent-override.conf /etc/systemd/system/elemental-system-agent.service.d/override.conf
----

== 组件版本

下表描述了构成 3.4.2 版本的各个组件，包括版本、Helm chart 版本（如果适用），以及可以从何处以二进制格式拉取已发布的制品。请遵循相关文档以获取使用和部署示例。

|======
| 名称 | 版本 | Helm Chart 版本 | 制品位置 (URL/镜像)
| SUSE Linux Micro | 6.1 (最新) | 不适用 | https://www.suse.com/download/sle-micro/[SUSE Linux Micro 下载页面] +
SL-Micro.x86_64-6.1-Base-SelfInstall-GM.install.iso (sha256 70b9be28f2d92bc3b228412e4fc2b1d5026e691874b728e530b8063522158854) +
SL-Micro.x86_64-6.1-Base-RT-SelfInstall-GM.install.iso (sha256 9ce83e4545d4b36c7c6a44f7841dc3d9c6926fe32dbff694832e0fbd7c496e9d) +
SL-Micro.x86_64-6.1-Base-GM.raw.xz (sha256 36e3efa55822113840dd76fdf6914e933a7b7e88a1dce5cb20c424ccf2fb4430) +
SL-Micro.x86_64-6.1-Base-RT-GM.raw.xz (sha256 2ee66735da3e1da107b4878e73ae68f5fb7309f5ec02b5dfdb94e254fda8415e) +
| SUSE Multi-Linux Manager | 5.0.5 | 不适用 | https://www.suse.com/download/suse-manager/[SUSE® Multi-Linux Manager 下载页面]
| K3s | 1.33.5 | 不适用 | https://github.com/k3s-io/k3s/releases/tag/v1.33.5%2Bk3s1[上游 K3s 版本]
| RKE2 | 1.33.5 | 不适用 | https://github.com/rancher/rke2/releases/tag/v1.33.5%2Brke2r1[上游 RKE2 版本]
s| SUSE Rancher Prime s| 2.12.4 s| 2.12.4 | https://charts.rancher.com/server-charts/prime/index.yaml[Rancher Prime Helm 存储库] +
\https://prime.ribs.rancher.io/rancher/v2.12.4/rancher-images.txt[Rancher 2.12.4 Container Images]
s| SUSE Storage (Longhorn) s| 1.9.2 s| 107.1.1+up1.9.2 | https://charts.rancher.io/index.yaml[Rancher Charts Helm 存储库] +
registry.suse.com/rancher/mirrored-longhornio-csi-attacher:v4.9.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-provisioner:v5.3.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-resizer:v1.14.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-snapshotter:v8.3.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-node-driver-registrar:v2.14.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-livenessprobe:v2.16.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-backing-image-manager:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-engine:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-instance-manager:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-manager:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-share-manager:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-ui:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-support-bundle-kit:v0.0.61 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-cli:v1.9.2 +
s| SUSE Security s| 5.4.8 s| 107.0.3+up2.8.10 | https://charts.rancher.io/index.yaml[Rancher Charts Helm 存储库] +
registry.suse.com/rancher/neuvector-controller:5.4.8 +
registry.suse.com/rancher/neuvector-enforcer:5.4.8 +
registry.suse.com/rancher/neuvector-manager:5.4.8 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.9 +
registry.suse.com/rancher/neuvector-registry-adapter:0.1.8 +
registry.suse.com/rancher/neuvector-scanner:6 +
registry.suse.com/rancher/neuvector-updater:0.0.4
s| Rancher Turtles (CAPI) s| 0.24.3 s| 304.0.7+up0.24.3 | registry.suse.com/edge/charts/rancher-turtles:304.0.7_up0.24.3 +
registry.rancher.com/rancher/rancher/turtles:v0.24.3 +
registry.rancher.com/rancher/cluster-api-metal3-controller:v1.10.2 +
registry.rancher.com/rancher/cluster-api-metal3-ipam-controller:v1.10.2 +
registry.suse.com/rancher/cluster-api-controller:v1.10.5 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.20.1 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.20.1
s| Rancher Turtles 离线资源 s| 0.24.3 | 304.0.7+up0.24.3 | registry.suse.com/edge/charts/rancher-turtles-airgap-resources:304.0.7_up0.24.3
s| Metal^3^s| 0.12.9 | 304.0.19+up0.12.9 | registry.suse.com/edge/charts/metal3:304.0.19_up0.12.9 +
registry.suse.com/edge/3.4/baremetal-operator:0.10.4 +
registry.suse.com/edge/3.4/ironic:29.0.4.4 +
registry.suse.com/edge/3.4/ironic-ipa-downloader:3.0.10 +
| MetalLB | 0.14.9 | 304.0.0+up0.14.9 | registry.suse.com/edge/charts/metallb:304.0.0_up0.14.9 +
registry.suse.com/edge/3.4/metallb-controller:v0.14.9 +
registry.suse.com/edge/3.4/metallb-speaker:v0.14.9 +
registry.suse.com/edge/3.4/frr:8.5.6 +
registry.suse.com/edge/3.4/frr-k8s:v0.0.16 +
registry.suse.com/edge/3.4/kube-rbac-proxy:0.18.1
| Elemental | 1.7.3 | 1.7.3 | registry.suse.com/rancher/elemental-operator-chart:1.7.3 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.7.3 +
registry.suse.com/rancher/elemental-operator:1.7.3
| Elemental 仪表板扩展 | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/4.0.0/charts/elemental/3.0.1[Elemental 扩展 Helm Chart]
s| Edge Image Builder s| 1.3.1 | 不适用 s| registry.suse.com/edge/3.4/edge-image-builder:1.3.1
s| NM 配置器 s| 0.3.5 | 不适用 s| https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.5[NMConfigurator 上游版本]
| KubeVirt | 1.5.2 | 304.0.1+up0.6.0 | registry.suse.com/edge/charts/kubevirt:304.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportproxy:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportserver:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.5.2
| KubeVirt 仪表板扩展 | 1.3.2 | 304.0.3+up1.3.2 | registry.suse.com/edge/charts/kubevirt-dashboard-extension:304.0.3_up1.3.2
| 容器化数据导入器 | 1.62.0 | 304.0.1+up0.6.0 | registry.suse.com/edge/charts/cdi:304.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-importer:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-cloner:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.62.0
| 端点复制器操作员 | 0.3.0 | 304.0.1+up0.3.0 | registry.suse.com/edge/charts/endpoint-copier-operator:304.0.1_up0.3.0 +
registry.suse.com/edge/3.4/endpoint-copier-operator:0.3.0
| SR-IOV Network Operator | 1.5.0 | 304.0.2+up1.5.0 | registry.suse.com/edge/charts/sriov-network-operator:304.0.2_up1.5.0 +
registry.suse.com/edge/charts/sriov-crd:304.0.2_up1.5.0
| 系统升级控制器 | 0.16.0 | 107.0.0 | https://charts.rancher.io/index.yaml[Rancher Charts Helm 存储库] +
registry.suse.com/rancher/system-upgrade-controller:v0.16.0
| 升级控制器 | 0.1.1 | 304.0.1+up0.1.1 | registry.suse.com/edge/charts/upgrade-controller:304.0.1_up0.1.1 +
registry.suse.com/edge/3.4/upgrade-controller:0.1.1 +
registry.suse.com/edge/3.4/kubectl:1.33.4 +
*registry.suse.com/edge/3.4/release-manifest:3.4.2*
s| Kiwi 构建器 s| 10.2.12.1 | 不适用 s| registry.suse.com/edge/3.4/kiwi-builder:10.2.12.1
|======

[#release-notes-3-4-1]
= 3.4.1 版本

可用性日期：2025 年 10 月 22 日

全面支持结束日期：2026 年 3 月 20 日

维护支持结束日期：2027 年 9 月 20 日

EOL：2027 年 9 月 21 日

摘要：SUSE Edge 3.4.1 是 SUSE Edge 3.4 发布流中的第一个 z-stream 版本

== 新功能

* 更新至 Kubernetes 1.33.5 和 Rancher Prime 2.12.2 https://github.com/rancher/rancher/releases/tag/v2.12.2[发行说明]
* 更新至 SUSE Security (NeuVector) 5.4.6 https://open-docs.neuvector.com/releasenotes/5x/#546-august-2025[发行说明]
* 更新至 SUSE Storage (Longhorn) 1.9.1 https://longhorn.io/docs/1.9.1/important-notes/[发行说明]

== Bug 修复与安全更新

* SUSE Security (NeuVector) 5.4.6 包含多项 Bug 修复 https://open-docs.neuvector.com/releasenotes/5x/#bugs-fixed[上游 NeuVector Bug 修复]
* https://github.com/rancher/rke2/releases/tag/v1.33.5%2Brke2r1[RKE2 1.33.5] 包含多项更新和修复，包括解决了某些部署中与 CPU 亲和性相关的问题 https://github.com/opencontainers/runc/pull/4858[上游 runc 问题]


== 已知问题

[WARNING]
====
如果正在部署新集群，请先按照 <<guides-kiwi-builder-images>> 构建全新的镜像，因为这是目前为 {x86-64} 和 {aarch64} 架构以及管理集群和下游集群创建集群所需的第一步。
====

* 当通过 Edge Image Builder 部署时，如果将 `HelmChartConfigs` 清单放入 `kubernetes/manifests` 配置目录，它们可能会失败。建议改为使用 EIB os-files 接口将任何 `HelmChartConfigs` 放置在 `/var/lib/rancher/{rke2/k3s}/server/manifests/` 中，示例请参见 <<mgmt-cluster-directory-structure>>。 如果不这样做，可能会导致节点在初始启动时保持在 `NotReady` 状态，如 https://github.com/rancher/rke2/issues/8357[#8357 RKE2 问题] 中所述

* 在 RKE2/K3s 1.31、1.32 和 1.33 版本中，用于存储 CNI 配置的目录 `/etc/cni` 可能不会因与 `overlayfs` 相关的某些条件而触发向 `containerd` 发送文件写入通知（请参阅 https://github.com/rancher/rke2/issues/8356[#8356 RKE2 问题]）。这反过来会导致 RKE2/K3s 的部署卡在等待 CNI 启动的状态，并使 RKE2/K3s 节点保持在 `NotReady` 状态。这可以在节点级别通过 `kubectl describe node <affected_node>` 查看：

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

作为一种变通方法，可以在 RKE2 启动之前将 tmpfs 卷挂载到 `/etc/cni` 目录。它避免了使用 overlayfs，因为后者会导致 containerd 丢失通知，并且配置应在每次节点重启和容器的 init 容器再次运行时被重写。如果使用 EIB，这可以是 `custom/scripts` 目录中的 `04-tmpfs-cni.sh` 脚本（如 [https://github.com/suse-edge/edge-image-builder/blob/release-1.2/docs/building-images.md#custom] 中所述），其内容如下：

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* 在使用 Elemental 接入远程主机时，`dbus.service` 和 `elemental-system-agent.service` 之间可能会出现竞态条件，导致远程主机上的 `rancher-system-agent.service` 启动失败，并出现类似于下方的错误。（有关详细信息，请参阅 https://github.com/suse-edge/edge-image-builder/issues/784[#784 Edge Image Builder 问题]。）

[,bash]
----
Sep 19 19:38:07 elementalvm elemental-system-agent[3671]: time="2025-09-19T19:38:07Z" level=info msg="[6b20fe64c854da2639804884b34129bb8f718eb59578111da58d9de1509c24db_1:stderr]: Failed to restart rancher-system-agent.service: Message recipient disconnected from message bus without replying"
----

作为一种变通方法，可以按如下方式创建 systemd 覆盖文件

[,bash]
----
[Unit]
Wants=dbus.service network-online.target
After=dbus.service network-online.target time-sync.target

[Service]
ExecStartPre=/bin/bash -c 'echo "Waiting for dbus to become active..." | systemd-cat -p info -t elemental-system-agent; sleep 15; timeout 300 bash -c "while ! systemctl is-active --quiet dbus.service; do sleep 15; done"'
----

并且可以使用名为 `30a-copy-elemental-system-agent-override.sh` 的自定义脚本，在 EIB 的 https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/templates/31-elemental-register.sh.tpl[31-elemental-register.sh] 脚本于 combustion 阶段运行之前，将该覆盖文件放置到 `/etc/systemd/system/elemental-system-agent.service.d` 中。

[,bash]
----
#!/bin/bash

/bin/mkdir -p /etc/systemd/system/elemental-system-agent.service.d
/bin/cp -f elemental-system-agent-override.conf /etc/systemd/system/elemental-system-agent.service.d/override.conf
----

== 组件版本

下表描述了构成 3.4.1 版本的各个组件，包括版本、Helm chart 版本（如果适用），以及可以从何处以二进制格式拉取已发布的制品。请遵循相关文档以获取使用和部署示例。

|======
| 名称 | 版本 | Helm Chart 版本 | 制品位置 (URL/镜像)
| SUSE Linux Micro | 6.1（最新） | 不适用 | https://www.suse.com/download/sle-micro/[SUSE Linux Micro 下载页面] +
SL-Micro.x86_64-6.1-Base-SelfInstall-GM.install.iso (sha256 70b9be28f2d92bc3b228412e4fc2b1d5026e691874b728e530b8063522158854) +
SL-Micro.x86_64-6.1-Base-RT-SelfInstall-GM.install.iso (sha256 9ce83e4545d4b36c7c6a44f7841dc3d9c6926fe32dbff694832e0fbd7c496e9d) +
SL-Micro.x86_64-6.1-Base-GM.raw.xz (sha256 36e3efa55822113840dd76fdf6914e933a7b7e88a1dce5cb20c424ccf2fb4430) +
SL-Micro.x86_64-6.1-Base-RT-GM.raw.xz (sha256 2ee66735da3e1da107b4878e73ae68f5fb7309f5ec02b5dfdb94e254fda8415e) +
| SUSE Multi-Linux Manager | 5.0.5 | 不适用 | https://www.suse.com/download/suse-manager/[SUSE® Multi-Linux Manager 下载页面]
s| K3s s| 1.33.5 | 不适用 | https://github.com/k3s-io/k3s/releases/tag/v1.33.5%2Bk3s1[上游 K3s 版本]
s| RKE2 s| 1.33.5 | 不适用 | https://github.com/rancher/rke2/releases/tag/v1.33.5%2Brke2r1[上游 RKE2 版本]
s| SUSE Rancher Prime s| 2.12.2 s| 2.12.2 | https://charts.rancher.com/server-charts/prime/index.yaml[Rancher Prime Helm 存储库] +
\https://github.com/rancher/rancher/releases/download/v2.12.2/rancher-images.txt[Rancher 2.12.2 容器镜像]
s| SUSE Storage (Longhorn) s| 1.9.1 s| 107.1.0+up1.9.1 | https://charts.rancher.io/index.yaml[Rancher Charts Helm 存储库] +
registry.suse.com/rancher/mirrored-longhornio-csi-attacher:v4.9.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-provisioner:v5.3.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-resizer:v1.14.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-snapshotter:v8.3.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-node-driver-registrar:v2.14.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-livenessprobe:v2.16.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-backing-image-manager:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-engine:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-instance-manager:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-manager:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-share-manager:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-ui:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-support-bundle-kit:v0.0.61 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-cli:v1.9.1 +
s| SUSE Security s| 5.4.6 s| 107.0.1+up2.8.8 | https://charts.rancher.io/index.yaml[Rancher Charts Helm 存储库] +
registry.suse.com/rancher/neuvector-controller:5.4.6 +
registry.suse.com/rancher/neuvector-enforcer:5.4.6 +
registry.suse.com/rancher/neuvector-manager:5.4.6 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.6 +
registry.suse.com/rancher/neuvector-registry-adapter:0.1.8 +
registry.suse.com/rancher/neuvector-scanner:6 +
registry.suse.com/rancher/neuvector-updater:0.0.4
| Rancher Turtles (CAPI) | 0.24.0 | 304.0.6+up0.24.0 | registry.suse.com/edge/charts/rancher-turtles:304.0.6_up0.24.0 +
registry.rancher.com/rancher/rancher/turtles:v0.24.0 +
registry.rancher.com/rancher/cluster-api-metal3-controller:v1.10.2 +
registry.rancher.com/rancher/cluster-api-metal3-ipam-controller:v1.10.2 +
registry.suse.com/rancher/cluster-api-controller:v1.10.5 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.20.1 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.20.1
| Rancher Turtles 离线资源 | 0.24.0 | 304.0.6+up0.24.0 | registry.suse.com/edge/charts/rancher-turtles-airgap-resources:304.0.6_up0.24.0
| Metal^3^| 0.11.5 | 304.0.16+up0.12.6 | registry.suse.com/edge/charts/metal3:304.0.16_up0.12.6 +
registry.suse.com/edge/3.4/baremetal-operator:0.10.2.1 +
registry.suse.com/edge/3.4/ironic:29.0.4.3 +
registry.suse.com/edge/3.4/ironic-ipa-downloader:3.0.9 +
registry.suse.com/edge/mariadb:10.6.15.1
| MetalLB | 0.14.9 | 304.0.0+up0.14.9 | registry.suse.com/edge/charts/metallb:304.0.0_up0.14.9 +
registry.suse.com/edge/3.4/metallb-controller:v0.14.9 +
registry.suse.com/edge/3.4/metallb-speaker:v0.14.9 +
registry.suse.com/edge/3.4/frr:8.5.6 +
registry.suse.com/edge/3.4/frr-k8s:v0.0.16 +
registry.suse.com/edge/3.4/kube-rbac-proxy:0.18.1
| Elemental | 1.7.3 | 1.7.3 | registry.suse.com/rancher/elemental-operator-chart:1.7.3 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.7.3 +
registry.suse.com/rancher/elemental-operator:1.7.3
| Elemental 仪表板扩展 | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/4.0.0/charts/elemental/3.0.1[Elemental 扩展 Helm Chart]
| Edge Image Builder | 1.3.0 | 不适用 | registry.suse.com/edge/3.4/edge-image-builder:1.3.0
| NM 配置程序 | 0.3.3 | 不适用 | https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.3[NMConfigurator 上游版本]
| KubeVirt | 1.5.2 | 304.0.1+up0.6.0 | registry.suse.com/edge/charts/kubevirt:304.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportproxy:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportserver:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.5.2
| KubeVirt 仪表板扩展 | 1.3.2 | 304.0.3+up1.3.2 | registry.suse.com/edge/charts/kubevirt-dashboard-extension:304.0.3_up1.3.2
| 容器化数据导入器 | 1.62.0 | 304.0.1+up0.6.0 | registry.suse.com/edge/charts/cdi:304.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-importer:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-cloner:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.62.0
| 端点复制器操作员 | 0.3.0 | 304.0.1+up0.3.0 | registry.suse.com/edge/charts/endpoint-copier-operator:304.0.1_up0.3.0 +
registry.suse.com/edge/3.4/endpoint-copier-operator:0.3.0
| SR-IOV Network Operator | 1.5.0 | 304.0.2+up1.5.0 | registry.suse.com/edge/charts/sriov-network-operator:304.0.2_up1.5.0 +
registry.suse.com/edge/charts/sriov-crd:304.0.2_up1.5.0
| 系统升级控制器 | 0.16.0 | 107.0.0 | https://charts.rancher.io/index.yaml[Rancher Charts Helm 存储库] +
registry.suse.com/rancher/system-upgrade-controller:v0.16.0
| 升级控制器 | 0.1.1 | 304.0.1+up0.1.1 | registry.suse.com/edge/charts/upgrade-controller:304.0.1_up0.1.1 +
registry.suse.com/edge/3.4/upgrade-controller:0.1.1 +
registry.suse.com/edge/3.4/kubectl:1.33.4 +
*registry.suse.com/edge/3.4/release-manifest:3.4.1*
| Kiwi 构建器 | 10.2.12.0 | 不适用 | registry.suse.com/edge/3.4/kiwi-builder:10.2.12.0
|======

[#release-notes-3-4-0]
= 3.4.0 版本

可用性日期：2025 年 9 月 24 日

全面支持结束日期：2026 年 3 月 20 日

维护支持结束日期：2027 年 9 月 20 日

EOL：2027 年 9 月 21 日

摘要：SUSE Edge 3.4.0 是 SUSE Edge 3.4 发布流中的第一个版本。

== 新功能

* 更新至 Kubernetes 1.33 和 Rancher Prime 2.12
* 更新了 Rancher Turtles、Cluster API 和 Metal3/Ironic 版本
* 更新至 SUSE Storage (Longhorn) 1.9.1 https://longhorn.io/docs/1.9.1/[发行说明]
* 现在可以通过定向网络配置流程更灵活地部署 {aarch64} 下游集群。有关详细信息，请参见 <<atip-automated-provisioning>>。
* 现在全面支持双栈集群的部署（单栈 IPv6 仍处于 <<tech-previews>> 状态）
* MetalLB 的 BGP 模式现已作为技术预览版提供，有关详细信息，请参阅 <<tech-previews>> 和 <<guides-metallb-k3s-l3>>。
* Edge Image Builder 已更新至 1.3.0，请参阅 https://github.com/suse-edge/edge-image-builder/blob/release-1.3/RELEASE_NOTES.md[上游发行说明]

== Bug 修复与安全更新

* Rancher Prime 2.12 包含多项 Bug 修复 https://github.com/rancher/rancher/releases/tag/v2.12.1[上游 Rancher 发行说明]
* Rancher Prime 2.12 修复了在确定扩展升级可用性时与 AppVersion 相关的问题，该问题影响了 Edge chart 的操作 https://github.com/rancher/dashboard/issues/14204[上游问题]
* SUSE Storage (Longhorn) 1.9.1 包含多项 Bug 修复 https://github.com/longhorn/longhorn/releases/tag/v1.9.1[上游 Longhorn Bug 修复]
* 更新后的 Metal^3^ chart 修复了在检查期间可能为绑定接口收集到错误 MAC 地址的问题 https://bugs.launchpad.net/ironic-python-agent/+bug/2103450[上游 IPA 问题]
* 更新后的 Metal^3^ chart 修复了在 ConfigMap 更新时部署可能无法正确重启的问题 https://github.com/suse-edge/charts/issues/219[上游问题]
* Rancher Turtles 更新包含一项修复，解决了 RKE2 CAPI 提供程序未应用 MachineTemplate ownerReferences 的问题 https://github.com/rancher/cluster-api-provider-rke2/issues/500[上游问题]

== 已知问题

[WARNING]
====
如果正在部署新集群，请先按照 <<guides-kiwi-builder-images>> 构建全新的镜像，因为这是目前为 {x86-64} 和 {aarch64} 架构以及管理集群和下游集群创建集群所需的第一步。
====

* 当通过 Edge Image Builder 部署时，如果将 `HelmChartConfigs` 清单放入 `kubernetes/manifests` 配置目录，它们可能会失败。建议改为使用 EIB os-files 接口将任何 `HelmChartConfigs` 放置在 `/var/lib/rancher/{rke2/k3s}/server/manifests/` 中，示例请参见 <<mgmt-cluster-directory-structure>>。 如果不这样做，可能会导致节点在初始启动时保持在 `NotReady` 状态，如 https://github.com/rancher/rke2/issues/8357[#8357 RKE2 问题] 中所述

* 在 RKE2/K3s 1.31、1.32 和 1.33 版本中，用于存储 CNI 配置的目录 `/etc/cni` 可能不会因与 `overlayfs` 相关的某些条件而触发向 `containerd` 发送文件写入通知（请参阅 https://github.com/rancher/rke2/issues/8356[#8356 RKE2 问题]）。这反过来会导致 RKE2/K3s 的部署卡在等待 CNI 启动的状态，并使 RKE2/K3s 节点保持在 `NotReady` 状态。这可以在节点级别通过 `kubectl describe node <affected_node>` 查看：

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

作为一种变通方法，可以在 RKE2 启动之前将 tmpfs 卷挂载到 `/etc/cni` 目录。它避免了使用 overlayfs，因为后者会导致 containerd 丢失通知，并且配置应在每次节点重启和容器的 init 容器再次运行时被重写。如果使用 EIB，这可以是一个位于 `custom/scripts` 目录中的 `04-tmpfs-cni.sh` 脚本（如 [https://github.com/suse-edge/edge-image-builder/blob/release-1.2/docs/building-images.md#custom] 中所述），其内容如下：

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* 在使用 Elemental 接入远程主机时，`dbus.service` 和 `elemental-system-agent.service` 之间可能会出现竞态条件，导致远程主机上的 `rancher-system-agent.service` 启动失败，并出现类似于下方的错误。（有关详细信息，请参阅 https://github.com/suse-edge/edge-image-builder/issues/784[#784 Edge Image Builder 问题]。）

[,bash]
----
Sep 19 19:38:07 elementalvm elemental-system-agent[3671]: time="2025-09-19T19:38:07Z" level=info msg="[6b20fe64c854da2639804884b34129bb8f718eb59578111da58d9de1509c24db_1:stderr]: Failed to restart rancher-system-agent.service: Message recipient disconnected from message bus without replying"
----

作为一种变通方法，可以按如下方式创建 systemd 覆盖文件

[,bash]
----
[Unit]
Wants=dbus.service network-online.target
After=dbus.service network-online.target time-sync.target

[Service]
ExecStartPre=/bin/bash -c 'echo "Waiting for dbus to become active..." | systemd-cat -p info -t elemental-system-agent; sleep 15; timeout 300 bash -c "while ! systemctl is-active --quiet dbus.service; do sleep 15; done"'
----

并且可以使用名为 `30a-copy-elemental-system-agent-override.sh` 的自定义脚本，在 EIB 的 https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/templates/31-elemental-register.sh.tpl[31-elemental-register.sh] 脚本于 combustion 阶段运行之前，将该覆盖文件放置到 `/etc/systemd/system/elemental-system-agent.service.d` 中。

[,bash]
----
#!/bin/bash

/bin/mkdir -p /etc/systemd/system/elemental-system-agent.service.d
/bin/cp -f elemental-system-agent-override.conf /etc/systemd/system/elemental-system-agent.service.d/override.conf
----

== 组件版本

下表描述了构成 3.4.0 版本的各个组件，包括版本、Helm Chart 版本（如果适用），以及可以从何处以二进制格式拉取已发布的制品。请遵循相关文档以获取使用和部署示例。

|======
| 名称 | 版本 | Helm Chart 版本 | 制品位置 (URL/镜像)
| SUSE Linux Micro | 6.1（最新） | 不适用 | https://www.suse.com/download/sle-micro/[SUSE Linux Micro 下载页面] +
SL-Micro.x86_64-6.1-Base-SelfInstall-GM.install.iso 映像 (sha256 70b9be28f2d92bc3b228412e4fc2b1d5026e691874b728e530b8063522158854) +
SL-Micro.x86_64-6.1-Base-RT-SelfInstall-GM.install.iso 映像 (sha256 9ce83e4545d4b36c7c6a44f7841dc3d9c6926fe32dbff694832e0fbd7c496e9d) +
SL-Micro.x86_64-6.1-Base-GM.raw.xz (sha256 36e3efa55822113840dd76fdf6914e933a7b7e88a1dce5cb20c424ccf2fb4430) +
SL-Micro.x86_64-6.1-Base-RT-GM.raw.xz (sha256 2ee66735da3e1da107b4878e73ae68f5fb7309f5ec02b5dfdb94e254fda8415e) +
| SUSE Multi-Linux Manager | 5.0.5 | 不适用 | https://www.suse.com/download/suse-manager/[SUSE® Multi-Linux Manager 下载页面]
| K3s | 1.33.3 | 不适用 | https://github.com/k3s-io/k3s/releases/tag/v1.33.3%2Bk3s1[上游 K3s 版本]
| RKE2 | 1.33.3 | 不适用 | https://github.com/rancher/rke2/releases/tag/v1.33.3%2Brke2r1[上游 RKE2 版本]
| SUSE Rancher Prime | 2.12.1 | 2.12.1 | https://charts.rancher.com/server-charts/prime/index.yaml[Rancher Prime Helm 存储库] +
\https://github.com/rancher/rancher/releases/download/v2.12.1/rancher-images.txt[Rancher 2.12.1 容器镜像]
| SUSE Storage (Longhorn) | 1.9.1 | 107.0.0+up1.9.1 | https://charts.rancher.io/index.yaml[Rancher Charts Helm 存储库] +
registry.suse.com/rancher/mirrored-longhornio-csi-attacher:v4.9.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-provisioner:v5.3.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-resizer:v1.14.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-snapshotter:v8.3.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-node-driver-registrar:v2.14.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-livenessprobe:v2.16.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-backing-image-manager:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-engine:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-instance-manager:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-manager:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-share-manager:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-ui:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-support-bundle-kit:v0.0.61 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-cli:v1.9.1 +
| SUSE Security | 5.4.5 | 107.0.0+up2.8.7 | https://charts.rancher.io/index.yaml[Rancher Charts Helm 存储库] +
registry.suse.com/rancher/neuvector-controller:5.4.5 +
registry.suse.com/rancher/neuvector-enforcer:5.4.5 +
registry.suse.com/rancher/neuvector-manager:5.4.5 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.6 +
registry.suse.com/rancher/neuvector-registry-adapter:0.1.8 +
registry.suse.com/rancher/neuvector-scanner:6 +
registry.suse.com/rancher/neuvector-updater:0.0.4
| Rancher Turtles (CAPI) | 0.24.0 | 304.0.6+up0.24.0 | registry.suse.com/edge/charts/rancher-turtles:304.0.6_up0.24.0 +
registry.rancher.com/rancher/rancher/turtles:v0.24.0 +
registry.rancher.com/rancher/cluster-api-metal3-controller:v1.10.2 +
registry.rancher.com/rancher/cluster-api-metal3-ipam-controller:v1.10.2 +
registry.suse.com/rancher/cluster-api-controller:v1.10.5 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.20.1 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.20.1
| Rancher Turtles 离线资源 | 0.24.0 | 304.0.6+up0.24.0 | registry.suse.com/edge/charts/rancher-turtles-airgap-resources:304.0.6_up0.24.0
| Metal^3^| 0.11.5 | 304.0.16+up0.12.6 | registry.suse.com/edge/charts/metal3:304.0.16_up0.12.6 +
registry.suse.com/edge/3.4/baremetal-operator:0.10.2.1 +
registry.suse.com/edge/3.4/ironic:29.0.4.3 +
registry.suse.com/edge/3.4/ironic-ipa-downloader:3.0.9 +
registry.suse.com/edge/mariadb:10.6.15.1
| MetalLB | 0.14.9 | 304.0.0+up0.14.9 | registry.suse.com/edge/charts/metallb:304.0.0_up0.14.9 +
registry.suse.com/edge/3.4/metallb-controller:v0.14.9 +
registry.suse.com/edge/3.4/metallb-speaker:v0.14.9 +
registry.suse.com/edge/3.4/frr:8.5.6 +
registry.suse.com/edge/3.4/frr-k8s:v0.0.16 +
registry.suse.com/edge/3.4/kube-rbac-proxy:0.18.1
| Elemental | 1.7.3 | 1.7.3 | registry.suse.com/rancher/elemental-operator-chart:1.7.3 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.7.3 +
registry.suse.com/rancher/elemental-operator:1.7.3
| Elemental 仪表板扩展 | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/4.0.0/charts/elemental/3.0.1[Elemental 扩展 Helm Chart]
| Edge Image Builder | 1.3.0 | 不适用 | registry.suse.com/edge/3.4/edge-image-builder:1.3.0
| NM 配置程序 | 0.3.3 | 不适用 | https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.3[NMConfigurator 上游版本]
| KubeVirt | 1.5.2 | 304.0.1+up0.6.0 | registry.suse.com/edge/charts/kubevirt:304.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportproxy:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportserver:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.5.2
| KubeVirt 仪表板扩展 | 1.3.2 | 304.0.3+up1.3.2 | registry.suse.com/edge/charts/kubevirt-dashboard-extension:304.0.3_up1.3.2
| 容器化数据导入器 | 1.62.0 | 304.0.1+up0.6.0 | registry.suse.com/edge/charts/cdi:304.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-importer:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-cloner:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.62.0
| 端点复制器操作员 | 0.3.0 | 304.0.1+up0.3.0 | registry.suse.com/edge/charts/endpoint-copier-operator:304.0.1_up0.3.0 +
registry.suse.com/edge/3.4/endpoint-copier-operator:0.3.0
| Akri（已弃用） | 0.12.20 | 304.0.0+up0.12.20 | registry.suse.com/edge/charts/akri:304.0.0_up0.12.20 +
registry.suse.com/edge/charts/akri-dashboard-extension:304.0.0_up1.3.1 +
registry.suse.com/edge/3.4/akri-agent:v0.12.20 +
registry.suse.com/edge/3.4/akri-controller:v0.12.20 +
registry.suse.com/edge/3.4/akri-debug-echo-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.4/akri-onvif-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.4/akri-opcua-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.4/akri-udev-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.4/akri-webhook-configuration:v0.12.20
| SR-IOV Network Operator | 1.5.0 | 304.0.2+up1.5.0 | registry.suse.com/edge/charts/sriov-network-operator:304.0.2_up1.5.0 +
registry.suse.com/edge/charts/sriov-crd:304.0.2_up1.5.0
| 系统升级控制器 | 0.16.0 | 107.0.0 | https://charts.rancher.io/index.yaml[Rancher Charts Helm 存储库] +
registry.suse.com/rancher/system-upgrade-controller:v0.16.0
| 升级控制器 | 0.1.1 | 304.0.1+up0.1.1 | registry.suse.com/edge/charts/upgrade-controller:304.0.1_up0.1.1 +
registry.suse.com/edge/3.4/upgrade-controller:0.1.1 +
registry.suse.com/edge/3.4/kubectl:1.33.4 +
registry.suse.com/edge/3.4/release-manifest:3.4.0
| Kiwi 构建器 | 10.2.12.0 | 不适用 | registry.suse.com/edge/3.4/kiwi-builder:10.2.12.0
|======

= 已弃用的功能

除非另有说明，否则这些内容适用于 3.4.0 版本及所有后续 z-stream 版本。

* Akri 在之前的 Edge 版本中是一项技术预览，现已被弃用。 计划在未来的版本中将其移除。

[#tech-previews]
= 技术预览

除非另有说明，否则这些内容适用于 3.4.0 版本及所有后续 z-stream 版本。

* 单栈 IPv6 部署是一项技术预览，不属于标准支持范围。
* 下游部署中的精确时间协议 (PTP) 是一项技术预览，不属于标准支持范围。
* MetalLB 的 BGP 模式是一项技术预览，不属于标准支持范围。

= 组件验证

上述组件可以使用软件物料清单 (SBOM) 数据进行验证 - 例如，使用如下所述的 `cosign`：

从 https://www.suse.com/support/security/keys/[SUSE 签名密钥源] 下载 SUSE Edge 容器公钥：

[,bash]
----
include::key.sh[]
----

验证容器镜像哈希，例如使用 `crane`：

[,bash]
----
> crane digest registry.suse.com/edge/3.4/baremetal-operator:0.10.2.1 --platform linux/amd64
sha256:310d939f8ae4b547710195b9671a4e9ff417420c0856103dd728b051788b5374
----

NOTE: 对于多架构镜像，在获取摘要时还需要指定平台，例如 `--platform linux/amd64` 或 `--platform linux/arm64`。如果不这样做，将在后续步骤 (`Error: no matching attestations`) 中导致错误。

使用 `cosign` 进行验证：

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/3.4/baremetal-operator@sha256:310d939f8ae4b547710195b9671a4e9ff417420c0856103dd728b051788b5374 > /dev/null
#
Verification for registry.suse.com/edge/3.4/baremetal-operator@sha256:310d939f8ae4b547710195b9671a4e9ff417420c0856103dd728b051788b5374 --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - The signatures were verified against the specified public key
----

按照 https://www.suse.com/support/security/sbom/[SUSE SBOM 文档] 中的说明提取 SBOM 数据：

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/3.4/baremetal-operator@sha256:310d939f8ae4b547710195b9671a4e9ff417420c0856103dd728b051788b5374 | jq '.payload | @base64d | fromjson | .predicate'
----

= 升级步骤

有关如何升级到新版本的详细信息，请参阅 <<day-2-operations>>。

= 产品支持生命周期

SUSE Edge 由 SUSE 提供屡获殊荣的支持，SUSE 是一家成熟的技术领导者，在提供企业级支持服务方面拥有良好的记录。有关更多信息，请参阅 https://www.suse.com/lifecycle[https://www.suse.com/lifecycle] 以及 https://www.suse.com/support/policy.html[https://www.suse.com/support/policy.html] 处的支持策略页面。如果您对提交支持案例、SUSE 如何划分严重性级别或支持范围有任何疑问，请参阅 https://www.suse.com/support/handbook/[https://www.suse.com/support/handbook/] 处的技术支持手册。

SUSE Edge "3.4"版本提供24个月的生产支持，其中最初6个月为"全面支持"，随后18个月为"维护支持"。 在这些支持阶段之后，产品达到“终止服务”（EOL），并不再获得支持。有关生命周期阶段的更多信息，请参见下表：

|======
| *全面支持（6个月）*| 在全面支持期间，将发布紧急和选定的高优先级 Bug 修复，所有其他补丁（非紧急、增强功能、新功能）将通过常规发布计划发布。
| *维护支持（18个月）*| 在此期间，仅通过补丁发布关键修复。其他 Bug 修复可能会由SUSE酌情发布，但不应抱有预期。
| *终止服务（EOL）* | 一旦产品版本达到其终止服务日期，客户可以在产品许可协议的条款范围内继续使用该产品。
SUSE的支持计划不适用于已过终止服务日期的产品版本。
|======

除非另有明确说明，否则所列出的所有组件均被视为一般可用（GA），并涵盖在SUSE的标准支持范围内。某些组件可能被列为“技术预览”，SUSE在此为客户提供早期预发布功能以供评估，但这些组件不受标准支持政策的约束，也不建议用于生产环境。SUSE非常欢迎对技术预览组件的改进提出反馈和建议，但如果技术预览功能无法满足客户需求或未达到我们要求的成熟度，SUSE保留在正式发布前弃用该功能的权利。

请注意，SUSE偶尔必须弃用功能或更改API规范。弃用功能或更改API的原因可能包括：功能被更新或被新实现所取代、新功能集的引入、上游技术不再可用，或者上游社区引入了不兼容的更改。在给定的次要版本（x.z）中，我们不打算进行此类更改，因此所有z-stream版本都将保持API兼容性和功能特性。SUSE将尽力在发行说明中提前发出弃用警告，并提供变通方法、建议和缓解措施，以最大限度地减少服务中断。

SUSE Edge 团队也欢迎社区反馈，您可以在 https://www.github.com/suse-edge[https://www.github.com/suse-edge]内的相应储存库中提出问题。

= 获取源代码

本 SUSE 产品包含根据 GNU 通用公共许可证 (GPL) 及其他各种开源许可证授权给 SUSE 的材料。GPL 要求 SUSE 提供与 GPL 许可材料相对应的源代码，并且 SUSE 符合所有其他开源许可证要求。因此，SUSE 提供了所有源代码，通常可以在 SUSE Edge GitHub 储存库 (https://www.github.com/suse-edge[https://www.github.com/suse-edge])、用于依赖组件的 SUSE Rancher GitHub 储存库 (https://www.github.com/rancher[https://www.github.com/rancher]) 中找到，特别是对于 SUSE Linux Micro，源代码可在 https://www.suse.com/download/sle-micro/[https://www.suse.com/download/sle-micro] 的“Medium 2”上下载。

= 法律声明

SUSE 对本文档的内容或使用不做任何声明或保证，并明确声明免除任何明示或暗示的关于适销性或适用于任何特定用途的保证。此外，SUSE 保留随时修订本出版物及其内容的权利，并且没有义务将这些修订或更改通知任何个人或实体。

此外，SUSE 对任何软件不做任何声明或保证，并明确声明免除任何明示或暗示的关于适销性或适用于任何特定用途的保证。此外，SUSE 保留随时更改 SUSE 软件全部或部分内容的权利，并且没有义务将这些更改通知任何个人或实体。

依据本协议提供的任何产品或技术信息都将受到美国出口控制和其他国家/地区的贸易法律的约束。您同意遵守所有出口控制法规，并同意在出口、再出口或进口可交付产品之前获得任何必要的许可证或分类证书。您同意不出口或再出口至当前美国出口排除列表上所列的实体，或者美国出口法律中规定的任何被禁运的国家/地区或支持恐怖主义的国家/地区。您同意不将可交付产品用于禁止的核、导弹或化学/生物武器的最终用途。有关出口 SUSE 软件的更多信息，请参阅 https://www.suse.com/company/legal/[https://www.suse.com/company/legal/]。如果您未能获得任何必要的出口许可，SUSE 对此不承担任何责任。

*版权所有 © 2024 SUSE LLC。*

本发行说明文档采用知识共享署名-禁止演绎 4.0 国际许可协议 (CC-BY-ND-4.0) 进行许可。您应该已随本文档收到一份许可证副本。如果还没有，请参见 https://creativecommons.org/licenses/by-nd/4.0/[https://creativecommons.org/licenses/by-nd/4.0/]。

SUSE 拥有与本文档所述产品中包含的技术相关的知识产权。特别是，这些知识产权可能包括但不限于在 https://www.suse.com/company/legal/[https://www.suse.com/company/legal/] 中列出的一项或多项美国专利，以及在美国和其他国家/地区的一项或多项其他专利或专利申请。

有关 SUSE 商标的信息，请参阅 SUSE 商标和服务标志列表 (https://www.suse.com/company/legal/[https://www.suse.com/company/legal/])。所有第三方商标均是其各自所有者的财产。有关 SUSE 品牌信息和使用要求，请参阅发布在 https://brand.suse.com/[https://brand.suse.com/] 上的指南。
