[#release-notes]

= 摘要
:revdate: 2026-06-29
:revnumber: 3.6
:page-revdate: {revdate}
ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

{product} 3.6 是一款紧密集成且经过全面验证的端到端解决方案，旨在解决边缘基础设施和云原生应用部署所面临的独特挑战。其主要目标是提供一个具有明确主张、同时高度灵活、可伸缩且安全的平台，涵盖初始部署镜像构建、节点配置和上线、应用部署、可观测性及生命周期管理。

该解决方案的设计理念是，由于客户的需求和期望各不相同，因此不存在“一刀切”的边缘平台。边缘部署促使我们不断解决并优化一些极具挑战性的问题，包括大规模可伸缩性、受限的网络可用性、物理空间限制、新的安全威胁和攻击向量、硬件架构及系统资源的差异、部署和对接旧有基础设施与应用的需求，以及生命周期更长的客户解决方案。

{product} 从底层构建于最优秀的开源软件之上，这既符合我们 30 年来提供安全、稳定和经过认证的 SUSE Linux 平台的历史，也符合我们通过 Rancher 产品组合提供高度可扩展且功能丰富的 Kubernetes 管理的经验。{product} 在这些功能的基础上构建，以提供能够满足众多细分市场需求的功能，包括零售、医疗、交通、物流、电信、智能制造和工业物联网。

有关 {product} 产品支持生命周期更新的更多信息，请参阅 link:https://www.suse.com/lifecycle/#suse-edge-36[产品支持生命周期]。

NOTE: SUSE Telco Cloud 是 SUSE Edge 的衍生产品，具有额外的优化和组件，使该平台能够满足电信用例中的需求。

= 关于

除非另有明确说明和解释，否则这些发行说明在所有架构上都是相同的，并且最新版本以及所有其他 SUSE 产品的发行说明始终可在 https://www.suse.com/releasenotes[https://www.suse.com/releasenotes] 在线获取。

条目仅列出一次，但如果它们很重要且属于多个部分，则可以在多个地方引用它们。发行说明通常仅列出两个后续版本之间发生的更改。以前产品版本的发行说明中的某些重要条目可能会重复。为了更容易识别这些条目，它们包含相关的说明。

但是，重复的条目仅作为一种便利提供。因此，如果您跳过一个或多个版本，请同时查看所跳过版本的发行说明。如果您仅阅读当前版本的发行说明，则可能会错过可能影响系统行为的重要更改。{product} 版本定义为 x.y.z，其中“x”表示主版本，“y”表示次版本，“z”表示补丁版本，也称为“z-stream”。{product} 产品生命周期是根据给定的次要版本定义的，例如。“3.6”，但在其生命周期内会随附后续补丁更新，例如。"3.6.1".

NOTE: {product} z-stream 版本作为版本化堆栈进行了紧密集成和全面测试。将任何单个组件升级到不同于上述版本的版本可能会导致系统停机时间。虽然可以在未经测试的配置中运行 Edge 集群，但不建议这样做，并且通过支持渠道提供解决方案可能需要更长时间。

[#release-notes-3-6-1]
= Release 3.6.1

可用性日期：2026年6月26日

全面支持结束日期：2026年11月27日

维护支持结束日期：2028年5月27日

EOL：2028年5月28日

摘要：{product} 3.6.1 是 {product} 3.6 发布流中的第一个 z-stream 版本。

== 新功能

* 更新至 Kubernetes 1.35.4 和 Rancher Prime 2.14.2
* 更新至 SUSE Security (NeuVector) 5.5.2 https://open-docs.neuvector.com/releasenotes/5x[NeuVector 发行说明]
* 更新至 SUSE Storage (Longhorn) 1.11.2 https://longhorn.io/docs/1.11.1/[上游 Longhorn 发行说明]
* 更新至 Rancher Turtles (CAPI) 0.26.2 https://turtles.docs.rancher.com/[Rancher Turtles 文档]
* 将 Metal^3^/Ironic 更新至 0.15.0，并包含 Ironic 35.0.0.2

== Bug 修复与安全更新

* Kubernetes 1.35.4 包含多项 Bug 修复和安全更新 https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.35.md[Kubernetes 更改日志]
* Rancher Prime 2.14.2 包含多项 Bug 修复 https://github.com/rancher/rancher/releases/tag/v2.14.1[上游 Rancher 发行说明]
* SUSE Storage (Longhorn) 1.11.2 包含多项 Bug 修复 https://github.com/longhorn/longhorn/releases/tag/v1.11.1[上游 Longhorn Bug 修复]
* NeuVector 5.5.2 包含新功能和若干 Bug 修复 https://open-docs.neuvector.com/releasenotes/5x[NeuVector 发行说明]
* Metal^3^/Ironic 更新修复了若干 Bug 和安全问题，包括以下内容：
** https://www.cve.org/CVERecord?id=CVE-2026-44919[CVE-2026-44919]
** https://www.cve.org/CVERecord?id=CVE-2026-46447[CVE-2026-46447]
** https://www.cve.org/CVERecord?id=CVE-2026-48681[CVE-2026-48681]
** https://www.cve.org/CVERecord?id=CVE-2026-44917[CVE-2026-44917]
** https://www.cve.org/CVERecord?id=CVE-2026-43003[CVE-2026-43003]
** https://www.cve.org/CVERecord?id=CVE-2026-50589[CVE-2026-50589]

== 已知问题

[WARNING]
====
如果部署新集群，请先按照 <<guides-kiwi-builder-images>> 构建全新的镜像。 建议管理集群和下游集群执行此操作，以确保镜像包含最新的安全和错误修复。
====

* 当通过 Edge Image Builder 部署时，如果将 `HelmChartConfigs` 清单放入 `kubernetes/manifests` 配置目录，它们可能会失败。建议改为使用 EIB os-files 接口将任何 `HelmChartConfigs` 放置在 `/var/lib/rancher/{rke2/k3s}/server/manifests/` 中。
ifeval::["{flavor}" == "telco"]
请参见<<mgmt-cluster-directory-structure>>中的示例。
endif::[]
如果不这样做，可能会导致节点在初始启动时保持在 `NotReady` 状态，如 https://github.com/rancher/rke2/issues/8357[#8357 RKE2 问题] 中所述。

* 在 RKE2/K3s 1.34 和 1.35 版本中，用于存储 CNI 配置的目录 `/etc/cni` 可能不会因 `overlayfs` 相关的某些条件而触发写入该目录的文件的通知给 `containerd`（请参阅 https://github.com/rancher/rke2/issues/8356[#8356 RKE2 问题]）。这反过来会导致 RKE2/K3s 的部署卡在等待 CNI 启动的状态，并使 RKE2/K3s 节点保持在 `NotReady` 状态。这可以在节点级别通过 `kubectl describe node <affected_node>` 查看：

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

作为一种变通方法，可以在 RKE2 启动之前将 tmpfs 卷挂载到 `/etc/cni` 目录。它避免了使用 overlayfs，因为后者会导致 containerd 丢失通知，并且配置应在每次节点重启和 Pod 初始化容器再次运行时被重写。如果使用 EIB，这可以是一个位于 `04-tmpfs-cni.sh` 目录中的 `custom/scripts` 脚本（如 https://github.com/suse-edge/edge-image-builder/blob/release-1.3/docs/building-images.md#custom[此处] 所述），其内容如下：

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* 目前尚无通过 synce4l 配置 SyncE 以及通过 gpsd 配置 GNSS 的官方文档或示例，这些主题将在未来的版本中涵盖。

* 某些容器仓库目前仅可通过 IPv4 访问，因此对于仅支持 IPv6 的下游集群，需要管理集群上的本地仓库。

== 组件版本

下表描述了构成 3.6.1 版本的各个组件，包括版本、Helm Chart 版本（如果适用），以及可以从何处以二进制格式拉取已发布的制品。请遵循相关文档以获取使用和部署示例。

|======
| 名称 | 版本 | Helm Chart 版本 | 制品位置 (URL/镜像)
| SUSE Linux Micro | 6.2 (最新) | 不适用 | https://www.suse.com/download/sle-micro/[SUSE Linux Micro 下载页面] +
| SUSE Linux Micro | 6.2 (最新) | 不适用 |校验和与签名可从 https://www.suse.com/download/sle-micro/[SUSE Linux Micro 下载页面] 下载 +
SL-Micro.x86_64-6.2-Base-SelfInstall-GM.install.iso +
SL-Micro.x86_64-6.2-Base-RT-SelfInstall-GM.install.iso +
SL-Micro.x86_64-6.2-Base-GM.raw.xz +
SL-Micro.x86_64-6.2-Base-RT-GM.raw.xz +
| SUSE Multi-Linux Manager | 5.1 | 不适用 | https://www.suse.com/download/suse-manager/[SUSE 多 Linux 管理器下载页面]
s| K3s s| 1.35.4 s| 不适用 s| https://github.com/k3s-io/k3s/releases/tag/v1.35.4%2Bk3s1[上游 K3s 版本]
s| RKE2 s| 1.35.4 s| 不适用 s| https://github.com/rancher/rke2/releases/tag/v1.35.4%2Brke2r1[上游 RKE2 版本]
s| SUSE Rancher Prime s| 2.14.2 s| 2.14.2 s| https://charts.rancher.com/server-charts/prime/index.yaml[Rancher Prime Helm 储存库] +
\https://prime.ribs.rancher.io/rancher/v2.14.2/rancher-images.txt[Rancher 2.14.2 Container Images]
s| SUSE Storage (Longhorn) s| 1.11.2 s| 1.11.2 s| https://apps.rancher.io/applications/suse-storage[SUSE Storage Helm 储存库] +
\https://apps.rancher.io/applications/suse-storage/components[SUSE Storage 容器镜像]
s| SUSE Security (NeuVector) s| 5.5.2 s| 109.0.2+up2.10.2 s| https://charts.rancher.io/index.yaml[Rancher Charts Helm 储存库] +
registry.rancher.com/rancher/neuvector-controller:5.5.2 +
registry.rancher.com/rancher/neuvector-enforcer:5.5.2 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.12
s| Rancher Turtles 提供程序 (CAPI) s| 0.26.2 s| 306.0.7+up0.26.2 s| registry.suse.com/edge/3.6/rancher-turtles-providers-chart:306.0.7+up0.26.2 +
registry.rancher.com/rancher/cluster-api-controller:v1.12.2 +
registry.rancher.com/rancher/turtles:v0.26.2 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.24.3 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.24.3
s| Metal^3^s| 0.15.0 s| 306.0.29+up0.15.0 s| registry.suse.com/edge/3.6/metal3-chart:306.0.29+up0.15.0 +
registry.suse.com/edge/3.6/baremetal-operator:0.12.3.0 +
registry.suse.com/edge/3.6/ironic:35.0.0.2 +
registry.suse.com/edge/3.6/ironic-ipa-downloader:3.1.1 +
registry.suse.com/edge/3.6/ironic-python-agent:3.0.9
| MetalLB | 0.15.3 | 306.0.2+up0.15.3 | registry.suse.com/edge/3.6/metallb-chart:306.0.2+up0.15.3 +
registry.suse.com/edge/3.6/metallb-controller:v0.15.3 +
registry.suse.com/edge/3.6/metallb-speaker:v0.15.3
| Elemental | 1.9.0 | 1.9.0 | registry.suse.com/rancher/elemental-operator-chart:1.9.0 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.9.0 +
registry.suse.com/rancher/elemental-operator:1.9.0
| Elemental 仪表板扩展 | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/main/charts/elemental/3.0.1[Elemental 扩展 Helm Chart]
| Edge Image Builder | 1.3.3.1 | 不适用 | registry.suse.com/edge/3.6/edge-image-builder:1.3.3.1
| KubeVirt | 1.7.0 | 306.0.2+up0.7.0 | registry.suse.com/edge/3.6/kubevirt-chart:306.0.2+up0.7.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.7.0-150700.3.16.2
| KubeVirt 仪表板扩展 | 1.3.3 | 306.0.4+up1.3.3 | registry.suse.com/edge/3.6/kubevirt-dashboard-extension-chart:306.0.4+up1.3.3
| 容器化数据导入器 (CDI) | 1.64.0 | 306.0.2+up0.7.0 | registry.suse.com/edge/3.6/cdi-chart:306.0.2+up0.7.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.64.0-150700.9.6.1
| 端点复制器操作员 | 0.3.0 | 306.0.1+up0.3.0 | registry.suse.com/edge/3.6/endpoint-copier-operator-chart:306.0.1+up0.3.0 +
registry.suse.com/edge/3.6/endpoint-copier-operator:0.3.0
| SR-IOV 网络操作员 | 1.6.0 | 306.0.4+up1.6.0 | registry.suse.com/edge/3.6/sriov-network-operator-chart:306.0.4+up1.6.0 +
registry.suse.com/edge/3.6/sriov-crd-chart:306.0.4+up1.6.0
| 系统升级控制器 | 0.19.1 | 109.0.1 | https://charts.rancher.io/index.yaml[Rancher Charts Helm 存储库] +
registry.rancher.com/rancher/system-upgrade-controller:v0.19.1
s| 升级控制器 s| 0.1.3 s| 306.0.4+up0.1.3 s| registry.suse.com/edge/3.6/upgrade-controller-chart:306.0.4+up0.1.3 +
registry.suse.com/edge/3.6/upgrade-controller:0.1.3 +
registry.rancher.com/rancher/kubectl:v1.35.2 +
registry.suse.com/edge/3.6/release-manifest:3.6.1
| SUSE Private Registry | 1.1.1 | 1.1.1 | oci://registry.suse.com/private-registry/private-registry-helm[SUSE Private Registry Helm 存储库] +
registry.suse.com/private-registry/harbor-core:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-jobservice:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-portal:1.1.1-1.20 +
registry.suse.com/private-registry/harbor-registry:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-registryctl:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-trivy-adapter:1.1.1-1.24
| Kiwi 构建器 | 10.2.29.1 | 不适用 | registry.suse.com/edge/3.6/kiwi-builder:10.2.29.1
| Cert-Manager | 1.20.1 | 1.20.1 | https://charts.jetstack.io[Jetstack Helm 存储库] +
quay.io/jetstack/cert-manager-controller:v1.20.1 +
quay.io/jetstack/cert-manager-webhook:v1.20.1 +
quay.io/jetstack/cert-manager-cainjector:v1.20.1
|======

[#release-notes-3-6-0]
= 3.6.0 版本

可用性日期：2026 年 5 月 27 日

全面支持结束日期：2026 年 11 月 27 日

维护支持结束日期：2028 年 5 月 27 日

EOL：2028 年 5 月 28 日

摘要：{product} 3.6.0 是 {product} 3.6 发布流中的第一个版本。

== 新功能

* 更新至 Kubernetes 1.35.3 和 Rancher Prime 2.14.1
* 更新至 SUSE Security (NeuVector) 5.5.1 https://open-docs.neuvector.com/releasenotes/5x[NeuVector 发行说明]
* 更新至 SUSE Storage (Longhorn) 1.11.1 https://longhorn.io/docs/1.11.1/[上游 Longhorn 发行说明]
* 更新至 Rancher Turtles (CAPI) 0.26.1 https://turtles.docs.rancher.com/[Rancher Turtles 文档]
* 更新至 MetalLB 0.15.3 https://metallb.universe.tf/release-notes/#version-0-15-3[上游发行说明]
* 更新至 KubeVirt 1.7.0 和 CDI (Containerized Data Importer) 1.64.0
* 更新至 Elemental 1.9.0 https://elemental.docs.rancher.com/release-notes/[Elemental 发行说明]
* 更新至 Cert-Manager 1.20.1 https://cert-manager.io/docs/release-notes/[上游发行说明]
* 将 Metal3/Ironic 更新至 0.15.0，其中包含 Ironic 35.0.0
* MetalLB 的 BGP 模式在 {product} 3.5 中为技术预览版，现已获得全面支持
* 下游部署中的精确时间协议 (PTP) 在 {product} 3.5 中为技术预览版，现已获得全面支持，同时支持 SyncE 和 GNSS
* 现已支持单栈 IPv6 下游集群部署，但请注意，这需要双栈管理集群（单栈管理集群仍为技术预览版）

== Bug 修复与安全更新

* Kubernetes 1.35.3 包含多项 Bug 修复和安全更新 https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.35.md[Kubernetes 更改日志]
* Rancher Prime 2.14.1 包含多项 Bug 修复 https://github.com/rancher/rancher/releases/tag/v2.14.1[上游 Rancher 发行说明]
* SUSE Storage (Longhorn) 1.11.1 包含多项 Bug 修复 https://github.com/longhorn/longhorn/releases/tag/v1.11.1[上游 Longhorn Bug 修复]
* NeuVector 5.5.1 包含新功能和若干 Bug 修复 https://open-docs.neuvector.com/releasenotes/5x[NeuVector 发行说明]

== 已知问题

[WARNING]
====
如果部署新集群，请先按照 <<guides-kiwi-builder-images>> 构建全新的镜像。 建议管理集群和下游集群执行此操作，以确保镜像包含最新的安全更新和 Bug 修复。
====

* 当通过 Edge Image Builder 部署时，如果将 `HelmChartConfigs` 清单放入 `kubernetes/manifests` 配置目录，它们可能会失败。建议改为使用 EIB os-files 接口将任何 `HelmChartConfigs` 放置在 `/var/lib/rancher/{rke2/k3s}/server/manifests/` 中。
ifeval::["{flavor}" == "telco"]
请参见<<mgmt-cluster-directory-structure>>中的示例。
endif::[]
如果不这样做，可能会导致节点在初始启动时保持在 `NotReady` 状态，如 https://github.com/rancher/rke2/issues/8357[#8357 RKE2 问题] 中所述。

* 在 RKE2/K3s 1.34 和 1.35 版本中，用于存储 CNI 配置的目录 `/etc/cni` 可能不会因与 `containerd` 相关的某些条件而触发向 `overlayfs` 发送文件写入通知（请参阅 https://github.com/rancher/rke2/issues/8356[#8356 RKE2 问题]）。这反过来会导致 RKE2/K3s 的部署卡在等待 CNI 启动的状态，并使 RKE2/K3s 节点保持在 `NotReady` 状态。这可以在节点级别通过 `kubectl describe node <affected_node>` 查看：

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

作为一种变通方法，可以在 RKE2 启动之前将 tmpfs 卷挂载到 `/etc/cni` 目录。它避免了使用 overlayfs，因为后者会导致 containerd 丢失通知，并且配置应在每次节点重启和容器的 init 容器再次运行时被重写。如果使用 EIB，这可以是一个位于 `custom/scripts` 目录中的 `04-tmpfs-cni.sh` 脚本（如 https://github.com/suse-edge/edge-image-builder/blob/release-1.3/docs/building-images.md#custom[此处] 所述），其内容如下：

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* 目前尚无通过 synce4l 配置 SyncE 以及通过 gpsd 配置 GNSS 的官方文档或示例，这些主题将在未来的版本中涵盖。

* 某些容器仓库目前仅可通过 IPv4 访问，因此对于仅支持 IPv6 的下游集群，需要管理集群上的本地仓库。

== 组件版本

下表描述了构成 3.6.0 版本的各个组件，包括版本、Helm chart 版本（如果适用），以及可以从何处以二进制格式拉取已发布的制品。请遵循相关文档以获取使用和部署示例。

|======
| 名称 | 版本 | Helm Chart 版本 | 制品位置 (URL/镜像)
| SUSE Linux Micro | 6.2 (最新) | 不适用 | https://www.suse.com/download/sle-micro/[SUSE Linux Micro 下载页面] +
| SUSE Linux Micro | 6.2 (最新) | 不适用 |校验和与签名可从 https://www.suse.com/download/sle-micro/[SUSE Linux Micro 下载页面] 下载 +
SL-Micro.x86_64-6.2-Base-SelfInstall-GM.install.iso +
SL-Micro.x86_64-6.2-Base-RT-SelfInstall-GM.install.iso +
SL-Micro.x86_64-6.2-Base-GM.raw.xz +
SL-Micro.x86_64-6.2-Base-RT-GM.raw.xz +
| SUSE Multi-Linux Manager | 5.1 | 不适用 | https://www.suse.com/download/suse-manager/[SUSE® Multi-Linux Manager 下载页面]
| K3s | 1.35.3 | 不适用 | https://github.com/k3s-io/k3s/releases/tag/v1.35.3%2Bk3s1[上游 K3s 版本]
| RKE2 | 1.35.3 | 不适用 | https://github.com/rancher/rke2/releases/tag/v1.35.3%2Brke2r3[上游 RKE2 版本]
| SUSE Rancher Prime | 2.14.1 | 2.14.1 | https://charts.rancher.com/server-charts/prime/index.yaml[Rancher Prime Helm 存储库] +
\https://prime.ribs.rancher.io/rancher/v2.14.1/rancher-images.txt[Rancher 2.14.1 Container Images]
| SUSE Storage (Longhorn) | 1.11.1 | 1.11.1 | https://apps.rancher.io/applications/suse-storage[SUSE Storage Helm 存储库] +
\https://apps.rancher.io/applications/suse-storage/components[SUSE Storage 容器镜像]
| SUSE Security (NeuVector) | 5.5.1 | 109.0.1+up2.8.13 | https://charts.rancher.io/index.yaml[Rancher Charts Helm 存储库] +
registry.rancher.com/rancher/neuvector-controller:5.5.1 +
registry.rancher.com/rancher/neuvector-enforcer:5.5.1 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.12
| Rancher Turtles 提供程序 (CAPI) | 0.26.1 | 306.0.6+up0.26.1 | registry.suse.com/edge/3.6/rancher-turtles-providers-chart:306.0.6+up0.26.1 +
registry.rancher.com/rancher/cluster-api-controller:v1.12.2 +
registry.rancher.com/rancher/turtles:v0.26.1 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.24.3 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.24.3
| Metal^3^| 0.15.0 | 306.0.26+up0.15.0 | registry.suse.com/edge/3.6/metal3-chart:306.0.26+up0.15.0 +
registry.suse.com/edge/3.6/baremetal-operator:0.12.3.0 +
registry.suse.com/edge/3.6/ironic:35.0.0.1 +
registry.suse.com/edge/3.6/ironic-ipa-downloader:3.1.1 +
registry.suse.com/edge/3.6/ironic-python-agent:3.0.8
| MetalLB | 0.15.3 | 306.0.2+up0.15.3 | registry.suse.com/edge/3.6/metallb-chart:306.0.2+up0.15.3 +
registry.suse.com/edge/3.6/metallb-controller:v0.15.3 +
registry.suse.com/edge/3.6/metallb-speaker:v0.15.3
| Elemental | 1.9.0 | 1.9.0 | registry.suse.com/rancher/elemental-operator-chart:1.9.0 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.9.0 +
registry.suse.com/rancher/elemental-operator:1.9.0
| Elemental 仪表板扩展 | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/main/charts/elemental/3.0.1[Elemental 扩展 Helm Chart]
| Edge Image Builder | 1.3.3.1 | 不适用 | registry.suse.com/edge/3.6/edge-image-builder:1.3.3.1
| KubeVirt | 1.7.0 | 306.0.2+up0.7.0 | registry.suse.com/edge/3.6/kubevirt-chart:306.0.2+up0.7.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.7.0-150700.3.16.2
| KubeVirt 仪表板扩展 | 1.3.3 | 306.0.4+up1.3.3 | registry.suse.com/edge/3.6/kubevirt-dashboard-extension-chart:306.0.4+up1.3.3
| 容器化数据导入器 (CDI) | 1.64.0 | 306.0.2+up0.7.0 | registry.suse.com/edge/3.6/cdi-chart:306.0.2+up0.7.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.64.0-150700.9.6.1
| 端点复制器操作员 | 0.3.0 | 306.0.1+up0.3.0 | registry.suse.com/edge/3.6/endpoint-copier-operator-chart:306.0.1+up0.3.0 +
registry.suse.com/edge/3.6/endpoint-copier-operator:0.3.0
| SR-IOV 网络操作员 | 1.6.0 | 306.0.4+up1.6.0 | registry.suse.com/edge/3.6/sriov-network-operator-chart:306.0.4+up1.6.0 +
registry.suse.com/edge/3.6/sriov-crd-chart:306.0.4+up1.6.0
| 系统升级控制器 | 0.19.1 | 109.0.1 | https://charts.rancher.io/index.yaml[Rancher Charts Helm 存储库] +
registry.rancher.com/rancher/system-upgrade-controller:v0.19.1
| 升级控制器 | 0.1.3 | 306.0.3+up0.1.3 | registry.suse.com/edge/3.6/upgrade-controller-chart:306.0.3+up0.1.3 +
registry.suse.com/edge/3.6/upgrade-controller:0.1.3 +
registry.rancher.com/rancher/kubectl:v1.35.2 +
registry.suse.com/edge/3.6/release-manifest:3.6.0
| SUSE Private Registry | 1.1.1 | 1.1.1 | oci://registry.suse.com/private-registry/private-registry-helm[SUSE Private Registry Helm 存储库] +
registry.suse.com/private-registry/harbor-core:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-jobservice:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-portal:1.1.1-1.20 +
registry.suse.com/private-registry/harbor-registry:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-registryctl:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-trivy-adapter:1.1.1-1.24
| Kiwi 构建器 | 10.2.29.1 | 不适用 | registry.suse.com/edge/3.6/kiwi-builder:10.2.29.1
| Cert-Manager | 1.20.1 | 1.20.1 | https://charts.jetstack.io[Jetstack Helm 存储库] +
quay.io/jetstack/cert-manager-controller:v1.20.1 +
quay.io/jetstack/cert-manager-webhook:v1.20.1 +
quay.io/jetstack/cert-manager-cainjector:v1.20.1
|======

= 已去除功能

除非另有说明，否则这些内容适用于 {version-edge}.0 版本及所有后续 z-stream 版本。

* Akri 在之前的 Edge 版本中是一项技术预览功能，从 3.4.0 版本开始被弃用。它现已从产品中完全去除。

[#tech-previews]
= 技术预览

除非另有说明，否则这些内容适用于 3.6.0 版本及所有后续 z-stream 版本。

* 单栈 IPv6 管理集群部署是一项技术预览功能，不属于标准支持范围。

= 组件验证

上述组件可以使用软件物料清单 (SBOM) 数据进行验证 - 例如，使用如下所述的 `cosign`：

从 https://www.suse.com/support/security/keys/[SUSE 签名密钥源] 下载 {product} 容器公钥：

[,bash]
----
include::key.sh[]
----

验证容器镜像哈希，例如使用 `crane`：

[,bash]
----
> crane digest registry.suse.com/edge/3.6/baremetal-operator:0.12.3.0 --platform linux/amd64
sha256:example-digest-placeholder
----

NOTE: 对于多架构镜像，在获取摘要时还需要指定平台，例如 `--platform linux/amd64` 或 `--platform linux/arm64`。如果不这样做，将在后续步骤 (`Error: no matching attestations`) 中导致错误。

使用 `cosign` 进行验证：

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/3.6/baremetal-operator@sha256:example-digest-placeholder > /dev/null
#
Verification for registry.suse.com/edge/3.6/baremetal-operator@sha256:example-digest-placeholder --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - The signatures were verified against the specified public key
----

按照 https://www.suse.com/support/security/sbom/[SUSE SBOM 文档] 中的说明提取 SBOM 数据：

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/3.6/baremetal-operator@sha256:example-digest-placeholder | jq '.payload | @base64d | fromjson | .predicate'
----

= 升级步骤

有关如何升级到新版本的详细信息，请参阅 <<day-2-operations>>。

= 产品支持生命周期

{product} 由 SUSE 提供屡获殊荣的支持，SUSE 是一家成熟的技术领导者，在提供企业级支持服务方面拥有良好的记录。有关更多信息，请参阅 https://www.suse.com/lifecycle[https://www.suse.com/lifecycle] 以及 https://www.suse.com/support/policy.html[https://www.suse.com/support/policy.html] 处的支持策略页面。如果您对提交支持案例、SUSE 如何划分严重性级别或支持范围有任何疑问，请参阅 https://www.suse.com/support/handbook/[https://www.suse.com/support/handbook/] 处的技术支持手册。

{product} “3.6”版本提供24个月的生产支持，其中最初6个月为“全面支持”，随后18个月为“维护支持”。 在这些支持阶段之后，产品达到“终止服务”（EOL），并不再获得支持。有关生命周期阶段的更多信息，请参见下表：

|======
| *全面支持（6个月）*| 在全面支持期间，将发布紧急和选定的高优先级 Bug 修复，所有其他补丁（非紧急、增强功能、新功能）将通过常规发布计划发布。
| *维护支持（18个月）*| 在此期间，仅通过补丁发布关键修复。其他 Bug 修复可能会由SUSE酌情发布，但不应抱有预期。
| *终止服务（EOL）* | 一旦产品版本达到其终止服务日期，客户可以在产品许可协议的条款范围内继续使用该产品。
SUSE的支持计划不适用于已过终止服务日期的产品版本。
|======

除非另有明确说明，否则所列出的所有组件均被视为一般可用（GA），并涵盖在SUSE的标准支持范围内。某些组件可能被列为“技术预览”，SUSE在此为客户提供早期预发布功能以供评估，但这些组件不受标准支持政策的约束，也不建议用于生产环境。SUSE非常欢迎对技术预览组件的改进提出反馈和建议，但如果技术预览功能无法满足客户需求或未达到我们要求的成熟度，SUSE保留在正式发布前弃用该功能的权利。

请注意，SUSE偶尔必须弃用功能或更改API规范。弃用功能或更改API的原因可能包括：功能被更新或被新实现所取代、新功能集的引入、上游技术不再可用，或者上游社区引入了不兼容的更改。在给定的次要版本（x.z）中，我们不打算进行此类更改，因此所有z-stream版本都将保持API兼容性和功能特性。SUSE将尽力在发行说明中提前发出弃用警告，并提供变通方法、建议和缓解措施，以最大限度地减少服务中断。

{product}团队也欢迎社区反馈，您可以在 https://www.github.com/suse-edge[https://www.github.com/suse-edge]内的相应储存库中提出问题。

= 获取源代码

本 SUSE 产品包含根据 GNU 通用公共许可证 (GPL) 及其他各种开源许可证授权给 SUSE 的材料。GPL 要求 SUSE 提供与 GPL 许可材料相对应的源代码，并且 SUSE 符合所有其他开源许可证要求。因此，SUSE 提供了所有源代码，通常可以在 {product} GitHub 储存库 (https://www.github.com/suse-edge[https://www.github.com/suse-edge])、用于依赖组件的 SUSE Rancher GitHub 储存库 (https://www.github.com/rancher[https://www.github.com/rancher]) 中找到，特别是对于 SUSE Linux Micro，源代码可在 https://www.suse.com/download/sle-micro/[https://www.suse.com/download/sle-micro] 的“Medium 2”上下载。

= 法律声明

SUSE 对本文档的内容或使用不做任何声明或保证，并明确声明免除任何明示或暗示的关于适销性或适用于任何特定用途的保证。此外，SUSE 保留随时修订本出版物及其内容的权利，并且没有义务将这些修订或更改通知任何个人或实体。

此外，SUSE 对任何软件不做任何声明或保证，并明确声明免除任何明示或暗示的关于适销性或适用于任何特定用途的保证。此外，SUSE 保留随时更改 SUSE 软件全部或部分内容的权利，并且没有义务将这些更改通知任何个人或实体。

依据本协议提供的任何产品或技术信息都将受到美国出口控制和其他国家/地区的贸易法律的约束。您同意遵守所有出口控制法规，并同意在出口、再出口或进口可交付产品之前获得任何必要的许可证或分类证书。您同意不出口或再出口至当前美国出口排除列表上所列的实体，或者美国出口法律中规定的任何被禁运的国家/地区或支持恐怖主义的国家/地区。您同意不将可交付产品用于禁止的核、导弹或化学/生物武器的最终用途。有关出口 SUSE 软件的更多信息，请参阅 https://www.suse.com/company/legal/[https://www.suse.com/company/legal/]。如果您未能获得任何必要的出口许可，SUSE 对此不承担任何责任。

*版权所有 © 2024 SUSE LLC。*

本发行说明文档采用知识共享署名-禁止演绎 4.0 国际许可协议 (CC-BY-ND-4.0) 进行许可。您应该已随本文档收到一份许可证副本。如果还没有，请参见 https://creativecommons.org/licenses/by-nd/4.0/[https://creativecommons.org/licenses/by-nd/4.0/]。

SUSE 拥有与本文档所述产品中包含的技术相关的知识产权。特别是，这些知识产权可能包括但不限于在 https://www.suse.com/company/legal/[https://www.suse.com/company/legal/] 中列出的一项或多项美国专利，以及在美国和其他国家/地区的一项或多项其他专利或专利申请。

有关 SUSE 商标的信息，请参阅 SUSE 商标和服务标志列表 (https://www.suse.com/company/legal/[https://www.suse.com/company/legal/])。所有第三方商标均是其各自所有者的财产。有关 SUSE 品牌信息和使用要求，请参阅发布在 https://brand.suse.com/[https://brand.suse.com/] 上的指南。
