[#release-notes-abstract]
= Abstrato
:revdate: 2026-03-18
:revnumber: 3.5
:page-revdate: {revdate}
ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

O SUSE Edge 3.5 é uma solução de ponta a ponta fortemente integrada e abrangentemente validada para abordar os desafios únicos da implantação de infraestrutura e aplicativos nativos de nuvem na borda. Seu foco principal é fornecer uma plataforma opinativa, porém altamente flexível, altamente escalável e segura que abrange a construção de imagem de implantação inicial, provisionamento e integração de nós, implantação de aplicativos, observabilidade e gerenciamento de ciclo de vida.

A solução foi projetada com a noção de que não existe uma plataforma de borda de "tamanho único" devido aos requisitos e expectativas amplamente variados de nossos clientes. As implantações de borda nos levam a resolver, e evoluir continuamente, alguns dos problemas mais desafiadores, incluindo escalabilidade massiva, disponibilidade de rede restrita, restrições de espaço físico, novas ameaças de segurança e vetores de ataque, variações na arquitetura de hardware e recursos do sistema, o requisito de implantar e interagir com infraestrutura e aplicativos legados, e soluções de clientes que possuem vida útil estendida.

O SUSE Edge é construído desde o início com o melhor software de código aberto, consistente tanto com nossa história de 30 anos na entrega de plataformas SUSE Linux seguras, estáveis e certificadas, quanto com nossa experiência no fornecimento de gerenciamento de Kubernetes altamente escalável e rico em recursos com nosso portfólio Rancher. O SUSE Edge baseia-se nessas capacidades para fornecer funcionalidades que podem atender a um grande número de segmentos de mercado, incluindo varejo, médico, transporte, logística, telecomunicações, manufatura inteligente e IoT industrial.

Para obter mais informações sobre atualizações do ciclo de vida de suporte do produto para o SUSE Edge, consulte link:https://www.suse.com/lifecycle/#suse-edge-33[Product Support Lifecycle]. 

NOTE: O SUSE Telco Cloud (anteriormente conhecido como SUSE Edge for Telco) é um derivado do SUSE Edge, com otimizações e componentes adicionais que permitem que a plataforma atenda aos requisitos encontrados em casos de uso de telecomunicações. A menos que explicitamente declarado, todas as notas de lançamento são aplicáveis tanto ao SUSE Edge 3.5 quanto ao SUSE Telco Cloud 3.5.

= Sobre

Estas Notas de Lançamento são, a menos que explicitamente especificado e explicado, idênticas em todas as arquiteturas, e a versão mais recente, juntamente com as notas de lançamento de todos os outros produtos SUSE, estão sempre disponíveis online em https://www.suse.com/releasenotes[https://www.suse.com/releasenotes].

As entradas são listadas apenas uma vez, mas podem ser referenciadas em vários lugares se forem importantes e pertencerem a mais de uma seção. As notas de lançamento geralmente listam apenas as alterações que ocorreram entre dois lançamentos subsequentes. Algumas entradas importantes das notas de lançamento de versões anteriores do produto podem ser repetidas. Para tornar essas entradas mais fáceis de identificar, elas contêm uma nota para esse efeito.

No entanto, as entradas repetidas são fornecidas apenas como uma cortesia. Portanto, se você estiver pulando um ou mais lançamentos, verifique também as notas de lançamento dos lançamentos ignorados. Se você estiver lendo apenas as notas de lançamento da versão atual, poderá perder mudanças importantes que podem afetar o comportamento do sistema. As versões do SUSE Edge são definidas como x.y.z, onde 'x' denota a versão principal, 'y' denota a versão secundária e 'z' denota a versão de patch, também conhecida como "z-stream". Os ciclos de vida do produto SUSE Edge são definidos com base em um determinado lançamento secundário, por exemplo. "3.5", mas são fornecidos com atualizações de patch subsequentes ao longo de seu ciclo de vida, por exemplo. "3.5.1".

NOTE: Os lançamentos z-stream do SUSE Edge são fortemente integrados e completamente testados como uma pilha versionada. Fazer upgrade de quaisquer componentes individuais para versões diferentes daquelas listadas acima provavelmente resultará em tempo de inatividade do sistema. Embora seja possível executar clusters Edge em configurações não testadas, isso não é recomendado e pode levar mais tempo para fornecer uma resolução por meio dos canais de suporte.

[#release-notes-3-5-2]
= Versão 3.5.2

Data de disponibilidade: 7 de julho de 2026

Data de término do suporte completo: 21 de julho de 2026

Data de término do suporte de manutenção: 21 de julho de 2027

EOL: 22 de julho de 2027

Resumo: O SUSE Edge 3.5.2 é o segundo lançamento z-stream no fluxo de lançamento do SUSE Edge 3.5.

== Novos recursos

* Atualizado para Kubernetes 1.34.7 e Rancher Prime 2.13.6
* Atualizado para SUSE Storage (Longhorn) 1.10.2 https://longhorn.io/docs/1.10.2/[Notas de lançamento do Longhorn upstream]
* Atualizado para SUSE Security (NeuVector) 5.5.1 https://open-docs.neuvector.com/releasenotes/5x/#551-april-2026[Notas de lançamento]
* Atualizado o chart Metal^3^ para 305.0.26+up0.13.2 com várias melhorias
* Atualizado o chart Upgrade Controller para 305.0.3+up0.1.3

== Correções de bug e segurança

* O Rancher Prime 2.13.6 contém várias correções de bugs e atualizações de segurança https://github.com/rancher/rancher/releases/tag/v2.13.6[Notas de lançamento do Rancher Upstream]
* As atualizações do Metal^3^/Ironic corrigem vários bugs e problemas de segurança, incluindo os seguintes:
** Fix CVE-2026-44916
** Fix CVE-2026-44917
** Fix CVE-2026-44919
** Fix CVE-2026-46447
** Fix CVE-2026-48681
** Fix CVE-2026-50589
** Fix CVE-2026-54421

== Problemas conhecidos

* Executar o https://documentation.suse.com/suse-edge/{version-edge}/html/edge/atip-features.html#ptp-telco-config[recurso PTP] na configuração padrão requer etapas adicionais:
O seguinte precisa ser adicionado às substituições no serviço ptp4l para que ele funcione corretamente na versão Edge 3.5:
[,bash]
----
[Service]
PrivateDevices=
DevicePolicy=closed
DeviceAllow=/dev/rtc rwm
DeviceAllow=char-ptp rwm
DeviceAllow=/dev/ptp0 rwm
----

Isso pode ser alcançado editando `/etc/systemd/system/ptp4l.service.d/override.conf` ou executando `systemctl edit ptp4l.service`
A correção adequada para isso será incluída assim que o https://bugzilla.suse.com/show_bug.cgi?id=1256059[bug do pacote linuxptp] for corrigido.

[WARNING]
====
Ao implantar novos clusters, siga <<guides-kiwi-builder-images>> para criar imagens novas primeiro, pois esta é agora a primeira etapa necessária para criar clusters para as arquiteturas {x86-64} e {aarch64}, bem como clusters de gerenciamento e downstream.
====

* Ao implantar via Edge Image Builder, os manifestos `HelmChartConfigs` podem falhar se forem colocados no diretório de configuração `kubernetes/manifests`. Em vez disso, recomenda-se colocar qualquer `HelmChartConfigs` em `/var/lib/rancher/{rke2/k3s}/server/manifests/` usando a interface os-files do EIB, consulte <<mgmt-cluster-directory-structure>> como exemplo.  Falhar em fazer isso pode fazer com que os nós permaneçam no estado `NotReady` na inicialização inicial, conforme discutido em https://github.com/rancher/rke2/issues/8357[#8357 problema do RKE2].

* Nas versões RKE2/K3s 1.31, 1.32, 1.33 e 1.34, o diretório `/etc/cni` usado para armazenar configurações de CNI pode não disparar uma notificação dos arquivos gravados para `containerd` devido a certas condições relacionadas ao `overlayfs` (consulte o https://github.com/rancher/rke2/issues/8356[#8356 problema do RKE2]). Isso, por sua vez, faz com que a implantação do RKE2/K3s fique travada aguardando a inicialização do CNI, e os nós do RKE2/K3s permaneçam no estado `NotReady`. Isso pode ser visto no nível do nó com `kubectl describe node <affected_node>`:

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

Como solução alternativa, um volume tmpfs pode ser montado no diretório `/etc/cni` antes que o RKE2 seja iniciado. Isso evita o uso de overlayfs, o que faz com que o containerd perca notificações, e as configurações devem ser reescritas toda vez que o nó for reiniciado e os initcontainers dos pods forem executados novamente. Se estiver usando o EIB, este pode ser um script `04-tmpfs-cni.sh` no diretório `custom/scripts` (conforme explicado aqui[https://github.com/suse-edge/edge-image-builder/blob/release-1.2/docs/building-images.md#custom]) que se parece com:

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* Ao integrar hosts remotos usando o Elemental, uma condição de corrida entre `dbus.service` e `elemental-system-agent.service` pode ocorrer, resultando na falha de inicialização do `rancher-system-agent.service` no host remoto com erros semelhantes ao abaixo. (consulte o https://github.com/suse-edge/edge-image-builder/issues/784[#784 problema do Edge Image Builder] para obter detalhes.)

[,bash]
----
Sep 19 19:38:07 elementalvm elemental-system-agent[3671]: time="2025-09-19T19:38:07Z" level=info msg="[6b20fe64c854da2639804884b34129bb8f718eb59578111da58d9de1509c24db_1:stderr]: Failed to restart rancher-system-agent.service: Message recipient disconnected from message bus without replying"
----

Como solução alternativa, um arquivo de substituição do systemd pode ser criado conforme abaixo

[,bash]
----
[Unit]
Wants=dbus.service network-online.target
After=dbus.service network-online.target time-sync.target

[Service]
ExecStartPre=/bin/bash -c 'echo "Waiting for dbus to become active..." | systemd-cat -p info -t elemental-system-agent; sleep 15; timeout 300 bash -c "while ! systemctl is-active --quiet dbus.service; do sleep 15; done"'
----

e um script personalizado chamado `30a-copy-elemental-system-agent-override.sh` pode ser usado para colocar a substituição em `/etc/systemd/system/elemental-system-agent.service.d` antes que o script https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/templates/31-elemental-register.sh.tpl[31-elemental-register.sh] do EIB seja executado durante a fase de combustão.

[,bash]
----
#!/bin/bash

/bin/mkdir -p /etc/systemd/system/elemental-system-agent.service.d
/bin/cp -f elemental-system-agent-override.conf /etc/systemd/system/elemental-system-agent.service.d/override.conf
----

== Versões dos Componentes

A tabela a seguir descreve os componentes individuais que compõem a versão 3.5.2, incluindo a versão, a versão do chart Helm (se aplicável), e de onde o artefato pode ser extraído no formato binário. Siga a documentação associada para exemplos de uso e implantação.

|======
| Nome | Versão | Versão do Gráfico Helm | Local do artefato (URL/Imagem)
| SUSE Linux Micro | 6.2 (mais recente) | N/A | https://www.suse.com/download/sle-micro/[Página de download do SUSE Linux Micro] +
SL-Micro.x86_64-6.2-Base-SelfInstall-GM.install.iso (sha256 76390cec4537821d90975d924bf9d7575c9912da89fa460383eff0c623fd403e) +
SL-Micro.x86_64-6.2-Base-RT-SelfInstall-GM.install.iso (sha256 8f4d03c6953966174efb4c4b176cbe6dd5cab6e2a406033fc5c2bf6884da8b5d) +
SL-Micro.x86_64-6.2-Base-GM.raw.xz (sha256 bea3ac202b54ee29fabc28568f50c86d34939cf861679f21a91dfbae9c54c92e) +
SL-Micro.x86_64-6.2-Base-RT-GM.raw.xz (sha256 b9af7763c8d63143e31e5f80eb8d06fcc9477a576de8e358ab2e9835ab39d305) +
| SUSE Multi-Linux Manager | 5.1 | N/A | https://www.suse.com/download/suse-manager/[Página de download do SUSE Multi-Linux Manager]
s| K3s s| 1.34.7 s| N/A s| https://github.com/k3s-io/k3s/releases/tag/v1.34.7%2Bk3s1[Versão upstream do K3s]
s| RKE2 s| 1.34.7 s| N/A s| https://github.com/rancher/rke2/releases/tag/v1.34.7%2Brke2r1[Versão upstream do RKE2]
s| SUSE Rancher Prime s| 2.13.6 s| 2.13.6 s| https://charts.rancher.com/server-charts/prime/index.yaml[Repositório Helm do Rancher Prime] +
\https://prime.ribs.rancher.io/rancher/v2.13.6/rancher-images.txt[Rancher 2.13.6 Container Images]
| SUSE Storage (Longhorn) | 1.10.2 | 1.10.2 | https://apps.rancher.io/applications/suse-storage[Repositório Helm do SUSE Storage] +
\https://apps.rancher.io/applications/suse-storage/components[Imagens de Contêiner do SUSE Storage]
s| SUSE Security s| 5.5.1 s| 108.0.4+up2.8.13 s| https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.suse.com/rancher/neuvector-controller:5.4.9 +
registry.suse.com/rancher/neuvector-enforcer:5.4.9 +
registry.suse.com/rancher/neuvector-manager:5.4.9 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.9 +
registry.suse.com/rancher/neuvector-registry-adapter:0.2.2 +
registry.suse.com/rancher/neuvector-scanner:6 +
registry.suse.com/rancher/neuvector-updater:0.0.7
| Provedores do Rancher Turtles (CAPI) | 0.25.4 | 305.0.5+up0.25.4 | registry.suse.com/edge/charts/rancher-turtles-providers:305.0.5+up0.25.4 +
registry.rancher.com/rancher/cluster-api-metal3-controller:v1.10.4 +
registry.rancher.com/rancher/cluster-api-metal3-ipam-controller:v1.10.4 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.21.1 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.21.1
s| Metal^3^ s| 0.13.2 s| 305.0.26+up0.13.2 s| registry.suse.com/edge/charts/metal3:305.0.26+up0.13.2 +
registry.suse.com/edge/3.5/baremetal-operator:0.11.2.0 +
registry.suse.com/edge/3.5/ironic:32.0.1.0 +
registry.suse.com/edge/3.5/ironic-ipa-downloader:3.0.11 +
registry.suse.com/edge/mariadb:10.11
| MetalLB | 0.15.2 | 305.0.1+up0.15.2 | registry.suse.com/edge/charts/metallb:305.0.1+up0.15.2 +
registry.suse.com/edge/3.5/metallb-controller:v0.15.2 +
registry.suse.com/edge/3.5/metallb-speaker:v0.15.2 +
registry.suse.com/edge/3.5/frr:10.2.1 +
registry.suse.com/edge/3.5/frr-k8s:v0.0.20 +
registry.suse.com/edge/3.5/kube-rbac-proxy:0.19.1
| Elemental | 1.8.1 | 1.8.1 | registry.suse.com/rancher/elemental-operator-chart:1.8.1 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.8.1 +
registry.suse.com/rancher/elemental-operator:1.8.1
| Extensão do Painel Elemental | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/4.0.0/charts/elemental/3.0.1[Helm Chart da Extensão Elemental]
s| Edge Image Builder s| 1.3.3.1 s| N/A s| registry.suse.com/edge/3.5/edge-image-builder:1.3.3.1
| Configurador NM | 0.3.5 | N/A | https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.5[Lançamento do NMConfigurator upstream]
| KubeVirt | 1.5.2 | 305.0.1+up0.6.0 | registry.suse.com/edge/charts/kubevirt:305.0.1+up0.6.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportproxy:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportserver:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.5.2
| Extensão do Painel KubeVirt | 1.3.3 | 305.0.4+up1.3.3 | registry.suse.com/edge/charts/kubevirt-dashboard-extension:305.0.4+up1.3.3
| Conteinerizado Importador de Dados | 1.62.0 | 305.0.1+up0.6.0 | registry.suse.com/edge/charts/cdi:305.0.1+up0.6.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-importer:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-cloner:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.62.0
| Operador Endpoint Copier | 0.3.0 | 305.0.1+up0.3.0 | registry.suse.com/edge/charts/endpoint-copier-operator:305.0.1+up0.3.0 +
registry.suse.com/edge/3.5/endpoint-copier-operator:0.3.0
| Akri (Descontinuado) | 0.12.20 | 305.0.0+up0.12.20 | registry.suse.com/edge/charts/akri:305.0.0+up0.12.20 +
registry.suse.com/edge/charts/akri-dashboard-extension:305.0.0+up1.3.1 +
registry.suse.com/edge/3.5/akri-agent:v0.12.20 +
registry.suse.com/edge/3.5/akri-controller:v0.12.20 +
registry.suse.com/edge/3.5/akri-debug-echo-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.5/akri-onvif-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.5/akri-opcua-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.5/akri-udev-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.5/akri-webhook-configuration:v0.12.20
| Operador de Rede SR-IOV | 1.6.0 | 305.0.4+up1.6.0 | registry.suse.com/edge/charts/sriov-network-operator:305.0.4+up1.6.0 +
registry.suse.com/edge/charts/sriov-crd:305.0.4+up1.6.0
| Upgrade Controller | 0.17.0 | 108.0.0 | https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.suse.com/rancher/system-upgrade-controller:v0.17.0
| Upgrade Controller | 0.1.3 | 305.0.3+up0.1.3 | registry.suse.com/edge/charts/upgrade-controller:305.0.3+up0.1.3 +
registry.suse.com/edge/3.5/upgrade-controller:0.1.3 +
registry.suse.com/edge/3.5/kubectl:1.34.2 +
registry.suse.com/edge/3.5/release-manifest:3.5.2
| Kiwi Builder | 10.2.29.1 | N/A | registry.suse.com/edge/3.5/kiwi-builder:10.2.29.1
|======

[#release-notes-3-5-1]
= Versão 3.5.1

Data de disponibilidade: 18 de março de 2026

Data de término do suporte completo: 21 de julho de 2026

Data de término do suporte de manutenção: 21 de julho de 2027

EOL: 22 de julho de 2027

Resumo: O SUSE Edge 3.5.1 é a primeira versão z-stream no fluxo de lançamento do SUSE Edge 3.5.

== Novos recursos

* Atualizado para Kubernetes 1.34.4 e Rancher Prime 2.13.3
* Atualizado para SUSE Storage (Longhorn) 1.10.2 https://longhorn.io/docs/1.10.2/[Notas de lançamento do Longhorn upstream]
* Atualizado para SUSE Security (NeuVector) 5.4.9 https://open-docs.neuvector.com/releasenotes/5x/#549-february-2026[Notas de lançamento]
* Atualizado o Elemental para 1.8.1
* Edge Image Builder atualizado para 1.3.3, veja https://github.com/suse-edge/edge-image-builder/blob/release-1.3/RELEASE_NOTES.md[Notas de lançamento upstream]
* SUSE Multi-Linux Manager atualizado para 5.1.2 veja https://www.suse.com/releasenotes/x86_64/multi-linux-manager/5.1/index.html[Notas de lançamento]

== Correções de bug e segurança

* O Rancher Prime 2.13.3 contém várias correções de bug https://github.com/rancher/rancher/releases/tag/v2.13.3[Notas de lançamento do Rancher upstream]
* O SUSE Storage (Longhorn) 1.10.2 contém várias correções de bug https://github.com/longhorn/longhorn/releases/tag/v1.10.2[Correções de bug do Longhorn upstream]
* O SUSE Security (NeuVector) 5.4.8 contém várias correções de bug https://open-docs.neuvector.com/releasenotes/5x/#bugs-fixed[Correções de bug do NeuVector upstream]
* O EIB (edge-image-builder) 1.3.3 contém várias correções de bug https://github.com/suse-edge/edge-image-builder/blob/release-1.3/RELEASE_NOTES.md#bug-fixes[Correções de bug do EIB]
* Atualizado o chart Metal3 com várias correções de bug

== Problemas conhecidos

* Executar o https://documentation.suse.com/suse-edge/{version-edge}/html/edge/atip-features.html#ptp-telco-config[recurso PTP] na configuração padrão requer etapas adicionais:
O seguinte precisa ser adicionado às substituições no serviço ptp4l para que ele funcione corretamente na versão Edge 3.5:
[,bash]
----
[Service]
PrivateDevices=
DevicePolicy=closed
DeviceAllow=/dev/rtc rwm
DeviceAllow=char-ptp rwm
DeviceAllow=/dev/ptp0 rwm
----

Isso pode ser alcançado editando `/etc/systemd/system/ptp4l.service.d/override.conf` ou executando `systemctl edit ptp4l.service`
A correção adequada para isso será incluída assim que o https://bugzilla.suse.com/show_bug.cgi?id=1256059[bug do pacote linuxptp] for corrigido.

[WARNING]
====
Ao implantar novos clusters, siga <<guides-kiwi-builder-images>> para criar imagens novas primeiro, pois esta é agora a primeira etapa necessária para criar clusters para as arquiteturas {x86-64} e {aarch64}, bem como clusters de gerenciamento e downstream.
====

* Ao implantar via Edge Image Builder, os manifestos `HelmChartConfigs` podem falhar se forem colocados no diretório de configuração `kubernetes/manifests`. Em vez disso, recomenda-se colocar qualquer `HelmChartConfigs` em `/var/lib/rancher/{rke2/k3s}/server/manifests/` usando a interface os-files do EIB, consulte <<mgmt-cluster-directory-structure>> como exemplo.  Falhar em fazer isso pode fazer com que os nós permaneçam no estado `NotReady` na inicialização inicial, conforme discutido em https://github.com/rancher/rke2/issues/8357[#8357 problema do RKE2].

* Nas versões RKE2/K3s 1.31, 1.32, 1.33 e 1.34, o diretório `/etc/cni` usado para armazenar configurações de CNI pode não disparar uma notificação dos arquivos gravados para `containerd` devido a certas condições relacionadas ao `overlayfs` (consulte o https://github.com/rancher/rke2/issues/8356[#8356 problema do RKE2]). Isso, por sua vez, faz com que a implantação do RKE2/K3s fique travada aguardando a inicialização do CNI, e os nós do RKE2/K3s permaneçam no estado `NotReady`. Isso pode ser visto no nível do nó com `kubectl describe node <affected_node>`:

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

Como solução alternativa, um volume tmpfs pode ser montado no diretório `/etc/cni` antes que o RKE2 seja iniciado. Isso evita o uso de overlayfs, o que faz com que o containerd perca notificações, e as configurações devem ser reescritas toda vez que o nó for reiniciado e os initcontainers dos pods forem executados novamente. Se estiver usando o EIB, este pode ser um script `04-tmpfs-cni.sh` no diretório `custom/scripts` (conforme explicado aqui[https://github.com/suse-edge/edge-image-builder/blob/release-1.2/docs/building-images.md#custom]) que se parece com:

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* Ao integrar hosts remotos usando o Elemental, uma condição de corrida entre `dbus.service` e `elemental-system-agent.service` pode ocorrer, resultando na falha de inicialização do `rancher-system-agent.service` no host remoto com erros semelhantes ao abaixo. (consulte o https://github.com/suse-edge/edge-image-builder/issues/784[#784 problema do Edge Image Builder] para obter detalhes.)

[,bash]
----
Sep 19 19:38:07 elementalvm elemental-system-agent[3671]: time="2025-09-19T19:38:07Z" level=info msg="[6b20fe64c854da2639804884b34129bb8f718eb59578111da58d9de1509c24db_1:stderr]: Failed to restart rancher-system-agent.service: Message recipient disconnected from message bus without replying"
----

Como solução alternativa, um arquivo de substituição do systemd pode ser criado conforme abaixo

[,bash]
----
[Unit]
Wants=dbus.service network-online.target
After=dbus.service network-online.target time-sync.target

[Service]
ExecStartPre=/bin/bash -c 'echo "Waiting for dbus to become active..." | systemd-cat -p info -t elemental-system-agent; sleep 15; timeout 300 bash -c "while ! systemctl is-active --quiet dbus.service; do sleep 15; done"'
----

e um script personalizado chamado `30a-copy-elemental-system-agent-override.sh` pode ser usado para colocar a substituição em `/etc/systemd/system/elemental-system-agent.service.d` antes que o script https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/templates/31-elemental-register.sh.tpl[31-elemental-register.sh] do EIB seja executado durante a fase de combustão.

[,bash]
----
#!/bin/bash

/bin/mkdir -p /etc/systemd/system/elemental-system-agent.service.d
/bin/cp -f elemental-system-agent-override.conf /etc/systemd/system/elemental-system-agent.service.d/override.conf
----

== Versões dos Componentes

A tabela a seguir descreve os componentes individuais que compõem a versão 3.5.1, incluindo a versão, a versão do chart do Helm (se aplicável) e de onde o artefato liberado pode ser obtido no formato binário. Siga a documentação associada para exemplos de uso e implantação.

|======
| Nome | Versão | Versão do Gráfico Helm | Local do artefato (URL/Imagem)
| SUSE Linux Micro | 6.2 (mais recente) | N/A | https://www.suse.com/download/sle-micro/[Página de download do SUSE Linux Micro] +
SL-Micro.x86_64-6.2-Base-SelfInstall-GM.install.iso (sha256 76390cec4537821d90975d924bf9d7575c9912da89fa460383eff0c623fd403e) +
SL-Micro.x86_64-6.2-Base-RT-SelfInstall-GM.install.iso (sha256 8f4d03c6953966174efb4c4b176cbe6dd5cab6e2a406033fc5c2bf6884da8b5d) +
SL-Micro.x86_64-6.2-Base-GM.raw.xz (sha256 bea3ac202b54ee29fabc28568f50c86d34939cf861679f21a91dfbae9c54c92e) +
SL-Micro.x86_64-6.2-Base-RT-GM.raw.xz (sha256 b9af7763c8d63143e31e5f80eb8d06fcc9477a576de8e358ab2e9835ab39d305) +
s| SUSE Multi-Linux Manager s| 5.1.2 s| N/A s| https://www.suse.com/download/suse-manager/[Página de download do SUSE Multi-Linux Manager]
s| K3s s| 1.34.4 s| N/A s| https://github.com/k3s-io/k3s/releases/tag/v1.34.4%2Bk3s1[Lançamento upstream do K3s]
s| RKE2 s| 1.34.4 s| N/A s| https://github.com/rancher/rke2/releases/tag/v1.34.4%2Brke2r1[Lançamento upstream do RKE2]
s| SUSE Rancher Prime s| 2.13.3 s| 2.13.3 s| https://charts.rancher.com/server-charts/prime/index.yaml[Repositório Helm do Rancher Prime] +
\https://prime.ribs.rancher.io/rancher/v2.13.3/rancher-images.txt[Rancher 2.13.3 Container Images]
s| SUSE Storage (Longhorn) s| 1.10.2 s| 1.10.2 s| https://apps.rancher.io/applications/suse-storage[Repositório Helm do SUSE Storage] +
\https://apps.rancher.io/applications/suse-storage/components[Imagens de Contêiner do SUSE Storage]
s| SUSE Security s| 5.4.9 s| 108.0.2+up2.8.11 s| https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.suse.com/rancher/neuvector-controller:5.4.9 +
registry.suse.com/rancher/neuvector-enforcer:5.4.9 +
registry.suse.com/rancher/neuvector-manager:5.4.9 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.9 +
registry.suse.com/rancher/neuvector-registry-adapter:0.2.2 +
registry.suse.com/rancher/neuvector-scanner:6 +
registry.suse.com/rancher/neuvector-updater:0.0.7
s| Provedores do Rancher Turtles (CAPI) s| 0.25.4 s| 305.0.5+up0.25.4 s| registry.suse.com/edge/charts/rancher-turtles-providers:305.0.5+up0.25.4 +
registry.rancher.com/rancher/cluster-api-metal3-controller:v1.10.4 +
registry.rancher.com/rancher/cluster-api-metal3-ipam-controller:v1.10.4 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.21.1 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.21.1
s| Metal^3^ s| 0.13.0 s| 305.0.23+up0.13.1 s| registry.suse.com/edge/charts/metal3:305.0.23_up0.13.1 +
registry.suse.com/edge/3.5/baremetal-operator:0.11.2.0 +
registry.suse.com/edge/3.5/ironic:32.0.0.1 +
registry.suse.com/edge/3.5/ironic-ipa-downloader:3.0.11 +
registry.suse.com/edge/mariadb:10.11
| MetalLB | 0.15.2 | 305.0.1+up0.15.2 | registry.suse.com/edge/charts/metallb:305.0.1_up0.15.2 +
registry.suse.com/edge/3.5/metallb-controller:v0.15.2 +
registry.suse.com/edge/3.5/metallb-speaker:v0.15.2 +
registry.suse.com/edge/3.5/frr:10.2.1 +
registry.suse.com/edge/3.5/frr-k8s:v0.0.20 +
registry.suse.com/edge/3.5/kube-rbac-proxy:0.19.1
s| Elemental s| 1.8.1 s| 1.8.1 s| registry.suse.com/rancher/elemental-operator-chart:1.8.1 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.8.1 +
registry.suse.com/rancher/elemental-operator:1.8.1
| Extensão do Painel Elemental | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/4.0.0/charts/elemental/3.0.1[Helm Chart da Extensão Elemental]
| Edge Image Builder | 1.3.3 | N/A | registry.suse.com/edge/3.5/edge-image-builder:1.3.3
| Configurador NM | 0.3.5 | N/A | https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.5[Lançamento do NMConfigurator upstream]
| KubeVirt | 1.5.2 | 305.0.1+up0.6.0 | registry.suse.com/edge/charts/kubevirt:305.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportproxy:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportserver:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.5.2
| Extensão do Painel KubeVirt | 1.3.3 | 305.0.4+up1.3.3 | registry.suse.com/edge/charts/kubevirt-dashboard-extension:305.0.4_up1.3.3
| Conteinerizado Importador de Dados | 1.62.0 | 305.0.1+up0.6.0 | registry.suse.com/edge/charts/cdi:305.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-importer:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-cloner:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.62.0
| Operador Endpoint Copier | 0.3.0 | 305.0.1+up0.3.0 | registry.suse.com/edge/charts/endpoint-copier-operator:305.0.1_up0.3.0 +
registry.suse.com/edge/3.5/endpoint-copier-operator:0.3.0
| Akri (Descontinuado) | 0.12.20 | 305.0.0+up0.12.20 | registry.suse.com/edge/charts/akri:305.0.0_up0.12.20 +
registry.suse.com/edge/charts/akri-dashboard-extension:305.0.0_up1.3.1 +
registry.suse.com/edge/3.5/akri-agent:v0.12.20 +
registry.suse.com/edge/3.5/akri-controller:v0.12.20 +
registry.suse.com/edge/3.5/akri-debug-echo-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.5/akri-onvif-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.5/akri-opcua-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.5/akri-udev-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.5/akri-webhook-configuration:v0.12.20
| Operador de Rede SR-IOV | 1.6.0 | 305.0.4+up1.6.0 | registry.suse.com/edge/charts/sriov-network-operator:305.0.4_up1.6.0 +
registry.suse.com/edge/charts/sriov-crd:305.0.4_up1.6.0
| Upgrade Controller | 0.17.0 | 108.0.0 | https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.suse.com/rancher/system-upgrade-controller:v0.17.0
| Upgrade Controller | 0.1.3 | 305.0.3+up0.1.3 | registry.suse.com/edge/charts/upgrade-controller:305.0.3_up0.1.3 +
registry.suse.com/edge/3.5/upgrade-controller:0.1.3 +
registry.suse.com/edge/3.5/kubectl:1.34.2 +
registry.suse.com/edge/3.5/release-manifest:3.5.1
| Kiwi Builder | 10.2.29.1 | N/A | registry.suse.com/edge/3.5/kiwi-builder:10.2.29.1
|======

[#release-notes-3-5-0]
= Lançamento 3.5.0

Data de disponibilidade: 21 de janeiro de 2026

Data de término do suporte completo: 21 de julho de 2026

Data de término do suporte de manutenção: 21 de julho de 2027

EOL: 22 de julho de 2027

Resumo: O SUSE Edge 3.5.0 é o primeiro lançamento no fluxo de lançamento do SUSE Edge 3.5.

== Novos recursos

* Atualizado para Kubernetes 1.34 e Rancher Prime 2.13
* Versões do Metal3/Ironic atualizadas
* Atualizado para SUSE Storage (Longhorn) 1.10.1 https://longhorn.io/docs/1.10.1/[Notas de lançamento upstream do Longhorn]
* Atualizado para SUSE Linux Micro 6.2 https://documentation.suse.com/releasenotes/sle-micro/html/releasenotes_sle-micro_6.2/index.html[Notas de Lançamento do SUSE Linux Micro 6.2]
* Atualizado Elemental para 1.8.0 https://elemental.docs.rancher.com/release-notes/[Notas de Lançamento do Elemental]
* Atualizado o operador de rede SR-IOV para 1.6.0 https://github.com/k8snetworkplumbingwg/sriov-network-operator/releases/tag/v1.6.0[Notas de lançamento upstream], e as imagens relacionadas agora são baseadas em https://www.suse.com/products/base-container-images/[imagens base BCI]
* Atualizado o MetalLB para 0.15.2 https://metallb.universe.tf/release-notes/#version-0-15-2[Notas de lançamento upstream]

== Correções de bug e segurança

* O Rancher Prime 2.13 contém várias correções de bug https://github.com/rancher/rancher/releases/tag/v2.13.1[Notas de lançamento upstream do Rancher]
* O SUSE Storage (Longhorn) 1.10.1 contém várias correções de bug https://github.com/longhorn/longhorn/releases/tag/v1.10.1[Correções de bug upstream do Longhorn]
* O SUSE Linux Micro 6.2 contém novos recursos, várias correções de bug e algumas alterações (por exemplo, a mudança para nomes de rede previsíveis). Verifique as https://documentation.suse.com/releasenotes/sle-micro/html/releasenotes_sle-micro_6.2/index.html[Notas de Lançamento do SUSE Linux Micro 6.2]
* O operador de rede SR-IOV 1.6.0 contém novos recursos, várias correções de bug e algumas alterações. Verifique as https://github.com/k8snetworkplumbingwg/sriov-network-operator/releases/tag/v1.6.0[Notas de lançamento upstream do SR-IOV]
* O MetalLB 0.15.2 contém novos recursos, várias correções de bug e algumas alterações. Verifique as https://metallb.universe.tf/release-notes/#version-0-15-2[Notas de Lançamento upstream do MetalLB]
* O Metal3 Ironic Python Agent (IPA) está alinhado com a mesma base de código do SUSE Linux Micro 6.2 (incluindo o Kernel), o que resolve problemas em alguns ambientes onde os nomes das interfaces de rede não correspondem entre os dados de inspeção e o SO implantado.

== Problemas conhecidos

* A versão do SUSE Multi-Linux Manager incluída com o SUSE Edge 3.5 (5.0.6) ainda não oferece suporte ao SUSE Linux Micro 6.2. Ela será atualizada e suportada em futuras versões do SUSE Edge 3.5.
* Executar o https://documentation.suse.com/suse-edge/{version-edge}/html/edge/atip-features.html#ptp-telco-config[recurso PTP] na configuração padrão requer etapas adicionais:
O seguinte precisa ser adicionado às substituições no serviço ptp4l para que ele funcione corretamente na versão Edge 3.5:
[,bash]
----
[Service]
PrivateDevices=
DevicePolicy=closed
DeviceAllow=/dev/rtc rwm
DeviceAllow=char-ptp rwm
DeviceAllow=/dev/ptp0 rwm
----

Isso pode ser alcançado editando `/etc/systemd/system/ptp4l.service.d/override.conf` ou executando `systemctl edit ptp4l.service`
A correção adequada para isso será incluída assim que o https://bugzilla.suse.com/show_bug.cgi?id=1256059[bug do pacote linuxptp] for corrigido.

[WARNING]
====
Ao implantar novos clusters, siga <<guides-kiwi-builder-images>> para criar imagens novas primeiro, pois esta é agora a primeira etapa necessária para criar clusters para as arquiteturas {x86-64} e {aarch64}, bem como clusters de gerenciamento e downstream.
====

* Ao implantar via Edge Image Builder, os manifestos `HelmChartConfigs` podem falhar se forem colocados no diretório de configuração `kubernetes/manifests`. Em vez disso, recomenda-se colocar qualquer `HelmChartConfigs` em `/var/lib/rancher/{rke2/k3s}/server/manifests/` usando a interface os-files do EIB, consulte <<mgmt-cluster-directory-structure>> como exemplo.  Falhar em fazer isso pode fazer com que os nós permaneçam no estado `NotReady` na inicialização inicial, conforme discutido em https://github.com/rancher/rke2/issues/8357[#8357 problema do RKE2].

* Nas versões RKE2/K3s 1.31, 1.32, 1.33 e 1.34, o diretório `/etc/cni` usado para armazenar configurações do CNI pode não disparar uma notificação dos arquivos gravados para `containerd` devido a certas condições relacionadas ao `overlayfs` (consulte o https://github.com/rancher/rke2/issues/8356[#8356 problema do RKE2]). Isso, por sua vez, faz com que a implantação do RKE2/K3s fique travada aguardando a inicialização do CNI, e os nós do RKE2/K3s permaneçam no estado `NotReady`. Isso pode ser visto no nível do nó com `kubectl describe node <affected_node>`:

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

Como solução alternativa, um volume tmpfs pode ser montado no diretório `/etc/cni` antes que o RKE2 seja iniciado. Isso evita o uso de overlayfs, o que faz com que o containerd perca notificações, e as configurações devem ser reescritas toda vez que o nó for reiniciado e os initcontainers dos pods forem executados novamente. Se estiver usando o EIB, este pode ser um script `04-tmpfs-cni.sh` no diretório `custom/scripts` (conforme explicado aqui[https://github.com/suse-edge/edge-image-builder/blob/release-1.2/docs/building-images.md#custom]) que se parece com:

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* Ao integrar hosts remotos usando o Elemental, uma condição de corrida entre `dbus.service` e `elemental-system-agent.service` pode ocorrer, resultando na falha de inicialização do `rancher-system-agent.service` no host remoto com erros semelhantes ao abaixo. (consulte o https://github.com/suse-edge/edge-image-builder/issues/784[#784 problema do Edge Image Builder] para obter detalhes.)

[,bash]
----
Sep 19 19:38:07 elementalvm elemental-system-agent[3671]: time="2025-09-19T19:38:07Z" level=info msg="[6b20fe64c854da2639804884b34129bb8f718eb59578111da58d9de1509c24db_1:stderr]: Failed to restart rancher-system-agent.service: Message recipient disconnected from message bus without replying"
----

Como solução alternativa, um arquivo de substituição do systemd pode ser criado conforme abaixo

[,bash]
----
[Unit]
Wants=dbus.service network-online.target
After=dbus.service network-online.target time-sync.target

[Service]
ExecStartPre=/bin/bash -c 'echo "Waiting for dbus to become active..." | systemd-cat -p info -t elemental-system-agent; sleep 15; timeout 300 bash -c "while ! systemctl is-active --quiet dbus.service; do sleep 15; done"'
----

e um script personalizado chamado `30a-copy-elemental-system-agent-override.sh` pode ser usado para colocar a substituição em `/etc/systemd/system/elemental-system-agent.service.d` antes que o script https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/templates/31-elemental-register.sh.tpl[31-elemental-register.sh] do EIB seja executado durante a fase de combustão.

[,bash]
----
#!/bin/bash

/bin/mkdir -p /etc/systemd/system/elemental-system-agent.service.d
/bin/cp -f elemental-system-agent-override.conf /etc/systemd/system/elemental-system-agent.service.d/override.conf
----

== Versões dos Componentes

A tabela a seguir descreve os componentes individuais que compõem a versão 3.5.0, incluindo a versão, a versão do Helm chart (se aplicável) e de onde o artefato disponibilizado pode ser obtido no formato binário. Siga a documentação associada para exemplos de uso e implantação.

|======
| Nome | Versão | Versão do Gráfico Helm | Local do artefato (URL/Imagem)
| SUSE Linux Micro | 6.2 (mais recente) | N/A | https://www.suse.com/download/sle-micro/[Página de download do SUSE Linux Micro] +
SL-Micro.x86_64-6.2-Base-SelfInstall-GM.install.iso (sha256 76390cec4537821d90975d924bf9d7575c9912da89fa460383eff0c623fd403e) +
SL-Micro.x86_64-6.2-Base-RT-SelfInstall-GM.install.iso (sha256 8f4d03c6953966174efb4c4b176cbe6dd5cab6e2a406033fc5c2bf6884da8b5d) +
SL-Micro.x86_64-6.2-Base-GM.raw.xz (sha256 bea3ac202b54ee29fabc28568f50c86d34939cf861679f21a91dfbae9c54c92e) +
SL-Micro.x86_64-6.2-Base-RT-GM.raw.xz (sha256 b9af7763c8d63143e31e5f80eb8d06fcc9477a576de8e358ab2e9835ab39d305) +
| SUSE Multi-Linux Manager | 5.0.6 | N/A | https://www.suse.com/download/suse-manager/[Página de download do SUSE Multi-Linux Manager]
| K3s | 1.34.2 | N/A | https://github.com/k3s-io/k3s/releases/tag/v1.34.2%2Bk3s1[Versão upstream do K3s]
| RKE2 | 1.34.2 | N/A | https://github.com/rancher/rke2/releases/tag/v1.34.2%2Brke2r1[Versão Upstream do RKE2]
| SUSE Rancher Prime | 2.13.1 | 2.13.1 | https://charts.rancher.com/server-charts/prime/index.yaml[Repositório Helm do Rancher Prime] +
\https://prime.ribs.rancher.io/rancher/v2.13.1/rancher-images.txt[Rancher 2.13.1 Container Images]
| SUSE Storage (Longhorn) | 1.10.1 | 1.10.1 | https://apps.rancher.io/applications/suse-storage[Repositório Helm do SUSE Storage] +
\https://apps.rancher.io/applications/suse-storage/components[Imagens de Contêiner do SUSE Storage]
| SUSE Security | 5.4.8 | 108.0.1+up2.8.10 | https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.suse.com/rancher/neuvector-controller:5.4.8 +
registry.suse.com/rancher/neuvector-enforcer:5.4.8 +
registry.suse.com/rancher/neuvector-manager:5.4.8 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.9 +
registry.suse.com/rancher/neuvector-registry-adapter:0.2.2 +
registry.suse.com/rancher/neuvector-scanner:6 +
registry.suse.com/rancher/neuvector-updater:0.0.7
| Provedores do Rancher Turtles (CAPI) | 0.25.1 | 305.0.4+up0.25.1 | registry.suse.com/edge/charts/rancher-turtles-providers:305.0.4+up0.25.1 +
registry.rancher.com/rancher/cluster-api-metal3-controller:v1.10.4 +
registry.rancher.com/rancher/cluster-api-metal3-ipam-controller:v1.10.4 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.21.1 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.21.1
| Metal^3^ | 0.13.0 | 305.0.21+up0.13.0 | registry.suse.com/edge/charts/metal3:305.0.21_up0.13.0 +
registry.suse.com/edge/3.5/baremetal-operator:0.11.2.0 +
registry.suse.com/edge/3.5/ironic:32.0.0.1 +
registry.suse.com/edge/3.5/ironic-ipa-downloader:3.0.10 +
registry.suse.com/edge/mariadb:10.11
| MetalLB | 0.15.2 | 305.0.1+up0.15.2 | registry.suse.com/edge/charts/metallb:305.0.1_up0.15.2 +
registry.suse.com/edge/3.5/metallb-controller:v0.15.2 +
registry.suse.com/edge/3.5/metallb-speaker:v0.15.2 +
registry.suse.com/edge/3.5/frr:10.2.1 +
registry.suse.com/edge/3.5/frr-k8s:v0.0.20 +
registry.suse.com/edge/3.5/kube-rbac-proxy:0.19.1
| Elemental | 1.8.0 | 1.8.0 | registry.suse.com/rancher/elemental-operator-chart:1.8.0 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.8.0 +
registry.suse.com/rancher/elemental-operator:1.8.0
| Extensão do Painel Elemental | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/4.0.0/charts/elemental/3.0.1[Helm Chart da Extensão Elemental]
| Edge Image Builder | 1.3.2 | N/A | registry.suse.com/edge/3.5/edge-image-builder:1.3.2
| Configurador NM | 0.3.5 | N/A | https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.5[Lançamento do NMConfigurator upstream]
| KubeVirt | 1.5.2 | 305.0.1+up0.6.0 | registry.suse.com/edge/charts/kubevirt:305.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportproxy:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportserver:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.5.2
| Extensão do Painel KubeVirt | 1.3.3 | 305.0.4+up1.3.3 | registry.suse.com/edge/charts/kubevirt-dashboard-extension:305.0.4_up1.3.3
| Importador de Dados Conteinerizado | 1.62.0 | 305.0.1+up0.6.0 | registry.suse.com/edge/charts/cdi:305.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-importer:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-cloner:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.62.0
| Operador Endpoint Copier | 0.3.0 | 305.0.1+up0.3.0 | registry.suse.com/edge/charts/endpoint-copier-operator:305.0.1_up0.3.0 +
registry.suse.com/edge/3.5/endpoint-copier-operator:0.3.0
| Akri (Descontinuado) | 0.12.20 | 305.0.0+up0.12.20 | registry.suse.com/edge/charts/akri:305.0.0_up0.12.20 +
registry.suse.com/edge/charts/akri-dashboard-extension:305.0.0_up1.3.1 +
registry.suse.com/edge/3.5/akri-agent:v0.12.20 +
registry.suse.com/edge/3.5/akri-controller:v0.12.20 +
registry.suse.com/edge/3.5/akri-debug-echo-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.5/akri-onvif-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.5/akri-opcua-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.5/akri-udev-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.5/akri-webhook-configuration:v0.12.20
| Operador de Rede SR-IOV | 1.6.0 | 305.0.4+up1.6.0 | registry.suse.com/edge/charts/sriov-network-operator:305.0.4_up1.6.0 +
registry.suse.com/edge/charts/sriov-crd:305.0.4_up1.6.0
| Upgrade Controller | 0.17.0 | 108.0.0 | https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.suse.com/rancher/system-upgrade-controller:v0.17.0
| Upgrade Controller | 0.1.3 | 305.0.2+up0.1.3 | registry.suse.com/edge/charts/upgrade-controller:305.0.3_up0.1.3 +
registry.suse.com/edge/3.5/upgrade-controller:0.1.3 +
registry.suse.com/edge/3.5/kubectl:1.34.2 +
registry.suse.com/edge/3.5/release-manifest:3.5.0
| Kiwi Builder | 10.2.29.1 | N/A | registry.suse.com/edge/3.5/kiwi-builder:10.2.29.1
|======

= Recursos descontinuados

Salvo indicação em contrário, estes se aplicam à versão 3.4.0 e a todas as versões z-stream subsequentes.

* O Akri era uma oferta de Technology Preview em versões anteriores do Edge e agora está descontinuado.  A remoção está planejada para uma versão futura.

[#tech-previews]
= Prévias de tecnologia

Salvo indicação em contrário, estes se aplicam à versão 3.4.0 e a todas as versões z-stream subsequentes.

* Implantações IPv6 de pilha única são uma oferta de Technology Preview e não estão sujeitas ao escopo padrão de suporte.
* O Precision Time Protocol (PTP) em implantações downstream é uma oferta de Technology Preview e não está sujeito ao escopo padrão de suporte.
* O modo BGP para MetalLB é uma oferta de Technology Preview e não está sujeito ao escopo padrão de suporte.

= Verificação de componentes

Os componentes mencionados acima podem ser verificados usando os dados da Lista de Materiais de Software (SBOM) - por exemplo, usando `cosign` conforme descrito abaixo:

Baixe a chave pública do contêiner SUSE Edge da https://www.suse.com/support/security/keys/[fonte de chaves de assinatura da SUSE]:

[,bash]
----
include::key.sh[]
----

Verifique o hash da imagem do contêiner, por exemplo, usando `crane`:

[,bash]
----
> crane digest registry.suse.com/edge/3.4/baremetal-operator:0.10.2.1 --platform linux/amd64
sha256:310d939f8ae4b547710195b9671a4e9ff417420c0856103dd728b051788b5374
----

NOTE: Para imagens multi-arquitetura, também é necessário especificar uma plataforma ao obter o digest, por exemplo, `--platform linux/amd64` ou `--platform linux/arm64`. A falha em fazer isso resultará em um erro na etapa a seguir (`Error: no matching attestations`).

Verifique com `cosign`:

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/3.4/baremetal-operator@sha256:310d939f8ae4b547710195b9671a4e9ff417420c0856103dd728b051788b5374 > /dev/null
#
Verification for registry.suse.com/edge/3.4/baremetal-operator@sha256:310d939f8ae4b547710195b9671a4e9ff417420c0856103dd728b051788b5374 --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - The signatures were verified against the specified public key
----

Extraia os dados da SBOM conforme descrito na https://www.suse.com/support/security/sbom/[documentação da SBOM da SUSE]:

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/3.4/baremetal-operator@sha256:310d939f8ae4b547710195b9671a4e9ff417420c0856103dd728b051788b5374 | jq '.payload | @base64d | fromjson | .predicate'
----

= Etapas de Atualização

Consulte o <<day-2-operations>> para obter detalhes sobre como fazer upgrade para uma nova versão.

= Ciclo de vida de suporte de produtos

O SUSE Edge conta com o suporte premiado da SUSE, uma líder tecnológica estabelecida com um histórico comprovado de entrega de serviços de suporte com qualidade empresarial. Para mais informações, consulte https://www.suse.com/lifecycle[https://www.suse.com/lifecycle] e a página da Política de Suporte em https://www.suse.com/support/policy.html[https://www.suse.com/support/policy.html]. Se você tiver alguma dúvida sobre como abrir um caso de suporte, como a SUSE classifica os níveis de severidade ou o escopo do suporte, consulte o Manual de Suporte Técnico em https://www.suse.com/support/handbook/[https://www.suse.com/support/handbook/].

O SUSE Edge "3.5" é suportado por 18 meses de suporte à produção, com 6 meses iniciais de "suporte completo", seguidos por 12 meses de "suporte de manutenção".  Após essas fases de suporte, o produto atinge o "fim do serviço" (EOL) e não é mais suportado. Mais informações sobre as fases do ciclo de vida podem ser encontradas na tabela abaixo:

|======
| *Suporte Completo (6 meses)* | Correções de bugs urgentes e de alta prioridade selecionadas serão lançadas durante a janela de suporte completo, e todos os outros patches (não urgentes, melhorias, novos recursos) serão lançados por meio do cronograma de lançamento regular.
| *Suporte de Manutenção (12 meses)* | Durante este período, apenas correções críticas serão lançadas por meio de patches. Outras correções de bugs podem ser lançadas a critério da SUSE, mas não devem ser esperadas.
| *Fim do Serviço (EOL)*  | Assim que uma versão de produto atinge sua data de Fim do Serviço (EOL), o cliente pode continuar a usar o produto dentro dos termos do contrato de licenciamento do produto.
Os Planos de Suporte da SUSE não se aplicam a versões de produtos após sua data de EOL.
|======

A menos que explicitamente declarado, todos os componentes listados são considerados Geralmente Disponíveis (GA) e são cobertos pelo escopo padrão de suporte da SUSE. Alguns componentes podem ser listados como "Technology Preview", onde a SUSE fornece aos clientes acesso a recursos e funcionalidades pré-GA iniciais para avaliação, mas não estão sujeitos às políticas de suporte padrão e não são recomendados para casos de uso em produção. A SUSE aceita muito bem comentários e sugestões sobre as melhorias que podem ser feitas nos componentes de Technology Preview, mas a SUSE reserva-se o direito de descontinuar um recurso de Technology Preview antes que ele se torne Geralmente Disponível se ele não atender às necessidades de nossos clientes ou não atingir um estado de maturidade que exigimos.

Observe que a SUSE deve ocasionalmente descontinuar recursos ou alterar especificações de API. Os motivos para a descontinuação de recursos ou alteração de API podem incluir um recurso sendo atualizado ou substituído por uma nova implementação, um novo conjunto de recursos, a tecnologia upstream não estar mais disponível ou a comunidade upstream ter introduzido alterações incompatíveis. Não se pretende que isso aconteça dentro de uma determinada versão secundária (x.z), portanto, todas as versões z-stream manterão a compatibilidade de API e a funcionalidade de recursos. A SUSE se esforçará para fornecer avisos de descontinuação com bastante antecedência nas notas de versão, juntamente com soluções alternativas, sugestões e mitigações para minimizar a interrupção do serviço.

A equipe do SUSE Edge também aceita comentários da comunidade, onde problemas podem ser levantados no respectivo repositório de código dentro de https://www.github.com/suse-edge[https://www.github.com/suse-edge].

= Obtenção de código-fonte

Este produto SUSE inclui materiais licenciados para a SUSE sob a GNU General Public License (GPL) e várias outras licenças de código aberto. A GPL exige que a SUSE forneça o código-fonte que corresponde ao material licenciado pela GPL e que a SUSE esteja em conformidade com todos os outros requisitos de licença de código aberto. Como tal, a SUSE disponibiliza todo o código-fonte, que geralmente pode ser encontrado no repositório GitHub do SUSE Edge (https://www.github.com/suse-edge[https://www.github.com/suse-edge]), no repositório GitHub do SUSE Rancher (https://www.github.com/rancher[https://www.github.com/rancher]) para componentes dependentes e, especificamente, para o SUSE Linux Micro, o código-fonte está disponível para download em https://www.suse.com/download/sle-micro/[https://www.suse.com/download/sle-micro] em "Medium 2".

= Informações legais

A SUSE não faz representações ou garantias quanto ao conteúdo ou à utilização desta documentação e, especificamente, isenta-se de quaisquer garantias explícitas ou implícitas de comerciabilidade ou adequação a qualquer propósito específico. Além disso, a SUSE reserva-se o direito de revisar esta publicação e de fazer mudanças em seu conteúdo a qualquer momento, sem a obrigação de notificar qualquer pessoa ou entidade sobre essas revisões ou mudanças.

Além disso, a SUSE não faz representações ou garantias quanto a qualquer software e, especificamente, isenta-se de quaisquer garantias explícitas ou implícitas de comerciabilidade ou adequação a qualquer propósito específico. Além disso, a SUSE reserva-se o direito de fazer mudanças em qualquer parte do software SUSE, a qualquer momento, sem a obrigação de notificar qualquer pessoa ou entidade sobre essas mudanças.

Todos os produtos ou as informaçőes técnicas fornecidas neste Contrato podem estar sujeitas aos controles de exportação dos Estados Unidos e ŕs leis de comércio de outros países. Você concorda em obedecer a todos os regulamentos de controle de exportação e em obter quaisquer licenças ou classificações necessárias para exportar, reexportar ou importar produtos. Você concorda em não exportar ou reexportar para entidades nas listas de exclusão de exportação atuais dos Estados Unidos ou para países sob embargo ou considerados terroristas, conforme especificado nas leis de exportação dos Estados Unidos. Você concorda em não usar entregáveis para fins proibidos relacionados a armas nucleares, mísseis ou armamentos químicos/biológicos. Consulte https://www.suse.com/company/legal/[https://www.suse.com/company/legal/] para obter mais informações sobre a exportação do software SUSE. A SUSE não assume qualquer responsabilidade caso você não obtenha as aprovações necessárias para exportação.

*Copyright © 2024 SUSE LLC.*

Este documento de notas de versão está licenciado sob uma Licença Creative Commons Atribuição-SemDerivações 4.0 Internacional (CC-BY-ND-4.0). Você deve ter recebido uma cópia da licença juntamente com este documento. Caso não tenha recebido, consulte https://creativecommons.org/licenses/by-nd/4.0/[https://creativecommons.org/licenses/by-nd/4.0/].

A SUSE possui direitos de propriedade intelectual relacionados à tecnologia incorporada ao produto descrito neste documento. Em particular, e sem limitações, esses direitos de propriedade intelectual podem incluir uma ou mais patentes dos EUA listadas em https://www.suse.com/company/legal/[https://www.suse.com/company/legal/] e uma ou mais patentes adicionais ou pedidos de patentes pendentes nos EUA e em outros países.

Para marcas registradas da SUSE, consulte a lista de Marcas Registradas e Marcas de Serviço da SUSE (https://www.suse.com/company/legal/[https://www.suse.com/company/legal/]). Todas as marcas registradas de terceiros pertencem aos seus respectivos proprietários. Para obter informações sobre a marca SUSE e requisitos de uso, consulte as diretrizes publicadas em https://brand.suse.com/[https://brand.suse.com/].
