[#release-notes-abstract]
= Abstrato
:revdate: 2026-06-29
:revnumber: 3.6
:page-revdate: {revdate}
ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

{product} 3.6 é uma solução de ponta a ponta fortemente integrada e abrangentemente validada para abordar os desafios únicos da implantação de infraestrutura e aplicativos nativos de nuvem na borda. Seu foco principal é fornecer uma plataforma opinativa, porém altamente flexível, altamente escalável e segura que abrange a construção de imagem de implantação inicial, provisionamento e integração de nós, implantação de aplicativos, observabilidade e gerenciamento de ciclo de vida.

A solução foi projetada com a noção de que não existe uma plataforma de borda de "tamanho único" devido aos requisitos e expectativas amplamente variados de nossos clientes. As implantações de borda nos levam a resolver, e evoluir continuamente, alguns dos problemas mais desafiadores, incluindo escalabilidade massiva, disponibilidade de rede restrita, restrições de espaço físico, novas ameaças de segurança e vetores de ataque, variações na arquitetura de hardware e recursos do sistema, o requisito de implantar e interagir com infraestrutura e aplicativos legados, e soluções de clientes que possuem vida útil estendida.

O {product} é construído sobre o melhor software de código aberto desde o início, consistente com nossa história de 30 anos na entrega de plataformas SUSE Linux seguras, estáveis e certificadas e nossa experiência no fornecimento de gerenciamento de Kubernetes altamente escalável e rico em recursos com nosso portfólio Rancher. O {product} baseia-se nessas capacidades para fornecer funcionalidade que pode atender a um grande número de segmentos de mercado, incluindo varejo, médico, transporte, logística, telecomunicações, manufatura inteligente e IoT Industrial.

Para obter mais informações sobre atualizações do ciclo de vida de suporte do produto para {product}, consulte link:https://www.suse.com/lifecycle/#suse-edge-36[Product Support Lifecycle].

NOTE: O SUSE Telco Cloud é um derivado do SUSE Edge, com otimizações e componentes adicionais que permitem que a plataforma atenda aos requisitos encontrados em casos de uso de telecomunicações.

= Sobre

Estas Notas de Lançamento são, a menos que explicitamente especificado e explicado, idênticas em todas as arquiteturas, e a versão mais recente, juntamente com as notas de lançamento de todos os outros produtos SUSE, estão sempre disponíveis online em https://www.suse.com/releasenotes[https://www.suse.com/releasenotes].

As entradas são listadas apenas uma vez, mas podem ser referenciadas em vários lugares se forem importantes e pertencerem a mais de uma seção. As notas de lançamento geralmente listam apenas as alterações que ocorreram entre dois lançamentos subsequentes. Algumas entradas importantes das notas de lançamento de versões anteriores do produto podem ser repetidas. Para tornar essas entradas mais fáceis de identificar, elas contêm uma nota para esse efeito.

No entanto, as entradas repetidas são fornecidas apenas como uma cortesia. Portanto, se você estiver pulando um ou mais lançamentos, verifique também as notas de lançamento dos lançamentos ignorados. Se você estiver lendo apenas as notas de lançamento da versão atual, poderá perder alterações importantes que podem afetar o comportamento do sistema. As versões {product} são definidas como x.y.z, onde 'x' denota a versão principal, 'y' denota a versão secundária e 'z' denota a versão de patch, também conhecida como "z-stream". Os ciclos de vida do produto {product} são definidos com base em um determinado lançamento secundário, por exemplo. "3.6", mas são fornecidos com atualizações de patch subsequentes ao longo de seu ciclo de vida, por exemplo. "3.6.1".

NOTE: Os lançamentos z-stream do {product} são fortemente integrados e completamente testados como uma pilha versionada. Fazer upgrade de quaisquer componentes individuais para versões diferentes daquelas listadas acima provavelmente resultará em tempo de inatividade do sistema. Embora seja possível executar clusters Edge em configurações não testadas, isso não é recomendado e pode levar mais tempo para fornecer uma resolução por meio dos canais de suporte.

[#release-notes-3-6-1]
= Release 3.6.1

Data de disponibilidade: 26 de junho de 2026

Data de término do suporte completo: 27 de novembro de 2026

Data de término do suporte de manutenção: 27 de maio de 2028

EOL: 28 de maio de 2028

Resumo: {product} 3.6.1 é a primeira versão z-stream no fluxo de versão {product} 3.6.

== Novos recursos

* Atualizado para Kubernetes 1.35.4 e Rancher Prime 2.14.2
* Atualizado para SUSE Security (NeuVector) 5.5.2 https://open-docs.neuvector.com/releasenotes/5x[Notas de versão do NeuVector]
* Atualizado para SUSE Storage (Longhorn) 1.11.2 https://longhorn.io/docs/1.11.1/[Notas de versão do Longhorn upstream]
* Atualizado para Rancher Turtles (CAPI) 0.26.2 https://turtles.docs.rancher.com/[Documentação do Rancher Turtles]
* Atualizado Metal^3^/Ironic para 0.15.0 com Ironic 35.0.0.2

== Correções de bug e atualizações de segurança

* O Kubernetes 1.35.4 contém várias correções de bugs e atualizações de segurança https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.35.md[Registro de alterações do Kubernetes]
* O Rancher Prime 2.14.2 contém várias correções de bugs https://github.com/rancher/rancher/releases/tag/v2.14.1[Notas de versão do Rancher upstream]
* O SUSE Storage (Longhorn) 1.11.2 contém várias correções de bugs https://github.com/longhorn/longhorn/releases/tag/v1.11.1[Correções de bugs do Longhorn upstream]
* O NeuVector 5.5.2 contém novos recursos e várias correções de bugs https://open-docs.neuvector.com/releasenotes/5x[Notas de versão do NeuVector]
* As atualizações do Metal^3^/Ironic corrigem vários bugs e problemas de segurança, incluindo os seguintes:
** https://www.cve.org/CVERecord?id=CVE-2026-44919[CVE-2026-44919]
** https://www.cve.org/CVERecord?id=CVE-2026-46447[CVE-2026-46447]
** https://www.cve.org/CVERecord?id=CVE-2026-48681[CVE-2026-48681]
** https://www.cve.org/CVERecord?id=CVE-2026-44917[CVE-2026-44917]
** https://www.cve.org/CVERecord?id=CVE-2026-43003[CVE-2026-43003]
** https://www.cve.org/CVERecord?id=CVE-2026-50589[CVE-2026-50589]

== Problemas conhecidos

[WARNING]
====
Se estiver implantando novos clusters, siga <<guides-kiwi-builder-images>> para criar imagens novas primeiro.  Isso é sugerido para clusters de gerenciamento e downstream para garantir que as imagens contenham as correções de segurança e bugs mais recentes.
====

* Ao implantar via Edge Image Builder, os manifestos `HelmChartConfigs` podem falhar se forem colocados no diretório de configuração `kubernetes/manifests`. Em vez disso, recomenda-se colocar qualquer `HelmChartConfigs` em `/var/lib/rancher/{rke2/k3s}/server/manifests/` usando a interface os-files do EIB.
ifeval::["{flavor}" == "telco"]
Consulte <<mgmt-cluster-directory-structure>> para obter um exemplo.
endif::[]
A falha em fazer isso pode fazer com que os nós permaneçam no estado `NotReady` na inicialização inicial, conforme discutido em https://github.com/rancher/rke2/issues/8357[#8357 problema do RKE2].

* Nas versões RKE2/K3s 1.34 e 1.35, o diretório `/etc/cni` usado para armazenar configurações de CNI pode não disparar uma notificação dos arquivos sendo gravados lá para `containerd` devido a certas condições relacionadas ao `overlayfs` (consulte o https://github.com/rancher/rke2/issues/8356[#8356 problema do RKE2]). Isso, por sua vez, faz com que a implantação do RKE2/K3s fique travada aguardando a inicialização do CNI, e os nós do RKE2/K3s permaneçam no estado `NotReady`. Isso pode ser visto no nível do nó com `kubectl describe node <affected_node>`:

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

Como solução alternativa, um volume tmpfs pode ser montado no diretório `/etc/cni` antes que o RKE2 seja iniciado. Isso evita o uso de overlayfs, o que faz com que o containerd perca notificações, e as configurações devem ser reescritas toda vez que o nó for reiniciado e os initcontainers dos pods forem executados novamente. Se estiver usando o EIB, isso pode ser um script `04-tmpfs-cni.sh` no diretório `custom/scripts` (conforme explicado https://github.com/suse-edge/edge-image-builder/blob/release-1.3/docs/building-images.md#custom[aqui]) que se parece com:

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* Não há documentação ou exemplos oficiais para configurar o SyncE via synce4l e GNSS via gpsd disponíveis neste estágio. Esses tópicos serão abordados em versões futuras.

* Alguns repositórios de contêineres estão acessíveis atualmente apenas via IPv4; por esse motivo, um repositório local no Cluster de Gerenciamento é necessário para um cluster downstream apenas com IPv6.

== Versões dos componentes

A tabela a seguir descreve os componentes individuais que compõem a versão 3.6.1, incluindo a versão, a versão do gráfico Helm (se aplicável) e de onde o artefato lançado pode ser extraído no formato binário. Siga a documentação associada para exemplos de uso e implantação.

|======
| Nome | Versão | Versão do gráfico Helm | Local do artefato (URL/Imagem)
| SUSE Linux Micro | 6.2 (mais recente) | N/A | https://www.suse.com/download/sle-micro/[Página de download do SUSE Linux Micro] +
| SUSE Linux Micro | 6.2 (mais recente) | N/A |Checksums e assinaturas estão disponíveis para download na https://www.suse.com/download/sle-micro/[Página de download do SUSE Linux Micro] +
SL-Micro.x86_64-6.2-Base-SelfInstall-GM.install.iso +
SL-Micro.x86_64-6.2-Base-RT-SelfInstall-GM.install.iso +
SL-Micro.x86_64-6.2-Base-GM.raw.xz +
SL-Micro.x86_64-6.2-Base-RT-GM.raw.xz +
| SUSE Multi-Linux Manager | 5.1 | N/A | https://www.suse.com/download/suse-manager/[Página de download do SUSE Multi-Linux Manager]
s| K3s s| 1.35.4 s| N/A s| https://github.com/k3s-io/k3s/releases/tag/v1.35.4%2Bk3s1[Versão upstream do K3s]
s| RKE2 s| 1.35.4 s| N/A s| https://github.com/rancher/rke2/releases/tag/v1.35.4%2Brke2r1[Versão upstream do RKE2]
s| SUSE Rancher Prime s| 2.14.2 s| 2.14.2 s| https://charts.rancher.com/server-charts/prime/index.yaml[Repositório Helm do Rancher Prime] +
\https://prime.ribs.rancher.io/rancher/v2.14.2/rancher-images.txt[Rancher 2.14.2 Container Images]
s| SUSE Storage (Longhorn) s| 1.11.2 s| 1.11.2 s| https://apps.rancher.io/applications/suse-storage[Repositório Helm do SUSE Storage] +
\https://apps.rancher.io/applications/suse-storage/components[Imagens de contêiner do SUSE Storage]
s| SUSE Security (NeuVector) s| 5.5.2 s| 109.0.2+up2.10.2 s| https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.rancher.com/rancher/neuvector-controller:5.5.2 +
registry.rancher.com/rancher/neuvector-enforcer:5.5.2 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.12
s| Provedores do Rancher Turtles (CAPI) s| 0.26.2 s| 306.0.7+up0.26.2 s| registry.suse.com/edge/3.6/rancher-turtles-providers-chart:306.0.7+up0.26.2 +
registry.rancher.com/rancher/cluster-api-controller:v1.12.2 +
registry.rancher.com/rancher/turtles:v0.26.2 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.24.3 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.24.3
s| Metal^3^ s| 0.15.0 s| 306.0.29+up0.15.0 s| registry.suse.com/edge/3.6/metal3-chart:306.0.29+up0.15.0 +
registry.suse.com/edge/3.6/baremetal-operator:0.12.3.0 +
registry.suse.com/edge/3.6/ironic:35.0.0.2 +
registry.suse.com/edge/3.6/ironic-ipa-downloader:3.1.1 +
registry.suse.com/edge/3.6/ironic-python-agent:3.0.9
| MetalLB | 0.15.3 | 306.0.2+up0.15.3 | registry.suse.com/edge/3.6/metallb-chart:306.0.2+up0.15.3 +
registry.suse.com/edge/3.6/metallb-controller:v0.15.3 +
registry.suse.com/edge/3.6/metallb-speaker:v0.15.3
| Elemental | 1.9.0 | 1.9.0 | registry.suse.com/rancher/elemental-operator-chart:1.9.0 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.9.0 +
registry.suse.com/rancher/elemental-operator:1.9.0
| Extensão do Painel Elemental | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/main/charts/elemental/3.0.1[Helm Chart da Extensão Elemental]
| Edge Image Builder | 1.3.3.1 | N/A | registry.suse.com/edge/3.6/edge-image-builder:1.3.3.1
| KubeVirt | 1.7.0 | 306.0.2+up0.7.0 | registry.suse.com/edge/3.6/kubevirt-chart:306.0.2+up0.7.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.7.0-150700.3.16.2
| Extensão do Painel KubeVirt | 1.3.3 | 306.0.4+up1.3.3 | registry.suse.com/edge/3.6/kubevirt-dashboard-extension-chart:306.0.4+up1.3.3
| Containerized Data Importer (CDI) | 1.64.0 | 306.0.2+up0.7.0 | registry.suse.com/edge/3.6/cdi-chart:306.0.2+up0.7.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.64.0-150700.9.6.1
| Operador Endpoint Copier | 0.3.0 | 306.0.1+up0.3.0 | registry.suse.com/edge/3.6/endpoint-copier-operator-chart:306.0.1+up0.3.0 +
registry.suse.com/edge/3.6/endpoint-copier-operator:0.3.0
| Operador de Rede SR-IOV | 1.6.0 | 306.0.4+up1.6.0 | registry.suse.com/edge/3.6/sriov-network-operator-chart:306.0.4+up1.6.0 +
registry.suse.com/edge/3.6/sriov-crd-chart:306.0.4+up1.6.0
| Controlador de Atualização do Sistema | 0.19.1 | 109.0.1 | https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.rancher.com/rancher/system-upgrade-controller:v0.19.1
s| Upgrade Controller s| 0.1.3 s| 306.0.4+up0.1.3 s| registry.suse.com/edge/3.6/upgrade-controller-chart:306.0.4+up0.1.3 +
registry.suse.com/edge/3.6/upgrade-controller:0.1.3 +
registry.rancher.com/rancher/kubectl:v1.35.2 +
registry.suse.com/edge/3.6/release-manifest:3.6.1
| SUSE Private Registry | 1.1.1 | 1.1.1 | oci://registry.suse.com/private-registry/private-registry-helm[Repositório Helm do SUSE Private Registry] +
registry.suse.com/private-registry/harbor-core:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-jobservice:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-portal:1.1.1-1.20 +
registry.suse.com/private-registry/harbor-registry:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-registryctl:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-trivy-adapter:1.1.1-1.24
| Kiwi Builder | 10.2.29.1 | N/A | registry.suse.com/edge/3.6/kiwi-builder:10.2.29.1
| Cert-Manager | 1.20.1 | 1.20.1 | https://charts.jetstack.io[Repositório Helm Jetstack] +
quay.io/jetstack/cert-manager-controller:v1.20.1 +
quay.io/jetstack/cert-manager-webhook:v1.20.1 +
quay.io/jetstack/cert-manager-cainjector:v1.20.1
|======

[#release-notes-3-6-0]
= Release 3.6.0

Data de disponibilidade: 27 de maio de 2026

Data de término do suporte completo: 27 de novembro de 2026

Data de término do suporte de manutenção: 27 de maio de 2028

EOL: 28 de maio de 2028

Resumo: {product} 3.6.0 é a primeira versão no fluxo de lançamentos 3.6.

== Novos recursos

* Atualizado para Kubernetes 1.35.3 e Rancher Prime 2.14.1
* Atualizado para SUSE Security (NeuVector) 5.5.1 https://open-docs.neuvector.com/releasenotes/5x[Notas de Lançamento do NeuVector]
* Atualizado para SUSE Storage (Longhorn) 1.11.1 https://longhorn.io/docs/1.11.1/[Notas de Lançamento do Longhorn Upstream]
* Atualizado para Rancher Turtles (CAPI) 0.26.1 https://turtles.docs.rancher.com/[Documentação do Rancher Turtles]
* Atualizado para MetalLB 0.15.3 https://metallb.universe.tf/release-notes/#version-0-15-3[Notas de Lançamento Upstream]
* Atualizado para KubeVirt 1.7.0 e CDI (Containerized Data Importer) 1.64.0
* Atualizado para Elemental 1.9.0 https://elemental.docs.rancher.com/release-notes/[Notas de Lançamento do Elemental]
* Atualizado para Cert-Manager 1.20.1 https://cert-manager.io/docs/release-notes/[Notas de Lançamento Upstream]
* Atualizado Metal3/Ironic para 0.15.0 com Ironic 35.0.0
* O modo BGP para MetalLB era uma Prévia Tecnológica no {product} 3.5 e agora é totalmente suportado
* O Precision Time Protocol (PTP) em implantações downstream era uma Prévia Tecnológica no {product} 3.5 e agora é totalmente suportado, juntamente com o suporte a SyncE e GNSS
* Implantações de cluster downstream IPv6 de pilha única agora são suportadas, no entanto, observe que isso requer um cluster de gerenciamento de pilha dupla (clusters de gerenciamento de pilha única permanecem como uma Prévia Tecnológica)

== Correções de bug e segurança

* O Kubernetes 1.35.3 contém várias correções de bug e atualizações de segurança https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.35.md[Registro de alterações do Kubernetes]
* O Rancher Prime 2.14.1 contém várias correções de bug https://github.com/rancher/rancher/releases/tag/v2.14.1[Notas de Lançamento do Rancher Upstream]
* O SUSE Storage (Longhorn) 1.11.1 contém várias correções de bug https://github.com/longhorn/longhorn/releases/tag/v1.11.1[Correções de bug do Longhorn Upstream]
* O NeuVector 5.5.1 contém novos recursos e várias correções de bug https://open-docs.neuvector.com/releasenotes/5x[Notas de Lançamento do NeuVector]

== Problemas conhecidos

[WARNING]
====
Se estiver implantando novos clusters, siga <<guides-kiwi-builder-images>> para criar novas imagens primeiro.  Isso é sugerido para clusters de gerenciamento e downstream para garantir que as imagens contenham as correções de segurança e de bug mais recentes.
====

* Ao implantar via Edge Image Builder, os manifestos `HelmChartConfigs` podem falhar se forem colocados no diretório de configuração `kubernetes/manifests`. Em vez disso, recomenda-se colocar qualquer `HelmChartConfigs` em `/var/lib/rancher/{rke2/k3s}/server/manifests/` usando a interface os-files do EIB.
ifeval::["{flavor}" == "telco"]
Consulte <<mgmt-cluster-directory-structure>> para obter um exemplo.
endif::[]
Falhar em fazer isso pode fazer com que os nós permaneçam no estado `NotReady` na inicialização inicial, conforme discutido em https://github.com/rancher/rke2/issues/8357[#8357 problema do RKE2].

* Nas versões RKE2/K3s 1.34 e 1.35, o diretório `/etc/cni` usado para armazenar configurações de CNI pode não disparar uma notificação dos arquivos gravados para `containerd` devido a certas condições relacionadas ao `overlayfs` (consulte o https://github.com/rancher/rke2/issues/8356[#8356 problema do RKE2]). Isso, por sua vez, faz com que a implantação do RKE2/K3s fique travada aguardando a inicialização do CNI, e os nós do RKE2/K3s permaneçam no estado `NotReady`. Isso pode ser visto no nível do nó com `kubectl describe node <affected_node>`:

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

Como solução alternativa, um volume tmpfs pode ser montado no diretório `/etc/cni` antes que o RKE2 seja iniciado. Isso evita o uso de overlayfs, o que faz com que o containerd perca notificações, e as configurações devem ser reescritas toda vez que o nó for reiniciado e os initcontainers dos pods forem executados novamente. Se estiver usando o EIB, isso pode ser um script `04-tmpfs-cni.sh` no diretório `custom/scripts` (conforme explicado https://github.com/suse-edge/edge-image-builder/blob/release-1.3/docs/building-images.md#custom[aqui]) que se parece com:

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* Não há documentação ou exemplos oficiais para configurar o SyncE via synce4l e GNSS via gpsd disponíveis neste estágio; esses tópicos serão abordados em versões futuras.

* Alguns repositórios de contêiner estão acessíveis atualmente apenas via IPv4; por esse motivo, um repositório local no Cluster de Gerenciamento é necessário para um cluster downstream somente com IPv6.

== Versões dos Componentes

A tabela a seguir descreve os componentes individuais que compõem a versão 3.6.0, incluindo a versão, a versão do gráfico Helm (se aplicável) e de onde o artefato lançado pode ser extraído no formato binário. Siga a documentação associada para exemplos de uso e implantação.

|======
| Nome | Versão | Versão do Gráfico Helm | Local do artefato (URL/Imagem)
| SUSE Linux Micro | 6.2 (mais recente) | N/A | https://www.suse.com/download/sle-micro/[Página de download do SUSE Linux Micro] +
| SUSE Linux Micro | 6.2 (mais recente) | N/A |Checksums e assinaturas estão disponíveis para download na https://www.suse.com/download/sle-micro/[Página de download do SUSE Linux Micro] +
SL-Micro.x86_64-6.2-Base-SelfInstall-GM.install.iso +
SL-Micro.x86_64-6.2-Base-RT-SelfInstall-GM.install.iso +
SL-Micro.x86_64-6.2-Base-GM.raw.xz +
SL-Micro.x86_64-6.2-Base-RT-GM.raw.xz +
| SUSE Multi-Linux Manager | 5.1 | N/A | https://www.suse.com/download/suse-manager/[Página de download do SUSE Multi-Linux Manager]
| K3s | 1.35.3 | N/A | https://github.com/k3s-io/k3s/releases/tag/v1.35.3%2Bk3s1[Versão upstream do K3s]
| RKE2 | 1.35.3 | N/A | https://github.com/rancher/rke2/releases/tag/v1.35.3%2Brke2r3[Versão upstream do RKE2]
| SUSE Rancher Prime | 2.14.1 | 2.14.1 | https://charts.rancher.com/server-charts/prime/index.yaml[Repositório Helm do Rancher Prime] +
\https://prime.ribs.rancher.io/rancher/v2.14.1/rancher-images.txt[Rancher 2.14.1 Container Images]
| SUSE Storage (Longhorn) | 1.11.1 | 1.11.1 | https://apps.rancher.io/applications/suse-storage[Repositório Helm do SUSE Storage] +
\https://apps.rancher.io/applications/suse-storage/components[Imagens de Contêiner do SUSE Storage]
| SUSE Security (NeuVector) | 5.5.1 | 109.0.1+up2.8.13 | https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.rancher.com/rancher/neuvector-controller:5.5.1 +
registry.rancher.com/rancher/neuvector-enforcer:5.5.1 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.12
| Provedores do Rancher Turtles (CAPI) | 0.26.1 | 306.0.6+up0.26.1 | registry.suse.com/edge/3.6/rancher-turtles-providers-chart:306.0.6+up0.26.1 +
registry.rancher.com/rancher/cluster-api-controller:v1.12.2 +
registry.rancher.com/rancher/turtles:v0.26.1 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.24.3 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.24.3
| Metal^3^ | 0.15.0 | 306.0.26+up0.15.0 | registry.suse.com/edge/3.6/metal3-chart:306.0.26+up0.15.0 +
registry.suse.com/edge/3.6/baremetal-operator:0.12.3.0 +
registry.suse.com/edge/3.6/ironic:35.0.0.1 +
registry.suse.com/edge/3.6/ironic-ipa-downloader:3.1.1 +
registry.suse.com/edge/3.6/ironic-python-agent:3.0.8
| MetalLB | 0.15.3 | 306.0.2+up0.15.3 | registry.suse.com/edge/3.6/metallb-chart:306.0.2+up0.15.3 +
registry.suse.com/edge/3.6/metallb-controller:v0.15.3 +
registry.suse.com/edge/3.6/metallb-speaker:v0.15.3
| Elemental | 1.9.0 | 1.9.0 | registry.suse.com/rancher/elemental-operator-chart:1.9.0 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.9.0 +
registry.suse.com/rancher/elemental-operator:1.9.0
| Extensão do Painel Elemental | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/main/charts/elemental/3.0.1[Helm Chart da Extensão Elemental]
| Edge Image Builder | 1.3.3.1 | N/A | registry.suse.com/edge/3.6/edge-image-builder:1.3.3.1
| KubeVirt | 1.7.0 | 306.0.2+up0.7.0 | registry.suse.com/edge/3.6/kubevirt-chart:306.0.2+up0.7.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.7.0-150700.3.16.2
| Extensão do Painel KubeVirt | 1.3.3 | 306.0.4+up1.3.3 | registry.suse.com/edge/3.6/kubevirt-dashboard-extension-chart:306.0.4+up1.3.3
| Containerized Data Importer (CDI) | 1.64.0 | 306.0.2+up0.7.0 | registry.suse.com/edge/3.6/cdi-chart:306.0.2+up0.7.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.64.0-150700.9.6.1
| Operador Endpoint Copier | 0.3.0 | 306.0.1+up0.3.0 | registry.suse.com/edge/3.6/endpoint-copier-operator-chart:306.0.1+up0.3.0 +
registry.suse.com/edge/3.6/endpoint-copier-operator:0.3.0
| Operador de Rede SR-IOV | 1.6.0 | 306.0.4+up1.6.0 | registry.suse.com/edge/3.6/sriov-network-operator-chart:306.0.4+up1.6.0 +
registry.suse.com/edge/3.6/sriov-crd-chart:306.0.4+up1.6.0
| Upgrade Controller | 0.19.1 | 109.0.1 | https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.rancher.com/rancher/system-upgrade-controller:v0.19.1
| Upgrade Controller | 0.1.3 | 306.0.3+up0.1.3 | registry.suse.com/edge/3.6/upgrade-controller-chart:306.0.3+up0.1.3 +
registry.suse.com/edge/3.6/upgrade-controller:0.1.3 +
registry.rancher.com/rancher/kubectl:v1.35.2 +
registry.suse.com/edge/3.6/release-manifest:3.6.0
| SUSE Private Registry | 1.1.1 | 1.1.1 | oci://registry.suse.com/private-registry/private-registry-helm[Repositório Helm do SUSE Private Registry] +
registry.suse.com/private-registry/harbor-core:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-jobservice:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-portal:1.1.1-1.20 +
registry.suse.com/private-registry/harbor-registry:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-registryctl:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-trivy-adapter:1.1.1-1.24
| Kiwi Builder | 10.2.29.1 | N/A | registry.suse.com/edge/3.6/kiwi-builder:10.2.29.1
| Cert-Manager | 1.20.1 | 1.20.1 | https://charts.jetstack.io[Repositório Helm Jetstack] +
quay.io/jetstack/cert-manager-controller:v1.20.1 +
quay.io/jetstack/cert-manager-webhook:v1.20.1 +
quay.io/jetstack/cert-manager-cainjector:v1.20.1
|======

= Recursos removidos

Salvo indicação em contrário, estes se aplicam à versão {version-edge}.0 e a todas as versões z-stream subsequentes.

* O Akri era uma oferta de Technology Preview em versões anteriores do Edge e foi descontinuado a partir da 3.4.0. Ele foi completamente removido da oferta.

[#tech-previews]
= Prévias de tecnologia

Salvo indicação em contrário, estes se aplicam à versão 3.6.0 e a todas as versões z-stream subsequentes.

* Implantações de cluster de gerenciamento IPv6 de pilha única são uma oferta de Technology Preview e não estão sujeitas ao escopo padrão de suporte.

= Verificação de componentes

Os componentes mencionados acima podem ser verificados usando os dados da Lista de Materiais de Software (SBOM) - por exemplo, usando `cosign` conforme descrito abaixo:

Baixe a chave pública do contêiner {product} da https://www.suse.com/support/security/keys/[fonte de chaves de assinatura da SUSE]:

[,bash]
----
include::key.sh[]
----

Verifique o hash da imagem do contêiner, por exemplo, usando `crane`:

[,bash]
----
> crane digest registry.suse.com/edge/3.6/baremetal-operator:0.12.3.0 --platform linux/amd64
sha256:example-digest-placeholder
----

NOTE: Para imagens multi-arquitetura, também é necessário especificar uma plataforma ao obter o digest, por exemplo, `--platform linux/amd64` ou `--platform linux/arm64`. A falha em fazer isso resultará em um erro na etapa a seguir (`Error: no matching attestations`).

Verifique com `cosign`:

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/3.6/baremetal-operator@sha256:example-digest-placeholder > /dev/null
#
Verification for registry.suse.com/edge/3.6/baremetal-operator@sha256:example-digest-placeholder --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - The signatures were verified against the specified public key
----

Extraia os dados da SBOM conforme descrito na https://www.suse.com/support/security/sbom/[documentação da SBOM da SUSE]:

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/3.6/baremetal-operator@sha256:example-digest-placeholder | jq '.payload | @base64d | fromjson | .predicate'
----

= Etapas de Atualização

Consulte o <<day-2-operations>> para obter detalhes sobre como fazer upgrade para uma nova versão.

= Ciclo de vida de suporte de produtos

O {product} conta com o suporte premiado da SUSE, uma líder tecnológica estabelecida com um histórico comprovado de entrega de serviços de suporte com qualidade empresarial. Para mais informações, consulte https://www.suse.com/lifecycle[https://www.suse.com/lifecycle] e a página da Política de Suporte em https://www.suse.com/support/policy.html[https://www.suse.com/support/policy.html]. Se você tiver alguma dúvida sobre como abrir um caso de suporte, como a SUSE classifica os níveis de severidade ou o escopo do suporte, consulte o Manual de Suporte Técnico em https://www.suse.com/support/handbook/[https://www.suse.com/support/handbook/].

O {product} \"3.6\" é suportado por 24 meses de suporte de produção, com 6 meses iniciais de \"suporte completo\", seguidos por 18 meses de \"suporte de manutenção\".  Após essas fases de suporte, o produto atinge o "fim do serviço" (EOL) e não é mais suportado. Mais informações sobre as fases do ciclo de vida podem ser encontradas na tabela abaixo:

|======
| *Suporte Completo (6 meses)* | Correções de bugs urgentes e de alta prioridade selecionadas serão lançadas durante a janela de suporte completo, e todos os outros patches (não urgentes, melhorias, novos recursos) serão lançados por meio do cronograma de lançamento regular.
| *Suporte de Manutenção (18 meses)* | Durante este período, apenas correções críticas serão lançadas por meio de patches. Outras correções de bugs podem ser lançadas a critério da SUSE, mas não devem ser esperadas.
| *Fim do Serviço (EOL)*  | Assim que uma versão de produto atinge sua data de Fim do Serviço (EOL), o cliente pode continuar a usar o produto dentro dos termos do contrato de licenciamento do produto.
Os Planos de Suporte da SUSE não se aplicam a versões de produtos após sua data de EOL.
|======

A menos que explicitamente declarado, todos os componentes listados são considerados Geralmente Disponíveis (GA) e são cobertos pelo escopo padrão de suporte da SUSE. Alguns componentes podem ser listados como "Technology Preview", onde a SUSE fornece aos clientes acesso a recursos e funcionalidades pré-GA iniciais para avaliação, mas não estão sujeitos às políticas de suporte padrão e não são recomendados para casos de uso em produção. A SUSE aceita muito bem comentários e sugestões sobre as melhorias que podem ser feitas nos componentes de Technology Preview, mas a SUSE reserva-se o direito de descontinuar um recurso de Technology Preview antes que ele se torne Geralmente Disponível se ele não atender às necessidades de nossos clientes ou não atingir um estado de maturidade que exigimos.

Observe que a SUSE deve ocasionalmente descontinuar recursos ou alterar especificações de API. Os motivos para a descontinuação de recursos ou alteração de API podem incluir um recurso sendo atualizado ou substituído por uma nova implementação, um novo conjunto de recursos, a tecnologia upstream não estar mais disponível ou a comunidade upstream ter introduzido alterações incompatíveis. Não se pretende que isso aconteça dentro de uma determinada versão secundária (x.z), portanto, todas as versões z-stream manterão a compatibilidade de API e a funcionalidade de recursos. A SUSE se esforçará para fornecer avisos de descontinuação com bastante antecedência nas notas de versão, juntamente com soluções alternativas, sugestões e mitigações para minimizar a interrupção do serviço.

A equipe {product} também aceita comentários da comunidade, onde problemas podem ser levantados no respectivo repositório de código dentro de https://www.github.com/suse-edge[https://www.github.com/suse-edge].

= Obtenção de código-fonte

Este produto SUSE inclui materiais licenciados para a SUSE sob a GNU General Public License (GPL) e várias outras licenças de código aberto. A GPL exige que a SUSE forneça o código-fonte que corresponde ao material licenciado pela GPL e que a SUSE esteja em conformidade com todos os outros requisitos de licença de código aberto. Como tal, a SUSE disponibiliza todo o código-fonte, que geralmente pode ser encontrado no repositório GitHub {product} (https://www.github.com/suse-edge[https://www.github.com/suse-edge]), no repositório GitHub do SUSE Rancher (https://www.github.com/rancher[https://www.github.com/rancher]) para componentes dependentes e, especificamente, para o SUSE Linux Micro, o código-fonte está disponível para download em https://www.suse.com/download/sle-micro/[https://www.suse.com/download/sle-micro] na "Medium 2".

= Informações legais

A SUSE não faz representações ou garantias quanto ao conteúdo ou à utilização desta documentação e, especificamente, isenta-se de quaisquer garantias explícitas ou implícitas de comerciabilidade ou adequação a qualquer propósito específico. Além disso, a SUSE reserva-se o direito de revisar esta publicação e de fazer mudanças em seu conteúdo a qualquer momento, sem a obrigação de notificar qualquer pessoa ou entidade sobre essas revisões ou mudanças.

Além disso, a SUSE não faz representações ou garantias quanto a qualquer software e, especificamente, isenta-se de quaisquer garantias explícitas ou implícitas de comerciabilidade ou adequação a qualquer propósito específico. Além disso, a SUSE reserva-se o direito de fazer mudanças em qualquer parte do software SUSE, a qualquer momento, sem a obrigação de notificar qualquer pessoa ou entidade sobre essas mudanças.

Todos os produtos ou as informaçőes técnicas fornecidas neste Contrato podem estar sujeitas aos controles de exportação dos Estados Unidos e ŕs leis de comércio de outros países. Você concorda em obedecer a todos os regulamentos de controle de exportação e em obter quaisquer licenças ou classificações necessárias para exportar, reexportar ou importar produtos. Você concorda em não exportar ou reexportar para entidades nas listas de exclusão de exportação atuais dos Estados Unidos ou para países sob embargo ou considerados terroristas, conforme especificado nas leis de exportação dos Estados Unidos. Você concorda em não usar entregáveis para fins proibidos relacionados a armas nucleares, mísseis ou armamentos químicos/biológicos. Consulte https://www.suse.com/company/legal/[https://www.suse.com/company/legal/] para obter mais informações sobre a exportação do software SUSE. A SUSE não assume qualquer responsabilidade caso você não obtenha as aprovações necessárias para exportação.

*Copyright © 2024 SUSE LLC.*

Este documento de notas de versão está licenciado sob uma Licença Creative Commons Atribuição-SemDerivações 4.0 Internacional (CC-BY-ND-4.0). Você deve ter recebido uma cópia da licença juntamente com este documento. Caso não tenha recebido, consulte https://creativecommons.org/licenses/by-nd/4.0/[https://creativecommons.org/licenses/by-nd/4.0/].

A SUSE possui direitos de propriedade intelectual relacionados à tecnologia incorporada ao produto descrito neste documento. Em particular, e sem limitações, esses direitos de propriedade intelectual podem incluir uma ou mais patentes dos EUA listadas em https://www.suse.com/company/legal/[https://www.suse.com/company/legal/] e uma ou mais patentes adicionais ou pedidos de patentes pendentes nos EUA e em outros países.

Para marcas registradas da SUSE, consulte a lista de Marcas Registradas e Marcas de Serviço da SUSE (https://www.suse.com/company/legal/[https://www.suse.com/company/legal/]). Todas as marcas registradas de terceiros pertencem aos seus respectivos proprietários. Para obter informações sobre a marca SUSE e requisitos de uso, consulte as diretrizes publicadas em https://brand.suse.com/[https://brand.suse.com/].
