[#release-notes-abstract]
= Abstrato
:revdate: 2026-07-17
:revnumber: 3.4
:page-revdate: {revdate}
ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

O SUSE Edge 3.4 é uma solução de ponta a ponta fortemente integrada e abrangentemente validada para abordar os desafios únicos da implantação de infraestrutura e aplicativos nativos de nuvem na borda. Seu foco principal é fornecer uma plataforma opinativa, porém altamente flexível, altamente escalável e segura que abrange a construção de imagem de implantação inicial, provisionamento e integração de nós, implantação de aplicativos, observabilidade e gerenciamento de ciclo de vida.

A solução foi projetada com a noção de que não existe uma plataforma de borda de "tamanho único" devido aos requisitos e expectativas amplamente variados de nossos clientes. As implantações de borda nos levam a resolver, e evoluir continuamente, alguns dos problemas mais desafiadores, incluindo escalabilidade massiva, disponibilidade de rede restrita, restrições de espaço físico, novas ameaças de segurança e vetores de ataque, variações na arquitetura de hardware e recursos do sistema, o requisito de implantar e interagir com infraestrutura e aplicativos legados, e soluções de clientes que possuem vida útil estendida.

O SUSE Edge é construído desde o início com o melhor software de código aberto, consistente tanto com nossa história de 30 anos na entrega de plataformas SUSE Linux seguras, estáveis e certificadas, quanto com nossa experiência no fornecimento de gerenciamento de Kubernetes altamente escalável e rico em recursos com nosso portfólio Rancher. O SUSE Edge baseia-se nessas capacidades para fornecer funcionalidades que podem atender a um grande número de segmentos de mercado, incluindo varejo, médico, transporte, logística, telecomunicações, manufatura inteligente e IoT industrial.

Para obter mais informações sobre atualizações do ciclo de vida de suporte do produto para o SUSE Edge, consulte link:https://www.suse.com/lifecycle/#suse-edge-33[Product Support Lifecycle]. 

NOTE: O SUSE Telco Cloud (anteriormente conhecido como SUSE Edge for Telco) é um derivado do SUSE Edge, com otimizações e componentes adicionais que permitem que a plataforma atenda aos requisitos encontrados em casos de uso de telecomunicações. A menos que explicitamente declarado, todas as notas de lançamento são aplicáveis tanto ao SUSE Edge 3.4 quanto ao SUSE Telco Cloud 3.4.

= Sobre

Estas Notas de Lançamento são, a menos que explicitamente especificado e explicado, idênticas em todas as arquiteturas, e a versão mais recente, juntamente com as notas de lançamento de todos os outros produtos SUSE, estão sempre disponíveis online em https://www.suse.com/releasenotes[https://www.suse.com/releasenotes].

As entradas são listadas apenas uma vez, mas podem ser referenciadas em vários lugares se forem importantes e pertencerem a mais de uma seção. As notas de lançamento geralmente listam apenas as alterações que ocorreram entre dois lançamentos subsequentes. Algumas entradas importantes das notas de lançamento de versões anteriores do produto podem ser repetidas. Para tornar essas entradas mais fáceis de identificar, elas contêm uma nota para esse efeito.

No entanto, as entradas repetidas são fornecidas apenas como uma cortesia. Portanto, se você estiver pulando um ou mais lançamentos, verifique também as notas de lançamento dos lançamentos ignorados. Se você estiver lendo apenas as notas de lançamento da versão atual, poderá perder mudanças importantes que podem afetar o comportamento do sistema. As versões do SUSE Edge são definidas como x.y.z, onde 'x' denota a versão principal, 'y' denota a versão secundária e 'z' denota a versão de patch, também conhecida como "z-stream". Os ciclos de vida do produto SUSE Edge são definidos com base em um determinado lançamento secundário, por exemplo. "3.4", mas são fornecidos com atualizações de patch subsequentes ao longo de seu ciclo de vida, por exemplo. "3.4.1".

NOTE: Os lançamentos z-stream do SUSE Edge são fortemente integrados e completamente testados como uma pilha versionada. Fazer upgrade de quaisquer componentes individuais para versões diferentes daquelas listadas acima provavelmente resultará em tempo de inatividade do sistema. Embora seja possível executar clusters Edge em configurações não testadas, isso não é recomendado e pode levar mais tempo para fornecer uma resolução por meio dos canais de suporte.

[#release-notes-3-4-4]
= Lançamento 3.4.4

Data de disponibilidade: 22 de julho de 2026

Data de término do suporte completo: 20 de março de 2026

Data de término do suporte de manutenção: 20 de setembro de 2027

EOL: 21 de setembro de 2027

Resumo: O SUSE Edge 3.4.4 é o quarto lançamento z-stream no fluxo de lançamento do SUSE Edge 3.4

* O Rancher Prime 2.11.15 contém várias correções de bugs e atualizações de segurança https://github.com/rancher/rancher/releases/tag/v2.11.15[Notas de Lançamento do Rancher Upstream]
* As atualizações do Metal^3^/Ironic corrigem vários bugs e problemas de segurança, incluindo os seguintes:
** Fix CVE-2026-44916
** Fix CVE-2026-44917
** Fix CVE-2026-44919
** Fix CVE-2026-46447
** Fix CVE-2026-48681
** Fix CVE-2026-54421


== Novos recursos

* Atualizado para Kubernetes 1.33.11 https://github.com/k3s-io/k3s/releases/tag/v1.33.11%2Bk3s1[Notas de versão do K3s] / https://github.com/rancher/rke2/releases/tag/v1.33.11%2Brke2r1[Notas de versão do RKE2]
* Atualizado para Rancher Prime 2.12.10 https://github.com/rancher/rancher/releases/tag/v2.12.10[Notas de versão]
* Atualizado para SUSE Security (Neuvector) 5.5.2 https://open-docs.neuvector.com/5.5/releasenotes/5x[Notas de versão]
* Atualizado o chart Metal^3^ para 304.0.22+up0.12.9 com várias melhorias

== Correções de bug e segurança

* O Rancher Prime 2.12.10 contém várias correções de bugs e atualizações de segurança https://github.com/rancher/rancher/releases/tag/v2.12.10[Notas de versão do Rancher upstream]
* O Edge Image Builder foi atualizado para 1.3.1.1
* As atualizações do Metal^3^/Ironic corrigem vários bugs e problemas de segurança, incluindo os seguintes:
** Fix CVE-2026-44916
** Fix CVE-2026-44917
** Fix CVE-2026-44919
** Fix CVE-2026-46447
** Fix CVE-2026-48681
** Fix CVE-2026-54421

== Problemas conhecidos

* Existe um bug conhecido nas versões do Rancher 2.12.* que pode interromper o fluxo de trabalho de atualização do System Upgrade Controller (SUC). O Rancher Prime 2.12.x agrupa um CRD `plans.upgrade.cattle.io` desatualizado e o reaplica a cada reinicialização do Rancher, sobrescrevendo o esquema pertencente ao SUC v0.16.3. Isso reverte o campo `spec.drain.timeout` de `IntOrString` para apenas números inteiros, portanto, qualquer `Plan` do SUC que use um valor de tempo limite de string (por exemplo, `timeout: "5m"`) falha na validação do esquema após uma reinicialização do Rancher. Como as reinicializações do Rancher ocorrem durante operações de rotina e upgrades, isso ocorre novamente na operação normal e pode bloquear fluxos de trabalho de upgrade de SO e Kubernetes gerenciados pelo SUC.
+
Como uma solução temporária, reinicie a implantação do System Upgrade Controller para reafirmar o esquema correto. Isso deve ser repetido após cada reinicialização do Rancher:
+
[,bash]
----
kubectl -n cattle-system rollout restart deployment/system-upgrade-controller
----
[WARNING]
====
Ao implantar novos clusters, siga <<guides-kiwi-builder-images>> para criar novas imagens primeiro, pois esta é agora a primeira etapa necessária para criar clusters para as arquiteturas {x86-64} e {aarch64}, bem como clusters de gerenciamento e downstream.
====

* Ao implantar via Edge Image Builder, os manifestos `HelmChartConfigs` podem falhar se forem colocados no diretório de configuração `kubernetes/manifests`. Em vez disso, recomenda-se colocar qualquer `HelmChartConfigs` em `/var/lib/rancher/{rke2/k3s}/server/manifests/` usando a interface os-files do EIB, veja <<mgmt-cluster-directory-structure>> como exemplo.  A não realização deste procedimento pode causar a permanência dos nós no estado `NotReady` na inicialização inicial, conforme discutido em https://github.com/rancher/rke2/issues/8357[#8357 issue do RKE2]

* Nas versões RKE2/K3s 1.31, 1.32 e 1.33, o diretório `/etc/cni` usado para armazenar configurações de CNI pode não disparar uma notificação dos arquivos gravados para `containerd` devido a certas condições relacionadas ao `overlayfs` (consulte o https://github.com/rancher/rke2/issues/8356[#8356 issue do RKE2]). Isso, por sua vez, faz com que a implantação do RKE2/K3s fique travada aguardando a inicialização do CNI, e os nós do RKE2/K3s permaneçam no estado `NotReady`. Isso pode ser visto no nível do nó com `kubectl describe node <affected_node>`:

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

Como solução alternativa, um volume tmpfs pode ser montado no diretório `/etc/cni` antes que o RKE2 seja iniciado. Isso evita o uso de overlayfs, o que faz com que o containerd perca notificações, e as configurações devem ser reescritas toda vez que o nó for reiniciado e os initcontainers dos pods forem executados novamente. Se estiver usando o EIB, este pode ser um script `04-tmpfs-cni.sh` no diretório `custom/scripts` (conforme explicado aqui[https://github.com/suse-edge/edge-image-builder/blob/release-1.2/docs/building-images.md#custom]) que se parece com:

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* Ao integrar hosts remotos usando o Elemental, uma condição de corrida entre `dbus.service` e `elemental-system-agent.service` pode ocorrer, resultando em falha de `rancher-system-agent.service` no host remoto ao iniciar com erros semelhantes ao abaixo. (consulte o https://github.com/suse-edge/edge-image-builder/issues/784[#784 issue do Edge Image Builder] para obter detalhes.)

[,bash]
----
Sep 19 19:38:07 elementalvm elemental-system-agent[3671]: time="2025-09-19T19:38:07Z" level=info msg="[6b20fe64c854da2639804884b34129bb8f718eb59578111da58d9de1509c24db_1:stderr]: Failed to restart rancher-system-agent.service: Message recipient disconnected from message bus without replying"
----

Como solução alternativa, um arquivo de substituição do systemd pode ser criado conforme abaixo.

[,bash]
----
[Unit]
Wants=dbus.service network-online.target
After=dbus.service network-online.target time-sync.target

[Service]
ExecStartPre=/bin/bash -c 'echo "Waiting for dbus to become active..." | systemd-cat -p info -t elemental-system-agent; sleep 15; timeout 300 bash -c "while ! systemctl is-active --quiet dbus.service; do sleep 15; done"'
----

e um script personalizado chamado `30a-copy-elemental-system-agent-override.sh` pode ser usado para colocar a substituição em `/etc/systemd/system/elemental-system-agent.service.d` antes que o script https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/templates/31-elemental-register.sh.tpl[31-elemental-register.sh] do EIB seja executado durante a fase de combustão.

[,bash]
----
#!/bin/bash

/bin/mkdir -p /etc/systemd/system/elemental-system-agent.service.d
/bin/cp -f elemental-system-agent-override.conf /etc/systemd/system/elemental-system-agent.service.d/override.conf
----

== Versões dos Componentes

A tabela a seguir descreve os componentes individuais que compõem a versão 3.4.4, incluindo a versão, a versão do Helm chart (se aplicável) e de onde o artefato lançado pode ser extraído no formato binário. Siga a documentação associada para exemplos de uso e implantação.

|======
| Nome | Versão | Versão do Gráfico Helm | Local do artefato (URL/Imagem)
| SUSE Linux Micro | 6.1 (mais recente) | N/A | https://www.suse.com/download/sle-micro/[Página de download do SUSE Linux Micro] +
SL-Micro.x86_64-6.1-Base-SelfInstall-GM.install.iso (sha256 70b9be28f2d92bc3b228412e4fc2b1d5026e691874b728e530b8063522158854) +
SL-Micro.x86_64-6.1-Base-RT-SelfInstall-GM.install.iso (sha256 9ce83e4545d4b36c7c6a44f7841dc3d9c6926fe32dbff694832e0fbd7c496e9d) +
SL-Micro.x86_64-6.1-Base-GM.raw.xz (sha256 36e3efa55822113840dd76fdf6914e933a7b7e88a1dce5cb20c424ccf2fb4430) +
SL-Micro.x86_64-6.1-Base-RT-GM.raw.xz (sha256 2ee66735da3e1da107b4878e73ae68f5fb7309f5ec02b5dfdb94e254fda8415e) +
| SUSE Multi-Linux Manager | 5.0.6 | N/A | https://www.suse.com/download/suse-manager/[Página de download do SUSE Multi-Linux Manager]
s| K3s s| 1.33.11 | N/A | https://github.com/k3s-io/k3s/releases/tag/v1.33.11%2Bk3s1[Versão upstream do K3s]
s| RKE2 s| 1.33.11 | N/A | https://github.com/rancher/rke2/releases/tag/v1.33.11%2Brke2r1[Versão upstream do RKE2]
s| SUSE Rancher Prime s| 2.12.10 s| 2.12.10 | https://charts.rancher.com/server-charts/prime/index.yaml[Repositório Helm do Rancher Prime] +
\https://prime.ribs.rancher.io/rancher/v2.12.10/rancher-images.txt[Rancher 2.12.10 Container Images]
| SUSE Storage (Longhorn) | 1.9.2 | 107.1.1+up1.9.2 | https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.suse.com/rancher/mirrored-longhornio-csi-attacher:v4.9.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-provisioner:v5.3.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-resizer:v1.14.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-snapshotter:v8.3.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-node-driver-registrar:v2.14.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-livenessprobe:v2.16.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-backing-image-manager:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-engine:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-instance-manager:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-manager:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-share-manager:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-ui:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-support-bundle-kit:v0.0.61 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-cli:v1.9.2 +
s| SUSE Security s| 5.5.2 s| 107.0.7+up2.10.2 | https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.suse.com/rancher/neuvector-controller:5.5.2 +
registry.suse.com/rancher/neuvector-enforcer:5.5.2 +
registry.suse.com/rancher/neuvector-manager:5.5.2 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.13 +
registry.suse.com/rancher/neuvector-registry-adapter:0.1.8 +
registry.suse.com/rancher/neuvector-scanner:6 +
registry.suse.com/rancher/neuvector-updater:0.0.4
| Rancher Turtles (CAPI) | 0.24.3 | 304.0.8+up0.24.3 | registry.suse.com/edge/charts/rancher-turtles:304.0.8_up0.24.3 +
registry.rancher.com/rancher/rancher/turtles:v0.24.3 +
registry.rancher.com/rancher/cluster-api-metal3-controller:v1.10.2 +
registry.rancher.com/rancher/cluster-api-metal3-ipam-controller:v1.10.2 +
registry.suse.com/rancher/cluster-api-controller:v1.10.5 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.20.1 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.20.1
| Recursos de Airgap do Rancher Turtles | 0.24.3 | 304.0.8+up0.24.3 | registry.suse.com/edge/charts/rancher-turtles-airgap-resources:304.0.8_up0.24.3
s| Metal^3^ | 0.12.9 s| 304.0.22+up0.12.9 | registry.suse.com/edge/charts/metal3:304.0.22_up0.12.9 +
registry.suse.com/edge/3.4/baremetal-operator:0.10.4 +
registry.suse.com/edge/3.4/ironic:29.0.4.4 +
registry.suse.com/edge/3.4/ironic-ipa-downloader:3.0.10 +
| MetalLB | 0.14.9 | 304.0.0+up0.14.9 | registry.suse.com/edge/charts/metallb:304.0.0_up0.14.9 +
registry.suse.com/edge/3.4/metallb-controller:v0.14.9 +
registry.suse.com/edge/3.4/metallb-speaker:v0.14.9 +
registry.suse.com/edge/3.4/frr:8.5.6 +
registry.suse.com/edge/3.4/frr-k8s:v0.0.16 +
registry.suse.com/edge/3.4/kube-rbac-proxy:0.18.1
| Elemental | 1.7.3 | 1.7.3 | registry.suse.com/rancher/elemental-operator-chart:1.7.3 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.7.3 +
registry.suse.com/rancher/elemental-operator:1.7.3
| Extensão do Painel Elemental | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/4.0.0/charts/elemental/3.0.1[Helm Chart de Extensão Elemental]
s| Edge Image Builder s| 1.3.1.1 | N/A s| registry.suse.com/edge/3.4/edge-image-builder:1.3.1.1
| Configurador NM | 0.3.5 | N/A | https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.5[Lançamento Upstream do NMConfigurator]
| KubeVirt | 1.5.2 | 304.0.1+up0.6.0 | registry.suse.com/edge/charts/kubevirt:304.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportproxy:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportserver:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.5.2
| Extensão do Painel KubeVirt | 1.3.2 | 304.0.3+up1.3.2 | registry.suse.com/edge/charts/kubevirt-dashboard-extension:304.0.3_up1.3.2
| Importador de Dados Conteinerizado | 1.62.0 | 304.0.1+up0.6.0 | registry.suse.com/edge/charts/cdi:304.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-importer:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-cloner:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.62.0
| Operador Endpoint Copier | 0.3.0 | 304.0.1+up0.3.0 | registry.suse.com/edge/charts/endpoint-copier-operator:304.0.1_up0.3.0 +
registry.suse.com/edge/3.4/endpoint-copier-operator:0.3.0
| Operador de Rede SR-IOV | 1.5.0 | 304.0.2+up1.5.0 | registry.suse.com/edge/charts/sriov-network-operator:304.0.2_up1.5.0 +
registry.suse.com/edge/charts/sriov-crd:304.0.2_up1.5.0
| Upgrade Controller | 0.16.3 | 107.0.0 | https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.suse.com/rancher/system-upgrade-controller:v0.16.3
s| Upgrade Controller s| 0.1.3 s| 304.0.3+up0.1.3 | registry.suse.com/edge/charts/upgrade-controller:304.0.3_up0.1.3 +
registry.suse.com/edge/3.4/upgrade-controller:0.1.3 +
registry.suse.com/edge/3.4/kubectl:1.33.11 +
*registry.suse.com/edge/3.4/release-manifest:3.4.4*
| Kiwi Builder | 10.2.12.1 | N/A | registry.suse.com/edge/3.4/kiwi-builder:10.2.12.1
|======

[#release-notes-3-4-3]
= Release 3.4.3

Data de disponibilidade: 12 de janeiro de 2026

Data de término do suporte completo: 20 de março de 2026

Data de término do suporte de manutenção: 20 de setembro de 2027

EOL: 21 de setembro de 2027

Resumo: O SUSE Edge 3.4.3 é o terceiro lançamento z-stream na linha de lançamento do SUSE Edge 3.4

== Novos recursos

* Atualizado para Kubernetes 1.33.6 e Rancher Prime 2.12.5 https://github.com/rancher/rancher/releases/tag/v2.12.5[Notas de Lançamento]
* Atualizar para o SUSE Multi-Linux Manager 5.0.6 https://documentation.suse.com/releasenotes/suma/5.0/#_version_5_0_6[Notas de Lançamento]

== Correções de bug e segurança

* O gráfico Edge Rancher Turtles foi atualizado para garantir que os recursos sejam removidos corretamente na desinstalação (o que será necessário como parte da migração para fazer upgrade para a versão 3.5)
* O RKE2 1.33.6 contém várias atualizações de versão e correções https://github.com/rancher/rke2/releases/tag/v1.33.6%2Brke2r1[Notas de Lançamento]
* O SUSE Multi-Linux Manager 5.0.6 contém várias correções relacionadas à segurança https://documentation.suse.com/releasenotes/suma/5.0/#_version_5_0_6[Notas de Lançamento]

== Problemas conhecidos

[WARNING]
====
Ao implantar novos clusters, siga <<guides-kiwi-builder-images>> para criar novas imagens primeiro, pois esta é agora a primeira etapa necessária para criar clusters para as arquiteturas {x86-64} e {aarch64}, bem como clusters de gerenciamento e downstream.
====

* Ao implantar via Edge Image Builder, os manifestos `HelmChartConfigs` podem falhar se forem colocados no diretório de configuração `kubernetes/manifests`. Em vez disso, recomenda-se colocar qualquer `HelmChartConfigs` em `/var/lib/rancher/{rke2/k3s}/server/manifests/` usando a interface os-files do EIB, veja <<mgmt-cluster-directory-structure>> como exemplo.  Falhar em fazer isso pode fazer com que os nós permaneçam no estado `NotReady` na inicialização inicial, conforme discutido em https://github.com/rancher/rke2/issues/8357[#8357 problema do RKE2]

* Nas versões RKE2/K3s 1.31, 1.32 e 1.33, o diretório `/etc/cni` usado para armazenar configurações de CNI pode não disparar uma notificação dos arquivos gravados para `containerd` devido a certas condições relacionadas ao `overlayfs` (consulte o https://github.com/rancher/rke2/issues/8356[#8356 problema do RKE2]). Isso, por sua vez, faz com que a implantação do RKE2/K3s fique travada aguardando a inicialização do CNI, e os nós do RKE2/K3s permaneçam no estado `NotReady`. Isso pode ser visto no nível do nó com `kubectl describe node <affected_node>`:

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

Como solução alternativa, um volume tmpfs pode ser montado no diretório `/etc/cni` antes que o RKE2 seja iniciado. Isso evita o uso de overlayfs, o que faz com que o containerd perca notificações, e as configurações devem ser reescritas toda vez que o nó for reiniciado e os initcontainers dos pods forem executados novamente. Se estiver usando o EIB, este pode ser um script `04-tmpfs-cni.sh` no diretório `custom/scripts` (conforme explicado aqui[https://github.com/suse-edge/edge-image-builder/blob/release-1.2/docs/building-images.md#custom]) que se parece com:

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* Ao integrar hosts remotos usando o Elemental, uma condição de corrida entre `dbus.service` e `elemental-system-agent.service` pode ocorrer, resultando na falha de `rancher-system-agent.service` no host remoto ao iniciar com erros semelhantes ao abaixo. (consulte o https://github.com/suse-edge/edge-image-builder/issues/784[problema do Edge Image Builder #784] para obter detalhes.)

[,bash]
----
Sep 19 19:38:07 elementalvm elemental-system-agent[3671]: time="2025-09-19T19:38:07Z" level=info msg="[6b20fe64c854da2639804884b34129bb8f718eb59578111da58d9de1509c24db_1:stderr]: Failed to restart rancher-system-agent.service: Message recipient disconnected from message bus without replying"
----

Como solução alternativa, um arquivo de substituição do systemd pode ser criado conforme abaixo

[,bash]
----
[Unit]
Wants=dbus.service network-online.target
After=dbus.service network-online.target time-sync.target

[Service]
ExecStartPre=/bin/bash -c 'echo "Waiting for dbus to become active..." | systemd-cat -p info -t elemental-system-agent; sleep 15; timeout 300 bash -c "while ! systemctl is-active --quiet dbus.service; do sleep 15; done"'
----

e um script personalizado chamado `30a-copy-elemental-system-agent-override.sh` pode ser usado para aplicar a substituição em `/etc/systemd/system/elemental-system-agent.service.d` antes que o script https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/templates/31-elemental-register.sh.tpl[31-elemental-register.sh] do EIB seja executado durante a fase de combustão.

[,bash]
----
#!/bin/bash

/bin/mkdir -p /etc/systemd/system/elemental-system-agent.service.d
/bin/cp -f elemental-system-agent-override.conf /etc/systemd/system/elemental-system-agent.service.d/override.conf
----

== Versões dos Componentes

A tabela a seguir descreve os componentes individuais que compõem a versão 3.4.3, incluindo a versão, a versão do chart do Helm (se aplicável) e de onde o artefato liberado pode ser obtido no formato binário. Siga a documentação associada para exemplos de uso e implantação.

|======
| Nome | Versão | Versão do Gráfico Helm | Local do artefato (URL/Imagem)
| SUSE Linux Micro | 6.1 (mais recente) | N/A | https://www.suse.com/download/sle-micro/[Página de download do SUSE Linux Micro] +
SL-Micro.x86_64-6.1-Base-SelfInstall-GM.install.iso (sha256 70b9be28f2d92bc3b228412e4fc2b1d5026e691874b728e530b8063522158854) +
SL-Micro.x86_64-6.1-Base-RT-SelfInstall-GM.install.iso (sha256 9ce83e4545d4b36c7c6a44f7841dc3d9c6926fe32dbff694832e0fbd7c496e9d) +
SL-Micro.x86_64-6.1-Base-GM.raw.xz (sha256 36e3efa55822113840dd76fdf6914e933a7b7e88a1dce5cb20c424ccf2fb4430) +
SL-Micro.x86_64-6.1-Base-RT-GM.raw.xz (sha256 2ee66735da3e1da107b4878e73ae68f5fb7309f5ec02b5dfdb94e254fda8415e) +
s| SUSE Multi-Linux Manager s| 5.0.6 | N/A | https://www.suse.com/download/suse-manager/[Página de download do SUSE Multi-Linux Manager]
s| K3s s| 1.33.6 | N/A | https://github.com/k3s-io/k3s/releases/tag/v1.33.6%2Bk3s1[Versão upstream do K3s]
s| RKE2 s| 1.33.6 | N/A | https://github.com/rancher/rke2/releases/tag/v1.33.6%2Brke2r1[Versão upstream do RKE2]
s| SUSE Rancher Prime s| 2.12.5 s| 2.12.5 | https://charts.rancher.com/server-charts/prime/index.yaml[Repositório Helm do Rancher Prime] +
\https://prime.ribs.rancher.io/rancher/v2.12.4/rancher-images.txt[Rancher 2.12.4 Container Images]
| SUSE Storage (Longhorn) | 1.9.2 | 107.1.1+up1.9.2 | https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.suse.com/rancher/mirrored-longhornio-csi-attacher:v4.9.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-provisioner:v5.3.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-resizer:v1.14.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-snapshotter:v8.3.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-node-driver-registrar:v2.14.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-livenessprobe:v2.16.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-backing-image-manager:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-engine:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-instance-manager:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-manager:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-share-manager:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-ui:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-support-bundle-kit:v0.0.61 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-cli:v1.9.2 +
| SUSE Security | 5.4.8 | 107.0.3+up2.8.10 | https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.suse.com/rancher/neuvector-controller:5.4.8 +
registry.suse.com/rancher/neuvector-enforcer:5.4.8 +
registry.suse.com/rancher/neuvector-manager:5.4.8 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.9 +
registry.suse.com/rancher/neuvector-registry-adapter:0.1.8 +
registry.suse.com/rancher/neuvector-scanner:6 +
registry.suse.com/rancher/neuvector-updater:0.0.4
s| Rancher Turtles (CAPI) s| 0.24.3 s| 304.0.8+up0.24.3 | registry.suse.com/edge/charts/rancher-turtles:304.0.8_up0.24.3 +
registry.rancher.com/rancher/rancher/turtles:v0.24.3 +
registry.rancher.com/rancher/cluster-api-metal3-controller:v1.10.2 +
registry.rancher.com/rancher/cluster-api-metal3-ipam-controller:v1.10.2 +
registry.suse.com/rancher/cluster-api-controller:v1.10.5 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.20.1 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.20.1
s| Recursos Airgap do Rancher Turtles s| 0.24.3 | 304.0.8+up0.24.3 | registry.suse.com/edge/charts/rancher-turtles-airgap-resources:304.0.8_up0.24.3
| Metal^3^ | 0.12.9 | 304.0.19+up0.12.9 | registry.suse.com/edge/charts/metal3:304.0.19_up0.12.9 +
registry.suse.com/edge/3.4/baremetal-operator:0.10.4 +
registry.suse.com/edge/3.4/ironic:29.0.4.4 +
registry.suse.com/edge/3.4/ironic-ipa-downloader:3.0.10 +
| MetalLB | 0.14.9 | 304.0.0+up0.14.9 | registry.suse.com/edge/charts/metallb:304.0.0_up0.14.9 +
registry.suse.com/edge/3.4/metallb-controller:v0.14.9 +
registry.suse.com/edge/3.4/metallb-speaker:v0.14.9 +
registry.suse.com/edge/3.4/frr:8.5.6 +
registry.suse.com/edge/3.4/frr-k8s:v0.0.16 +
registry.suse.com/edge/3.4/kube-rbac-proxy:0.18.1
| Elemental | 1.7.3 | 1.7.3 | registry.suse.com/rancher/elemental-operator-chart:1.7.3 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.7.3 +
registry.suse.com/rancher/elemental-operator:1.7.3
| Extensão do Painel Elemental | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/4.0.0/charts/elemental/3.0.1[Extensão Elemental Helm Chart]
| Edge Image Builder | 1.3.1 | N/A s| registry.suse.com/edge/3.4/edge-image-builder:1.3.1
| Configurador NM | 0.3.5 | N/A s| https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.5[Versão upstream do NMConfigurator]
| KubeVirt | 1.5.2 | 304.0.1+up0.6.0 | registry.suse.com/edge/charts/kubevirt:304.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportproxy:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportserver:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.5.2
| Extensão do Painel KubeVirt | 1.3.2 | 304.0.3+up1.3.2 | registry.suse.com/edge/charts/kubevirt-dashboard-extension:304.0.3_up1.3.2
| Importador de Dados Conteinerizado (CDI) | 1.62.0 | 304.0.1+up0.6.0 | registry.suse.com/edge/charts/cdi:304.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-importer:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-cloner:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.62.0
| Operador Endpoint Copier | 0.3.0 | 304.0.1+up0.3.0 | registry.suse.com/edge/charts/endpoint-copier-operator:304.0.1_up0.3.0 +
registry.suse.com/edge/3.4/endpoint-copier-operator:0.3.0
| Operador de Rede SR-IOV | 1.5.0 | 304.0.2+up1.5.0 | registry.suse.com/edge/charts/sriov-network-operator:304.0.2_up1.5.0 +
registry.suse.com/edge/charts/sriov-crd:304.0.2_up1.5.0
| Upgrade Controller | 0.16.0 | 107.0.0 | https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.suse.com/rancher/system-upgrade-controller:v0.16.0
| Upgrade Controller | 0.1.1 | 304.0.1+up0.1.1 | registry.suse.com/edge/charts/upgrade-controller:304.0.1_up0.1.1 +
registry.suse.com/edge/3.4/upgrade-controller:0.1.1 +
registry.suse.com/edge/3.4/kubectl:1.33.4 +
*registry.suse.com/edge/3.4/release-manifest:3.4.3*
| Kiwi Builder s| 10.2.12.1 | N/A s| registry.suse.com/edge/3.4/kiwi-builder:10.2.12.1
|======

[#release-notes-3-4-2]
= Lançamento 3.4.2

Data de disponibilidade: 17 de dezembro de 2025

Data de término do suporte completo: 20 de março de 2026

Data de término do suporte de manutenção: 20 de setembro de 2027

EOL: 21 de setembro de 2027

Resumo: O SUSE Edge 3.4.2 é o segundo lançamento z-stream no fluxo de lançamento do SUSE Edge 3.4

== Novos recursos

* Atualizado para o Rancher Prime 2.12.4 https://github.com/rancher/rancher/releases/tag/v2.12.4[Notas de Lançamento]
* Atualizado para SUSE Security (Neuvector) 5.4.8 https://open-docs.neuvector.com/releasenotes/5x#548-december-2025[Notas de Lançamento]
* Atualizado para o SUSE Storage (Longhorn) 1.9.2 https://longhorn.io/docs/1.9.2/important-notes/[Notas de Lançamento]
* O Edge Image Builder foi atualizado para 1.3.1, veja https://github.com/suse-edge/edge-image-builder/blob/release-1.3/RELEASE_NOTES.md[Notas de Lançamento upstream]
* Versões atualizadas do Rancher Turtles, Kiwi Builder, NM Configurator, Metal3/IPA/Ironic

== Correções de bug e segurança

* O SUSE Security (Neuvector) 5.4.8 contém várias correções de bug https://open-docs.neuvector.com/releasenotes/5x/#548-december-2025[Correções de bug do Neuvector upstream]
* O SUSE Storage (Longhorn) 1.9.2 contém várias correções de bug https://github.com/longhorn/longhorn/releases/tag/v1.9.2[Correções de bug do Longhorn upstream]
* O EIB (edge-image-builder) 1.3.1 contém uma correção para exclusões de cluster elemental https://github.com/suse-edge/edge-image-builder/issues/808[Correção de bug do EIB]
* O Metal3 0.12.9 contém várias correções de bug para problemas de LACP com alguns NICs Intel e a adição de algumas variáveis de ambiente para ajustar o conjunto de cifras TLS para superar problemas de BMC.
* O NMC (nm-configurator) 0.3.5 contém várias correções de bug https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.5[Correções de bug do NMC]
* O Kiwi Builder 10.2.12.1 adiciona iptables, pois isso é necessário ao implantar o RKE2.

== Problemas conhecidos

[WARNING]
====
Ao implantar novos clusters, siga <<guides-kiwi-builder-images>> para criar novas imagens primeiro, pois esta é agora a primeira etapa necessária para criar clusters para as arquiteturas {x86-64} e {aarch64}, bem como clusters de gerenciamento e downstream.
====

* Ao implantar via Edge Image Builder, os manifestos `HelmChartConfigs` podem falhar se forem colocados no diretório de configuração `kubernetes/manifests`. Em vez disso, recomenda-se colocar qualquer `HelmChartConfigs` em `/var/lib/rancher/{rke2/k3s}/server/manifests/` usando a interface os-files do EIB, veja <<mgmt-cluster-directory-structure>> como exemplo.  A falha em fazer isso pode fazer com que os nós permaneçam no estado `NotReady` na inicialização inicial, conforme discutido em https://github.com/rancher/rke2/issues/8357[#8357 problema do RKE2]

* Nas versões RKE2/K3s 1.31, 1.32 e 1.33, o diretório `/etc/cni` usado para armazenar configurações de CNI pode não disparar uma notificação dos arquivos gravados para `containerd` devido a certas condições relacionadas ao `overlayfs` (consulte o https://github.com/rancher/rke2/issues/8356[#8356 problema do RKE2]). Isso, por sua vez, faz com que a implantação do RKE2/K3s fique travada aguardando a inicialização do CNI, e os nós do RKE2/K3s permaneçam no estado `NotReady`. Isso pode ser visto no nível do nó com `kubectl describe node <affected_node>`:

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

Como solução alternativa, um volume tmpfs pode ser montado no diretório `/etc/cni` antes que o RKE2 seja iniciado. Isso evita o uso de overlayfs, o que faz com que o containerd perca notificações, e as configurações devem ser reescritas toda vez que o nó for reiniciado e os initcontainers dos pods forem executados novamente. Se estiver usando o EIB, este pode ser um script `04-tmpfs-cni.sh` no diretório `custom/scripts` (conforme explicado aqui[https://github.com/suse-edge/edge-image-builder/blob/release-1.2/docs/building-images.md#custom]) que se parece com:

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* Ao integrar hosts remotos usando o Elemental, uma condição de corrida entre `dbus.service` e `elemental-system-agent.service` pode ocorrer, resultando na falha de `rancher-system-agent.service` no host remoto ao iniciar com erros semelhantes ao abaixo. (consulte o https://github.com/suse-edge/edge-image-builder/issues/784[#784 problema do Edge Image Builder] para obter detalhes.)

[,bash]
----
Sep 19 19:38:07 elementalvm elemental-system-agent[3671]: time="2025-09-19T19:38:07Z" level=info msg="[6b20fe64c854da2639804884b34129bb8f718eb59578111da58d9de1509c24db_1:stderr]: Failed to restart rancher-system-agent.service: Message recipient disconnected from message bus without replying"
----

Como solução alternativa, um arquivo de substituição do systemd pode ser criado conforme abaixo

[,bash]
----
[Unit]
Wants=dbus.service network-online.target
After=dbus.service network-online.target time-sync.target

[Service]
ExecStartPre=/bin/bash -c 'echo "Waiting for dbus to become active..." | systemd-cat -p info -t elemental-system-agent; sleep 15; timeout 300 bash -c "while ! systemctl is-active --quiet dbus.service; do sleep 15; done"'
----

e um script personalizado chamado `30a-copy-elemental-system-agent-override.sh` pode ser usado para colocar a substituição em `/etc/systemd/system/elemental-system-agent.service.d` antes que o script https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/templates/31-elemental-register.sh.tpl[31-elemental-register.sh] do EIB seja executado durante a fase de combustão.

[,bash]
----
#!/bin/bash

/bin/mkdir -p /etc/systemd/system/elemental-system-agent.service.d
/bin/cp -f elemental-system-agent-override.conf /etc/systemd/system/elemental-system-agent.service.d/override.conf
----

== Versões dos Componentes

A tabela a seguir descreve os componentes individuais que compõem a versão 3.4.2, incluindo a versão, a versão do gráfico Helm (se aplicável) e de onde o artefato lançado pode ser extraído no formato binário. Siga a documentação associada para exemplos de uso e implantação.

|======
| Nome | Versão | Versão do Gráfico Helm | Local do artefato (URL/Imagem)
| SUSE Linux Micro | 6.1 (mais recente) | N/A | https://www.suse.com/download/sle-micro/[Página de download do SUSE Linux Micro] +
SL-Micro.x86_64-6.1-Base-SelfInstall-GM.install.iso (sha256 70b9be28f2d92bc3b228412e4fc2b1d5026e691874b728e530b8063522158854) +
SL-Micro.x86_64-6.1-Base-RT-SelfInstall-GM.install.iso (sha256 9ce83e4545d4b36c7c6a44f7841dc3d9c6926fe32dbff694832e0fbd7c496e9d) +
SL-Micro.x86_64-6.1-Base-GM.raw.xz (sha256 36e3efa55822113840dd76fdf6914e933a7b7e88a1dce5cb20c424ccf2fb4430) +
SL-Micro.x86_64-6.1-Base-RT-GM.raw.xz (sha256 2ee66735da3e1da107b4878e73ae68f5fb7309f5ec02b5dfdb94e254fda8415e) +
| SUSE Multi-Linux Manager | 5.0.5 | N/A | https://www.suse.com/download/suse-manager/[Página de download do SUSE Multi-Linux Manager]
| K3s | 1.33.5 | N/A | https://github.com/k3s-io/k3s/releases/tag/v1.33.5%2Bk3s1[Versão upstream do K3s]
| RKE2 | 1.33.5 | N/A | https://github.com/rancher/rke2/releases/tag/v1.33.5%2Brke2r1[Versão upstream do RKE2]
s| SUSE Rancher Prime s| 2.12.4 s| 2.12.4 | https://charts.rancher.com/server-charts/prime/index.yaml[Repositório Helm do Rancher Prime] +
\https://prime.ribs.rancher.io/rancher/v2.12.4/rancher-images.txt[Rancher 2.12.4 Container Images]
s| SUSE Storage (Longhorn) s| 1.9.2 s| 107.1.1+up1.9.2 | https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.suse.com/rancher/mirrored-longhornio-csi-attacher:v4.9.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-provisioner:v5.3.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-resizer:v1.14.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-snapshotter:v8.3.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-node-driver-registrar:v2.14.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-livenessprobe:v2.16.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-backing-image-manager:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-engine:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-instance-manager:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-manager:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-share-manager:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-ui:v1.9.2 +
registry.suse.com/rancher/mirrored-longhornio-support-bundle-kit:v0.0.61 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-cli:v1.9.2 +
s| SUSE Security s| 5.4.8 s| 107.0.3+up2.8.10 | https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.suse.com/rancher/neuvector-controller:5.4.8 +
registry.suse.com/rancher/neuvector-enforcer:5.4.8 +
registry.suse.com/rancher/neuvector-manager:5.4.8 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.9 +
registry.suse.com/rancher/neuvector-registry-adapter:0.1.8 +
registry.suse.com/rancher/neuvector-scanner:6 +
registry.suse.com/rancher/neuvector-updater:0.0.4
s| Rancher Turtles (CAPI) s| 0.24.3 s| 304.0.7+up0.24.3 | registry.suse.com/edge/charts/rancher-turtles:304.0.7_up0.24.3 +
registry.rancher.com/rancher/rancher/turtles:v0.24.3 +
registry.rancher.com/rancher/cluster-api-metal3-controller:v1.10.2 +
registry.rancher.com/rancher/cluster-api-metal3-ipam-controller:v1.10.2 +
registry.suse.com/rancher/cluster-api-controller:v1.10.5 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.20.1 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.20.1
s| Recursos de Airgap do Rancher Turtles s| 0.24.3 | 304.0.7+up0.24.3 | registry.suse.com/edge/charts/rancher-turtles-airgap-resources:304.0.7_up0.24.3
s| Metal^3^ s| 0.12.9 | 304.0.19+up0.12.9 | registry.suse.com/edge/charts/metal3:304.0.19_up0.12.9 +
registry.suse.com/edge/3.4/baremetal-operator:0.10.4 +
registry.suse.com/edge/3.4/ironic:29.0.4.4 +
registry.suse.com/edge/3.4/ironic-ipa-downloader:3.0.10 +
| MetalLB | 0.14.9 | 304.0.0+up0.14.9 | registry.suse.com/edge/charts/metallb:304.0.0_up0.14.9 +
registry.suse.com/edge/3.4/metallb-controller:v0.14.9 +
registry.suse.com/edge/3.4/metallb-speaker:v0.14.9 +
registry.suse.com/edge/3.4/frr:8.5.6 +
registry.suse.com/edge/3.4/frr-k8s:v0.0.16 +
registry.suse.com/edge/3.4/kube-rbac-proxy:0.18.1
| Elemental | 1.7.3 | 1.7.3 | registry.suse.com/rancher/elemental-operator-chart:1.7.3 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.7.3 +
registry.suse.com/rancher/elemental-operator:1.7.3
| Extensão do Painel Elemental | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/4.0.0/charts/elemental/3.0.1[Helm Chart da extensão Elemental]
s| Edge Image Builder s| 1.3.1 | N/A s| registry.suse.com/edge/3.4/edge-image-builder:1.3.1
s| NMConfigurator s| 0.3.5 | N/A s| https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.5[Lançamento do NMConfigurator upstream]
| KubeVirt | 1.5.2 | 304.0.1+up0.6.0 | registry.suse.com/edge/charts/kubevirt:304.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportproxy:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportserver:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.5.2
| Extensão do Painel KubeVirt | 1.3.2 | 304.0.3+up1.3.2 | registry.suse.com/edge/charts/kubevirt-dashboard-extension:304.0.3_up1.3.2
| Importador de Dados Conteinerizado | 1.62.0 | 304.0.1+up0.6.0 | registry.suse.com/edge/charts/cdi:304.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-importer:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-cloner:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.62.0
| Operador Endpoint Copier | 0.3.0 | 304.0.1+up0.3.0 | registry.suse.com/edge/charts/endpoint-copier-operator:304.0.1_up0.3.0 +
registry.suse.com/edge/3.4/endpoint-copier-operator:0.3.0
| Operador de Rede SR-IOV | 1.5.0 | 304.0.2+up1.5.0 | registry.suse.com/edge/charts/sriov-network-operator:304.0.2_up1.5.0 +
registry.suse.com/edge/charts/sriov-crd:304.0.2_up1.5.0
| Upgrade Controller | 0.16.0 | 107.0.0 | https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.suse.com/rancher/system-upgrade-controller:v0.16.0
| Upgrade Controller | 0.1.1 | 304.0.1+up0.1.1 | registry.suse.com/edge/charts/upgrade-controller:304.0.1_up0.1.1 +
registry.suse.com/edge/3.4/upgrade-controller:0.1.1 +
registry.suse.com/edge/3.4/kubectl:1.33.4 +
*registry.suse.com/edge/3.4/release-manifest:3.4.2*
s| Kiwi Builder s| 10.2.12.1 | N/A s| registry.suse.com/edge/3.4/kiwi-builder:10.2.12.1
|======

[#release-notes-3-4-1]
= Lançamento 3.4.1

Data de disponibilidade: 22 de outubro de 2025

Data de término do suporte completo: 20 de março de 2026

Data de término do suporte de manutenção: 20 de setembro de 2027

EOL: 21 de setembro de 2027

Resumo: O SUSE Edge 3.4.1 é o primeiro lançamento z-stream no fluxo de lançamento do SUSE Edge 3.4

== Novos recursos

* Atualizado para Kubernetes 1.33.5 e Rancher Prime 2.12.2 https://github.com/rancher/rancher/releases/tag/v2.12.2[Notas de Lançamento]
* Atualizado para SUSE Security (NeuVector) 5.4.6 https://open-docs.neuvector.com/releasenotes/5x/#546-august-2025[Notas de Lançamento]
* Atualizado para o SUSE Storage (Longhorn) 1.9.1 https://longhorn.io/docs/1.9.1/important-notes/[Notas de Lançamento]

== Correções de bug e segurança

* O SUSE Security (NeuVector) 5.4.6 contém várias correções de bug https://open-docs.neuvector.com/releasenotes/5x/#bugs-fixed[Correções de bug upstream do NeuVector]
* https://github.com/rancher/rke2/releases/tag/v1.33.5%2Brke2r1[RKE2 1.33.5] contém várias atualizações e correções, incluindo a resolução de um problema em certas implantações relacionado à afinidade de CPU https://github.com/opencontainers/runc/pull/4858[Problema upstream do runc]


== Problemas conhecidos

[WARNING]
====
Ao implantar novos clusters, siga <<guides-kiwi-builder-images>> para criar imagens novas primeiro, pois esta é agora a primeira etapa necessária para criar clusters para as arquiteturas {x86-64} e {aarch64}, bem como clusters de gerenciamento e downstream.
====

* Ao implantar via Edge Image Builder, os manifestos `HelmChartConfigs` podem falhar se forem colocados no diretório de configuração `kubernetes/manifests`. Em vez disso, recomenda-se colocar qualquer `HelmChartConfigs` em `/var/lib/rancher/{rke2/k3s}/server/manifests/` usando a interface os-files do EIB, consulte <<mgmt-cluster-directory-structure>> como exemplo.  A falha em fazer isso pode fazer com que os nós permaneçam no estado `NotReady` na inicialização inicial, conforme discutido em https://github.com/rancher/rke2/issues/8357[#8357 problema do RKE2]

* Nas versões RKE2/K3s 1.31, 1.32 e 1.33, o diretório `/etc/cni` usado para armazenar configurações de CNI pode não disparar uma notificação dos arquivos gravados para `containerd` devido a certas condições relacionadas ao `overlayfs` (consulte o https://github.com/rancher/rke2/issues/8356[#8356 problema do RKE2]). Isso, por sua vez, faz com que a implantação do RKE2/K3s fique travada aguardando a inicialização do CNI, e os nós do RKE2/K3s permaneçam no estado `NotReady`. Isso pode ser visto no nível do nó com `kubectl describe node <affected_node>`:

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

Como solução alternativa, um volume tmpfs pode ser montado no diretório `/etc/cni` antes que o RKE2 seja iniciado. Isso evita o uso de overlayfs, o que faz com que o containerd perca notificações, e as configurações devem ser reescritas toda vez que o nó for reiniciado e os initcontainers dos pods forem executados novamente. Se estiver usando o EIB, este pode ser um script `04-tmpfs-cni.sh` no diretório `custom/scripts` (conforme explicado aqui[https://github.com/suse-edge/edge-image-builder/blob/release-1.2/docs/building-images.md#custom]), que se parece com:

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* Ao integrar hosts remotos usando o Elemental, uma condição de corrida entre `dbus.service` e `elemental-system-agent.service` pode ocorrer, resultando na falha de inicialização do `rancher-system-agent.service` no host remoto com erros semelhantes ao abaixo. (consulte o https://github.com/suse-edge/edge-image-builder/issues/784[#784 problema do Edge Image Builder] para obter detalhes.)

[,bash]
----
Sep 19 19:38:07 elementalvm elemental-system-agent[3671]: time="2025-09-19T19:38:07Z" level=info msg="[6b20fe64c854da2639804884b34129bb8f718eb59578111da58d9de1509c24db_1:stderr]: Failed to restart rancher-system-agent.service: Message recipient disconnected from message bus without replying"
----

Como solução alternativa, um arquivo de override do systemd pode ser criado conforme abaixo

[,bash]
----
[Unit]
Wants=dbus.service network-online.target
After=dbus.service network-online.target time-sync.target

[Service]
ExecStartPre=/bin/bash -c 'echo "Waiting for dbus to become active..." | systemd-cat -p info -t elemental-system-agent; sleep 15; timeout 300 bash -c "while ! systemctl is-active --quiet dbus.service; do sleep 15; done"'
----

e um script personalizado chamado `30a-copy-elemental-system-agent-override.sh` pode ser usado para aplicar o override em `/etc/systemd/system/elemental-system-agent.service.d` antes que o script https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/templates/31-elemental-register.sh.tpl[31-elemental-register.sh] do EIB seja executado durante a fase de combustão.

[,bash]
----
#!/bin/bash

/bin/mkdir -p /etc/systemd/system/elemental-system-agent.service.d
/bin/cp -f elemental-system-agent-override.conf /etc/systemd/system/elemental-system-agent.service.d/override.conf
----

== Versões dos Componentes

A tabela a seguir descreve os componentes individuais que compõem a versão 3.4.1, incluindo a versão, a versão do gráfico Helm (se aplicável) e de onde o artefato lançado pode ser extraído no formato binário. Siga a documentação associada para exemplos de uso e implantação.

|======
| Nome | Versão | Versão do Gráfico Helm | Local do artefato (URL/Imagem)
| SUSE Linux Micro | 6.1 (mais recente) | N/A | https://www.suse.com/download/sle-micro/[Página de download do SUSE Linux Micro] +
SL-Micro.x86_64-6.1-Base-SelfInstall-GM.install.iso (sha256 70b9be28f2d92bc3b228412e4fc2b1d5026e691874b728e530b8063522158854) +
SL-Micro.x86_64-6.1-Base-RT-SelfInstall-GM.install.iso (sha256 9ce83e4545d4b36c7c6a44f7841dc3d9c6926fe32dbff694832e0fbd7c496e9d) +
SL-Micro.x86_64-6.1-Base-GM.raw.xz (sha256 36e3efa55822113840dd76fdf6914e933a7b7e88a1dce5cb20c424ccf2fb4430) +
SL-Micro.x86_64-6.1-Base-RT-GM.raw.xz (sha256 2ee66735da3e1da107b4878e73ae68f5fb7309f5ec02b5dfdb94e254fda8415e) +
| SUSE Multi-Linux Manager | 5.0.5 | N/A | https://www.suse.com/download/suse-manager/[Página de download do SUSE Multi-Linux Manager]
s| K3s s| 1.33.5 | N/A | https://github.com/k3s-io/k3s/releases/tag/v1.33.5%2Bk3s1[Versão upstream do K3s]
s| RKE2 s| 1.33.5 | N/A | https://github.com/rancher/rke2/releases/tag/v1.33.5%2Brke2r1[Versão upstream do RKE2]
s| SUSE Rancher Prime s| 2.12.2 s| 2.12.2 | https://charts.rancher.com/server-charts/prime/index.yaml[Repositório Helm do Rancher Prime] +
\https://github.com/rancher/rancher/releases/download/v2.12.2/rancher-images.txt[Imagens de contêiner do Rancher 2.12.2]
s| SUSE Storage (Longhorn) s| 1.9.1 s| 107.1.0+up1.9.1 | https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.suse.com/rancher/mirrored-longhornio-csi-attacher:v4.9.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-provisioner:v5.3.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-resizer:v1.14.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-snapshotter:v8.3.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-node-driver-registrar:v2.14.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-livenessprobe:v2.16.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-backing-image-manager:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-engine:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-instance-manager:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-manager:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-share-manager:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-ui:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-support-bundle-kit:v0.0.61 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-cli:v1.9.1 +
s| SUSE Security s| 5.4.6 s| 107.0.1+up2.8.8 | https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.suse.com/rancher/neuvector-controller:5.4.6 +
registry.suse.com/rancher/neuvector-enforcer:5.4.6 +
registry.suse.com/rancher/neuvector-manager:5.4.6 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.6 +
registry.suse.com/rancher/neuvector-registry-adapter:0.1.8 +
registry.suse.com/rancher/neuvector-scanner:6 +
registry.suse.com/rancher/neuvector-updater:0.0.4
| Rancher Turtles (CAPI) | 0.24.0 | 304.0.6+up0.24.0 | registry.suse.com/edge/charts/rancher-turtles:304.0.6_up0.24.0 +
registry.rancher.com/rancher/rancher/turtles:v0.24.0 +
registry.rancher.com/rancher/cluster-api-metal3-controller:v1.10.2 +
registry.rancher.com/rancher/cluster-api-metal3-ipam-controller:v1.10.2 +
registry.suse.com/rancher/cluster-api-controller:v1.10.5 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.20.1 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.20.1
| Recursos Airgap do Rancher Turtles | 0.24.0 | 304.0.6+up0.24.0 | registry.suse.com/edge/charts/rancher-turtles-airgap-resources:304.0.6_up0.24.0
| Metal^3^ | 0.11.5 | 304.0.16+up0.12.6 | registry.suse.com/edge/charts/metal3:304.0.16_up0.12.6 +
registry.suse.com/edge/3.4/baremetal-operator:0.10.2.1 +
registry.suse.com/edge/3.4/ironic:29.0.4.3 +
registry.suse.com/edge/3.4/ironic-ipa-downloader:3.0.9 +
registry.suse.com/edge/mariadb:10.6.15.1
| MetalLB | 0.14.9 | 304.0.0+up0.14.9 | registry.suse.com/edge/charts/metallb:304.0.0_up0.14.9 +
registry.suse.com/edge/3.4/metallb-controller:v0.14.9 +
registry.suse.com/edge/3.4/metallb-speaker:v0.14.9 +
registry.suse.com/edge/3.4/frr:8.5.6 +
registry.suse.com/edge/3.4/frr-k8s:v0.0.16 +
registry.suse.com/edge/3.4/kube-rbac-proxy:0.18.1
| Elemental | 1.7.3 | 1.7.3 | registry.suse.com/rancher/elemental-operator-chart:1.7.3 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.7.3 +
registry.suse.com/rancher/elemental-operator:1.7.3
| Extensão do Painel Elemental | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/4.0.0/charts/elemental/3.0.1[Helm Chart da Extensão Elemental]
| Edge Image Builder | 1.3.0 | N/A | registry.suse.com/edge/3.4/edge-image-builder:1.3.0
| NM Configurator | 0.3.3 | N/A | https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.3[Lançamento do NMConfigurator Upstream]
| KubeVirt | 1.5.2 | 304.0.1+up0.6.0 | registry.suse.com/edge/charts/kubevirt:304.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportproxy:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportserver:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.5.2
| Extensão do Painel KubeVirt | 1.3.2 | 304.0.3+up1.3.2 | registry.suse.com/edge/charts/kubevirt-dashboard-extension:304.0.3_up1.3.2
| Importador de Dados Conteinerizado | 1.62.0 | 304.0.1+up0.6.0 | registry.suse.com/edge/charts/cdi:304.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-importer:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-cloner:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.62.0
| Operador Endpoint Copier | 0.3.0 | 304.0.1+up0.3.0 | registry.suse.com/edge/charts/endpoint-copier-operator:304.0.1_up0.3.0 +
registry.suse.com/edge/3.4/endpoint-copier-operator:0.3.0
| Operador de Rede SR-IOV | 1.5.0 | 304.0.2+up1.5.0 | registry.suse.com/edge/charts/sriov-network-operator:304.0.2_up1.5.0 +
registry.suse.com/edge/charts/sriov-crd:304.0.2_up1.5.0
| Upgrade Controller | 0.16.0 | 107.0.0 | https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.suse.com/rancher/system-upgrade-controller:v0.16.0
| Upgrade Controller | 0.1.1 | 304.0.1+up0.1.1 | registry.suse.com/edge/charts/upgrade-controller:304.0.1_up0.1.1 +
registry.suse.com/edge/3.4/upgrade-controller:0.1.1 +
registry.suse.com/edge/3.4/kubectl:1.33.4 +
*registry.suse.com/edge/3.4/release-manifest:3.4.1*
| Kiwi Builder | 10.2.12.0 | N/A | registry.suse.com/edge/3.4/kiwi-builder:10.2.12.0
|======

[#release-notes-3-4-0]
= Versão 3.4.0

Data de disponibilidade: 24 de setembro de 2025

Data de término do suporte completo: 20 de março de 2026

Data de término do suporte de manutenção: 20 de setembro de 2027

EOL: 21 de setembro de 2027

Resumo: O SUSE Edge 3.4.0 é a primeira versão no fluxo de lançamento do SUSE Edge 3.4.

== Novos recursos

* Atualizado para Kubernetes 1.33 e Rancher Prime 2.12
* Versões atualizadas do Rancher Turtles, Cluster API e Metal3/Ironic
* Atualizado para o SUSE Storage (Longhorn) 1.9.1 https://longhorn.io/docs/1.9.1/[Notas de Lançamento]
* Uma implantação mais flexível de {aarch64} clusters downstream agora é possível por meio do fluxo de provisionamento de rede direcionado. Consulte o <<atip-automated-provisioning>> para obter mais detalhes.
* A implantação de clusters de pilha dupla (dual-stack) agora é totalmente suportada (o IPv6 de pilha única permanece em <<tech-previews>>)
* O modo BGP para MetalLB agora está disponível como uma prévia técnica; consulte <<tech-previews>> e <<guides-metallb-k3s-l3>> para obter mais detalhes.
* O Edge Image Builder foi atualizado para 1.3.0, consulte https://github.com/suse-edge/edge-image-builder/blob/release-1.3/RELEASE_NOTES.md[Notas de Lançamento do Upstream]

== Correções de bug e segurança

* O Rancher Prime 2.12 contém várias correções de bug https://github.com/rancher/rancher/releases/tag/v2.12.1[Notas de Lançamento do Rancher Upstream]
* O Rancher Prime 2.12 contém uma correção para problemas relacionados à AppVersion ao determinar a disponibilidade de atualização de extensão, o que impactou a operação com gráficos do Edge https://github.com/rancher/dashboard/issues/14204[Problema Upstream]
* O SUSE Storage (Longhorn) 1.9.1 contém várias correções de bug https://github.com/longhorn/longhorn/releases/tag/v1.9.1[Correções de bug do Longhorn Upstream]
* O gráfico Metal^3^ atualizado corrige um problema em que o MAC incorreto pode ser coletado para interface de vínculo durante a inspeção https://bugs.launchpad.net/ironic-python-agent/+bug/2103450[Problema do IPA Upstream]
* O gráfico Metal^3^ atualizado corrige um problema em que a implantação pode não ser reiniciada corretamente em atualizações de ConfigMap https://github.com/suse-edge/charts/issues/219[Problema Upstream]
* A atualização do Rancher Turtles inclui uma correção que resolve um problema em que as ownerReferences do MachineTemplate não eram aplicadas pelo provedor RKE2 CAPI https://github.com/rancher/cluster-api-provider-rke2/issues/500[Problema Upstream]

== Problemas conhecidos

[WARNING]
====
Ao implantar novos clusters, siga <<guides-kiwi-builder-images>> para criar imagens novas primeiro, pois esta é agora a primeira etapa necessária para criar clusters para as arquiteturas {x86-64} e {aarch64}, bem como clusters de gerenciamento e downstream.
====

* Ao implantar via Edge Image Builder, os manifestos `HelmChartConfigs` podem falhar se forem colocados no diretório de configuração `kubernetes/manifests`. Em vez disso, recomenda-se colocar qualquer `HelmChartConfigs` em `/var/lib/rancher/{rke2/k3s}/server/manifests/` usando a interface os-files do EIB, consulte <<mgmt-cluster-directory-structure>> como exemplo.  Falhar em fazer isso pode fazer com que os nós permaneçam no estado `NotReady` na inicialização inicial, conforme discutido em https://github.com/rancher/rke2/issues/8357[#8357 problema do RKE2].

* Nas versões RKE2/K3s 1.31, 1.32 e 1.33, o diretório `/etc/cni` usado para armazenar configurações de CNI pode não disparar uma notificação dos arquivos gravados para `containerd` devido a certas condições relacionadas ao `overlayfs` (consulte o https://github.com/rancher/rke2/issues/8356[#8356 problema do RKE2]). Isso, por sua vez, faz com que a implantação do RKE2/K3s fique travada aguardando a inicialização do CNI, e os nós do RKE2/K3s permaneçam no estado `NotReady`. Isso pode ser visto no nível do nó com `kubectl describe node <affected_node>`:

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

Como solução alternativa, um volume tmpfs pode ser montado no diretório `/etc/cni` antes que o RKE2 seja iniciado. Isso evita o uso de overlayfs, o que faz com que o containerd perca notificações, e as configurações devem ser reescritas toda vez que o nó for reiniciado e os initcontainers dos pods forem executados novamente. Se estiver usando o EIB, este pode ser um script `04-tmpfs-cni.sh` no diretório `custom/scripts` (conforme explicado aqui[https://github.com/suse-edge/edge-image-builder/blob/release-1.2/docs/building-images.md#custom]) que se parece com:

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* Ao integrar hosts remotos usando o Elemental, uma condição de corrida entre `dbus.service` e `elemental-system-agent.service` pode ocorrer, resultando na falha de inicialização do `rancher-system-agent.service` no host remoto com erros semelhantes ao abaixo. (consulte o https://github.com/suse-edge/edge-image-builder/issues/784[#784 problema do Edge Image Builder] para obter detalhes.)

[,bash]
----
Sep 19 19:38:07 elementalvm elemental-system-agent[3671]: time="2025-09-19T19:38:07Z" level=info msg="[6b20fe64c854da2639804884b34129bb8f718eb59578111da58d9de1509c24db_1:stderr]: Failed to restart rancher-system-agent.service: Message recipient disconnected from message bus without replying"
----

Como solução alternativa, um arquivo de substituição do systemd pode ser criado conforme abaixo

[,bash]
----
[Unit]
Wants=dbus.service network-online.target
After=dbus.service network-online.target time-sync.target

[Service]
ExecStartPre=/bin/bash -c 'echo "Waiting for dbus to become active..." | systemd-cat -p info -t elemental-system-agent; sleep 15; timeout 300 bash -c "while ! systemctl is-active --quiet dbus.service; do sleep 15; done"'
----

e um script personalizado chamado `30a-copy-elemental-system-agent-override.sh` pode ser usado para colocar a substituição em `/etc/systemd/system/elemental-system-agent.service.d` antes que o script https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/templates/31-elemental-register.sh.tpl[31-elemental-register.sh] do EIB seja executado durante a fase de combustão.

[,bash]
----
#!/bin/bash

/bin/mkdir -p /etc/systemd/system/elemental-system-agent.service.d
/bin/cp -f elemental-system-agent-override.conf /etc/systemd/system/elemental-system-agent.service.d/override.conf
----

== Versões dos Componentes

A tabela a seguir descreve os componentes individuais que compõem a versão 3.4.0, incluindo a versão, a versão do gráfico Helm (se aplicável) e de onde o artefato lançado pode ser extraído no formato binário. Siga a documentação associada para exemplos de uso e implantação.

|======
| Nome | Versão | Versão do Gráfico Helm | Local do artefato (URL/Imagem)
| SUSE Linux Micro | 6.1 (mais recente) | N/A | https://www.suse.com/download/sle-micro/[Página de download do SUSE Linux Micro] +
SL-Micro.x86_64-6.1-Base-SelfInstall-GM.install.iso (sha256 70b9be28f2d92bc3b228412e4fc2b1d5026e691874b728e530b8063522158854) +
SL-Micro.x86_64-6.1-Base-RT-SelfInstall-GM.install.iso (sha256 9ce83e4545d4b36c7c6a44f7841dc3d9c6926fe32dbff694832e0fbd7c496e9d) +
SL-Micro.x86_64-6.1-Base-GM.raw.xz (sha256 36e3efa55822113840dd76fdf6914e933a7b7e88a1dce5cb20c424ccf2fb4430) +
SL-Micro.x86_64-6.1-Base-RT-GM.raw.xz (sha256 2ee66735da3e1da107b4878e73ae68f5fb7309f5ec02b5dfdb94e254fda8415e) +
| SUSE Multi-Linux Manager | 5.0.5 | N/A | https://www.suse.com/download/suse-manager/[Página de download do SUSE Multi-Linux Manager]
| K3s | 1.33.3 | N/A | https://github.com/k3s-io/k3s/releases/tag/v1.33.3%2Bk3s1[Versão upstream do K3s]
| RKE2 | 1.33.3 | N/A | https://github.com/rancher/rke2/releases/tag/v1.33.3%2Brke2r1[Versão upstream do RKE2]
| SUSE Rancher Prime | 2.12.1 | 2.12.1 | https://charts.rancher.com/server-charts/prime/index.yaml[Repositório Helm do Rancher Prime] +
\https://github.com/rancher/rancher/releases/download/v2.12.1/rancher-images.txt[Imagens de contêiner do Rancher 2.12.1]
| SUSE Storage (Longhorn) | 1.9.1 | 107.0.0+up1.9.1 | https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.suse.com/rancher/mirrored-longhornio-csi-attacher:v4.9.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-provisioner:v5.3.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-resizer:v1.14.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-snapshotter:v8.3.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-csi-node-driver-registrar:v2.14.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-livenessprobe:v2.16.0-20250709 +
registry.suse.com/rancher/mirrored-longhornio-backing-image-manager:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-engine:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-instance-manager:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-manager:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-share-manager:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-ui:v1.9.1 +
registry.suse.com/rancher/mirrored-longhornio-support-bundle-kit:v0.0.61 +
registry.suse.com/rancher/mirrored-longhornio-longhorn-cli:v1.9.1 +
| SUSE Security | 5.4.5 | 107.0.0+up2.8.7 | https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.suse.com/rancher/neuvector-controller:5.4.5 +
registry.suse.com/rancher/neuvector-enforcer:5.4.5 +
registry.suse.com/rancher/neuvector-manager:5.4.5 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.6 +
registry.suse.com/rancher/neuvector-registry-adapter:0.1.8 +
registry.suse.com/rancher/neuvector-scanner:6 +
registry.suse.com/rancher/neuvector-updater:0.0.4
| Rancher Turtles (CAPI) | 0.24.0 | 304.0.6+up0.24.0 | registry.suse.com/edge/charts/rancher-turtles:304.0.6_up0.24.0 +
registry.rancher.com/rancher/rancher/turtles:v0.24.0 +
registry.rancher.com/rancher/cluster-api-metal3-controller:v1.10.2 +
registry.rancher.com/rancher/cluster-api-metal3-ipam-controller:v1.10.2 +
registry.suse.com/rancher/cluster-api-controller:v1.10.5 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.20.1 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.20.1
| Recursos de Airgap do Rancher Turtles | 0.24.0 | 304.0.6+up0.24.0 | registry.suse.com/edge/charts/rancher-turtles-airgap-resources:304.0.6_up0.24.0
| Metal^3^ | 0.11.5 | 304.0.16+up0.12.6 | registry.suse.com/edge/charts/metal3:304.0.16_up0.12.6 +
registry.suse.com/edge/3.4/baremetal-operator:0.10.2.1 +
registry.suse.com/edge/3.4/ironic:29.0.4.3 +
registry.suse.com/edge/3.4/ironic-ipa-downloader:3.0.9 +
registry.suse.com/edge/mariadb:10.6.15.1
| MetalLB | 0.14.9 | 304.0.0+up0.14.9 | registry.suse.com/edge/charts/metallb:304.0.0_up0.14.9 +
registry.suse.com/edge/3.4/metallb-controller:v0.14.9 +
registry.suse.com/edge/3.4/metallb-speaker:v0.14.9 +
registry.suse.com/edge/3.4/frr:8.5.6 +
registry.suse.com/edge/3.4/frr-k8s:v0.0.16 +
registry.suse.com/edge/3.4/kube-rbac-proxy:0.18.1
| Elemental | 1.7.3 | 1.7.3 | registry.suse.com/rancher/elemental-operator-chart:1.7.3 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.7.3 +
registry.suse.com/rancher/elemental-operator:1.7.3
| Extensão do Painel Elemental | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/4.0.0/charts/elemental/3.0.1[Helm Chart da Extensão Elemental]
| Edge Image Builder | 1.3.0 | N/A | registry.suse.com/edge/3.4/edge-image-builder:1.3.0
| NM Configurator | 0.3.3 | N/A | https://github.com/suse-edge/nm-configurator/releases/tag/v0.3.3[Lançamento do NMConfigurator Upstream]
| KubeVirt | 1.5.2 | 304.0.1+up0.6.0 | registry.suse.com/edge/charts/kubevirt:304.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportproxy:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-exportserver:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.5.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.5.2
| Extensão do Painel KubeVirt | 1.3.2 | 304.0.3+up1.3.2 | registry.suse.com/edge/charts/kubevirt-dashboard-extension:304.0.3_up1.3.2
| Importador de Dados Conteinerizado | 1.62.0 | 304.0.1+up0.6.0 | registry.suse.com/edge/charts/cdi:304.0.1_up0.6.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-importer:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-cloner:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadserver:1.62.0 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.62.0
| Operador Endpoint Copier | 0.3.0 | 304.0.1+up0.3.0 | registry.suse.com/edge/charts/endpoint-copier-operator:304.0.1_up0.3.0 +
registry.suse.com/edge/3.4/endpoint-copier-operator:0.3.0
| Akri (Descontinuado) | 0.12.20 | 304.0.0+up0.12.20 | registry.suse.com/edge/charts/akri:304.0.0_up0.12.20 +
registry.suse.com/edge/charts/akri-dashboard-extension:304.0.0_up1.3.1 +
registry.suse.com/edge/3.4/akri-agent:v0.12.20 +
registry.suse.com/edge/3.4/akri-controller:v0.12.20 +
registry.suse.com/edge/3.4/akri-debug-echo-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.4/akri-onvif-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.4/akri-opcua-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.4/akri-udev-discovery-handler:v0.12.20 +
registry.suse.com/edge/3.4/akri-webhook-configuration:v0.12.20
| Operador de Rede SR-IOV | 1.5.0 | 304.0.2+up1.5.0 | registry.suse.com/edge/charts/sriov-network-operator:304.0.2_up1.5.0 +
registry.suse.com/edge/charts/sriov-crd:304.0.2_up1.5.0
| Upgrade Controller | 0.16.0 | 107.0.0 | https://charts.rancher.io/index.yaml[Repositório Helm de Charts do Rancher] +
registry.suse.com/rancher/system-upgrade-controller:v0.16.0
| Upgrade Controller | 0.1.1 | 304.0.1+up0.1.1 | registry.suse.com/edge/charts/upgrade-controller:304.0.1_up0.1.1 +
registry.suse.com/edge/3.4/upgrade-controller:0.1.1 +
registry.suse.com/edge/3.4/kubectl:1.33.4 +
registry.suse.com/edge/3.4/release-manifest:3.4.0
| Kiwi Builder | 10.2.12.0 | N/A | registry.suse.com/edge/3.4/kiwi-builder:10.2.12.0
|======

= Recursos descontinuados

Salvo indicação em contrário, estes se aplicam à versão 3.4.0 e a todas as versões z-stream subsequentes.

* O Akri era uma oferta de Technology Preview em versões anteriores do Edge e agora está descontinuado.  A remoção está planejada para uma versão futura.

[#tech-previews]
= Prévias de tecnologia

Salvo indicação em contrário, estes se aplicam à versão 3.4.0 e a todas as versões z-stream subsequentes.

* Implantações IPv6 de pilha única são uma oferta de Technology Preview e não estão sujeitas ao escopo padrão de suporte.
* O Precision Time Protocol (PTP) em implantações downstream é uma oferta de Technology Preview e não está sujeito ao escopo padrão de suporte.
* O modo BGP para MetalLB é uma oferta de Technology Preview e não está sujeito ao escopo padrão de suporte.

= Verificação de componentes

Os componentes mencionados acima podem ser verificados usando os dados da Lista de Materiais de Software (SBOM) - por exemplo, usando `cosign` conforme descrito abaixo:

Baixe a chave pública do contêiner SUSE Edge da https://www.suse.com/support/security/keys/[fonte de chaves de assinatura da SUSE]:

[,bash]
----
include::key.sh[]
----

Verifique o hash da imagem do contêiner, por exemplo, usando `crane`:

[,bash]
----
> crane digest registry.suse.com/edge/3.4/baremetal-operator:0.10.2.1 --platform linux/amd64
sha256:310d939f8ae4b547710195b9671a4e9ff417420c0856103dd728b051788b5374
----

NOTE: Para imagens multi-arquitetura, também é necessário especificar uma plataforma ao obter o digest, por exemplo, `--platform linux/amd64` ou `--platform linux/arm64`. A falha em fazer isso resultará em um erro na etapa a seguir (`Error: no matching attestations`).

Verifique com `cosign`:

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/3.4/baremetal-operator@sha256:310d939f8ae4b547710195b9671a4e9ff417420c0856103dd728b051788b5374 > /dev/null
#
Verification for registry.suse.com/edge/3.4/baremetal-operator@sha256:310d939f8ae4b547710195b9671a4e9ff417420c0856103dd728b051788b5374 --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - The signatures were verified against the specified public key
----

Extraia os dados da SBOM conforme descrito na https://www.suse.com/support/security/sbom/[documentação da SBOM da SUSE]:

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/3.4/baremetal-operator@sha256:310d939f8ae4b547710195b9671a4e9ff417420c0856103dd728b051788b5374 | jq '.payload | @base64d | fromjson | .predicate'
----

= Etapas de Atualização

Consulte o <<day-2-operations>> para obter detalhes sobre como fazer upgrade para uma nova versão.

= Ciclo de vida de suporte de produtos

O SUSE Edge conta com o suporte premiado da SUSE, uma líder tecnológica estabelecida com um histórico comprovado de entrega de serviços de suporte com qualidade empresarial. Para mais informações, consulte https://www.suse.com/lifecycle[https://www.suse.com/lifecycle] e a página da Política de Suporte em https://www.suse.com/support/policy.html[https://www.suse.com/support/policy.html]. Se você tiver alguma dúvida sobre como abrir um caso de suporte, como a SUSE classifica os níveis de severidade ou o escopo do suporte, consulte o Manual de Suporte Técnico em https://www.suse.com/support/handbook/[https://www.suse.com/support/handbook/].

O SUSE Edge \"3.4\" é suportado por 24 meses de suporte de produção, com 6 meses iniciais de \"suporte completo\", seguidos por 18 meses de \"suporte de manutenção\".  Após essas fases de suporte, o produto atinge o "fim do serviço" (EOL) e não é mais suportado. Mais informações sobre as fases do ciclo de vida podem ser encontradas na tabela abaixo:

|======
| *Suporte Completo (6 meses)* | Correções de bugs urgentes e de alta prioridade selecionadas serão lançadas durante a janela de suporte completo, e todos os outros patches (não urgentes, melhorias, novos recursos) serão lançados por meio do cronograma de lançamento regular.
| *Suporte de Manutenção (18 meses)* | Durante este período, apenas correções críticas serão lançadas por meio de patches. Outras correções de bugs podem ser lançadas a critério da SUSE, mas não devem ser esperadas.
| *Fim do Serviço (EOL)*  | Assim que uma versão de produto atinge sua data de Fim do Serviço (EOL), o cliente pode continuar a usar o produto dentro dos termos do contrato de licenciamento do produto.
Os Planos de Suporte da SUSE não se aplicam a versões de produtos após sua data de EOL.
|======

A menos que explicitamente declarado, todos os componentes listados são considerados Geralmente Disponíveis (GA) e são cobertos pelo escopo padrão de suporte da SUSE. Alguns componentes podem ser listados como "Technology Preview", onde a SUSE fornece aos clientes acesso a recursos e funcionalidades pré-GA iniciais para avaliação, mas não estão sujeitos às políticas de suporte padrão e não são recomendados para casos de uso em produção. A SUSE aceita muito bem comentários e sugestões sobre as melhorias que podem ser feitas nos componentes de Technology Preview, mas a SUSE reserva-se o direito de descontinuar um recurso de Technology Preview antes que ele se torne Geralmente Disponível se ele não atender às necessidades de nossos clientes ou não atingir um estado de maturidade que exigimos.

Observe que a SUSE deve ocasionalmente descontinuar recursos ou alterar especificações de API. Os motivos para a descontinuação de recursos ou alteração de API podem incluir um recurso sendo atualizado ou substituído por uma nova implementação, um novo conjunto de recursos, a tecnologia upstream não estar mais disponível ou a comunidade upstream ter introduzido alterações incompatíveis. Não se pretende que isso aconteça dentro de uma determinada versão secundária (x.z), portanto, todas as versões z-stream manterão a compatibilidade de API e a funcionalidade de recursos. A SUSE se esforçará para fornecer avisos de descontinuação com bastante antecedência nas notas de versão, juntamente com soluções alternativas, sugestões e mitigações para minimizar a interrupção do serviço.

A equipe do SUSE Edge também aceita comentários da comunidade, onde problemas podem ser levantados no respectivo repositório de código dentro de https://www.github.com/suse-edge[https://www.github.com/suse-edge].

= Obtenção de código-fonte

Este produto SUSE inclui materiais licenciados para a SUSE sob a GNU General Public License (GPL) e várias outras licenças de código aberto. A GPL exige que a SUSE forneça o código-fonte que corresponde ao material licenciado pela GPL e que a SUSE esteja em conformidade com todos os outros requisitos de licença de código aberto. Como tal, a SUSE disponibiliza todo o código-fonte, que geralmente pode ser encontrado no repositório GitHub do SUSE Edge (https://www.github.com/suse-edge[https://www.github.com/suse-edge]), no repositório GitHub do SUSE Rancher (https://www.github.com/rancher[https://www.github.com/rancher]) para componentes dependentes e, especificamente, para o SUSE Linux Micro, o código-fonte está disponível para download em https://www.suse.com/download/sle-micro/[https://www.suse.com/download/sle-micro] em "Medium 2".

= Informações legais

A SUSE não faz representações ou garantias quanto ao conteúdo ou à utilização desta documentação e, especificamente, isenta-se de quaisquer garantias explícitas ou implícitas de comerciabilidade ou adequação a qualquer propósito específico. Além disso, a SUSE reserva-se o direito de revisar esta publicação e de fazer mudanças em seu conteúdo a qualquer momento, sem a obrigação de notificar qualquer pessoa ou entidade sobre essas revisões ou mudanças.

Além disso, a SUSE não faz representações ou garantias quanto a qualquer software e, especificamente, isenta-se de quaisquer garantias explícitas ou implícitas de comerciabilidade ou adequação a qualquer propósito específico. Além disso, a SUSE reserva-se o direito de fazer mudanças em qualquer parte do software SUSE, a qualquer momento, sem a obrigação de notificar qualquer pessoa ou entidade sobre essas mudanças.

Todos os produtos ou as informaçőes técnicas fornecidas neste Contrato podem estar sujeitas aos controles de exportação dos Estados Unidos e ŕs leis de comércio de outros países. Você concorda em obedecer a todos os regulamentos de controle de exportação e em obter quaisquer licenças ou classificações necessárias para exportar, reexportar ou importar produtos. Você concorda em não exportar ou reexportar para entidades nas listas de exclusão de exportação atuais dos Estados Unidos ou para países sob embargo ou considerados terroristas, conforme especificado nas leis de exportação dos Estados Unidos. Você concorda em não usar entregáveis para fins proibidos relacionados a armas nucleares, mísseis ou armamentos químicos/biológicos. Consulte https://www.suse.com/company/legal/[https://www.suse.com/company/legal/] para obter mais informações sobre a exportação do software SUSE. A SUSE não assume qualquer responsabilidade caso você não obtenha as aprovações necessárias para exportação.

*Copyright © 2024 SUSE LLC.*

Este documento de notas de versão está licenciado sob uma Licença Creative Commons Atribuição-SemDerivações 4.0 Internacional (CC-BY-ND-4.0). Você deve ter recebido uma cópia da licença juntamente com este documento. Caso não tenha recebido, consulte https://creativecommons.org/licenses/by-nd/4.0/[https://creativecommons.org/licenses/by-nd/4.0/].

A SUSE possui direitos de propriedade intelectual relacionados à tecnologia incorporada ao produto descrito neste documento. Em particular, e sem limitações, esses direitos de propriedade intelectual podem incluir uma ou mais patentes dos EUA listadas em https://www.suse.com/company/legal/[https://www.suse.com/company/legal/] e uma ou mais patentes adicionais ou pedidos de patentes pendentes nos EUA e em outros países.

Para marcas registradas da SUSE, consulte a lista de Marcas Registradas e Marcas de Serviço da SUSE (https://www.suse.com/company/legal/[https://www.suse.com/company/legal/]). Todas as marcas registradas de terceiros pertencem aos seus respectivos proprietários. Para obter informações sobre a marca SUSE e requisitos de uso, consulte as diretrizes publicadas em https://brand.suse.com/[https://brand.suse.com/].
