[#release-notes]

= Resumen
:revdate: 2026-06-29
:revnumber: 3.6
:page-revdate: {revdate}
ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

{product} 3.6 es una solución integral, estrechamente integrada y exhaustivamente validada para abordar los desafíos únicos del despliegue de infraestructura y aplicaciones nativas de nube en edge. Su objetivo principal es proporcionar una plataforma con lineamientos predefinidos, pero altamente flexible, escalable y segura que abarca la creación de imágenes para el despliegue inicial, el aprovisionamiento e incorporación de nodos, el despliegue de aplicaciones, la observabilidad y la gestión del ciclo de vida.

La solución está diseñada con la idea de que no existe una plataforma edge única debido a los requisitos y expectativas muy variados de nuestros clientes. Los despliegues en edge nos empujan a resolver, y a evolucionar continuamente, algunos de los problemas más desafiantes, incluyendo la escalabilidad masiva, la disponibilidad de red restringida, las limitaciones de espacio físico, las nuevas amenazas de seguridad y vectores de ataque, las variaciones en la arquitectura de hardware y los recursos del sistema, el requisito de desplegar e interactuar con infraestructura y aplicaciones heredadas, y las soluciones de los clientes que tienen una vida útil prolongada.

{product} se ha creado desde cero con el mejor software de código abierto, en consonancia tanto con nuestros 30 años de historia ofreciendo plataformas SUSE Linux seguras, estables y certificadas, como con nuestra experiencia proporcionando una gestión de Kubernetes altamente escalable y rica en funciones con nuestra cartera Rancher. {product} se basa en estas capacidades para ofrecer una funcionalidad que puede abordar un gran número de segmentos de mercado, incluyendo el comercio minorista, la medicina, el transporte, la logística, las telecomunicaciones, la fabricación inteligente y el IoT industrial.

Para obtener más información sobre las actualizaciones del ciclo de vida de soporte del producto para {product}, consulte link:https://www.suse.com/lifecycle/#suse-edge-36[Product Support Lifecycle].

NOTE: SUSE Telco Cloud es un derivado de SUSE Edge, con optimizaciones y componentes adicionales que permiten a la plataforma abordar los requisitos que se encuentran en los casos de uso de telecomunicaciones.

= Acerca de

Estas notas de la versión son, a menos que se especifique y explique explícitamente, idénticas en todas las arquitecturas, y la versión más reciente, junto con las notas de la versión de todos los demás productos de SUSE, están siempre disponibles en línea en https://www.suse.com/releasenotes[https://www.suse.com/releasenotes].

Las entradas solo se enumeran una vez, pero pueden referenciarse en varios lugares si son importantes y pertenecen a más de una sección. Las notas de la versión suelen enumerar solo los cambios que se produjeron entre dos versiones consecutivas. Ciertas entradas importantes de las notas de la versión de versiones anteriores del producto pueden repetirse. Para facilitar la identificación de estas entradas, contienen una nota al respecto.

Sin embargo, las entradas repetidas se proporcionan solo por cortesía. Por lo tanto, si se salta una o más versiones, consulte también las notas de la versión de las versiones omitidas. Si solo lee las notas de la versión actual, podría pasar por alto cambios importantes que pueden afectar al comportamiento del sistema. Las versiones de {product} se definen como x.y.z, donde 'x' denota la versión principal, 'y' denota la versión menor y 'z' denota la versión de parche, también conocida como "z-stream". Los ciclos de vida del producto {product} se definen en torno a una versión menor determinada, p. ej. "3.6", pero se distribuyen con parches posteriores a lo largo de su ciclo de vida, p. ej. "3.6.1".

NOTE: {product} Las versiones z-stream están estrechamente integradas y probadas exhaustivamente como una pila versionada. La actualización de cualquier componente individual a versiones diferentes a las enumeradas anteriormente probablemente resulte en tiempo de inactividad del sistema. Aunque es posible ejecutar clústeres Edge en configuraciones no probadas, no se recomienda y puede llevar más tiempo proporcionar una resolución a través de los canales de soporte.

[#release-notes-3-6-1]
= Versión 3.6.1

Fecha de disponibilidad: 26 de junio de 2026

Fecha de finalización del soporte completo: 27 de noviembre de 2026

Fecha de finalización del soporte de mantenimiento: 27 de mayo de 2028

EOL: 28 de mayo de 2028

Resumen: {product} 3.6.1 es la primera versión z-stream en el flujo de versiones {product} 3.6.

== Nuevas funciones

* Actualizado a Kubernetes 1.35.4 y Rancher Prime 2.14.2
* Actualizado a SUSE Security (NeuVector) 5.5.2 https://open-docs.neuvector.com/releasenotes/5x[Notas de la versión de NeuVector]
* Actualizado a SUSE Storage (Longhorn) 1.11.2 https://longhorn.io/docs/1.11.1/[Notas de la versión de Longhorn ascendente]
* Actualizado a Rancher Turtles (CAPI) 0.26.2 https://turtles.docs.rancher.com/[Documentación de Rancher Turtles]
* Actualizado Metal^3^/Ironic a 0.15.0 con Ironic 35.0.0.2

== Corrección de fallos y actualizaciones de seguridad

* Kubernetes 1.35.4 contiene varias correcciones de fallos y actualizaciones de seguridad https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.35.md[Registro de cambios de Kubernetes]
* Rancher Prime 2.14.2 contiene varias correcciones de fallos https://github.com/rancher/rancher/releases/tag/v2.14.1[Notas de la versión de Rancher ascendentes]
* SUSE Storage (Longhorn) 1.11.2 contiene varias correcciones de fallos https://github.com/longhorn/longhorn/releases/tag/v1.11.1[Correcciones de fallos de Longhorn ascendentes]
* NeuVector 5.5.2 contiene nuevas funciones y varias correcciones de fallos https://open-docs.neuvector.com/releasenotes/5x[Notas de la versión de NeuVector]
* Las actualizaciones de Metal^3^/Ironic corrigen varios fallos y problemas de seguridad, incluidos los siguientes:
** https://www.cve.org/CVERecord?id=CVE-2026-44919[CVE-2026-44919]
** https://www.cve.org/CVERecord?id=CVE-2026-46447[CVE-2026-46447]
** https://www.cve.org/CVERecord?id=CVE-2026-48681[CVE-2026-48681]
** https://www.cve.org/CVERecord?id=CVE-2026-44917[CVE-2026-44917]
** https://www.cve.org/CVERecord?id=CVE-2026-43003[CVE-2026-43003]
** https://www.cve.org/CVERecord?id=CVE-2026-50589[CVE-2026-50589]

== Problemas conocidos

[WARNING]
====
Si va a desplegar nuevos clústeres, siga <<guides-kiwi-builder-images>> para crear primero imágenes nuevas.  Esto se recomienda para los clústeres de gestión y descendentes a fin de garantizar que las imágenes contengan las últimas correcciones de seguridad y de fallos.
====

* Al realizar el despliegue a través de Edge Image Builder, los manifiestos `HelmChartConfigs` pueden fallar si se colocan en el directorio de configuración `kubernetes/manifests`. En su lugar, se recomienda colocar cualquier `HelmChartConfigs` en `/var/lib/rancher/{rke2/k3s}/server/manifests/` utilizando la interfaz os-files de EIB.
ifeval::["{flavor}" == "telco"]
Consulte <<mgmt-cluster-directory-structure>> para ver un ejemplo.
endif::[]
Si no se hace esto, los nodos podrían permanecer en estado `NotReady` durante el inicio inicial, tal como se comenta en https://github.com/rancher/rke2/issues/8357[#8357 RKE2 issue].

* En las versiones 1.34 y 1.35 de RKE2/K3s, es posible que el directorio `/etc/cni` utilizado para almacenar las configuraciones de CNI no notifique a `containerd` cuando se escriben archivos en él debido a ciertas condiciones relacionadas con `overlayfs` (véase el https://github.com/rancher/rke2/issues/8356[#8356 RKE2 issue]). Esto, a su vez, provoca que el despliegue de RKE2/K3s se quede bloqueado esperando a que se inicie la CNI y que los nodos de RKE2/K3s permanezcan en estado `NotReady`. Esto puede observarse a nivel de nodo con `kubectl describe node <affected_node>`:

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

Como solución alternativa, se puede montar un volumen tmpfs en el directorio `/etc/cni` antes de que se inicie RKE2. Esto evita el uso de overlayfs, que provoca que containerd no reciba notificaciones, y las configuraciones deberían reescribirse cada vez que se reinicie el nodo y se vuelvan a ejecutar los initcontainers de los pods. Si utiliza EIB, puede tratarse de un script `04-tmpfs-cni.sh` en el directorio `custom/scripts` (como se explica https://github.com/suse-edge/edge-image-builder/blob/release-1.3/docs/building-images.md#custom[aquí]) que tenga el siguiente aspecto:

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* En este momento no hay documentación oficial ni ejemplos disponibles para configurar SyncE mediante synce4l y GNSS mediante gpsd; estos temas se tratarán en futuras versiones.

* Algunos repositorios de contenedores solo son accesibles actualmente a través de IPv4; por este motivo, se requiere un repositorio local en el clúster de gestión para un clúster de sentido descendente que solo utilice IPv6.

== Versiones de los componentes

La siguiente tabla describe los componentes individuales que conforman la versión 3.6.1, incluyendo la versión, la versión del gráfico de Helm (si procede) y desde dónde se puede extraer el artefacto publicado en formato binario. Siga la documentación asociada para ver ejemplos de uso y despliegue.

|======
| Nombre | Versión | Versión del gráfico de Helm | Ubicación del artefacto (URL/Imagen)
| SUSE Linux Micro | 6.2 (el más reciente) | N/D | https://www.suse.com/download/sle-micro/[Página de descarga de SUSE Linux Micro] +
| SUSE Linux Micro | 6.2 (el más reciente) | N/D |Las sumas de comprobación y las firmas están disponibles para su descarga en https://www.suse.com/download/sle-micro/[Página de descarga de SUSE Linux Micro] +
SL-Micro.x86_64-6.2-Base-SelfInstall-GM.install.iso +
SL-Micro.x86_64-6.2-Base-RT-SelfInstall-GM.install.iso +
SL-Micro.x86_64-6.2-Base-GM.raw.xz +
SL-Micro.x86_64-6.2-Base-RT-GM.raw.xz +
| SUSE Multi-Linux Manager | 5.1 | N/D | https://www.suse.com/download/suse-manager/[Página de descarga de SUSE Multi-Linux Manager]
s| K3s s| 1.35.4 s| N/D s| https://github.com/k3s-io/k3s/releases/tag/v1.35.4%2Bk3s1[Versión de K3s de sentido ascendente]
s| RKE2 s| 1.35.4 s| N/D s| https://github.com/rancher/rke2/releases/tag/v1.35.4%2Brke2r1[Versión upstream de RKE2]
s| SUSE Rancher Prime s| 2.14.2 s| 2.14.2 s| https://charts.rancher.com/server-charts/prime/index.yaml[Repositorio de Helm de Rancher Prime] +
\https://prime.ribs.rancher.io/rancher/v2.14.2/rancher-images.txt[Rancher 2.14.2 Container Images]
s| SUSE Storage (Longhorn) s| 1.11.2 s| 1.11.2 s| https://apps.rancher.io/applications/suse-storage[Repositorio de Helm de SUSE Storage] +
\https://apps.rancher.io/applications/suse-storage/components[SUSE Storage Container Images]
s| SUSE Security (NeuVector) s| 5.5.2 s| 109.0.2+up2.10.2 s| https://charts.rancher.io/index.yaml[Repositorio de Helm de Rancher Charts] +
registry.rancher.com/rancher/neuvector-controller:5.5.2 +
registry.rancher.com/rancher/neuvector-enforcer:5.5.2 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.12
s| Proveedores de Rancher Turtles (CAPI) s| 0.26.2 s| 306.0.7+up0.26.2 s| registry.suse.com/edge/3.6/rancher-turtles-providers-chart:306.0.7+up0.26.2 +
registry.rancher.com/rancher/cluster-api-controller:v1.12.2 +
registry.rancher.com/rancher/turtles:v0.26.2 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.24.3 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.24.3
s| Metal^3^ s| 0.15.0 s| 306.0.29+up0.15.0 s| registry.suse.com/edge/3.6/metal3-chart:306.0.29+up0.15.0 +
registry.suse.com/edge/3.6/baremetal-operator:0.12.3.0 +
registry.suse.com/edge/3.6/ironic:35.0.0.2 +
registry.suse.com/edge/3.6/ironic-ipa-downloader:3.1.1 +
registry.suse.com/edge/3.6/ironic-python-agent:3.0.9
| MetalLB | 0.15.3 | 306.0.2+up0.15.3 | registry.suse.com/edge/3.6/metallb-chart:306.0.2+up0.15.3 +
registry.suse.com/edge/3.6/metallb-controller:v0.15.3 +
registry.suse.com/edge/3.6/metallb-speaker:v0.15.3
| Elemental | 1.9.0 | 1.9.0 | registry.suse.com/rancher/elemental-operator-chart:1.9.0 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.9.0 +
registry.suse.com/rancher/elemental-operator:1.9.0
| Extensión del panel de control de Elemental | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/main/charts/elemental/3.0.1[Helm Chart de la extensión de Elemental]
| Edge Image Builder | 1.3.3.1 | N/D | registry.suse.com/edge/3.6/edge-image-builder:1.3.3.1
| KubeVirt | 1.7.0 | 306.0.2+up0.7.0 | registry.suse.com/edge/3.6/kubevirt-chart:306.0.2+up0.7.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.7.0-150700.3.16.2
| Extensión del panel de control de KubeVirt | 1.3.3 | 306.0.4+up1.3.3 | registry.suse.com/edge/3.6/kubevirt-dashboard-extension-chart:306.0.4+up1.3.3
| Importador de datos en contenedores (CDI) | 1.64.0 | 306.0.2+up0.7.0 | registry.suse.com/edge/3.6/cdi-chart:306.0.2+up0.7.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.64.0-150700.9.6.1
| Operador de Endpoint Copier | 0.3.0 | 306.0.1+up0.3.0 | registry.suse.com/edge/3.6/endpoint-copier-operator-chart:306.0.1+up0.3.0 +
registry.suse.com/edge/3.6/endpoint-copier-operator:0.3.0
| Operador de red SR-IOV | 1.6.0 | 306.0.4+up1.6.0 | registry.suse.com/edge/3.6/sriov-network-operator-chart:306.0.4+up1.6.0 +
registry.suse.com/edge/3.6/sriov-crd-chart:306.0.4+up1.6.0
| Upgrade Controller | 0.19.1 | 109.0.1 | https://charts.rancher.io/index.yaml[Repositorio de Helm de Rancher Charts] +
registry.rancher.com/rancher/system-upgrade-controller:v0.19.1
s| Upgrade Controller s| 0.1.3 s| 306.0.4+up0.1.3 s| registry.suse.com/edge/3.6/upgrade-controller-chart:306.0.4+up0.1.3 +
registry.suse.com/edge/3.6/upgrade-controller:0.1.3 +
registry.rancher.com/rancher/kubectl:v1.35.2 +
registry.suse.com/edge/3.6/release-manifest:3.6.1
| SUSE Private Registry | 1.1.1 | 1.1.1 | oci://registry.suse.com/private-registry/private-registry-helm[Repositorio de Helm de SUSE Private Registry] +
registry.suse.com/private-registry/harbor-core:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-jobservice:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-portal:1.1.1-1.20 +
registry.suse.com/private-registry/harbor-registry:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-registryctl:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-trivy-adapter:1.1.1-1.24
| Kiwi Builder | 10.2.29.1 | N/D | registry.suse.com/edge/3.6/kiwi-builder:10.2.29.1
| Cert-Manager | 1.20.1 | 1.20.1 | https://charts.jetstack.io[Repositorio de Helm de Jetstack] +
quay.io/jetstack/cert-manager-controller:v1.20.1 +
quay.io/jetstack/cert-manager-webhook:v1.20.1 +
quay.io/jetstack/cert-manager-cainjector:v1.20.1
|======

[#release-notes-3-6-0]
= Versión 3.6.0

Fecha de disponibilidad: 27 de mayo de 2026

Fecha de finalización del soporte completo: 27 de noviembre de 2026

Fecha de finalización del soporte de mantenimiento: 27 de mayo de 2028

EOL: 28 de mayo de 2028

Resumen: {product} 3.6.0 es la primera versión en la línea de lanzamientos {product} 3.6.

== Nuevas funciones

* Actualizado a Kubernetes 1.35.3 y Rancher Prime 2.14.1
* Actualizado a SUSE Security (NeuVector) 5.5.1 https://open-docs.neuvector.com/releasenotes/5x[Notas de la versión de NeuVector]
* Actualizado a SUSE Storage (Longhorn) 1.11.1 https://longhorn.io/docs/1.11.1/[Notas de la versión de Longhorn (upstream)]
* Actualizado a Rancher Turtles (CAPI) 0.26.1 https://turtles.docs.rancher.com/[Documentación de Rancher Turtles]
* Actualizado a MetalLB 0.15.3 https://metallb.universe.tf/release-notes/#version-0-15-3[Notas de la versión (upstream)]
* Actualizado a KubeVirt 1.7.0 y CDI (Importador de datos en contenedores) 1.64.0
* Actualizado a Elemental 1.9.0 https://elemental.docs.rancher.com/release-notes/[Notas de la versión de Elemental]
* Actualizado a Cert-Manager 1.20.1 https://cert-manager.io/docs/release-notes/[Notas de la versión (upstream)]
* Actualizado Metal3/Ironic a 0.15.0 con Ironic 35.0.0
* El modo BGP para MetalLB era una vista previa tecnológica en {product} 3.5 y ahora es totalmente compatible
* El protocolo de tiempo de precisión (PTP) en despliegues descendentes era una vista previa tecnológica en {product} 3.5 y ahora es totalmente compatible, junto con la compatibilidad con SyncE y GNSS
* Los despliegues de clústeres descendentes IPv6 de pila única ya son compatibles; no obstante, tenga en cuenta que esto requiere un clúster de gestión de pila dual (los clústeres de gestión de pila única siguen siendo una vista previa tecnológica)

== Correcciones de errores y actualizaciones de seguridad

* Kubernetes 1.35.3 contiene varias correcciones de errores y actualizaciones de seguridad https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.35.md[Registro de cambios de Kubernetes]
* Rancher Prime 2.14.1 contiene varias correcciones de errores https://github.com/rancher/rancher/releases/tag/v2.14.1[Notas de la versión de Rancher (upstream)]
* SUSE Storage (Longhorn) 1.11.1 contiene varias correcciones de fallos https://github.com/longhorn/longhorn/releases/tag/v1.11.1[Correcciones de fallos de Longhorn en sentido ascendente]
* NeuVector 5.5.1 contiene nuevas funciones y varias correcciones de fallos https://open-docs.neuvector.com/releasenotes/5x[Notas de la versión de NeuVector]

== Problemas conocidos

[WARNING]
====
Si va a desplegar nuevos clústeres, siga <<guides-kiwi-builder-images>> para crear primero imágenes nuevas.  Esto se recomienda para los clústeres de gestión y de sentido descendente a fin de garantizar que las imágenes contengan las últimas correcciones de seguridad y de fallos.
====

* Al desplegar a través de Edge Image Builder, los manifiestos `HelmChartConfigs` pueden fallar si se colocan en el directorio de configuración `kubernetes/manifests`. En su lugar, se recomienda colocar cualquier `HelmChartConfigs` en `/var/lib/rancher/{rke2/k3s}/server/manifests/` utilizando la interfaz os-files de EIB.
ifeval::["{flavor}" == "telco"]
Si desea ver un ejemplo, consulte <<mgmt-cluster-directory-structure>>.
endif::[]
Si no se hace esto, los nodos podrían permanecer en estado `NotReady` durante el inicio inicial, tal como se comenta en https://github.com/rancher/rke2/issues/8357[#8357 RKE2 issue].

* En las versiones 1.34 y 1.35 de RKE2/K3s, es posible que el directorio `/etc/cni` utilizado para almacenar las configuraciones de CNI no notifique a `containerd` cuando se escriben archivos en él debido a ciertas condiciones relacionadas con `overlayfs` (véase el https://github.com/rancher/rke2/issues/8356[#8356 RKE2 issue]). Esto, a su vez, provoca que el despliegue de RKE2/K3s se quede bloqueado esperando a que se inicie la CNI, y que los nodos de RKE2/K3s permanezcan en estado `NotReady`. Esto puede observarse a nivel de nodo con `kubectl describe node <affected_node>`:

[,bash]
----
Conditions:
  Type   Status  LastHeartbeatTime                LastTransitionTime               Reason           Message
  ----   ------  -----------------                ------------------               ------           -------
  Ready  False   Thu, 05 Jun 2025 17:41:28 +0000  Thu, 05 Jun 2025 14:38:16 +0000  KubeletNotReady  container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
----

Como solución alternativa, se puede montar un volumen tmpfs en el directorio `/etc/cni` antes de que se inicie RKE2. Esto evita el uso de overlayfs, que provoca que containerd no reciba notificaciones, y las configuraciones deberían reescribirse cada vez que se reinicie el nodo y se vuelvan a ejecutar los initcontainers de los pods. Si utiliza EIB, puede tratarse de un guion `04-tmpfs-cni.sh` en el directorio `custom/scripts` (como se explica https://github.com/suse-edge/edge-image-builder/blob/release-1.3/docs/building-images.md#custom[aquí]) que tenga el siguiente aspecto:

[,bash]
----
#!/bin/bash
mkdir -p /etc/cni
mount -t tmpfs -o mode=0700,size=5M tmpfs /etc/cni
echo "tmpfs /etc/cni tmpfs defaults,size=5M,mode=0700 0 0" >> /etc/fstab
----

* En este momento no hay documentación oficial ni ejemplos disponibles para configurar SyncE mediante synce4l y GNSS mediante gpsd; estos temas se tratarán en futuras versiones.

* Algunos repositorios de contenedores solo son accesibles actualmente a través de IPv4; por este motivo, se requiere un registro local en el clúster de gestión para un clúster de sentido descendente que solo utilice IPv6.

== Versiones de los componentes

La siguiente tabla describe los componentes individuales que conforman la versión 3.6.0, incluida la versión, la versión del gráfico de Helm (si procede) y desde dónde se puede extraer el artefacto publicado en formato binario. Siga la documentación asociada para ver ejemplos de uso y despliegue.

|======
| Nombre | Versión | Versión del chart de Helm | Ubicación del artefacto (URL/Imagen)
| SUSE Linux Micro | 6.2 (el más reciente) | N/D | https://www.suse.com/download/sle-micro/[Página de descarga de SUSE Linux Micro] +
| SUSE Linux Micro | 6.2 (el más reciente) | N/D |Las sumas de comprobación y las firmas están disponibles para descargar en https://www.suse.com/download/sle-micro/[Página de descarga de SUSE Linux Micro] +
SL-Micro.x86_64-6.2-Base-SelfInstall-GM.install.iso +
SL-Micro.x86_64-6.2-Base-RT-SelfInstall-GM.install.iso +
SL-Micro.x86_64-6.2-Base-GM.raw.xz +
SL-Micro.x86_64-6.2-Base-RT-GM.raw.xz +
| SUSE Multi-Linux Manager | 5.1 | N/D | https://www.suse.com/download/suse-manager/[Página de descarga de SUSE Multi-Linux Manager]
| K3s | 1.35.3 | N/D | https://github.com/k3s-io/k3s/releases/tag/v1.35.3%2Bk3s1[Versión en sentido ascendente de K3s]
| RKE2 | 1.35.3 | N/D | https://github.com/rancher/rke2/releases/tag/v1.35.3%2Brke2r3[Versión en sentido ascendente de RKE2]
| SUSE Rancher Prime | 2.14.1 | 2.14.1 | https://charts.rancher.com/server-charts/prime/index.yaml[Repositorio de Helm de Rancher Prime] +
\https://prime.ribs.rancher.io/rancher/v2.14.1/rancher-images.txt[Rancher 2.14.1 Container Images]
| SUSE Storage (Longhorn) | 1.11.1 | 1.11.1 | https://apps.rancher.io/applications/suse-storage[Repositorio de Helm de SUSE Storage] +
\https://apps.rancher.io/applications/suse-storage/components[SUSE Storage Container Images]
| SUSE Security (NeuVector) | 5.5.1 | 109.0.1+up2.8.13 | https://charts.rancher.io/index.yaml[Repositorio de Helm de Rancher Charts] +
registry.rancher.com/rancher/neuvector-controller:5.5.1 +
registry.rancher.com/rancher/neuvector-enforcer:5.5.1 +
registry.suse.com/rancher/neuvector-compliance-config:1.0.12
| Proveedores de Rancher Turtles (CAPI) | 0.26.1 | 306.0.6+up0.26.1 | registry.suse.com/edge/3.6/rancher-turtles-providers-chart:306.0.6+up0.26.1 +
registry.rancher.com/rancher/cluster-api-controller:v1.12.2 +
registry.rancher.com/rancher/turtles:v0.26.1 +
registry.suse.com/rancher/cluster-api-provider-rke2-bootstrap:v0.24.3 +
registry.suse.com/rancher/cluster-api-provider-rke2-controlplane:v0.24.3
| Metal^3^ | 0.15.0 | 306.0.26+up0.15.0 | registry.suse.com/edge/3.6/metal3-chart:306.0.26+up0.15.0 +
registry.suse.com/edge/3.6/baremetal-operator:0.12.3.0 +
registry.suse.com/edge/3.6/ironic:35.0.0.1 +
registry.suse.com/edge/3.6/ironic-ipa-downloader:3.1.1 +
registry.suse.com/edge/3.6/ironic-python-agent:3.0.8
| MetalLB | 0.15.3 | 306.0.2+up0.15.3 | registry.suse.com/edge/3.6/metallb-chart:306.0.2+up0.15.3 +
registry.suse.com/edge/3.6/metallb-controller:v0.15.3 +
registry.suse.com/edge/3.6/metallb-speaker:v0.15.3
| Elemental | 1.9.0 | 1.9.0 | registry.suse.com/rancher/elemental-operator-chart:1.9.0 +
registry.suse.com/rancher/elemental-operator-crds-chart:1.9.0 +
registry.suse.com/rancher/elemental-operator:1.9.0
| Extensión del panel de control de Elemental | 3.0.1 | 3.0.1 | link:https://github.com/rancher/ui-plugin-charts/tree/main/charts/elemental/3.0.1[Gráfico de Helm de la extensión de Elemental]
| Edge Image Builder | 1.3.3.1 | N/D | registry.suse.com/edge/3.6/edge-image-builder:1.3.3.1
| KubeVirt | 1.7.0 | 306.0.2+up0.7.0 | registry.suse.com/edge/3.6/kubevirt-chart:306.0.2+up0.7.0 +
registry.suse.com/suse/sles/15.7/virt-operator:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-api:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-controller:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-handler:1.7.0-150700.3.16.2 +
registry.suse.com/suse/sles/15.7/virt-launcher:1.7.0-150700.3.16.2
| Extensión del panel de control de KubeVirt | 1.3.3 | 306.0.4+up1.3.3 | registry.suse.com/edge/3.6/kubevirt-dashboard-extension-chart:306.0.4+up1.3.3
| Importador de datos en contenedores (CDI) | 1.64.0 | 306.0.2+up0.7.0 | registry.suse.com/edge/3.6/cdi-chart:306.0.2+up0.7.0 +
registry.suse.com/suse/sles/15.7/cdi-operator:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-controller:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-apiserver:1.64.0-150700.9.6.1 +
registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.64.0-150700.9.6.1
| Operador de Endpoint Copier | 0.3.0 | 306.0.1+up0.3.0 | registry.suse.com/edge/3.6/endpoint-copier-operator-chart:306.0.1+up0.3.0 +
registry.suse.com/edge/3.6/endpoint-copier-operator:0.3.0
| Operador de red SR-IOV | 1.6.0 | 306.0.4+up1.6.0 | registry.suse.com/edge/3.6/sriov-network-operator-chart:306.0.4+up1.6.0 +
registry.suse.com/edge/3.6/sriov-crd-chart:306.0.4+up1.6.0
| Controlador de actualización del sistema | 0.19.1 | 109.0.1 | https://charts.rancher.io/index.yaml[Repositorio de Helm de Rancher Charts] +
registry.rancher.com/rancher/system-upgrade-controller:v0.19.1
| Upgrade Controller | 0.1.3 | 306.0.3+up0.1.3 | registry.suse.com/edge/3.6/upgrade-controller-chart:306.0.3+up0.1.3 +
registry.suse.com/edge/3.6/upgrade-controller:0.1.3 +
registry.rancher.com/rancher/kubectl:v1.35.2 +
registry.suse.com/edge/3.6/release-manifest:3.6.0
| SUSE Private Registry | 1.1.1 | 1.1.1 | oci://registry.suse.com/private-registry/private-registry-helm[Repositorio Helm de SUSE Private Registry] +
registry.suse.com/private-registry/harbor-core:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-jobservice:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-portal:1.1.1-1.20 +
registry.suse.com/private-registry/harbor-registry:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-registryctl:1.1.1-1.19 +
registry.suse.com/private-registry/harbor-trivy-adapter:1.1.1-1.24
| Kiwi Builder | 10.2.29.1 | N/D | registry.suse.com/edge/3.6/kiwi-builder:10.2.29.1
| Cert-Manager | 1.20.1 | 1.20.1 | https://charts.jetstack.io[Repositorio Helm de Jetstack] +
quay.io/jetstack/cert-manager-controller:v1.20.1 +
quay.io/jetstack/cert-manager-webhook:v1.20.1 +
quay.io/jetstack/cert-manager-cainjector:v1.20.1
|======

= Funciones eliminadas

A menos que se indique lo contrario, esto se aplica a la versión {version-edge}.0 y a todas las versiones z-stream posteriores.

* Akri era una oferta de vista previa tecnológica en versiones anteriores de Edge y ha quedado obsoleta a partir de la 3.4.0. Ahora se ha eliminado por completo de la oferta.

[#tech-previews]
= Tecnología en fase preliminar.

A menos que se indique lo contrario, esto se aplica a la versión 3.6.0 y a todas las versiones z-stream posteriores.

* Los despliegues de clústeres de gestión IPv6 de pila única son una oferta de vista previa tecnológica y no están sujetos al ámbito de soporte estándar.

= Verificación de componentes

Los componentes mencionados anteriormente pueden verificarse utilizando los datos de la Lista de materiales de software (SBOM); por ejemplo, utilizando `cosign` como se indica a continuación:

Descargue la clave pública del contenedor {product} desde la https://www.suse.com/support/security/keys/[fuente de claves de firma de SUSE]:

[,bash]
----
include::key.sh[]
----

Verifique el hash de la imagen del contenedor, por ejemplo, utilizando `crane`:

[,bash]
----
> crane digest registry.suse.com/edge/3.6/baremetal-operator:0.12.3.0 --platform linux/amd64
sha256:example-digest-placeholder
----

NOTE: Para imágenes multiarquitectura, también es necesario especificar una plataforma al obtener el resumen (digest), p. ej., `--platform linux/amd64` o `--platform linux/arm64`. Si no se hace esto, se producirá un error en el siguiente paso (`Error: no matching attestations`).

Verifique con `cosign`:

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/3.6/baremetal-operator@sha256:example-digest-placeholder > /dev/null
#
Verification for registry.suse.com/edge/3.6/baremetal-operator@sha256:example-digest-placeholder --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - The signatures were verified against the specified public key
----

Extraiga los datos de la SBOM como se describe en la https://www.suse.com/support/security/sbom/[documentación de SBOM de SUSE]:

[,bash]
----
> cosign verify-attestation --type spdxjson --key key.pem registry.suse.com/edge/3.6/baremetal-operator@sha256:example-digest-placeholder | jq '.payload | @base64d | fromjson | .predicate'
----

= Pasos de actualización

Consulte <<day-2-operations>> para obtener detalles sobre cómo actualizar a una nueva versión.

= Etapas de asistencia técnica de los productos

{product} cuenta con el respaldo del galardonado soporte de SUSE, un líder tecnológico consolidado con un historial probado en la prestación de servicios de soporte de calidad empresarial. Para obtener más información, consulte https://www.suse.com/lifecycle[https://www.suse.com/lifecycle] y la página de Política de soporte en https://www.suse.com/support/policy.html[https://www.suse.com/support/policy.html]. Si tiene alguna pregunta sobre cómo abrir un caso de soporte, cómo clasifica SUSE los niveles de gravedad o el alcance del soporte, consulte el Manual de soporte técnico en https://www.suse.com/support/handbook/[https://www.suse.com/support/handbook/].

{product} «3.6» cuenta con 24 meses de soporte de producción, con 6 meses iniciales de «soporte completo», seguidos de 18 meses de «soporte de mantenimiento».  Tras estas fases de soporte, el producto alcanza el «fin de vida útil» (EOL) y deja de recibir soporte. Puede encontrar más información sobre las fases del ciclo de vida en la siguiente tabla:

|======
| *Soporte completo (6 meses)* | Durante el periodo de soporte completo se publicarán correcciones de errores urgentes y de alta prioridad seleccionadas, y el resto de los parches (no urgentes, mejoras, nuevas capacidades) se publicarán siguiendo el calendario de lanzamientos habitual.
| *Soporte de mantenimiento (18 meses)* | Durante este periodo, solo se publicarán correcciones críticas mediante parches. Es posible que se publiquen otras correcciones de errores a discreción de SUSE, pero no debe esperarse que así sea.
| *Fin de vida útil (EOL)*  | Una vez que una versión de producto alcanza su fecha de fin de vida útil, el cliente puede seguir utilizando el producto dentro de los términos del acuerdo de licencia del producto.
Los planes de soporte de SUSE no se aplican a las versiones de productos que han superado su fecha de EOL.
|======

A menos que se indique explícitamente, todos los componentes enumerados se consideran de disponibilidad general (GA) y están cubiertos por el alcance estándar de soporte de SUSE. Algunos componentes pueden aparecer como «Technology Preview», donde SUSE proporciona a los clientes acceso a características y funcionalidades tempranas previas a la GA para su evaluación, pero no están sujetos a las políticas de soporte estándar y no se recomiendan para casos de uso de producción. SUSE agradece enormemente los comentarios y sugerencias sobre las mejoras que se pueden realizar en los componentes de Technology Preview, pero SUSE se reserva el derecho de dejar obsoleta una característica de Technology Preview antes de que esté disponible de forma general si no satisface las necesidades de nuestros clientes o no alcanza el estado de madurez que requerimos.

Tenga en cuenta que SUSE debe dejar obsoletas ocasionalmente características o cambiar las especificaciones de la API. Las razones para que una característica quede obsoleta o para el cambio de una API podrían incluir que una característica se actualice o sea reemplazada por una nueva implementación, un nuevo conjunto de características, que la tecnología en sentido ascendente ya no esté disponible o que la comunidad en sentido ascendente haya introducido cambios incompatibles. No se pretende que esto ocurra nunca dentro de una versión menor determinada (x.z), por lo que todas las versiones z-stream mantendrán la compatibilidad de la API y la funcionalidad de las características. SUSE se esforzará por proporcionar avisos de obsolescencia con suficiente antelación en las notas de la versión, junto con soluciones alternativas, sugerencias y medidas de mitigación para minimizar la interrupción del servicio.

El equipo de {product} también agradece los comentarios de la comunidad, donde se pueden plantear problemas dentro del repositorio de código respectivo en https://www.github.com/suse-edge[https://www.github.com/suse-edge].

= Obtención del código fuente

Este producto de SUSE incluye materiales con licencia para SUSE bajo la Licencia Pública General de GNU (GPL) y otras licencias de código abierto. La GPL requiere que SUSE proporcione el código fuente que corresponde al material con licencia GPL, y SUSE cumple con todos los demás requisitos de las licencias de código abierto. Como tal, SUSE pone a disposición todo el código fuente, que generalmente se puede encontrar en el repositorio de GitHub de {product} (https://www.github.com/suse-edge[https://www.github.com/suse-edge]), el repositorio de GitHub de SUSE Rancher (https://www.github.com/rancher[https://www.github.com/rancher]) para los componentes dependientes y, específicamente para SUSE Linux Micro, el código fuente está disponible para su descarga en https://www.suse.com/download/sle-micro/[https://www.suse.com/download/sle-micro] en el «Medio 2».

= Información legal

SUSE no otorga ninguna garantía respecto al contenido y el uso de esta documentación y, específicamente, renuncia a cualquier garantía explícita o implícita de posibilidad de comercialización o adecuación para un fin determinado. Asimismo, SUSE se reserva el derecho a revisar esta publicación y a realizar cambios en su contenido en cualquier momento, sin obligación de notificar tales cambios a ninguna persona o entidad.

Asimismo, SUSE no otorga ninguna garantía con respecto a ningún programa de software, y específicamente rechaza cualquier garantía explícita o implícita de comercialización o adecuación para un fin determinado. Por otra parte, SUSE se reserva el derecho a realizar cambios en cualquiera de las partes o en la totalidad del software de SUSE en cualquier momento, sin obligación de notificar de tales cambios a ninguna persona ni entidad.

Los productos o la información técnica que se proporcionan bajo este Acuerdo pueden están sujetos a los controles de exportación de Estados Unidos o a la legislación sobre comercio de otros países. Usted se compromete a cumplir todas las normativas de control de exportaciones y a obtener las licencias o clasificaciones necesarias para exportar, reexportar o importar los entregables. Usted acepta no realizar exportaciones ni reexportaciones a las entidades que se incluyan en las listas actuales de exclusión de exportaciones de EE. UU., así como a ningún país terrorista o sometido a embargo, tal y como queda recogido en las leyes de exportación de EE. UU. Usted acepta no utilizar los entregables para fines finales prohibidos relacionados con armamento nuclear, de misiles o químico/biológico. Consulte https://www.suse.com/company/legal/[https://www.suse.com/company/legal/] para obtener más información sobre la exportación del software de SUSE. SUSE no asume ninguna responsabilidad por los fallos que cometa el usuario en la obtención de los permisos de exportación necesarios.

*Copyright © 2024 SUSE LLC.*

Este documento de notas de la versión cuenta con una licencia Creative Commons Attribution-NoDerivatives 4.0 International License (CC-BY-ND-4.0). Debería haber recibido una copia de la licencia junto con este documento. Si no es así, consulte https://creativecommons.org/licenses/by-nd/4.0/[https://creativecommons.org/licenses/by-nd/4.0/].

SUSE posee derechos de propiedad intelectual relacionados con la tecnología incorporada en el producto descrito en este documento. En concreto, y sin limitación, estos derechos de propiedad intelectual pueden incluir una o más de las patentes de EE. UU. que aparecen en https://www.suse.com/company/legal/[https://www.suse.com/company/legal/] y una o más patentes adicionales o solicitudes de patentes pendientes en EE. UU. y en otros países.

Para consultar las marcas comerciales de SUSE, véase la lista de marcas comerciales y marcas de servicio de SUSE (https://www.suse.com/company/legal/[https://www.suse.com/company/legal/]). Todas las marcas comerciales de otros fabricantes son propiedad de sus propietarios respectivos. Para obtener información sobre la marca SUSE y los requisitos de uso, consulte las directrices publicadas en https://brand.suse.com/[https://brand.suse.com/].
