[#atip]
= SUSE Adaptive Telco Infrastructure Platform (ATIP) 
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc: preamble

SUSE Adaptive Telco Infrastructure Platform (`ATIP`) is a Telco-optimized edge computing platform that enables telecom companies to innovate and accelerate modernization of their networks.

ATIP is a complete Telco cloud stack for hosting CNFs such as 5G Packet Core, Cloud RAN.

- Automates zero-touch rollout and lifecycle management of complex edge stack configurations at Telco scale.
- Continuously assureds quality on Telco-grade hardware, using Telco-specific configurations and workloads.
- Consists of components that are purpose built for the edge and hence have smaller footprint and higher performance per Watt.
- Maintains a flexible platform strategy with vendor-neutral APIs and 100% open source.

include::atip-architecture.adoc[]

include::atip-requirements.adoc[]

include::atip-management-cluster.adoc[]

include::atip-features.adoc[]

include::atip-automated-provision.adoc[]

include::atip-lifecycle.adoc[]
