[#atip]
= SUSE Telco Cloud
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc: preamble

SUSE Telco Cloud (formerly known as SUSE Edge for Telco, or Adaptive Telco Infrastructure Platform) is a telecom-optimized computing platform that enables telecom operators and teelcom network vendors to innovate and accelerate the modernization of their networks.

SUSE Telco Cloud is a complete Telco cloud stack for hosting CNFs, including 5G Packet Core, Cloud RAN, OSS and BSS.

- Automates zero-touch rollout and lifecycle management of complex edge stack configurations at Telco scale.
- Continuously assures quality on Telco-grade hardware, using Telco-specific configurations and workloads.
- Consists of components that are purpose-built for the edge and hence have smaller footprint and higher performance per Watt.
- Maintains a flexible platform strategy with vendor-neutral APIs and 100% open source.
