[#{cluster-type}-day2-fleet]
== Fleet
:revdate: 2025-01-14
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

本节提供有关如何使用 <<components-fleet, Fleet>> 组件执行“第 2 天”操作的信息。

本节涵盖以下主题：

. <<{cluster-type}-day2-fleet-components>> - 用于所有“第 2 天”操作的默认组件。
. <<{cluster-type}-day2-fleet-determine-use-case>> - 提供将要使用的 Fleet 自定义资源概述，以及它们对不同“第 2 天”操作用例的适用性。
. <<{cluster-type}-day2-upgrade-workflow>> - 提供使用 Fleet 执行“第 2 天”操作的工作流程指南。
. <<{cluster-type}-day2-fleet-os-upgrade>> - 描述如何使用 Fleet 进行操作系统升级。
. <<{cluster-type}-day2-fleet-k8s-upgrade>> - 描述如何使用 Fleet 进行 Kubernetes 版本升级。
. <<{cluster-type}-day2-fleet-helm-upgrade>> - 描述如何使用 Fleet 进行 Helm chart 升级。

[#{cluster-type}-day2-fleet-components]
=== 组件

您可以在下方找到应在您的 `{cluster-type}` 集群上设置的默认组件说明，以便您能够使用 Fleet 成功执行“第 2 天”操作。

ifeval::["{cluster-type}" == "management"]
==== Rancher

*可选*；负责管理 `downstream clusters` 并在您的 `System Upgrade Controller` 上部署 `management cluster`。

有关详细信息，请访问 <<components-rancher>>。
endif::[]

==== 系统升级控制器 (SUC)

ifeval::["{cluster-type}" == "downstream"]
[NOTE]
====
*必须*部署在每个下游集群上。
====
endif::[]

*系统升级控制器*负责根据通过名为 `Plan` 的自定义资源提供配置数据，在指定节点上执行任务。

*SUC*被主动用于升级操作系统和 Kubernetes 发行版。

有关 *SUC* 组件及其如何适配 Edge 堆栈的更多信息，请参阅 <<components-system-upgrade-controller>>。

ifeval::["{cluster-type}" == "downstream"]
有关如何部署 *SUC* 的信息，请先 <<{cluster-type}-day2-fleet-determine-use-case, 确定您的用例>>，然后参考 <<components-system-upgrade-controller-fleet-gitrepo, 系统升级控制器安装 - GitRepo>> 或 <<components-system-upgrade-controller-fleet-bundle, 系统升级控制器安装 - Bundle>>。
endif::[]

[#{cluster-type}-day2-fleet-determine-use-case]
=== 确定您的用例

Fleet 使用两种类型的 link:https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[自定义资源] 来实现 Kubernetes 和 Helm 资源的管理。

您可以在下方找到有关这些资源的目的以及它们在“第 2 天”操作背景下最适合的用例的信息。

==== GitRepo

`GitRepo` 是一个 <<components-fleet, Fleet>> 资源，它代表一个 `Fleet` 可以从中创建 `Bundles` 的 Git 储存库。每个 `Bundle` 都是基于 `GitRepo` 资源内定义的配置路径创建的。有关详细信息，请参见 https://fleet.rancher.io/gitrepo-add[GitRepo] 文档。

在“Day 2”操作的背景下，`GitRepo` 资源通常用于在利用 _Fleet GitOps_ 方法的 *非隔离的* 环境中部署 `SUC` 或 `SUC Plans`。

或者，`GitRepo` 资源也可用于在 *隔离的* 环境中部署 `SUC` 或 `SUC Plans`，*前提是您通过本地 git 服务器镜像您的储存库设置*。

==== 捆绑包

`Bundles` 包含将部署在目标集群上的 *原始* Kubernetes 资源。通常它们是从 `GitRepo` 资源创建的，但在某些用例中也可以手动部署它们。有关详细信息，请参考 https://fleet.rancher.io/bundle-add[Bundle] 文档。

在“Day 2”操作的背景下，`Bundle` 资源通常用于在不使用某种 _本地 GitOps_ 流程（例如 *本地 git 服务器*）的 *隔离的* 环境中部署 `SUC` 或 `SUC Plans`。

或者，如果您的用例不允许 _GitOps_ 工作流（例如使用 Git 储存库），则 `Bundle` 资源也可用于在 *非隔离的* 环境中部署 `SUC` 或 `SUC Plans`。

[#{cluster-type}-day2-upgrade-workflow]
=== Day 2 工作流

以下是升级 {cluster-type} 集群到特定 Edge 版本时应遵循的“Day 2”工作流。

. <<{cluster-type}-day2-fleet-os-upgrade, 操作系统升级>>

. <<{cluster-type}-day2-fleet-k8s-upgrade, Kubernetes 版本升级>>

. <<{cluster-type}-day2-fleet-helm-upgrade, Helm chart 升级>>

:leveloffset: +1

include::fleet-os-upgrade.adoc[]

include::fleet-k8s-upgrade.adoc[]

include::fleet-helm-upgrade.adoc[]

:leveloffset: -1
