[#day2-migration]
= 边缘 {version-edge} 迁移
:revdate: 2026-05-06
:revnumber: 3.6
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc: preamble
:previous-edge-version: 3.5
:static-edge-version: 3.6.0
:static-fleet-examples-tag: release-3.6.0

本节介绍了如何将您的 `management` 和 `downstream` 集群从 `{product} {previous-edge-version}` 迁移到 `{product} {static-edge-version}`。

[IMPORTANT]
====
请务必从 `latest Z-stream` 的 `{product} {previous-edge-version}` 版本执行集群迁移。

请务必迁移到 `{product} {static-edge-version}` 版本。有关后续迁移后的升级，请参阅 <<day2-mgmt-cluster, 管理>>
ifeval::["{flavor}" == "edge"]
和 <<day2-downstream-clusters,下游>> 集群
endif::[]
中的各个部分。
====

下表列出了不同类型的集群以及升级集群的方法：

[[Clusters-and-methods-to-upgrade-downstream-clusters]]
.集群以及升级下游集群的方法
|===
| 集群类型  | 方法

|EIB 配置的集群
|有关详细信息，请参见<<day2-migration-mgmt-fleet>>。
ifeval::["{flavor}" == "telco"]
|Metal^3^ 配置的集群
|有关详细信息，请参阅 <<atip-lifecycle-downstream,下游集群升级>>。
endif::[]
ifeval::["{flavor}" == "edge"]
|Phone-home 配置的集群
|有关 Kubernetes 版本升级，请参阅 https://ranchermanager.docs.rancher.com/{rancher-docs-version}/getting-started/installation-and-upgrade/upgrade-and-roll-back-kubernetes#upgrading-the-kubernetes-version[升级 Kubernetes 版本]；有关 SUC、操作系统和其他组件，请参阅 <<day2-downstream-clusters,下游集群>>。
endif::[]
|===

[#day2-migration-mgmt]
== 管理群集
:cluster-type: management

本节包含下列主题：

<<day2-migration-mgmt-prereq>> - 开始迁移前需要完成的先决条件步骤。

<<day2-migration-mgmt-upgrade-controller>> - 如何使用 `{cluster-type}` 执行 <<components-upgrade-controller>> 集群迁移。

<<day2-migration-mgmt-fleet>> - 如何使用 `{cluster-type}` 执行 <<components-fleet>> 集群迁移。

[#day2-migration-mgmt-prereq]
=== 先决条件

ifeval::["{flavor}" == "telco"]
==== 升级裸机操作员 CRD

[NOTE]
====
仅适用于需要 <<components-metal3>> chart 升级的 CAPI/Metal3 管理集群。
====

`Metal^3^` Helm chart 通过利用 Helm 的 link:https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you[CRD] 目录包含 link:https://book.metal3.io/bmo/introduction.html[Bare Metal Operator (BMO)] CRD。

然而，这种方法有一定的局限性，特别是无法使用 Helm 升级此目录中的 CRD。有关详细信息，请参见 link:https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations[Helm 文档]。

因此，在将 Metal^3^ 升级到 `{product} {static-edge-version}` 兼容版本之前，用户必须手动升级底层的 BMO CRD。

在安装了 `Helm` 且 `kubectl` 配置为指向您的 `{cluster-type}` 集群的机器上：

. 手动应用 BMO CRD：
+
[,bash,subs="attributes"]
----
helm show crds oci://registry.suse.com/edge/charts/metal3 --version {version-metal3-chart} | kubectl apply -f -
----
endif::[]

==== 迁移 Metal^3^ CA 证书配置

[NOTE]
====
仅适用于使用额外的受信任 CA 来处理带有 TLS 的外部媒体服务器的 Metal^3^ 部署。
====

Metal^3^ Helm chart 更改了受信任 CA 证书的配置方式。以前，额外的 CA 是通过带有 `additionalTrustedCAs` 布尔标志的 Secret (`tls-ca-additional`) 提供的。新版本使用包含由 `global.trustedCAs` 值引用的完整 CA 捆绑包的 ConfigMap。

如果您已为 Metal^3^ 配置了额外的受信任 CA，则需要从基于 Secret 的方法迁移到基于 ConfigMap 的方法：

. 从现有的 Secret 创建包含您的 CA 捆绑包的 ConfigMap：
+
从旧的 Secret 中提取证书：
+
[,shell]
----
kubectl get secret tls-ca-additional -n metal3-system -o jsonpath='{.data}' | \
  jq -r 'to_entries[] | .value' | base64 -d > ca-bundle.pem
----
+
*可选 - 包含系统 CA 捆绑包：*
如果您的 Metal^3^ 部署还需要信任公共 CA（例如，通过 HTTPS 访问外部资源时），则除了自定义 CA 之外，还需要包含系统 CA 捆绑包。从容器镜像中提取系统 CA 捆绑包，并将其添加到您的自定义 CA 之前：
+
[,shell]
----
# Extract system CAs from a container image (using podman or docker)
podman run --rm registry.suse.com/bci/bci-base:latest cat /etc/ssl/certs/ca-certificates.crt > system-cas.pem

# Combine system CAs with your custom CAs
cat system-cas.pem ca-bundle.pem > combined-ca-bundle.pem
mv combined-ca-bundle.pem ca-bundle.pem
----
+
[IMPORTANT]
====
如果您包含系统 CA 捆绑包，则您有责任使其保持最新。容器镜像中的系统 CA 可能会随着 CA 证书过期或被吊销而逐渐过时。您应该通过从更新的容器镜像中重新提取系统 CA 捆绑包来定期刷新它。
====
+
使用最终的 CA 捆绑包创建 ConfigMap：
+
[,shell]
----
kubectl create configmap tls-ca-bundle -n metal3-system --from-file=ca-bundle.pem=ca-bundle.pem
----

. 更新您的 Metal^3^ Helm 值以使用新的 ConfigMap 引用：
+
更改自：
+
[,yaml]
----
global:
  additionalTrustedCAs: true
----
+
至：
+
[,yaml]
----
global:
  trustedCAs: tls-ca-bundle
----

. 使用新配置升级 Metal^3^ Helm chart 后，您可以删除旧的 Secret：
+
[,shell]
----
kubectl delete secret tls-ca-additional -n metal3-system
----

[#day2-migration-mgmt-upgrade-controller]
=== 升级控制器

[IMPORTANT]
====
`Upgrade Controller` 目前仅支持 `{product}` 版本迁移，仅适用于 *非隔离的管理* 集群。
====

本节涵盖以下主题：

<<day2-migration-mgmt-upgrade-controller-prereq>> - `Upgrade Controller` 的特定先决条件。

<<day2-migration-mgmt-upgrade-controller-migration>> - 使用 `Upgrade Controller` 将 `{cluster-type}` 集群迁移到新 `{product}` 版本的步骤。

[#day2-migration-mgmt-upgrade-controller-prereq]
==== 先决条件

===== {product} {version} 升级控制器

在使用 `Upgrade Controller` 之前，您必须首先确保其运行的版本能够迁移到所需的 `{product}` 版本。

要执行这一操作：

. 如果您已经从之前的 `Upgrade Controller` 版本部署了 `{product}`，请升级其 chart：
+
[,bash,subs="attributes"]
----
helm upgrade upgrade-controller -n upgrade-controller-system oci://registry.suse.com/edge/charts/upgrade-controller --version {version-upgrade-controller-chart}
----

. 如果您 *没有* 部署 `Upgrade Controller`，请遵循 <<components-upgrade-controller-installation>>。

[#day2-migration-mgmt-upgrade-controller-migration]
==== 迁移步骤

使用 `{cluster-type}` 执行 `Upgrade Controller` 集群迁移与执行升级基本相似。

唯一的区别是您的 `UpgradePlan` *必须* 指定 `{static-edge-version}` 发布版本：

[,yaml,subs="attributes"]
----
apiVersion: lifecycle.suse.com/v1alpha1
kind: UpgradePlan
metadata:
  name: upgrade-plan-mgmt
  # Change to the namespace of your Upgrade Controller
  namespace: CHANGE_ME
spec:
  releaseVersion: {static-edge-version}
----

有关如何使用上述 `UpgradePlan` 进行迁移的信息，请参阅 <<{cluster-type}-day2-upgrade-controller, Upgrade Controller 升级流程>>。

[#day2-migration-mgmt-fleet]
=== Fleet

[NOTE]
====
尽可能使用 <<day2-migration-mgmt-upgrade-controller>> 进行迁移。

仅在 `Upgrade Controller` 未涵盖的用例中参考本节。
====

使用 `{cluster-type}` 执行 `Fleet` 集群迁移与执行升级基本相似。

*关键*区别在于：

. 必须使用 `suse-edge/fleet-examples` 储存库的 link:https://github.com/suse-edge/fleet-examples/releases/tag/{static-fleet-examples-tag}[{static-fleet-examples-tag}] 版本中的 *Fleet*。

. 计划升级的 Chart *必须*升级到与 `{product} {static-edge-version}` 版本兼容的版本。有关 `{product} {static-edge-version}` 组件的列表，请参阅 <<release-notes-3-6-0>>。

[IMPORTANT]
====
为确保 `{product} {static-edge-version}` 迁移成功，用户务必遵守上述要点。
====

ifeval::["{flavor}" == "edge"]
考虑到上述几点，用户可以遵循 `{cluster-type}` 集群 <<{cluster-type}-day2-fleet, Fleet>> 文档，获取执行迁移所需步骤的综合指南。
endif::[]

[#day2-migration-downstream]
== 下游集群
:cluster-type: downstream

<<day2-migration-downstream-fleet>> - 如何使用 `{cluster-type}` 执行 <<components-fleet>> 集群迁移。

[#day2-migration-downstream-fleet]
=== Fleet

使用 `{cluster-type}` 执行 `Fleet` 集群迁移与执行升级基本相似。

*关键*区别在于：

. 必须使用 `suse-edge/fleet-examples` 储存库的 link:https://github.com/suse-edge/fleet-examples/releases/tag/{static-fleet-examples-tag}[{static-fleet-examples-tag}] 版本中的 *Fleet*。

. 计划升级的 Chart *必须*升级到与 `{product} {static-edge-version}` 版本兼容的版本。有关 `{product} {static-edge-version}` 组件的列表，请参阅 <<release-notes-3-6-0>>。

[IMPORTANT]
====
为确保 `{product} {static-edge-version}` 迁移成功，用户务必遵守上述要点。
====

ifeval::["{flavor}" == "edge"]
考虑到上述几点，用户可以遵循 `{cluster-type}` 集群 <<{cluster-type}-day2-fleet, Fleet>> 文档，获取执行迁移所需步骤的综合指南。
endif::[]
