[#{cluster-type}-day2-upgrade-controller]
== Upgrade Controller
:revdate: 2025-01-16
:revnumber: 3.4
:page-revdate: {revdate}
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[IMPORTANT]
====
`Upgrade Controller` 目前仅支持 *非隔离的管理* 集群的 `Day 2` 操作。
====

本节介绍了如何执行与将 `management` 集群从一个 Edge 平台版本升级到另一个版本相关的各种 `Day 2` 操作。

`Day 2` 操作由 <<components-upgrade-controller, 升级控制器>> 自动执行，包括：

* <<components-slmicro, SUSE Linux Micro>> 操作系统升级

* <<components-rke2>> 或 <<components-k3s>> Kubernetes 升级

* SUSE 附加组件（SUSE Rancher Prime、SUSE Security 等）升级

=== 先决条件

在升级您的 `management` 集群之前，必须满足以下先决条件：

. `SCC registered nodes` - 确保您的集群节点操作系统已使用支持您打算升级到的 Edge <<release-notes,版本>> 中指定的操作系统版本的订阅密钥进行注册。

. `Upgrade Controller` - 确保 `Upgrade Controller` 已部署在您的 `management` 集群上。有关安装步骤，请参阅 <<components-upgrade-controller-installation>>。

=== 升级

. 确定您希望将 `management` 集群升级到的 Edge <<release-notes,版本>>。

. 在 `management` 集群中，部署一个指定所需 `UpgradePlan` 的 `release version`。`UpgradePlan` 必须部署在 `Upgrade Controller` 的名称空间中。
+
[,bash]
----
kubectl apply -n <upgrade_controller_namespace> -f - <<EOF
apiVersion: lifecycle.suse.com/v1alpha1
kind: UpgradePlan
metadata:
  name: upgrade-plan-mgmt
spec:
  # Version retrieved from release notes
  releaseVersion: 3.X.Y
EOF
----
+
[NOTE]
====
在某些用例中，您可能希望对 `UpgradePlan` 进行额外配置。有关所有可能的配置，请参考 <<components-upgrade-controller-extensions-upgrade-plan>>。
====

. 将 `UpgradePlan` 部署到 `Upgrade Controller's` 名称空间将开始 `upgrade process`。
+
[NOTE]
====
有关实际 `upgrade process` 的详细信息，请参考 <<components-upgrade-controller-how>>。

有关如何跟踪 `upgrade process` 的信息，请参考 <<components-upgrade-controller-how-track>>。
====
