[#guides-public-cloud]
= Running the Management Cluster in the Public Cloud
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]



TODO: Write intro section

== Networking and Topology

Downstream clusters need to have access to the Rancher server that's managing it. This means that we need to provide a FQDN that's resolves to a LoadBalancer that routes the traffic to Rancher.

In the public cloud, this 

== Sizing Considerations

The number of downstream clusters a single Rancher server is able to manage is influenced by both the number of objects being created for each cluster as well as the size of the VMs hosting the management cluster's workers.

=== Object Count

Rancher creates several Kubernetes objects for each cluster. These 

More information can be found at https://ranchermanager.docs.rancher.com/v2.10/reference-guides/best-practices/rancher-server/tuning-and-best-practices-for-rancher-at-scale#managing-your-object-counts 

=== Instance Size:

Some basic sizing considerations can be found at https://ranchermanager.docs.rancher.com/v2.10/getting-started/installation-and-upgrade/installation-requirements#rke2-kubernetes

== Federation

TODO: write about setting up multiple Rancher servers and using fleet-local to manage their configuration 
