[#guides-public-cloud]
= Running the Management Cluster in the Public Cloud
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]



TODO: Write intro section


== Networking and Topology

TODO: Add diagram here

Downstream clusters need to have access to the Rancher server that's managing it. This means that we need to provide a FQDN that's resolves to a LoadBalancer that routes the traffic to Rancher. 

In the public cloud, this typically is done through the tools provided by your cloud provider.

[NOTE]
==== 
For example, in Amazon AWS you could set up an EKS cluster then use an Application Load Balancer (ALB) to both terminate TLS and route traffic to the cluster's ingress controller. If AWS is also your DNS registrar, it can also create a CNAME entry to point at the ALB being created.
====

=== SUSE Manager

It can also be advantageous to use <<component-suse-manager,SUSE Manager>> to reduce network traffic for updates along with reducing risk of losing access to individual nodes with a "belt and suspenders" approach. 

TODO: some basics about SUMA 

=== Cloud Marketplace 

SUSE also maintains offerings in the marketplace of the most commonly used cloud providers. For more information here

TODO: find link for above

== Sizing Considerations

The number of downstream clusters a single Rancher server is able to manage is influenced by both the number of objects being created for each cluster as well as the size of the VMs hosting the management cluster's workers.

=== Object Count

Rancher creates several Kubernetes objects for each cluster which affects it's performance. The amount of objects that are created depends on factors such as:

- # of Roles/RoleBindings
- # of Users
- # of workloads 
- # of extensions being used

More information can be found at https://ranchermanager.docs.rancher.com/v2.10/reference-guides/best-practices/rancher-server/tuning-and-best-practices-for-rancher-at-scale#managing-your-object-counts 

=== Instance Size:

Some basic sizing considerations can be found at https://ranchermanager.docs.rancher.com/v2.10/getting-started/installation-and-upgrade/installation-requirements#rke2-kubernetes

== Federation

If you need to scale further (or limit impact of outages) it make be advantageous to split your clusters across several Rancher server instances. 

To make this configuration easier to manage, you can use Fleet to configure the Rancher instances themselves. 

TODO: fill out with mention of tech preview rancher exporter