name: Test deployment

# https://github.com/peaceiris/actions-gh-pages/issues/852
permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - "release-3.*"
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run the docs build in a container
        uses: addnab/docker-run-action@v3
        with:
            image: registry.opensuse.org/home/atgracey/cnbp/containers/builder:latest
            options: -v ${{ github.workspace }}:/docs
            run: |
                cd /docs/asciidoc
                daps -d DC-edge html
