= Edge Image Builder Quick-Start Guide
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Edge Image Builder (EIB) is a tool that streamlines the process of generating pre-configured, ready-to-deploy (RTD) disk images for bootstrapping machines, even in air-gapped scenarios.

For more information, read the  link:../components/edge-image-builder.adoc[Edge Image Builder Introduction]

== Prerequisites

* x86_64 machine to run EIB
* Podman or alternative container runtime
* Local copy of `SLE-Micro.x86_64-5.5.0-Default-SelfInstall-GM2.install.iso` found https://www.suse.com/download/sle-micro/[here]

[NOTE]
====
If you are running Rancher Desktop, you need to switch to the https://docs.rancherdesktop.io/ui/preferences/container-engine/general[`dockerd (moby)` container runtime]
====

=== Getting the EIB Image

`podman pull EIB-IMAGE-HERE`

=== Creating the image configuration directory

EIB requires mounting a directory from the host.

This directory must follow a specific structure, the following instructions outline a non-comprehensive example:

For simplicity, setting the variable `$EIB` to the full path of where you want the configuration directory is recommended, e.g. `EIB=/home/user/eib/config`.

`mkdir -p $EIB/base-images`

`mkdir $EIB/network`

`cp SLE-Micro.x86_64-5.5.0-Default-SelfInstall-GM2.install.iso $EIB/base-images/slemicro.iso`

The generated directory should look like:

[,console]
----
├── base-images/
│   └ slemicro.iso
├── network/
└──
----

=== Building the image definition file

The definition file declaratively defines the desired configuration of the RTD image.

The base contents of the file are:

[,yaml]
----
apiVersion: 1.0
image:
  imageType: iso
  arch: x86_64
  baseImage: slemicro.iso
  outputImageName: eib-image.iso
----

This definition outlines that we are generating an image for an `x86_64` system and that the base image to be modified is an `ISO` image named `slemicro.iso` that is expected to be found at `$EIB/base-images/slemicro.iso`. It also outlines that after EIB is done modifying the image, the RTD image will be named `eib-image.iso`.

We will save this file as `eib-iso-definition.yaml`

Now our directory structure should look like:
[,console]
----
├── eib-iso-definition.yaml
├── base-images/
│   └ slemicro.iso
├── network/
└──
----

==== Configuring OS Users

EIB allows us to pre-configure users with login information such as passwords or SSH keys. (Doing this for root is not typically recommended but we will use root for this guide).

First, create an encrypted password:

[,console]
----
openssl passwd -6 MyPassword!123
----

This will output something similar to:

[,console]
----
$6$UrXB1sAGs46DOiSq$HSwi9GFJLCorm0J53nF2Sq8YEoyINhHcObHzX2R8h13mswUIsMwzx4eUzn/rRx0QPV4JIb0eWCoNrxGiKH4R31
----

We can then add a section in the definition file called `operatingSystem` with a `users` array inside it. The resulting file should look like:

[,yaml]
----
apiVersion: 1.0
image:
  imageType: iso
  arch: x86_64
  baseImage: slemicro.iso
  outputImageName: eib-image.iso
operatingSystem:
  users:
    - username: root
      encryptedPassword: $6$UrXB1sAGs46DOiSq$HSwi9GFJLCorm0J53nF2Sq8YEoyINhHcObHzX2R8h13mswUIsMwzx4eUzn/rRx0QPV4JIb0eWCoNrxGiKH4R31
----

==== Packages

EIB also allows us to pre-configure our RTD image with packages.

As an example, to install the `yq` package (a package that simplifies working with YAML) found in the PackageHub repository, we can specify the package as part of a package list and also the repository where it can be found:

[,yaml]
----
  packages:
    packageList:
      - yq
    additionalRepos:
      - url: https://download.opensuse.org/repositories/openSUSE:Factory/standard
----

The resulting definition file looks like:

[,yaml]
----
apiVersion: 1.0
image:
  imageType: iso
  arch: x86_64
  baseImage: slemicro.iso
  outputImageName: eib-image.iso
operatingSystem:
  users:
    - username: root
      encryptedPassword: $6$UrXB1sAGs46DOiSq$HSwi9GFJLCorm0J53nF2Sq8YEoyINhHcObHzX2R8h13mswUIsMwzx4eUzn/rRx0QPV4JIb0eWCoNrxGiKH4R31
  packages:
    packageList:
      - yq
    additionalRepos:
      - url: https://download.opensuse.org/repositories/openSUSE:Factory/standard
----

Given this, the EIB package resolver will automatically search for and download the required RPMs for the package as well as all of the necessary dependencies. This package will then be pre-installed to the RTD image with no network connection necessary.

[NOTE]
====
More operating system settings can be found https://github.com/suse-edge/edge-image-builder/blob/main/docs/building-images.md#operating-system[here] in the Edge Image Builder documentation.
====

==== Kubernetes and Kubernetes workload Configuration

Another feature of EIB is the simplified air-gapped deployment of a Kubernetes cluster with Helm charts and manifests.

The following addition to the definition file:

[,yaml]
----
kubernetes:
  version: v1.28.7+rke2r1
  manifests:
    urls:
      - https://k8s.io/examples/application/nginx-app.yaml
  helm:
    charts:
      - name: kubevirt
        version: 0.2.2
        repositoryName: suse-edge
    repositories:
      - name: suse-edge
        url: https://suse-edge.github.io/charts
----

defines that RKE2 Kubernetes version `v1.28.7+rke2r1`, the `kubevirt` Helm chart version `0.2.2` found in the `https://suse-edge.github.io/charts` repository, and the manifest found at `https://k8s.io/examples/application/nginx-app.yaml` should be automatically deployed on the generated RTD image.

The resulting full definition file should now look like:
[,yaml]
----
apiVersion: 1.0
image:
  imageType: iso
  arch: x86_64
  baseImage: slemicro.iso
  outputImageName: eib-image.iso
operatingSystem:
  users:
    - username: root
      encryptedPassword: $6$UrXB1sAGs46DOiSq$HSwi9GFJLCorm0J53nF2Sq8YEoyINhHcObHzX2R8h13mswUIsMwzx4eUzn/rRx0QPV4JIb0eWCoNrxGiKH4R31
  packages:
    packageList:
      - yq
    additionalRepos:
      - url: https://download.opensuse.org/repositories/openSUSE:Factory/standard
kubernetes:
  version: v1.28.7+rke2r1
  manifests:
    urls:
      - https://k8s.io/examples/application/nginx-app.yaml
  helm:
    charts:
      - name: kubevirt
        version: 0.2.2
        repositoryName: suse-edge
    repositories:
      - name: suse-edge
        url: https://suse-edge.github.io/charts
----

[NOTE]
====
Further examples of options such as multi-node deployments, networking, and Helm chart options/values can be seen https://github.com/suse-edge/edge-image-builder/blob/main/docs/building-images.md#operating-system[here] in the Edge Image Builder documentation.
====


==== Network Configuration

Lastly, for this quick-start example, let's set up a network device.

Within the `network` directory at `$EIB/network`, create a file named `host1.local.yaml` containing the following:

[,yaml]
----
routes:
  config:
  - destination: 0.0.0.0/0
    metric: 100
    next-hop-address: 192.168.122.1
    next-hop-interface: eth0
    table-id: 254
  - destination: 192.168.122.0/24
    metric: 100
    next-hop-address:
    next-hop-interface: eth0
    table-id: 254
dns-resolver:
  config:
    server:
    - 192.168.122.1
    - 8.8.8.8
interfaces:
- name: eth0
  type: ethernet
  state: up
  mac-address: 34:8A:B1:4B:16:E7
  ipv4:
    address:
    - ip: 192.168.122.50
      prefix-length: 24
    dhcp: false
    enabled: true
  ipv6:
    enabled: false
----

The resulting file structure should look like:
[,console]
----
├── eib-iso-definition.yaml
├── base-images/
│   └ slemicro.iso
├── network/
│   └ host1.local.yaml
└──
----

This will be turned into the necessary https://github.com/nmstate/nmstate[nmstate] configuration files when the image is built, which configures the RTD image's networking according to that file.

=== Building the image

To build the image, we can run:

[,bash]
----
podman run --rm -it --privileged -v $EIB:/eib \
eib:demo \
build --definition-file eib-iso-definition.yaml
----

The output of the command should be similar to:

[,console]
----
Setting up Podman API listener...
Generating image customization components...
Identifier ................... [SUCCESS]
Custom Files ................. [SKIPPED]
Time ......................... [SKIPPED]
Network ...................... [SUCCESS]
Groups ....................... [SKIPPED]
Users ........................ [SUCCESS]
Proxy ........................ [SKIPPED]
Resolving package dependencies...
Rpm .......................... [SUCCESS]
Systemd ...................... [SKIPPED]
Elemental .................... [SKIPPED]
Suma ......................... [SKIPPED]
Downloading file: dl-manifest-1.yaml 100% | (498/498 B, 4.2 MB/s)        
Embedded Artifact Registry ... [SUCCESS]
Keymap ....................... [SUCCESS]
Configuring Kubernetes component...
The Kubernetes CNI is not explicitly set, defaulting to 'cilium'.
Downloading file: rke2-images-core.linux-amd64.tar.zst 100% | (780/780 MB, 116 MB/s)        
Downloading file: rke2-images-cilium.linux-amd64.tar.zst 100% | (367/367 MB, 32 MB/s)         
Downloading file: rke2.linux-amd64.tar.gz 100% | (34/34 MB, 102 MB/s)        
Downloading file: sha256sum-amd64.txt 100% | (3.9/3.9 kB, 32 MB/s)        
Downloading file: dl-manifest-1.yaml 100% | (498/498 B, 6.8 MB/s)        
Kubernetes ................... [SUCCESS]
Certificates ................. [SKIPPED]
Building ISO image...
Kernel Params ................ [SKIPPED]
Image build complete.
----

The generated RTD `ISO` image will be created at `$EIB/eib-image.iso`:

[,console]
----
├── eib-iso-definition.yaml
├── eib-image.iso
├── _build
│    └ build-XYZ
├── base-images/
│    └ slemicro.iso
├── network/
└──
----

Additionally, each build creates a timestamped folder in `$EIB/_build/` that includes the logs of the build, the artifacts used during the build, and the `combustion` directory which contains all of the artifacts that are added to the RTD image.

The contents of this directory should look like:
[,console]
----
├── build-XYZ
├── combustion
│   │   ├── 05-configure-network.sh
│   │   ├── 10-rpm-install.sh
│   │   ├── 12-keymap-setup.sh
│   │   ├── 13b-add-users.sh
│   │   ├── 20-k8s-install.sh
│   │   ├── 26-embedded-registry.sh
│   │   ├── 48-message.sh
│   │   ├── hauler
│   │   ├── kubernetes
│   │   │   ├── images
│   │   │   │   ├── rke2-images-cilium.linux-amd64.tar.zst
│   │   │   │   └── rke2-images-core.linux-amd64.tar.zst
│   │   │   ├── install
│   │   │   │   ├── rke2.linux-amd64.tar.gz
│   │   │   │   └── sha256sum-amd64.txt
│   │   │   └── manifests
│   │   │       ├── dl-manifest-1.yaml
│   │   │       └── kubevirt.yaml
│   │   ├── network
│   │   │   ├── host1.local
│   │   │   │   └── eth0.nmconnection
│   │   │   └── host_config.yaml
│   │   ├── nmc
│   │   ├── registries.yaml
│   │   ├── registry
│   │   │   └── embedded-registry.tar.zst
│   │   ├── rke2_installer.sh
│   │   ├── rpm-repo
│   │   │   ├── addrepo0
│   │   │   │   └── x86_64
│   │   │   │       ├── ...
│   │   │   ├── repodata
│   │   │   │   ├── ...
│   │   │   └── zypper-success
│   │   ├── script
│   │   └── server.yaml
│   ├── createrepo.log
│   ├── eib-build.log
│   ├── embedded-registry.log
│   ├── hauler-manifest.yaml
│   ├── helm
│   │   └── kubevirt-0.2.2.tgz
│   ├── helm-pull.log
│   ├── helm-repo-add.log
│   ├── helm-template.log
│   ├── iso-build.log
│   ├── iso-build.sh
│   ├── iso-extract
│   │   ├── ...
│   ├── iso-extract.log
│   ├── iso-extract.sh
│   ├── modify-raw-image.sh
│   ├── network-config.log
│   ├── podman-image-build.log
│   ├── podman-system-service.log
│   ├── prepare-resolver-base-tarball-image.log
│   ├── prepare-resolver-base-tarball-image.sh
│   ├── raw-build.log
│   ├── raw-extract
│   │   ├── ...
│   └── resolver-image-build
│       ├──...
└── cache
    ├── ...
----

In the case of the build failing, `eib-build.log` is the first log that will contain information. From there, it will direct you to the component that failed for debugging.

=== Testing your newly built image

For instructions on how to test the newly build RTD image, refer to the https://github.com/suse-edge/edge-image-builder/blob/main/docs/testing-guide.md[EIB image testing guide].
