[#quickstart-eib]
= Standalone clusters with Edge Image Builder
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Edge Image Builder (EIB) is a tool that streamlines the process of generating customized, ready-to-boot (CRB) disk images for bootstrapping machines, even in air-gapped scenarios.

For more information, read the <<components-eib,Edge Image Builder Introduction>>.

== Prerequisites

* An x86_64 physical host (or virtual machine) running SLES 15 SP5 or openSUSE Leap 15.5
* An available container runtime (e.g. Podman)
* A copy of the SLE Micro 5.5 ISO image found https://www.suse.com/download/sle-micro/[here]

=== Getting the EIB Image

The EIB container image is publicly available and can be downloaded from the SUSE Edge registry by running:

[,shell]
----
podman pull registry.suse.com/edge/edge-image-builder:1.0.1
----

== Creating the image configuration directory

EIB containers require mounting a configuration directory from the host.
This directory must follow a specific structure. Let's create it:

[,shell]
----
export CONFIG_DIR=$HOME/eib
mkdir -p $CONFIG_DIR/base-images
----

We will now ensure that the downloaded base image copy is moved over to the configuration directory:

[,shell]
----
mv /path/to/downloads/SLE-Micro.x86_64-5.5.0-Default-SelfInstall-GM2.install.iso $CONFIG_DIR/base-images/slemicro.iso
----

> NOTE: EIB is never going to modify the base image input.

The configuration directory at this point should look like the following:

[,console]
----
└── base-images/
    └── slemicro.iso
----

== Creating the image definition file

The definition file describes the majority of configurable options that the Edge Image Builder supports.

[NOTE]
====
The following instructions outline a non-comprehensive example.
Please refer to the https://github.com/suse-edge/edge-image-builder/blob/main/docs/building-images.md[upstream building images guide] for details.
====

Let's start with a very basic definition file for our OS image:

[,console]
----
cat << EOF > $CONFIG_DIR/iso-definition.yaml
apiVersion: 1.0
image:
  imageType: iso
  arch: x86_64
  baseImage: slemicro.iso
  outputImageName: eib-image.iso
EOF
----

This definition specifies generating an image for an `x86_64` system. The base image to be modified is an `ISO` image named `slemicro.iso`,
expected to be located at `$CONFIG_DIR/base-images/slemicro.iso`. It also outlines that after EIB finishes modifying the image, the CRB image will be named `eib-image.iso`.

Now our directory structure should look like:
[,console]
----
├── iso-definition.yaml
└── base-images/
    └── slemicro.iso
----

=== Configuring OS Users

EIB allows us to preconfigure users with login information, such as passwords or SSH keys.

First, create an encrypted password:

[,console]
----
openssl passwd -6 SecurePassword
----

This will output something similar to:

[,console]
----
$6$G392FCbxVgnLaFw1$Ujt00mdpJ3tDHxEg1snBU3GjujQf6f8kvopu7jiCBIhRbRvMmKUqwcmXAKggaSSKeUUOEtCP3ZUoZQY7zTXnC1
----

We can then add a section in the definition file called `operatingSystem` with a `users` array inside it.
The resulting file should look like:

[,yaml]
----
apiVersion: 1.0
image:
  imageType: iso
  arch: x86_64
  baseImage: slemicro.iso
  outputImageName: eib-image.iso
operatingSystem:
  users:
    - username: root
      encryptedPassword: $6$G392FCbxVgnLaFw1$Ujt00mdpJ3tDHxEg1snBU3GjujQf6f8kvopu7jiCBIhRbRvMmKUqwcmXAKggaSSKeUUOEtCP3ZUoZQY7zTXnC1
----

=== Configuring RPM packages

EIB also allows us to preconfigure our CRB image with RPM packages.
It will automatically resolve and install all listed RPMs and their dependencies.

[NOTE]
====
More examples can be found in the https://github.com/suse-edge/edge-image-builder/blob/main/docs/installing-packages.md[upstream documentation].
====

We are going to install the `yq` RPM package found in the PackageHub repository:

[,yaml]
----
  packages:
    packageList:
      - yq
    additionalRepos:
      - url: https://download.opensuse.org/repositories/openSUSE:Factory/standard
----

The resulting definition file looks like:

[,yaml]
----
apiVersion: 1.0
image:
  imageType: iso
  arch: x86_64
  baseImage: slemicro.iso
  outputImageName: eib-image.iso
operatingSystem:
  users:
    - username: root
      encryptedPassword: $6$G392FCbxVgnLaFw1$Ujt00mdpJ3tDHxEg1snBU3GjujQf6f8kvopu7jiCBIhRbRvMmKUqwcmXAKggaSSKeUUOEtCP3ZUoZQY7zTXnC1
  packages:
    packageList:
      - yq
    additionalRepos:
      - url: https://download.opensuse.org/repositories/openSUSE:Factory/standard
----

[NOTE]
====
More operating system settings can be found in the https://github.com/suse-edge/edge-image-builder/blob/main/docs/building-images.md#operating-system[upstream documentation].
====

=== Configuring Kubernetes cluster and user workloads

Another feature of EIB is the simplified air-gapped deployment of Kubernetes clusters and bootstrapping application workloads via Helm charts and manifests.

We will be using the following addition to the definition file to instruct EIB to provision a single-node RKE2 Kubernetes cluster.
We are also going to install KubeVirt via the SUSE Edge Helm chart, as well as NGINX via a Kubernetes manifest.

[,yaml]
----
kubernetes:
  version: v1.28.8+rke2r1
  manifests:
    urls:
      - https://k8s.io/examples/application/nginx-app.yaml
  helm:
    charts:
      - name: kubevirt-chart
        version: 0.2.4
        repositoryName: suse-edge
    repositories:
      - name: suse-edge
        url: oci://registry.suse.com/edge
----

The resulting full definition file should now look like:
[,yaml]
----
apiVersion: 1.0
image:
  imageType: iso
  arch: x86_64
  baseImage: slemicro.iso
  outputImageName: eib-image.iso
operatingSystem:
  users:
    - username: root
      encryptedPassword: $6$G392FCbxVgnLaFw1$Ujt00mdpJ3tDHxEg1snBU3GjujQf6f8kvopu7jiCBIhRbRvMmKUqwcmXAKggaSSKeUUOEtCP3ZUoZQY7zTXnC1
  packages:
    packageList:
      - yq
    additionalRepos:
      - url: https://download.opensuse.org/repositories/openSUSE:Factory/standard
kubernetes:
  version: v1.28.8+rke2r1
  manifests:
    urls:
      - https://k8s.io/examples/application/nginx-app.yaml
  helm:
    charts:
      - name: kubevirt-chart
        version: 0.2.4
        repositoryName: suse-edge
    repositories:
      - name: suse-edge
        url: oci://registry.suse.com/edge
----

[NOTE]
====
Further examples of options such as multi-node deployments, networking, and Helm chart options/values can be seen https://github.com/suse-edge/edge-image-builder/blob/main/docs/building-images.md#kubernetes[upstream documentation].
====


=== Configuring the network

Lastly, for this quick start example, let us set up a network device.

[NOTE]
====
The following assumes a default `libvirt` network with an IP address range `192.168.122.1/24`.
Adjust accordingly if this differs in your environment.
====

Let's create a file describing the desired network state in the respective network directory:

[,console]
----
mkdir $CONFIG_DIR/network

cat << EOF > $CONFIG_DIR/network/host1.local.yaml
routes:
  config:
  - destination: 0.0.0.0/0
    metric: 100
    next-hop-address: 192.168.122.1
    next-hop-interface: eth0
    table-id: 254
  - destination: 192.168.122.0/24
    metric: 100
    next-hop-address:
    next-hop-interface: eth0
    table-id: 254
dns-resolver:
  config:
    server:
    - 192.168.122.1
    - 8.8.8.8
interfaces:
- name: eth0
  type: ethernet
  state: up
  mac-address: 34:8A:B1:4B:16:E7
  ipv4:
    address:
    - ip: 192.168.122.50
      prefix-length: 24
    dhcp: false
    enabled: true
  ipv6:
    enabled: false
EOF
----

[WARNING]
====
EIB networking is MAC address-dependent. In the case of virtual machines, you may be able to set the MAC address at boot.
For physical machines, you need to know the MAC address ahead of time.
====

The resulting file structure should look like:
[,console]
----
├── iso-definition.yaml
├── base-images/
│   └── slemicro.iso
└── network/  
    └── host1.local.yaml
----

The network configuration we just created will be parsed and converted to the necessary NetworkManager connection files.
These files will be applied during the provisioning of the host, resulting in a complete network configuration.

[NOTE]
====
Please refer to the <<components-nmc, Edge Networking component>> for comprehensive explanation and examples of this feature.
====

== Building the image

To build the image, we can run:

[,bash]
----
podman run --rm -it --privileged -v $CONFIG_DIR:/eib \
registry.suse.com/edge/edge-image-builder:1.0.1 \
build --definition-file iso-definition.yaml
----

The output of the command should be similar to:

[,console]
----
Setting up Podman API listener...
Generating image customization components...
Identifier ................... [SUCCESS]
Custom Files ................. [SKIPPED]
Time ......................... [SKIPPED]
Network ...................... [SUCCESS]
Groups ....................... [SKIPPED]
Users ........................ [SUCCESS]
Proxy ........................ [SKIPPED]
Resolving package dependencies...
Rpm .......................... [SUCCESS]
Systemd ...................... [SKIPPED]
Elemental .................... [SKIPPED]
Suma ......................... [SKIPPED]
Downloading file: dl-manifest-1.yaml 100%  (498/498 B, 5.9 MB/s)
Populating Embedded Artifact Registry... 100%  (3/3, 11 it/min)
Embedded Artifact Registry ... [SUCCESS]
Keymap ....................... [SUCCESS]
Configuring Kubernetes component...
The Kubernetes CNI is not explicitly set, defaulting to 'cilium'.
Downloading file: rke2_installer.sh
Downloading file: rke2-images-core.linux-amd64.tar.zst 100% (782/782 MB, 98 MB/s)
Downloading file: rke2-images-cilium.linux-amd64.tar.zst 100% (367/367 MB, 100 MB/s)
Downloading file: rke2.linux-amd64.tar.gz 100%  (34/34 MB, 101 MB/s)
Downloading file: sha256sum-amd64.txt 100%  (3.9/3.9 kB, 1.5 MB/s)
Downloading file: dl-manifest-1.yaml 100%  (498/498 B, 7.2 MB/s)
Kubernetes ................... [SUCCESS]
Certificates ................. [SKIPPED]
Building ISO image...
Kernel Params ................ [SKIPPED]
Image build complete!
----

The built ISO image is stored at `$CONFIG_DIR/eib-image.iso`:

[,console]
----
├── iso-definition.yaml
├── eib-image.iso
├── _build
│   └── cache/
│       └── ...
│   └── build-<timestamp>/
│       └── ...
├── base-images/
│   └── slemicro.iso
└── network/
    └── host1.local.yaml
----

Each build creates a time-stamped folder in `$CONFIG_DIR/_build/` that includes the logs of the build, the artifacts used during the build,
and the `combustion` and `artefacts` directories which contain all the scripts and artifacts that are added to the CRB image.

The contents of this directory should look like:
[,console]
----
├── build-<timestamp>/
│   │── combustion/
│   │   ├── 05-configure-network.sh
│   │   ├── 10-rpm-install.sh
│   │   ├── 12-keymap-setup.sh
│   │   ├── 13b-add-users.sh
│   │   ├── 20-k8s-install.sh
│   │   ├── 26-embedded-registry.sh
│   │   ├── 48-message.sh
│   │   ├── network/
│   │   │   ├── host1.local/
│   │   │   │   └── eth0.nmconnection
│   │   │   └── host_config.yaml
│   │   ├── nmc
│   │   └── script
│   │── artefacts/
│   │   │── registry/
│   │   │   ├── hauler
│   │   │   ├── nginx:1.14.2-registry.tar.zst
│   │   │   ├── rancher_kubectl:v1.28.7-registry.tar.zst
│   │   │   └── registry.suse.com_suse_sles_15.5_virt-operator:1.1.1-150500.8.12.1-registry.tar.zst
│   │   │── rpms/
│   │   │   ├── rpm-repo
│   │   │   │   ├── addrepo0
│   │   │   │   │   └── x86_64
│   │   │   │   │       ├── ...
│   │   │   │   ├── repodata
│   │   │   │   │   ├── ...
│   │   │   │   └── zypper-success
│   │   │── kubernetes/
│   │   │   ├── rke2_installer.sh
│   │   │   ├── registries.yaml
│   │   │   ├── server.yaml
│   │   │   ├── images/
│   │   │   │   ├── rke2-images-cilium.linux-amd64.tar.zst
│   │   │   │   └── rke2-images-core.linux-amd64.tar.zst
│   │   │   ├── install/
│   │   │   │   ├── rke2.linux-amd64.tar.gz
│   │   │   │   └── sha256sum-amd64.txt
│   │   │   └── manifests/
│   │   │       ├── dl-manifest-1.yaml
│   │   │       └── kubevirt-chart.yaml
│   ├── createrepo.log
│   ├── eib-build.log
│   ├── embedded-registry.log
│   ├── helm
│   │   └── kubevirt-chart
│   │       └── kubevirt-0.2.4.tgz
│   ├── helm-pull.log
│   ├── helm-template.log
│   ├── iso-build.log
│   ├── iso-build.sh
│   ├── iso-extract
│   │   ├── ...
│   ├── iso-extract.log
│   ├── iso-extract.sh
│   ├── modify-raw-image.sh
│   ├── network-config.log
│   ├── podman-image-build.log
│   ├── podman-system-service.log
│   ├── prepare-resolver-base-tarball-image.log
│   ├── prepare-resolver-base-tarball-image.sh
│   ├── raw-build.log
│   ├── raw-extract
│   │   ├── ...
│   └── resolver-image-build
│       ├──...
└── cache
    ├── ...
----

If the build fails, `eib-build.log` is the first log that contains information.
From there, it will direct you to the component that failed for debugging.

== Debugging the image build process

If the image build process fails, refer to the https://github.com/suse-edge/edge-image-builder/blob/main/docs/debugging.md[upstream debugging guide].

== Testing your newly built image

For instructions on how to test the newly built CRB image, refer to the https://github.com/suse-edge/edge-image-builder/blob/main/docs/testing-guide.md[upstream image testing guide].
